
DROP TABLE IVOLACTDIR CASCADE CONSTRAINTS ;

CREATE TABLE IVOLACTDIR (
  VOLID     NUMBER (10)   NOT NULL,
  ACTDIR    NUMBER (10)   NOT NULL,
  NUMFILES  NUMBER (10)   NOT NULL ) ;


CREATE UNIQUE INDEX IVOLACTDIR1 ON
  IVOLACTDIR(VOLID)
;


DROP TABLE IVOLARCHLIST CASCADE CONSTRAINTS ;

CREATE TABLE IVOLARCHLIST (
  ARCHID  NUMBER (10)   NOT NULL,
  LISTID  NUMBER (10)   NOT NULL ) ;


CREATE UNIQUE INDEX IVOLARCHLIST1 ON
  IVOLARCHLIST(ARCHID)
;

CREATE INDEX IVOLARCHLIST2 ON
  IVOLARCHLIST(LISTID)
;


DROP TABLE IVOLFILEFTS CASCADE CONSTRAINTS ;

CREATE TABLE IVOLFILEFTS (
  ID         NUMBER (10)   NOT NULL,
  EXTID1     NUMBER (10)   NOT NULL,
  EXTID2     NUMBER (10)   NOT NULL,
  EXTID3     NUMBER (10)   NOT NULL,
  EXTID4     NUMBER (10)   NOT NULL,
  PATH       VARCHAR2 (254)  NOT NULL,
  TIMESTAMP  DATE          NOT NULL ) ;


CREATE UNIQUE INDEX IVOLFILEFTS1 ON
  IVOLFILEFTS(ID)
;


DROP TABLE IVOLFILEHDR CASCADE CONSTRAINTS ;

CREATE TABLE IVOLFILEHDR (
  ID         NUMBER (10)   NOT NULL,
  VOLID      NUMBER (10)   NOT NULL,
  LOC        VARCHAR2 (254)  NOT NULL,
  EXTID1     NUMBER (10)   NOT NULL,
  EXTID2     NUMBER (10)   NOT NULL,
  EXTID3     NUMBER (10)   NOT NULL,
  FLAGS      NUMBER (10)   NOT NULL,
  STAT       NUMBER (10)   NOT NULL,
  TIMESTAMP  DATE,
  FILESIZE   NUMBER (20,4) NOT NULL ) ;


CREATE UNIQUE INDEX IVOLFILEHDR1 ON
  IVOLFILEHDR(ID)
;

CREATE INDEX IVOLFILEHDR2 ON
  IVOLFILEHDR(VOLID)
;


DROP TABLE IVOLLISTHDR CASCADE CONSTRAINTS ;

CREATE TABLE IVOLLISTHDR (
  ID        NUMBER (10)   NOT NULL,
  NAME      VARCHAR2 (32)  NOT NULL,
  FLAGS     NUMBER (10)   NOT NULL,
  STAT      NUMBER (10)   NOT NULL,
  REMARKS   VARCHAR2 (254),
  CRTRID    NUMBER (10)   NOT NULL,
  CRTNDATE  DATE          NOT NULL,
  UPDRID    NUMBER (10),
  UPDDATE   DATE ) ;


CREATE UNIQUE INDEX IVOLLISTHDR1 ON
  IVOLLISTHDR(ID)
;


DROP TABLE IVOLLISTVOL CASCADE CONSTRAINTS ;

CREATE TABLE IVOLLISTVOL (
  LISTID     NUMBER (10)   NOT NULL,
  VOLID      NUMBER (10)   NOT NULL,
  SORTORDER  NUMBER (10)   NOT NULL ) ;


CREATE INDEX IVOLLISTVOL1 ON
  IVOLLISTVOL(LISTID)
;

CREATE INDEX IVOLLISTVOL2 ON
  IVOLLISTVOL(VOLID)
;


DROP TABLE IVOLNEXTID CASCADE CONSTRAINTS ;

CREATE TABLE IVOLNEXTID (
  TYPE  NUMBER (10)   NOT NULL,
  ID    NUMBER (10)   NOT NULL ) ;


CREATE UNIQUE INDEX IVOLNEXTID1 ON
  IVOLNEXTID(TYPE)
;


DROP TABLE IVOLREPHDR CASCADE CONSTRAINTS ;

CREATE TABLE IVOLREPHDR (
  ID        NUMBER (10)   NOT NULL,
  NAME      VARCHAR2 (32)  NOT NULL,
  TYPE      NUMBER (10)   NOT NULL,
  INFO      CLOB          NOT NULL,
  STAT      NUMBER (10)   NOT NULL,
  REMARKS   VARCHAR2 (254),
  CRTRID    NUMBER (10)   NOT NULL,
  CRTNDATE  DATE          NOT NULL,
  UPDRID    NUMBER (10),
  UPDDATE   DATE ) ;


CREATE UNIQUE INDEX IVOLREPHDR1 ON
  IVOLREPHDR(ID)
;


DROP TABLE IVOLVOLHDR CASCADE CONSTRAINTS ;

CREATE TABLE IVOLVOLHDR (
  ID        NUMBER (10)   NOT NULL,
  NAME      VARCHAR2 (32)  NOT NULL,
  REPID     NUMBER (10)   NOT NULL,
  INFO      CLOB          NOT NULL,
  ITEMP     NUMBER (10)   NOT NULL,
  ACTSIZE   VARCHAR2 (32)  NOT NULL,
  NUMFILES  NUMBER (10)   NOT NULL,
  STAT      NUMBER (10)   NOT NULL,
  REMARKS   VARCHAR2 (254),
  CRTRID    NUMBER (10)   NOT NULL,
  CRTNDATE  DATE          NOT NULL,
  UPDRID    NUMBER (10),
  UPDDATE   DATE ) ;


CREATE UNIQUE INDEX IVOLVOLHDR1 ON
  IVOLVOLHDR(ID)
;

CREATE INDEX IVOLVOLHDR2 ON
  IVOLVOLHDR(REPID)
;

DROP TABLE IVOLVOLTBL CASCADE CONSTRAINTS ;

CREATE TABLE IVOLVOLTBL (
  LOCID    VARCHAR2 (32)  NOT NULL,
  EXTID1   NUMBER (10)   NOT NULL,
  EXTID2   NUMBER (10)   NOT NULL,
  EXTID3   NUMBER (10)   NOT NULL,
  EXTID4   NUMBER (10)   NOT NULL,
  FILEEXT  VARCHAR2 (10)  NOT NULL,
  FILEVAL  LONG RAW      NOT NULL ) ;


CREATE UNIQUE INDEX IVOLVOLTBL1 ON
  IVOLVOLTBL(LOCID)
;

CREATE INDEX IVOLVOLTBLFTS ON IVOLVOLTBL
(FILEVAL)
INDEXTYPE IS CTXSYS.CONTEXT;

INSERT INTO IVOLACTDIR ( VOLID, ACTDIR, NUMFILES ) VALUES (
1, 1, 0);
commit;

INSERT INTO IVOLLISTHDR ( ID, NAME, FLAGS, STAT, REMARKS, CRTRID, CRTNDATE, UPDRID,
UPDDATE ) VALUES (
6, 'ListBD', 0, 0, NULL, 0,  TO_Date( '07/03/2007 09:38:42 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL);
commit;

INSERT INTO IVOLLISTVOL ( LISTID, VOLID, SORTORDER ) VALUES (
6, 1, 1);
commit;

INSERT INTO IVOLNEXTID ( TYPE, ID ) VALUES (
1, 7);
INSERT INTO IVOLNEXTID ( TYPE, ID ) VALUES (
2, 7);
INSERT INTO IVOLNEXTID ( TYPE, ID ) VALUES (
3, 7);
INSERT INTO IVOLNEXTID ( TYPE, ID ) VALUES (
4, 130);
commit;

INSERT INTO IVOLVOLHDR ( ID, NAME, REPID, INFO, ITEMP, ACTSIZE, NUMFILES, STAT, REMARKS, CRTRID, CRTNDATE,
UPDRID, UPDDATE ) VALUES (
1, 'RepBD', 1, '(CLOB)', 0, '0', 0, 0, NULL, 0,  TO_Date( '07/03/2007 09:38:31 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 0,  TO_Date( '07/03/2007 09:38:31 AM', 'MM/DD/YYYY HH:MI:SS AM'));
commit;

INSERT INTO IVOLREPHDR ( ID, NAME, TYPE, INFO, STAT, REMARKS, CRTRID, CRTNDATE, UPDRID,
UPDDATE ) VALUES (
1, 'RepBD', 5, '(CLOB)', 0, NULL, 0,  TO_Date( '07/03/2007 09:38:31 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, NULL);
commit;
