-- /***************************/
-- /* Actualización 4.7->4.8  */
-- /***************************/

INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.8',getdate());

--Fecha devolución en prorroga
ALTER TABLE ASGPPRORROGA ADD FECHAFINPRORROGA DATETIME;

--Motivo por el cual se solicita la prorroga
ALTER TABLE ASGPPRORROGA ADD MOTIVOPRORROGA VARCHAR(512);

IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ASGFELIMSELUDOCF]') AND name = N'ASGFELIMSELUDOC1')
DROP INDEX [ASGFELIMSELUDOC1] ON [dbo].[ASGFELIMSELUDOC] WITH ( ONLINE = OFF )

IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ASGFELIMSELUDOCF]') AND name = N'ASGFELIMSELUDOC2')
DROP INDEX [ASGFELIMSELUDOC2] ON [dbo].[ASGFELIMSELUDOC] WITH ( ONLINE = OFF )

--Modificar el nombre de la tabla ASGFELIMSELUDOC por ASGFELIMUDOCCONS
EXEC sp_rename 'ASGFELIMSELUDOC', 'ASGFELIMUDOCCONS';
GO

-- Tabla: ASGFELIMSELUDOC
CREATE INDEX ASGFELIMUDOCCONS1 ON ASGFELIMUDOCCONS (IDELIMINACION);
CREATE INDEX ASGFELIMUDOCCONS2 ON ASGFELIMUDOCCONS (IDUDOC);
GO

CREATE TABLE ASGFELIMSELUDOC(
	IDELIMINACION VARCHAR(32) NOT NULL,
	IDUDOC VARCHAR(32) NOT NULL,
	IDFONDO VARCHAR(32),
	CODREFERENCIA VARCHAR(1024),
	CODIGO VARCHAR(128),
	SIGNATURAUDOC VARCHAR(32),
	EXPEDIENTEUDOC VARCHAR(256),
	TITULO VARCHAR(1024),
	CODSISTPRODUCTOR VARCHAR(16),
	TIPODOCUMENTAL VARCHAR(254),
	IDUINSTALACION VARCHAR(32),
	UBICACION VARCHAR(512),
	FECHAINIUDOC DATETIME,
	FECHAFINUDOC DATETIME,
	NUMERO VARCHAR(10)

);
GO
-- Tabla: ASGFELIMSELUDOC
CREATE INDEX ASGFELIMSELUDOC1 ON ASGFELIMSELUDOC (IDELIMINACION);
CREATE INDEX ASGFELIMSELUDOC2 ON ASGFELIMSELUDOC (IDUDOC);

-- Tabla: ASGFUNIDADDOC4
CREATE INDEX ASGFUNIDADDOC4 ON ASGFUNIDADDOC(IDFONDO);
