-- /***************************/
-- /* Versión 4.8 -> 5.0      */
-- /***************************/

INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.8->5.0',getdate());

--Renombrar IDLVOLPREF a IDREPECMPREF
EXEC sp_rename
		@objname = 'ADCTLGLISTAD.IDLVOLPREF',
		@newname = 'IDREPECMPREF',
		@objtype = 'COLUMN';
GO

--Renombrar IDLVOL a IDREPECM
EXEC sp_rename
		@objname = 'ADDESCRIPTOR.IDLVOL',
		@newname = 'IDREPECM',
		@objtype = 'COLUMN';
GO

--Renombrar IDLVOL a IDREPECM
EXEC sp_rename
		@objname = 'ASGFELEMENTOCF.IDLVOL',
		@newname = 'IDREPECM',
		@objtype = 'COLUMN';
GO

--Renombrar IDLVOLPREF a IDREPECMPREF
EXEC sp_rename
		@objname = 'ASGFNIVELCF.IDLVOLPREF',
		@newname = 'IDREPECMPREF',
		@objtype = 'COLUMN';
GO

--Renombrar INFOFICHAUDOCLVOL a INFOFICHAUDOCREPECM
EXEC sp_rename
		@objname = 'ASGFSERIE.INFOFICHAUDOCLVOL',
		@newname = 'INFOFICHAUDOCREPECM',
		@objtype = 'COLUMN';
GO

--Añadir idRepECm
ALTER TABLE ADOCDOCUMENTODESCR ADD IDREPECM VARCHAR(32);
ALTER TABLE ADOCDOCUMENTOCF ADD IDREPECM VARCHAR(32);
ALTER TABLE ADPCDOCUMENTOVIT ADD IDREPECM VARCHAR(32);

--Establecer el campo IDMOTIVO como NULL
ALTER TABLE ASGPCONSULTA ALTER COLUMN IDMOTIVO VARCHAR(32) NULL;

--Cambiar Tamaño de IDFICH a 128
ALTER TABLE ADPCDOCUMENTOVIT ALTER COLUMN IDFICH VARCHAR(128);

--Añadir el campo subtiponivel
ALTER TABLE ADFICHA ADD SUBTIPONIVEL INT  DEFAULT 0 NOT NULL;

--Actualizar los valores de subtiponivel
UPDATE ADFICHA SET SUBTIPONIVEL=61 WHERE ID='1';
UPDATE ADFICHA SET SUBTIPONIVEL=62 WHERE ID='6';


CREATE INDEX ASGFELEMENTOCF8 ON ASGFELEMENTOCF (ESTADO, IDNIVEL) INCLUDE (CODREFERENCIA);
CREATE INDEX ASGFELEMENTOCF9 ON ASGFELEMENTOCF (ESTADO, IDNIVEL) INCLUDE (ID, CODREFERENCIA);
CREATE INDEX ASGFELEMENTOCF10 ON ASGFELEMENTOCF (IDNIVEL, ESTADO) INCLUDE (ID, CODREFERENCIA);
CREATE INDEX ASGFELEMENTOCF11 ON ASGFELEMENTOCF (IDNIVEL, IDPADRE, ESTADO) INCLUDE (ID);
CREATE INDEX ASGFELEMENTOCF12 ON ASGFELEMENTOCF (IDPADRE, ESTADO) INCLUDE (ID, IDNIVEL);
CREATE INDEX ASGFELEMENTOCF13 ON ASGFELEMENTOCF (IDNIVEL, IDPADRE, ESTADO) INCLUDE (ID, TIPO, CODIGO, TITULO, IDFONDO, CODREFFONDO, FINALCODREFPADRE, CODREFERENCIA, IDELIMINACION, IDFICHADESCR, TIENEDESCR, EDITCLFDOCS, IDREPECM, IDARCHIVO, NIVELACCESO, IDLCA, SUBTIPO, ORDPOS);
CREATE INDEX ASGFELEMENTOCF14 ON ASGFELEMENTOCF (IDPADRE, ESTADO) INCLUDE (ID, TIPO, IDNIVEL, CODIGO, TITULO, IDFONDO, CODREFFONDO, FINALCODREFPADRE, CODREFERENCIA, IDELIMINACION, IDFICHADESCR, TIENEDESCR, EDITCLFDOCS, IDREPECM, IDARCHIVO, NIVELACCESO, IDLCA, SUBTIPO, ORDPOS);

CREATE INDEX ASGFUNIDADDOC4 ON ASGFUNIDADDOC (IDFONDO);

CREATE INDEX ADVCFECHACF6 ON ADVCFECHACF (IDCAMPO) INCLUDE (IDELEMENTOCF);
CREATE INDEX ADVCFECHACF7 ON ADVCFECHACF (IDCAMPO) INCLUDE (IDELEMENTOCF, FECHAINI);
CREATE INDEX ADVCFECHACF8 ON ADVCFECHACF (IDCAMPO) INCLUDE (IDELEMENTOCF, FECHAFIN);

CREATE INDEX ASGDUDOCENUI5 ON ASGDUDOCENUI (SIGNATURAUDOC);

CREATE INDEX ASGFSERIE5 ON ASGFSERIE (IDUSRGESTOR, ESTADOSERIE);

CREATE INDEX ASGFDIVISIONFS2 ON ASGFDIVISIONFS (IDUSRGESTOR, ESTADO);

CREATE INDEX ASGPCONSULTA5 ON ASGPCONSULTA (ESTADO) INCLUDE (NUSRCONSULTOR, IDARCHIVO);
CREATE INDEX ASGPCONSULTA6 ON ASGPCONSULTA (ESTADO) INCLUDE (NORGCONSULTOR, IDARCHIVO);

CREATE INDEX ASGFUDOCENDIVISIONFS2 ON ASGFUDOCENDIVISIONFS (IDUDOC);

--Nuevo Indice por etiquetaxml en campo tabla
CREATE UNIQUE INDEX ADCAMPOTBL5 ON ADCAMPOTBL (ETIQUETAXML);

UPDATE ADCAMPODATO SET ETIQUETAXML = 'Documento_Fisico_Descripcion' WHERE ID='43' AND ETIQUETAXML = 'Descripcion';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Documento_Electronico_Descripcion' WHERE ID='50' AND ETIQUETAXML = 'Descripcion';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Identificacion' WHERE ID='1' AND ETIQUETAXML = 'Identificador';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Identificador_Recurso' WHERE ID='131' AND ETIQUETAXML = 'Identificador';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Entidad_Relacionada_Nombre' WHERE ID='114' AND ETIQUETAXML = 'Nombre';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Documento_Fisico_Nombre' WHERE ID='19' AND ETIQUETAXML = 'Nombre';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Productor_Nombre' WHERE ID='34' AND ETIQUETAXML = 'Nombre';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Documento_Electronico_Nombre' WHERE ID='49' AND ETIQUETAXML = 'Nombre';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Entidad_Relacionada_Tipo_Relacion' WHERE ID='115' AND ETIQUETAXML = 'Tipo_Relacion';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Naturaleza_Relacion' WHERE ID='133' AND ETIQUETAXML = 'Tipo_Relacion';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Interesado_Validado' WHERE ID='12' AND ETIQUETAXML = 'Validado';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Emplazamiento_Validado' WHERE ID='212' AND ETIQUETAXML = 'Validado';

--Nuevo Indice por etiquetaxml en campo dato
CREATE UNIQUE INDEX ADCAMPODATO6 ON ADCAMPODATO (ETIQUETAXML);

--Modificado el tamaño del nombre del formato
ALTER TABLE ADFMTFICHA ALTER COLUMN NOMBRE VARCHAR(128) NOT NULL;
