spool 02_create_indexes.log

-------------
-- SISTEMA --
-------------
-- Tabla: AGARCHIVO
CREATE UNIQUE INDEX AGARCHIVO1 ON AGARCHIVO(ID) TABLESPACE &1;

-- Tabla: AGNIVELARCHIVO
CREATE UNIQUE INDEX AGNIVELARCHIVO01 ON AGNIVELARCHIVO(ID) TABLESPACE &1;
CREATE INDEX AGNIVELARCHIVO02 ON AGNIVELARCHIVO(ORDEN) TABLESPACE &1;

-- Tabla: AGOBJBLOQUEO
CREATE UNIQUE INDEX AGOBJBLOQUEO1 ON AGOBJBLOQUEO(TIPOOBJ, IDOBJ, MODULO) TABLESPACE &1;

-- Tabla: AGINFOSISTEMA
CREATE UNIQUE INDEX AGINFOSISTEMA1 ON AGINFOSISTEMA(AUTID) TABLESPACE &1;

-----------------------
-- CONTROL DE ACCESO --
-----------------------

-- Tabla: ASCAORGANO
CREATE UNIQUE INDEX ASCAORGANO1 ON ASCAORGANO (ID) TABLESPACE &1;
CREATE INDEX ASCAORGANO2 ON ASCAORGANO (CODIGO) TABLESPACE &1;
CREATE INDEX ASCAORGANO3 ON ASCAORGANO (SISTEXTGESTOR, IDORGSEXTGESTOR) TABLESPACE &1;

-- Tabla: ASCAUSRORG
CREATE INDEX ASCAUSRORG1 ON ASCAUSRORG (IDUSUARIO) TABLESPACE &1;

-- Tabla:  ASCAGRUPO
CREATE UNIQUE INDEX ASCAGRUPO1 ON ASCAGRUPO (ID) TABLESPACE &1;
CREATE UNIQUE INDEX ASCAGRUPO2 ON ASCAGRUPO (NOMBRE) TABLESPACE &1;

-- Tabla: ASCAUSRGRP
CREATE INDEX ASCAUSRGRP1 ON ASCAUSRGRP (IDUSUARIO) TABLESPACE &1;
CREATE INDEX ASCAUSRGRP2 ON ASCAUSRGRP (IDGRUPO) TABLESPACE &1;

-- Tabla: ASCAUSUARIO
CREATE UNIQUE INDEX ASCAUSUARIO1 ON ASCAUSUARIO (ID) TABLESPACE &1;

-- Tabla: ASCAROL
CREATE UNIQUE INDEX ASCAROL1 ON ASCAROL (ID) TABLESPACE &1;
CREATE INDEX ASCAROL2 ON ASCAROL (NOMBRE) TABLESPACE &1;

-- Tabla: ASCAPERMGENROL
CREATE INDEX ASCAPERMGENROL1 ON ASCAPERMGENROL (IDROL) TABLESPACE &1;
CREATE INDEX ASCAPERMGENROL2 ON ASCAPERMGENROL (PERM) TABLESPACE &1;

-- Tabla: ASCAROLUSR
CREATE INDEX ASCAROLUSR1 ON ASCAROLUSR (IDUSUARIO) TABLESPACE &1;
CREATE UNIQUE INDEX ASCAROLUSR2 ON ASCAROLUSR (IDROL, IDUSUARIO) TABLESPACE &1;

-- Tabla: ASCALISTCA
CREATE UNIQUE INDEX ASCALISTCA1 ON ASCALISTCA (ID) TABLESPACE &1;
CREATE UNIQUE INDEX ASCALISTCA2 ON ASCALISTCA (NOMBRE) TABLESPACE &1;

-- Tabla: ASCAPERMLISTCA
CREATE INDEX ASCAPERMLISTCA1 ON ASCAPERMLISTCA (IDLISTCA) TABLESPACE &1;
CREATE INDEX ASCAPERMLISTCA2 ON ASCAPERMLISTCA (TIPODEST, IDDEST) TABLESPACE &1;
CREATE INDEX ASCAPERMLISTCA3 ON ASCAPERMLISTCA (TIPODEST, IDDEST, IDLISTCA) TABLESPACE &1;

--------------------
-- TRANSFERENCIAS --
--------------------

-- Tabla: ASGTPREVISION
CREATE UNIQUE INDEX ASGTPREVISION1	ON ASGTPREVISION (ID) TABLESPACE &1;
CREATE INDEX ASGTPREVISION2	ON ASGTPREVISION (TIPOTRANSFERENCIA) TABLESPACE &1;
CREATE INDEX ASGTPREVISION3	ON ASGTPREVISION (ESTADO) TABLESPACE &1;
CREATE INDEX ASGTPREVISION4	ON ASGTPREVISION (ANO) TABLESPACE &1;
CREATE INDEX ASGTPREVISION5	ON ASGTPREVISION (IDUSRGESTOR) TABLESPACE &1;

-- Tabla:  ASGTDETALLEPREV
CREATE UNIQUE INDEX ASGTDETALLEPREV1 ON ASGTDETALLEPREV (ID) TABLESPACE &1;
CREATE INDEX ASGTDETALLEPREV2 ON ASGTDETALLEPREV (IDPREVISION) TABLESPACE &1;

-- Tabla: ASGTRENTREGA
CREATE UNIQUE INDEX ASGTRENTREGA1 ON ASGTRENTREGA (ID) TABLESPACE &1;
CREATE INDEX ASGTRENTREGA2 ON ASGTRENTREGA (TIPOTRANSFERENCIA) TABLESPACE &1;
CREATE INDEX ASGTRENTREGA3 ON ASGTRENTREGA (ESTADO) TABLESPACE &1;
CREATE INDEX ASGTRENTREGA4 ON ASGTRENTREGA (ANO) TABLESPACE &1;
CREATE INDEX ASGTRENTREGA5 ON ASGTRENTREGA (IDUSRGESTORREM) TABLESPACE &1;
CREATE INDEX ASGTRENTREGA6 ON ASGTRENTREGA (IDUSRGESTORARCHIVOREC) TABLESPACE &1;

-- Tabla: ASGTSNSEC
CREATE UNIQUE INDEX ASGTSNSEC1 ON ASGTSNSEC (TIPO, ANO, IDARCHIVO) TABLESPACE &1;

-- Tabla: ASGTUNIDADDOCRE
CREATE UNIQUE INDEX ASGTUNIDADDOCRE1 ON ASGTUNIDADDOCRE (ID) TABLESPACE &1;
CREATE INDEX ASGTUNIDADDOCRE2 ON ASGTUNIDADDOCRE (IDRELENTREGA) TABLESPACE &1;
CREATE INDEX ASGTUNIDADDOCRE3 ON ASGTUNIDADDOCRE (TIPOTRANSFERENCIA, NUMEXP) TABLESPACE &1;
CREATE INDEX ASGTUNIDADDOCRE4 ON ASGTUNIDADDOCRE (SINDOCSFISICOS) TABLESPACE &1;

--Tabla: ASGTUINSTALACIONRE
CREATE UNIQUE INDEX ASGTUINSTALACIONRE1 ON ASGTUINSTALACIONRE (ID) TABLESPACE &1;
CREATE INDEX ASGTUINSTALACIONRE2 ON ASGTUINSTALACIONRE (IDRELENTREGA) TABLESPACE &1;

--Tabla: ASGTUINSTALACIONREEA
CREATE INDEX ASGTUINSTALACIONREEA1 ON ASGTUINSTALACIONREEA (IDUIDEPOSITO) TABLESPACE &1;
CREATE INDEX ASGTUINSTALACIONREEA2 ON ASGTUINSTALACIONREEA (IDRELENTREGA) TABLESPACE &1;

-- Tabla: ASGTUDOCENUI
CREATE INDEX ASGTUDOCENUI1 ON ASGTUDOCENUI (IDRELENTREGA) TABLESPACE &1;
CREATE INDEX ASGTUDOCENUI2 ON ASGTUDOCENUI (IDUINSTALACIONRE) TABLESPACE &1;
CREATE INDEX ASGTUDOCENUI3 ON ASGTUDOCENUI (IDUNIDADDOC, IDUINSTALACIONRE) TABLESPACE &1;

-- Tabla: AGFORMATO
CREATE UNIQUE INDEX AGFORMATO1 ON AGFORMATO (ID) TABLESPACE &1;
CREATE INDEX AGFORMATO2 ON AGFORMATO (VIGENTE) TABLESPACE &1;

-- Tabla: ASGTUDOCSDF
CREATE UNIQUE INDEX ASGTUDOCSDF1 ON ASGTUDOCSDF (ID) TABLESPACE &1;
CREATE UNIQUE INDEX ASGTUDOCSDF2 ON ASGTUDOCSDF (ID, IDRELENTREGA) TABLESPACE &1;

--------------
-- DEPOSITO --
--------------

-- Tabla: ASGDTIPOELEMENTO
CREATE UNIQUE INDEX ASGDTIPOELEMENTO1 ON ASGDTIPOELEMENTO (ID) TABLESPACE &1;
CREATE UNIQUE INDEX ASGDTIPOELEMENTO2 ON ASGDTIPOELEMENTO (NOMBRE) TABLESPACE &1;

-- Tabla: ASGDDEPOSITO
CREATE UNIQUE INDEX ASGDDEPOSITO1 ON ASGDDEPOSITO (ID) TABLESPACE &1;
CREATE UNIQUE INDEX ASGDDEPOSITO2 ON ASGDDEPOSITO (NOMBRE) TABLESPACE &1;

-- Tabla: ASGDDEPOSITOELECTRONICO
CREATE UNIQUE INDEX ASGDDEPOSITOELECTRONICO1 ON ASGDDEPOSITOELECTRONICO (ID) TABLESPACE &1;

-- Tabla: ASGDELEMNOASIG
CREATE UNIQUE INDEX ASGDELEMNOASIG1 ON ASGDELEMNOASIG (ID) TABLESPACE &1;
CREATE INDEX ASGDELEMNOASIG2 ON ASGDELEMNOASIG (IDPADRE) TABLESPACE &1;
CREATE UNIQUE INDEX ASGDELEMNOASIG3 ON ASGDELEMNOASIG (CODORDEN, IDDEPOSITO) TABLESPACE &1;

-- Tabla: ASGDELEMASIG
CREATE UNIQUE INDEX ASGDELEMASIG1 ON ASGDELEMASIG (ID) TABLESPACE &1;
CREATE INDEX ASGDELEMASIG2 ON ASGDELEMASIG (IDELEMNAPADRE) TABLESPACE &1;
CREATE INDEX ASGDELEMASIG3 ON ASGDELEMASIG (IDDEPOSITO) TABLESPACE &1;
CREATE UNIQUE INDEX ASGDELEMASIG4 ON ASGDELEMASIG (CODORDEN, IDDEPOSITO) TABLESPACE &1;

-- Tabla: ASGDHUECO
CREATE UNIQUE INDEX ASGDHUECO1 ON ASGDHUECO (IDELEMAPADRE, NUMORDEN) TABLESPACE &1;
CREATE INDEX ASGDHUECO2 ON ASGDHUECO (IDELEMAPADRE) TABLESPACE &1;
CREATE INDEX ASGDHUECO3 ON ASGDHUECO (IDDEPOSITO) TABLESPACE &1;
CREATE INDEX ASGDHUECO4 ON ASGDHUECO (ESTADO) TABLESPACE &1;
CREATE INDEX ASGDHUECO5 ON ASGDHUECO (ESTADO, IDDEPOSITO) TABLESPACE &1;
CREATE INDEX ASGDHUECO6 ON ASGDHUECO (ESTADO, IDFORMATO) TABLESPACE &1;
CREATE INDEX ASGDHUECO7 ON ASGDHUECO (CODORDEN, TIPOORD) TABLESPACE &1;
CREATE UNIQUE INDEX ASGDHUECO8 ON ASGDHUECO (CODORDEN, IDDEPOSITO) TABLESPACE &1;

-- Tabla: ASGDSIGNUMORDEN
CREATE UNIQUE INDEX SIGNUMORDEN1 ON ASGDSIGNUMORDEN (IDTIPOELEMPADRE, IDELEMPADRE, IDTIPOELEMENTO) TABLESPACE &1;

-- Tabla: ASGDUINSTALACION
CREATE UNIQUE INDEX ASGDUINSTALACION1 ON ASGDUINSTALACION (ID) TABLESPACE &1;
CREATE INDEX ASGDUINSTALACION2 ON ASGDUINSTALACION (SIGNATURAUI) TABLESPACE &1;
CREATE INDEX ASGDUINSTALACION3 ON ASGDUINSTALACION (IDENTIFICACION) TABLESPACE &1;

-- Tabla: ASGDHISTUINSTALACION
CREATE UNIQUE INDEX ASGDHISTUINSTALACION1 ON ASGDHISTUINSTALACION(ID) TABLESPACE &1;
CREATE INDEX ASGDHISTUINSTALACION2 ON ASGDHISTUINSTALACION(SIGNATURAUI) TABLESPACE &1;
CREATE INDEX ASGDHISTUINSTALACION3 ON ASGDHISTUINSTALACION(ID,FELIMINACION) TABLESPACE &1;
CREATE INDEX ASGDHISTUINSTALACION4 ON ASGDHISTUINSTALACION(IDARCHIVO) TABLESPACE &1;

-- Tabla: ASGDUDOCENUI
CREATE INDEX ASGDUDOCENUI1 ON ASGDUDOCENUI (IDENTIFICACION) TABLESPACE &1;
CREATE INDEX ASGDUDOCENUI2 ON ASGDUDOCENUI (IDUINSTALACION) TABLESPACE &1;
CREATE INDEX ASGDUDOCENUI3 ON ASGDUDOCENUI (IDUNIDADDOC) TABLESPACE &1;
CREATE INDEX ASGDUDOCENUI4 ON ASGDUDOCENUI (IDUDOCRE) TABLESPACE &1;

-----------------
-- SOLICUTUDES --
-----------------

-- Tabla: ASGPPRESTAMO
CREATE UNIQUE INDEX ASGPPRESTAMO1 ON ASGPPRESTAMO (ID) TABLESPACE &1;
CREATE INDEX ASGPPRESTAMO2 ON ASGPPRESTAMO (NUSRSOLICITANTE) TABLESPACE &1;
CREATE INDEX ASGPPRESTAMO3 ON ASGPPRESTAMO (IDUSRSOLICITANTE) TABLESPACE &1;
CREATE INDEX ASGPPRESTAMO4 ON ASGPPRESTAMO (ESTADO) TABLESPACE &1;

-- Tabla: ASGPMTVPRESTAMO
CREATE UNIQUE INDEX ASGPMTVPRESTAMO1 ON ASGPMTVPRESTAMO(ID) TABLESPACE &1;

-- Tabla:  ASGPSOLICITUDUDOC
CREATE INDEX ASGPSOLICITUDUDOC1 ON ASGPSOLICITUDUDOC (IDSOLICITUD, TIPOSOLICITUD, IDUDOC, SIGNATURAUDOC) TABLESPACE &1;
CREATE INDEX ASGPSOLICITUDUDOC2 ON ASGPSOLICITUDUDOC (IDSOLICITUD, TIPOSOLICITUD) TABLESPACE &1;
CREATE INDEX ASGPSOLICITUDUDOC3 ON ASGPSOLICITUDUDOC (IDUDOC) TABLESPACE &1;
CREATE INDEX ASGPSOLICITUDUDOC4 ON ASGPSOLICITUDUDOC (SIGNATURAUDOC) TABLESPACE &1;
CREATE INDEX ASGPSOLICITUDUDOC5 ON ASGPSOLICITUDUDOC (IDUDOC, ESTADO) TABLESPACE &1;

-- Tabla: ASGPSNSEC
CREATE UNIQUE INDEX ASGPSNSEC1 ON ASGPSNSEC (TIPO, ANO) TABLESPACE &1;

-- Tabla: ASGPPRORROGA
CREATE INDEX ASGPPRORROGA1 ON ASGPPRORROGA (IDPRESTAMO,ESTADO) TABLESPACE &1;

-- Tabla: ASGPCONSULTA
CREATE UNIQUE INDEX ASGPCONSULTA1 ON ASGPCONSULTA (ID) TABLESPACE &1;
CREATE INDEX ASGPCONSULTA2 ON ASGPCONSULTA (NUSRCONSULTOR) TABLESPACE &1;
CREATE INDEX ASGPCONSULTA3 ON ASGPCONSULTA (IDUSRSOLICITANTE) TABLESPACE &1;
CREATE INDEX ASGPCONSULTA4 ON ASGPCONSULTA (ESTADO) TABLESPACE &1;

-- Tabla: ASGPMTVCONSULTA
CREATE INDEX ASGPMTVCONSULTA1 ON ASGPMTVCONSULTA (TIPOCONSULTA, TIPOENTIDAD) TABLESPACE &1;
CREATE UNIQUE INDEX ASGPMTVCONSULTA2 ON ASGPMTVCONSULTA(ID) TABLESPACE &1;

-- Tabla: ASGPMTVRECHAZO
CREATE INDEX ASGPMTVRECHAZO1 ON ASGPMTVRECHAZO (TIPOSOLICITUD) TABLESPACE &1;
CREATE UNIQUE INDEX ASGPMTVRECHAZO2 ON ASGPMTVRECHAZO(ID) TABLESPACE &1;

-- Tabla: ASGPTEMA
CREATE INDEX ASGPTEMA1 ON ASGPTEMA (TIPOENTIDAD, IDUSUARIO) TABLESPACE &1;

-- ASGPREVDOCUDOC
CREATE UNIQUE INDEX ASGPREVDOCUDOC1 ON ASGPREVDOCUDOC (IDREVDOC) TABLESPACE &1;
CREATE INDEX ASGPREVDOCUDOC2 ON ASGPREVDOCUDOC (IDUDOC) TABLESPACE &1;
CREATE INDEX ASGPREVDOCUDOC3 ON ASGPREVDOCUDOC (IDUDOC, ESTADO) TABLESPACE &1;

-----------------
-- DESCRIPCION --
-----------------

-- Tabla: ADAREA
CREATE UNIQUE INDEX ADAREA1 ON ADAREA (ID) TABLESPACE &1;
CREATE INDEX ADAREA2 ON ADAREA (TIPONORMA) TABLESPACE &1;
CREATE UNIQUE INDEX ADAREA3 ON ADAREA (NOMBRE, TIPONORMA) TABLESPACE &1;

-- Tabla: ADCAMPOTBL
CREATE UNIQUE INDEX ADCAMPOTBL1 ON ADCAMPOTBL (ID) TABLESPACE &1;
CREATE INDEX ADCAMPOTBL2 ON ADCAMPOTBL (TIPONORMA) TABLESPACE &1;
CREATE UNIQUE INDEX ADCAMPOTBL3 ON ADCAMPOTBL (NOMBRE) TABLESPACE &1;
CREATE INDEX ADCAMPOTBL4 ON ADCAMPOTBL (IDAREA) TABLESPACE &1;

-- Tabla: ADCAMPODATO
CREATE UNIQUE INDEX ADCAMPODATO1 ON ADCAMPODATO (ID) TABLESPACE &1;
CREATE INDEX ADCAMPODATO2 ON ADCAMPODATO (TIPONORMA) TABLESPACE &1;
CREATE UNIQUE INDEX ADCAMPODATO3 ON ADCAMPODATO (NOMBRE) TABLESPACE &1;
CREATE INDEX ADCAMPODATO4 ON ADCAMPODATO (IDAREA) TABLESPACE &1;
CREATE INDEX ADCAMPODATO5 ON ADCAMPODATO (IDTBLPADRE) TABLESPACE &1;

-- Tabla: ADFICHA
CREATE UNIQUE INDEX ADFICHA1 ON ADFICHA (ID) TABLESPACE &1;
CREATE INDEX ADFICHA2 ON ADFICHA (TIPONORMA) TABLESPACE &1;
CREATE INDEX ADFICHA3 ON ADFICHA (TIPONIVEL) TABLESPACE &1;

-- Tabla: ADFMTFICHA
CREATE UNIQUE INDEX ADFMTFICHA1 ON ADFMTFICHA (ID) TABLESPACE &1;
CREATE INDEX ADFMTFICHA2 ON ADFMTFICHA (IDFICHA, TIPO) TABLESPACE &1;

-- Tabla: ADFMTPREF
CREATE INDEX ADFMTPREF1 ON ADFMTPREF (IDFICHA, IDUSUARIO, TIPOFMT) TABLESPACE &1;

-- Tabla: ADTEXTTBLVLD
CREATE INDEX ADTEXTTBLVLD1 ON ADTEXTTBLVLD (IDTBLVLD) TABLESPACE &1;
CREATE UNIQUE INDEX ADTEXTTBLVLD2 ON ADTEXTTBLVLD (ID) TABLESPACE &1;

-- Tabla: ADCTLGLISTAD
CREATE UNIQUE INDEX ADCTLGLISTAD1 ON ADCTLGLISTAD (ID) TABLESPACE &1;
CREATE INDEX ADCTLGLISTAD2 ON ADCTLGLISTAD (TIPODESCRIPTOR) TABLESPACE &1;

-- Tabla: ADCTLGTBLVLD
CREATE UNIQUE INDEX ADCTLGTBLVLD1 ON ADCTLGTBLVLD (ID) TABLESPACE &1;

-- Tabla: ADDESCRIPTOR
CREATE UNIQUE INDEX ADDESCRIPTOR1 ON ADDESCRIPTOR (ID) TABLESPACE &1;
CREATE INDEX ADDESCRIPTOR2 ON ADDESCRIPTOR (IDLISTA) TABLESPACE &1;
CREATE INDEX ADDESCRIPTOR3 ON ADDESCRIPTOR (TIPO) TABLESPACE &1;
CREATE INDEX ADDESCRIPTOR4 ON ADDESCRIPTOR (IDLISTA, NOMBRE) TABLESPACE &1;
CREATE INDEX ADDESCRIPTOR5 ON ADDESCRIPTOR (NIVELACCESO) TABLESPACE &1;

-- Tabla: ADUSOOBJETO
CREATE UNIQUE INDEX ADUSOOBJETO1 ON ADUSOOBJETO (IDOBJ,TIPOOBJ,IDOBJUSUARIO,TIPOOBJUSUARIO) TABLESPACE &1;

-- Tabla: ADVCTEXTCF
CREATE UNIQUE INDEX ADVCTEXTCF1 ON ADVCTEXTCF (IDELEMENTOCF, IDCAMPO, ORDEN) TABLESPACE &1;
CREATE INDEX ADVCTEXTCF2  ON ADVCTEXTCF  (IDELEMENTOCF) TABLESPACE &1;
CREATE INDEX ADVCTEXTCF3  ON ADVCTEXTCF  (IDCAMPO, VALOR) TABLESPACE &1;

-- Tabla: ADVCTEXTLCF
CREATE UNIQUE INDEX ADVCTEXTLCF1 ON ADVCTEXTLCF (IDELEMENTOCF, IDCAMPO, ORDEN) TABLESPACE &1;
CREATE INDEX ADVCTEXTLCF2 ON ADVCTEXTLCF (IDELEMENTOCF) TABLESPACE &1;

-- Tabla: ADVCNUMCF
CREATE UNIQUE INDEX ADVCNUMCF1 ON ADVCNUMCF (IDELEMENTOCF, IDCAMPO, ORDEN) TABLESPACE &1;
CREATE INDEX ADVCNUMCF2   ON ADVCNUMCF   (IDELEMENTOCF) TABLESPACE &1;
CREATE INDEX ADVCNUMCF3   ON ADVCNUMCF   (IDCAMPO, VALOR) TABLESPACE &1;

-- Tabla: ADVCFECHACF
CREATE UNIQUE INDEX ADVCFECHACF1 ON ADVCFECHACF (IDELEMENTOCF, IDCAMPO, ORDEN) TABLESPACE &1;
CREATE INDEX ADVCFECHACF2 ON ADVCFECHACF (IDELEMENTOCF) TABLESPACE &1;
CREATE INDEX ADVCFECHACF3 ON ADVCFECHACF (IDCAMPO, FECHAINI ) TABLESPACE &1;
CREATE INDEX ADVCFECHACF4 ON ADVCFECHACF (IDCAMPO, FECHAFIN) TABLESPACE &1;
CREATE INDEX ADVCFECHACF5 ON ADVCFECHACF (IDCAMPO, FECHAINI, FECHAFIN, CALIFICADOR) TABLESPACE &1;

-- Tabla: ADVCREFCF
CREATE UNIQUE INDEX ADVCREFCF1 ON ADVCREFCF (IDELEMENTOCF, IDCAMPO, ORDEN) TABLESPACE &1;
CREATE INDEX ADVCREFCF2   ON ADVCREFCF (IDELEMENTOCF) TABLESPACE &1;
CREATE INDEX ADVCREFCF3   ON ADVCREFCF (TIPOOBJREF, IDOBJREF) TABLESPACE &1;
CREATE INDEX ADVCREFCF4   ON ADVCREFCF (IDCAMPO, IDOBJREF ) TABLESPACE &1;
CREATE INDEX ADVCREFCF5   ON ADVCREFCF (IDOBJREF ) TABLESPACE &1;

-- Tabla: ADVCTEXTDESCR
CREATE UNIQUE INDEX ADVCTEXTDESCR1 ON ADVCTEXTDESCR (IDDESCR, IDCAMPO, ORDEN) TABLESPACE &1;
CREATE INDEX ADVCTEXTDESCR2 ON ADVCTEXTDESCR (IDDESCR) TABLESPACE &1;
CREATE INDEX ADVCTEXTDESCR3 ON ADVCTEXTDESCR (IDCAMPO, VALOR) TABLESPACE &1;

-- Tabla: ADVCTEXTLDESCR
CREATE UNIQUE INDEX ADVCTEXTLDESCR1 ON ADVCTEXTLDESCR (IDDESCR, IDCAMPO, ORDEN) TABLESPACE &1;
CREATE INDEX ADVCTEXTLDESCR2 ON ADVCTEXTLDESCR (IDDESCR) TABLESPACE &1;

-- Tabla: ADVCNUMDESCR
CREATE UNIQUE INDEX ADVCNUMDESCR1 ON ADVCNUMDESCR (IDDESCR, IDCAMPO, ORDEN) TABLESPACE &1;
CREATE INDEX ADVCNUMDESCR2 ON ADVCNUMDESCR (IDDESCR) TABLESPACE &1;
CREATE INDEX ADVCNUMDESCR3 ON ADVCNUMDESCR (IDCAMPO, VALOR) TABLESPACE &1;

-- Tabla: ADVCFECHADESCR
CREATE UNIQUE INDEX ADVCFECHADESCR1 ON ADVCFECHADESCR (IDDESCR, IDCAMPO, ORDEN) TABLESPACE &1;
CREATE INDEX ADVCFECHADESCR2 ON ADVCFECHADESCR (IDDESCR) TABLESPACE &1;
CREATE INDEX ADVCFECHADESCR3 ON ADVCFECHADESCR (IDCAMPO, FECHAINI ) TABLESPACE &1;
CREATE INDEX ADVCFECHADESCR4 ON ADVCFECHADESCR (IDCAMPO, FECHAFIN) TABLESPACE &1;
CREATE INDEX ADVCFECHADESCR5 ON ADVCFECHADESCR (IDCAMPO, FECHAINI, FECHAFIN, CALIFICADOR) TABLESPACE &1;

-- Tabla: ADVCREFDESCR
CREATE UNIQUE INDEX ADVCREFDESCR1 ON ADVCREFDESCR (IDDESCR, IDCAMPO, ORDEN) TABLESPACE &1;
CREATE INDEX ADVCREFDESCR2 ON ADVCREFDESCR (IDDESCR) TABLESPACE &1;
CREATE INDEX ADVCREFDESCR3 ON ADVCREFDESCR (TIPOOBJREF, IDOBJREF) TABLESPACE &1;
CREATE INDEX ADVCREFDESCR4 ON ADVCREFDESCR (IDCAMPO, IDOBJREF ) TABLESPACE &1;

-- Tabla: ASGTMAPDESCRUDOC
CREATE UNIQUE INDEX ASGTMAPDESCRUDOC1 ON ASGTMAPDESCRUDOC (IDFICHA) TABLESPACE &1;

------------
-- FONDOS --
------------

--Tabla: ASGFNIVELCF
CREATE UNIQUE INDEX ASGFNIVELCF1 ON ASGFNIVELCF (ID) TABLESPACE &1;
CREATE INDEX ASGFNIVELCF2 ON ASGFNIVELCF (TIPO) TABLESPACE &1;

-- Tabla: ASGFESTRUCTJNIVCF
CREATE UNIQUE INDEX ASGFESTRUCTJNIVCF1 ON ASGFESTRUCTJNIVCF (IDNIVELPADRE, IDNIVELHIJO) TABLESPACE &1;
CREATE INDEX ASGFESTRUCTJNIVCF2 ON ASGFESTRUCTJNIVCF (IDNIVELPADRE) TABLESPACE &1;

-- Tabla: ASGFELEMENTOCF
CREATE UNIQUE INDEX ASGFELEMENTOCF1 ON ASGFELEMENTOCF (ID) TABLESPACE &1;
CREATE UNIQUE INDEX ASGFELEMENTOCF2 ON ASGFELEMENTOCF (ID, TIPO) TABLESPACE &1;
CREATE INDEX ASGFELEMENTOCF3 ON ASGFELEMENTOCF (IDPADRE) TABLESPACE &1;
CREATE INDEX ASGFELEMENTOCF4 ON ASGFELEMENTOCF (ESTADO) TABLESPACE &1;
CREATE INDEX ASGFELEMENTOCF5 ON ASGFELEMENTOCF (IDFONDO) TABLESPACE &1;
CREATE INDEX ASGFELEMENTOCF6 ON ASGFELEMENTOCF (IDNIVEL) TABLESPACE &1;
CREATE INDEX ASGFELEMENTOCF7 ON ASGFELEMENTOCF (NIVELACCESO, IDARCHIVO, IDLCA) TABLESPACE &1;

-- Tabla: ASGFSERIE
CREATE UNIQUE INDEX ASGFSERIE1 ON ASGFSERIE (IDELEMENTOCF) TABLESPACE &1;
CREATE INDEX ASGFSERIE2 ON ASGFSERIE (IDFONDO) TABLESPACE &1;
CREATE INDEX ASGFSERIE3 ON ASGFSERIE (ESTADOSERIE) TABLESPACE &1;
CREATE INDEX ASGFSERIE4 ON ASGFSERIE (TIPOPROCEDIMIENTO) TABLESPACE &1;

-- Tabla: ASGFVOLUMENSERIE
CREATE UNIQUE INDEX ASGFVOLUMENSERIE1 ON ASGFVOLUMENSERIE (IDSERIE, TIPODOCUMENTAL) TABLESPACE &1;

-- Tabla:  ASGFENTPRODUCTORA
CREATE UNIQUE INDEX ASGFENTPRODUCTORA1 ON ASGFENTPRODUCTORA (IDDESCR) TABLESPACE &1;

-- Tabla:  ASGFFONDO
CREATE UNIQUE INDEX ASGFFONDO1 ON ASGFFONDO (IDELEMENTOCF) TABLESPACE &1;
CREATE UNIQUE INDEX ASGFFONDO2 ON ASGFFONDO(CODARCHIVO,IDENTPRODUCTORA) TABLESPACE &1;

-- Tabla: ASGFNUMSECVAL
CREATE INDEX ASGFNUMSECVAL1 ON ASGFNUMSECVAL (IDSERIE) TABLESPACE &1;

-- Tabla: ASGFNUMSECSEL
CREATE INDEX ASGFNUMSECSEL1 ON ASGFNUMSECSEL (IDSERIE) TABLESPACE &1;

-- Tabla:  ASGFPRODSERIE
CREATE INDEX ASGFPRODSERIE1 ON ASGFPRODSERIE (IDSERIE) TABLESPACE &1;
CREATE INDEX ASGFPRODSERIE2 ON ASGFPRODSERIE (IDSERIE, IDPROCEDIMIENTO) TABLESPACE &1;

-- Tabla: ASGFUNIDADDOC
CREATE UNIQUE INDEX ASGFUNIDADDOC1 ON ASGFUNIDADDOC (IDELEMENTOCF) TABLESPACE &1;
CREATE INDEX ASGFUNIDADDOC2 ON ASGFUNIDADDOC (IDSERIE) TABLESPACE &1;
CREATE INDEX ASGFUNIDADDOC3 ON ASGFUNIDADDOC (NUMEXP) TABLESPACE &1;
CREATE INDEX ASGFUNIDADDOC4 ON ASGFUNIDADDOC(IDFONDO) TABLESPACE &1;

-- Tabla:  ASGFSOLICITUDSERIE
CREATE UNIQUE INDEX ASGFSOLICITUDSERIE1 ON ASGFSOLICITUDSERIE (ID) TABLESPACE &1;
CREATE INDEX ASGFSOLICITUDSERIE2 ON ASGFSOLICITUDSERIE (IDSERIE) TABLESPACE &1;

-- Tabla: ASGFORGPROD
CREATE UNIQUE INDEX ASGFORGPROD1 ON ASGFORGPROD (IDDESCR) TABLESPACE &1;

-- Tabla: ASGFVALSERIE
CREATE UNIQUE INDEX ASGFVALSERIE1 ON ASGFVALSERIE (ID) TABLESPACE &1;
CREATE INDEX ASGFVALSERIE2 ON ASGFVALSERIE (ESTADO) TABLESPACE &1;
CREATE INDEX ASGFVALSERIE3 ON ASGFVALSERIE (IDSERIE, ESTADO) TABLESPACE &1;
CREATE INDEX ASGFVALSERIE4 ON ASGFVALSERIE (IDUSRGESTORSERIE) TABLESPACE &1;

-- Tabla: ASGFELIMSERIE
CREATE UNIQUE INDEX ASGFELIMSERIE1 ON ASGFELIMSERIE (ID) TABLESPACE &1;
CREATE INDEX ASGFELIMSERIE2 ON ASGFELIMSERIE (ESTADO) TABLESPACE &1;

-- Tabla: ASGFELIMSELUDOC
CREATE INDEX ASGFELIMSELUDOC1 ON ASGFELIMSELUDOC (IDELIMINACION) TABLESPACE &1;
CREATE INDEX ASGFELIMSELUDOC2 ON ASGFELIMSELUDOC (IDUDOC) TABLESPACE &1;

-- Tabla: ASGFELIMUDOCCONS
CREATE INDEX ASGFELIMUDOCCONS1 ON ASGFELIMUDOCCONS (IDELIMINACION) TABLESPACE &1;
CREATE INDEX ASGFELIMUDOCCONS2 ON ASGFELIMUDOCCONS (IDUDOC) TABLESPACE &1;


-- Tabla: ASGFHISTUDOC
CREATE INDEX ASGFHISTUDOC1 ON ASGFHISTUDOC (IDELIMINACION) TABLESPACE &1;
CREATE INDEX ASGFHISTUDOC2 ON ASGFHISTUDOC (IDUDOC) TABLESPACE &1;

-- Tabla: ASGFUDOCSDF
CREATE UNIQUE INDEX ASGFUDOCSDF1 ON ASGFUDOCSDF (IDELEMENTOCF) TABLESPACE &1;

-----------------------------
-- DOCUMENTOS ELECTRONICOS --
-----------------------------

-- Tabla: ADOCCLASIFCF
CREATE UNIQUE INDEX ADOCCLASIFCF1 ON ADOCCLASIFCF(ID) TABLESPACE &1;
CREATE INDEX ADOCCLASIFCF2 ON ADOCCLASIFCF(IDCLFPADRE) TABLESPACE &1;
CREATE INDEX ADOCCLASIFCF3 ON ADOCCLASIFCF(IDELEMENTOCF) TABLESPACE &1;
CREATE INDEX ADOCCLASIFCF4 ON ADOCCLASIFCF(IDELEMENTOCF, ESTADO) TABLESPACE &1;

-- Tabla: ADOCDOCUMENTOCF
CREATE UNIQUE INDEX ADOCDOCUMENTOCF1 ON ADOCDOCUMENTOCF(ID) TABLESPACE &1;
CREATE INDEX ADOCDOCUMENTOCF2 ON ADOCDOCUMENTOCF(IDELEMENTOCF, IDCLFPADRE) TABLESPACE &1;
CREATE INDEX ADOCDOCUMENTOCF3 ON ADOCDOCUMENTOCF(IDELEMENTOCF, IDCLFPADRE, ESTADO) TABLESPACE &1;

-- Tabla: ADOCCLASIFDESCR
CREATE UNIQUE INDEX ADOCCLASIFDESCR1 ON ADOCCLASIFDESCR(ID) TABLESPACE &1;
CREATE INDEX ADOCCLASIFDESCR2 ON ADOCCLASIFDESCR(IDCLFPADRE) TABLESPACE &1;
CREATE INDEX ADOCCLASIFDESCR3 ON ADOCCLASIFDESCR(IDDESCR) TABLESPACE &1;
CREATE INDEX ADOCCLASIFDESCR4 ON ADOCCLASIFDESCR(IDDESCR, ESTADO) TABLESPACE &1;

-- Tabla: ADOCDOCUMENTODESCR
CREATE UNIQUE INDEX ADOCDOCUMENTODESCR1 ON ADOCDOCUMENTODESCR(ID) TABLESPACE &1;
CREATE INDEX ADOCDOCUMENTODESCR2 ON ADOCDOCUMENTODESCR(IDDESCR, IDCLFPADRE) TABLESPACE &1;
CREATE INDEX ADOCDOCUMENTODESCR3 ON ADOCDOCUMENTODESCR(IDDESCR, IDCLFPADRE, ESTADO) TABLESPACE &1;

-- Tabla: ADOCFICHACLF
CREATE UNIQUE INDEX ADOCFICHACLF1 ON ADOCFICHACLF(ID) TABLESPACE &1;

-- Tabla: ADOCTCAPTURA
CREATE UNIQUE INDEX ADOCTCAPTURA1 ON ADOCTCAPTURA(ID) TABLESPACE &1;
CREATE INDEX ADOCTCAPTURA2 ON ADOCTCAPTURA(IDUSRCAPTURA) TABLESPACE &1;
CREATE INDEX ADOCTCAPTURA3 ON ADOCTCAPTURA(ESTADO) TABLESPACE &1;

-- Tabla: ADPCDOCUMENTOVIT
CREATE UNIQUE INDEX ADPCDOCUMENTOVIT1 ON ADPCDOCUMENTOVIT(ID) TABLESPACE &1;

-- Tabla: ADPCUSODOCVIT
CREATE UNIQUE INDEX ADPCUSODOCVIT1 ON ADPCUSODOCVIT(IDDOCVIT,IDEXP,IDSIST) TABLESPACE &1;

-- Tabla: ADPCTIPODOCVIT
CREATE UNIQUE INDEX ADPCTIPODOCVIT1 ON ADPCTIPODOCVIT(ID) TABLESPACE &1;

-- Tabla: ADPCTIPODOCPROC
CREATE UNIQUE INDEX ADPCTIPODOCPROC1 ON ADPCTIPODOCPROC(IDTIPODOC,IDPROC) TABLESPACE &1;

---------------
-- AUDITORIA --
---------------

-- Tabla: AATRAZA
CREATE UNIQUE INDEX AATRAZA1 ON AATRAZA (ID) TABLESPACE &1;
CREATE INDEX AATRAZA2 ON AATRAZA (MODULO) TABLESPACE &1;
CREATE INDEX AATRAZA3 ON AATRAZA (TIMESTAMP) TABLESPACE &1;

-- Tabla: AADATOSTRAZA
CREATE UNIQUE INDEX AADATOSTRAZA1 ON AADATOSTRAZA (ID) TABLESPACE &1;
CREATE INDEX AADATOSTRAZA2 ON AADATOSTRAZA (IDTRAZA) TABLESPACE &1;

-- Tabla: AANAUDITUSR
CREATE UNIQUE INDEX AANAUDITUSR1 ON AANAUDITUSR (TIPOAUDITADO, IDAUDITADO) TABLESPACE &1;

-- Tabla: AANAUDITACCION
CREATE INDEX AANAUDITACCION1 ON AANAUDITACCION (MODULO, ACCION) TABLESPACE &1;











---------------------------------------------------------------------------------------------
-- Índices de las tablas para almacenar los campos descriptivos de unidades en alta/relación
---------------------------------------------------------------------------------------------
--Tabla: ADVCFECHAUDOCRE
CREATE UNIQUE INDEX ADVCFECHAUDOCRE1 ON ADVCFECHAUDOCRE (IDUDOCRE, IDCAMPO, ORDEN) TABLESPACE &1;
CREATE INDEX ADVCFECHAUDOCRE2 ON ADVCFECHAUDOCRE (IDUDOCRE) TABLESPACE &1;
CREATE INDEX ADVCFECHAUDOCRE3 ON ADVCFECHAUDOCRE (IDCAMPO, FECHAINI) TABLESPACE &1;
CREATE INDEX ADVCFECHAUDOCRE4 ON ADVCFECHAUDOCRE (IDCAMPO, FECHAFIN) TABLESPACE &1;
CREATE INDEX ADVCFECHAUDOCRE5 ON ADVCFECHAUDOCRE (IDCAMPO, FECHAINI, FECHAFIN, CALIFICADOR) TABLESPACE &1;

--Tabla: ADVCNUMUDOCRE
CREATE UNIQUE INDEX ADVCNUMUDOCRE1 ON ADVCNUMUDOCRE (IDUDOCRE, IDCAMPO, ORDEN) TABLESPACE &1;
CREATE INDEX ADVCNUMUDOCRE2 ON ADVCNUMUDOCRE (IDUDOCRE) TABLESPACE &1;
CREATE INDEX ADVCNUMUDOCRE3 ON ADVCNUMUDOCRE (IDCAMPO, VALOR) TABLESPACE &1;

--Tabla: ADVCREFUDOCRE
CREATE UNIQUE INDEX ADVCREFUDOCRE1 ON ADVCREFUDOCRE (IDUDOCRE, IDCAMPO, ORDEN) TABLESPACE &1;
CREATE INDEX ADVCREFUDOCRE2 ON ADVCREFUDOCRE (IDUDOCRE) TABLESPACE &1;
CREATE INDEX ADVCREFUDOCRE3 ON ADVCREFUDOCRE (TIPOOBJREF, IDOBJREF) TABLESPACE &1;
CREATE INDEX ADVCREFUDOCRE4 ON ADVCREFUDOCRE (IDCAMPO, IDOBJREF) TABLESPACE &1;

--Tabla: ADVCTEXTLUDOCRE
CREATE UNIQUE INDEX ADVCTEXTLUDOCRE1 ON ADVCTEXTLUDOCRE (IDUDOCRE, IDCAMPO, ORDEN) TABLESPACE &1;
CREATE INDEX ADVCTEXTLUDOCRE2 ON ADVCTEXTLUDOCRE (IDUDOCRE) TABLESPACE &1;

--Tabla: ADVCTEXTUDOCRE
CREATE UNIQUE INDEX ADVCTEXTUDOCRE1 ON ADVCTEXTUDOCRE (ORDEN, IDCAMPO, IDUDOCRE) TABLESPACE &1;
CREATE INDEX ADVCTEXTUDOCRE2 ON ADVCTEXTUDOCRE (IDUDOCRE) TABLESPACE &1;


--Tabla: ASGFDIVISIONFS
CREATE UNIQUE INDEX ASGFDIVISIONFS1 ON ASGFDIVISIONFS (IDFS) TABLESPACE &1;


--Tabla: ASGFUDOCENDIVISIONFS
CREATE UNIQUE INDEX ASGFUDOCENDIVISIONFS1 ON ASGFUDOCENDIVISIONFS (IDFS, IDUDOC) TABLESPACE &1;


-- Tabla: ASGDSIGNUMHUECO
CREATE UNIQUE INDEX ASGDSIGNUMHUECO1 ON ASGDSIGNUMHUECO(IDARCHIVO, SIGNUMHUECO) TABLESPACE &1;

-- Tabla: ASGSEDIFICIO
CREATE UNIQUE INDEX ASGSEDIFICIO1 ON ASGSEDIFICIO(ID) TABLESPACE &1;
CREATE UNIQUE INDEX ASGSEDIFICIO2 ON ASGSEDIFICIO(NOMBRE) TABLESPACE &1;

-- Tabla: ASGSSALA
CREATE UNIQUE INDEX ASGSSALA1 ON ASGSSALA(ID) TABLESPACE &1;
CREATE UNIQUE INDEX ASGSSALA2 ON ASGSSALA(IDEDIFICIO,NOMBRE) TABLESPACE &1;
CREATE INDEX ASGSSALA3 ON ASGSSALA(IDEDIFICIO) TABLESPACE &1;

-- Tabla: ASGSMESA
CREATE INDEX ASGSMESA1 ON ASGSMESA(IDSALA) TABLESPACE &1;
CREATE UNIQUE INDEX ASGSMESA2 ON ASGSMESA(IDSALA,CODIGO) TABLESPACE &1;
CREATE UNIQUE INDEX ASGSMESA3 ON ASGSMESA(IDSALA,NUMORDEN) TABLESPACE &1;
CREATE INDEX ASGSMESA4 ON ASGSMESA(ESTADO) TABLESPACE &1;

-- Tabla: ASGSUSRCSALA
CREATE UNIQUE INDEX ASGSUSRCSALA1 ON ASGSUSRCSALA(ID) TABLESPACE &1;
CREATE INDEX ASGSUSRCSALA2 ON ASGSUSRCSALA(NUMDOCIDENTIFICACION) TABLESPACE &1;
CREATE INDEX ASGSUSRCSALA3 ON ASGSUSRCSALA(VIGENTE) TABLESPACE &1;

-- Tabla: ASGSUSRCSARCH
CREATE UNIQUE INDEX ASGSUSRCSARCH1 ON ASGSUSRCSARCH(IDUSRCSALA,IDARCHIVO) TABLESPACE &1;
CREATE INDEX ASGSUSRCSARCH2 ON ASGSUSRCSARCH(IDUSRCSALA) TABLESPACE &1;

-- Tabla: ASGSREGCSALA
CREATE UNIQUE INDEX ASGSREGCSALA1 ON ASGSREGCSALA(ID) TABLESPACE &1;
CREATE INDEX ASGSREGCSALA2 ON ASGSREGCSALA(IDUSRCSALA) TABLESPACE &1;
CREATE INDEX ASGSREGCSALA3 ON ASGSREGCSALA(NUMDOCIDENTIFICACION) TABLESPACE &1;

-- Tabla: ASGTUIREEACR
CREATE UNIQUE INDEX ASGTUIREEACR1 ON ASGTUIREEACR (ID) TABLESPACE &1;
CREATE INDEX ASGTUIREEACR2 ON ASGTUIREEACR (IDRELENTREGA) TABLESPACE &1;

-- Tabla: ASGTUDOCENUIREEACR
CREATE UNIQUE INDEX ASGTUDOCENUIREEACR1 ON ASGTUDOCENUIREEACR (ID) TABLESPACE &1;
CREATE INDEX ASGTUDOCENUIREEACR2 ON ASGTUDOCENUIREEACR (IDUDOCORIGEN) TABLESPACE &1;
CREATE INDEX ASGTUDOCENUIREEACR3 ON ASGTUDOCENUIREEACR (IDRELENTREGA) TABLESPACE &1;
CREATE INDEX ASGTUDOCENUIREEACR4 ON ASGTUDOCENUIREEACR (IDUNIDADDOC) TABLESPACE &1;
CREATE INDEX ASGTUDOCENUIREEACR5 ON ASGTUDOCENUIREEACR (IDUIREEACR) TABLESPACE &1;
CREATE INDEX ASGTUDOCENUIREEACR6 ON ASGTUDOCENUIREEACR (IDRELENTREGA,IDUNIDADDOC) TABLESPACE &1;

-- Tabla: ASGTUDOCREEACR
CREATE UNIQUE INDEX ASGTUDOCREEACR1 ON ASGTUDOCREEACR (ID) TABLESPACE &1;
CREATE INDEX ASGTUDOCREEACR2 ON ASGTUDOCREEACR (IDRELENTREGA) TABLESPACE &1;
CREATE INDEX ASGTUDOCREEACR3 ON ASGTUDOCREEACR (IDRELENTREGA,IDUNIDADDOC) TABLESPACE &1;

CREATE UNIQUE INDEX ASGFCTLGTBLTMP1 ON ASGFCTLGTBLTMP(ID) TABLESPACE &1;
CREATE UNIQUE INDEX ASGFCTLGTBLTMP2 ON ASGFCTLGTBLTMP(NOMBRETABLA) TABLESPACE &1;


COMMIT;

spool off