CREATE UNIQUE INDEX IVOLACTDIR1 ON 
  IVOLACTDIR(VOLID) 
; 

CREATE UNIQUE INDEX IVOLARCHLIST1 ON 
  IVOLARCHLIST(ARCHID) 
; 

CREATE INDEX IVOLARCHLIST2 ON 
  IVOLARCHLIST(LISTID) 
; 

CREATE UNIQUE INDEX IVOLFILEFTS1 ON 
  IVOLFILEFTS(ID) 
; 

CREATE UNIQUE INDEX IVOLFILEHDR1 ON 
  IVOLFILEHDR(ID) 
; 

CREATE INDEX IVOLFILEHDR2 ON 
  IVOLFILEHDR(VOLID) 
; 

CREATE UNIQUE INDEX IVOLLISTHDR1 ON 
  IVOLLISTHDR(ID) 
; 

CREATE INDEX IVOLLISTVOL1 ON 
  IVOLLISTVOL(LISTID) 
; 

CREATE INDEX IVOLLISTVOL2 ON 
  IVOLLISTVOL(VOLID) 
; 

CREATE UNIQUE INDEX IVOLNEXTID1 ON 
  IVOLNEXTID(TYPE) 
; 

CREATE UNIQUE INDEX IVOLREPHDR1 ON 
  IVOLREPHDR(ID) 
; 

CREATE UNIQUE INDEX IVOLVOLHDR1 ON 
  IVOLVOLHDR(ID) 
; 

CREATE INDEX IVOLVOLHDR2 ON 
  IVOLVOLHDR(REPID) 
; 

CREATE UNIQUE INDEX IVOLVOLTBL1 ON 
  IVOLVOLTBL(LOCID) 
; 

