INSERT INTO IVOLACTDIR ( VOLID, ACTDIR, NUMFILES ) VALUES ( 
1, 1, 0); 
commit;
 
INSERT INTO IVOLLISTHDR ( ID, NAME, FLAGS, STAT, REMARKS, CRTRID, CRTNDATE, UPDRID,
UPDDATE ) VALUES ( 
6, 'ListBD', 0, 0, NULL, 0,  SYSDATE
, NULL, NULL); 
commit;
 
INSERT INTO IVOLLISTVOL ( LISTID, VOLID, SORTORDER ) VALUES ( 
6, 1, 1);  
commit;
 
INSERT INTO IVOLNEXTID ( TYPE, ID ) VALUES ( 
1, 7); 
INSERT INTO IVOLNEXTID ( TYPE, ID ) VALUES ( 
2, 7); 
INSERT INTO IVOLNEXTID ( TYPE, ID ) VALUES ( 
3, 7); 
INSERT INTO IVOLNEXTID ( TYPE, ID ) VALUES ( 
4, 130); 
commit;

INSERT INTO IVOLVOLHDR ( ID, NAME, REPID, INFO, ITEMP, ACTSIZE, NUMFILES, STAT, REMARKS, CRTRID, CRTNDATE,
UPDRID, UPDDATE ) VALUES ( 
1, 'RepBD', 1, '(CLOB)', 0, '0', 0, 0, NULL, 0,  SYSDATE
, 0,  SYSDATE); 
commit;

INSERT INTO IVOLREPHDR ( ID, NAME, TYPE, INFO, STAT, REMARKS, CRTRID, CRTNDATE, UPDRID,
UPDDATE ) VALUES ( 
1, 'RepBD', 5, '(CLOB)', 0, NULL, 0, SYSDATE
, NULL, NULL); 
commit;

