--Tabla: AOESTRORG
CREATE UNIQUE INDEX AOESTRORG1 ON AOESTRORG (ID) TABLESPACE &1;
CREATE UNIQUE INDEX AOESTRORG2 ON AOESTRORG (CODIGO) TABLESPACE &1;

--Tabla: AOUSR
CREATE INDEX AOUSR1 ON AOUSR (NOMBRE) TABLESPACE &1;
CREATE UNIQUE INDEX AOUSR2 ON AOUSR (NOMBREUSUARIO) TABLESPACE &1;

--Tabla: AOUSRORGV
CREATE UNIQUE INDEX AOUSRORGV1 ON AOUSRORGV (IDUSUARIO) TABLESPACE &1;
