CREATE SEQUENCE  SEC_SQ_ID_CONTADORES AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE SPAC_SQ_661291693 AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE SPAC_SQ_562949042 AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE SPAC_SQ_660930754 AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE SPAC_SQ_1765192511 AS INTEGER NO CACHE ORDER;


ALTER TABLE SEC_CONTADORES
    ADD CONSTRAINT pk_SEC_CONTADORES PRIMARY KEY (id);
ALTER TABLE SEC_VLDTBL_ORGANO_GOBIERNO
    ADD CONSTRAINT pk_SEC_VLDTBL_ORGANO_GOBIERNO PRIMARY KEY (id);
ALTER TABLE SEC_VLDTBL_CARGO_ORGANO
    ADD CONSTRAINT pk_SEC_VLDTBL_CARGO_ORGANO PRIMARY KEY (id);
ALTER TABLE SEC_VLDTBL_AREA_GOBIERNO
    ADD CONSTRAINT pk_SEC_VLDTBL_AREA_GOBIERNO PRIMARY KEY (id);
ALTER TABLE SEC_VLDTBL_CARGO_AREA
    ADD CONSTRAINT pk_SEC_VLDTBL_CARGO_AREA PRIMARY KEY (id);
