/**
 * ConsultaExpedientesWebService_PortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.3 Oct 05, 2005 (05:23:37 EDT) WSDL2Java emitter.
 */

package es.ieci.tecdoc.sigem.ConsultaExpedientesWebService;

public interface ConsultaExpedientesWebService_PortType extends java.rmi.Remote {
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Expedientes consultarExpedientesNIF(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.CriterioBusquedaExpedientes poNif, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Expedientes consultarExpedientes(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.CriterioBusquedaExpedientes poCriterio, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Url obtenerURLAportacionExpedientes() throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Url obtenerURLNotificacionExpedientes() throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Url obtenerURLPagoTasas() throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Expediente obtenerDetalle(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Expediente poNumExpediente, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.HitosExpediente obtenerHistoricoExpediente(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Expediente poNumExpediente, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.HitoExpediente obtenerHitoEstado(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Expediente poNumExpediente, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.FicherosHito obtenerFicherosHito(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.HitoExpediente poGuidHito, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.FicherosHitos obtenerFicherosHitos(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.HitosExpediente poHitos, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.RetornoServicio nuevoExpediente(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Expediente poExpediente, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Interesado poInteresado, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.RetornoServicio eliminarExpediente(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Expediente poExpediente, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.RetornoServicio nuevoInteresado(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Interesado poInteresado, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.RetornoServicio eliminarInteresado(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Interesado poInteresado, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.RetornoServicio eliminarInteresadoExpediente(java.lang.String numeroExpediente, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.RetornoServicio establecerHitoActual(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.HitoExpediente poHito, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.FicherosHito poFicheros, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Historico poHistorico, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.RetornoServicio eliminarHitoActual(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Expediente poNumExpediente, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.RetornoServicio nuevoHitoHistorico(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.HitoExpediente poHito, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.RetornoServicio eliminarHitoHistorico(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.HitoExpediente poHito, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.InfoDocumento cargarDocumento(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.InfoDocumento poInfodoc, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.InfoDocumento recogerDocumento(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.InfoDocumento poInfodoc, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Expedientes busquedaExpedientes(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.CriterioBusquedaExpedientes poCriterio, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.RetornoServicio anexarFicherosHitoActual(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.FicherosHito poFicheros, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.NotificacionesPendientes recogerNotificaciones(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Expediente poExpediente, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.RetornoServicio altaSolicitudSubsanacion(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Subsanacion poSubsanacion, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Subsanaciones obtenerSubsanacionesHitoActual(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Expediente poExpediente, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Subsanaciones obtenerSubsanacionesHito(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.HitoExpediente poHitoExp, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.RetornoServicio altaSolicitudPago(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Pago poPago, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Pagos obtenerPagosHitoActual(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Expediente poExpediente, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Pagos obtenerPagosHito(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.HitoExpediente poHitoExp, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.RetornoServicio altaNotificacion(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Notificacion poNotificacion, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Notificaciones obtenerNotificionesHitoActual(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Expediente poExpediente, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Notificaciones obtenerNotificionesHito(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.HitoExpediente poHitoExp, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.RetornoLogico existenNotificaciones(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Expediente poExpediente, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.RetornoLogico existenPagos(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Expediente poExpediente, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.RetornoLogico existenSubsanaciones(es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Expediente poExpediente, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.RetornoLogico actualizarEstadoLocalGIS(java.lang.String idExpediente, java.lang.String estado, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
    public es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.RetornoLogico publicarExpedienteLocalGIS(java.lang.String idExpediente, java.lang.String nif, java.lang.String tipoExpediente, java.lang.String estado, java.lang.String fecha, es.ieci.tecdoc.sigem.ConsultaExpedientesWebService.Entidad entidad) throws java.rmi.RemoteException;
}
