DROP FUNCTION ADD_MONTHS(TIMESTAMP, NUMERIC);
DROP FUNCTION ISNUMERIC(character varying);
DROP FUNCTION GETNUMERICPOSITIVE(character varying);
DROP FUNCTION DEVOLVERMARCA(numeric, numeric);
DROP FUNCTION CALCULARFINALCODREFPADRE(VARCHAR(255),VARCHAR(255),VARCHAR(255),VARCHAR(255),VARCHAR(255));
DROP FUNCTION GETCODREF(VARCHAR(32), VARCHAR(1));
DROP FUNCTION GETFINCODREFPADRE (VARCHAR(32),VARCHAR(1));
DROP FUNCTION UPDATECODREF ( VARCHAR(32), VARCHAR(1), VARCHAR(1) );