/* TABLES OR VIEWS --------------------------------------- */
CREATE TABLE DIR_OFICINA (
	CODIGO_OFICINA                    	VARCHAR2(9 CHAR)         NOT NULL,
	DENOMINACION_OFICINA              	VARCHAR2(300 CHAR)       NOT NULL,
	CODIGO_UNIDAD_RESPONSABLE       	VARCHAR2(9 CHAR)         NULL,
	EXTERNO_FUENTE            			VARCHAR2(40 CHAR)        NULL,
	PROVINCIA	            			VARCHAR2(100 CHAR)       NULL,
	LOCALIDAD	            			VARCHAR2(100 CHAR)       NULL,
	DIRECCION	            			VARCHAR2(300 CHAR)       NULL
);


CREATE TABLE DIR_UNIDAD_ORGANICA (
	CODIGO_UNIDAD_ORGANICA                		VARCHAR2(9 CHAR)        NOT NULL,
	NOMBRE_UNIDAD_ORGANICA               		VARCHAR2(300 CHAR)      NOT NULL,
	CODIGO_UNIDAD_SUP_JERARQUICA     			VARCHAR2(9 CHAR)        NULL,
	DENOM_UNIDAD_SUP_JERARQUICA    				VARCHAR2(300 CHAR) 		NULL,
	CODIGO_EXTERNO_FUENTE             			VARCHAR2(40 CHAR)       NULL
);

CREATE TABLE DIR_ESTADO_ACTUALIZACION (
	ID 											INTEGER 		  NOT NULL,
	FECHA_ACTUALIZACION							DATE			  NOT NULL,
	ESTADO										VARCHAR(10 CHAR)  NOT NULL
);

CREATE TABLE DIR_RELAC_UNID_ORG_OFIC (
	CODIGO_OFICINA                    			VARCHAR2(9 CHAR)         NOT NULL,
	DENOMINACION_OFICINA              			VARCHAR2(300 CHAR)       NOT NULL,
	CODIGO_UNIDAD_ORGANICA                		VARCHAR2(9 CHAR)         NOT NULL,
	DENOM_UNIDAD_ORGANICA		          		VARCHAR2(300 CHAR)       NOT NULL
);


/* PRIMARY KEYS --------------------------------------- */
ALTER TABLE DIR_OFICINA ADD CONSTRAINT PK_DIR_OFICINA PRIMARY KEY (CODIGO_OFICINA);

ALTER TABLE DIR_UNIDAD_ORGANICA ADD CONSTRAINT PK_DIR_UNIDAD_ORGANICA PRIMARY KEY (CODIGO_UNIDAD_ORGANICA);

ALTER TABLE DIR_ESTADO_ACTUALIZACION ADD CONSTRAINT PK_ESTADO_ACTUALIZACION PRIMARY KEY(ID);