-- /***************************/
-- /* Actualización 4.0->4.2  */
-- /***************************/

    -- Insertar la versión actual de bd
	INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.0->4.2',now());

	-- Establecer el id de motivo en consultas como nulo
	ALTER TABLE ASGPCONSULTA ALTER COLUMN IDMOTIVO TYPE VARCHAR(32);
	ALTER TABLE ASGPCONSULTA ALTER COLUMN IDMOTIVO DROP NOT NULL;

	-- Establecer el id de motivo en consultas como nulo
	ALTER TABLE ASGPCONSULTA ALTER COLUMN MOTIVO TYPE VARCHAR(32);
	ALTER TABLE ASGPCONSULTA ALTER COLUMN MOTIVO DROP NOT NULL;

	-- Establecer el id de motivo en préstamos como nulo
	ALTER TABLE ASGPPRESTAMO ALTER COLUMN IDMOTIVO TYPE VARCHAR(32);
	ALTER TABLE ASGPPRESTAMO ALTER COLUMN IDMOTIVO DROP NOT NULL;

-- /***************************/
-- /* Actualización 4.2->4.3            */
-- /***************************/

	-- Insertar la versión actual de bd
	INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.2->4.3',now());

	-- Aniadir marcas de bloqueo a la tabla de unidades documentales en la relacion
	ALTER TABLE ASGTUNIDADDOCRE ADD MARCASBLOQUEO INTEGER DEFAULT 0 NOT NULL;

	-- Aniadir marcas de bloqueo a la tabla de unidades documentales
	ALTER TABLE ASGFUNIDADDOC ADD MARCASBLOQUEO INTEGER DEFAULT 0 NOT NULL;

-- /***************************/
-- /* Actualización 4.3->4.4             */
-- /***************************/

	-- Insertar la versión actual de bd
	INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.3->4.4',now());

	-- Crear tabla de Edificios
	CREATE TABLE ASGSEDIFICIO (
     ID			VARCHAR (32) NOT NULL,
     NOMBRE        VARCHAR (64) NOT NULL,
     UBICACION     VARCHAR (254),
     IDARCHIVO   	VARCHAR (32) NOT NULL
	);

	-- Crear índices de la tabla de Edificios
	CREATE UNIQUE INDEX ASGSEDIFICIO1 ON ASGSEDIFICIO(ID);
	CREATE UNIQUE INDEX ASGSEDIFICIO2 ON ASGSEDIFICIO(NOMBRE);

	-- Crear tabla de Salas
	CREATE TABLE ASGSSALA (
     ID	 	  	  		VARCHAR (32) NOT NULL,
     NOMBRE          		VARCHAR (64) NOT NULL,
     DESCRIPCION     		VARCHAR (254),
     IDEDIFICIO   	  		VARCHAR (32) NOT NULL,
     EQUIPOINFORMATICO     CHAR (1) NOT NULL
	);

	-- Crear índices de la tabla de Salas
	CREATE UNIQUE INDEX ASGSSALA1 ON ASGSSALA(ID);
	CREATE UNIQUE INDEX ASGSSALA2 ON ASGSSALA(IDEDIFICIO,NOMBRE);
	CREATE INDEX ASGSSALA3 ON ASGSSALA(IDEDIFICIO);

	-- Crear tabla de Mesas
	CREATE TABLE ASGSMESA (
     ID	 	  	  VARCHAR (32) NOT NULL,
     CODIGO          VARCHAR (64) NOT NULL,
     NUMORDEN	  	  INTEGER NOT NULL,
     IDSALA   	  	  VARCHAR (32) NOT NULL,
     ESTADO          CHAR (1) NOT NULL,
     FECHAESTADO     TIMESTAMP NOT NULL,
     IDUSRCSALA   	  VARCHAR (32)
	);

	-- Crear índices de la tabla Mesas
	CREATE INDEX ASGSMESA1 ON ASGSMESA(IDSALA);
	CREATE UNIQUE INDEX ASGSMESA2 ON ASGSMESA(IDSALA,CODIGO);
	CREATE UNIQUE INDEX ASGSMESA3 ON ASGSMESA(IDSALA,NUMORDEN);
	CREATE INDEX ASGSMESA4 ON ASGSMESA(ESTADO);

	-- Crear tabla de usuarios investigadores de consulta de sala
	CREATE TABLE ASGSUSRCSALA (
     ID	 	  	  			VARCHAR (32) NOT NULL,
     TIPODOCIDENTIFICACION     INTEGER NOT NULL,
     NUMDOCIDENTIFICACION		VARCHAR (32) NOT NULL,
     NOMBRE			  	    VARCHAR (64) NOT NULL,
      APELLIDOS			  	    VARCHAR (254) NOT NULL,
     NACIONALIDAD	   	  	    VARCHAR (64),
     TELEFONOS					VARCHAR (128),
     EMAIL						VARCHAR (128),
     DIRECCION		            VARCHAR (254),
     FECHAALTA				    TIMESTAMP NOT NULL,
     VIGENTE					CHAR (1) NOT NULL,
     IDSCAUSR					VARCHAR (32)
	);

	-- Crear índices de la tabla usuarios investigadores
	CREATE UNIQUE INDEX ASGSUSRCSALA1 ON ASGSUSRCSALA(ID);
	CREATE INDEX ASGSUSRCSALA2 ON ASGSUSRCSALA(NUMDOCIDENTIFICACION);
	CREATE INDEX ASGSUSRCSALA3 ON ASGSUSRCSALA(VIGENTE);

	-- Crear tabla relación usuarios consulta y archivos
	CREATE TABLE ASGSUSRCSARCH (
     IDUSRCSALA  	  VARCHAR (32) NOT NULL,
     IDARCHIVO       VARCHAR (64) NOT NULL
	);

	-- Crear índices de la tabla de relación entre usuarios y archivos de consulta
	CREATE UNIQUE INDEX ASGSUSRCSARCH1 ON ASGSUSRCSARCH(IDUSRCSALA,IDARCHIVO);
	CREATE INDEX ASGSUSRCSARCH2 ON ASGSUSRCSARCH(IDUSRCSALA);

	-- Crear tabla de registro de consultas
	CREATE TABLE ASGSREGCSALA (
     ID		  	  		VARCHAR (32) NOT NULL,
     IDUSRCSALA  	  		VARCHAR (32) NOT NULL,
     FENTRADA				TIMESTAMP NOT NULL,
     FSALIDA				TIMESTAMP,
     NUMDOCIDENTIFICACION	VARCHAR (32) NOT NULL,
     NOMBREAPELLIDOS		VARCHAR (254) NOT NULL,
     IDSCAUSR  	  		VARCHAR (32),
     IDARCHIVO  	  		VARCHAR (32) NOT NULL,
     MESAASIGNADA			VARCHAR (254) NOT NULL
	);

	-- Crear índices de la tabla de registro de consultas
	CREATE UNIQUE INDEX ASGSREGCSALA1 ON ASGSREGCSALA(ID);
	CREATE INDEX ASGSREGCSALA2 ON ASGSREGCSALA(IDUSRCSALA);
	CREATE INDEX ASGSREGCSALA3 ON ASGSREGCSALA(NUMDOCIDENTIFICACION);


	--Añadir columna IDUSRCSALA a la tabla de consultas
	ALTER TABLE ASGPCONSULTA ADD IDUSRCSALA VARCHAR(32);

	--Añadir columna IDUSRCSALA a la tabla de temas
	ALTER TABLE ASGPTEMA ADD IDUSRCSALA VARCHAR(32);

-- /***************************/
-- /* Actualización 4.4->4.5            */
-- /***************************/

	-- Insertar la versión actual de bd
	INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.4->4.5',now());



	--Añadir columnas CONREENCAJADO e IDFORMATORE a la tabla de relaciones de entrega
	ALTER TABLE ASGTRENTREGA ADD CONREENCAJADO VARCHAR(1) DEFAULT 'N' NOT NULL;
	ALTER TABLE ASGTRENTREGA ADD IDFORMATORE VARCHAR(32);

	--Añadir columna IDUIREEACR a la tabla de huecos
	ALTER TABLE ASGDHUECO ADD IDUIREEACR VARCHAR(32);

	--Crear la tabla de unidades de instalación transferencias entre archivo con reencajado
	CREATE TABLE ASGTUIREEACR (
     ID			  VARCHAR (32)  NOT NULL,
     IDRELENTREGA    VARCHAR (32)  NOT NULL,
     IDUIDEPOSITO    VARCHAR (32),
     SIGNATURAUI     VARCHAR (16),
     IDFORMATO       VARCHAR (32) NOT NULL,
     ORDEN			  SMALLINT NOT NULL,
     ESTADOCOTEJO 	  SMALLINT NOT NULL	DEFAULT 1,
     NOTASCOTEJO	  VARCHAR (256),
     DEVOLUCION	  CHAR (1) DEFAULT 'N',
     DESCRIPCION	  VARCHAR (256)
	);

	--Crear la tabla de unidades documentales en unidad de instalacion de transferencias
	--entre archivos con reencajado
	CREATE TABLE ASGTUDOCENUIREEACR (
     ID			  VARCHAR (32)  NOT NULL,
     IDUDOCORIGEN    VARCHAR (32)  NOT NULL,
     IDRELENTREGA    VARCHAR (32)  NOT NULL,
     IDUNIDADDOC     VARCHAR (32)  NOT NULL,
     IDUIREEACR	  VARCHAR (32),
     ASUNTO		  VARCHAR (1024) NOT NULL,
     UDOCCOMPLETA	  VARCHAR (1) NOT NULL,
     SIGNATURAUDOC   VARCHAR (32),
     POSUDOCENUI     SMALLINT,
     NUMEXP          VARCHAR (256),
     NUMPARTE        SMALLINT,
     FECHAINI        VARCHAR (64),
     FECHAFIN        VARCHAR (64),
     SIGNATURAUDOCORIGEN VARCHAR (32),
     DESCRIPCION	  VARCHAR (256)
	);

	--Tabla de unidades documentales originales en el reencajado
	CREATE TABLE ASGTUDOCREEACR (
     ID			  VARCHAR (32)  NOT NULL,
     IDRELENTREGA    VARCHAR (32)  NOT NULL,
     IDUNIDADDOC     VARCHAR (32)  NOT NULL,
     SIGNATURAUDOC	  VARCHAR (32)  NOT NULL,
     IDUIDEPOSITO	  VARCHAR (32)  NOT NULL,
     SIGNATURAUI	  VARCHAR (16)  NOT NULL
	);


	-- Tabla: ASGTUIREEACR
	CREATE UNIQUE INDEX ASGTUIREEACR1 ON ASGTUIREEACR (ID);
	CREATE INDEX ASGTUIREEACR2 ON ASGTUIREEACR (IDRELENTREGA);

	-- Tabla: ASGTUDOCENUIREEACR
	CREATE UNIQUE INDEX ASGTUDOCENUIREEACR1 ON ASGTUDOCENUIREEACR (ID);
	CREATE INDEX ASGTUDOCENUIREEACR2 ON ASGTUDOCENUIREEACR (IDUDOCORIGEN);
	CREATE INDEX ASGTUDOCENUIREEACR3 ON ASGTUDOCENUIREEACR (IDRELENTREGA);
	CREATE INDEX ASGTUDOCENUIREEACR4 ON ASGTUDOCENUIREEACR (IDUNIDADDOC);
	CREATE INDEX ASGTUDOCENUIREEACR5 ON ASGTUDOCENUIREEACR (IDUIREEACR);
	CREATE INDEX ASGTUDOCENUIREEACR6 ON ASGTUDOCENUIREEACR (IDRELENTREGA,IDUNIDADDOC);

	-- Tabla: ASGTUDOCREEACR
	CREATE UNIQUE INDEX ASGTUDOCREEACR1 ON ASGTUDOCREEACR (ID);
	CREATE INDEX ASGTUDOCREEACR2 ON ASGTUDOCREEACR (IDRELENTREGA);
	CREATE INDEX ASGTUDOCREEACR3 ON ASGTUDOCREEACR (IDRELENTREGA,IDUNIDADDOC);

-- /***************************/
-- /* Actualización 4.5->4.7            */
-- /***************************/

INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.5->4.7',now());

CREATE TABLE ASGFCTLGTBLTMP(
	ID NUMERIC(5)NOT NULL,
	NOMBRETABLA VARCHAR(16) NOT NULL,
	IDUSUARIO VARCHAR(32),
	ESTADO NUMERIC(1) default 0,
	FECHA DATE
);

CREATE UNIQUE INDEX ASGFCTLGTBLTMP1 ON ASGFCTLGTBLTMP(ID);
CREATE UNIQUE INDEX ASGFCTLGTBLTMP2 ON ASGFCTLGTBLTMP(NOMBRETABLA);

CREATE UNIQUE INDEX ASGFFONDO2 ON ASGFFONDO(CODARCHIVO,IDENTPRODUCTORA);

--/*************************/
--/* Actualización 4.7->4.8 */
--/*************************/
INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.7->4.8',now());


--Fecha devolución en prorroga
ALTER TABLE ASGPPRORROGA ADD FECHAFINPRORROGA DATE;

--Motivo por el cual se solicita la prorroga
ALTER TABLE ASGPPRORROGA ADD MOTIVOPRORROGA VARCHAR(512);

DROP INDEX ASGFELIMSELUDOC1;

DROP INDEX ASGFELIMSELUDOC2;

--Modificar el nombre de la tabla ASGFELIMSELUDOC por ASGFELIMUDOCCONS
ALTER TABLE ASGFELIMSELUDOC RENAME TO ASGFELIMUDOCCONS;

-- Tabla: ASGFELIMUDOCCONS
CREATE INDEX ASGFELIMUDOCCONS1 ON ASGFELIMUDOCCONS (IDELIMINACION);
CREATE INDEX ASGFELIMUDOCCONS2 ON ASGFELIMUDOCCONS (IDUDOC);


CREATE TABLE ASGFELIMSELUDOC(
    IDELIMINACION VARCHAR(32) NOT NULL,
    IDUDOC VARCHAR(32) NOT NULL,
    IDFONDO VARCHAR(32),
    CODREFERENCIA VARCHAR(1024),
    CODIGO VARCHAR(128),
    SIGNATURAUDOC VARCHAR(32),
    EXPEDIENTEUDOC VARCHAR(256),
    TITULO VARCHAR(1024),
    CODSISTPRODUCTOR VARCHAR(16),
    TIPODOCUMENTAL VARCHAR(254),
    IDUINSTALACION VARCHAR(32),
    UBICACION VARCHAR(512),
    FECHAINIUDOC DATE,
    FECHAFINUDOC DATE,
    NUMERO VARCHAR(10)
);

-- Tabla: ASGFELIMSELUDOC
CREATE INDEX ASGFELIMSELUDOC1 ON ASGFELIMSELUDOC (IDELIMINACION);
CREATE INDEX ASGFELIMSELUDOC2 ON ASGFELIMSELUDOC (IDUDOC);

-- Tabla: ASGFUNIDADDOC4
CREATE INDEX ASGFUNIDADDOC4 ON ASGFUNIDADDOC(IDFONDO);

--/*************************/
--/* Versión 4.8 > 5.0     */
--/*************************/
INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.8->5.0',now());


--Renombrar IDLVOLPREF a IDREPECMPREF
ALTER TABLE ADCTLGLISTAD RENAME COLUMN IDLVOLPREF TO IDREPECMPREF;

--Renombrar IDLVOL a IDREPECM
ALTER TABLE ADDESCRIPTOR RENAME COLUMN IDLVOL TO IDREPECM;

--Renombrar IDLVOL a IDREPECM
ALTER TABLE ASGFELEMENTOCF RENAME COLUMN IDLVOL TO IDREPECM;

--Renombrar IDLVOLPREF a IDREPECMPREF
ALTER TABLE ASGFNIVELCF RENAME COLUMN IDLVOLPREF TO IDREPECMPREF;

--Renombrar INFOFICHAUDOCLVOL a INFOFICHAUDOCREPECM
ALTER TABLE ASGFSERIE RENAME COLUMN INFOFICHAUDOCLVOL TO INFOFICHAUDOCREPECM;

--Añadir idRepEcm
ALTER TABLE ADOCDOCUMENTODESCR ADD IDREPECM VARCHAR(32);
ALTER TABLE ADOCDOCUMENTOCF ADD IDREPECM VARCHAR(32);
ALTER TABLE ADPCDOCUMENTOVIT ADD IDREPECM VARCHAR(32);

--Cambiar Tamaño de IDFICH a 128
ALTER TABLE ADPCDOCUMENTOVIT ALTER COLUMN IDFICH TYPE VARCHAR(128);

--Añadir el campo subtiponivel
ALTER TABLE ADFICHA ADD SUBTIPONIVEL INTEGER DEFAULT 0 NOT NULL;

--Actualizar los valores de subtiponivel
UPDATE ADFICHA SET SUBTIPONIVEL=61 WHERE ID='1';
UPDATE ADFICHA SET SUBTIPONIVEL=62 WHERE ID='6';



--Nuevo Índice por etiquetaxml en campo tabla
CREATE UNIQUE INDEX ADCAMPOTBL5 ON ADCAMPOTBL (ETIQUETAXML);

UPDATE ADCAMPODATO SET ETIQUETAXML = 'Documento_Fisico_Descripcion' WHERE ID='43' AND ETIQUETAXML = 'Descripcion';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Documento_Electronico_Descripcion' WHERE ID='50' AND ETIQUETAXML = 'Descripcion';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Identificacion' WHERE ID='1' AND ETIQUETAXML = 'Identificador';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Identificador_Recurso' WHERE ID='131' AND ETIQUETAXML = 'Identificador';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Entidad_Relacionada_Nombre' WHERE ID='114' AND ETIQUETAXML = 'Nombre';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Documento_Fisico_Nombre' WHERE ID='19' AND ETIQUETAXML = 'Nombre';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Productor_Nombre' WHERE ID='34' AND ETIQUETAXML = 'Nombre';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Documento_Electronico_Nombre' WHERE ID='49' AND ETIQUETAXML = 'Nombre';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Entidad_Relacionada_Tipo_Relacion' WHERE ID='115' AND ETIQUETAXML = 'Tipo_Relacion';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Naturaleza_Relacion' WHERE ID='133' AND ETIQUETAXML = 'Tipo_Relacion';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Interesado_Validado' WHERE ID='12' AND ETIQUETAXML = 'Validado';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Emplazamiento_Validado' WHERE ID='212' AND ETIQUETAXML = 'Validado';

--Nuevo Índice por etiquetaxml en campo dato
CREATE UNIQUE INDEX ADCAMPODATO6 ON ADCAMPODATO (ETIQUETAXML);

--Modificado el tamaño del nombre del formato
ALTER TABLE ADFMTFICHA ALTER COLUMN NOMBRE TYPE VARCHAR(128) NOT NULL;

--Modificar el NUMORDEN de para que no tenga tamaño fijo
ALTER TABLE ASGDDEPOSITO MODIFY NUMORDEN NUMBER NOT NULL;
ALTER TABLE ASGDELEMNOASIG MODIFY NUMORDEN NUMBER NOT NULL;
ALTER TABLE ASGDSIGNUMORDEN MODIFY NUMORDEN NUMBER NOT NULL;

ALTER TABLE ASGTRENTREGA MODIFY ESTADO NUMBER(2) NOT NULL;

--Nuevo Rol para el servicio web de transferencias
INSERT INTO ASCAROL (ID,NOMBRE, TIPOMODULO,DESCRIPCION)
VALUES('ID_ROL_WS_TRANSFERENCIAS','Servicio Web de Transferencias de Expedientes','2','Permisos necesarios para la ejecución del servicio web de transferencias');

-- Servicio Web de Transferencias

--Ampliado de Elaboración de Transferencias Ordinarias
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,201);

--Ubicación de Relaciones de Entrega
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,207);

-- Consulta de Cuadro de Clasificación
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,500);

--Solicitud de Alta de Serie
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,501);

-- Gestor de Serie
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,502);

-- Gestión de Solicitudes de Serie
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,503);

-- Creación en el Cuadro de Clasificación
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,505);

-- Consulta de Descripción en el Cuadro de Clasificación
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,600);

-- Edición de Descripción en el Cuadro de Clasificación
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,601);

-- Administración de Descripción
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,606);

-- Uso de Ficha Descriptiva en Altas/Relaciones
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,607);

--Administración de Usuarios, Órganos, Grupos y Perfiles
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,701);

-- Consulta de Documentos Electrónicos
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,900);

--Edición de Documentos Electrónicos
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,901);

--Tabla de Firmas
INSERT INTO ADCAMPOTBL (ID,NOMBRE,TIPONORMA,IDAREA,ETIQUETAXML, ETIQXMLFILA)
VALUES ('105','Firmas',1,'3','Firmas','Firma');

--Norma ENI
INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1001','Versión NTI',1,'1','3',NULL,NULL,'Version_NTI');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1002','Estado',1,'1','3',NULL,NULL,'Estado');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1003','Tipo de Firma',1,'1','3','105',1,'Tipo_Firma');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1004','Valor_CSV',2,'1','3','105',2,'Valor_CSV');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1005','Definición de Generación CSV',1,'1','3','105',3,'Definicion_Generacion_CSV');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1006','Identificador interno Firma',1,'1','3','105',4,'Id_Interno_Firma');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1011','Documento Electrónico: Versión NTI',1,'1','3','6',3, 'Documento_Electronico_Version_NTI');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1012','Documento Electrónico: Órgano',5,'1','3','6',4,'Documento_Electronico_Organo');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1013','Documento Electrónico: Fecha de Captura',3,'1','3','6',5,'Documento_Electronico_Fecha_Captura');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1014','Documento Electrónico: Origen',1,'1','3','6',6,'Documento_Electronico_Origen');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1015','Documento Electrónico: Estado Elaboración',1,'1','3','6',7,'Documento_Electronico_Estado_Elaboracion');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1016','Documento Electrónico: Nombre Formato',1,'1','3','6',8,'Documento_Electronico_Nombre_Formato');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1017','Documento Electrónico: Tipo Documental',1,'1','3','6',9,'Documento_Electronico_Tipo_Documental');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1018','Documento Electrónico: Tipo Firma',1,'1','3','6',10,'Documento_Electronico_Tipo_Firma');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1019','Documento Electrónico: Valor CSV',2,'1','3','6',11,'Documento_Electronico_Valor_CSV');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1020','Documento Electrónco: Definición Generación CSV',2,'1','3','6',12,'Documento_Electronico_Definicion_Generacion_CSV');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1021','Documento Electronico: Identificador Documento Origen',1,'1','3','6',13,'Documento_Electronico_Identificador_Documento_Origen');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1022','Documento Electrónico: Id Interno',1,'1','3','6',14,'Documento_Electronico_Id_Interno');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1023','Documento Electrónico: Identificador interno Firma',1,'1','3','6',15,'Documento_Electronico_Id_Interno_Firma');
