--/***************************/
--/* Versión 3.4             */
--/***************************/

--  Crear tablas para el conector de organización

CREATE TABLE AOESTRORG(
	ID               VARCHAR2(32) NOT NULL,
	CODIGO           VARCHAR2(64) NOT NULL,
	NOMBRE           VARCHAR2(254) NOT NULL,
	TIPO             NUMBER(38) NOT NULL,
	NIVEL            NUMBER(38) NOT NULL,
	IDORGPADRE       VARCHAR2(32),
	ESTADO           NUMBER(38) NOT NULL,
	FINICIOVIGENCIA  DATE,
	FFINVIGENCIA     DATE,
	DESCRIPCION      VARCHAR2(254)
);

CREATE TABLE AOUSR(
	ID             VARCHAR2(64) NOT NULL,
	DIRECCION      VARCHAR2(254),
	EMAIL          VARCHAR2(254),
	NOMBRE         VARCHAR2(64),
	APELLIDOS      VARCHAR2(128),
	NOMBREUSUARIO  VARCHAR2(64) NOT NULL,
	PASSWORD       VARCHAR2(64) NOT NULL
);

CREATE TABLE AOUSRORGV(
	IDUSUARIO      VARCHAR2(64) NOT NULL,
	NOMBREUSUARIO  VARCHAR2(254) NOT NULL,
	IDORGANO       VARCHAR2(32) NOT NULL
);

CREATE UNIQUE INDEX ORGANIZACION1 ON AOESTRORG (ID) TABLESPACE &1;
CREATE UNIQUE INDEX ORGANIZACION2 ON AOESTRORG (CODIGO) TABLESPACE &1;

CREATE INDEX USUARIO1 ON AOUSR (NOMBRE) TABLESPACE &1;
CREATE UNIQUE INDEX USUARIO2 ON AOUSR (NOMBREUSUARIO) TABLESPACE &1;

CREATE UNIQUE INDEX USRORGANO1 ON AOUSRORGV (IDUSUARIO) TABLESPACE &1;

DROP INDEX ASGTUDOCSDF2; 
CREATE UNIQUE INDEX ASGTUDOCSDF2 ON ASGTUDOCSDF (ID, IDRELENTREGA) TABLESPACE &1;

-- Actualizar el nombre de clasificador de serie de una ficha
UPDATE ADFICHA SET NOMBRE='ISAD(G) Nivel de Descripción Clasificador Serie' WHERE ID='3';

INSERT INTO AGINFOSISTEMA (AUTID,NOMBRE,VALOR,FECHAACTUALIZACION) VALUES (SEQ_INFO.NextVal,'VERSIONBD','3.4',SYSDATE);

COMMIT;