--
-- SCR_ATTACHMENT_SEQ
--

CREATE SEQUENCE SCR_ATTACHMENT_SEQ
 MINVALUE 1
 MAXVALUE 9223372036854775807
 INCREMENT BY 1
 START WITH 1
 ;


--
-- SCR_ATTACHMENT_SIGN_INFO_SEQ
--

CREATE SEQUENCE SCR_ATTACHMENT_SIGN_INFO_SEQ
 MINVALUE 1
 MAXVALUE 9223372036854775807
 INCREMENT BY 1
 START WITH 1
 ;


--
-- SCR_ENTITYREG_ID_SEQ
--

CREATE SEQUENCE SCR_ENTITYREG_ID_SEQ
 MINVALUE 1
 MAXVALUE 9223372036854775807
 INCREMENT BY 1
 START WITH 1
 ;


--
-- SCR_EXREGSTATE_ID_SEQ
--

CREATE SEQUENCE SCR_EXREGSTATE_ID_SEQ
 MINVALUE 1
 MAXVALUE 9223372036854775807
 INCREMENT BY 1
 START WITH 1
 ;


--
-- SCR_EXREG_ID_SEQ
--

CREATE SEQUENCE SCR_EXREG_ID_SEQ
 MINVALUE 1
 MAXVALUE 9223372036854775807
 INCREMENT BY 1
 START WITH 1
 ;


--
-- SCR_EXREG_IN_ID_SEQ
--

CREATE SEQUENCE SCR_EXREG_IN_ID_SEQ
 MINVALUE 1
 MAXVALUE 9223372036854775807
 INCREMENT BY 1
 START WITH 1
 ;


--
-- SCR_TRAMUNIT_ID_SEQ
--

CREATE SEQUENCE SCR_TRAMUNIT_ID_SEQ
 MINVALUE 1
 MAXVALUE 9223372036854775807
 INCREMENT BY 1
 START WITH 1
 ;


--
-- IUSERDATA
--

CREATE TABLE IUSERDATA (ID             NUMBER NOT NULL,
                        CARGO          VARCHAR2(256 CHAR) NULL,
                        TFNO_MOVIL     VARCHAR2(16 CHAR) NULL,
                        ID_CERTIFICADO VARCHAR2(256 CHAR) NULL,
                        EMAIL          VARCHAR2(256 CHAR) NULL,
                        NOMBRE         VARCHAR2(256 CHAR) NULL,
                        APELLIDOS      VARCHAR2(256 CHAR) NULL);

CREATE UNIQUE INDEX PK_IUSERDATA ON IUSERDATA (ID ASC) ;

ALTER TABLE IUSERDATA ADD CONSTRAINT PK_IUSERDATA PRIMARY KEY (ID);


--
-- SCR_ATTACHMENT
--

CREATE TABLE SCR_ATTACHMENT (ID            NUMBER(10,0) NOT NULL,
                             BOOKID        NUMBER(10,0) NOT NULL,
                             FOLDERID      NUMBER(10,0) NOT NULL,
                             PAGEID        NUMBER(10,0) NOT NULL,
                             COMMENTS      VARCHAR2(50 CHAR) NULL,
                             MIME_TYPE     VARCHAR2(20 CHAR) NULL,
                             NAME          VARCHAR2(80 CHAR) NULL,
                             CODE_NAME     VARCHAR2(50 CHAR) NULL,
                             VALIDITY_TYPE NUMBER(10,0) NULL,
                             DOCUMENT_TYPE NUMBER(10,0) NULL)
 ;
CREATE UNIQUE INDEX PK_SCR_ATTACHMENT ON SCR_ATTACHMENT (ID ASC);

ALTER TABLE SCR_ATTACHMENT ADD CONSTRAINT PK_SCR_ATTACHMENT PRIMARY KEY (ID);


--
-- SCR_ATTACHMENT_DOCUMENT_TYPE
--

CREATE TABLE SCR_ATTACHMENT_DOCUMENT_TYPE (ID   NUMBER(10,0) NOT NULL,
                                           NAME VARCHAR2(250 CHAR) NULL,
                                           CODE VARCHAR2(2 CHAR) NULL);

CREATE UNIQUE INDEX PK_ATTACHMENT_DOCUMENT_TYPE ON SCR_ATTACHMENT_DOCUMENT_TYPE (ID ASC);

ALTER TABLE SCR_ATTACHMENT_DOCUMENT_TYPE ADD CONSTRAINT PK_ATTACHMENT_DOCUMENT_TYPE PRIMARY KEY (ID);

--
-- SCR_ATTACHMENT_SIGN_INFO
--

CREATE TABLE SCR_ATTACHMENT_SIGN_INFO (ID                   NUMBER(10,0) NOT NULL,
                                       ID_ATTACHMENT        NUMBER(10,0) NOT NULL UNIQUE,
                                       ID_ATTACHMENT_SIGNED NUMBER(10,0) NULL,
                                       CERT                 BLOB NULL,
                                       SIGNATURE            BLOB NULL,
                                       SIGNATURE_ALG        VARCHAR2(2 CHAR) NULL,
                                       SIGNATURE_FORMAT     VARCHAR2(2 CHAR) NULL,
                                       TIME_SIGNATURE       BLOB NULL,
                                       OCSP_VALIDATION      BLOB NULL,
                                       HASH_ALG             VARCHAR2(2 CHAR) NULL,
                                       HASH                 BLOB NULL);


CREATE UNIQUE INDEX PK_ATTACHMENT_SIGN_INFO ON SCR_ATTACHMENT_SIGN_INFO (ID ASC);

ALTER TABLE SCR_ATTACHMENT_SIGN_INFO ADD CONSTRAINT PK_ATTACHMENT_SIGN_INFO PRIMARY KEY (ID);

ALTER TABLE SCR_ATTACHMENT_SIGN_INFO ADD CONSTRAINT SYS_C00196999 UNIQUE (ID_ATTACHMENT);

--
-- SCR_ATTACHMENT_VALIDITY_TYPE
--

CREATE TABLE SCR_ATTACHMENT_VALIDITY_TYPE (ID   NUMBER(10,0) NOT NULL,
                                           NAME VARCHAR2(250 CHAR) NULL,
                                           CODE VARCHAR2(2 CHAR) NULL);

CREATE UNIQUE INDEX PK_ATTACHMENT_VALIDITY_TYPE ON SCR_ATTACHMENT_VALIDITY_TYPE (ID ASC);

ALTER TABLE SCR_ATTACHMENT_VALIDITY_TYPE ADD CONSTRAINT PK_ATTACHMENT_VALIDITY_TYPE PRIMARY KEY (ID);

--
-- SCR_BOOKSLANG
--

ALTER TABLE SCR_BOOKSLANG MODIFY NAME VARCHAR2(250 CHAR);

--
-- SCR_CITIES
--

ALTER TABLE SCR_CITIES ADD CONSTRAINT PK_CITIES PRIMARY KEY (ID);

--
-- SCR_CITIESEXREG
--

CREATE TABLE SCR_CITIESEXREG (ID      NUMBER(10,0) NOT NULL,
                              CODE    VARCHAR2(5 CHAR) NOT NULL,
                              NAME    VARCHAR2(80 CHAR) NOT NULL,
                              ID_CITY NUMBER(10,0) NOT NULL);

CREATE UNIQUE INDEX PK_SCR_CITIESEXREG ON SCR_CITIESEXREG (ID ASC);

ALTER TABLE SCR_CITIESEXREG ADD CONSTRAINT PK_SCR_CITIESEXREG PRIMARY KEY (ID);

--
-- SCR_COUNTRY
--

CREATE TABLE SCR_COUNTRY (ID      NUMBER(10,0) NOT NULL,
                          TMSTAMP DATE NOT NULL,
                          CODE    VARCHAR2(16 CHAR) NOT NULL,
                          NAME    VARCHAR2(50 CHAR) NOT NULL);

--
-- SCR_DOM
--

ALTER TABLE SCR_DOM MODIFY ADDRESS VARCHAR2(160 CHAR);
ALTER TABLE SCR_DOM ADD PAIS VARCHAR2(50 CHAR);


--
-- SCR_ENTITYREG
--

CREATE TABLE SCR_ENTITYREG (ID      NUMBER(10,0) NOT NULL,
                            CODE    VARCHAR2(21 CHAR) NOT NULL,
                            NAME    VARCHAR2(80 CHAR) NOT NULL,
                            ID_OFIC NUMBER(10,0) NOT NULL);

CREATE UNIQUE INDEX PK_SCR_ENTITYREG ON SCR_ENTITYREG (ID ASC);

ALTER TABLE SCR_ENTITYREG ADD CONSTRAINT PK_SCR_ENTITYREG PRIMARY KEY (ID);


--
-- SCR_EXREG
--

CREATE TABLE SCR_EXREG (ID              NUMBER(10,0) NOT NULL,
                        ID_ARCH         NUMBER(10,0) NOT NULL,
                        ID_FDR          NUMBER(10,0) NOT NULL,
                        ID_OFIC         NUMBER(10,0) NOT NULL,
                        TYPE_ORIG       NUMBER(10,0) NOT NULL,
                        EXCHANGE_DATE   DATE NULL,
                        STATE           NUMBER(10,0) NOT NULL,
                        STATE_DATE      DATE NOT NULL,
                        ID_EXCHANGE_SIR VARCHAR2(33 CHAR) NULL,
                        ID_EXCHANGE     NUMBER(10,0) NOT NULL,
                        USERNAME        VARCHAR2(32 CHAR) NOT NULL,
                        CODE_TRAMUNIT   VARCHAR2(21 CHAR) NULL,
                        NAME_TRAMUNIT   VARCHAR2(80 CHAR) NULL,
                        CODE_ENTITY     VARCHAR2(21 CHAR) NOT NULL,
                        NAME_ENTITY     VARCHAR2(80 CHAR) NOT NULL,
                        COMMENTS        VARCHAR2(4000 CHAR) NULL);

CREATE UNIQUE INDEX PK_SCR_EXREG ON SCR_EXREG (ID ASC);

ALTER TABLE SCR_EXREG ADD CONSTRAINT PK_SCR_EXREG PRIMARY KEY (ID);


--
-- SCR_EXREGSTATE
--

CREATE TABLE SCR_EXREGSTATE (ID         NUMBER(10,0) NOT NULL,
                             ID_EXREG   NUMBER(10,0) NOT NULL,
                             STATE      NUMBER(10,0) NOT NULL,
                             STATE_DATE DATE NOT NULL,
                             USERNAME   VARCHAR2(32 CHAR) NOT NULL,
                             COMMENTS   VARCHAR2(4000 CHAR) NULL)
                             ;
CREATE UNIQUE INDEX PK_SCR_EXREGSTATE ON SCR_EXREGSTATE (ID ASC);

ALTER TABLE SCR_EXREGSTATE ADD CONSTRAINT PK_SCR_EXREGSTATE PRIMARY KEY (ID);



--
-- SCR_EXREG_IN
--

CREATE TABLE SCR_EXREG_IN (ID              NUMBER(10,0) NOT NULL,
                           ID_ARCH         NUMBER(10,0) NULL,
                           ID_FDR          NUMBER(10,0) NULL,
                           ID_OFIC         NUMBER(10,0) NOT NULL,
                           EXCHANGE_DATE   DATE NOT NULL,
                           STATE           NUMBER(10,0) NOT NULL,
                           STATE_DATE      DATE NOT NULL,
                           ID_EXCHANGE_SIR VARCHAR2(33 CHAR) NOT NULL,
                           ID_EXCHANGE     NUMBER(10,0) NOT NULL,
                           USERNAME        VARCHAR2(32 CHAR) NOT NULL,
                           CODE_TRAMUNIT   VARCHAR2(21 CHAR) NULL,
                           NAME_TRAMUNIT   VARCHAR2(80 CHAR) NULL,
                           CODE_ENTITY     VARCHAR2(21 CHAR) NOT NULL,
                           NAME_ENTITY     VARCHAR2(80 CHAR) NOT NULL,
                           NUM_REG_ORIG    VARCHAR2(20 CHAR) NOT NULL,
                           CONTACTO_ORIG   VARCHAR2(160 CHAR) NULL,
                           COMMENTS        VARCHAR2(4000 CHAR) NULL);

CREATE UNIQUE INDEX PK_SCR_EXREG_IN ON SCR_EXREG_IN (ID ASC);

ALTER TABLE SCR_EXREG_IN ADD CONSTRAINT PK_SCR_EXREG_IN PRIMARY KEY (ID);
--
-- SCR_PAGEREPOSITORY
--

ALTER TABLE SCR_PAGEREPOSITORY ADD ID_PAGETYPE NUMBER DEFAULT 0 NOT NULL;


--
-- SCR_PAGETYPE
--

CREATE TABLE SCR_PAGETYPE (ID   NUMBER NOT NULL,
                           NAME VARCHAR2(100 CHAR) NOT NULL);

CREATE UNIQUE INDEX PK_PAGETYPE ON SCR_PAGETYPE (ID ASC);

ALTER TABLE SCR_PAGETYPE ADD CONSTRAINT PK_PAGETYPE PRIMARY KEY (ID);

--
-- SCR_PFIS
--

ALTER TABLE SCR_PFIS MODIFY FIRST_NAME VARCHAR2(30 CHAR);
ALTER TABLE SCR_PFIS MODIFY SECOND_NAME VARCHAR2(30 CHAR);
ALTER TABLE SCR_PFIS MODIFY SURNAME VARCHAR2(30 CHAR);

--
-- SCR_PJUR
--

ALTER TABLE SCR_PJUR MODIFY NAME VARCHAR2(80 CHAR);

--
-- SCR_REGINT
--

ALTER TABLE SCR_REGINT MODIFY NAME VARCHAR2(95 CHAR);

--
-- SCR_PROV
--
ALTER TABLE SCR_PROV ADD CONSTRAINT PK_PROV PRIMARY KEY (ID);

--
-- SCR_PROVEXREG
--
CREATE TABLE SCR_PROVEXREG (ID      NUMBER(10,0) NOT NULL,
                            CODE    VARCHAR2(2 CHAR) NOT NULL,
                            NAME    VARCHAR2(80 CHAR) NOT NULL,
                            ID_PROV NUMBER(10,0) NOT NULL);

CREATE UNIQUE INDEX PK_SCR_PROVEXREG ON SCR_PROVEXREG (ID ASC);

ALTER TABLE SCR_PROVEXREG ADD CONSTRAINT PK_SCR_PROVEXREG PRIMARY KEY (ID);


--
-- SCR_REPRE
--

CREATE TABLE SCR_REPRE (ID               NUMBER(10,0) NOT NULL,
                        ID_REPRESENTANTE NUMBER(10,0) NOT NULL,
                        ID_REPRESENTADO  NUMBER(10,0) NOT NULL,
                        ID_ADDRESS       NUMBER(10,0) NULL,
                        NAME             VARCHAR2(95 CHAR) NOT NULL);


--
-- SCR_TRAMUNIT
--

CREATE TABLE SCR_TRAMUNIT (ID            NUMBER(10,0) NOT NULL,
                           CODE_TRAMUNIT VARCHAR2(21 CHAR) NULL,
                           NAME_TRAMUNIT VARCHAR2(80 CHAR) NULL,
                           CODE_ENTITY   VARCHAR2(21 CHAR) NULL,
                           NAME_ENTITY   VARCHAR2(80 CHAR) NULL,
                           ID_ORGS       NUMBER(10,0) NOT NULL);

CREATE UNIQUE INDEX PK_SCR_TRAMUNIT ON SCR_TRAMUNIT (ID ASC);

CREATE UNIQUE INDEX U_CODE_TRAMUNIT ON SCR_TRAMUNIT (CODE_TRAMUNIT ASC);

ALTER TABLE SCR_TRAMUNIT ADD CONSTRAINT U_CODE_TRAMUNIT UNIQUE (CODE_TRAMUNIT);

ALTER TABLE SCR_TRAMUNIT ADD CONSTRAINT PK_SCR_TRAMUNIT PRIMARY KEY (ID);


--
-- SCR_USERFILTER
--

DROP INDEX SCR_USERFILTER2;
CREATE UNIQUE INDEX SCR_USERFILTER2 ON SCR_USERFILTER (IDARCH ASC, IDUSER ASC, TYPE_OBJ ASC);

--
-- FOREIGN KEYS [CREATE]
--

ALTER TABLE SCR_ATTACHMENT ADD CONSTRAINT FK_DOCUMENT_TYPE_ATTACHMENT FOREIGN KEY (DOCUMENT_TYPE) REFERENCES SCR_ATTACHMENT_DOCUMENT_TYPE (ID);
ALTER TABLE SCR_ATTACHMENT ADD CONSTRAINT FK_VALIDITY_TYPE_ATTACHMENT FOREIGN KEY (VALIDITY_TYPE) REFERENCES SCR_ATTACHMENT_VALIDITY_TYPE (ID);
ALTER TABLE SCR_ATTACHMENT_SIGN_INFO ADD CONSTRAINT FK_SIGN_INFO_ATTACHMENT_SIGNED FOREIGN KEY (ID_ATTACHMENT_SIGNED) REFERENCES SCR_ATTACHMENT (ID);
ALTER TABLE SCR_ATTACHMENT_SIGN_INFO ADD CONSTRAINT FK_SIGN_INFO_ATTACHMENT FOREIGN KEY (ID_ATTACHMENT) REFERENCES SCR_ATTACHMENT (ID);
ALTER TABLE SCR_CITIESEXREG ADD CONSTRAINT FK_CITIESEXREGCITIES FOREIGN KEY (ID_CITY) REFERENCES SCR_CITIES (ID);
ALTER TABLE SCR_ENTITYREG ADD CONSTRAINT FK_ENTITYOFIC FOREIGN KEY (ID_OFIC) REFERENCES SCR_OFIC (ID);
ALTER TABLE SCR_PAGEREPOSITORY ADD CONSTRAINT FK_PAGEREPOSITORY0 FOREIGN KEY (ID_PAGETYPE) REFERENCES SCR_PAGETYPE (ID);
ALTER TABLE SCR_PROVEXREG ADD CONSTRAINT FK_PROVEXREGPROV FOREIGN KEY (ID_PROV) REFERENCES SCR_PROV (ID);
ALTER TABLE SCR_TRAMUNIT ADD CONSTRAINT FK_TRAMUNITGORGS FOREIGN KEY (ID_ORGS) REFERENCES SCR_ORGS (ID);
