--/*************************/
--/* Versión 4.7           */
--/*************************/

spool actualizacion47.log

INSERT INTO AGINFOSISTEMA (AUTID,NOMBRE,VALOR,FECHAACTUALIZACION) VALUES (SEQ_INFO.NextVal,'VERSIONBD','4.5->4.7',SYSDATE);

--Catalogo de Tablas Temporales
CREATE TABLE ASGFCTLGTBLTMP(
	ID NUMERIC(5)NOT NULL,
	NOMBRETABLA VARCHAR2(16) NOT NULL,
	IDUSUARIO VARCHAR2(32),
	ESTADO NUMERIC(1) default 0,
	FECHA DATE
);

CREATE UNIQUE INDEX ASGFCTLGTBLTMP1 ON ASGFCTLGTBLTMP(ID) TABLESPACE &1;
CREATE UNIQUE INDEX ASGFCTLGTBLTMP2 ON ASGFCTLGTBLTMP(NOMBRETABLA) TABLESPACE &1;

CREATE UNIQUE INDEX ASGFFONDO2 ON ASGFFONDO(CODARCHIVO,IDENTPRODUCTORA) TABLESPACE &1;

COMMIT;

spool off