--/*************************/
--/* Versión 4.8 > 5.0     */
--/*************************/

spool actualizacion50.log


INSERT INTO AGINFOSISTEMA (AUTID,NOMBRE,VALOR,FECHAACTUALIZACION) VALUES (SEQ_INFO.NextVal,'VERSIONBD','4.8->5.0',SYSDATE);

--Renombrar IDLVOLPREF a IDREPECMPREF
ALTER TABLE ADCTLGLISTAD RENAME COLUMN IDLVOLPREF TO IDREPECMPREF;

--Renombrar IDLVOL a IDREPECM
ALTER TABLE ADDESCRIPTOR RENAME COLUMN IDLVOL TO IDREPECM;

--Renombrar IDLVOL a IDREPECM
ALTER TABLE ASGFELEMENTOCF RENAME COLUMN IDLVOL TO IDREPECM;

--Renombrar IDLVOLPREF a IDREPECMPREF
ALTER TABLE ASGFNIVELCF RENAME COLUMN IDLVOLPREF TO IDREPECMPREF;

--Renombrar INFOFICHAUDOCLVOL a INFOFICHAUDOCREPECM
ALTER TABLE ASGFSERIE RENAME COLUMN INFOFICHAUDOCLVOL TO INFOFICHAUDOCREPECM;

--Añadir campo IdRepEcm
ALTER TABLE ADOCDOCUMENTODESCR ADD IDREPECM VARCHAR2(32);

--Añadir campo IdRepEcm
ALTER TABLE ADOCDOCUMENTOCF ADD IDREPECM VARCHAR2(32);
--Añadir campo IdRepEcm
ALTER TABLE ADPCDOCUMENTOVIT ADD IDREPECM VARCHAR2(32);

--Cambiar Tamaño de IDFICH a 128
ALTER TABLE ADPCDOCUMENTOVIT MODIFY IDFICH	VARCHAR2(128);

--Añadir el campo subtiponivel
ALTER TABLE ADFICHA ADD (SUBTIPONIVEL INTEGER DEFAULT 0 NOT NULL);

--Actualizar los valores de subtiponivel
UPDATE ADFICHA SET SUBTIPONIVEL=61 WHERE ID='1';
UPDATE ADFICHA SET SUBTIPONIVEL=62 WHERE ID='6';


--Nuevo Índice por etiquetaxml en campo tabla
CREATE UNIQUE INDEX ADCAMPOTBL5 ON ADCAMPOTBL (ETIQUETAXML) TABLESPACE &1;

UPDATE ADCAMPODATO SET ETIQUETAXML = 'Documento_Fisico_Descripcion' WHERE ID='43' AND ETIQUETAXML = 'Descripcion';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Documento_Electronico_Descripcion' WHERE ID='50' AND ETIQUETAXML = 'Descripcion';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Identificacion' WHERE ID='1' AND ETIQUETAXML = 'Identificador';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Identificador_Recurso' WHERE ID='131' AND ETIQUETAXML = 'Identificador';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Entidad_Relacionada_Nombre' WHERE ID='114' AND ETIQUETAXML = 'Nombre';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Documento_Fisico_Nombre' WHERE ID='19' AND ETIQUETAXML = 'Nombre';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Productor_Nombre' WHERE ID='34' AND ETIQUETAXML = 'Nombre';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Documento_Electronico_Nombre' WHERE ID='49' AND ETIQUETAXML = 'Nombre';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Entidad_Relacionada_Tipo_Relacion' WHERE ID='115' AND ETIQUETAXML = 'Tipo_Relacion';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Naturaleza_Relacion' WHERE ID='133' AND ETIQUETAXML = 'Tipo_Relacion';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Interesado_Validado' WHERE ID='12' AND ETIQUETAXML = 'Validado';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Emplazamiento_Validado' WHERE ID='212' AND ETIQUETAXML = 'Validado';

--Nuevo Índice por etiquetaxml en campo dato
CREATE UNIQUE INDEX ADCAMPODATO6 ON ADCAMPODATO (ETIQUETAXML) TABLESPACE &1;

--Modificado el tamaño del nombre del formato
ALTER TABLE ADFMTFICHA MODIFY NOMBRE VARCHAR(128) NOT NULL;

--Modificar el NUMORDEN de para que no tenga tamaño fijo
ALTER TABLE ASGDDEPOSITO MODIFY NUMORDEN NUMBER NOT NULL;
ALTER TABLE ASGDELEMNOASIG MODIFY NUMORDEN NUMBER NOT NULL;
ALTER TABLE ASGDSIGNUMORDEN MODIFY NUMORDEN NUMBER NOT NULL;

ALTER TABLE ASGTRENTREGA MODIFY ESTADO NUMBER(2) NOT NULL;

spool off