/******************************************************************************************************/
/* Versión 2.0 */
/******************************************************************************************************/

-- Añadir a ASGFVALSERIE un campo justificación de dictamen
	ALTER TABLE asgfvalserie ADD valordictjust CLOB;

-- Eliminar el campo PDTEASIGNARUI de la tabla ASGTUNIDADDOCRE
	ALTER TABLE ASGTUNIDADDOCRE DROP (PDTEASIGNARUI);

--Cambio del campo TIPO de VARCHAR(5) a CHAR(1) DE LA TABLA ASCAUSUARIO
	ALTER TABLE ASCAUSUARIO ADD (TIPON CHAR(1) DEFAULT '0' NOT NULL );

	UPDATE ASCAUSUARIO SET TIPON = SUBSTR(TIPO,0,1);

	COMMIT;

  ALTER TABLE ASCAUSUARIO DROP (TIPO);

	ALTER TABLE ASCAUSUARIO ADD (TIPO CHAR(1) DEFAULT '0' NOT NULL );

	UPDATE ASCAUSUARIO SET TIPO = TIPON;

	ALTER TABLE ASCAUSUARIO DROP (TIPON);

	COMMIT;


--Cambio del Nombre de Columna SYSTABLE por USOINTERNO TABLA ADCTLGTBLVLD
	ALTER TABLE ADCTLGTBLVLD RENAME COLUMN SYSTABLE TO USOINTERNO;

--Cambios de Tamaño
	ALTER TABLE ASGFUNIDADDOC MODIFY NUMEXP	VARCHAR2(128); --Cambiado de VARCHAR2(32) a VARCHAR2(128)

	--Tabla ADOCDOCUMENTOCF
	ALTER TABLE ADOCDOCUMENTOCF MODIFY IDFICH	VARCHAR2(128); --Cambiado de VARCHAR2(32) a VARCHAR2(128)

	--Tabla ADOCDOCUMENTODESCR
	ALTER TABLE ADOCDOCUMENTODESCR MODIFY IDFICH	VARCHAR2(128); --Cambiado de VARCHAR2(32) a VARCHAR2(128)

	--Tabla ADOCCLASIFDESCR
	ALTER TABLE ADOCCLASIFDESCR MODIFY DESCRIPCION	VARCHAR2(254); --Cambiado de VARCHAR2(128) a VARCHAR2(254)



-- Cambio de Columnas para que no permitan valores nulos
	--TABLA ASCAUSUARIO
	ALTER TABLE ASCAUSUARIO
		MODIFY NOMBRE	VARCHAR2(254) NOT NULL
		MODIFY HABILITADO	CHAR(1) NOT NULL
		MODIFY IDUSRSEXTGESTOR	VARCHAR2(64) NOT NULL;

	-- Tabla ASGFUNIDADDOC
	ALTER TABLE ASGFUNIDADDOC
		MODIFY IDELEMENTOCF	VARCHAR2(32) NOT NULL
		MODIFY IDSERIE	VARCHAR2(32) NOT NULL
		MODIFY IDFONDO	VARCHAR2(32) NOT NULL;


-- Actualización de la Tabla ASGFSERIE
	--Actualización de la columna VOLUMEN a 0 los que tengan nulo.
	UPDATE ASGFSERIE SET VOLUMEN = 0 WHERE VOLUMEN IS NULL
	UPDATE ASGFSERIE SET FECHAESTADO = SYSDATE WHERE FECHAESTADO IS NULL;

	ALTER TABLE ASGFSERIE
		MODIFY IDFONDO	VARCHAR2(32) NOT NULL
		MODIFY ESTADOSERIE	NUMBER(2) NOT NULL
		MODIFY FECHAESTADO	DATE NOT NULL
		MODIFY NUMUNIDADDOC	NUMBER(10) NOT NULL
		MODIFY NUMUINSTALACION	NUMBER(10) NOT NULL
		MODIFY VOLUMEN	NUMBER NOT NULL;