-- TABLAS
DROP TABLE SGL_OBRAS_MENORES;
DROP TABLE SGQ_QUEJAS;
DROP TABLE SGS_SUBVENCIONES;
DROP TABLE SPAC_TBL_010;
DROP TABLE SPAC_TBL_011;
DROP TABLE SPAC_TBL_012;
DROP TABLE SPAC_TBL_013;

-- SECUENCIAS
DROP SEQUENCE sgl_sq_id_obras_menores;
DROP SEQUENCE sgq_sq_id_quejas;
DROP SEQUENCE sgs_sq_id_subvenciones;
DROP SEQUENCE spac_sq_spac_tbl_010;
DROP SEQUENCE spac_sq_spac_tbl_011;
DROP SEQUENCE spac_sq_spac_tbl_012;
DROP SEQUENCE spac_sq_spac_tbl_013;