----------------
-- SECUENCIAS --
----------------

CREATE SEQUENCE sgl_sq_id_obras_menores INCREMENT BY 1 NO MAXVALUE NO MINVALUE CACHE 1;
CREATE SEQUENCE sgq_sq_id_quejas INCREMENT BY 1 NO MAXVALUE NO MINVALUE CACHE 1;
CREATE SEQUENCE sgs_sq_id_subvenciones INCREMENT BY 1 NO MAXVALUE NO MINVALUE CACHE 1;
CREATE SEQUENCE spac_sq_spac_tbl_010 INCREMENT BY 1 NO MAXVALUE NO MINVALUE CACHE 1;
CREATE SEQUENCE spac_sq_spac_tbl_011 INCREMENT BY 1 NO MAXVALUE NO MINVALUE CACHE 1;
CREATE SEQUENCE spac_sq_spac_tbl_012 INCREMENT BY 1 NO MAXVALUE NO MINVALUE CACHE 1;
CREATE SEQUENCE spac_sq_spac_tbl_013 INCREMENT BY 1 NO MAXVALUE NO MINVALUE CACHE 1;




