IF OBJECT_ID('dbo.GREATEST') IS NOT NULL BEGIN
	DROP FUNCTION dbo.GREATEST
END

IF OBJECT_ID('dbo.IdsDescendientesNoAsignable') IS NOT NULL BEGIN
	DROP PROCEDURE dbo.IdsDescendientesNoAsignable
END

IF OBJECT_ID('dbo.DEVOLVERMARCA') IS NOT NULL BEGIN
	DROP FUNCTION dbo.DEVOLVERMARCA
END

IF OBJECT_ID('dbo.CALCULARFINALCODREFPADRE') IS NOT NULL BEGIN
	DROP FUNCTION dbo.CALCULARFINALCODREFPADRE
END

IF OBJECT_ID('dbo.GETNUMERICPOSITIVE') IS NOT NULL BEGIN
	DROP FUNCTION dbo.GETNUMERICPOSITIVE
END
