-------------
-- SISTEMA --
-------------

-- Tabla: AGFORMATO
DROP INDEX AGFORMATO1 ON AGFORMATO;
DROP INDEX AGFORMATO2 ON AGFORMATO;

-- Tabla: AGARCHIVO
DROP INDEX AGARCHIVO1 ON AGARCHIVO;

-- Tabla: AGNIVELARCHIVO
DROP INDEX AGNIVELARCHIVO01 ON AGNIVELARCHIVO;
DROP INDEX AGNIVELARCHIVO02 ON AGNIVELARCHIVO;

-- Tabla: AGOBJBLOQUEO
DROP INDEX AGOBJBLOQUEO1 ON AGOBJBLOQUEO;

-- Tabla: AGINFOSISTEMA
DROP INDEX AGINFOSISTEMA1 ON AGINFOSISTEMA;

-----------------------
-- CONTROL DE ACCESO --
-----------------------
-- Tabla: ASCAUSUARIO
DROP INDEX ASCAUSUARIO1 ON ASCAUSUARIO;

-- Tabla: ASCAORGANO
DROP INDEX ASCAORGANO1 ON ASCAORGANO;
DROP INDEX ASCAORGANO2 ON ASCAORGANO;
DROP INDEX ASCAORGANO3 ON ASCAORGANO;

-- Tabla: ASCAUSRORG
DROP INDEX ASCAUSRORG1 ON ASCAUSRORG;

-- Tabla:  ASCAGRUPO
DROP INDEX ASCAGRUPO1 ON ASCAGRUPO;
DROP INDEX ASCAGRUPO2 ON ASCAGRUPO;

-- Tabla: ASCAUSRGRP
DROP INDEX ASCAUSRGRP1 ON ASCAUSRGRP;
DROP INDEX ASCAUSRGRP2 ON ASCAUSRGRP;

-- Tabla: ASCAROL
DROP INDEX ASCAROL1 ON ASCAROL;
DROP INDEX ASCAROL2 ON ASCAROL;

-- Tabla: ASCAPERMGENROL
DROP INDEX ASCAPERMGENROL1 ON ASCAPERMGENROL;
DROP INDEX ASCAPERMGENROL2 ON ASCAPERMGENROL;

-- Tabla: ASCAROLUSR
DROP INDEX ASCAROLUSR1 ON ASCAROLUSR;
DROP INDEX ASCAROLUSR2 ON ASCAROLUSR;

-- Tabla: ASCALISTCA
DROP INDEX ASCALISTCA1 ON ASCALISTCA;
DROP INDEX ASCALISTCA2 ON ASCALISTCA;

-- Tabla: ASCAPERMLISTCA
DROP INDEX ASCAPERMLISTCA1 ON ASCAPERMLISTCA;
DROP INDEX ASCAPERMLISTCA2 ON ASCAPERMLISTCA;
DROP INDEX ASCAPERMLISTCA3 ON ASCAPERMLISTCA;

--------------------
-- TRANSFERENCIAS --
--------------------

-- Tabla: ASGTPREVISION --
DROP INDEX ASGTPREVISION1 ON ASGTPREVISION;
DROP INDEX ASGTPREVISION2 ON ASGTPREVISION;
DROP INDEX ASGTPREVISION3 ON ASGTPREVISION;
DROP INDEX ASGTPREVISION4 ON ASGTPREVISION;
DROP INDEX ASGTPREVISION5 ON ASGTPREVISION;

-- Tabla:  ASGTDETALLEPREV
DROP INDEX ASGTDETALLEPREV1 ON ASGTDETALLEPREV;
DROP INDEX ASGTDETALLEPREV2 ON ASGTDETALLEPREV;

-- Tabla: ASGTRENTREGA
DROP INDEX ASGTRENTREGA1 ON ASGTRENTREGA;
DROP INDEX ASGTRENTREGA2 ON ASGTRENTREGA;
DROP INDEX ASGTRENTREGA3 ON ASGTRENTREGA;
DROP INDEX ASGTRENTREGA4 ON ASGTRENTREGA;
DROP INDEX ASGTRENTREGA5 ON ASGTRENTREGA;
DROP INDEX ASGTRENTREGA6 ON ASGTRENTREGA;

-- Tabla: ASGTSNSEC
DROP INDEX ASGTSNSEC1 ON ASGTSNSEC;

-- Tabla: ASGTUNIDADDOCRE
DROP INDEX ASGTUNIDADDOCRE1 ON ASGTUNIDADDOCRE;
DROP INDEX ASGTUNIDADDOCRE2 ON ASGTUNIDADDOCRE;
DROP INDEX ASGTUNIDADDOCRE3 ON ASGTUNIDADDOCRE;
DROP INDEX ASGTUNIDADDOCRE4 ON ASGTUNIDADDOCRE;

--Tabla: ASGTUINSTALACIONRE
DROP INDEX ASGTUINSTALACIONRE1 ON ASGTUINSTALACIONRE;
DROP INDEX ASGTUINSTALACIONRE2 ON ASGTUINSTALACIONRE;

--Tabla: ASGTUINSTALACIONREEA
DROP INDEX ASGTUINSTALACIONREEA1 ON ASGTUINSTALACIONREEA;
DROP INDEX ASGTUINSTALACIONREEA2 ON ASGTUINSTALACIONREEA;

-- Tabla: ASGTUDOCENUI
DROP INDEX ASGTUDOCENUI1 ON ASGTUDOCENUI;
DROP INDEX ASGTUDOCENUI2 ON ASGTUDOCENUI;
DROP INDEX ASGTUDOCENUI3 ON ASGTUDOCENUI;

-- Tabla: ASGTUDOCSDF
DROP INDEX ASGTUDOCSDF1 ON ASGTUDOCSDF;
DROP INDEX ASGTUDOCSDF2 ON ASGTUDOCSDF;

--------------
-- DEPOSITO --
--------------

-- Tabla: ASGDTIPOELEMENTO
DROP INDEX ASGDTIPOELEMENTO1 ON ASGDTIPOELEMENTO;
DROP INDEX ASGDTIPOELEMENTO2 ON ASGDTIPOELEMENTO;

-- Tabla: ASGDDEPOSITO
DROP INDEX ASGDDEPOSITO1 ON ASGDDEPOSITO;
DROP INDEX ASGDDEPOSITO2 ON ASGDDEPOSITO;

-- Tabla: ASGDDEPOSITOELECTRONICO
DROP INDEX ASGDDEPOSITOELECTRONICO1 ON ASGDDEPOSITOELECTRONICO;

-- Tabla: ASGDELEMNOASIG
DROP INDEX ASGDELEMNOASIG1 ON ASGDELEMNOASIG;
DROP INDEX ASGDELEMNOASIG2 ON ASGDELEMNOASIG;
DROP INDEX ASGDELEMNOASIG3 ON ASGDELEMNOASIG;

-- Tabla: ASGDELEMASIG
DROP INDEX ASGDELEMASIG1 ON ASGDELEMASIG;
DROP INDEX ASGDELEMASIG2 ON ASGDELEMASIG;
DROP INDEX ASGDELEMASIG3 ON ASGDELEMASIG;
DROP INDEX ASGDELEMASIG4 ON ASGDELEMASIG;

-- Tabla: ASGDHUECO
DROP INDEX ASGDHUECO1 ON ASGDHUECO;
DROP INDEX ASGDHUECO2 ON ASGDHUECO;
DROP INDEX ASGDHUECO3 ON ASGDHUECO;
DROP INDEX ASGDHUECO4 ON ASGDHUECO;
DROP INDEX ASGDHUECO5 ON ASGDHUECO;
DROP INDEX ASGDHUECO6 ON ASGDHUECO;
DROP INDEX ASGDHUECO7 ON ASGDHUECO;
DROP INDEX ASGDHUECO8 ON ASGDHUECO;

-- Tabla: ASGDSIGNUMORDEN
DROP INDEX ASGDSIGNUMORDEN1 ON ASGDSIGNUMORDEN;

-- Tabla: ASGDUINSTALACION
DROP INDEX ASGDUINSTALACION1 ON ASGDUINSTALACION;
DROP INDEX ASGDUINSTALACION2 ON ASGDUINSTALACION;
DROP INDEX ASGDUINSTALACION3 ON ASGDUINSTALACION;

-- Tabla: ASGDHISTUINSTALACION
DROP INDEX ASGDHISTUINSTALACION1 ON ASGDHISTUINSTALACION;
DROP INDEX ASGDHISTUINSTALACION2 ON ASGDHISTUINSTALACION;
DROP INDEX ASGDHISTUINSTALACION3 ON ASGDHISTUINSTALACION;
DROP INDEX ASGDHISTUINSTALACION4 ON ASGDHISTUINSTALACION;

-- Tabla: ASGDUDOCENUI
DROP INDEX ASGDUDOCENUI1 ON ASGDUDOCENUI;
DROP INDEX ASGDUDOCENUI2 ON ASGDUDOCENUI;
DROP INDEX ASGDUDOCENUI3 ON ASGDUDOCENUI;
DROP INDEX ASGDUDOCENUI4 ON ASGDUDOCENUI;
DROP INDEX ASGDUDOCENUI5 ON ASGDUDOCENUI;

-----------------
-- SOLICUTUDES --
-----------------

-- Tabla: ASGPPRESTAMO
DROP INDEX ASGPPRESTAMO1 ON ASGPPRESTAMO;
DROP INDEX ASGPPRESTAMO2 ON ASGPPRESTAMO;
DROP INDEX ASGPPRESTAMO3 ON ASGPPRESTAMO;
DROP INDEX ASGPPRESTAMO4 ON ASGPPRESTAMO;

-- Tabla: ASGPMTVPRESTAMO
DROP INDEX ASGPMTVPRESTAMO1 ON ASGPMTVPRESTAMO;

-- Tabla:  ASGPSOLICITUDUDOC
DROP INDEX ASGPSOLICITUDUDOC1 ON ASGPSOLICITUDUDOC;
DROP INDEX ASGPSOLICITUDUDOC2 ON ASGPSOLICITUDUDOC;
DROP INDEX ASGPSOLICITUDUDOC3 ON ASGPSOLICITUDUDOC;
DROP INDEX ASGPSOLICITUDUDOC4 ON ASGPSOLICITUDUDOC;
DROP INDEX ASGPSOLICITUDUDOC5 ON ASGPSOLICITUDUDOC;

-- Tabla: ASGPSNSEC
DROP INDEX ASGPSNSEC1 ON ASGPSNSEC;

-- Tabla: ASGPPRORROGA
DROP INDEX ASGPPRORROGA1 ON ASGPPRORROGA;


-- Tabla: ASGPCSULTA
DROP INDEX ASGPCONSULTA1 ON ASGPCONSULTA;
DROP INDEX ASGPCONSULTA2 ON ASGPCONSULTA;
DROP INDEX ASGPCONSULTA3 ON ASGPCONSULTA;
DROP INDEX ASGPCONSULTA4 ON ASGPCONSULTA;
DROP INDEX ASGPCONSULTA5 ON ASGPCONSULTA;
DROP INDEX ASGPCONSULTA6 ON ASGPCONSULTA;

-- Tabla: ASGPMTVCONSULTA
DROP INDEX ASGPMTVCONSULTA1 ON ASGPMTVCONSULTA;
DROP INDEX ASGPMTVCONSULTA2 ON ASGPMTVCONSULTA;

-- Tabla: ASGPMTVRECHAZO
DROP INDEX ASGPMTVRECHAZO1 ON ASGPMTVRECHAZO;
DROP INDEX ASGPMTVRECHAZO2 ON ASGPMTVRECHAZO;

-- Tabla: ASGPTEMA
DROP INDEX ASGPTEMA1 ON ASGPTEMA;

-- ASGPREVDOCUDOC
DROP INDEX ASGPREVDOCUDOC1 ON ASGPREVDOCUDOC;
DROP INDEX ASGPREVDOCUDOC2 ON ASGPREVDOCUDOC;
DROP INDEX ASGPREVDOCUDOC3 ON ASGPREVDOCUDOC;

-----------------
-- DESCRIPCION --
-----------------

-- Tabla: ADAREA
DROP INDEX ADAREA1 ON ADAREA;
DROP INDEX ADAREA2 ON ADAREA;
DROP INDEX ADAREA3 ON ADAREA;

-- Tabla: ADCAMPOTBL
DROP INDEX ADCAMPOTBL1 ON ADCAMPOTBL;
DROP INDEX ADCAMPOTBL2 ON ADCAMPOTBL;
DROP INDEX ADCAMPOTBL3 ON ADCAMPOTBL;
DROP INDEX ADCAMPOTBL4 ON ADCAMPOTBL;
DROP INDEX ADCAMPOTBL5 ON ADCAMPOTBL;

-- Tabla: ADCAMPODATO
DROP INDEX ADCAMPODATO1 ON ADCAMPODATO;
DROP INDEX ADCAMPODATO2 ON ADCAMPODATO;
DROP INDEX ADCAMPODATO3 ON ADCAMPODATO;
DROP INDEX ADCAMPODATO4 ON ADCAMPODATO;
DROP INDEX ADCAMPODATO5 ON ADCAMPODATO;
DROP INDEX ADCAMPODATO6 ON ADCAMPODATO;

-- Tabla: ADFICHA
DROP INDEX ADFICHA1 ON ADFICHA;
DROP INDEX ADFICHA2 ON ADFICHA;
DROP INDEX ADFICHA3 ON ADFICHA;

-- Tabla: ADFMTFICHA
DROP INDEX ADFMTFICHA1 ON ADFMTFICHA;
DROP INDEX ADFMTFICHA2 ON ADFMTFICHA;

-- Tabla: ADFMTPREF
DROP INDEX ADFMTPREF1 ON ADFMTPREF;

-- Tabla: ADTEXTTBLVLD
DROP INDEX ADTEXTTBLVLD1 ON ADTEXTTBLVLD;
DROP INDEX ADTEXTTBLVLD2 ON ADTEXTTBLVLD;

-- Tabla: ADCTLGLISTAD
DROP INDEX ADCTLGLISTAD1 ON ADCTLGLISTAD;
DROP INDEX ADCTLGLISTAD2 ON ADCTLGLISTAD;

-- Tabla: ADCTLGTBLVLD
DROP INDEX ADCTLGTBLVLD1 ON ADCTLGTBLVLD;

-- Tabla: ADDESCRIPTOR
DROP INDEX ADDESCRIPTOR1 ON ADDESCRIPTOR;
DROP INDEX ADDESCRIPTOR2 ON ADDESCRIPTOR;
DROP INDEX ADDESCRIPTOR3 ON ADDESCRIPTOR;
DROP INDEX ADDESCRIPTOR4 ON ADDESCRIPTOR;
DROP INDEX ADDESCRIPTOR5 ON ADDESCRIPTOR;

-- Tabla: ADUSOOBJETO
DROP INDEX ADUSOOBJETO1 ON ADUSOOBJETO;

-- Tabla: ADVCTEXTCF
DROP INDEX ADVCTEXTCF1 ON ADVCTEXTCF;
DROP INDEX ADVCTEXTCF2 ON ADVCTEXTCF;
DROP INDEX ADVCTEXTCF3 ON ADVCTEXTCF;

-- Tabla: ADVCTEXTLCF
DROP INDEX ADVCTEXTLCF1 ON ADVCTEXTLCF;
DROP INDEX ADVCTEXTLCF2 ON ADVCTEXTLCF;

-- Tabla: ADVCNUMCF
DROP INDEX ADVCNUMCF1 ON ADVCNUMCF;
DROP INDEX ADVCNUMCF2 ON ADVCNUMCF;
DROP INDEX ADVCNUMCF3 ON ADVCNUMCF;

-- Tabla: ADVCFECHACF
DROP INDEX ADVCFECHACF1 ON ADVCFECHACF;
DROP INDEX ADVCFECHACF2 ON ADVCFECHACF;
DROP INDEX ADVCFECHACF3 ON ADVCFECHACF;
DROP INDEX ADVCFECHACF4 ON ADVCFECHACF;
DROP INDEX ADVCFECHACF5 ON ADVCFECHACF;
DROP INDEX ADVCFECHACF6 ON ADVCFECHACF;
DROP INDEX ADVCFECHACF7 ON ADVCFECHACF;
DROP INDEX ADVCFECHACF8 ON ADVCFECHACF;

-- Tabla: ADVCREFCF
DROP INDEX ADVCREFCF1 ON ADVCREFCF;
DROP INDEX ADVCREFCF2 ON ADVCREFCF;
DROP INDEX ADVCREFCF3 ON ADVCREFCF;
DROP INDEX ADVCREFCF4 ON ADVCREFCF;
DROP INDEX ADVCREFCF5 ON ADVCREFCF;

-- Tabla: ADVCTEXTDESCR
DROP INDEX ADVCTEXTDESCR1 ON ADVCTEXTDESCR;
DROP INDEX ADVCTEXTDESCR2 ON ADVCTEXTDESCR;
DROP INDEX ADVCTEXTDESCR3 ON ADVCTEXTDESCR;

-- Tabla: ADVCTEXTLDESCR
DROP INDEX ADVCTEXTLDESCR1 ON ADVCTEXTLDESCR;
DROP INDEX ADVCTEXTLDESCR2 ON ADVCTEXTLDESCR;

-- Tabla: ADVCNUMDESCR
DROP INDEX ADVCNUMDESCR1 ON ADVCNUMDESCR;
DROP INDEX ADVCNUMDESCR2 ON ADVCNUMDESCR;
DROP INDEX ADVCNUMDESCR3 ON ADVCNUMDESCR;

-- Tabla: ADVCFECHADESCR
DROP INDEX ADVCFECHADESCR1 ON ADVCFECHADESCR;
DROP INDEX ADVCFECHADESCR2 ON ADVCFECHADESCR;
DROP INDEX ADVCFECHADESCR3 ON ADVCFECHADESCR;
DROP INDEX ADVCFECHADESCR4 ON ADVCFECHADESCR;
DROP INDEX ADVCFECHADESCR5 ON ADVCFECHADESCR;

-- Tabla: ADVCREFDESCR
DROP INDEX ADVCREFDESCR1 ON ADVCREFDESCR;
DROP INDEX ADVCREFDESCR2 ON ADVCREFDESCR;
DROP INDEX ADVCREFDESCR3 ON ADVCREFDESCR;
DROP INDEX ADVCREFDESCR4 ON ADVCREFDESCR;

-- Tabla: ASGTMAPDESCRUDOC
DROP INDEX ASGTMAPDESCRUDOC1 ON ASGTMAPDESCRUDOC;

------------
-- FONDOS --
------------

--Tabla: ASGFNIVELCF
DROP INDEX ASGFNIVELCF1 ON ASGFNIVELCF;
DROP INDEX ASGFNIVELCF2 ON ASGFNIVELCF;

-- Tabla: ASGFESTRUCTJNIVCF
DROP INDEX ASGFESTRUCTJNIVCF1 ON ASGFESTRUCTJNIVCF;
DROP INDEX ASGFESTRUCTJNIVCF2 ON ASGFESTRUCTJNIVCF;

-- Tabla: ASGFELEMENTOCF
DROP INDEX ASGFELEMENTOCF1 ON ASGFELEMENTOCF;
DROP INDEX ASGFELEMENTOCF2 ON ASGFELEMENTOCF;
DROP INDEX ASGFELEMENTOCF3 ON ASGFELEMENTOCF;
DROP INDEX ASGFELEMENTOCF4 ON ASGFELEMENTOCF;
DROP INDEX ASGFELEMENTOCF5 ON ASGFELEMENTOCF;
DROP INDEX ASGFELEMENTOCF6 ON ASGFELEMENTOCF;
DROP INDEX ASGFELEMENTOCF7 ON ASGFELEMENTOCF;
DROP INDEX ASGFELEMENTOCF8 ON ASGFELEMENTOCF;
DROP INDEX ASGFELEMENTOCF9 ON ASGFELEMENTOCF;
DROP INDEX ASGFELEMENTOCF10 ON ASGFELEMENTOCF;
DROP INDEX ASGFELEMENTOCF11 ON ASGFELEMENTOCF;
DROP INDEX ASGFELEMENTOCF12 ON ASGFELEMENTOCF;
DROP INDEX ASGFELEMENTOCF13 ON ASGFELEMENTOCF;
DROP INDEX ASGFELEMENTOCF14 ON ASGFELEMENTOCF;

-- Tabla: ASGFSERIE
DROP INDEX ASGFSERIE1 ON ASGFSERIE;
DROP INDEX ASGFSERIE2 ON ASGFSERIE;
DROP INDEX ASGFSERIE3 ON ASGFSERIE;
DROP INDEX ASGFSERIE4 ON ASGFSERIE;
DROP INDEX ASGFSERIE5 ON ASGFSERIE;

-- Tabla: ASGFVOLUMENSERIE
DROP INDEX ASGFVOLUMENSERIE1 ON ASGFVOLUMENSERIE;

-- Tabla:  ASGFENTPRODUCTORA
DROP INDEX ASGFENTPRODUCTORA1 ON ASGFENTPRODUCTORA;

-- Tabla:  ASGFFONDO
DROP INDEX ASGFFONDO1 ON ASGFFONDO;
DROP INDEX ASGFFONDO2 ON ASGFFONDO;

-- Tabla: ASGFNUMSECVAL
DROP INDEX ASGFNUMSECVAL1 ON ASGFNUMSECVAL;

-- Tabla: ASGFNUMSECSEL
DROP INDEX ASGFNUMSECSEL1 ON ASGFNUMSECSEL;

-- Tabla:  ASGFPRODSERIE
DROP INDEX ASGFPRODSERIE1 ON ASGFPRODSERIE;
DROP INDEX ASGFPRODSERIE2 ON ASGFPRODSERIE;

-- Tabla: ASGFUNIDADDOC
DROP INDEX ASGFUNIDADDOC1 ON ASGFUNIDADDOC;
DROP INDEX ASGFUNIDADDOC2 ON ASGFUNIDADDOC;
DROP INDEX ASGFUNIDADDOC3 ON ASGFUNIDADDOC;
DROP INDEX ASGFUNIDADDOC4 ON ASGFUNIDADDOC;

-- Tabla:  ASGFSOLICITUDSERIE
DROP INDEX ASGFSOLICITUDSERIE1 ON ASGFSOLICITUDSERIE;
DROP INDEX ASGFSOLICITUDSERIE2 ON ASGFSOLICITUDSERIE;

-- Tabla: ASGFORGPROD
DROP INDEX ASGFORGPROD1 ON ASGFORGPROD;

-- Tabla: ASGFVALSERIE
DROP INDEX ASGFVALSERIE1 ON ASGFVALSERIE;
DROP INDEX ASGFVALSERIE2 ON ASGFVALSERIE;
DROP INDEX ASGFVALSERIE3 ON ASGFVALSERIE;
DROP INDEX ASGFVALSERIE4 ON ASGFVALSERIE;

-- Tabla: ASGFELIMSERIE
DROP INDEX ASGFELIMSERIE1 ON ASGFELIMSERIE;
DROP INDEX ASGFELIMSERIE2 ON ASGFELIMSERIE;

-- Tabla: ASGFELIMSELUDOC
DROP INDEX ASGFELIMSELUDOC1 ON ASGFELIMSELUDOC;
DROP INDEX ASGFELIMSELUDOC2 ON ASGFELIMSELUDOC;

-- Tabla: ASGFELIMUDOCCONS
DROP INDEX ASGFELIMUDOCCONS1 ON ASGFELIMUDOCCONS;
DROP INDEX ASGFELIMUDOCCONS2 ON ASGFELIMUDOCCONS;

-- Tabla: ASGFHISTUDOC
DROP INDEX ASGFHISTUDOC1 ON ASGFHISTUDOC;
DROP INDEX ASGFHISTUDOC2 ON ASGFHISTUDOC;

-- Tabla: ASGFUDOCSDF
DROP INDEX ASGFUDOCSDF1 ON ASGFUDOCSDF;

-----------------------------
-- DOCUMENTOS ELECTRONICOS --
-----------------------------

-- Tabla: ADOCCLASIFCF
DROP INDEX ADOCCLASIFCF1 ON ADOCCLASIFCF;
DROP INDEX ADOCCLASIFCF2 ON ADOCCLASIFCF;
DROP INDEX ADOCCLASIFCF3 ON ADOCCLASIFCF;
DROP INDEX ADOCCLASIFCF4 ON ADOCCLASIFCF;

-- Tabla: ADOCDOCUMENTOCF
DROP INDEX ADOCDOCUMENTOCF1 ON ADOCDOCUMENTOCF;
DROP INDEX ADOCDOCUMENTOCF2 ON ADOCDOCUMENTOCF;
DROP INDEX ADOCDOCUMENTOCF3 ON ADOCDOCUMENTOCF;

-- Tabla: ADOCCLASIFDESCR
DROP INDEX ADOCCLASIFDESCR1 ON ADOCCLASIFDESCR;
DROP INDEX ADOCCLASIFDESCR2 ON ADOCCLASIFDESCR;
DROP INDEX ADOCCLASIFDESCR3 ON ADOCCLASIFDESCR;
DROP INDEX ADOCCLASIFDESCR4 ON ADOCCLASIFDESCR;

-- Tabla: ADOCDOCUMENTODESCR
DROP INDEX ADOCDOCUMENTODESCR1 ON ADOCDOCUMENTODESCR;
DROP INDEX ADOCDOCUMENTODESCR2 ON ADOCDOCUMENTODESCR;
DROP INDEX ADOCDOCUMENTODESCR3 ON ADOCDOCUMENTODESCR;

-- Tabla: ADOCFICHACLF
DROP INDEX ADOCFICHACLF1 ON ADOCFICHACLF;

-- Tabla: ADOCTCAPTURA
DROP INDEX ADOCTCAPTURA1 ON ADOCTCAPTURA;
DROP INDEX ADOCTCAPTURA2 ON ADOCTCAPTURA;
DROP INDEX ADOCTCAPTURA3 ON ADOCTCAPTURA;

-- Tabla: ADPCDOCUMENTOVIT
DROP INDEX ADPCDOCUMENTOVIT1 ON ADPCDOCUMENTOVIT;

-- Tabla: ADPCUSODOCVIT
DROP INDEX ADPCUSODOCVIT1 ON ADPCUSODOCVIT;

-- Tabla: ADPCTIPODOCVIT
DROP INDEX ADPCTIPODOCVIT1 ON ADPCTIPODOCVIT;

-- Tabla: ADPCTIPODOCPROC
DROP INDEX ADPCTIPODOCPROC1 ON ADPCTIPODOCPROC;

---------------
-- AUDITORIA --
---------------

-- Tabla: AATRAZA
DROP INDEX AATRAZA1 ON AATRAZA;
DROP INDEX AATRAZA2 ON AATRAZA;
DROP INDEX AATRAZA3 ON AATRAZA;

-- Tabla: AADATOSTRAZA
DROP INDEX AADATOSTRAZA1 ON AADATOSTRAZA;
DROP INDEX AADATOSTRAZA2 ON AADATOSTRAZA;

-- Tabla: AANAUDITUSR
DROP INDEX AANAUDITUSR1 ON AANAUDITUSR;

-- Tabla: AANAUDITACCION
DROP INDEX AANAUDITACCION1 ON AANAUDITACCION;

--------------------------
-- ÍNDICES DOCUMENTALES --
--------------------------

DROP INDEX ID_ADVCTEXTCF ON ADVCTEXTCF;
DROP INDEX ID_ADVCTEXTLCF ON ADVCTEXTLCF;
DROP INDEX ID_ADVCTEXTDESCR ON ADVCTEXTDESCR;
DROP INDEX ID_ADVCTEXTLDESCR ON ADVCTEXTLDESCR;
DROP INDEX ID_ADDESCRIPTOR ON ADDESCRIPTOR;

---------------------------------------------------------------------------------------------
-- Índices de las tablas para almacenar los campos descriptivos de unidades en alta/relación
---------------------------------------------------------------------------------------------
--Tabla: ADVCFECHAUDOCRE
DROP INDEX ADVCFECHAUDOCRE1 ON ADVCFECHAUDOCRE;
DROP INDEX ADVCFECHAUDOCRE2 ON ADVCFECHAUDOCRE;
DROP INDEX ADVCFECHAUDOCRE3 ON ADVCFECHAUDOCRE;
DROP INDEX ADVCFECHAUDOCRE4 ON ADVCFECHAUDOCRE;
DROP INDEX ADVCFECHAUDOCRE5 ON ADVCFECHAUDOCRE;

--Tabla: ADVCNUMUDOCRE
DROP INDEX ADVCNUMUDOCRE1 ON ADVCNUMUDOCRE;
DROP INDEX ADVCNUMUDOCRE2 ON ADVCNUMUDOCRE;
DROP INDEX ADVCNUMUDOCRE3 ON ADVCNUMUDOCRE;

--Tabla: ADVCREFUDOCRE
DROP INDEX ADVCREFUDOCRE1 ON ADVCREFUDOCRE;
DROP INDEX ADVCREFUDOCRE2 ON ADVCREFUDOCRE;
DROP INDEX ADVCREFUDOCRE3 ON ADVCREFUDOCRE;
DROP INDEX ADVCREFUDOCRE4 ON ADVCREFUDOCRE;

--Tabla: ADVCTEXTLUDOCRE
DROP INDEX ADVCTEXTLUDOCRE1 ON ADVCTEXTLUDOCRE;
DROP INDEX ADVCTEXTLUDOCRE2 ON ADVCTEXTLUDOCRE;

--Tabla: ADVCTEXTUDOCRE
DROP INDEX ADVCTEXTUDOCRE1 ON ADVCTEXTUDOCRE;
DROP INDEX ADVCTEXTUDOCRE2 ON ADVCTEXTUDOCRE;


--Tabla: ASGFDIVISIONFS
DROP INDEX ASGFDIVISIONFS1 ON ASGFDIVISIONFS;
DROP INDEX ASGFDIVISIONFS2 ON ASGFDIVISIONFS;

--Tabla: ASGFUDOCENDIVISIONFS
DROP INDEX ASGFUDOCENDIVISIONFS1 ON ASGFUDOCENDIVISIONFS;
DROP INDEX ASGFUDOCENDIVISIONFS2 ON ASGFUDOCENDIVISIONFS;

-- Tabla: ASGDSIGNUMHUECO
DROP INDEX ASGDSIGNUMHUECO1 ON ASGDSIGNUMHUECO;

-- Tabla: ASGSEDIFICIO
DROP INDEX ASGSEDIFICIO1 ON ASGSEDIFICIO;
DROP INDEX ASGSEDIFICIO2 ON ASGSEDIFICIO;

-- Tabla: ASGSSALA
DROP INDEX ASGSSALA1 ON ASGSSALA;
DROP INDEX ASGSSALA2 ON ASGSSALA;
DROP INDEX ASGSSALA3 ON ASGSSALA;

-- Tabla: ASGSMESA
DROP INDEX ASGSMESA1 ON ASGSMESA;
DROP INDEX ASGSMESA2 ON ASGSMESA;
DROP INDEX ASGSMESA3 ON ASGSMESA;
DROP INDEX ASGSMESA4 ON ASGSMESA;

-- Tabla: ASGSUSRCSALA
DROP INDEX ASGSUSRCSALA1 ON ASGSUSRCSALA;
DROP INDEX ASGSUSRCSALA2 ON ASGSUSRCSALA;
DROP INDEX ASGSUSRCSALA3 ON ASGSUSRCSALA;

-- Tabla: ASGSUSRCSARCH
DROP INDEX ASGSUSRCSARCH1 ON ASGSUSRCSARCH;
DROP INDEX ASGSUSRCSARCH2 ON ASGSUSRCSARCH;

-- Tabla: ASGSREGCSALA
DROP INDEX ASGSREGCSALA1 ON ASGSREGCSALA;
DROP INDEX ASGSREGCSALA2 ON ASGSREGCSALA;
DROP INDEX ASGSREGCSALA3 ON ASGSREGCSALA;

-- Tabla: ASGTUIREEACR
DROP INDEX ASGTUIREEACR1 ON ASGTUIREEACR;
DROP INDEX ASGTUIREEACR2 ON ASGTUIREEACR;

-- Tabla: ASGTUDOCENUIREEACR
DROP INDEX ASGTUDOCENUIREEACR1 ON ASGTUDOCENUIREEACR;
DROP INDEX ASGTUDOCENUIREEACR2 ON ASGTUDOCENUIREEACR;
DROP INDEX ASGTUDOCENUIREEACR3 ON ASGTUDOCENUIREEACR;
DROP INDEX ASGTUDOCENUIREEACR4 ON ASGTUDOCENUIREEACR;
DROP INDEX ASGTUDOCENUIREEACR5 ON ASGTUDOCENUIREEACR;
DROP INDEX ASGTUDOCENUIREEACR6 ON ASGTUDOCENUIREEACR;

-- Tabla: ASGTUDOCREEACR
DROP INDEX ASGTUDOCREEACR1 ON ASGTUDOCREEACR;
DROP INDEX ASGTUDOCREEACR2 ON ASGTUDOCREEACR;
DROP INDEX ASGTUDOCREEACR3 ON ASGTUDOCREEACR;

--Tabla: ASGFCTLGTBLTMP
DROP INDEX ASGFCTLGTBLTMP1 ON ASGFCTLGTBLTMP;
DROP INDEX ASGFCTLGTBLTMP2 ON ASGFCTLGTBLTMP;
