
create or replace view SEC_TBL_VIEW_ORGANO_CARGO  (ID, VALOR, SUSTITUTO, VIGENTE , ORDEN) as

SELECT   ORG.ID*100+CARGO.ID :: int,
	(ORG.VALOR || '-' || CARGO.VALOR) :: CHARACTER VARYING (5),
	(ORG.SUSTITUTO || '-' || CARGO.SUSTITUTO) :: CHARACTER VARYING (129),
	1 ::NUMERIC(1,0)  , CAST(ORG.ORDEN*100+CARGO.ORDEN AS NUMERIC(10,0))
FROM  SEC_VLDTBL_ORGANO_GOBIERNO  ORG , SEC_VLDTBL_CARGO_ORGANO CARGO;



create or replace view SEC_TBL_VIEW_AREA_CARGO  (ID, VALOR, SUSTITUTO, VIGENTE , ORDEN) as

SELECT   AREA.ID*100+CARGO.ID :: int,
	(AREA.VALOR || '-' || CARGO.VALOR) :: CHARACTER VARYING (5),
	(AREA.SUSTITUTO || '-' || CARGO.SUSTITUTO) :: CHARACTER VARYING (129),
	1 ::NUMERIC(1,0)  , CAST(AREA.ORDEN*100+CARGO.ORDEN AS NUMERIC(10,0))
FROM  SEC_VLDTBL_AREA_GOBIERNO  AREA , SEC_VLDTBL_CARGO_AREA CARGO;



CREATE OR REPLACE FUNCTION createViewJerarquiaByName(IN name character varying, OUT id numeric) AS
$BODY$DECLARE stmt varchar(512);
BEGIN
stmt:='SELECT id from spac_ct_jerarquias where nombre=''' || name || '''' ;
EXECUTE  stmt INTO id;
stmt:='CREATE OR REPLACE VIEW SPAC_CT_JERARQUIA_'|| id ||' AS SELECT SPAC_EXPEDIENTES.ID as id, SPAC_EXPEDIENTES.ID   as id_padre , SPAC_EXPEDIENTES.ID as id_hija FROM SPAC_EXPEDIENTES WHERE ID=1;';
EXECUTE  stmt ;

END$BODY$
  LANGUAGE 'plpgsql' VOLATILE;
ALTER FUNCTION createViewJerarquiaByName(IN name character varying, OUT id numeric) OWNER TO postgres;







