//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v@@BUILD_VERSION@@ 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2011.07.04 en 12:38:50 CEST 
//


package org.notariado.ancert.xml.plusvalias.liquidacion.impl;

public class DireccionTypeImpl implements org.notariado.ancert.xml.plusvalias.liquidacion.DireccionType, com.sun.xml.bind.JAXBObject, org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.UnmarshallableObject, org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.XMLSerializable, org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.ValidatableObject
{

    protected java.lang.String _PLANTA;
    protected java.lang.String _NUMEROVIA;
    protected java.lang.String _ESCALERA;
    protected java.lang.String _RESTO;
    protected java.lang.String _BLOQUE;
    protected java.lang.String _CODIGOPOSTAL;
    protected java.lang.String _INEMUNICIPIO;
    protected java.lang.String _TIPOVIA;
    protected java.lang.String _ENTIDADMENOR;
    protected boolean has_APRKM;
    protected int _APRKM;
    protected java.lang.String _VIA;
    protected java.lang.String _INEPROVINCIA;
    protected java.lang.String _PUERTA;
    protected java.lang.String _DUPLICADO;
    public final static java.lang.Class version = (org.notariado.ancert.xml.plusvalias.liquidacion.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (org.notariado.ancert.xml.plusvalias.liquidacion.DireccionType.class);
    }

    public java.lang.String getPLANTA() {
        return _PLANTA;
    }

    public void setPLANTA(java.lang.String value) {
        _PLANTA = value;
    }

    public java.lang.String getNUMEROVIA() {
        return _NUMEROVIA;
    }

    public void setNUMEROVIA(java.lang.String value) {
        _NUMEROVIA = value;
    }

    public java.lang.String getESCALERA() {
        return _ESCALERA;
    }

    public void setESCALERA(java.lang.String value) {
        _ESCALERA = value;
    }

    public java.lang.String getRESTO() {
        return _RESTO;
    }

    public void setRESTO(java.lang.String value) {
        _RESTO = value;
    }

    public java.lang.String getBLOQUE() {
        return _BLOQUE;
    }

    public void setBLOQUE(java.lang.String value) {
        _BLOQUE = value;
    }

    public java.lang.String getCODIGOPOSTAL() {
        return _CODIGOPOSTAL;
    }

    public void setCODIGOPOSTAL(java.lang.String value) {
        _CODIGOPOSTAL = value;
    }

    public java.lang.String getINEMUNICIPIO() {
        return _INEMUNICIPIO;
    }

    public void setINEMUNICIPIO(java.lang.String value) {
        _INEMUNICIPIO = value;
    }

    public java.lang.String getTIPOVIA() {
        return _TIPOVIA;
    }

    public void setTIPOVIA(java.lang.String value) {
        _TIPOVIA = value;
    }

    public java.lang.String getENTIDADMENOR() {
        return _ENTIDADMENOR;
    }

    public void setENTIDADMENOR(java.lang.String value) {
        _ENTIDADMENOR = value;
    }

    public int getAPRKM() {
        return _APRKM;
    }

    public void setAPRKM(int value) {
        _APRKM = value;
        has_APRKM = true;
    }

    public java.lang.String getVIA() {
        return _VIA;
    }

    public void setVIA(java.lang.String value) {
        _VIA = value;
    }

    public java.lang.String getINEPROVINCIA() {
        return _INEPROVINCIA;
    }

    public void setINEPROVINCIA(java.lang.String value) {
        _INEPROVINCIA = value;
    }

    public java.lang.String getPUERTA() {
        return _PUERTA;
    }

    public void setPUERTA(java.lang.String value) {
        _PUERTA = value;
    }

    public java.lang.String getDUPLICADO() {
        return _DUPLICADO;
    }

    public void setDUPLICADO(java.lang.String value) {
        _DUPLICADO = value;
    }

    public org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.UnmarshallingEventHandler createUnmarshaller(org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.UnmarshallingContext context) {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.DireccionTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.startElement("http://ancert.notariado.org/XML/Plusvalias/Liquidacion", "INE_PROVINCIA");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _INEPROVINCIA), "INEPROVINCIA");
        } catch (java.lang.Exception e) {
            org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("http://ancert.notariado.org/XML/Plusvalias/Liquidacion", "INE_MUNICIPIO");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _INEMUNICIPIO), "INEMUNICIPIO");
        } catch (java.lang.Exception e) {
            org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("http://ancert.notariado.org/XML/Plusvalias/Liquidacion", "TIPO_VIA");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _TIPOVIA), "TIPOVIA");
        } catch (java.lang.Exception e) {
            org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("http://ancert.notariado.org/XML/Plusvalias/Liquidacion", "VIA");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _VIA), "VIA");
        } catch (java.lang.Exception e) {
            org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        if (_NUMEROVIA!= null) {
            context.startElement("http://ancert.notariado.org/XML/Plusvalias/Liquidacion", "NUMERO_VIA");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _NUMEROVIA), "NUMEROVIA");
            } catch (java.lang.Exception e) {
                org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_ESCALERA!= null) {
            context.startElement("http://ancert.notariado.org/XML/Plusvalias/Liquidacion", "ESCALERA");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _ESCALERA), "ESCALERA");
            } catch (java.lang.Exception e) {
                org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_PLANTA!= null) {
            context.startElement("http://ancert.notariado.org/XML/Plusvalias/Liquidacion", "PLANTA");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _PLANTA), "PLANTA");
            } catch (java.lang.Exception e) {
                org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_PUERTA!= null) {
            context.startElement("http://ancert.notariado.org/XML/Plusvalias/Liquidacion", "PUERTA");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _PUERTA), "PUERTA");
            } catch (java.lang.Exception e) {
                org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_DUPLICADO!= null) {
            context.startElement("http://ancert.notariado.org/XML/Plusvalias/Liquidacion", "DUPLICADO");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _DUPLICADO), "DUPLICADO");
            } catch (java.lang.Exception e) {
                org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_BLOQUE!= null) {
            context.startElement("http://ancert.notariado.org/XML/Plusvalias/Liquidacion", "BLOQUE");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _BLOQUE), "BLOQUE");
            } catch (java.lang.Exception e) {
                org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (has_APRKM) {
            context.startElement("http://ancert.notariado.org/XML/Plusvalias/Liquidacion", "APR_KM");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(javax.xml.bind.DatatypeConverter.printInt(((int) _APRKM)), "APRKM");
            } catch (java.lang.Exception e) {
                org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_ENTIDADMENOR!= null) {
            context.startElement("http://ancert.notariado.org/XML/Plusvalias/Liquidacion", "ENTIDAD_MENOR");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _ENTIDADMENOR), "ENTIDADMENOR");
            } catch (java.lang.Exception e) {
                org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        if (_RESTO!= null) {
            context.startElement("http://ancert.notariado.org/XML/Plusvalias/Liquidacion", "RESTO");
            context.endNamespaceDecls();
            context.endAttributes();
            try {
                context.text(((java.lang.String) _RESTO), "RESTO");
            } catch (java.lang.Exception e) {
                org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endElement();
        }
        context.startElement("http://ancert.notariado.org/XML/Plusvalias/Liquidacion", "CODIGO_POSTAL");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _CODIGOPOSTAL), "CODIGOPOSTAL");
        } catch (java.lang.Exception e) {
            org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
    }

    public void serializeAttributes(org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeURIs(org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (org.notariado.ancert.xml.plusvalias.liquidacion.DireccionType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0002L\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000b"
+"expandedExpq\u0000~\u0000\u0002xpppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000pp"
+"sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0000ppsr\u0000\'"
+"com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameCla"
+"sst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv.grammar."
+"ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\fcontent"
+"Modelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003pp\u0000sq\u0000~\u0000\u0000ppsr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~"
+"\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0003ppsr\u0000%com.sun"
+".msv.datatype.xsd.PatternFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001[\u0000\bpatternst\u0000\u0013[Ljav"
+"a/lang/String;xr\u0000;com.sun.msv.datatype.xsd.DataTypeWithLexic"
+"alConstraintFacetT\u0090\u001c>\u001azb\u00ea\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd.Dat"
+"aTypeWithFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFacetFixedZ\u0000\u0012needValueCheckFla"
+"gL\u0000\bbaseTypet\u0000)Lcom/sun/msv/datatype/xsd/XSDatatypeImpl;L\u0000\fc"
+"oncreteTypet\u0000\'Lcom/sun/msv/datatype/xsd/ConcreteType;L\u0000\tface"
+"tNamet\u0000\u0012Ljava/lang/String;xr\u0000\'com.sun.msv.datatype.xsd.XSDat"
+"atypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUriq\u0000~\u0000!L\u0000\btypeNameq\u0000~\u0000!L\u0000\nw"
+"hiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpaceProcessor;xp"
+"t\u00006http://ancert.notariado.org/XML/Plusvalias/Liquidaciont\u0000\u0014"
+"CODIGO_PROVINCIATypesr\u00005com.sun.msv.datatype.xsd.WhiteSpaceP"
+"rocessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.Whi"
+"teSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0000\u0000sr\u0000#com.sun.msv.datatype.xsd."
+"StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxr\u0000*com.sun.msv.datatyp"
+"e.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.x"
+"sd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\"t\u0000 http://www.w3.org/2001/XM"
+"LSchemat\u0000\u0006stringq\u0000~\u0000)\u0001q\u0000~\u0000-t\u0000\u0007patternur\u0000\u0013[Ljava.lang.String;"
+"\u00ad\u00d2V\u00e7\u00e9\u001d{G\u0002\u0000\u0000xp\u0000\u0000\u0000\u0001t\u0000\b[0-9]{2}sr\u00000com.sun.msv.grammar.Expressi"
+"on$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sr\u0000\u0011java.lang.Boolean\u00cd "
+"r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0"
+"\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000!L\u0000\fnamespaceURIq\u0000~\u0000!xpq\u0000~\u0000&q\u0000~\u0000%sr\u0000\u001dcom."
+"sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001ppsr\u0000 com.sun.msv."
+"grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\u0013x"
+"q\u0000~\u0000\u0003q\u0000~\u00007psq\u0000~\u0000\u0017ppsr\u0000\"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000+q\u0000~\u0000.t\u0000\u0005QNamesr\u00005com.sun.msv.datatype.xsd.Whit"
+"eSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000(q\u0000~\u00005sq\u0000~\u00008q\u0000~\u0000Aq\u0000~"
+"\u0000.sr\u0000#com.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocal"
+"Nameq\u0000~\u0000!L\u0000\fnamespaceURIq\u0000~\u0000!xr\u0000\u001dcom.sun.msv.grammar.NameCla"
+"ss\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000)http://www.w3.org/2001/XMLSchema-in"
+"stancesr\u00000com.sun.msv.grammar.Expression$EpsilonExpression\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003sq\u0000~\u00006\u0001q\u0000~\u0000Ksq\u0000~\u0000Et\u0000\rINE_PROVINCIAq\u0000~\u0000%sq\u0000~\u0000\u0012"
+"pp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0017ppsq\u0000~\u0000\u001bq\u0000~\u0000%t\u0000\u0014CODIGO_MUNICIPIOTypeq\u0000~\u0000)\u0000\u0000"
+"q\u0000~\u0000-q\u0000~\u0000-q\u0000~\u00000uq\u0000~\u00001\u0000\u0000\u0000\u0001t\u0000\b[0-9]{4}q\u0000~\u00005sq\u0000~\u00008q\u0000~\u0000Sq\u0000~\u0000%sq\u0000"
+"~\u0000:ppsq\u0000~\u0000<q\u0000~\u00007pq\u0000~\u0000>q\u0000~\u0000Gq\u0000~\u0000Ksq\u0000~\u0000Et\u0000\rINE_MUNICIPIOq\u0000~\u0000%s"
+"q\u0000~\u0000\u0012pp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0017ppsr\u0000)com.sun.msv.datatype.xsd.Enumera"
+"tionFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0006valuest\u0000\u000fLjava/util/Set;xr\u00009com.sun.m"
+"sv.datatype.xsd.DataTypeWithValueConstraintFacet\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000x"
+"q\u0000~\u0000\u001eq\u0000~\u0000%t\u0000\fTIPO_VIATypeq\u0000~\u0000)\u0000\u0000q\u0000~\u0000-q\u0000~\u0000-t\u0000\u000benumerationsr\u0000\u0011"
+"java.util.HashSet\u00baD\u0085\u0095\u0096\u00b8\u00b74\u0003\u0000\u0000xpw\f\u0000\u0000\u0000\u0080?@\u0000\u0000\u0000\u0000\u0000Lt\u0000\u0002CRt\u0000\u0002GVt\u0000\u0002RBt"
+"\u0000\u0002PJt\u0000\u0002RDt\u0000\u0002CHt\u0000\u0002ERt\u0000\u0002MNt\u0000\u0002BOt\u0000\u0002PQt\u0000\u0002MZt\u0000\u0002GLt\u0000\u0002TRt\u0000\u0002MLt\u0000\u0002MSt"
+"\u0000\u0002DEt\u0000\u0002TOt\u0000\u0002CNt\u0000\u0002BJt\u0000\u0002GRt\u0000\u0002MCt\u0000\u0002EDt\u0000\u0002AGt\u0000\u0002RRt\u0000\u0002PLt\u0000\u0002CLt\u0000\u0002AUt"
+"\u0000\u0002SDt\u0000\u0002CMt\u0000\u0002FCt\u0000\u0002TNt\u0000\u0002ENt\u0000\u0002EXt\u0000\u0002HTt\u0000\u0002LGt\u0000\u0002PSt\u0000\u0002SNt\u0000\u0002CUt\u0000\u0002MTt"
+"\u0000\u0002COt\u0000\u0002AVt\u0000\u0002CJt\u0000\u0002PMt\u0000\u0002DPt\u0000\u0002URt\u0000\u0002PZt\u0000\u0002JRt\u0000\u0002VRt\u0000\u0002CPt\u0000\u0002CIt\u0000\u0002LDt"
+"\u0000\u0002ESt\u0000\u0002PRt\u0000\u0002RUt\u0000\u0002RPt\u0000\u0002FNt\u0000\u0002AYt\u0000\u0002QTt\u0000\u0002DSt\u0000\u0002RMt\u0000\u0002ALt\u0000\u0002CAt\u0000\u0002SUt"
+"\u0000\u0002BRt\u0000\u0002CSt\u0000\u0002PTt\u0000\u0002ARt\u0000\u0002CYt\u0000\u0002CTt\u0000\u0002CGt\u0000\u0002PBt\u0000\u0002SLt\u0000\u0002SAt\u0000\u0002RCt\u0000\u0002PDt"
+"\u0000\u0002EMxq\u0000~\u00005sq\u0000~\u00008q\u0000~\u0000bq\u0000~\u0000%sq\u0000~\u0000:ppsq\u0000~\u0000<q\u0000~\u00007pq\u0000~\u0000>q\u0000~\u0000Gq\u0000~\u0000"
+"Ksq\u0000~\u0000Et\u0000\bTIPO_VIAq\u0000~\u0000%sq\u0000~\u0000\u0012pp\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0017ppsr\u0000\'com.sun."
+"msv.datatype.xsd.MaxLengthFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\tmaxLengthxq\u0000~\u0000`"
+"q\u0000~\u0000%t\u0000\u000eNOMBRE_VIATypeq\u0000~\u0000)\u0000\u0000sq\u0000~\u0000\u001bq\u0000~\u0000%t\u0000\nSTRINGTypeq\u0000~\u0000)\u0000\u0000"
+"q\u0000~\u0000-q\u0000~\u0000-q\u0000~\u00000uq\u0000~\u00001\u0000\u0000\u0000\u0001t\u0000\n[^\\r\\n\\t]*q\u0000~\u0000-t\u0000\tmaxLength\u0000\u0000\u0000\u0019q"
+"\u0000~\u00005sq\u0000~\u00008q\u0000~\u0000\u00bcq\u0000~\u0000%sq\u0000~\u0000:ppsq\u0000~\u0000<q\u0000~\u00007pq\u0000~\u0000>q\u0000~\u0000Gq\u0000~\u0000Ksq\u0000~\u0000"
+"Et\u0000\u0003VIAq\u0000~\u0000%sq\u0000~\u0000:ppsq\u0000~\u0000\u0012q\u0000~\u00007p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0017ppsq\u0000~\u0000\u00baq\u0000~\u0000%"
+"t\u0000\u000eNUMERO_VIATypeq\u0000~\u0000)\u0000\u0000q\u0000~\u0000\u00bdq\u0000~\u0000-q\u0000~\u0000\u00c1\u0000\u0000\u0000\u0004q\u0000~\u00005sq\u0000~\u00008q\u0000~\u0000\u00ccq"
+"\u0000~\u0000%sq\u0000~\u0000:ppsq\u0000~\u0000<q\u0000~\u00007pq\u0000~\u0000>q\u0000~\u0000Gq\u0000~\u0000Ksq\u0000~\u0000Et\u0000\nNUMERO_VIAq\u0000"
+"~\u0000%q\u0000~\u0000Ksq\u0000~\u0000:ppsq\u0000~\u0000\u0012q\u0000~\u00007p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0017ppsq\u0000~\u0000\u00baq\u0000~\u0000%pq\u0000~"
+"\u0000)\u0000\u0001sr\u0000\'com.sun.msv.datatype.xsd.MinLengthFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000"
+"\tminLengthxq\u0000~\u0000`q\u0000~\u0000%pq\u0000~\u0000)\u0000\u0000q\u0000~\u0000\u00bdq\u0000~\u0000-t\u0000\tminLength\u0000\u0000\u0000\u0001q\u0000~\u0000-"
+"q\u0000~\u0000\u00c1\u0000\u0000\u0000\u0002q\u0000~\u00005sq\u0000~\u00008t\u0000\u000estring-derivedq\u0000~\u0000%sq\u0000~\u0000:ppsq\u0000~\u0000<q\u0000~\u0000"
+"7pq\u0000~\u0000>q\u0000~\u0000Gq\u0000~\u0000Ksq\u0000~\u0000Et\u0000\bESCALERAq\u0000~\u0000%q\u0000~\u0000Ksq\u0000~\u0000:ppsq\u0000~\u0000\u0012q\u0000"
+"~\u00007p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0017ppsq\u0000~\u0000\u00baq\u0000~\u0000%pq\u0000~\u0000)\u0000\u0001sq\u0000~\u0000\u00d7q\u0000~\u0000%pq\u0000~\u0000)\u0000\u0000q"
+"\u0000~\u0000\u00bdq\u0000~\u0000-q\u0000~\u0000\u00d9\u0000\u0000\u0000\u0001q\u0000~\u0000-q\u0000~\u0000\u00c1\u0000\u0000\u0000\u0002q\u0000~\u00005sq\u0000~\u00008t\u0000\u000estring-derived"
+"q\u0000~\u0000%sq\u0000~\u0000:ppsq\u0000~\u0000<q\u0000~\u00007pq\u0000~\u0000>q\u0000~\u0000Gq\u0000~\u0000Ksq\u0000~\u0000Et\u0000\u0006PLANTAq\u0000~\u0000%"
+"q\u0000~\u0000Ksq\u0000~\u0000:ppsq\u0000~\u0000\u0012q\u0000~\u00007p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0017ppsq\u0000~\u0000\u00baq\u0000~\u0000%pq\u0000~\u0000)\u0000"
+"\u0001sq\u0000~\u0000\u00d7q\u0000~\u0000%pq\u0000~\u0000)\u0000\u0000q\u0000~\u0000\u00bdq\u0000~\u0000-q\u0000~\u0000\u00d9\u0000\u0000\u0000\u0001q\u0000~\u0000-q\u0000~\u0000\u00c1\u0000\u0000\u0000\u0003q\u0000~\u00005sq"
+"\u0000~\u00008t\u0000\u000estring-derivedq\u0000~\u0000%sq\u0000~\u0000:ppsq\u0000~\u0000<q\u0000~\u00007pq\u0000~\u0000>q\u0000~\u0000Gq\u0000~\u0000"
+"Ksq\u0000~\u0000Et\u0000\u0006PUERTAq\u0000~\u0000%q\u0000~\u0000Ksq\u0000~\u0000:ppsq\u0000~\u0000\u0012q\u0000~\u00007p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000"
+"\u0017ppsq\u0000~\u0000^q\u0000~\u0000%t\u0000\rDUPLICADOTypeq\u0000~\u0000)\u0000\u0000q\u0000~\u0000-q\u0000~\u0000-q\u0000~\u0000csq\u0000~\u0000dw\f"
+"\u0000\u0000\u0000\u0010?@\u0000\u0000\u0000\u0000\u0000\u0003t\u0000\u0001Dt\u0000\u0001Ct\u0000\u0001Txq\u0000~\u00005sq\u0000~\u00008q\u0000~\u0000\u00fdq\u0000~\u0000%sq\u0000~\u0000:ppsq\u0000~\u0000<"
+"q\u0000~\u00007pq\u0000~\u0000>q\u0000~\u0000Gq\u0000~\u0000Ksq\u0000~\u0000Et\u0000\tDUPLICADOq\u0000~\u0000%q\u0000~\u0000Ksq\u0000~\u0000:ppsq\u0000"
+"~\u0000\u0012q\u0000~\u00007p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0017ppsq\u0000~\u0000\u00baq\u0000~\u0000%pq\u0000~\u0000)\u0000\u0001sq\u0000~\u0000\u00d7q\u0000~\u0000%pq\u0000~"
+"\u0000)\u0000\u0000q\u0000~\u0000\u00bdq\u0000~\u0000-q\u0000~\u0000\u00d9\u0000\u0000\u0000\u0001q\u0000~\u0000-q\u0000~\u0000\u00c1\u0000\u0000\u0000\u0004q\u0000~\u00005sq\u0000~\u00008t\u0000\u000estring-de"
+"rivedq\u0000~\u0000%sq\u0000~\u0000:ppsq\u0000~\u0000<q\u0000~\u00007pq\u0000~\u0000>q\u0000~\u0000Gq\u0000~\u0000Ksq\u0000~\u0000Et\u0000\u0006BLOQUE"
+"q\u0000~\u0000%q\u0000~\u0000Ksq\u0000~\u0000:ppsq\u0000~\u0000\u0012q\u0000~\u00007p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0017ppsr\u0000 com.sun.m"
+"sv.datatype.xsd.IntType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000+com.sun.msv.datatype.x"
+"sd.IntegerDerivedType\u0099\u00f1]\u0090&6k\u00be\u0002\u0000\u0001L\u0000\nbaseFacetsq\u0000~\u0000\u001fxq\u0000~\u0000+q\u0000~\u0000"
+".t\u0000\u0003intq\u0000~\u0000Csr\u0000*com.sun.msv.datatype.xsd.MaxInclusiveFacet\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000#com.sun.msv.datatype.xsd.RangeFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L"
+"\u0000\nlimitValuet\u0000\u0012Ljava/lang/Object;xq\u0000~\u0000`ppq\u0000~\u0000C\u0000\u0001sr\u0000*com.sun."
+"msv.datatype.xsd.MinInclusiveFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0001\u001cppq\u0000~\u0000C\u0000\u0000"
+"sr\u0000!com.sun.msv.datatype.xsd.LongType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0001\u0018q\u0000~\u0000.t"
+"\u0000\u0004longq\u0000~\u0000Csq\u0000~\u0001\u001bppq\u0000~\u0000C\u0000\u0001sq\u0000~\u0001\u001fppq\u0000~\u0000C\u0000\u0000sr\u0000$com.sun.msv.dat"
+"atype.xsd.IntegerType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0001\u0018q\u0000~\u0000.t\u0000\u0007integerq\u0000~\u0000Csr"
+"\u0000,com.sun.msv.datatype.xsd.FractionDigitsFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001I\u0000\u0005"
+"scalexq\u0000~\u0000\u001dppq\u0000~\u0000C\u0001\u0000sr\u0000#com.sun.msv.datatype.xsd.NumberType\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000+q\u0000~\u0000.t\u0000\u0007decimalq\u0000~\u0000Cq\u0000~\u0001,t\u0000\u000efractionDigits\u0000\u0000"
+"\u0000\u0000q\u0000~\u0001\'t\u0000\fminInclusivesr\u0000\u000ejava.lang.Long;\u008b\u00e4\u0090\u00cc\u008f#\u00df\u0002\u0000\u0001J\u0000\u0005valuex"
+"r\u0000\u0010java.lang.Number\u0086\u00ac\u0095\u001d\u000b\u0094\u00e0\u008b\u0002\u0000\u0000xp\u0080\u0000\u0000\u0000\u0000\u0000\u0000\u0000q\u0000~\u0001\'t\u0000\fmaxInclusive"
+"sq\u0000~\u00010\u007f\u00ff\u00ff\u00ff\u00ff\u00ff\u00ff\u00ffq\u0000~\u0001\"q\u0000~\u0001/sr\u0000\u0011java.lang.Integer\u0012\u00e2\u00a0\u00a4\u00f7\u0081\u00878\u0002\u0000\u0001I\u0000\u0005v"
+"aluexq\u0000~\u00011\u0080\u0000\u0000\u0000q\u0000~\u0001\"q\u0000~\u00013sq\u0000~\u00015\u007f\u00ff\u00ff\u00ffq\u0000~\u00005sq\u0000~\u00008q\u0000~\u0001\u001aq\u0000~\u0000.sq\u0000~\u0000"
+":ppsq\u0000~\u0000<q\u0000~\u00007pq\u0000~\u0000>q\u0000~\u0000Gq\u0000~\u0000Ksq\u0000~\u0000Et\u0000\u0006APR_KMq\u0000~\u0000%q\u0000~\u0000Ksq\u0000~\u0000"
+":ppsq\u0000~\u0000\u0012q\u0000~\u00007p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0017ppsq\u0000~\u0000\u00baq\u0000~\u0000%pq\u0000~\u0000)\u0000\u0001sq\u0000~\u0000\u00d7q\u0000~"
+"\u0000%pq\u0000~\u0000)\u0000\u0000q\u0000~\u0000\u00bdq\u0000~\u0000-q\u0000~\u0000\u00d9\u0000\u0000\u0000\u0001q\u0000~\u0000-q\u0000~\u0000\u00c1\u0000\u0000\u0000\u000fq\u0000~\u00005sq\u0000~\u00008t\u0000\u000estr"
+"ing-derivedq\u0000~\u0000%sq\u0000~\u0000:ppsq\u0000~\u0000<q\u0000~\u00007pq\u0000~\u0000>q\u0000~\u0000Gq\u0000~\u0000Ksq\u0000~\u0000Et\u0000\r"
+"ENTIDAD_MENORq\u0000~\u0000%q\u0000~\u0000Ksq\u0000~\u0000:ppsq\u0000~\u0000\u0012q\u0000~\u00007p\u0000sq\u0000~\u0000\u0000ppsq\u0000~\u0000\u0017pp"
+"sq\u0000~\u0000\u00baq\u0000~\u0000%pq\u0000~\u0000)\u0000\u0001sq\u0000~\u0000\u00d7q\u0000~\u0000%pq\u0000~\u0000)\u0000\u0000q\u0000~\u0000\u00bdq\u0000~\u0000-q\u0000~\u0000\u00d9\u0000\u0000\u0000\u0001q\u0000~"
+"\u0000-q\u0000~\u0000\u00c1\u0000\u0000\u0000\u0019q\u0000~\u00005sq\u0000~\u00008t\u0000\u000estring-derivedq\u0000~\u0000%sq\u0000~\u0000:ppsq\u0000~\u0000<q\u0000"
+"~\u00007pq\u0000~\u0000>q\u0000~\u0000Gq\u0000~\u0000Ksq\u0000~\u0000Et\u0000\u0005RESTOq\u0000~\u0000%q\u0000~\u0000Ksq\u0000~\u0000\u0012pp\u0000sq\u0000~\u0000\u0000pp"
+"sq\u0000~\u0000\u0017ppsq\u0000~\u0000\u001bq\u0000~\u0000%t\u0000\u0011CODIGO_POSTALTypeq\u0000~\u0000)\u0000\u0000q\u0000~\u0000-q\u0000~\u0000-q\u0000~\u0000"
+"0uq\u0000~\u00001\u0000\u0000\u0000\u0001t\u0000\b[0-9]{5}q\u0000~\u00005sq\u0000~\u00008q\u0000~\u0001Yq\u0000~\u0000%sq\u0000~\u0000:ppsq\u0000~\u0000<q\u0000~"
+"\u00007pq\u0000~\u0000>q\u0000~\u0000Gq\u0000~\u0000Ksq\u0000~\u0000Et\u0000\rCODIGO_POSTALq\u0000~\u0000%sr\u0000\"com.sun.msv"
+".grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv"
+"/grammar/ExpressionPool$ClosedHash;xpsr\u0000-com.sun.msv.grammar"
+".ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0003\u0000\u0003I\u0000\u0005countB\u0000\rstreamVersio"
+"nL\u0000\u0006parentt\u0000$Lcom/sun/msv/grammar/ExpressionPool;xp\u0000\u0000\u00002\u0001pq\u0000~"
+"\u0001\u0015q\u0000~\u0001\tq\u0000~\u0000\u00f8q\u0000~\u0000\u000bq\u0000~\u0000\u00e2q\u0000~\u0000\\q\u0000~\u0000\u00faq\u0000~\u0000\u0016q\u0000~\u0000\bq\u0000~\u0000\u0010q\u0000~\u0000\u0005q\u0000~\u0000\u00ecq\u0000~"
+"\u0000\u00c9q\u0000~\u0000\u00c7q\u0000~\u0000\u00d4q\u0000~\u0001\u0007q\u0000~\u0000\u0011q\u0000~\u0000\u000eq\u0000~\u0001Iq\u0000~\u0000\u00d2q\u0000~\u0000Pq\u0000~\u0000\tq\u0000~\u0000\u000fq\u0000~\u0000\fq\u0000~"
+"\u0000\u0006q\u0000~\u0000\nq\u0000~\u0000\u00b8q\u0000~\u0000;q\u0000~\u0000Wq\u0000~\u0000\u00b3q\u0000~\u0000\u00c3q\u0000~\u0000\u00ceq\u0000~\u0000\u00dcq\u0000~\u0000\u00e8q\u0000~\u0000\u00f4q\u0000~\u0001\u0003q\u0000~"
+"\u0001\u000fq\u0000~\u00019q\u0000~\u0001Eq\u0000~\u0001?q\u0000~\u0001Qq\u0000~\u0001]q\u0000~\u0001Vq\u0000~\u0001\u0013q\u0000~\u0001=q\u0000~\u0001Kq\u0000~\u0000\u00eeq\u0000~\u0000\u0007q\u0000~"
+"\u0000\u00e0q\u0000~\u0000\rx"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.UnmarshallingContext context) {
            super(context, "-------------------------------------------");
        }

        protected Unmarshaller(org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return org.notariado.ancert.xml.plusvalias.liquidacion.impl.DireccionTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  9 :
                        if (("VIA" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 10;
                            return ;
                        }
                        break;
                    case  42 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  39 :
                        if (("CODIGO_POSTAL" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 40;
                            return ;
                        }
                        break;
                    case  27 :
                        if (("BLOQUE" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 28;
                            return ;
                        }
                        state = 30;
                        continue outer;
                    case  0 :
                        if (("INE_PROVINCIA" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 1;
                            return ;
                        }
                        break;
                    case  12 :
                        if (("NUMERO_VIA" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 13;
                            return ;
                        }
                        state = 15;
                        continue outer;
                    case  33 :
                        if (("ENTIDAD_MENOR" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 34;
                            return ;
                        }
                        state = 36;
                        continue outer;
                    case  3 :
                        if (("INE_MUNICIPIO" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 4;
                            return ;
                        }
                        break;
                    case  15 :
                        if (("ESCALERA" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 16;
                            return ;
                        }
                        state = 18;
                        continue outer;
                    case  18 :
                        if (("PLANTA" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 19;
                            return ;
                        }
                        state = 21;
                        continue outer;
                    case  24 :
                        if (("DUPLICADO" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 25;
                            return ;
                        }
                        state = 27;
                        continue outer;
                    case  6 :
                        if (("TIPO_VIA" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 7;
                            return ;
                        }
                        break;
                    case  30 :
                        if (("APR_KM" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 31;
                            return ;
                        }
                        state = 33;
                        continue outer;
                    case  21 :
                        if (("PUERTA" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 22;
                            return ;
                        }
                        state = 24;
                        continue outer;
                    case  36 :
                        if (("RESTO" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 37;
                            return ;
                        }
                        state = 39;
                        continue outer;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  42 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  23 :
                        if (("PUERTA" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.popAttributes();
                            state = 24;
                            return ;
                        }
                        break;
                    case  20 :
                        if (("PLANTA" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.popAttributes();
                            state = 21;
                            return ;
                        }
                        break;
                    case  35 :
                        if (("ENTIDAD_MENOR" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.popAttributes();
                            state = 36;
                            return ;
                        }
                        break;
                    case  2 :
                        if (("INE_PROVINCIA" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  5 :
                        if (("INE_MUNICIPIO" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.popAttributes();
                            state = 6;
                            return ;
                        }
                        break;
                    case  26 :
                        if (("DUPLICADO" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.popAttributes();
                            state = 27;
                            return ;
                        }
                        break;
                    case  38 :
                        if (("RESTO" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.popAttributes();
                            state = 39;
                            return ;
                        }
                        break;
                    case  27 :
                        state = 30;
                        continue outer;
                    case  8 :
                        if (("TIPO_VIA" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.popAttributes();
                            state = 9;
                            return ;
                        }
                        break;
                    case  29 :
                        if (("BLOQUE" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.popAttributes();
                            state = 30;
                            return ;
                        }
                        break;
                    case  12 :
                        state = 15;
                        continue outer;
                    case  33 :
                        state = 36;
                        continue outer;
                    case  32 :
                        if (("APR_KM" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.popAttributes();
                            state = 33;
                            return ;
                        }
                        break;
                    case  11 :
                        if (("VIA" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.popAttributes();
                            state = 12;
                            return ;
                        }
                        break;
                    case  15 :
                        state = 18;
                        continue outer;
                    case  17 :
                        if (("ESCALERA" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.popAttributes();
                            state = 18;
                            return ;
                        }
                        break;
                    case  14 :
                        if (("NUMERO_VIA" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.popAttributes();
                            state = 15;
                            return ;
                        }
                        break;
                    case  18 :
                        state = 21;
                        continue outer;
                    case  24 :
                        state = 27;
                        continue outer;
                    case  30 :
                        state = 33;
                        continue outer;
                    case  21 :
                        state = 24;
                        continue outer;
                    case  36 :
                        state = 39;
                        continue outer;
                    case  41 :
                        if (("CODIGO_POSTAL" == ___local)&&("http://ancert.notariado.org/XML/Plusvalias/Liquidacion" == ___uri)) {
                            context.popAttributes();
                            state = 42;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  42 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  27 :
                        state = 30;
                        continue outer;
                    case  12 :
                        state = 15;
                        continue outer;
                    case  33 :
                        state = 36;
                        continue outer;
                    case  15 :
                        state = 18;
                        continue outer;
                    case  18 :
                        state = 21;
                        continue outer;
                    case  24 :
                        state = 27;
                        continue outer;
                    case  30 :
                        state = 33;
                        continue outer;
                    case  21 :
                        state = 24;
                        continue outer;
                    case  36 :
                        state = 39;
                        continue outer;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  42 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  27 :
                        state = 30;
                        continue outer;
                    case  12 :
                        state = 15;
                        continue outer;
                    case  33 :
                        state = 36;
                        continue outer;
                    case  15 :
                        state = 18;
                        continue outer;
                    case  18 :
                        state = 21;
                        continue outer;
                    case  24 :
                        state = 27;
                        continue outer;
                    case  30 :
                        state = 33;
                        continue outer;
                    case  21 :
                        state = 24;
                        continue outer;
                    case  36 :
                        state = 39;
                        continue outer;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  16 :
                            eatText1(value);
                            state = 17;
                            return ;
                        case  42 :
                            revertToParentFromText(value);
                            return ;
                        case  31 :
                            eatText2(value);
                            state = 32;
                            return ;
                        case  13 :
                            eatText3(value);
                            state = 14;
                            return ;
                        case  28 :
                            eatText4(value);
                            state = 29;
                            return ;
                        case  22 :
                            eatText5(value);
                            state = 23;
                            return ;
                        case  1 :
                            eatText6(value);
                            state = 2;
                            return ;
                        case  37 :
                            eatText7(value);
                            state = 38;
                            return ;
                        case  10 :
                            eatText8(value);
                            state = 11;
                            return ;
                        case  4 :
                            eatText9(value);
                            state = 5;
                            return ;
                        case  25 :
                            eatText10(value);
                            state = 26;
                            return ;
                        case  27 :
                            state = 30;
                            continue outer;
                        case  12 :
                            state = 15;
                            continue outer;
                        case  33 :
                            state = 36;
                            continue outer;
                        case  40 :
                            eatText11(value);
                            state = 41;
                            return ;
                        case  15 :
                            state = 18;
                            continue outer;
                        case  34 :
                            eatText12(value);
                            state = 35;
                            return ;
                        case  18 :
                            state = 21;
                            continue outer;
                        case  24 :
                            state = 27;
                            continue outer;
                        case  7 :
                            eatText13(value);
                            state = 8;
                            return ;
                        case  19 :
                            eatText14(value);
                            state = 20;
                            return ;
                        case  30 :
                            state = 33;
                            continue outer;
                        case  21 :
                            state = 24;
                            continue outer;
                        case  36 :
                            state = 39;
                            continue outer;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _ESCALERA = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _APRKM = javax.xml.bind.DatatypeConverter.parseInt(com.sun.xml.bind.WhiteSpaceProcessor.collapse(value));
                has_APRKM = true;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText3(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _NUMEROVIA = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText4(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _BLOQUE = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText5(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _PUERTA = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText6(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _INEPROVINCIA = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText7(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _RESTO = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText8(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _VIA = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText9(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _INEMUNICIPIO = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText10(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _DUPLICADO = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText11(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _CODIGOPOSTAL = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText12(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _ENTIDADMENOR = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText13(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _TIPOVIA = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText14(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _PLANTA = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

    }

}
