-- /***************************/
-- /* Actualización 4.0->4.2  */
-- /***************************/

	-- Insertar la versión actual de bd
	INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.0->4.2',getdate());
	GO

	-- Establecer el id de motivo en consultas como nulo
	ALTER TABLE ASGPCONSULTA ALTER COLUMN IDMOTIVO VARCHAR(32) NULL;
	GO

	-- Establecer el motivo en consultas como nulo
	ALTER TABLE ASGPCONSULTA ALTER COLUMN MOTIVO VARCHAR(254) NULL;
	GO

	-- Establecer el id de motivo en préstamos como nulo
	ALTER TABLE ASGPPRESTAMO ALTER COLUMN IDMOTIVO VARCHAR(32) NULL;
	GO

-- /***************************/
-- /* Actualización 4.2->4.3  */
-- /***************************/

	-- Insertar la versión actual de bd
	INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.2->4.3',getdate());
	GO

	--Añadir columna MARCASBLOQUEO
	ALTER TABLE ASGTUNIDADDOCRE ADD MARCASBLOQUEO INT NOT NULL DEFAULT 0;
	GO

	--Añadir columna MARCASBLOQUEO
	ALTER TABLE ASGFUNIDADDOC ADD MARCASBLOQUEO INT NOT NULL DEFAULT 0;
	GO

	-- /***************************/
-- /* Actualización 4.3->4.5  */
-- /***************************/
	-- Insertar la versión actual de bd
	INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.4',getdate());
	GO

	-- Crear tabla de Edificios
	CREATE TABLE dbo.ASGSEDIFICIO (
	  ID			VARCHAR (32) NOT NULL,
	  NOMBRE        VARCHAR (64) NOT NULL,
	  UBICACION     VARCHAR (254),
	  IDARCHIVO   	VARCHAR (32) NOT NULL
	);
	GO

	-- Crear índices de la tabla de Edificios
	CREATE UNIQUE INDEX ASGSEDIFICIO1 ON ASGSEDIFICIO(ID);
	GO
	CREATE UNIQUE INDEX ASGSEDIFICIO2 ON ASGSEDIFICIO(NOMBRE);
	GO

	-- Crear tabla de Salas
	CREATE TABLE dbo.ASGSSALA (
	  ID	 	  	  		VARCHAR (32) NOT NULL,
	  NOMBRE          		VARCHAR (64) NOT NULL,
	  DESCRIPCION     		VARCHAR (254),
	  IDEDIFICIO   	  		VARCHAR (32) NOT NULL,
	  EQUIPOINFORMATICO     CHAR(1) NOT NULL
	);
	GO

	-- Crear índices de la tabla de Salas
	CREATE UNIQUE INDEX ASGSSALA1 ON ASGSSALA(ID);
	GO
	CREATE UNIQUE INDEX ASGSSALA2 ON ASGSSALA(IDEDIFICIO,NOMBRE);
	GO
	CREATE INDEX ASGSSALA3 ON ASGSSALA(IDEDIFICIO);
	GO

	-- Crear tabla de Mesas
	CREATE TABLE dbo.ASGSMESA (
	  ID	 	  	  VARCHAR (32) NOT NULL,
	  CODIGO          VARCHAR (64) NOT NULL,
	  NUMORDEN	  	  INT NOT NULL,
	  IDSALA   	  	  VARCHAR (32) NOT NULL,
	  ESTADO          CHAR (1) NOT NULL,
	  FECHAESTADO     DATETIME NOT NULL,
	  IDUSRCSALA   	  VARCHAR (32)
	);
	GO

	-- Crear índices de la tabla Mesas
	CREATE INDEX ASGSMESA1 ON ASGSMESA(IDSALA);
	GO
	CREATE UNIQUE INDEX ASGSMESA2 ON ASGSMESA(IDSALA,CODIGO);
	GO
	CREATE UNIQUE INDEX ASGSMESA3 ON ASGSMESA(IDSALA,NUMORDEN);
	GO
	CREATE INDEX ASGSMESA4 ON ASGSMESA(ESTADO);
	GO

	-- Crear tabla de usuarios investigadores de consulta de sala
	CREATE TABLE dbo.ASGSUSRCSALA (
	  ID	 	  	  			VARCHAR (32) NOT NULL,
	  TIPODOCIDENTIFICACION     INT NOT NULL,
	  NUMDOCIDENTIFICACION		VARCHAR (32) NOT NULL,
	  NOMBRE			  	    VARCHAR (64) NOT NULL,
      APELLIDOS			  	    VARCHAR (254) NOT NULL,
	  NACIONALIDAD	   	  	    VARCHAR (64),
	  TELEFONOS					VARCHAR (128),
	  EMAIL						VARCHAR (128),
	  DIRECCION		            VARCHAR (254),
	  FECHAALTA				    DATETIME NOT NULL,
	  VIGENTE					CHAR (1) NOT NULL,
	  IDSCAUSR					VARCHAR (32)
	);
	GO

	-- Crear índices de la tabla usuarios investigadores
	CREATE UNIQUE INDEX ASGSUSRCSALA1 ON ASGSUSRCSALA(ID);
	GO
	CREATE INDEX ASGSUSRCSALA2 ON ASGSUSRCSALA(NUMDOCIDENTIFICACION);
	GO
	CREATE INDEX ASGSUSRCSALA3 ON ASGSUSRCSALA(VIGENTE);
	GO

	-- Crear tabla relación usuarios consulta y archivos
	CREATE TABLE dbo.ASGSUSRCSARCH (
	  IDUSRCSALA  	  VARCHAR (32) NOT NULL,
	  IDARCHIVO       VARCHAR (64) NOT NULL
	);
	GO

	-- Crear índices de la tabla de relación entre usuarios y archivos de consulta
	CREATE UNIQUE INDEX ASGSUSRCSARCH1 ON ASGSUSRCSARCH(IDUSRCSALA,IDARCHIVO);
	GO
	CREATE INDEX ASGSUSRCSARCH2 ON ASGSUSRCSARCH(IDUSRCSALA);
	GO

	-- Crear tabla de registro de consultas
	CREATE TABLE dbo.ASGSREGCSALA (
	  ID		  	  		VARCHAR (32) NOT NULL,
	  IDUSRCSALA  	  		VARCHAR (32) NOT NULL,
	  FENTRADA	      		DATETIME NOT NULL,
	  FSALIDA	      		DATETIME,
	  NUMDOCIDENTIFICACION	VARCHAR (32) NOT NULL,
	  NOMBREAPELLIDOS		VARCHAR (254) NOT NULL,
	  IDSCAUSR  	  		VARCHAR (32),
	  IDARCHIVO  	  		VARCHAR (32) NOT NULL,
	  MESAASIGNADA			VARCHAR (254) NOT NULL
	);
	GO

	-- Crear índices de la tabla de registro de consultas
	CREATE UNIQUE INDEX ASGSREGCSALA1 ON ASGSREGCSALA(ID);
	GO
	CREATE INDEX ASGSREGCSALA2 ON ASGSREGCSALA(IDUSRCSALA);
	GO
	CREATE INDEX ASGSREGCSALA3 ON ASGSREGCSALA(NUMDOCIDENTIFICACION);
	GO

	--Añadir columna IDUSRCSALA
	ALTER TABLE ASGPCONSULTA ADD IDUSRCSALA VARCHAR(32);
	GO

	--Añadir columna IDUSRCSALA en ASGPTEMA
	ALTER TABLE ASGPTEMA ADD IDUSRCSALA VARCHAR(32);
	GO

-- /***************************/
-- /* Actualización 4.4->4.5            */
-- /***************************/
	-- Insertar la versión actual de bd
	INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.4->4.5',getdate());

	--Añadir columnaS CONREENCAJADO E IDFORMATORE a la tabla de relaciones de entrega
	ALTER TABLE ASGTRENTREGA ADD CONREENCAJADO CHAR(1) NOT NULL DEFAULT 'N';
	GO
	ALTER TABLE ASGTRENTREGA ADD IDFORMATORE VARCHAR(32);
	GO

	--Añadir columna IDUIREEACR a la tabla de huecos
	ALTER TABLE ASGDHUECO ADD IDUIREEACR VARCHAR(32);
	GO

	--Crear la tabla de unidades de instalación transferencias entre archivo con reencajado
	CREATE TABLE ASGTUIREEACR (
	  ID			  VARCHAR (32)  NOT NULL,
	  IDRELENTREGA    VARCHAR (32)  NOT NULL,
	  IDUIDEPOSITO    VARCHAR (32),
	  SIGNATURAUI     VARCHAR (16),
	  IDFORMATO       VARCHAR (32) NOT NULL,
	  ORDEN			  SMALLINT NOT NULL,
	  ESTADOCOTEJO 	  SMALLINT NOT NULL	DEFAULT 1,
	  NOTASCOTEJO	  VARCHAR (256),
	  DEVOLUCION	  CHAR (1) DEFAULT 'N',
	  DESCRIPCION	  VARCHAR (256)
	);
	GO

	--Crear la tabla de unidades documentales en unidad de instalacion de transferencias
	--entre archivos con reencajado
	CREATE TABLE ASGTUDOCENUIREEACR (
	  ID			  VARCHAR (32)  NOT NULL,
	  IDUDOCORIGEN    VARCHAR (32)  NOT NULL,
	  IDRELENTREGA    VARCHAR (32)  NOT NULL,
	  IDUNIDADDOC     VARCHAR (32)  NOT NULL,
	  IDUIREEACR	  VARCHAR (32),
	  ASUNTO		  VARCHAR (1024) NOT NULL,
	  UDOCCOMPLETA	  VARCHAR (1) NOT NULL,
	  SIGNATURAUDOC   VARCHAR (32),
	  POSUDOCENUI     SMALLINT,
	  NUMEXP          VARCHAR (256),
	  NUMPARTE        SMALLINT,
	  FECHAINI        VARCHAR (64),
	  FECHAFIN        VARCHAR (64),
	  SIGNATURAUDOCORIGEN VARCHAR (32),
	  DESCRIPCION	  VARCHAR (256)
	);
	GO

	--Tabla de unidades documentales originales en el reencajado
	CREATE TABLE ASGTUDOCREEACR (
	  ID			  VARCHAR (32)  NOT NULL,
	  IDRELENTREGA    VARCHAR (32)  NOT NULL,
	  IDUNIDADDOC     VARCHAR (32)  NOT NULL,
	  SIGNATURAUDOC	  VARCHAR (32)  NOT NULL,
	  IDUIDEPOSITO	  VARCHAR (32)  NOT NULL,
	  SIGNATURAUI	  VARCHAR (16)  NOT NULL
	);
	GO

	-- Tabla: ASGTUIREEACR
	CREATE UNIQUE INDEX ASGTUIREEACR1 ON ASGTUIREEACR (ID);
	GO
	CREATE INDEX ASGTUIREEACR2 ON ASGTUIREEACR (IDRELENTREGA);
	GO

	-- Tabla: ASGTUDOCENUIREEACR
	CREATE UNIQUE INDEX ASGTUDOCENUIREEACR1 ON ASGTUDOCENUIREEACR (ID);
	GO
	CREATE INDEX ASGTUDOCENUIREEACR2 ON ASGTUDOCENUIREEACR (IDUDOCORIGEN);
	GO
	CREATE INDEX ASGTUDOCENUIREEACR3 ON ASGTUDOCENUIREEACR (IDRELENTREGA);
	GO
	CREATE INDEX ASGTUDOCENUIREEACR4 ON ASGTUDOCENUIREEACR (IDUNIDADDOC);
	GO
	CREATE INDEX ASGTUDOCENUIREEACR5 ON ASGTUDOCENUIREEACR (IDUIREEACR);
	GO
	CREATE INDEX ASGTUDOCENUIREEACR6 ON ASGTUDOCENUIREEACR (IDRELENTREGA,IDUNIDADDOC);
	GO

	-- Tabla: ASGTUDOCREEACR
	CREATE UNIQUE INDEX ASGTUDOCREEACR1 ON ASGTUDOCREEACR (ID);
	GO
	CREATE INDEX ASGTUDOCREEACR2 ON ASGTUDOCREEACR (IDRELENTREGA);
	GO
	CREATE INDEX ASGTUDOCREEACR3 ON ASGTUDOCREEACR (IDRELENTREGA,IDUNIDADDOC);
	GO

-- /***************************/
-- /* Actualización 4.5->4.7  */
-- /***************************/

INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.7',getdate());

--Catalogo de Tablas Temporales
--NOTA: Para esta funcionalidad necesario permiso de db_ddladmin o permisos para crear tablas. ya que la aplicacion necesita crear tablas en tiempo de ejecucion
CREATE TABLE ASGFCTLGTBLTMP(
	ID smallint	NOT NULL,
	NOMBRETABLA VARCHAR(16) NOT NULL,
	IDUSUARIO VARCHAR(32),
	ESTADO smallint default 0,
	FECHA datetime
);

CREATE UNIQUE INDEX ASGFCTLGTBLTMP1 ON ASGFCTLGTBLTMP(ID);
CREATE UNIQUE INDEX ASGFCTLGTBLTMP2 ON ASGFCTLGTBLTMP(NOMBRETABLA);

CREATE UNIQUE INDEX ASGFFONDO2 ON ASGFFONDO(CODARCHIVO,IDENTPRODUCTORA);

-- /***************************/
-- /* Actualización 4.7->4.8  */
-- /***************************/

INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.8',getdate());

--Fecha devolución en prorroga
ALTER TABLE ASGPPRORROGA ADD FECHAFINPRORROGA DATETIME;

--Motivo por el cual se solicita la prorroga
ALTER TABLE ASGPPRORROGA ADD MOTIVOPRORROGA VARCHAR(512);

IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ASGFELIMSELUDOC]') AND name = N'ASGFELIMSELUDOC1')
DROP INDEX [ASGFELIMSELUDOC1] ON [dbo].[ASGFELIMSELUDOC] WITH ( ONLINE = OFF )

IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ASGFELIMSELUDOC]') AND name = N'ASGFELIMSELUDOC2')
DROP INDEX [ASGFELIMSELUDOC2] ON [dbo].[ASGFELIMSELUDOC] WITH ( ONLINE = OFF )


--Modificar el nombre de la tabla ASGFELIMSELUDOC por ASGFELIMUDOCCONS
EXEC sp_rename 'ASGFELIMSELUDOC', 'ASGFELIMUDOCCONS';
GO

-- Tabla: ASGFELIMSELUDOC
CREATE INDEX ASGFELIMUDOCCONS1 ON ASGFELIMUDOCCONS (IDELIMINACION);
CREATE INDEX ASGFELIMUDOCCONS2 ON ASGFELIMUDOCCONS (IDUDOC);
GO

CREATE TABLE ASGFELIMSELUDOC(
	IDELIMINACION VARCHAR(32) NOT NULL,
	IDUDOC VARCHAR(32) NOT NULL,
	IDFONDO VARCHAR(32),
	CODREFERENCIA VARCHAR(1024),
	CODIGO VARCHAR(128),
	SIGNATURAUDOC VARCHAR(32),
	EXPEDIENTEUDOC VARCHAR(256),
	TITULO VARCHAR(1024),
	CODSISTPRODUCTOR VARCHAR(16),
	TIPODOCUMENTAL VARCHAR(254),
	IDUINSTALACION VARCHAR(32),
	UBICACION VARCHAR(512),
	FECHAINIUDOC DATETIME,
	FECHAFINUDOC DATETIME,
	NUMERO VARCHAR(10)

);
GO
-- Tabla: ASGFELIMSELUDOC
CREATE INDEX ASGFELIMSELUDOC1 ON ASGFELIMSELUDOC (IDELIMINACION);
CREATE INDEX ASGFELIMSELUDOC2 ON ASGFELIMSELUDOC (IDUDOC);


-- Tabla: ASGFUNIDADDOC4
CREATE INDEX ASGFUNIDADDOC4 ON ASGFUNIDADDOC(IDFONDO);


-- /***************************/
-- /* Versión 4.8 -> 5.0      */
-- /***************************/

INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.8->5.0',getdate());

--Renombrar IDLVOLPREF a IDREPECMPREF
EXEC sp_rename
		@objname = 'ADCTLGLISTAD.IDLVOLPREF',
		@newname = 'IDREPECMPREF',
		@objtype = 'COLUMN';
GO

--Renombrar IDLVOL a IDREPECM
EXEC sp_rename
		@objname = 'ADDESCRIPTOR.IDLVOL',
		@newname = 'IDREPECM',
		@objtype = 'COLUMN';
GO

--Renombrar IDLVOL a IDREPECM
EXEC sp_rename
		@objname = 'ASGFELEMENTOCF.IDLVOL',
		@newname = 'IDREPECM',
		@objtype = 'COLUMN';
GO

--Renombrar IDLVOLPREF a IDREPECMPREF
EXEC sp_rename
		@objname = 'ASGFNIVELCF.IDLVOLPREF',
		@newname = 'IDREPECMPREF',
		@objtype = 'COLUMN';
GO

--Renombrar INFOFICHAUDOCLVOL a INFOFICHAUDOCREPECM
EXEC sp_rename
		@objname = 'ASGFSERIE.INFOFICHAUDOCLVOL',
		@newname = 'INFOFICHAUDOCREPECM',
		@objtype = 'COLUMN';
GO

--Añadir idRepECm
ALTER TABLE ADOCDOCUMENTODESCR ADD IDREPECM VARCHAR(32);
ALTER TABLE ADOCDOCUMENTOCF ADD IDREPECM VARCHAR(32);
ALTER TABLE ADPCDOCUMENTOVIT ADD IDREPECM VARCHAR(32);

--Establecer el campo IDMOTIVO como NULL
ALTER TABLE ASGPCONSULTA ALTER COLUMN IDMOTIVO VARCHAR(32) NULL;

--Cambiar Tamaño de IDFICH a 128
ALTER TABLE ADPCDOCUMENTOVIT ALTER COLUMN IDFICH VARCHAR(128) NOT NULL;

--Añadir el campo subtiponivel
ALTER TABLE ADFICHA ADD SUBTIPONIVEL INT  DEFAULT 0 NOT NULL;


GO
--Actualizar los valores de subtiponivel
UPDATE ADFICHA SET SUBTIPONIVEL=61 WHERE ID='1';
UPDATE ADFICHA SET SUBTIPONIVEL=62 WHERE ID='6';

--Nuevo Índice por etiquetaxml en campo tabla
CREATE UNIQUE INDEX ADCAMPOTBL5 ON ADCAMPOTBL (ETIQUETAXML);

UPDATE ADCAMPODATO SET ETIQUETAXML = 'Documento_Fisico_Descripcion' WHERE ID='43' AND ETIQUETAXML = 'Descripcion';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Documento_Electronico_Descripcion' WHERE ID='50' AND ETIQUETAXML = 'Descripcion';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Identificacion' WHERE ID='1' AND ETIQUETAXML = 'Identificador';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Identificador_Recurso' WHERE ID='131' AND ETIQUETAXML = 'Identificador';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Entidad_Relacionada_Nombre' WHERE ID='114' AND ETIQUETAXML = 'Nombre';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Documento_Fisico_Nombre' WHERE ID='19' AND ETIQUETAXML = 'Nombre';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Productor_Nombre' WHERE ID='34' AND ETIQUETAXML = 'Nombre';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Documento_Electronico_Nombre' WHERE ID='49' AND ETIQUETAXML = 'Nombre';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Entidad_Relacionada_Tipo_Relacion' WHERE ID='115' AND ETIQUETAXML = 'Tipo_Relacion';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Entidad_Relacionada_Tipo_Relacion' WHERE ID='115' AND ETIQUETAXML = 'Tipo_Relación';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Naturaleza_Relacion' WHERE ID='133' AND ETIQUETAXML = 'Tipo_Relacion';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Naturaleza_Relacion' WHERE ID='133' AND ETIQUETAXML = 'Tipo_Relación';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Interesado_Validado' WHERE ID='12' AND ETIQUETAXML = 'Validado';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Emplazamiento_Validado' WHERE ID='212' AND ETIQUETAXML = 'Validado';

CREATE UNIQUE INDEX ADCAMPODATO6 ON ADCAMPODATO (ETIQUETAXML);

--Modificado el tamaño del nombre del formato
ALTER TABLE ADFMTFICHA ALTER COLUMN NOMBRE VARCHAR(128) NOT NULL;


--Nuevo Rol para el servicio web de transferencias
INSERT INTO ASCAROL (ID,NOMBRE, TIPOMODULO,DESCRIPCION)
VALUES('ID_ROL_WS_TRANSFERENCIAS','Servicio Web de Transferencias de Expedientes','2','Permisos necesarios para la ejecución del servicio web de transferencias');

-- Servicio Web de Transferencias

--Ampliado de Elaboración de Transferencias Ordinarias
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,201);

--Ubicación de Relaciones de Entrega
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,207);

-- Consulta de Cuadro de Clasificación
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,500);

--Solicitud de Alta de Serie
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,501);

-- Gestor de Serie
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,502);

-- Gestión de Solicitudes de Serie
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,503);

-- Creación en el Cuadro de Clasificación
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,505);

-- Consulta de Descripción en el Cuadro de Clasificación
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,600);

-- Edición de Descripción en el Cuadro de Clasificación
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,601);

-- Administración de Descripción
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,606);

-- Uso de Ficha Descriptiva en Altas/Relaciones
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,607);

--Administración de Usuarios, Órganos, Grupos y Perfiles
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,701);

-- Consulta de Documentos Electrónicos
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,900);

--Edición de Documentos Electrónicos
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,901);

--Tabla de Firmas
INSERT INTO ADCAMPOTBL (ID,NOMBRE,TIPONORMA,IDAREA,ETIQUETAXML, ETIQXMLFILA)
VALUES ('105','Firmas',1,'3','Firmas','Firma');

--Norma ENI
INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1001','Versión NTI',1,'1','3',NULL,NULL,'Version_NTI');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1002','Estado',1,'1','3',NULL,NULL,'Estado');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1003','Tipo de Firma',1,'1','3','105',1,'Tipo_Firma');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1004','Valor_CSV',2,'1','3','105',2,'Valor_CSV');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1005','Definición de Generación CSV',1,'1','3','105',3,'Definicion_Generacion_CSV');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1006','Identificador interno Firma',1,'1','3','105',4,'Id_Interno_Firma');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1011','Documento Electrónico: Versión NTI',1,'1','3','6',3, 'Documento_Electronico_Version_NTI');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1012','Documento Electrónico: Órgano',5,'1','3','6',4,'Documento_Electronico_Organo');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1013','Documento Electrónico: Fecha de Captura',3,'1','3','6',5,'Documento_Electronico_Fecha_Captura');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1014','Documento Electrónico: Origen',1,'1','3','6',6,'Documento_Electronico_Origen');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1015','Documento Electrónico: Estado Elaboración',1,'1','3','6',7,'Documento_Electronico_Estado_Elaboracion');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1016','Documento Electrónico: Nombre Formato',1,'1','3','6',8,'Documento_Electronico_Nombre_Formato');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1017','Documento Electrónico: Tipo Documental',1,'1','3','6',9,'Documento_Electronico_Tipo_Documental');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1018','Documento Electrónico: Tipo Firma',1,'1','3','6',10,'Documento_Electronico_Tipo_Firma');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1019','Documento Electrónico: Valor CSV',2,'1','3','6',11,'Documento_Electronico_Valor_CSV');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1020','Documento Electrónico: Definición Generación CSV',2,'1','3','6',12,'Documento_Electronico_Definicion_Generacion_CSV');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1021','Documento Electrónico: Identificador Documento Origen',1,'1','3','6',13,'Documento_Electronico_Identificador_Documento_Origen');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1022','Documento Electrónico: Id Interno',1,'1','3','6',14,'Documento_Electronico_Id_Interno');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1023','Documento Electrónico: Identificador interno Firma',1,'1','3','6',15,'Documento_Electronico_Id_Interno_Firma');

CREATE INDEX ASGFELEMENTOCF8 ON ASGFELEMENTOCF (CODIGO);
CREATE INDEX ASGFELEMENTOCF9 ON ASGFELEMENTOCF (ESTADO, IDNIVEL) INCLUDE (ID, CODREFERENCIA);
CREATE INDEX ASGFELEMENTOCF10 ON ASGFELEMENTOCF (IDNIVEL, ESTADO) INCLUDE (ID, CODREFERENCIA);
CREATE INDEX ASGFELEMENTOCF11 ON ASGFELEMENTOCF (IDNIVEL, IDPADRE, ESTADO) INCLUDE (ID);
CREATE INDEX ASGFELEMENTOCF12 ON ASGFELEMENTOCF (IDPADRE, ESTADO) INCLUDE (ID, IDNIVEL);
CREATE INDEX ASGFELEMENTOCF13 ON ASGFELEMENTOCF (IDNIVEL, IDPADRE, ESTADO) INCLUDE (ID, TIPO, CODIGO, TITULO, IDFONDO, CODREFFONDO, FINALCODREFPADRE, CODREFERENCIA, IDELIMINACION, IDFICHADESCR, TIENEDESCR, EDITCLFDOCS, IDREPECM, IDARCHIVO, NIVELACCESO, IDLCA, SUBTIPO, ORDPOS);
CREATE INDEX ASGFELEMENTOCF14 ON ASGFELEMENTOCF (IDPADRE, ESTADO) INCLUDE (ID, TIPO, IDNIVEL, CODIGO, TITULO, IDFONDO, CODREFFONDO, FINALCODREFPADRE, CODREFERENCIA, IDELIMINACION, IDFICHADESCR, TIENEDESCR, EDITCLFDOCS, IDREPECM, IDARCHIVO, NIVELACCESO, IDLCA, SUBTIPO, ORDPOS);

CREATE INDEX ADVCFECHACF6 ON ADVCFECHACF (IDCAMPO) INCLUDE (IDELEMENTOCF);
CREATE INDEX ADVCFECHACF7 ON ADVCFECHACF (IDCAMPO) INCLUDE (IDELEMENTOCF, FECHAINI);
CREATE INDEX ADVCFECHACF8 ON ADVCFECHACF (IDCAMPO) INCLUDE (IDELEMENTOCF, FECHAFIN);

IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ASGDSIGNUMORDEN]') AND name = N'SIGNUMORDEN1')
DROP INDEX SIGNUMORDEN1 ON ASGDSIGNUMORDEN;

IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ASGDSIGNUMORDEN]') AND name = N'ASGDSIGNUMORDEN1')
DROP INDEX ASGDSIGNUMORDEN1 ON ASGDSIGNUMORDEN;

CREATE UNIQUE INDEX ASGDSIGNUMORDEN1 ON ASGDSIGNUMORDEN (IDTIPOELEMPADRE, IDELEMPADRE, IDTIPOELEMENTO);


CREATE INDEX ASGDUDOCENUI5 ON ASGDUDOCENUI (SIGNATURAUDOC);

CREATE INDEX ASGFSERIE5 ON ASGFSERIE (IDUSRGESTOR, ESTADOSERIE);

CREATE INDEX ASGFDIVISIONFS2 ON ASGFDIVISIONFS (IDUSRGESTOR, ESTADO);

CREATE INDEX ASGPCONSULTA5 ON ASGPCONSULTA (ESTADO) INCLUDE (NUSRCONSULTOR, IDARCHIVO);
CREATE INDEX ASGPCONSULTA6 ON ASGPCONSULTA (ESTADO) INCLUDE (NORGCONSULTOR, IDARCHIVO);

CREATE INDEX ASGFUDOCENDIVISIONFS2 ON ASGFUDOCENDIVISIONFS (IDUDOC);


IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ADDESCRIPTOR]') AND name = N'ADDESCRIPTOR4')
DROP INDEX ADDESCRIPTOR4 ON ADDESCRIPTOR;

CREATE UNIQUE INDEX ADDESCRIPTOR4 ON ADDESCRIPTOR (IDLISTA, NOMBRE);


IF  EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[ASCAROL]') AND name = N'ASCAROL2')
DROP INDEX ASCAROL2 ON ASCAROL;

CREATE UNIQUE INDEX ASCAROL2 ON ASCAROL (NOMBRE);

