CREATE UNIQUE INDEX AOESTRORG1 ON AOESTRORG (ID);
CREATE UNIQUE INDEX AOESTRORG2 ON AOESTRORG (CODIGO);

CREATE INDEX AOUSR1 ON AOUSR (NOMBRE);
CREATE UNIQUE INDEX AOUSR2 ON AOUSR (NOMBREUSUARIO);

CREATE UNIQUE INDEX AOUSRORGV1 ON AOUSRORGV (IDUSUARIO);