

-------------------------------------------------
-- Actualización de prototipos de v5.2.2 a v5.2.3
-------------------------------------------------

--
-- i18n de las reglas de publicación de los prototipos
UPDATE pub_reglas SET atributos='<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>[ES]Solicitud recibida</label><label locale=''eu''>[EU]Solicitud recibida</label><label locale=''ca''>[CA]Solicitud recibida</label><label locale=''gl''>[GL]Solicitud recibida</label></labels></attribute></attributes>' where id=3;
UPDATE pub_reglas SET atributos='<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>[ES]Se está estudiando su solicitud</label><label locale=''eu''>[EU]Se está estudiando su solicitud</label><label locale=''ca''>[CA]Se está estudiando su solicitud</label><label locale=''gl''>[GL]Se está estudiando su solicitud</label></labels></attribute><attribute name=''PASO_A_HISTORICO''>S</attribute></attributes>' where id=6;
UPDATE pub_reglas SET atributos='<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>[ES]Se le enviará una comunicación referente al expediente</label><label locale=''eu''>[EU]Se le enviará una comunicación referente al expediente</label><label locale=''ca''>[CA]Se le enviará una comunicación referente al expediente</label><label locale=''gl''>[GL]Se le enviará una comunicación referente al expediente</label></labels></attribute><attribute name=''PASO_A_HISTORICO''>S</attribute><attribute name=''ENVIAR_DOCUMENTOS''>S</attribute></attributes>' where id=7;
UPDATE pub_reglas SET atributos='<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>[ES]Se le enviará una comunicación referente al expediente</label><label locale=''eu''>[EU]Se le enviará una comunicación referente al expediente</label><label locale=''ca''>[CA]Se le enviará una comunicación referente al expediente</label><label locale=''gl''>[GL]Se le enviará una comunicación referente al expediente</label></labels></attribute><attribute name=''PASO_A_HISTORICO''>S</attribute><attribute name=''ENVIAR_DOCUMENTOS''>S</attribute></attributes>' where id=8;
UPDATE pub_reglas SET atributos='<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>[ES]Expediente finalizado</label><label locale=''eu''>[EU]Expediente finalizado</label><label locale=''ca''>[CA]Expediente finalizado</label><label locale=''gl''>[GL]Expediente finalizado</label></labels></attribute><attribute name=''PASO_A_HISTORICO''>S</attribute></attributes>' where id=9;
UPDATE pub_reglas SET atributos='<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>[ES]Solicitud recibida</label><label locale=''eu''>[EU]Solicitud recibida</label><label locale=''ca''>[CA]Solicitud recibida</label><label locale=''gl''>[GL]Solicitud recibida</label></labels></attribute></attributes>' where id=11;
UPDATE pub_reglas SET atributos='<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>[ES]Comprobando la documentación aportada</label><label locale=''eu''>[EU]Comprobando la documentación aportada</label><label locale=''ca''>[CA]Comprobando la documentación aportada</label><label locale=''gl''>[GL]Comprobando la documentación aportada</label></labels></attribute><attribute name=''PASO_A_HISTORICO''>S</attribute></attributes>' where id=13;
UPDATE pub_reglas SET atributos='<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>[ES]Se está estudiando su solicitud</label><label locale=''eu''>[EU]Se está estudiando su solicitud</label><label locale=''ca''>[CA]Se está estudiando su solicitud</label><label locale=''gl''>[GL]Se está estudiando su solicitud</label></labels></attribute><attribute name=''PASO_A_HISTORICO''>S</attribute></attributes>' where id=16;
UPDATE pub_reglas SET atributos='<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>[ES]Decisión sobre la solicitud</label><label locale=''eu''>[EU]Decisión sobre la solicitud</label><label locale=''ca''>[CA]Decisión sobre la solicitud</label><label locale=''gl''>[GL]Decisión sobre la solicitud</label></labels></attribute><attribute name=''PASO_A_HISTORICO''>S</attribute><attribute name=''ENVIAR_DOCUMENTOS''>S</attribute></attributes>' where id=17;
UPDATE pub_reglas SET atributos='<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>[ES]Expediente finalizado</label><label locale=''eu''>[EU]Expediente finalizado</label><label locale=''ca''>[CA]Expediente finalizado</label><label locale=''gl''>[GL]Expediente finalizado</label></labels></attribute><attribute name=''PASO_A_HISTORICO''>S</attribute></attributes>' where id=18;
UPDATE pub_reglas SET atributos='<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>[ES]Solicitud recibida</label><label locale=''eu''>[EU]Solicitud recibida</label><label locale=''ca''>[CA]Solicitud recibida</label><label locale=''gl''>[GL]Solicitud recibida</label></labels></attribute></attributes>' where id=20;
UPDATE pub_reglas SET atributos='<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>[ES]Comprobando la documentación aportada</label><label locale=''eu''>[EU]Comprobando la documentación aportada</label><label locale=''ca''>[CA]Comprobando la documentación aportada</label><label locale=''gl''>[GL]Comprobando la documentación aportada</label></labels></attribute><attribute name=''PASO_A_HISTORICO''>S</attribute></attributes>' where id=22;
UPDATE pub_reglas SET atributos='<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>[ES]Se está estudiando su solicitud</label><label locale=''eu''>[EU]Se está estudiando su solicitud</label><label locale=''ca''>[CA]Se está estudiando su solicitud</label><label locale=''gl''>[GL]Se está estudiando su solicitud</label></labels></attribute><attribute name=''PASO_A_HISTORICO''>S</attribute></attributes>' where id=25;
UPDATE pub_reglas SET atributos='<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>[ES]Decisión sobre la solicitud</label><label locale=''eu''>[EU]Decisión sobre la solicitud</label><label locale=''ca''>[CA]Decisión sobre la solicitud</label><label locale=''gl''>[GL]Decisión sobre la solicitud</label></labels></attribute><attribute name=''PASO_A_HISTORICO''>S</attribute><attribute name=''ENVIAR_DOCUMENTOS''>S</attribute></attributes>' where id=26;
UPDATE pub_reglas SET atributos='<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>[ES]Expediente finalizado</label><label locale=''eu''>[EU]Expediente finalizado</label><label locale=''ca''>[CA]Expediente finalizado</label><label locale=''gl''>[GL]Expediente finalizado</label></labels></attribute><attribute name=''PASO_A_HISTORICO''>S</attribute></attributes>' where id=27;
UPDATE pub_reglas SET atributos='<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''TASA_1''><tax><labels><label locale=''es''>[ES]Resguardo del pago de tasa</label><label locale=''eu''>[EU]Resguardo del pago de tasa</label><label locale=''ca''>[CA]Resguardo del pago de tasa</label><label locale=''gl''>[GL]Resguardo del pago de tasa</label></labels><import>1000</import><sender_entity_id>000000</sender_entity_id><self_settlement_id>100</self_settlement_id></tax></attribute></attributes>' where id=23;
