--  Crear tablas para el conector de organización

CREATE TABLE AOESTRORG(
	ID               VARCHAR(32) NOT NULL,
	CODIGO           VARCHAR(64) NOT NULL,
	NOMBRE           VARCHAR(254) NOT NULL,
	TIPO             INTEGER NOT NULL,
	NIVEL            INTEGER NOT NULL,
	IDORGPADRE       VARCHAR(32),
	ESTADO           INTEGER NOT NULL,
	FINICIOVIGENCIA  TIMESTAMP,
	FFINVIGENCIA     TIMESTAMP,
	DESCRIPCION      VARCHAR(254)
);

CREATE TABLE AOUSR(
	ID             VARCHAR(64) NOT NULL,
	DIRECCION      VARCHAR(254),
	EMAIL          VARCHAR(254),
	NOMBRE         VARCHAR(64),
	APELLIDOS      VARCHAR(128),
	NOMBREUSUARIO  VARCHAR(64) NOT NULL,
	PASSWORD       VARCHAR(64) NOT NULL
);

CREATE TABLE AOUSRORGV(
	IDUSUARIO      VARCHAR(64) NOT NULL,
	NOMBREUSUARIO  VARCHAR(254) NOT NULL,
	IDORGANO       VARCHAR(32) NOT NULL
);



-- Si las tablas se meten en un schema distinto del de archivo habría que ejecutar las siguientes sentencias:

-- CREATE TABLE ITDGUIDGEN(
-- 	cnode  VARCHAR(12),
--	clpid  INTEGER
-- );

-- INSERT INTO ITDGUIDGEN (CNODE, CLPID) VALUES ('000000000000', 1);
