//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v@@BUILD_VERSION@@ 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2011.07.04 en 12:38:50 CEST 
//


package org.notariado.ancert.xml.plusvalias.liquidacion;


/**
 * Java content class for anonymous complex type.
 * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 8)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="REQUEST">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="CABECERA" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}CabeceraType"/>
 *                     &lt;element name="NOTARIO_TITULAR" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}NotarioType"/>
 *                     &lt;element name="NOTARIO_AUTORIZANTE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}NotarioType"/>
 *                     &lt;element name="PROTOCOLO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}ProtocoloType"/>
 *                     &lt;element name="ACTO_JURIDICO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}ActoJuridicoType"/>
 *                     &lt;element name="TRANSMITENTES">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="TRANSMITENTE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}TransmitenteType" maxOccurs="unbounded"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="ADQUIRENTES">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="ADQUIRENTE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}AdquirenteType" maxOccurs="unbounded"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="INMUEBLE">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="REFERENCIA_CATASTRAL" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}REFERENCIA_CATASTRALType"/>
 *                               &lt;element name="DIRECCION">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element name="INE_PROVINCIA" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}CODIGO_PROVINCIAType"/>
 *                                         &lt;element name="INE_MUNICIPIO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}CODIGO_MUNICIPIOType"/>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="REPRESENTANTES" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="REPRESENTANTE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}SujetoType" maxOccurs="unbounded"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="REPLY">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="CABECERA" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}CabeceraType"/>
 *                     &lt;sequence minOccurs="0">
 *                       &lt;element name="NOTARIO_TITULAR" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}NotarioType"/>
 *                       &lt;element name="NOTARIO_AUTORIZANTE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}NotarioType"/>
 *                       &lt;element name="PROTOCOLO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}ProtocoloType"/>
 *                       &lt;element name="ACTO_JURIDICO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}ActoJuridicoType"/>
 *                       &lt;element name="TRANSMITENTES">
 *                         &lt;complexType>
 *                           &lt;complexContent>
 *                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                               &lt;sequence>
 *                                 &lt;element name="TRANSMITENTE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}TransmitenteType" maxOccurs="unbounded"/>
 *                               &lt;/sequence>
 *                             &lt;/restriction>
 *                           &lt;/complexContent>
 *                         &lt;/complexType>
 *                       &lt;/element>
 *                       &lt;element name="ADQUIRENTES">
 *                         &lt;complexType>
 *                           &lt;complexContent>
 *                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                               &lt;sequence>
 *                                 &lt;element name="ADQUIRENTE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}AdquirenteType" maxOccurs="unbounded"/>
 *                               &lt;/sequence>
 *                             &lt;/restriction>
 *                           &lt;/complexContent>
 *                         &lt;/complexType>
 *                       &lt;/element>
 *                       &lt;element name="INMUEBLE">
 *                         &lt;complexType>
 *                           &lt;complexContent>
 *                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                               &lt;sequence>
 *                                 &lt;element name="REFERENCIA_CATASTRAL" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}REFERENCIA_CATASTRALType"/>
 *                                 &lt;element name="DIRECCION" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}DireccionInmuebleType"/>
 *                                 &lt;element name="SUPERFICIE_INMUEBLE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}SUPERFICIE_INMUEBLEType" minOccurs="0"/>
 *                               &lt;/sequence>
 *                             &lt;/restriction>
 *                           &lt;/complexContent>
 *                         &lt;/complexType>
 *                       &lt;/element>
 *                       &lt;element name="REPRESENTANTES" minOccurs="0">
 *                         &lt;complexType>
 *                           &lt;complexContent>
 *                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                               &lt;sequence>
 *                                 &lt;element name="REPRESENTANTE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}SujetoType" maxOccurs="unbounded"/>
 *                               &lt;/sequence>
 *                             &lt;/restriction>
 *                           &lt;/complexContent>
 *                         &lt;/complexType>
 *                       &lt;/element>
 *                       &lt;element name="IMPORTE_TOTAL" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}IMPORTE_ECONOMICOType"/>
 *                       &lt;element name="DOCUMENTOS">
 *                         &lt;complexType>
 *                           &lt;complexContent>
 *                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                               &lt;sequence>
 *                                 &lt;element name="DOCUMENTO" maxOccurs="unbounded">
 *                                   &lt;complexType>
 *                                     &lt;complexContent>
 *                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                         &lt;sequence>
 *                                           &lt;element name="ID_SUJETO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}ID_SECUENCIALType"/>
 *                                           &lt;element name="IMPORTE">
 *                                             &lt;complexType>
 *                                               &lt;complexContent>
 *                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                   &lt;sequence>
 *                                                     &lt;element name="INFORMA_RECARGO" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                                                     &lt;element name="PORCENTAJE_RECARGO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}PORCENTAJEType" minOccurs="0"/>
 *                                                     &lt;element name="IMPORTE_RECARGO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}IMPORTE_ECONOMICOType" minOccurs="0"/>
 *                                                     &lt;element name="IMPORTE_TOTAL" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}IMPORTE_ECONOMICOType"/>
 *                                                   &lt;/sequence>
 *                                                 &lt;/restriction>
 *                                               &lt;/complexContent>
 *                                             &lt;/complexType>
 *                                           &lt;/element>
 *                                           &lt;element name="PDF">
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}base64Binary">
 *                                               &lt;minLength value="1"/>
 *                                             &lt;/restriction>
 *                                           &lt;/element>
 *                                         &lt;/sequence>
 *                                       &lt;/restriction>
 *                                     &lt;/complexContent>
 *                                   &lt;/complexType>
 *                                 &lt;/element>
 *                               &lt;/sequence>
 *                             &lt;/restriction>
 *                           &lt;/complexContent>
 *                         &lt;/complexType>
 *                       &lt;/element>
 *                     &lt;/sequence>
 *                     &lt;element name="RESULTADO">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="RETORNO" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                               &lt;element name="ERROR" minOccurs="0">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element name="CODIGO">
 *                                           &lt;restriction base="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}STRINGType">
 *                                             &lt;length value="4"/>
 *                                           &lt;/restriction>
 *                                         &lt;/element>
 *                                         &lt;element name="DESCRIPCION">
 *                                           &lt;restriction base="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}STRINGType">
 *                                             &lt;minLength value="1"/>
 *                                             &lt;maxLength value="255"/>
 *                                           &lt;/restriction>
 *                                         &lt;/element>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface CALCULOLIQUIDACIONType {


    /**
     * Respuesta con el resultado del cálculo enviado por el organismo de gestión tributaria.
     * 
     * @return
     *     possible object is
     *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType}
     */
    org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType getREPLY();

    /**
     * Respuesta con el resultado del cálculo enviado por el organismo de gestión tributaria.
     * 
     * @param value
     *     allowed object is
     *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType}
     */
    void setREPLY(org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType value);

    /**
     * Petición de cálculo enviado desde el CGN
     * 
     * @return
     *     possible object is
     *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType}
     */
    org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType getREQUEST();

    /**
     * Petición de cálculo enviado desde el CGN
     * 
     * @param value
     *     allowed object is
     *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType}
     */
    void setREQUEST(org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType value);


    /**
     * Java content class for anonymous complex type.
     * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 109)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CABECERA" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}CabeceraType"/>
     *         &lt;sequence minOccurs="0">
     *           &lt;element name="NOTARIO_TITULAR" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}NotarioType"/>
     *           &lt;element name="NOTARIO_AUTORIZANTE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}NotarioType"/>
     *           &lt;element name="PROTOCOLO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}ProtocoloType"/>
     *           &lt;element name="ACTO_JURIDICO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}ActoJuridicoType"/>
     *           &lt;element name="TRANSMITENTES">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element name="TRANSMITENTE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}TransmitenteType" maxOccurs="unbounded"/>
     *                   &lt;/sequence>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *           &lt;element name="ADQUIRENTES">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element name="ADQUIRENTE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}AdquirenteType" maxOccurs="unbounded"/>
     *                   &lt;/sequence>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *           &lt;element name="INMUEBLE">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element name="REFERENCIA_CATASTRAL" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}REFERENCIA_CATASTRALType"/>
     *                     &lt;element name="DIRECCION" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}DireccionInmuebleType"/>
     *                     &lt;element name="SUPERFICIE_INMUEBLE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}SUPERFICIE_INMUEBLEType" minOccurs="0"/>
     *                   &lt;/sequence>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *           &lt;element name="REPRESENTANTES" minOccurs="0">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element name="REPRESENTANTE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}SujetoType" maxOccurs="unbounded"/>
     *                   &lt;/sequence>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *           &lt;element name="IMPORTE_TOTAL" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}IMPORTE_ECONOMICOType"/>
     *           &lt;element name="DOCUMENTOS">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element name="DOCUMENTO" maxOccurs="unbounded">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;sequence>
     *                               &lt;element name="ID_SUJETO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}ID_SECUENCIALType"/>
     *                               &lt;element name="IMPORTE">
     *                                 &lt;complexType>
     *                                   &lt;complexContent>
     *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                       &lt;sequence>
     *                                         &lt;element name="INFORMA_RECARGO" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                                         &lt;element name="PORCENTAJE_RECARGO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}PORCENTAJEType" minOccurs="0"/>
     *                                         &lt;element name="IMPORTE_RECARGO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}IMPORTE_ECONOMICOType" minOccurs="0"/>
     *                                         &lt;element name="IMPORTE_TOTAL" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}IMPORTE_ECONOMICOType"/>
     *                                       &lt;/sequence>
     *                                     &lt;/restriction>
     *                                   &lt;/complexContent>
     *                                 &lt;/complexType>
     *                               &lt;/element>
     *                               &lt;element name="PDF">
     *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}base64Binary">
     *                                   &lt;minLength value="1"/>
     *                                 &lt;/restriction>
     *                               &lt;/element>
     *                             &lt;/sequence>
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                   &lt;/sequence>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *         &lt;/sequence>
     *         &lt;element name="RESULTADO">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RETORNO" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="ERROR" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CODIGO">
     *                               &lt;restriction base="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}STRINGType">
     *                                 &lt;length value="4"/>
     *                               &lt;/restriction>
     *                             &lt;/element>
     *                             &lt;element name="DESCRIPCION">
     *                               &lt;restriction base="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}STRINGType">
     *                                 &lt;minLength value="1"/>
     *                                 &lt;maxLength value="255"/>
     *                               &lt;/restriction>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface REPLYType {


        /**
         * Operación que origina el impuesto.
         * 
         * @return
         *     possible object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.ActoJuridicoType}
         */
        org.notariado.ancert.xml.plusvalias.liquidacion.ActoJuridicoType getACTOJURIDICO();

        /**
         * Operación que origina el impuesto.
         * 
         * @param value
         *     allowed object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.ActoJuridicoType}
         */
        void setACTOJURIDICO(org.notariado.ancert.xml.plusvalias.liquidacion.ActoJuridicoType value);

        /**
         * Datos del Notario autorizante del documento
         * 
         * @return
         *     possible object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.NotarioType}
         */
        org.notariado.ancert.xml.plusvalias.liquidacion.NotarioType getNOTARIOAUTORIZANTE();

        /**
         * Datos del Notario autorizante del documento
         * 
         * @param value
         *     allowed object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.NotarioType}
         */
        void setNOTARIOAUTORIZANTE(org.notariado.ancert.xml.plusvalias.liquidacion.NotarioType value);

        /**
         * Cada uno de los sujetos que adquieren el inmueble o terreno urbano transmitido.
         * 
         * @return
         *     possible object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.ADQUIRENTESType}
         */
        org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.ADQUIRENTESType getADQUIRENTES();

        /**
         * Cada uno de los sujetos que adquieren el inmueble o terreno urbano transmitido.
         * 
         * @param value
         *     allowed object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.ADQUIRENTESType}
         */
        void setADQUIRENTES(org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.ADQUIRENTESType value);

        /**
         * Datos identificativos del documento notarial.
         * 
         * @return
         *     possible object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.ProtocoloType}
         */
        org.notariado.ancert.xml.plusvalias.liquidacion.ProtocoloType getPROTOCOLO();

        /**
         * Datos identificativos del documento notarial.
         * 
         * @param value
         *     allowed object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.ProtocoloType}
         */
        void setPROTOCOLO(org.notariado.ancert.xml.plusvalias.liquidacion.ProtocoloType value);

        /**
         * PDFs con el cálculo de la liquidación de cada sujeto pasivo del impuesto.
         * 
         * @return
         *     possible object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.DOCUMENTOSType}
         */
        org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.DOCUMENTOSType getDOCUMENTOS();

        /**
         * PDFs con el cálculo de la liquidación de cada sujeto pasivo del impuesto.
         * 
         * @param value
         *     allowed object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.DOCUMENTOSType}
         */
        void setDOCUMENTOS(org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.DOCUMENTOSType value);

        /**
         * Representantes legales.
         * 
         * @return
         *     possible object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.REPRESENTANTESType}
         */
        org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.REPRESENTANTESType getREPRESENTANTES();

        /**
         * Representantes legales.
         * 
         * @param value
         *     allowed object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.REPRESENTANTESType}
         */
        void setREPRESENTANTES(org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.REPRESENTANTESType value);

        /**
         * Resultado de la petición . Los datos del cálculo no seran obligatorios si el retorno es distinto de cero.
         * 
         * @return
         *     possible object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.RESULTADOType}
         */
        org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.RESULTADOType getRESULTADO();

        /**
         * Resultado de la petición . Los datos del cálculo no seran obligatorios si el retorno es distinto de cero.
         * 
         * @param value
         *     allowed object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.RESULTADOType}
         */
        void setRESULTADO(org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.RESULTADOType value);

        /**
         * Importe total de la liquidación
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getIMPORTETOTAL();

        /**
         * Importe total de la liquidación
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setIMPORTETOTAL(java.lang.String value);

        /**
         * Objeto transmitido
         * 
         * @return
         *     possible object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.INMUEBLEType}
         */
        org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.INMUEBLEType getINMUEBLE();

        /**
         * Objeto transmitido
         * 
         * @param value
         *     allowed object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.INMUEBLEType}
         */
        void setINMUEBLE(org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.INMUEBLEType value);

        /**
         * Cabecera del mensaje.
         * 
         * @return
         *     possible object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CabeceraType}
         */
        org.notariado.ancert.xml.plusvalias.liquidacion.CabeceraType getCABECERA();

        /**
         * Cabecera del mensaje.
         * 
         * @param value
         *     allowed object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CabeceraType}
         */
        void setCABECERA(org.notariado.ancert.xml.plusvalias.liquidacion.CabeceraType value);

        /**
         * Cada uno de los sujetos que transmiten el inmueble o terreno urbano.
         * 
         * @return
         *     possible object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.TRANSMITENTESType}
         */
        org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.TRANSMITENTESType getTRANSMITENTES();

        /**
         * Cada uno de los sujetos que transmiten el inmueble o terreno urbano.
         * 
         * @param value
         *     allowed object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.TRANSMITENTESType}
         */
        void setTRANSMITENTES(org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.TRANSMITENTESType value);

        /**
         * Datos del Notario titular del documento
         * 
         * @return
         *     possible object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.NotarioType}
         */
        org.notariado.ancert.xml.plusvalias.liquidacion.NotarioType getNOTARIOTITULAR();

        /**
         * Datos del Notario titular del documento
         * 
         * @param value
         *     allowed object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.NotarioType}
         */
        void setNOTARIOTITULAR(org.notariado.ancert.xml.plusvalias.liquidacion.NotarioType value);


        /**
         * Java content class for anonymous complex type.
         * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 154)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ADQUIRENTE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}AdquirenteType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface ADQUIRENTESType {


            /**
             * Gets the value of the ADQUIRENTE property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the ADQUIRENTE property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getADQUIRENTE().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link org.notariado.ancert.xml.plusvalias.liquidacion.AdquirenteType}
             * 
             */
            java.util.List getADQUIRENTE();

        }


        /**
         * Java content class for anonymous complex type.
         * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 199)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="DOCUMENTO" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ID_SUJETO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}ID_SECUENCIALType"/>
         *                   &lt;element name="IMPORTE">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="INFORMA_RECARGO" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *                             &lt;element name="PORCENTAJE_RECARGO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}PORCENTAJEType" minOccurs="0"/>
         *                             &lt;element name="IMPORTE_RECARGO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}IMPORTE_ECONOMICOType" minOccurs="0"/>
         *                             &lt;element name="IMPORTE_TOTAL" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}IMPORTE_ECONOMICOType"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="PDF">
         *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}base64Binary">
         *                       &lt;minLength value="1"/>
         *                     &lt;/restriction>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface DOCUMENTOSType {


            /**
             * Gets the value of the DOCUMENTO property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the DOCUMENTO property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDOCUMENTO().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.DOCUMENTOSType.DOCUMENTOType}
             * 
             */
            java.util.List getDOCUMENTO();


            /**
             * Java content class for anonymous complex type.
             * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 202)
             * <p>
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ID_SUJETO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}ID_SECUENCIALType"/>
             *         &lt;element name="IMPORTE">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="INFORMA_RECARGO" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
             *                   &lt;element name="PORCENTAJE_RECARGO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}PORCENTAJEType" minOccurs="0"/>
             *                   &lt;element name="IMPORTE_RECARGO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}IMPORTE_ECONOMICOType" minOccurs="0"/>
             *                   &lt;element name="IMPORTE_TOTAL" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}IMPORTE_ECONOMICOType"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="PDF">
             *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}base64Binary">
             *             &lt;minLength value="1"/>
             *           &lt;/restriction>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             */
            public interface DOCUMENTOType {


                /**
                 * Contenido del documento PDF en base64
                 * 
                 * @return
                 *     possible object is
                 *     byte[]
                 */
                byte[] getPDF();

                /**
                 * Contenido del documento PDF en base64
                 * 
                 * @param value
                 *     allowed object is
                 *     byte[]
                 */
                void setPDF(byte[] value);

                /**
                 * Identificador del sujeto pasivo.
                 * 
                 */
                long getIDSUJETO();

                /**
                 * Identificador del sujeto pasivo.
                 * 
                 */
                void setIDSUJETO(long value);

                /**
                 * Gets the value of the importe property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.DOCUMENTOSType.DOCUMENTOType.IMPORTEType}
                 */
                org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.DOCUMENTOSType.DOCUMENTOType.IMPORTEType getIMPORTE();

                /**
                 * Sets the value of the importe property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.DOCUMENTOSType.DOCUMENTOType.IMPORTEType}
                 */
                void setIMPORTE(org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.DOCUMENTOSType.DOCUMENTOType.IMPORTEType value);


                /**
                 * Java content class for anonymous complex type.
                 * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 210)
                 * <p>
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="INFORMA_RECARGO" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
                 *         &lt;element name="PORCENTAJE_RECARGO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}PORCENTAJEType" minOccurs="0"/>
                 *         &lt;element name="IMPORTE_RECARGO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}IMPORTE_ECONOMICOType" minOccurs="0"/>
                 *         &lt;element name="IMPORTE_TOTAL" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}IMPORTE_ECONOMICOType"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 */
                public interface IMPORTEType {


                    /**
                     * Importe del recargo
                     * 
                     * @return
                     *     possible object is
                     *     {@link java.lang.String}
                     */
                    java.lang.String getIMPORTERECARGO();

                    /**
                     * Importe del recargo
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link java.lang.String}
                     */
                    void setIMPORTERECARGO(java.lang.String value);

                    /**
                     * Indica si el ayuntamiento devuelve los cálculos aplicando recargos en caso que sean aplicables
                     * 
                     */
                    boolean isINFORMARECARGO();

                    /**
                     * Indica si el ayuntamiento devuelve los cálculos aplicando recargos en caso que sean aplicables
                     * 
                     */
                    void setINFORMARECARGO(boolean value);

                    /**
                     * Importe total a pagar por sujeto pasivo incluyendo los recargos que informe el ayuntamiento
                     * 
                     * @return
                     *     possible object is
                     *     {@link java.lang.String}
                     */
                    java.lang.String getIMPORTETOTAL();

                    /**
                     * Importe total a pagar por sujeto pasivo incluyendo los recargos que informe el ayuntamiento
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link java.lang.String}
                     */
                    void setIMPORTETOTAL(java.lang.String value);

                    /**
                     * Porcentaje que se aplicará
                     * 
                     * @return
                     *     possible object is
                     *     {@link java.lang.String}
                     */
                    java.lang.String getPORCENTAJERECARGO();

                    /**
                     * Porcentaje que se aplicará
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link java.lang.String}
                     */
                    void setPORCENTAJERECARGO(java.lang.String value);

                }

            }

        }


        /**
         * Java content class for anonymous complex type.
         * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 164)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="REFERENCIA_CATASTRAL" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}REFERENCIA_CATASTRALType"/>
         *         &lt;element name="DIRECCION" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}DireccionInmuebleType"/>
         *         &lt;element name="SUPERFICIE_INMUEBLE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}SUPERFICIE_INMUEBLEType" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface INMUEBLEType {


            /**
             * Se indicará la superfície del inmueble en metros cuadrados.
             * 
             * @return
             *     possible object is
             *     {@link java.lang.String}
             */
            java.lang.String getSUPERFICIEINMUEBLE();

            /**
             * Se indicará la superfície del inmueble en metros cuadrados.
             * 
             * @param value
             *     allowed object is
             *     {@link java.lang.String}
             */
            void setSUPERFICIEINMUEBLE(java.lang.String value);

            /**
             * Gets the value of the direccion property.
             * 
             * @return
             *     possible object is
             *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.DireccionInmuebleType}
             */
            org.notariado.ancert.xml.plusvalias.liquidacion.DireccionInmuebleType getDIRECCION();

            /**
             * Sets the value of the direccion property.
             * 
             * @param value
             *     allowed object is
             *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.DireccionInmuebleType}
             */
            void setDIRECCION(org.notariado.ancert.xml.plusvalias.liquidacion.DireccionInmuebleType value);

            /**
             * Referéncia Catastral completa.
             * 
             * @return
             *     possible object is
             *     {@link java.lang.String}
             */
            java.lang.String getREFERENCIACATASTRAL();

            /**
             * Referéncia Catastral completa.
             * 
             * @param value
             *     allowed object is
             *     {@link java.lang.String}
             */
            void setREFERENCIACATASTRAL(java.lang.String value);

        }


        /**
         * Java content class for anonymous complex type.
         * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 184)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="REPRESENTANTE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}SujetoType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface REPRESENTANTESType {


            /**
             * Gets the value of the REPRESENTANTE property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the REPRESENTANTE property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getREPRESENTANTE().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link org.notariado.ancert.xml.plusvalias.liquidacion.SujetoType}
             * 
             */
            java.util.List getREPRESENTANTE();

        }


        /**
         * Java content class for anonymous complex type.
         * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 256)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RETORNO" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="ERROR" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CODIGO">
         *                     &lt;restriction base="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}STRINGType">
         *                       &lt;length value="4"/>
         *                     &lt;/restriction>
         *                   &lt;/element>
         *                   &lt;element name="DESCRIPCION">
         *                     &lt;restriction base="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}STRINGType">
         *                       &lt;minLength value="1"/>
         *                       &lt;maxLength value="255"/>
         *                     &lt;/restriction>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface RESULTADOType {


            /**
             * Se indicará 0 si la operación ha sido completada correctamente. En caso contrario se indicará 1.
             * 
             */
            boolean isRETORNO();

            /**
             * Se indicará 0 si la operación ha sido completada correctamente. En caso contrario se indicará 1.
             * 
             */
            void setRETORNO(boolean value);

            /**
             * En caso de error se indicará el código y la descripción.
             * 
             * @return
             *     possible object is
             *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.RESULTADOType.ERRORType}
             */
            org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.RESULTADOType.ERRORType getERROR();

            /**
             * En caso de error se indicará el código y la descripción.
             * 
             * @param value
             *     allowed object is
             *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.RESULTADOType.ERRORType}
             */
            void setERROR(org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.RESULTADOType.ERRORType value);


            /**
             * Java content class for anonymous complex type.
             * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 267)
             * <p>
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CODIGO">
             *           &lt;restriction base="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}STRINGType">
             *             &lt;length value="4"/>
             *           &lt;/restriction>
             *         &lt;/element>
             *         &lt;element name="DESCRIPCION">
             *           &lt;restriction base="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}STRINGType">
             *             &lt;minLength value="1"/>
             *             &lt;maxLength value="255"/>
             *           &lt;/restriction>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             */
            public interface ERRORType {


                /**
                 * Descripción del error.
                 * 
                 * @return
                 *     possible object is
                 *     {@link java.lang.String}
                 */
                java.lang.String getDESCRIPCION();

                /**
                 * Descripción del error.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link java.lang.String}
                 */
                void setDESCRIPCION(java.lang.String value);

                /**
                 * Código del error pactado entre el organismo de gestión tributaria y el CGN.
                 * 
                 * @return
                 *     possible object is
                 *     {@link java.lang.String}
                 */
                java.lang.String getCODIGO();

                /**
                 * Código del error pactado entre el organismo de gestión tributaria y el CGN.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link java.lang.String}
                 */
                void setCODIGO(java.lang.String value);

            }

        }


        /**
         * Java content class for anonymous complex type.
         * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 144)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TRANSMITENTE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}TransmitenteType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface TRANSMITENTESType {


            /**
             * Gets the value of the TRANSMITENTE property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the TRANSMITENTE property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTRANSMITENTE().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType}
             * 
             */
            java.util.List getTRANSMITENTE();

        }

    }


    /**
     * Java content class for anonymous complex type.
     * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 15)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CABECERA" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}CabeceraType"/>
     *         &lt;element name="NOTARIO_TITULAR" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}NotarioType"/>
     *         &lt;element name="NOTARIO_AUTORIZANTE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}NotarioType"/>
     *         &lt;element name="PROTOCOLO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}ProtocoloType"/>
     *         &lt;element name="ACTO_JURIDICO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}ActoJuridicoType"/>
     *         &lt;element name="TRANSMITENTES">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="TRANSMITENTE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}TransmitenteType" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ADQUIRENTES">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ADQUIRENTE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}AdquirenteType" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="INMUEBLE">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="REFERENCIA_CATASTRAL" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}REFERENCIA_CATASTRALType"/>
     *                   &lt;element name="DIRECCION">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="INE_PROVINCIA" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}CODIGO_PROVINCIAType"/>
     *                             &lt;element name="INE_MUNICIPIO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}CODIGO_MUNICIPIOType"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="REPRESENTANTES" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="REPRESENTANTE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}SujetoType" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface REQUESTType {


        /**
         * Operación que origina el impuesto.
         * 
         * @return
         *     possible object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.ActoJuridicoType}
         */
        org.notariado.ancert.xml.plusvalias.liquidacion.ActoJuridicoType getACTOJURIDICO();

        /**
         * Operación que origina el impuesto.
         * 
         * @param value
         *     allowed object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.ActoJuridicoType}
         */
        void setACTOJURIDICO(org.notariado.ancert.xml.plusvalias.liquidacion.ActoJuridicoType value);

        /**
         * Datos del Notario autorizante del documento
         * 
         * @return
         *     possible object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.NotarioType}
         */
        org.notariado.ancert.xml.plusvalias.liquidacion.NotarioType getNOTARIOAUTORIZANTE();

        /**
         * Datos del Notario autorizante del documento
         * 
         * @param value
         *     allowed object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.NotarioType}
         */
        void setNOTARIOAUTORIZANTE(org.notariado.ancert.xml.plusvalias.liquidacion.NotarioType value);

        /**
         * Cada uno de los sujetos que adquieren el inmueble o terreno urbano transmitido.
         * 
         * @return
         *     possible object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.ADQUIRENTESType}
         */
        org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.ADQUIRENTESType getADQUIRENTES();

        /**
         * Cada uno de los sujetos que adquieren el inmueble o terreno urbano transmitido.
         * 
         * @param value
         *     allowed object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.ADQUIRENTESType}
         */
        void setADQUIRENTES(org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.ADQUIRENTESType value);

        /**
         * Datos identificativos del documento notarial.
         * 
         * @return
         *     possible object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.ProtocoloType}
         */
        org.notariado.ancert.xml.plusvalias.liquidacion.ProtocoloType getPROTOCOLO();

        /**
         * Datos identificativos del documento notarial.
         * 
         * @param value
         *     allowed object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.ProtocoloType}
         */
        void setPROTOCOLO(org.notariado.ancert.xml.plusvalias.liquidacion.ProtocoloType value);

        /**
         * Representantes legales.
         * 
         * @return
         *     possible object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.REPRESENTANTESType}
         */
        org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.REPRESENTANTESType getREPRESENTANTES();

        /**
         * Representantes legales.
         * 
         * @param value
         *     allowed object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.REPRESENTANTESType}
         */
        void setREPRESENTANTES(org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.REPRESENTANTESType value);

        /**
         * Objeto transmitido
         * 
         * @return
         *     possible object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.INMUEBLEType}
         */
        org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.INMUEBLEType getINMUEBLE();

        /**
         * Objeto transmitido
         * 
         * @param value
         *     allowed object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.INMUEBLEType}
         */
        void setINMUEBLE(org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.INMUEBLEType value);

        /**
         * Cabecera del mensaje.
         * 
         * @return
         *     possible object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CabeceraType}
         */
        org.notariado.ancert.xml.plusvalias.liquidacion.CabeceraType getCABECERA();

        /**
         * Cabecera del mensaje.
         * 
         * @param value
         *     allowed object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CabeceraType}
         */
        void setCABECERA(org.notariado.ancert.xml.plusvalias.liquidacion.CabeceraType value);

        /**
         * Cada uno de los sujetos que transmiten el inmueble o terreno urbano.
         * 
         * @return
         *     possible object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.TRANSMITENTESType}
         */
        org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.TRANSMITENTESType getTRANSMITENTES();

        /**
         * Cada uno de los sujetos que transmiten el inmueble o terreno urbano.
         * 
         * @param value
         *     allowed object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.TRANSMITENTESType}
         */
        void setTRANSMITENTES(org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.TRANSMITENTESType value);

        /**
         * Datos del Notario titular del documento
         * 
         * @return
         *     possible object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.NotarioType}
         */
        org.notariado.ancert.xml.plusvalias.liquidacion.NotarioType getNOTARIOTITULAR();

        /**
         * Datos del Notario titular del documento
         * 
         * @param value
         *     allowed object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.NotarioType}
         */
        void setNOTARIOTITULAR(org.notariado.ancert.xml.plusvalias.liquidacion.NotarioType value);


        /**
         * Java content class for anonymous complex type.
         * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 56)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ADQUIRENTE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}AdquirenteType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface ADQUIRENTESType {


            /**
             * Gets the value of the ADQUIRENTE property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the ADQUIRENTE property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getADQUIRENTE().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link org.notariado.ancert.xml.plusvalias.liquidacion.AdquirenteType}
             * 
             */
            java.util.List getADQUIRENTE();

        }


        /**
         * Java content class for anonymous complex type.
         * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 66)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="REFERENCIA_CATASTRAL" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}REFERENCIA_CATASTRALType"/>
         *         &lt;element name="DIRECCION">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="INE_PROVINCIA" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}CODIGO_PROVINCIAType"/>
         *                   &lt;element name="INE_MUNICIPIO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}CODIGO_MUNICIPIOType"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface INMUEBLEType {


            /**
             * Gets the value of the direccion property.
             * 
             * @return
             *     possible object is
             *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.INMUEBLEType.DIRECCIONType}
             */
            org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.INMUEBLEType.DIRECCIONType getDIRECCION();

            /**
             * Sets the value of the direccion property.
             * 
             * @param value
             *     allowed object is
             *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.INMUEBLEType.DIRECCIONType}
             */
            void setDIRECCION(org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.INMUEBLEType.DIRECCIONType value);

            /**
             * Referéncia Catastral completa.
             * 
             * @return
             *     possible object is
             *     {@link java.lang.String}
             */
            java.lang.String getREFERENCIACATASTRAL();

            /**
             * Referéncia Catastral completa.
             * 
             * @param value
             *     allowed object is
             *     {@link java.lang.String}
             */
            void setREFERENCIACATASTRAL(java.lang.String value);


            /**
             * Java content class for anonymous complex type.
             * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 74)
             * <p>
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="INE_PROVINCIA" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}CODIGO_PROVINCIAType"/>
             *         &lt;element name="INE_MUNICIPIO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}CODIGO_MUNICIPIOType"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             */
            public interface DIRECCIONType {


                /**
                 * Codigo INE de Provincia
                 * 
                 * @return
                 *     possible object is
                 *     {@link java.lang.String}
                 */
                java.lang.String getINEPROVINCIA();

                /**
                 * Codigo INE de Provincia
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link java.lang.String}
                 */
                void setINEPROVINCIA(java.lang.String value);

                /**
                 * Codigo INE de Municipio. (incluye digito de control)
                 * 
                 * @return
                 *     possible object is
                 *     {@link java.lang.String}
                 */
                java.lang.String getINEMUNICIPIO();

                /**
                 * Codigo INE de Municipio. (incluye digito de control)
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link java.lang.String}
                 */
                void setINEMUNICIPIO(java.lang.String value);

            }

        }


        /**
         * Java content class for anonymous complex type.
         * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 96)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="REPRESENTANTE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}SujetoType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface REPRESENTANTESType {


            /**
             * Gets the value of the REPRESENTANTE property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the REPRESENTANTE property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getREPRESENTANTE().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link org.notariado.ancert.xml.plusvalias.liquidacion.SujetoType}
             * 
             */
            java.util.List getREPRESENTANTE();

        }


        /**
         * Java content class for anonymous complex type.
         * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 46)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="TRANSMITENTE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}TransmitenteType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface TRANSMITENTESType {


            /**
             * Gets the value of the TRANSMITENTE property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the TRANSMITENTE property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTRANSMITENTE().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType}
             * 
             */
            java.util.List getTRANSMITENTE();

        }

    }

}
