//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v@@BUILD_VERSION@@ 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2011.07.04 en 12:38:50 CEST 
//


package org.notariado.ancert.xml.plusvalias.liquidacion;


/**
 * Java content class for anonymous complex type.
 * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 659)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="REQUEST">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="CABECERA" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}CabeceraType"/>
 *                     &lt;element name="INE_MUNICIPIO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}CODIGO_MUNICIPIOType"/>
 *                     &lt;element name="INE_PROVINCIA" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}CODIGO_PROVINCIAType"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="REPLY">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="CABECERA" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}CabeceraType"/>
 *                     &lt;sequence minOccurs="0">
 *                       &lt;element name="BONIFICACIONES" minOccurs="0">
 *                         &lt;complexType>
 *                           &lt;complexContent>
 *                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                               &lt;sequence>
 *                                 &lt;element name="BONIFICACION" maxOccurs="unbounded">
 *                                   &lt;complexType>
 *                                     &lt;complexContent>
 *                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                         &lt;sequence>
 *                                           &lt;element name="PORCENTAJE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}PORCENTAJEType"/>
 *                                           &lt;element name="CONCEPTO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                           &lt;element name="DESCRIPCION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                         &lt;/sequence>
 *                                       &lt;/restriction>
 *                                     &lt;/complexContent>
 *                                   &lt;/complexType>
 *                                 &lt;/element>
 *                               &lt;/sequence>
 *                             &lt;/restriction>
 *                           &lt;/complexContent>
 *                         &lt;/complexType>
 *                       &lt;/element>
 *                       &lt;element name="EXENCIONES" minOccurs="0">
 *                         &lt;complexType>
 *                           &lt;complexContent>
 *                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                               &lt;sequence>
 *                                 &lt;element name="EXENCION" maxOccurs="unbounded">
 *                                   &lt;complexType>
 *                                     &lt;complexContent>
 *                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                         &lt;sequence>
 *                                           &lt;element name="PORCENTAJE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}PORCENTAJEType"/>
 *                                           &lt;element name="CONCEPTO" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                           &lt;element name="DESCRIPCION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                         &lt;/sequence>
 *                                       &lt;/restriction>
 *                                     &lt;/complexContent>
 *                                   &lt;/complexType>
 *                                 &lt;/element>
 *                               &lt;/sequence>
 *                             &lt;/restriction>
 *                           &lt;/complexContent>
 *                         &lt;/complexType>
 *                       &lt;/element>
 *                     &lt;/sequence>
 *                     &lt;element name="RESULTADO">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element name="RETORNO" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                               &lt;element name="ERROR" minOccurs="0">
 *                                 &lt;complexType>
 *                                   &lt;complexContent>
 *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                       &lt;sequence>
 *                                         &lt;element name="CODIGO">
 *                                           &lt;restriction base="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}STRINGType">
 *                                             &lt;length value="4"/>
 *                                           &lt;/restriction>
 *                                         &lt;/element>
 *                                         &lt;element name="DESCRIPCION">
 *                                           &lt;restriction base="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}STRINGType">
 *                                             &lt;minLength value="1"/>
 *                                             &lt;maxLength value="255"/>
 *                                           &lt;/restriction>
 *                                         &lt;/element>
 *                                       &lt;/sequence>
 *                                     &lt;/restriction>
 *                                   &lt;/complexContent>
 *                                 &lt;/complexType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface EXENCIONESBONIFICACIONESType {


    /**
     * Respuesta con las bonificaciones y exenciones enviado por el organismo de gestión tributaria.
     * 
     * @return
     *     possible object is
     *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType}
     */
    org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType getREPLY();

    /**
     * Respuesta con las bonificaciones y exenciones enviado por el organismo de gestión tributaria.
     * 
     * @param value
     *     allowed object is
     *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType}
     */
    void setREPLY(org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType value);

    /**
     * Interrogación de bonificaciones y exenciones enviado desde el CGN
     * 
     * @return
     *     possible object is
     *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REQUESTType}
     */
    org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REQUESTType getREQUEST();

    /**
     * Interrogación de bonificaciones y exenciones enviado desde el CGN
     * 
     * @param value
     *     allowed object is
     *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REQUESTType}
     */
    void setREQUEST(org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REQUESTType value);


    /**
     * Java content class for anonymous complex type.
     * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 682)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CABECERA" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}CabeceraType"/>
     *         &lt;sequence minOccurs="0">
     *           &lt;element name="BONIFICACIONES" minOccurs="0">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element name="BONIFICACION" maxOccurs="unbounded">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;sequence>
     *                               &lt;element name="PORCENTAJE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}PORCENTAJEType"/>
     *                               &lt;element name="CONCEPTO" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                               &lt;element name="DESCRIPCION" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;/sequence>
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                   &lt;/sequence>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *           &lt;element name="EXENCIONES" minOccurs="0">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;sequence>
     *                     &lt;element name="EXENCION" maxOccurs="unbounded">
     *                       &lt;complexType>
     *                         &lt;complexContent>
     *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                             &lt;sequence>
     *                               &lt;element name="PORCENTAJE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}PORCENTAJEType"/>
     *                               &lt;element name="CONCEPTO" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                               &lt;element name="DESCRIPCION" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;/sequence>
     *                           &lt;/restriction>
     *                         &lt;/complexContent>
     *                       &lt;/complexType>
     *                     &lt;/element>
     *                   &lt;/sequence>
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *         &lt;/sequence>
     *         &lt;element name="RESULTADO">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RETORNO" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="ERROR" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="CODIGO">
     *                               &lt;restriction base="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}STRINGType">
     *                                 &lt;length value="4"/>
     *                               &lt;/restriction>
     *                             &lt;/element>
     *                             &lt;element name="DESCRIPCION">
     *                               &lt;restriction base="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}STRINGType">
     *                                 &lt;minLength value="1"/>
     *                                 &lt;maxLength value="255"/>
     *                               &lt;/restriction>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface REPLYType {


        /**
         * Gets the value of the bonificaciones property.
         * 
         * @return
         *     possible object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.BONIFICACIONESType}
         */
        org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.BONIFICACIONESType getBONIFICACIONES();

        /**
         * Sets the value of the bonificaciones property.
         * 
         * @param value
         *     allowed object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.BONIFICACIONESType}
         */
        void setBONIFICACIONES(org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.BONIFICACIONESType value);

        /**
         * Gets the value of the exenciones property.
         * 
         * @return
         *     possible object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.EXENCIONESType}
         */
        org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.EXENCIONESType getEXENCIONES();

        /**
         * Sets the value of the exenciones property.
         * 
         * @param value
         *     allowed object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.EXENCIONESType}
         */
        void setEXENCIONES(org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.EXENCIONESType value);

        /**
         * Resultado de la petición . Los datos del cálculo no seran obligatorios si el retorno es distinto de cero.
         * 
         * @return
         *     possible object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.RESULTADOType}
         */
        org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.RESULTADOType getRESULTADO();

        /**
         * Resultado de la petición . Los datos del cálculo no seran obligatorios si el retorno es distinto de cero.
         * 
         * @param value
         *     allowed object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.RESULTADOType}
         */
        void setRESULTADO(org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.RESULTADOType value);

        /**
         * Cabecera del mensaje.
         * 
         * @return
         *     possible object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CabeceraType}
         */
        org.notariado.ancert.xml.plusvalias.liquidacion.CabeceraType getCABECERA();

        /**
         * Cabecera del mensaje.
         * 
         * @param value
         *     allowed object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CabeceraType}
         */
        void setCABECERA(org.notariado.ancert.xml.plusvalias.liquidacion.CabeceraType value);


        /**
         * Java content class for anonymous complex type.
         * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 691)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="BONIFICACION" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="PORCENTAJE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}PORCENTAJEType"/>
         *                   &lt;element name="CONCEPTO" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="DESCRIPCION" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface BONIFICACIONESType {


            /**
             * Gets the value of the BONIFICACION property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the BONIFICACION property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getBONIFICACION().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.BONIFICACIONESType.BONIFICACIONType}
             * 
             */
            java.util.List getBONIFICACION();


            /**
             * Java content class for anonymous complex type.
             * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 694)
             * <p>
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="PORCENTAJE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}PORCENTAJEType"/>
             *         &lt;element name="CONCEPTO" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="DESCRIPCION" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             */
            public interface BONIFICACIONType {


                /**
                 * Gets the value of the descripcion property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link java.lang.String}
                 */
                java.lang.String getDESCRIPCION();

                /**
                 * Sets the value of the descripcion property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link java.lang.String}
                 */
                void setDESCRIPCION(java.lang.String value);

                /**
                 * Gets the value of the porcentaje property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link java.lang.String}
                 */
                java.lang.String getPORCENTAJE();

                /**
                 * Sets the value of the porcentaje property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link java.lang.String}
                 */
                void setPORCENTAJE(java.lang.String value);

                /**
                 * Gets the value of the concepto property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link java.lang.String}
                 */
                java.lang.String getCONCEPTO();

                /**
                 * Sets the value of the concepto property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link java.lang.String}
                 */
                void setCONCEPTO(java.lang.String value);

            }

        }


        /**
         * Java content class for anonymous complex type.
         * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 706)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="EXENCION" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="PORCENTAJE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}PORCENTAJEType"/>
         *                   &lt;element name="CONCEPTO" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="DESCRIPCION" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface EXENCIONESType {


            /**
             * Gets the value of the EXENCION property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the EXENCION property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getEXENCION().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.EXENCIONESType.EXENCIONType}
             * 
             */
            java.util.List getEXENCION();


            /**
             * Java content class for anonymous complex type.
             * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 709)
             * <p>
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="PORCENTAJE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}PORCENTAJEType"/>
             *         &lt;element name="CONCEPTO" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="DESCRIPCION" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             */
            public interface EXENCIONType {


                /**
                 * Gets the value of the descripcion property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link java.lang.String}
                 */
                java.lang.String getDESCRIPCION();

                /**
                 * Sets the value of the descripcion property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link java.lang.String}
                 */
                void setDESCRIPCION(java.lang.String value);

                /**
                 * Gets the value of the porcentaje property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link java.lang.String}
                 */
                java.lang.String getPORCENTAJE();

                /**
                 * Sets the value of the porcentaje property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link java.lang.String}
                 */
                void setPORCENTAJE(java.lang.String value);

                /**
                 * Gets the value of the concepto property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link java.lang.String}
                 */
                java.lang.String getCONCEPTO();

                /**
                 * Sets the value of the concepto property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link java.lang.String}
                 */
                void setCONCEPTO(java.lang.String value);

            }

        }


        /**
         * Java content class for anonymous complex type.
         * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 725)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RETORNO" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="ERROR" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="CODIGO">
         *                     &lt;restriction base="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}STRINGType">
         *                       &lt;length value="4"/>
         *                     &lt;/restriction>
         *                   &lt;/element>
         *                   &lt;element name="DESCRIPCION">
         *                     &lt;restriction base="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}STRINGType">
         *                       &lt;minLength value="1"/>
         *                       &lt;maxLength value="255"/>
         *                     &lt;/restriction>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface RESULTADOType {


            /**
             * Se indicará 0 si la operación ha sido completada correctamente. En caso contrario se indicará 1.
             * 
             */
            boolean isRETORNO();

            /**
             * Se indicará 0 si la operación ha sido completada correctamente. En caso contrario se indicará 1.
             * 
             */
            void setRETORNO(boolean value);

            /**
             * En caso de error se indicará el código y la descripción.
             * 
             * @return
             *     possible object is
             *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.RESULTADOType.ERRORType}
             */
            org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.RESULTADOType.ERRORType getERROR();

            /**
             * En caso de error se indicará el código y la descripción.
             * 
             * @param value
             *     allowed object is
             *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.RESULTADOType.ERRORType}
             */
            void setERROR(org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.RESULTADOType.ERRORType value);


            /**
             * Java content class for anonymous complex type.
             * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 736)
             * <p>
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="CODIGO">
             *           &lt;restriction base="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}STRINGType">
             *             &lt;length value="4"/>
             *           &lt;/restriction>
             *         &lt;/element>
             *         &lt;element name="DESCRIPCION">
             *           &lt;restriction base="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}STRINGType">
             *             &lt;minLength value="1"/>
             *             &lt;maxLength value="255"/>
             *           &lt;/restriction>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             */
            public interface ERRORType {


                /**
                 * Descripción del error.
                 * 
                 * @return
                 *     possible object is
                 *     {@link java.lang.String}
                 */
                java.lang.String getDESCRIPCION();

                /**
                 * Descripción del error.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link java.lang.String}
                 */
                void setDESCRIPCION(java.lang.String value);

                /**
                 * Código del error pactado entre el organismo de gestión tributaria y el CGN.
                 * 
                 * @return
                 *     possible object is
                 *     {@link java.lang.String}
                 */
                java.lang.String getCODIGO();

                /**
                 * Código del error pactado entre el organismo de gestión tributaria y el CGN.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link java.lang.String}
                 */
                void setCODIGO(java.lang.String value);

            }

        }

    }


    /**
     * Java content class for anonymous complex type.
     * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 666)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CABECERA" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}CabeceraType"/>
     *         &lt;element name="INE_MUNICIPIO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}CODIGO_MUNICIPIOType"/>
     *         &lt;element name="INE_PROVINCIA" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}CODIGO_PROVINCIAType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface REQUESTType {


        /**
         * Cabecera del mensaje.
         * 
         * @return
         *     possible object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CabeceraType}
         */
        org.notariado.ancert.xml.plusvalias.liquidacion.CabeceraType getCABECERA();

        /**
         * Cabecera del mensaje.
         * 
         * @param value
         *     allowed object is
         *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.CabeceraType}
         */
        void setCABECERA(org.notariado.ancert.xml.plusvalias.liquidacion.CabeceraType value);

        /**
         * Gets the value of the ineprovincia property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getINEPROVINCIA();

        /**
         * Sets the value of the ineprovincia property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setINEPROVINCIA(java.lang.String value);

        /**
         * Gets the value of the inemunicipio property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getINEMUNICIPIO();

        /**
         * Sets the value of the inemunicipio property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setINEMUNICIPIO(java.lang.String value);

    }

}
