//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v@@BUILD_VERSION@@ 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2011.07.04 en 12:38:50 CEST 
//


package org.notariado.ancert.xml.plusvalias.liquidacion;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.notariado.ancert.xml.plusvalias.liquidacion package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class ObjectFactory
    extends org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap(95, 0.75F);
    private static java.util.HashMap rootTagMap = new java.util.HashMap();
    public final static org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.GrammarInfo grammarInfo = new org.notariado.ancert.xml.plusvalias.liquidacion.impl.runtime.GrammarInfoImpl(rootTagMap, defaultImplementations, (org.notariado.ancert.xml.plusvalias.liquidacion.ObjectFactory.class));
    public final static java.lang.Class version = (org.notariado.ancert.xml.plusvalias.liquidacion.impl.JAXBVersion.class);

    static {
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.ORDENPAGOType.PARAMETROSPAGOType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.ORDENPAGOTypeImpl.PARAMETROSPAGOTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REQUESTType.REPRESENTANTESType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REQUESTTypeImpl.REPRESENTANTESTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REQUESTType.TRANSMITENTESType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REQUESTTypeImpl.TRANSMITENTESTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REPLYType.REPRESENTANTESType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REPLYTypeImpl.REPRESENTANTESTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REPLYTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.TRANSMITENTESType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REQUESTTypeImpl.TRANSMITENTESTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REPLYType.DOCUMENTOSType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REPLYTypeImpl.DOCUMENTOSTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.RESULTADOType.ERRORType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REPLYTypeImpl.RESULTADOTypeImpl.ERRORTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.DOCUMENTOSType.DOCUMENTOType.IMPORTEType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REPLYTypeImpl.DOCUMENTOSTypeImpl.DOCUMENTOTypeImpl.IMPORTETypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.NotarioType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.NotarioTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REPLYType.INMUEBLEType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REPLYTypeImpl.INMUEBLETypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.REPRESENTANTESType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.TransmitenteTypeImpl.REPRESENTANTESTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.BONIFICACIONESType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.EXENCIONESBONIFICACIONESTypeImpl.REPLYTypeImpl.BONIFICACIONESTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.EXENCIONESBONIFICACIONESTypeImpl.REPLYTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.ActoJuridicoType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.ActoJuridicoTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.DireccionExtranjeraType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.DireccionExtranjeraTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.EXENCIONESBONIFICACIONESTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.ADQUIRENTESType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REQUESTTypeImpl.ADQUIRENTESTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.AdquirenteType.REPRESENTANTESType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.AdquirenteTypeImpl.REPRESENTANTESTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACION.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.SujetoType.DATOSPERSONALESType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.SujetoTypeImpl.DATOSPERSONALESTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.BONIFICACIONESType.BONIFICACIONType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.EXENCIONESBONIFICACIONESTypeImpl.REPLYTypeImpl.BONIFICACIONESTypeImpl.BONIFICACIONTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.RESULTADOType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REPLYTypeImpl.RESULTADOTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REQUESTType.INMUEBLEType.DIRECCIONType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REQUESTTypeImpl.INMUEBLETypeImpl.DIRECCIONTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REPLYType.DOCUMENTOSType.DOCUMENTOType.IMPORTEType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REPLYTypeImpl.DOCUMENTOSTypeImpl.DOCUMENTOTypeImpl.IMPORTETypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.SujetoType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.SujetoTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REPLYType.DOCUMENTOSType.DOCUMENTOType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REPLYTypeImpl.DOCUMENTOSTypeImpl.DOCUMENTOTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REPLYType.TRANSMITENTESType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REPLYTypeImpl.TRANSMITENTESTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.INMUEBLEType.DIRECCIONType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REQUESTTypeImpl.INMUEBLETypeImpl.DIRECCIONTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.ORDENPAGOType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.ORDENPAGOTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.DOCUMENTOSType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REPLYTypeImpl.DOCUMENTOSTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.INMUEBLEType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REPLYTypeImpl.INMUEBLETypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.RESULTADOType.ERRORType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.EXENCIONESBONIFICACIONESTypeImpl.REPLYTypeImpl.RESULTADOTypeImpl.ERRORTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.AdquirenteType.PRORROGASOLICITADAType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.AdquirenteTypeImpl.PRORROGASOLICITADATypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.EXENCIONESType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.TransmitenteTypeImpl.EXENCIONESTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.TRANSMISIONESANTERIORESType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.TransmitenteTypeImpl.TRANSMISIONESANTERIORESTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.ORDENPAGOType.PARAMETROSPAGOType.IMPORTESType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.ORDENPAGOTypeImpl.PARAMETROSPAGOTypeImpl.IMPORTESTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REQUESTType.ADQUIRENTESType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REQUESTTypeImpl.ADQUIRENTESTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.ORDENPAGOType.PARAMETROSPAGOType.DATOSBANCARIOSType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.ORDENPAGOTypeImpl.PARAMETROSPAGOTypeImpl.DATOSBANCARIOSTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.ADQUIRENTESType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REPLYTypeImpl.ADQUIRENTESTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.DireccionType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.DireccionTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.CabeceraType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.CabeceraTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.EXENCIONESType.EXENCIONType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.EXENCIONESBONIFICACIONESTypeImpl.REPLYTypeImpl.EXENCIONESTypeImpl.EXENCIONTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.DOCUMENTOSType.DOCUMENTOType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REPLYTypeImpl.DOCUMENTOSTypeImpl.DOCUMENTOTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REPLYType.RESULTADOType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REPLYTypeImpl.RESULTADOTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.TransmitenteTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REQUESTType.ESCRITURAType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REQUESTTypeImpl.ESCRITURATypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REPLYType.RESULTADOType.ERRORType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REPLYTypeImpl.RESULTADOTypeImpl.ERRORTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.TRANSMISIONESANTERIORESType.TRANSMISIONType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.TransmitenteTypeImpl.TRANSMISIONESANTERIORESTypeImpl.TRANSMISIONTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REQUESTType.INMUEBLEType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REQUESTTypeImpl.INMUEBLETypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACION.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REQUESTTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.INMUEBLEType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REQUESTTypeImpl.INMUEBLETypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REPLYType.ADQUIRENTESType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REPLYTypeImpl.ADQUIRENTESTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.REPRESENTANTESType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REPLYTypeImpl.REPRESENTANTESTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.REPRESENTANTESType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REQUESTTypeImpl.REPRESENTANTESTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REPLYType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REPLYTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.AdquirenteType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.AdquirenteTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REQUESTType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REQUESTTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.EXENCIONESType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.EXENCIONESBONIFICACIONESTypeImpl.REPLYTypeImpl.EXENCIONESTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REQUESTType.PAGOType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REQUESTTypeImpl.PAGOTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.ProtocoloType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.ProtocoloTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.BONIFICACIONESType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.TransmitenteTypeImpl.BONIFICACIONESTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.DireccionInmuebleType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.DireccionInmuebleTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.RESULTADOType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.EXENCIONESBONIFICACIONESTypeImpl.REPLYTypeImpl.RESULTADOTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.TRANSMITENTESType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REPLYTypeImpl.TRANSMITENTESTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REQUESTType.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.EXENCIONESBONIFICACIONESTypeImpl.REQUESTTypeImpl");
        defaultImplementations.put((org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONES.class), "org.notariado.ancert.xml.plusvalias.liquidacion.impl.EXENCIONESBONIFICACIONESImpl");
        rootTagMap.put(new javax.xml.namespace.QName("http://ancert.notariado.org/XML/Plusvalias/Liquidacion", "EXENCIONES_BONIFICACIONES"), (org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONES.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://ancert.notariado.org/XML/Plusvalias/Liquidacion", "CALCULO_LIQUIDACION"), (org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACION.class));
        rootTagMap.put(new javax.xml.namespace.QName("http://ancert.notariado.org/XML/Plusvalias/Liquidacion", "PAGO_LIQUIDACION"), (org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACION.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.notariado.ancert.xml.plusvalias.liquidacion
     * 
     */
    public ObjectFactory() {
        super(grammarInfo);
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface
     *     the Class object of the javacontent interface to instantiate
     * @return
     *     a new instance
     * @throws JAXBException
     *     if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @return
     *     the value of the requested property
     * @throws PropertyException
     *     when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param value
     *     the value of the property to be set
     * @param name
     *     the name of the property to retrieve
     * @throws PropertyException
     *     when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of ORDENPAGOTypePARAMETROSPAGOType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.ORDENPAGOType.PARAMETROSPAGOType createORDENPAGOTypePARAMETROSPAGOType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.ORDENPAGOTypeImpl.PARAMETROSPAGOTypeImpl();
    }

    /**
     * Create an instance of PAGOLIQUIDACIONTypeREQUESTTypeREPRESENTANTESType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REQUESTType.REPRESENTANTESType createPAGOLIQUIDACIONTypeREQUESTTypeREPRESENTANTESType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REQUESTTypeImpl.REPRESENTANTESTypeImpl();
    }

    /**
     * Create an instance of PAGOLIQUIDACIONTypeREQUESTTypeTRANSMITENTESType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REQUESTType.TRANSMITENTESType createPAGOLIQUIDACIONTypeREQUESTTypeTRANSMITENTESType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REQUESTTypeImpl.TRANSMITENTESTypeImpl();
    }

    /**
     * Create an instance of PAGOLIQUIDACIONTypeREPLYTypeREPRESENTANTESType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REPLYType.REPRESENTANTESType createPAGOLIQUIDACIONTypeREPLYTypeREPRESENTANTESType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REPLYTypeImpl.REPRESENTANTESTypeImpl();
    }

    /**
     * Create an instance of CALCULOLIQUIDACIONTypeREPLYType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType createCALCULOLIQUIDACIONTypeREPLYType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REPLYTypeImpl();
    }

    /**
     * Create an instance of CALCULOLIQUIDACIONTypeREQUESTTypeTRANSMITENTESType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.TRANSMITENTESType createCALCULOLIQUIDACIONTypeREQUESTTypeTRANSMITENTESType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REQUESTTypeImpl.TRANSMITENTESTypeImpl();
    }

    /**
     * Create an instance of PAGOLIQUIDACIONTypeREPLYTypeDOCUMENTOSType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REPLYType.DOCUMENTOSType createPAGOLIQUIDACIONTypeREPLYTypeDOCUMENTOSType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REPLYTypeImpl.DOCUMENTOSTypeImpl();
    }

    /**
     * Create an instance of CALCULOLIQUIDACIONTypeREPLYTypeRESULTADOTypeERRORType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.RESULTADOType.ERRORType createCALCULOLIQUIDACIONTypeREPLYTypeRESULTADOTypeERRORType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REPLYTypeImpl.RESULTADOTypeImpl.ERRORTypeImpl();
    }

    /**
     * Create an instance of CALCULOLIQUIDACIONTypeREPLYTypeDOCUMENTOSTypeDOCUMENTOTypeIMPORTEType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.DOCUMENTOSType.DOCUMENTOType.IMPORTEType createCALCULOLIQUIDACIONTypeREPLYTypeDOCUMENTOSTypeDOCUMENTOTypeIMPORTEType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REPLYTypeImpl.DOCUMENTOSTypeImpl.DOCUMENTOTypeImpl.IMPORTETypeImpl();
    }

    /**
     * Create an instance of NotarioType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.NotarioType createNotarioType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.NotarioTypeImpl();
    }

    /**
     * Create an instance of CALCULOLIQUIDACIONType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType createCALCULOLIQUIDACIONType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl();
    }

    /**
     * Create an instance of PAGOLIQUIDACIONTypeREPLYTypeINMUEBLEType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REPLYType.INMUEBLEType createPAGOLIQUIDACIONTypeREPLYTypeINMUEBLEType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REPLYTypeImpl.INMUEBLETypeImpl();
    }

    /**
     * Create an instance of TransmitenteTypeREPRESENTANTESType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.REPRESENTANTESType createTransmitenteTypeREPRESENTANTESType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.TransmitenteTypeImpl.REPRESENTANTESTypeImpl();
    }

    /**
     * Create an instance of EXENCIONESBONIFICACIONESTypeREPLYTypeBONIFICACIONESType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.BONIFICACIONESType createEXENCIONESBONIFICACIONESTypeREPLYTypeBONIFICACIONESType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.EXENCIONESBONIFICACIONESTypeImpl.REPLYTypeImpl.BONIFICACIONESTypeImpl();
    }

    /**
     * Create an instance of EXENCIONESBONIFICACIONESTypeREPLYType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType createEXENCIONESBONIFICACIONESTypeREPLYType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.EXENCIONESBONIFICACIONESTypeImpl.REPLYTypeImpl();
    }

    /**
     * Create an instance of ActoJuridicoType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.ActoJuridicoType createActoJuridicoType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.ActoJuridicoTypeImpl();
    }

    /**
     * Create an instance of DireccionExtranjeraType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.DireccionExtranjeraType createDireccionExtranjeraType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.DireccionExtranjeraTypeImpl();
    }

    /**
     * Create an instance of EXENCIONESBONIFICACIONESType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType createEXENCIONESBONIFICACIONESType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.EXENCIONESBONIFICACIONESTypeImpl();
    }

    /**
     * Create an instance of CALCULOLIQUIDACIONTypeREQUESTTypeADQUIRENTESType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.ADQUIRENTESType createCALCULOLIQUIDACIONTypeREQUESTTypeADQUIRENTESType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REQUESTTypeImpl.ADQUIRENTESTypeImpl();
    }

    /**
     * Create an instance of AdquirenteTypeREPRESENTANTESType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.AdquirenteType.REPRESENTANTESType createAdquirenteTypeREPRESENTANTESType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.AdquirenteTypeImpl.REPRESENTANTESTypeImpl();
    }

    /**
     * Create an instance of CALCULOLIQUIDACION
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACION createCALCULOLIQUIDACION()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONImpl();
    }

    /**
     * Create an instance of SujetoTypeDATOSPERSONALESType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.SujetoType.DATOSPERSONALESType createSujetoTypeDATOSPERSONALESType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.SujetoTypeImpl.DATOSPERSONALESTypeImpl();
    }

    /**
     * Create an instance of EXENCIONESBONIFICACIONESTypeREPLYTypeBONIFICACIONESTypeBONIFICACIONType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.BONIFICACIONESType.BONIFICACIONType createEXENCIONESBONIFICACIONESTypeREPLYTypeBONIFICACIONESTypeBONIFICACIONType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.EXENCIONESBONIFICACIONESTypeImpl.REPLYTypeImpl.BONIFICACIONESTypeImpl.BONIFICACIONTypeImpl();
    }

    /**
     * Create an instance of CALCULOLIQUIDACIONTypeREPLYTypeRESULTADOType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.RESULTADOType createCALCULOLIQUIDACIONTypeREPLYTypeRESULTADOType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REPLYTypeImpl.RESULTADOTypeImpl();
    }

    /**
     * Create an instance of PAGOLIQUIDACIONTypeREQUESTTypeINMUEBLETypeDIRECCIONType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REQUESTType.INMUEBLEType.DIRECCIONType createPAGOLIQUIDACIONTypeREQUESTTypeINMUEBLETypeDIRECCIONType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REQUESTTypeImpl.INMUEBLETypeImpl.DIRECCIONTypeImpl();
    }

    /**
     * Create an instance of PAGOLIQUIDACIONTypeREPLYTypeDOCUMENTOSTypeDOCUMENTOTypeIMPORTEType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REPLYType.DOCUMENTOSType.DOCUMENTOType.IMPORTEType createPAGOLIQUIDACIONTypeREPLYTypeDOCUMENTOSTypeDOCUMENTOTypeIMPORTEType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REPLYTypeImpl.DOCUMENTOSTypeImpl.DOCUMENTOTypeImpl.IMPORTETypeImpl();
    }

    /**
     * Create an instance of SujetoType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.SujetoType createSujetoType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.SujetoTypeImpl();
    }

    /**
     * Create an instance of PAGOLIQUIDACIONTypeREPLYTypeDOCUMENTOSTypeDOCUMENTOType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REPLYType.DOCUMENTOSType.DOCUMENTOType createPAGOLIQUIDACIONTypeREPLYTypeDOCUMENTOSTypeDOCUMENTOType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REPLYTypeImpl.DOCUMENTOSTypeImpl.DOCUMENTOTypeImpl();
    }

    /**
     * Create an instance of PAGOLIQUIDACIONTypeREPLYTypeTRANSMITENTESType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REPLYType.TRANSMITENTESType createPAGOLIQUIDACIONTypeREPLYTypeTRANSMITENTESType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REPLYTypeImpl.TRANSMITENTESTypeImpl();
    }

    /**
     * Create an instance of CALCULOLIQUIDACIONTypeREQUESTTypeINMUEBLETypeDIRECCIONType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.INMUEBLEType.DIRECCIONType createCALCULOLIQUIDACIONTypeREQUESTTypeINMUEBLETypeDIRECCIONType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REQUESTTypeImpl.INMUEBLETypeImpl.DIRECCIONTypeImpl();
    }

    /**
     * Create an instance of ORDENPAGOType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.ORDENPAGOType createORDENPAGOType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.ORDENPAGOTypeImpl();
    }

    /**
     * Create an instance of CALCULOLIQUIDACIONTypeREPLYTypeDOCUMENTOSType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.DOCUMENTOSType createCALCULOLIQUIDACIONTypeREPLYTypeDOCUMENTOSType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REPLYTypeImpl.DOCUMENTOSTypeImpl();
    }

    /**
     * Create an instance of CALCULOLIQUIDACIONTypeREPLYTypeINMUEBLEType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.INMUEBLEType createCALCULOLIQUIDACIONTypeREPLYTypeINMUEBLEType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REPLYTypeImpl.INMUEBLETypeImpl();
    }

    /**
     * Create an instance of EXENCIONESBONIFICACIONESTypeREPLYTypeRESULTADOTypeERRORType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.RESULTADOType.ERRORType createEXENCIONESBONIFICACIONESTypeREPLYTypeRESULTADOTypeERRORType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.EXENCIONESBONIFICACIONESTypeImpl.REPLYTypeImpl.RESULTADOTypeImpl.ERRORTypeImpl();
    }

    /**
     * Create an instance of AdquirenteTypePRORROGASOLICITADAType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.AdquirenteType.PRORROGASOLICITADAType createAdquirenteTypePRORROGASOLICITADAType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.AdquirenteTypeImpl.PRORROGASOLICITADATypeImpl();
    }

    /**
     * Create an instance of TransmitenteTypeEXENCIONESType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.EXENCIONESType createTransmitenteTypeEXENCIONESType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.TransmitenteTypeImpl.EXENCIONESTypeImpl();
    }

    /**
     * Create an instance of TransmitenteTypeTRANSMISIONESANTERIORESType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.TRANSMISIONESANTERIORESType createTransmitenteTypeTRANSMISIONESANTERIORESType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.TransmitenteTypeImpl.TRANSMISIONESANTERIORESTypeImpl();
    }

    /**
     * Create an instance of ORDENPAGOTypePARAMETROSPAGOTypeIMPORTESType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.ORDENPAGOType.PARAMETROSPAGOType.IMPORTESType createORDENPAGOTypePARAMETROSPAGOTypeIMPORTESType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.ORDENPAGOTypeImpl.PARAMETROSPAGOTypeImpl.IMPORTESTypeImpl();
    }

    /**
     * Create an instance of PAGOLIQUIDACIONTypeREQUESTTypeADQUIRENTESType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REQUESTType.ADQUIRENTESType createPAGOLIQUIDACIONTypeREQUESTTypeADQUIRENTESType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REQUESTTypeImpl.ADQUIRENTESTypeImpl();
    }

    /**
     * Create an instance of ORDENPAGOTypePARAMETROSPAGOTypeDATOSBANCARIOSType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.ORDENPAGOType.PARAMETROSPAGOType.DATOSBANCARIOSType createORDENPAGOTypePARAMETROSPAGOTypeDATOSBANCARIOSType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.ORDENPAGOTypeImpl.PARAMETROSPAGOTypeImpl.DATOSBANCARIOSTypeImpl();
    }

    /**
     * Create an instance of CALCULOLIQUIDACIONTypeREPLYTypeADQUIRENTESType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.ADQUIRENTESType createCALCULOLIQUIDACIONTypeREPLYTypeADQUIRENTESType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REPLYTypeImpl.ADQUIRENTESTypeImpl();
    }

    /**
     * Create an instance of DireccionType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.DireccionType createDireccionType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.DireccionTypeImpl();
    }

    /**
     * Create an instance of CabeceraType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.CabeceraType createCabeceraType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.CabeceraTypeImpl();
    }

    /**
     * Create an instance of EXENCIONESBONIFICACIONESTypeREPLYTypeEXENCIONESTypeEXENCIONType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.EXENCIONESType.EXENCIONType createEXENCIONESBONIFICACIONESTypeREPLYTypeEXENCIONESTypeEXENCIONType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.EXENCIONESBONIFICACIONESTypeImpl.REPLYTypeImpl.EXENCIONESTypeImpl.EXENCIONTypeImpl();
    }

    /**
     * Create an instance of CALCULOLIQUIDACIONTypeREPLYTypeDOCUMENTOSTypeDOCUMENTOType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.DOCUMENTOSType.DOCUMENTOType createCALCULOLIQUIDACIONTypeREPLYTypeDOCUMENTOSTypeDOCUMENTOType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REPLYTypeImpl.DOCUMENTOSTypeImpl.DOCUMENTOTypeImpl();
    }

    /**
     * Create an instance of PAGOLIQUIDACIONType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType createPAGOLIQUIDACIONType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl();
    }

    /**
     * Create an instance of PAGOLIQUIDACIONTypeREPLYTypeRESULTADOType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REPLYType.RESULTADOType createPAGOLIQUIDACIONTypeREPLYTypeRESULTADOType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REPLYTypeImpl.RESULTADOTypeImpl();
    }

    /**
     * Create an instance of TransmitenteType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType createTransmitenteType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.TransmitenteTypeImpl();
    }

    /**
     * Create an instance of PAGOLIQUIDACIONTypeREQUESTTypeESCRITURAType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REQUESTType.ESCRITURAType createPAGOLIQUIDACIONTypeREQUESTTypeESCRITURAType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REQUESTTypeImpl.ESCRITURATypeImpl();
    }

    /**
     * Create an instance of PAGOLIQUIDACIONTypeREPLYTypeRESULTADOTypeERRORType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REPLYType.RESULTADOType.ERRORType createPAGOLIQUIDACIONTypeREPLYTypeRESULTADOTypeERRORType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REPLYTypeImpl.RESULTADOTypeImpl.ERRORTypeImpl();
    }

    /**
     * Create an instance of TransmitenteTypeTRANSMISIONESANTERIORESTypeTRANSMISIONType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.TRANSMISIONESANTERIORESType.TRANSMISIONType createTransmitenteTypeTRANSMISIONESANTERIORESTypeTRANSMISIONType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.TransmitenteTypeImpl.TRANSMISIONESANTERIORESTypeImpl.TRANSMISIONTypeImpl();
    }

    /**
     * Create an instance of PAGOLIQUIDACIONTypeREQUESTTypeINMUEBLEType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REQUESTType.INMUEBLEType createPAGOLIQUIDACIONTypeREQUESTTypeINMUEBLEType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REQUESTTypeImpl.INMUEBLETypeImpl();
    }

    /**
     * Create an instance of PAGOLIQUIDACION
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACION createPAGOLIQUIDACION()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONImpl();
    }

    /**
     * Create an instance of CALCULOLIQUIDACIONTypeREQUESTType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType createCALCULOLIQUIDACIONTypeREQUESTType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REQUESTTypeImpl();
    }

    /**
     * Create an instance of CALCULOLIQUIDACIONTypeREQUESTTypeINMUEBLEType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.INMUEBLEType createCALCULOLIQUIDACIONTypeREQUESTTypeINMUEBLEType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REQUESTTypeImpl.INMUEBLETypeImpl();
    }

    /**
     * Create an instance of PAGOLIQUIDACIONTypeREPLYTypeADQUIRENTESType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REPLYType.ADQUIRENTESType createPAGOLIQUIDACIONTypeREPLYTypeADQUIRENTESType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REPLYTypeImpl.ADQUIRENTESTypeImpl();
    }

    /**
     * Create an instance of CALCULOLIQUIDACIONTypeREPLYTypeREPRESENTANTESType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.REPRESENTANTESType createCALCULOLIQUIDACIONTypeREPLYTypeREPRESENTANTESType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REPLYTypeImpl.REPRESENTANTESTypeImpl();
    }

    /**
     * Create an instance of CALCULOLIQUIDACIONTypeREQUESTTypeREPRESENTANTESType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REQUESTType.REPRESENTANTESType createCALCULOLIQUIDACIONTypeREQUESTTypeREPRESENTANTESType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REQUESTTypeImpl.REPRESENTANTESTypeImpl();
    }

    /**
     * Create an instance of PAGOLIQUIDACIONTypeREPLYType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REPLYType createPAGOLIQUIDACIONTypeREPLYType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REPLYTypeImpl();
    }

    /**
     * Create an instance of AdquirenteType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.AdquirenteType createAdquirenteType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.AdquirenteTypeImpl();
    }

    /**
     * Create an instance of PAGOLIQUIDACIONTypeREQUESTType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REQUESTType createPAGOLIQUIDACIONTypeREQUESTType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REQUESTTypeImpl();
    }

    /**
     * Create an instance of EXENCIONESBONIFICACIONESTypeREPLYTypeEXENCIONESType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.EXENCIONESType createEXENCIONESBONIFICACIONESTypeREPLYTypeEXENCIONESType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.EXENCIONESBONIFICACIONESTypeImpl.REPLYTypeImpl.EXENCIONESTypeImpl();
    }

    /**
     * Create an instance of PAGOLIQUIDACIONTypeREQUESTTypePAGOType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.PAGOLIQUIDACIONType.REQUESTType.PAGOType createPAGOLIQUIDACIONTypeREQUESTTypePAGOType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.PAGOLIQUIDACIONTypeImpl.REQUESTTypeImpl.PAGOTypeImpl();
    }

    /**
     * Create an instance of ProtocoloType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.ProtocoloType createProtocoloType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.ProtocoloTypeImpl();
    }

    /**
     * Create an instance of TransmitenteTypeBONIFICACIONESType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.BONIFICACIONESType createTransmitenteTypeBONIFICACIONESType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.TransmitenteTypeImpl.BONIFICACIONESTypeImpl();
    }

    /**
     * Create an instance of DireccionInmuebleType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.DireccionInmuebleType createDireccionInmuebleType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.DireccionInmuebleTypeImpl();
    }

    /**
     * Create an instance of EXENCIONESBONIFICACIONESTypeREPLYTypeRESULTADOType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REPLYType.RESULTADOType createEXENCIONESBONIFICACIONESTypeREPLYTypeRESULTADOType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.EXENCIONESBONIFICACIONESTypeImpl.REPLYTypeImpl.RESULTADOTypeImpl();
    }

    /**
     * Create an instance of CALCULOLIQUIDACIONTypeREPLYTypeTRANSMITENTESType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.CALCULOLIQUIDACIONType.REPLYType.TRANSMITENTESType createCALCULOLIQUIDACIONTypeREPLYTypeTRANSMITENTESType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.CALCULOLIQUIDACIONTypeImpl.REPLYTypeImpl.TRANSMITENTESTypeImpl();
    }

    /**
     * Create an instance of EXENCIONESBONIFICACIONESTypeREQUESTType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONESType.REQUESTType createEXENCIONESBONIFICACIONESTypeREQUESTType()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.EXENCIONESBONIFICACIONESTypeImpl.REQUESTTypeImpl();
    }

    /**
     * Create an instance of EXENCIONESBONIFICACIONES
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public org.notariado.ancert.xml.plusvalias.liquidacion.EXENCIONESBONIFICACIONES createEXENCIONESBONIFICACIONES()
        throws javax.xml.bind.JAXBException
    {
        return new org.notariado.ancert.xml.plusvalias.liquidacion.impl.EXENCIONESBONIFICACIONESImpl();
    }

}
