//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v@@BUILD_VERSION@@ 
// 	See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// 	Any modifications to this file will be lost upon recompilation of the source schema. 
// 	Generated on: 2011.07.04 en 12:38:50 CEST 
//


package org.notariado.ancert.xml.plusvalias.liquidacion;


/**
 * Java content class for TransmitenteType complex type.
 * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 1013)
 * <p>
 * <pre>
 * &lt;complexType name="TransmitenteType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DATOS_BASICOS" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}SujetoType"/>
 *         &lt;element name="PORCENTAJE_TRANSMITIDO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}PORCENTAJEType"/>
 *         &lt;element name="CLASE_DERECHO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}CLASE_DERECHOType"/>
 *         &lt;element name="FECHA_DEFUNCION" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}TFecha" minOccurs="0"/>
 *         &lt;element name="EDAD_USUFRUCTUARIO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}ANYOSType" minOccurs="0"/>
 *         &lt;element name="ANYOS_USUFRUCTO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}ANYOSType" minOccurs="0"/>
 *         &lt;element name="EDAD_USO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}ANYOSType" minOccurs="0"/>
 *         &lt;element name="ANYOS_USO" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}ANYOSType" minOccurs="0"/>
 *         &lt;element name="TRANSMISIONES_ANTERIORES">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TRANSMISION" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="FECHA" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}TFecha"/>
 *                             &lt;element name="PORCENTAJE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}PORCENTAJEType"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BONIFICACIONES" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PORCENTAJE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}PORCENTAJEType"/>
 *                   &lt;element name="CONCEPTO">
 *                     &lt;restriction base="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}STRINGType">
 *                       &lt;minLength value="1"/>
 *                       &lt;maxLength value="50"/>
 *                     &lt;/restriction>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EXENCIONES" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PORCENTAJE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}PORCENTAJEType"/>
 *                   &lt;element name="CONCEPTO">
 *                     &lt;restriction base="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}STRINGType">
 *                       &lt;minLength value="1"/>
 *                       &lt;maxLength value="50"/>
 *                     &lt;/restriction>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="REPRESENTANTES" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ID_REPRESENTANTE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}ID_SECUENCIALType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface TransmitenteType {


    /**
     * Años de usufructo. Obligatorio en usufructos temporales.
     * 
     */
    long getANYOSUSUFRUCTO();

    /**
     * Años de usufructo. Obligatorio en usufructos temporales.
     * 
     */
    void setANYOSUSUFRUCTO(long value);

    /**
     * Clase de derecho transmitido o constituido mediante la operación ("1" Pleno dominio, "2" Nuda Propiedad, "3" Usufructo vitalicio, "4" Uso o habitación temporal, "5" Derecho de superficie, "6" Concesión administrativa, "7" Usufructo temporal, "8" Uso o habitación vitalicio)
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getCLASEDERECHO();

    /**
     * Clase de derecho transmitido o constituido mediante la operación ("1" Pleno dominio, "2" Nuda Propiedad, "3" Usufructo vitalicio, "4" Uso o habitación temporal, "5" Derecho de superficie, "6" Concesión administrativa, "7" Usufructo temporal, "8" Uso o habitación vitalicio)
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setCLASEDERECHO(java.lang.String value);

    /**
     * Edad del usufructuario. Obligatorio en usufructos vitalicios.
     * 
     */
    long getEDADUSUFRUCTUARIO();

    /**
     * Edad del usufructuario. Obligatorio en usufructos vitalicios.
     * 
     */
    void setEDADUSUFRUCTUARIO(long value);

    /**
     * Porcentaje transmitido sobre el total de la finca.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getPORCENTAJETRANSMITIDO();

    /**
     * Porcentaje transmitido sobre el total de la finca.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setPORCENTAJETRANSMITIDO(java.lang.String value);

    /**
     * Cada una de las transmisiones anteriores. (fechas y porcentajes de adquisición del bien transmitido)
     * 
     * @return
     *     possible object is
     *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.TRANSMISIONESANTERIORESType}
     */
    org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.TRANSMISIONESANTERIORESType getTRANSMISIONESANTERIORES();

    /**
     * Cada una de las transmisiones anteriores. (fechas y porcentajes de adquisición del bien transmitido)
     * 
     * @param value
     *     allowed object is
     *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.TRANSMISIONESANTERIORESType}
     */
    void setTRANSMISIONESANTERIORES(org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.TRANSMISIONESANTERIORESType value);

    /**
     * Gets the value of the datosbasicos property.
     * 
     * @return
     *     possible object is
     *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.SujetoType}
     */
    org.notariado.ancert.xml.plusvalias.liquidacion.SujetoType getDATOSBASICOS();

    /**
     * Sets the value of the datosbasicos property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.SujetoType}
     */
    void setDATOSBASICOS(org.notariado.ancert.xml.plusvalias.liquidacion.SujetoType value);

    /**
     * Si hay bonificación, se indicará el concepto y el porcentaje bonificado.
     * 
     * @return
     *     possible object is
     *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.BONIFICACIONESType}
     */
    org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.BONIFICACIONESType getBONIFICACIONES();

    /**
     * Si hay bonificación, se indicará el concepto y el porcentaje bonificado.
     * 
     * @param value
     *     allowed object is
     *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.BONIFICACIONESType}
     */
    void setBONIFICACIONES(org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.BONIFICACIONESType value);

    /**
     * Años de uso. Obligatorio en Uso o habitación vitalicio.
     * 
     */
    long getEDADUSO();

    /**
     * Años de uso. Obligatorio en Uso o habitación vitalicio.
     * 
     */
    void setEDADUSO(long value);

    /**
     * Gets the value of the representantes property.
     * 
     * @return
     *     possible object is
     *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.REPRESENTANTESType}
     */
    org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.REPRESENTANTESType getREPRESENTANTES();

    /**
     * Sets the value of the representantes property.
     * 
     * @param value
     *     allowed object is
     *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.REPRESENTANTESType}
     */
    void setREPRESENTANTES(org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.REPRESENTANTESType value);

    /**
     * Si hay exenciones, se indicará el concepto y el porcentaje exento.
     * 
     * @return
     *     possible object is
     *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.EXENCIONESType}
     */
    org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.EXENCIONESType getEXENCIONES();

    /**
     * Si hay exenciones, se indicará el concepto y el porcentaje exento.
     * 
     * @param value
     *     allowed object is
     *     {@link org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.EXENCIONESType}
     */
    void setEXENCIONES(org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.EXENCIONESType value);

    /**
     * Años de uso. Obligatorio en Uso o habitación temporal.
     * 
     */
    long getANYOSUSO();

    /**
     * Años de uso. Obligatorio en Uso o habitación temporal.
     * 
     */
    void setANYOSUSO(long value);

    /**
     * Fecha de defunción del causante de heréncia. Será la fecha de transmisión en transmisiones Mortis causa.
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getFECHADEFUNCION();

    /**
     * Fecha de defunción del causante de heréncia. Será la fecha de transmisión en transmisiones Mortis causa.
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setFECHADEFUNCION(java.lang.String value);


    /**
     * Java content class for anonymous complex type.
     * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 1080)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PORCENTAJE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}PORCENTAJEType"/>
     *         &lt;element name="CONCEPTO">
     *           &lt;restriction base="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}STRINGType">
     *             &lt;minLength value="1"/>
     *             &lt;maxLength value="50"/>
     *           &lt;/restriction>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface BONIFICACIONESType {


        /**
         * Gets the value of the porcentaje property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getPORCENTAJE();

        /**
         * Sets the value of the porcentaje property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setPORCENTAJE(java.lang.String value);

        /**
         * Gets the value of the concepto property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getCONCEPTO();

        /**
         * Sets the value of the concepto property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setCONCEPTO(java.lang.String value);

    }


    /**
     * Java content class for anonymous complex type.
     * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 1098)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PORCENTAJE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}PORCENTAJEType"/>
     *         &lt;element name="CONCEPTO">
     *           &lt;restriction base="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}STRINGType">
     *             &lt;minLength value="1"/>
     *             &lt;maxLength value="50"/>
     *           &lt;/restriction>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface EXENCIONESType {


        /**
         * Gets the value of the porcentaje property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getPORCENTAJE();

        /**
         * Sets the value of the porcentaje property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setPORCENTAJE(java.lang.String value);

        /**
         * Gets the value of the concepto property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.String}
         */
        java.lang.String getCONCEPTO();

        /**
         * Sets the value of the concepto property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.String}
         */
        void setCONCEPTO(java.lang.String value);

    }


    /**
     * Java content class for anonymous complex type.
     * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 1113)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ID_REPRESENTANTE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}ID_SECUENCIALType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface REPRESENTANTESType {


        /**
         * Identificador del representante del sujeto pasivo.Gets the value of the IDREPRESENTANTE property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the IDREPRESENTANTE property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIDREPRESENTANTE().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * long
         * 
         */
        java.util.List getIDREPRESENTANTE();

    }


    /**
     * Java content class for anonymous complex type.
     * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 1055)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TRANSMISION" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="FECHA" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}TFecha"/>
     *                   &lt;element name="PORCENTAJE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}PORCENTAJEType"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface TRANSMISIONESANTERIORESType {


        /**
         * Gets the value of the TRANSMISION property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the TRANSMISION property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTRANSMISION().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link org.notariado.ancert.xml.plusvalias.liquidacion.TransmitenteType.TRANSMISIONESANTERIORESType.TRANSMISIONType}
         * 
         */
        java.util.List getTRANSMISION();


        /**
         * Java content class for anonymous complex type.
         * 	<p>The following schema fragment specifies the expected 	content contained within this java content object. 	(defined at file:/C:/Sun/jwsdp-1.5/jaxb/bin/IIVTNU-WS-Ayto.xsd line 1058)
         * <p>
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="FECHA" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}TFecha"/>
         *         &lt;element name="PORCENTAJE" type="{http://ancert.notariado.org/XML/Plusvalias/Liquidacion}PORCENTAJEType"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         */
        public interface TRANSMISIONType {


            /**
             * Porcentaje adquirido sobre el total transmitido.
             * 
             * @return
             *     possible object is
             *     {@link java.lang.String}
             */
            java.lang.String getPORCENTAJE();

            /**
             * Porcentaje adquirido sobre el total transmitido.
             * 
             * @param value
             *     allowed object is
             *     {@link java.lang.String}
             */
            void setPORCENTAJE(java.lang.String value);

            /**
             * Fecha de adquisición
             * 
             * @return
             *     possible object is
             *     {@link java.lang.String}
             */
            java.lang.String getFECHA();

            /**
             * Fecha de adquisición
             * 
             * @param value
             *     allowed object is
             *     {@link java.lang.String}
             */
            void setFECHA(java.lang.String value);

        }

    }

}
