

CREATE SEQUENCE SEQ_INFO
INCREMENT BY 1
MINVALUE 1
MAXVALUE 100000000000
START WITH 1;

CREATE TABLE AANAUDITACCION (
  MODULO	NUMBER  NOT NULL,
  ACCION  	NUMBER  NOT NULL,
  NIVEL		NUMBER  NOT NULL
  );

CREATE TABLE AANAUDITUSR (
  TIPOAUDITADO	VARCHAR2(32 CHAR) NOT NULL,
  IDAUDITADO    VARCHAR2(32 CHAR) NOT NULL,
  NIVEL         NUMBER NOT NULL
  );

CREATE TABLE AADATOSTRAZA (
  ID          VARCHAR2(32 CHAR) NOT NULL,
  IDTRAZA     VARCHAR2(32 CHAR) NOT NULL,
  CONTENIDO   CLOB,
  TIPOOBJETO  NUMBER,
  IDOBJETO    VARCHAR2(32 CHAR)
  );

CREATE TABLE AATRAZA (
  ID         VARCHAR2(32 CHAR)	NOT NULL,
  MODULO     NUMBER        	NOT NULL,
  ACCION     NUMBER			NOT NULL,
  TIMESTAMP  DATE			NOT NULL,
  DIRIP      VARCHAR2(32 CHAR)	NOT NULL,
  IDUSUARIO  VARCHAR2(32 CHAR),
  CODERROR   NUMBER
  );

CREATE TABLE AASESION (
  IDUSUARIO  VARCHAR2(32 CHAR)	NOT NULL,
  KEEPALIVE  DATE			NOT NULL,
  ID         VARCHAR2(64 CHAR)	NOT NULL
  );

CREATE TABLE ADAREA (
  ID           VARCHAR2(32 CHAR)  NOT NULL,
  NOMBRE       VARCHAR2(128 CHAR) NOT NULL,
  TIPONORMA    INTEGER       DEFAULT 0 NOT NULL,
  DESCRIPCION  VARCHAR2(254 CHAR)
  );

CREATE TABLE ADCAMPODATO (
  ID           VARCHAR2(32 CHAR)  NOT NULL,
  NOMBRE       VARCHAR2(64 CHAR)  NOT NULL,
  TIPO         INTEGER       NOT NULL,
  TIPONORMA    INTEGER       NOT NULL,
  IDAREA       VARCHAR2(32 CHAR),
  IDTBLPADRE   VARCHAR2(32 CHAR),
  POSENTBL     INTEGER,
  ETIQUETAXML  VARCHAR2(128 CHAR)  NOT NULL,
  DESCRIPCION  VARCHAR2(254 CHAR)
  );

CREATE TABLE ADCAMPOTBL (
  ID           VARCHAR2(32 CHAR)  NOT NULL,
  NOMBRE       VARCHAR2(64 CHAR)  NOT NULL,
  TIPONORMA    INTEGER       NOT NULL,
  IDAREA       VARCHAR2(32 CHAR),
  ETIQUETAXML  VARCHAR2(128 CHAR)  NOT NULL,
  ETIQXMLFILA  VARCHAR2(128 CHAR)  NOT NULL,
  DESCRIPCION  VARCHAR2(254 CHAR)
  );

CREATE TABLE ADCTLGLISTAD (
  ID                 VARCHAR2(32 CHAR)  	NOT NULL,
  NOMBRE             VARCHAR2(64 CHAR)  	NOT NULL,
  TIPO               INTEGER		NOT NULL,
  TIPODESCRIPTOR     INTEGER  		NOT NULL,
  IDFICHADESCRPREF   VARCHAR2(32 CHAR),
  IDFICHACLFDOCPREF  VARCHAR2(32 CHAR),
  IDREPECMPREF         VARCHAR2(32 CHAR),
  DESCRIPCION        VARCHAR2(254 CHAR)
  );

CREATE TABLE ADCTLGTBLVLD (
  ID           	VARCHAR2(32 CHAR)  NOT NULL,
  NOMBRE       	VARCHAR2(64 CHAR)  NOT NULL,
  DESCRIPCION  	VARCHAR2(254 CHAR),
  USOINTERNO	CHAR(1 CHAR)
  );

CREATE TABLE ADDESCRIPTOR (
  ID              VARCHAR2(32 CHAR)  NOT NULL,
  NOMBRE          VARCHAR2(512 CHAR)  NOT NULL,
  IDLISTA         VARCHAR2(32 CHAR)  NOT NULL,
  TIPO            INTEGER       NOT NULL,
  ESTADO          INTEGER       NOT NULL,
  IDSISTEXT       VARCHAR2(64 CHAR),
  IDDESCRSISTEXT  VARCHAR2(32 CHAR),
  TIMESTAMP       DATE          NOT NULL,
  IDFICHADESCR    VARCHAR2(32 CHAR),
  TIENEDESCR      CHAR(1 CHAR),
  EDITCLFDOCS     CHAR(1 CHAR),
  IDREPECM          VARCHAR2(32 CHAR),
  NIVELACCESO     NUMBER (2) NOT NULL,
  IDLCA           VARCHAR2(32 CHAR)
  );

CREATE TABLE ADFICHA (
  ID           VARCHAR2(32 CHAR) NOT NULL,
  NOMBRE       VARCHAR2(64 CHAR) NOT NULL,
  DEFINICION   CLOB         NOT NULL,
  TIPONORMA    INTEGER		NOT NULL,
  TIPONIVEL    INTEGER      NOT NULL,
  SUBTIPONIVEL    INTEGER   DEFAULT 0 NOT NULL,
  DESCRIPCION  VARCHAR2(254 CHAR)
  );

CREATE TABLE ADFMTFICHA (
  ID           VARCHAR2(32 CHAR)  NOT NULL,
  NOMBRE       VARCHAR2(128 CHAR)  NOT NULL,
  DEFINICION   CLOB          NOT NULL,
  IDFICHA      VARCHAR2(32 CHAR)  NOT NULL,
  TIPO         NUMBER (1)    NOT NULL,
  NIVELACCESO  NUMBER (2)    NOT NULL,
  IDLCA        VARCHAR2(32 CHAR),
  DESCRIPCION  VARCHAR2(254 CHAR)
  );

CREATE TABLE ADFMTPREF (
  IDFICHA    VARCHAR2(32 CHAR)  NOT NULL,
  IDUSUARIO  VARCHAR2(32 CHAR)  NOT NULL,
  TIPOFMT    NUMBER (1)    NOT NULL,
  IDFMT      VARCHAR2(32 CHAR)  NOT NULL
  );

CREATE TABLE ADOCCLASIFCF (
  ID            VARCHAR2(32 CHAR)  NOT NULL,
  NOMBRE        VARCHAR2(128 CHAR)  NOT NULL,
  IDCLFPADRE    VARCHAR2(32 CHAR),
  IDELEMENTOCF  VARCHAR2(32 CHAR)  NOT NULL,
  MARCAS        INTEGER       NOT NULL,
  ESTADO        INTEGER       NOT NULL,
  DESCRIPCION   VARCHAR2(512 CHAR)
  );

CREATE TABLE ADOCCLASIFDESCR (
  ID            VARCHAR2(32 CHAR)  NOT NULL,
  NOMBRE        VARCHAR2(128 CHAR)  NOT NULL,
  IDCLFPADRE    VARCHAR2(32 CHAR),
  IDDESCR       VARCHAR2(32 CHAR)  NOT NULL,
  MARCAS        INTEGER       NOT NULL,
  ESTADO        INTEGER       NOT NULL,
  DESCRIPCION   VARCHAR2(254 CHAR)
  );

CREATE TABLE ADOCDOCUMENTOCF (
  ID            VARCHAR2(32 CHAR)  NOT NULL,
  NOMBRE        VARCHAR2(128 CHAR) NOT NULL,
  IDCLFPADRE    VARCHAR2(32 CHAR),
  IDELEMENTOCF  VARCHAR2(32 CHAR)  NOT NULL,
  TAMANOFICH    FLOAT NOT NULL,
  NOMBREORGFICH VARCHAR2(254 CHAR) NOT NULL,
  EXTFICH       VARCHAR2(16 CHAR)  NOT NULL,
  IDEXTDEPOSITO VARCHAR2(32 CHAR),
  IDFICH        VARCHAR2(128 CHAR) NOT NULL,
  ESTADO        INTEGER NOT NULL,
  DESCRIPCION   VARCHAR2(254 CHAR),
  IDREPECM      VARCHAR2(32 CHAR)
  );

CREATE TABLE ADOCDOCUMENTODESCR (
  ID            VARCHAR2(32 CHAR)  NOT NULL,
  NOMBRE        VARCHAR2(128 CHAR)  NOT NULL,
  IDCLFPADRE    VARCHAR2(32 CHAR),
  IDDESCR       VARCHAR2(32 CHAR)  NOT NULL,
  TAMANOFICH    FLOAT          NOT NULL,
  NOMBREORGFICH VARCHAR2(254 CHAR) NOT NULL,
  EXTFICH       VARCHAR2(16 CHAR)  NOT NULL,
  IDFICH        VARCHAR2(128 CHAR)  NOT NULL,
  ESTADO        INTEGER       NOT NULL,
  DESCRIPCION   VARCHAR2(254 CHAR),
  IDREPECM      VARCHAR2(32 CHAR)
  );

CREATE TABLE ADOCFICHACLF (
  ID           VARCHAR2(32 CHAR)  NOT NULL,
  NOMBRE       VARCHAR2(64 CHAR)  NOT NULL,
  DEFINICION   CLOB          NOT NULL,
  DESCRIPCION  VARCHAR2(254 CHAR)
  );

CREATE TABLE ADOCTCAPTURA (
  ID           VARCHAR2(32 CHAR)  NOT NULL,
  TIPOOBJ      INTEGER        NOT NULL,
  IDOBJ        VARCHAR2(32 CHAR)  NOT NULL,
  IDUSRCAPTURA VARCHAR2(32 CHAR)  NOT NULL,
  CODREFOBJ    VARCHAR2(1024 CHAR),
  TITULOOBJ    VARCHAR2(1024 CHAR) NOT NULL,
  ESTADO       INTEGER        NOT NULL,
  FECHAESTADO  DATE           NOT NULL,
  OBSERVACIONES VARCHAR2(254 CHAR),
  MOTIVOERROR  VARCHAR2(254 CHAR)
  );

CREATE TABLE ADPCDOCUMENTOVIT (
  ID           VARCHAR2(32 CHAR)  NOT NULL,
  IDBDTERCEROS VARCHAR2(64 CHAR)  NOT NULL,
  NUMIDENTIDAD VARCHAR2(32 CHAR),
  IDENTIDAD    VARCHAR2(254 CHAR),
  IDTIPODOCVIT VARCHAR2(32 CHAR)  NOT NULL,
  FECHACAD     DATE,
  ESTADODOCVIT INTEGER        NOT NULL,
  FECHACR      DATE           NOT NULL,
  IDUSUARIOCR  VARCHAR2(32 CHAR)  NOT NULL,
  FECHAVIG     DATE,
  IDUSUARIOVIG VARCHAR2(32 CHAR),
  NUMACCESOS   INTEGER        NOT NULL,
  FECHAULTACCESO DATE,
  TAMANOFICH   FLOAT          NOT NULL,
  NOMBREORGFICH VARCHAR2(254 CHAR) NOT NULL,
  EXTFICH      VARCHAR2(16 CHAR)  NOT NULL,
  IDFICH       VARCHAR2(128 CHAR)  NOT NULL,
  OBSERVACIONES VARCHAR2(254 CHAR),
  IDREPECM		VARCHAR2(32 CHAR)
  );

CREATE TABLE ADPCUSODOCVIT (
  IDDOCVIT     VARCHAR2(32 CHAR)  NOT NULL,
  IDEXP        VARCHAR2(254 CHAR)  NOT NULL,
  IDSIST       VARCHAR2(254 CHAR)  NOT NULL,
  FECHAUSO     DATE            NOT NULL,
  USUARIO      VARCHAR2(254 CHAR)  NOT NULL
  );

CREATE TABLE ADPCTIPODOCVIT (
  ID           VARCHAR2(32 CHAR)  NOT NULL,
  NOMBRE       VARCHAR2(254 CHAR)  NOT NULL,
  DESCRIPCION  VARCHAR2(512 CHAR)
  );

CREATE TABLE ADPCTIPODOCPROC (
  IDTIPODOC    VARCHAR2(32 CHAR)  NOT NULL,
  IDPROC       VARCHAR2(254 CHAR)  NOT NULL
  );

CREATE TABLE ADTEXTTBLVLD (
  ID        VARCHAR2(32 CHAR)  NOT NULL,
  VALOR     VARCHAR2(254 CHAR)  NOT NULL,
  IDTBLVLD  VARCHAR2(32 CHAR)  NOT NULL
  );

CREATE TABLE ADUSOOBJETO (
  IDOBJ           VARCHAR2(32 CHAR)  NOT NULL,
  TIPOOBJ         INTEGER       NOT NULL,
  IDOBJUSUARIO    VARCHAR2(32 CHAR)  NOT NULL,
  TIPOOBJUSUARIO  INTEGER       NOT NULL
  );

CREATE TABLE ADVCFECHACF (
  IDELEMENTOCF  VARCHAR2(32 CHAR)  NOT NULL,
  IDCAMPO       VARCHAR2(32 CHAR)  NOT NULL,
  VALOR         VARCHAR2(64 CHAR),
  FECHAINI      DATE,
  FECHAFIN      DATE,
  CALIFICADOR   VARCHAR2(32 CHAR),
  ORDEN         INTEGER       NOT NULL,
  TIMESTAMP     DATE          NOT NULL,
  FORMATO       VARCHAR2(16 CHAR),
  SEP           CHAR(1 CHAR)
  );

CREATE TABLE ADVCFECHADESCR (
  IDDESCR      VARCHAR2(32 CHAR)  NOT NULL,
  IDCAMPO      VARCHAR2(32 CHAR)  NOT NULL,
  VALOR        VARCHAR2(64 CHAR),
  FECHAINI     DATE,
  FECHAFIN     DATE,
  FORMATO      VARCHAR2(16 CHAR),
  SEP          CHAR(1 CHAR),
  CALIFICADOR  VARCHAR2(32 CHAR),
  ORDEN        INTEGER       NOT NULL,
  TIMESTAMP    DATE          NOT NULL
  );

CREATE TABLE ADVCNUMCF (
  IDELEMENTOCF  VARCHAR2(32 CHAR)  NOT NULL,
  IDCAMPO       VARCHAR2(32 CHAR)  NOT NULL,
  VALOR         NUMBER (20,4) NOT NULL,
  ORDEN         INTEGER       NOT NULL,
  TIMESTAMP     DATE          NOT NULL,
  TIPOMEDIDA    INTEGER,
  UNIDADMEDIDA  VARCHAR2(16 CHAR)
  );

CREATE TABLE ADVCNUMDESCR (
  IDDESCR       VARCHAR2(32 CHAR)  NOT NULL,
  IDCAMPO       VARCHAR2(32 CHAR)  NOT NULL,
  VALOR         NUMBER (20,4) NOT NULL,
  ORDEN         INTEGER       NOT NULL,
  TIMESTAMP     DATE          NOT NULL,
  TIPOMEDIDA    INTEGER,
  UNIDADMEDIDA  VARCHAR2(16 CHAR)
  );

CREATE TABLE ADVCREFCF (
  IDELEMENTOCF  VARCHAR2(32 CHAR)  NOT NULL,
  IDCAMPO       VARCHAR2(32 CHAR)  NOT NULL,
  TIPOOBJREF    INTEGER       NOT NULL,
  IDOBJREF      VARCHAR2(32 CHAR)  NOT NULL,
  ORDEN         INTEGER       NOT NULL,
  TIMESTAMP     DATE          NOT NULL
  );

CREATE TABLE ADVCREFDESCR (
  IDDESCR     VARCHAR2(32 CHAR)  NOT NULL,
  IDCAMPO     VARCHAR2(32 CHAR)  NOT NULL,
  TIPOOBJREF  INTEGER       NOT NULL,
  IDOBJREF    VARCHAR2(32 CHAR)  NOT NULL,
  ORDEN       INTEGER       NOT NULL,
  TIMESTAMP   DATE          NOT NULL
  );

CREATE TABLE ADVCTEXTCF (
  IDELEMENTOCF  VARCHAR2(32 CHAR)  NOT NULL,
  IDCAMPO       VARCHAR2(32 CHAR)  NOT NULL,
  VALOR         VARCHAR2(254 CHAR)  NOT NULL,
  ORDEN         INTEGER       NOT NULL,
  TIMESTAMP     DATE          NOT NULL
  );


CREATE TABLE ADVCTEXTDESCR (
  IDDESCR    VARCHAR2(32 CHAR)  NOT NULL,
  IDCAMPO    VARCHAR2(32 CHAR)  NOT NULL,
  VALOR      VARCHAR2(254 CHAR)  NOT NULL,
  ORDEN      INTEGER       NOT NULL,
  TIMESTAMP  DATE          NOT NULL
  );

CREATE TABLE ADVCTEXTLCF (
  IDELEMENTOCF  VARCHAR2(32 CHAR)  NOT NULL,
  IDCAMPO       VARCHAR2(32 CHAR)  NOT NULL,
  VALOR         CLOB          NOT NULL,
  ORDEN         INTEGER       NOT NULL,
  TIMESTAMP     DATE          NOT NULL
  );


CREATE TABLE ADVCTEXTLDESCR (
  IDDESCR    VARCHAR2(32 CHAR)  NOT NULL,
  IDCAMPO    VARCHAR2(32 CHAR)  NOT NULL,
  VALOR      CLOB          NOT NULL,
  ORDEN      INTEGER       NOT NULL,
  TIMESTAMP  DATE          NOT NULL
  );


CREATE TABLE AGARCHIVO (
  ID      VARCHAR2(32 CHAR) NOT NULL,
  CODIGO  VARCHAR2(32 CHAR) NOT NULL,
  NOMBRE  VARCHAR2(128 CHAR) NOT NULL,
  IDNIVEL  VARCHAR2(32 CHAR) NOT NULL,
  IDRECEPTORDEFECTO VARCHAR2(32 CHAR),
  NOMBRECORTO VARCHAR2(25 CHAR) NOT NULL,
  TIPOSIGNATURACION INTEGER DEFAULT 1 NOT NULL
  );

CREATE TABLE AGNIVELARCHIVO(
  ID VARCHAR2(32 CHAR) NOT NULL,
  NOMBRE VARCHAR2(64 CHAR) NOT NULL,
  DESCRIPCION VARCHAR2(254 CHAR),
  ORDEN NUMBER NOT NULL
  );

CREATE TABLE AGFORMATO (
  ID          VARCHAR2(32 CHAR)  NOT NULL,
  NOMBRE      VARCHAR2(64 CHAR)  NOT NULL,
  TIPO        NUMBER (1)    NOT NULL,
  ESMULTIDOC  NUMBER (1)    NOT NULL,
  REGULAR     NUMBER (1)    NOT NULL,
  LONGITUD    NUMBER (8,2),
  XINFO       VARCHAR2(1024 CHAR),
  VIGENTE     NUMBER (1)    NOT NULL
  );

CREATE TABLE AGOBJBLOQUEO (
  IDOBJ      VARCHAR2(32 CHAR)  NOT NULL,
  TIPOOBJ    NUMBER        NOT NULL,
  MODULO     NUMBER        NOT NULL,
  TS         DATE          NOT NULL,
  IDUSUARIO  VARCHAR2(32 CHAR)  NOT NULL
  );

CREATE TABLE ASCAGRUPO (
  ID           VARCHAR2(32 CHAR)  NOT NULL,
  NOMBRE       VARCHAR2(254 CHAR)  NOT NULL,
  IDARCHIVO    VARCHAR2(32 CHAR),
  DESCRIPCION  VARCHAR2(254 CHAR),
  INFO 		   VARCHAR2(1024 CHAR) DEFAULT ''
  );

CREATE TABLE ASCALISTCA (
  ID           VARCHAR2(32 CHAR)  NOT NULL,
  NOMBRE       VARCHAR2(254 CHAR) NOT NULL,
  TIPO         NUMBER (1) NOT NULL,
  DESCRIPCION  VARCHAR2(512 CHAR) NOT NULL
  );

CREATE TABLE ASCAORGANO (
  ID                 VARCHAR2(32 CHAR)  NOT NULL,
  CODIGO             VARCHAR2(64 CHAR) NOT NULL,
  NOMBRE             VARCHAR2(254 CHAR) NOT NULL,
  NOMBRELARGO        VARCHAR2(1024 CHAR),
  IDARCHIVORECEPTOR  VARCHAR2(32 CHAR) NOT NULL,
  SISTEXTGESTOR      VARCHAR2(32 CHAR) NOT NULL,
  IDORGSEXTGESTOR    VARCHAR2(64 CHAR) NOT NULL,
  VIGENTE            CHAR(1 CHAR) NOT NULL,
  DESCRIPCION        VARCHAR2(254 CHAR)
  );

CREATE TABLE ASCAPERMGENROL (
  IDROL       VARCHAR2(32 CHAR) NOT NULL,
  TIPOMODULO  NUMBER (2) NOT NULL,
  PERM        NUMBER (4) NOT NULL
  );

CREATE TABLE ASCAPERMLISTCA (
  IDLISTCA  VARCHAR2(32 CHAR) NOT NULL,
  TIPODEST  NUMBER (1) NOT NULL,
  IDDEST    VARCHAR2(64 CHAR) NOT NULL,
  PERM      NUMBER (4) NOT NULL
  );

CREATE TABLE ASCAROL (
  ID           VARCHAR2(32 CHAR)  NOT NULL,
  NOMBRE       VARCHAR2(64 CHAR) NOT NULL,
  TIPOMODULO   NUMBER (2),
  DESCRIPCION  VARCHAR2(254 CHAR)
  );

CREATE TABLE ASCAROLUSR (
  IDROL       VARCHAR2(32 CHAR) NOT NULL,
  TIPOMODULO  NUMBER (2) NOT NULL,
  IDUSUARIO   VARCHAR2(32 CHAR) NOT NULL
  );

CREATE TABLE ASCAUSRGRP (
  IDUSUARIO  VARCHAR2(32 CHAR) NOT NULL,
  IDGRUPO    VARCHAR2(32 CHAR) NOT NULL
  );

CREATE TABLE ASCAUSRORG (
  IDUSUARIO  VARCHAR2(32 CHAR) NOT NULL,
  IDORGANO   VARCHAR2(32 CHAR) NOT NULL,
  FECHAINI   DATE,
  FECHAFIN   DATE
  );

CREATE TABLE ASCAUSUARIO (
  ID               VARCHAR2(32 CHAR)  NOT NULL,
  NOMBRE           VARCHAR2(254 CHAR) NOT NULL,
  APELLIDOS        VARCHAR2(254 CHAR),
  EMAIL            VARCHAR2(254 CHAR),
  DIRECCION        VARCHAR2(254 CHAR),
  TIPO             CHAR(1 CHAR) NOT NULL,
  HABILITADO       CHAR(1 CHAR) NOT NULL,
  FMAXVIGENCIA     DATE,
  IDUSRSEXTGESTOR  VARCHAR2(64 CHAR) NOT NULL,
  IDUSRSISTORG     VARCHAR2(64 CHAR),
  DESCRIPCION      VARCHAR2(254 CHAR)
  );

CREATE TABLE ASGDDEPOSITO (
  ID              VARCHAR2(32 CHAR)  NOT NULL,
  IDTIPOELEMENTO  VARCHAR2(32 CHAR)  NOT NULL,
  NUMORDEN        NUMBER NOT NULL,
  NOMBRE          VARCHAR2(64 CHAR) NOT NULL,
  UBICACION       VARCHAR2(255) NOT NULL,
  MARCAS          NUMBER (10) NOT NULL,
  IDARCHIVO VARCHAR2(32 CHAR) NOT NULL
  );

CREATE TABLE ASGDDEPOSITOELECTRONICO (
  ID              VARCHAR2(32 CHAR)  NOT NULL,
  IDEXT           VARCHAR2(64 CHAR)  NOT NULL,
  NOMBRE          VARCHAR2(64 CHAR)  NOT NULL,
  DESCRIPCION     VARCHAR2(254 CHAR),
  LOCALIZACION    CLOB           NOT NULL,
  USOFIRMA        VARCHAR2(1 CHAR)  DEFAULT 'N' NOT NULL
  );

CREATE TABLE ASGDELEMASIG (
  ID              VARCHAR2(32 CHAR)  NOT NULL,
  NOMBRE          VARCHAR2(64 CHAR)  NOT NULL,
  IDTIPOELEMENTO  VARCHAR2(32 CHAR)  NOT NULL,
  NUMORDEN        NUMBER        NOT NULL,
  IDELEMNAPADRE   VARCHAR2(32 CHAR)  NOT NULL,
  IDDEPOSITO      VARCHAR2(32 CHAR)  NOT NULL,
  LONGITUD        NUMBER (8,2)    NOT NULL,
  IDFORMATO       VARCHAR2(32 CHAR)  NOT NULL,
  NUMHUECOS       NUMBER (5)    NOT NULL,
  CODORDEN        VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL
  );

CREATE TABLE ASGDELEMNOASIG (
  ID              VARCHAR2(32 CHAR)  NOT NULL,
  IDTIPOELEMENTO  VARCHAR2(32 CHAR)  NOT NULL,
  NUMORDEN        NUMBER    NOT NULL,
  IDDEPOSITO      VARCHAR2(32 CHAR)  NOT NULL,
  NOMBRE          VARCHAR2(64 CHAR) NOT NULL,
  IDPADRE         VARCHAR2(32 CHAR),
  MARCAS          NUMBER (10) NOT NULL,
  CODORDEN        VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL
  );

CREATE TABLE ASGDHUECO (
  IDELEMAPADRE    VARCHAR2(32 CHAR)  NOT NULL,
  IDDEPOSITO      VARCHAR2(32 CHAR)  NOT NULL,
  NUMORDEN        NUMBER        NOT NULL,
  ESTADO          CHAR(1 CHAR) NOT NULL,
  IDFORMATO       VARCHAR2(32 CHAR) NOT NULL,
  IDUINSTALACION  VARCHAR2(32 CHAR),
  IDRELENTREGA    VARCHAR2(32 CHAR),
  FECHAESTADO     DATE NOT NULL,
  PATH            VARCHAR2(512 CHAR) NOT NULL,
  ORDENENRELACION  NUMBER        DEFAULT 0,
  CODORDEN        VARCHAR2(50 CHAR) DEFAULT ' ' NOT NULL ,
  TIPOORD         NUMBER(5) DEFAULT 1 NOT NULL,
  NUMERACION 	  VARCHAR2(16 CHAR),
  MARCAS 		  NUMBER(2) DEFAULT 0 NOT NULL,
  IDUIREEACR	  VARCHAR2(32 CHAR)
  );

CREATE TABLE ASGDSIGNUMORDEN (
  IDTIPOELEMPADRE  VARCHAR2(32 CHAR),
  IDELEMPADRE      VARCHAR2(32 CHAR),
  IDTIPOELEMENTO   VARCHAR2(32 CHAR) NOT NULL,
  NUMORDEN         NUMBER  NOT NULL
  );

CREATE TABLE ASGDTIPOELEMENTO (
  ID           VARCHAR2(32 CHAR)  NOT NULL,
  NOMBRE       VARCHAR2(64 CHAR)  NOT NULL,
  NOMBREABREV  VARCHAR2(16 CHAR),
  IDPADRE      VARCHAR2(32 CHAR),
  ASIGNABLE    NUMBER (1)    NOT NULL,
  DESCRIPCION  VARCHAR2(254 CHAR),
  CARACTERORDEN CHAR(1 CHAR) DEFAULT ' ' NOT NULL ,
  TIPOORD      NUMBER(5) DEFAULT 1 NOT NULL
  );

CREATE TABLE ASGDUDOCENUI (
  IDUNIDADDOC     VARCHAR2(32 CHAR),
  IDUINSTALACION  VARCHAR2(32 CHAR)  NOT NULL,
  POSUDOCENUI     NUMBER (5)    NOT NULL,
  SIGNATURAUDOC   VARCHAR2(32 CHAR)  NOT NULL,
  IDENTIFICACION  VARCHAR2(254 CHAR)  NOT NULL,
  IDUDOCRE        VARCHAR2(32 CHAR),
  DESCRIPCION     VARCHAR2(254 CHAR)
  );

CREATE TABLE ASGDUINSTALACION (
  ID              VARCHAR2(32 CHAR)  NOT NULL,
  IDFORMATO       VARCHAR2(32 CHAR)  NOT NULL,
  SIGNATURAUI     VARCHAR2(16 CHAR)  NOT NULL,
  IDENTIFICACION  VARCHAR2(254 CHAR)  NOT NULL,
  MARCASBLOQUEO   NUMBER(10) DEFAULT 0 NOT NULL,
  FCREACION 	  DATE DEFAULT SYSDATE NOT NULL
  );

CREATE TABLE ASGDHISTUINSTALACION(
  ID              VARCHAR2(32 CHAR) NOT NULL,
  IDARCHIVO       VARCHAR2(32 CHAR) NOT NULL,
  IDFORMATO       VARCHAR2(32 CHAR) NOT NULL,
  SIGNATURAUI	    VARCHAR2(16 CHAR) NOT NULL,
  IDENTIFICACION  VARCHAR2(254 CHAR)	NOT NULL,
  FELIMINACION    DATE NOT NULL,
  MOTIVO	        NUMBER(3) NOT NULL
  );

CREATE TABLE ASGFELEMENTOCF (
  ID             VARCHAR2(32 CHAR)  NOT NULL,
  TIPO           NUMBER (1) NOT NULL,
  IDNIVEL        VARCHAR2(32 CHAR) NOT NULL,
  CODIGO         VARCHAR2(128 CHAR),
  TITULO         VARCHAR2(1024 CHAR) NOT NULL,
  IDPADRE        VARCHAR2(32 CHAR),
  IDFONDO        VARCHAR2(32 CHAR),
  CODREFFONDO    VARCHAR2(254 CHAR),
  FINALCODREFPADRE  VARCHAR2(1024 CHAR),
  CODREFERENCIA  VARCHAR2(1024 CHAR),
  ESTADO         NUMBER (1) NOT NULL,
  IDELIMINACION  VARCHAR2(32 CHAR),
  IDFICHADESCR   VARCHAR2(32 CHAR),
  TIENEDESCR     CHAR(1 CHAR),
  EDITCLFDOCS	  CHAR(1 CHAR),
  IDREPECM			  VARCHAR2(32 CHAR),
  IDARCHIVO      VARCHAR2(32 CHAR),
  NIVELACCESO    NUMBER (2) NOT NULL,
  IDLCA          VARCHAR2(32 CHAR),
  SUBTIPO		 NUMBER(5) DEFAULT 0 NOT NULL,
  ORDPOS 		 VARCHAR2(32 CHAR)
  );

CREATE TABLE ASGFENTPRODUCTORA (
  CODIGO          VARCHAR2(32 CHAR)  NOT NULL,
  TIPO            NUMBER (1) NOT NULL,
  SISTGESTORORG   VARCHAR2(32 CHAR),
  IDENTPRODSGORG  VARCHAR2(64 CHAR),
  IDDESCR         VARCHAR2(32 CHAR) NOT NULL
  );

CREATE TABLE ASGFESTRUCTJNIVCF (
  IDNIVELPADRE    VARCHAR2(32 CHAR) NOT NULL,
  TIPONIVELPADRE  NUMBER (1) NOT NULL,
  IDNIVELHIJO     VARCHAR2(32 CHAR) NOT NULL,
  TIPONIVELHIJO   NUMBER (1) NOT NULL
  );

CREATE TABLE ASGFFONDO (
  CODPAIS          VARCHAR2(16 CHAR),
  CODCOMUNIDAD     VARCHAR2(16 CHAR),
  CODARCHIVO       VARCHAR2(32 CHAR),
  TIPO             NUMBER (1),
  IDENTPRODUCTORA  VARCHAR2(32 CHAR),
  IDELEMENTOCF     VARCHAR2(32 CHAR)  NOT NULL
  );

CREATE TABLE ASGFNIVELCF (
  ID                VARCHAR2(32 CHAR)  NOT NULL,
  NOMBRE            VARCHAR2(64 CHAR)  NOT NULL,
  TIPO              NUMBER (1)    NOT NULL,
  IDFICHADESCRPREF  VARCHAR2(32 CHAR),
  IDFICHACLFDOCPREF VARCHAR2(32 CHAR),
  IDREPECMPREF 		  VARCHAR2(32 CHAR),
  SUBTIPO NUMBER(5) DEFAULT 0 NOT NULL
  );

CREATE TABLE ASGFORGPROD (
  IDDESCR        VARCHAR2(32 CHAR)  NOT NULL,
  IDORG          VARCHAR2(32 CHAR)  NOT NULL,
  IDENTPRODINST  VARCHAR2(32 CHAR)  NOT NULL
  );

CREATE TABLE ASGFPRODSERIE (
  IDSERIE          VARCHAR2(32 CHAR) NOT NULL,
  IDPROCEDIMIENTO  VARCHAR2(32 CHAR),
  IDPRODUCTOR      VARCHAR2(32 CHAR) NOT NULL,
  TIPOPRODUCTOR    NUMBER NOT NULL,
  FECHAINICIO      DATE NOT NULL,
  FECHAFINAL       DATE,
  IDLCAPREF        VARCHAR2(32 CHAR),
  MARCAS NUMBER(10) DEFAULT 0
  );

CREATE TABLE ASGFSERIE (
  IDELEMENTOCF         VARCHAR2(32 CHAR)  NOT NULL,
  IDFONDO              VARCHAR2(32 CHAR)   NOT NULL,
  ESTADOSERIE          NUMBER (2),
  FECHAESTADO          DATE NOT NULL,
  ULTIMOESTADOAUTORIZ  NUMBER (2),
  IDUSRGESTOR          VARCHAR2(32 CHAR),
  FEXTREMAINICIAL      DATE,
  FEXTREMAFINAL        DATE,
  IDPROCEDIMIENTO      VARCHAR2(32 CHAR),
  TIPOPROCEDIMIENTO	  NUMBER(1),
  NUMUNIDADDOC         NUMBER (10)  NOT NULL,
  NUMUINSTALACION      NUMBER (10)  NOT NULL,
  VOLUMEN		NUMBER  NOT NULL,
  IDENTIFICACION       CLOB,
  OBSERVACIONES        VARCHAR2(254 CHAR),
  INFOFICHAUDOCREPECM CLOB
  );

CREATE TABLE ASGFVOLUMENSERIE (
  IDSERIE VARCHAR2(32 CHAR) NOT NULL,
  TIPODOCUMENTAL VARCHAR2(254 CHAR) NOT NULL,
  CANTIDAD NUMBER NOT NULL
  );

CREATE TABLE ASGFSOLICITUDSERIE (
  ID                VARCHAR2(32 CHAR) 	NOT NULL,
  IDSERIE           VARCHAR2(32 CHAR),
  ETIQUETASERIE     VARCHAR2(254 CHAR) 	NOT NULL,
  TIPO              NUMBER (1) 		NOT NULL,
  FECHA             DATE 			NOT NULL,
  INFO              VARCHAR2(2000 CHAR),
  MOTIVOSOLICITUD   VARCHAR2(254 CHAR),
  IDUSRSOLICITANTE  VARCHAR2(32 CHAR) 	NOT NULL,
  ESTADO            NUMBER (1) 		NOT NULL,
  FECHAESTADO       DATE 			NOT NULL,
  IDUSRGESTOR       VARCHAR2(32 CHAR),
  MOTIVORECHAZO     VARCHAR2(254 CHAR)
  );

CREATE TABLE ASGFUNIDADDOC (
  IDELEMENTOCF      VARCHAR2(32 CHAR) NOT NULL,
  IDSERIE           VARCHAR2(32 CHAR) NOT NULL,
  IDFONDO           VARCHAR2(32 CHAR) NOT NULL,
  TIPODOCUMENTAL	  VARCHAR2(254 CHAR),
  NUMEXP            VARCHAR2(256 CHAR),
  CODSISTPRODUCTOR  VARCHAR2(16 CHAR),
  MARCASBLOQUEO     NUMBER DEFAULT 0 NOT NULL
  );

CREATE TABLE ASGFSNSEC (
  NUMSEC  NUMBER (10)   NOT NULL
  );

CREATE TABLE ASGFNUMSECVAL (
  IDSERIE  VARCHAR2(32 CHAR) NOT NULL,
  NUMSEC   NUMBER(10)  NOT NULL
  );

CREATE TABLE ASGFNUMSECSEL (
  IDSERIE  VARCHAR2(32 CHAR)  NOT NULL,
  NUMSEC   NUMBER (10) NOT NULL
  );

CREATE TABLE ASGFVALSERIE (
  ID                   VARCHAR2(32 CHAR)  NOT NULL,
  IDSERIE              VARCHAR2(32 CHAR)  NOT NULL,
  TITULO               VARCHAR2(254 CHAR) NOT NULL,
  ESTADO               NUMBER (1)    NOT NULL,
  FECHAESTADO          DATE          NOT NULL,
  MOTIVORECHAZO        VARCHAR2(254 CHAR),
  ORDSERIEPRIMERNIVEL  NUMBER,
  ORDSERIESEGNIVEL     NUMBER,
  SERIESPRECEDENTES    CLOB,
  SERIESRELACIONADAS   CLOB,
  DOCSRECOPILATORIOS   VARCHAR2(1024 CHAR),
  VALORADMTIPO         NUMBER,
  VALORADMVIG          NUMBER,
  VALORADMJUST         VARCHAR2(1024 CHAR),
  VALORLEGALTIPO       NUMBER,
  VALORLEGALVIG        NUMBER,
  VALORLEGALJUST       VARCHAR2(1024 CHAR),
  VALORINFTIPO         NUMBER,
  VALORINFJUST         VARCHAR2(1024 CHAR),
  VALORCIENTTIPO       NUMBER,
  VALORCIENTJUST       VARCHAR2(1024 CHAR),
  VALORTECNTIPO        NUMBER,
  VALORTECNJUST        VARCHAR2(1024 CHAR),
  VALORCULTTIPO        NUMBER,
  VALORCULTJUST        VARCHAR2(1024 CHAR),
  TECNICAMUESTREO      NUMBER,
  NUMREGISTRO          NUMBER,
  FVALIDACION          DATE,
  FEVALUACION          DATE,
  FDICTAMEN            DATE,
  VALORDICTAMEN        NUMBER,
  VALORDICTJUST	       CLOB,
  FRESOLDICTAMEN       DATE,
  BOLETINDICTAMEN      VARCHAR2(128 CHAR),
  FBOLETINDICTAMEN     DATE,
  IDUSRGESTORSERIE     VARCHAR2(32 CHAR) NOT NULL,
  REGIMENACCESOTIPO    NUMBER NOT NULL,
  REGIMENACCESOJUST    VARCHAR2(1024 CHAR),
  REGIMENACCESOVIG     NUMBER,
  INFOSERIE CLOB,
  REGIMENACCESOSUBTIPO NUMBER(5)
  );

CREATE TABLE ASGFELIMSERIE (
  ID               VARCHAR2(32 CHAR)  NOT NULL,
  IDVALORACION     VARCHAR2(32 CHAR)  NOT NULL,
  IDSERIE          VARCHAR2(32 CHAR)  NOT NULL,
  TITULO           VARCHAR2(254 CHAR)  NOT NULL,
  ESTADO           INTEGER       NOT NULL,
  FECHAESTADO      DATE          NOT NULL,
  MOTIVORECHAZO    VARCHAR2(254 CHAR),
  NOTAS            VARCHAR2(1024 CHAR),
  MAXANOSVIGENCIA  INTEGER       NOT NULL,
  CONDBUSQANADIDA  VARCHAR2(1024 CHAR),
  TIPOELIMINACION  INTEGER       NOT NULL,
  SELECCIONUDOC    VARCHAR2(1 CHAR)  NOT NULL,
  FEJECUCION       DATE,
  FAPROBACION      DATE,
  FDESTRUCCION     DATE,
  FFINALIZACION    DATE,
  IDARCHIVO VARCHAR2(32 CHAR) NOT NULL
  );

CREATE TABLE ASGFELIMUDOCCONS (
  IDELIMINACION  VARCHAR2(32 CHAR)  NOT NULL,
  IDUDOC         VARCHAR2(32 CHAR)  NOT NULL,
  SIGNATURAUDOC  VARCHAR2(128 CHAR)  NOT NULL,
  TITULOUDOC     VARCHAR2(1024 CHAR)  NOT NULL,
  FECHAINIUDOC   DATE,
  FECHAFINUDOC   DATE
  );

CREATE TABLE ASGFELIMSELUDOC(
  IDELIMINACION VARCHAR2(32 CHAR) NOT NULL,
  IDUDOC VARCHAR2(32 CHAR) NOT NULL,
  IDFONDO VARCHAR2(32 CHAR),
  CODREFERENCIA VARCHAR2(1024 CHAR),
  CODIGO VARCHAR2(128 CHAR),
  SIGNATURAUDOC VARCHAR2(32 CHAR),
  EXPEDIENTEUDOC VARCHAR2(256 CHAR),
  TITULO VARCHAR2(1024 CHAR),
  CODSISTPRODUCTOR VARCHAR2(16 CHAR),
  TIPODOCUMENTAL VARCHAR2(254 CHAR),
  IDUINSTALACION VARCHAR2(32 CHAR),
  UBICACION VARCHAR2(512 CHAR),
  FECHAINIUDOC DATE,
  FECHAFINUDOC DATE,
  NUMERO VARCHAR2(10 CHAR)
  );

CREATE TABLE ASGFHISTUDOC (
  IDELIMINACION   VARCHAR2(32 CHAR)  NOT NULL,
  IDUDOC          VARCHAR2(32 CHAR)  NOT NULL,
  SIGNATURAUDOC   VARCHAR2(128 CHAR)  NOT NULL,
  TITULOUDOC      VARCHAR2(1024 CHAR)  NOT NULL,
  NUMEXPUDOC      VARCHAR2(256 CHAR),
  CODREFUDOC      VARCHAR2(1024 CHAR)  NOT NULL,
  DATOSDESCRUDOC  CLOB
  );

CREATE TABLE ASGPCONSULTA (
  ID                 VARCHAR2(32 CHAR)  NOT NULL,
  ANO                VARCHAR2(4 CHAR)  NOT NULL,
  ORDEN              NUMBER (10)   NOT NULL,
  TIPOENTCONSULTORA  NUMBER (2)    NOT NULL,
  NORGCONSULTOR      VARCHAR2(254 CHAR),
  NUSRCONSULTOR      VARCHAR2(254 CHAR)  NOT NULL,
  FINICIALRESERVA    DATE,
  FENTREGA           DATE,
  FMAXFINCONSULTA    DATE,
  ESTADO             NUMBER (2)    NOT NULL,
  FESTADO            DATE          NOT NULL,
  MOTIVO             VARCHAR2(254 CHAR),
  IDARCHIVO          VARCHAR2(32 CHAR)  NOT NULL,
  IDUSRSOLICITANTE   VARCHAR2(32 CHAR)  NOT NULL,
  INFORMACION        VARCHAR2(1024 CHAR),
  TEMA               VARCHAR2(254 CHAR),
  TIPO               NUMBER (2)    NOT NULL,
  TIPOENTREGA 	     VARCHAR2(254 CHAR),
  DATOSAUTORIZADO    VARCHAR2(254 CHAR),
  DATOSSOLICITANTE   VARCHAR2(512 CHAR),
  OBSERVACIONES VARCHAR2(254 CHAR),
  IDMOTIVO VARCHAR2(32 CHAR),
  IDUSRCSALA VARCHAR2(32 CHAR)
  );

CREATE TABLE ASGPMTVCONSULTA (
  ID            VARCHAR2(32 CHAR) NOT NULL,
  TIPOENTIDAD   NUMBER (2)    NOT NULL,
  MOTIVO        VARCHAR2(254 CHAR)  NOT NULL,
  TIPOCONSULTA  NUMBER (2) NOT NULL,
  VISIBILIDAD   NUMBER (3)
  );

CREATE TABLE ASGPMTVRECHAZO (
  ID             VARCHAR2(32 CHAR) NOT NULL,
  TIPOSOLICITUD  NUMBER (2)    NOT NULL,
  MOTIVO         VARCHAR2(254 CHAR)  NOT NULL
  );

CREATE TABLE ASGPPRESTAMO (
  ID                VARCHAR2(32 CHAR)  NOT NULL,
  ANO               VARCHAR2(4 CHAR)  NOT NULL,
  ORDEN             NUMBER (10)   NOT NULL,
  NORGSOLICITANTE   VARCHAR2(254 CHAR)  NOT NULL,
  NUSRSOLICITANTE   VARCHAR2(254 CHAR)  NOT NULL,
  IDUSRSOLICITANTE  VARCHAR2(32 CHAR),
  FINICIALRESERVA   DATE,
  IDORGSOLICITANTE  VARCHAR2(32 CHAR),
  FENTREGA          DATE,
  FMAXFINPRESTAMO   DATE,
  ESTADO            NUMBER (2)    NOT NULL,
  FESTADO           DATE          NOT NULL,
  IDARCHIVO         VARCHAR2(32 CHAR)  NOT NULL,
  IDUSRGESTOR       VARCHAR2(32 CHAR)  NOT NULL,
  NUMRECLAMACIONES  NUMBER (10)   NOT NULL,
  FRECLAMACION1     DATE,
  FRECLAMACION2     DATE,
  TIPOENTREGA 	    VARCHAR2(254 CHAR),
  DATOSAUTORIZADO   VARCHAR2(254 CHAR),
  DATOSSOLICITANTE  VARCHAR2(512 CHAR),
  OBSERVACIONES     VARCHAR2(254 CHAR),
  IDMOTIVO          VARCHAR2(32 CHAR)
  );

CREATE TABLE ASGPMTVPRESTAMO (
  ID            VARCHAR2(32 CHAR) NOT NULL,
  TIPOUSUARIO   NUMBER(3)    NOT NULL,
  MOTIVO        VARCHAR2(254 CHAR)  NOT NULL,
  VISIBILIDAD   NUMBER(3)
  );

CREATE TABLE ASGPPRORROGA (
  ID             VARCHAR2(32 CHAR)  NOT NULL,
  IDPRESTAMO     VARCHAR2(32 CHAR)  NOT NULL,
  ESTADO         NUMBER (2)    NOT NULL,
  FESTADO        DATE          NOT NULL,
  MOTIVORECHAZO  VARCHAR2(254 CHAR),
  IDMOTIVO       VARCHAR2(32 CHAR),
  FECHAFINPRORROGA DATE,
  MOTIVOPRORROGA VARCHAR2(512 CHAR)
  );

CREATE TABLE ASGPSNSEC (
  TIPO    NUMBER (10)   NOT NULL,
  ANO     VARCHAR2(4 CHAR)  NOT NULL,
  NUMSEC  NUMBER (10)   NOT NULL
  );

CREATE TABLE ASGPSOLICITUDUDOC (
  IDSOLICITUD     VARCHAR2(32 CHAR)  NOT NULL,
  TIPOSOLICITUD   NUMBER (2)    NOT NULL,
  IDUDOC          VARCHAR2(32 CHAR)  NOT NULL,
  TITULO          VARCHAR2(1024 CHAR)  NOT NULL,
  SIGNATURAUDOC   VARCHAR2(254 CHAR)  NOT NULL,
  EXPEDIENTEUDOC  VARCHAR2(128 CHAR),
  IDENTIFICACION  VARCHAR2(254 CHAR)  NOT NULL,
  ESTADO          NUMBER (2)    NOT NULL,
  FESTADO         DATE          NOT NULL,
  FINICIALUSO     DATE,
  FFINALUSO       DATE,
  MOTIVORECHAZO   VARCHAR2(254 CHAR),
  INFORMACION     VARCHAR2(1024 CHAR),
  IDFONDO         VARCHAR2(32 CHAR) NOT NULL,
  IDMOTIVO        VARCHAR2(32 CHAR)
  );

CREATE TABLE ASGPTEMA (
  IDUSUARIO    VARCHAR2(32 CHAR),
  TIPOENTIDAD  NUMBER (2)    NOT NULL,
  TEMA         VARCHAR2(254 CHAR)  NOT NULL,
  IDUSRCSALA VARCHAR2(32 CHAR)
  );

CREATE TABLE ASGTDETALLEPREV (
  ID                   VARCHAR2(32 CHAR)  NOT NULL,
  IDPREVISION          VARCHAR2(32 CHAR) NOT NULL,
  ORDEN                NUMBER (3) NOT NULL,
  CODSISTPRODUCTOR     VARCHAR2(16 CHAR),
  NOMBRESISTPRODUCTOR  VARCHAR2(64 CHAR),
  IDPROCEDIMIENTO      VARCHAR2(32 CHAR),
  IDSERIEDESTINO       VARCHAR2(32 CHAR) NOT NULL,
  ANOINIUDOC           CHAR (4) NOT NULL,
  ANOFINUDOC           CHAR (4) NOT NULL,
  NUMUINSTALACION      NUMBER (4) NOT NULL,
  IDFORMATOUI          VARCHAR2(32 CHAR) NOT NULL,
  NUMRENTREGA          NUMBER (3),
  CERRADO              CHAR(1 CHAR) NOT NULL,
  OBSERVACIONES        VARCHAR2(254 CHAR),
  IDSERIEORIGEN VARCHAR2(32 CHAR),
  INFO VARCHAR2(1024 CHAR)
  );

CREATE TABLE ASGTPREVISION (
  ID                 VARCHAR2(32 CHAR)     NOT NULL,
  TIPOTRANSFERENCIA  NUMBER NOT NULL,
  TIPOPREVISION      NUMBER NOT NULL,
  IDORGREMITENTE     VARCHAR2(32 CHAR) NOT NULL,
  ANO                VARCHAR2(4 CHAR) NOT NULL,
  ORDEN              NUMBER (10) NOT NULL,
  IDFONDODESTINO     VARCHAR2(32 CHAR) NOT NULL,
  FECHAINITRANS      DATE,
  FECHAFINTRANS      DATE,
  NUMUINSTALACION    NUMBER,
  ESTADO             NUMBER (1) NOT NULL,
  FECHAESTADO        DATE NOT NULL,
  IDARCHIVORECEPTOR  VARCHAR2(32 CHAR) NOT NULL,
  IDUSRGESTOR        VARCHAR2(32 CHAR) NOT NULL,
  MOTIVORECHAZO      VARCHAR2(254 CHAR),
  OBSERVACIONES      VARCHAR2(254 CHAR),
  IDARCHIVOREMITENTE VARCHAR2(32 CHAR)
  );

CREATE TABLE ASGTRENTREGA (
  ID                   VARCHAR2(32 CHAR)  NOT NULL,
  TIPOTRANSFERENCIA    NUMBER (1) NOT NULL,
  IDPREVISION          VARCHAR2(32 CHAR) NOT NULL,
  IDDETPREVISION       VARCHAR2(32 CHAR),
  IDORGANOREMITENTE    VARCHAR2(32 CHAR) NOT NULL,
  ANO                  CHAR (4 CHAR) NOT NULL,
  ORDEN                NUMBER (4) NOT NULL,
  IDFONDODESTINO       VARCHAR2(32 CHAR) NOT NULL,
  CODSISTPRODUCTOR     VARCHAR2(16 CHAR),
  NOMBRESISTPRODUCTOR  VARCHAR2(64 CHAR),
  IDPROCEDIMIENTO      VARCHAR2(32 CHAR),
  IDFORMATOUI          VARCHAR2(32 CHAR) NOT NULL,
  TIPODOCUMENTAL		  VARCHAR2(254 CHAR),
  ESTADO               NUMBER (2) NOT NULL,
  FECHAESTADO          DATE NOT NULL,
  IDARCHIVORECEPTOR    VARCHAR2(32 CHAR) NOT NULL,
  FECHARECEPCION       DATE,
  IDUSRGESTORREM       VARCHAR2(32 CHAR) NOT NULL,
  IDUSRGESTORARCHIVOREC   VARCHAR2(32 CHAR),
  IDDEPOSITO           VARCHAR2(32 CHAR),
  RESERVADEPOSITO      NUMBER (1),
  UIENDEPOSITO         CHAR(1 CHAR),
  DEVOLUCIONUI         CHAR(1 CHAR),
  REGENTRADA           VARCHAR2(64 CHAR),
  OBSERVACIONES        VARCHAR2(2048 CHAR),
  IDSERIEDESTINO       VARCHAR2(32 CHAR) NOT NULL,
  IDELMTODRESERVA      VARCHAR2(32 CHAR),
  IDDESCRORGPRODUCTOR  VARCHAR2(32 CHAR),
  IDTIPOELMTODRESERVA  VARCHAR2(32 CHAR),
  IDARCHIVOREMITENTE VARCHAR2(32 CHAR),
  IDFONDOORIGEN VARCHAR2(32 CHAR),
  IDSERIEORIGEN VARCHAR2(32 CHAR),
  CORRECCIONENARCHIVO VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
  IDNIVELDOCUMENTAL    VARCHAR2(32 CHAR) NOT NULL,
  SINDOCSFISICOS VARCHAR2(1 CHAR),
  IDFICHA VARCHAR2(32 CHAR),
  CONREENCAJADO 	VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL,
  IDFORMATORE		VARCHAR2(32 CHAR)
  );

CREATE TABLE ASGTSNSEC (
  TIPO    NUMBER (1)  NOT NULL,
  ANO     CHAR (4)  NOT NULL,
  NUMSEC  NUMBER (10)  NOT NULL,
  IDARCHIVO  VARCHAR2(32 CHAR) NOT NULL
  );

CREATE TABLE ASGTSNSECUI (
  NUMSEC  NUMBER NOT NULL,
  IDARCHIVO VARCHAR2(32 CHAR)
  );

CREATE TABLE ASGTSNSECUDOC(
  NUMSEC  NUMBER NOT NULL
  );

CREATE TABLE ASGTUDOCENUI (
  IDRELENTREGA      VARCHAR2(32 CHAR)     NOT NULL,
  IDUNIDADDOC       VARCHAR2(32 CHAR) NOT NULL,
  IDUINSTALACIONRE  VARCHAR2(32 CHAR) NOT NULL,
  POSUDOCENUI       NUMBER (5) NOT NULL,
  UDOCCOMPLETA      CHAR(1 CHAR) NOT NULL,
  ESTADOCOTEJO      NUMBER (1) NOT NULL,
  NOTASCOTEJO       VARCHAR2(254 CHAR),
  SIGNATURAUDOC     VARCHAR2(32 CHAR),
  NUMPARTEUDOC      NUMBER (2) NOT NULL,
  DESCCONTENIDO     VARCHAR2(254 CHAR)
  );

CREATE TABLE ASGTUINSTALACIONRE (
  ID            VARCHAR2(32 CHAR)  NOT NULL,
  IDRELENTREGA  VARCHAR2(32 CHAR) NOT NULL,
  ORDEN         NUMBER NOT NULL,
  IDFORMATO     VARCHAR2(32 CHAR) NOT NULL,
  SIGNATURAUI   VARCHAR2(16 CHAR),
  ESTADOCOTEJO  NUMBER (1) NOT NULL,
  NOTASCOTEJO   VARCHAR2(254 CHAR),
  DEVOLUCION    CHAR(1 CHAR) NOT NULL,
  IDUIUBICADA 	VARCHAR2(32 CHAR)
  );

CREATE TABLE ASGTUINSTALACIONREEA(
  IDUIDEPOSITO 	VARCHAR2(32 CHAR) NOT NULL,
  IDRELENTREGA 	VARCHAR2(32 CHAR) NOT NULL,
  ORDEN 	NUMBER NOT NULL,
  IDFORMATO 	VARCHAR2(32 CHAR) NOT NULL,
  ESTADOCOTEJO 	NUMBER NOT NULL,
  NOTASCOTEJO 	VARCHAR2(254 CHAR),
  DEVOLUCION 	VARCHAR2(1 CHAR) NOT NULL,
  PATHDEPOSITOORIGEN VARCHAR2(512 CHAR) NOT NULL,
  SIGNATURAUI VARCHAR2(16 CHAR),
  IDELEMAPADREHUECOORIGEN VARCHAR2(32 CHAR) NOT NULL,
  NUMORDENHUECOORIGEN NUMBER NOT NULL,
  SIGNATURAUIORIGEN VARCHAR2(16 CHAR)
  );

CREATE TABLE ASGTUNIDADDOCRE (
  ID                VARCHAR2(32 CHAR)  NOT NULL,
  IDRELENTREGA      VARCHAR2(32 CHAR) NOT NULL,
  TIPOTRANSFERENCIA NUMBER (1) NOT NULL,
  NUMEXP            VARCHAR2(256 CHAR),
  CODSISTPRODUCTOR  VARCHAR2(16 CHAR),
  FECHAEXTINI       DATE,
  FECHAEXTFIN       DATE,
  ASUNTO            VARCHAR2(1024 CHAR),
  VALIDADA          CHAR(1 CHAR) NOT NULL,
  SINDOCSFISICOS    CHAR(1 CHAR) NOT NULL,
  INFO              CLOB NOT NULL,
  NUMPARTES         NUMBER (2),
  ORDEN             NUMBER,
  MARCASBLOQUEO     NUMBER DEFAULT 0 NOT NULL
  );

CREATE TABLE ASGTUDOCSDF(
	ID VARCHAR2(32 CHAR) NOT NULL,
	IDRELENTREGA VARCHAR2(32 CHAR) NOT NULL,
	POSICION NUMBER(5) NOT NULL,
	ESTADOCOTEJO NUMBER(5) NOT NULL,
	NOTASCOTEJO VARCHAR2(254 CHAR)
);

CREATE TABLE ASGFUDOCSDF (
	IDELEMENTOCF     VARCHAR2(32 CHAR) NOT NULL,
	MARCASBLOQUEO   NUMBER(10) DEFAULT 0 NOT NULL
);

CREATE TABLE ASGTMAPDESCRUDOC (
	IDFICHA   VARCHAR2(32 CHAR)  NOT NULL,
	INFO    CLOB  NOT NULL
);

CREATE TABLE ITDGUIDGEN (
  CNODE  VARCHAR2(12),
  CLPID  NUMBER
  );

CREATE TABLE AGINFOSISTEMA (
  AUTID NUMBER NOT NULL,
  NOMBRE VARCHAR2(32 CHAR) NOT NULL,
  VALOR CLOB NOT NULL,
  FECHAACTUALIZACION DATE NOT NULL
);

CREATE TABLE ADVCFECHAUDOCRE (
	IDUDOCRE VARCHAR2(32 CHAR) NOT NULL,
	IDCAMPO VARCHAR2(32 CHAR) NOT NULL,
	VALOR VARCHAR2(64 CHAR),
	FECHAINI DATE,
	FECHAFIN DATE,
	FORMATO VARCHAR2(16 CHAR),
	SEP VARCHAR2(1 CHAR),
	CALIFICADOR VARCHAR2(32 CHAR),
	ORDEN NUMBER(3) NOT NULL,
	TIPOUDOC NUMBER(2) DEFAULT 1 NOT NULL
);

CREATE TABLE ADVCNUMUDOCRE (
	IDUDOCRE VARCHAR2(32 CHAR) NOT NULL,
	IDCAMPO VARCHAR2(32 CHAR) NOT NULL,
	VALOR NUMBER(8,2) NOT NULL,
	ORDEN NUMBER(3) NOT NULL,
	TIPOMEDIDA NUMBER,
	UNIDADMEDIDA VARCHAR2(16 CHAR),
	TIPOUDOC NUMBER(2) DEFAULT 1 NOT NULL
);

CREATE TABLE ADVCREFUDOCRE (
	IDUDOCRE VARCHAR2(32 CHAR) NOT NULL,
	IDCAMPO VARCHAR2(32 CHAR) NOT NULL,
	TIPOOBJREF NUMBER(38) NOT NULL,
	IDOBJREF VARCHAR2(32 CHAR) NOT NULL,
	ORDEN NUMBER(3) NOT NULL,
	TIPOUDOC NUMBER(2) DEFAULT 1 NOT NULL
);

CREATE TABLE ADVCTEXTLUDOCRE (
	IDUDOCRE VARCHAR2(32 CHAR) NOT NULL,
	IDCAMPO VARCHAR2(32 CHAR) NOT NULL,
	VALOR CLOB NOT NULL,
	ORDEN NUMBER(3) NOT NULL,
	TIPOUDOC NUMBER(2) DEFAULT 1 NOT NULL
);

CREATE TABLE ADVCTEXTUDOCRE (
	IDUDOCRE VARCHAR2(32 CHAR) NOT NULL,
	IDCAMPO VARCHAR2(32 CHAR) NOT NULL,
	VALOR VARCHAR2(254 CHAR) NOT NULL,
	ORDEN NUMBER(3) NOT NULL,
	TIPOUDOC NUMBER(2) DEFAULT 1 NOT NULL
);

CREATE TABLE ASGFDIVISIONFS (
	IDFS VARCHAR2(32 CHAR) NOT NULL,
	IDFICHA VARCHAR2(32 CHAR) NULL,
	IDNIVELDOCUMENTAL VARCHAR2(32 CHAR) NOT NULL,
	IDUSRGESTOR VARCHAR2(32 CHAR) NOT NULL,
	ESTADO NUMBER(2) NOT NULL,
	INFO VARCHAR2(1024 CHAR),
	FECHAESTADO DATE NOT NULL
	);

CREATE TABLE ASGFUDOCENDIVISIONFS (
   	IDFS 			VARCHAR2(32 CHAR) NOT NULL,
   	IDUDOC 			VARCHAR2(32 CHAR) NOT NULL,
   	NUMEXP           VARCHAR2(256 CHAR),
   	FECHAEXTINI      DATE NOT NULL,
 	FECHAEXTFIN      DATE NOT NULL,
	ASUNTO           VARCHAR2(1024 CHAR) NOT NULL,
   	ORDEN			NUMBER(5) NOT NULL,
  	VALIDADA 		VARCHAR2(1 CHAR) NOT NULL,
  	INFO             CLOB
  	);

CREATE TABLE ASGFPZTRVALSERIE(
	IDVALSERIE 		VARCHAR2(32 CHAR) NOT NULL,
	PLAZO 			NUMBER  NOT NULL,
	IDNIVELARCHORG 	VARCHAR2(32 CHAR) NOT NULL,
	IDNIVELARCHDST 	VARCHAR2(32 CHAR) NOT NULL,
	ORDEN 			NUMBER NOT NULL
);

CREATE TABLE ASGDSIGNUMHUECO (
  IDARCHIVO 	VARCHAR2(32 CHAR) NOT NULL,
  SIGNUMHUECO  	NUMBER(16) NOT NULL
);

CREATE TABLE ASGPREVDOCUDOC (
  IDREVDOC			VARCHAR2(32 CHAR)  NOT NULL,
  IDUDOC          		VARCHAR2(32 CHAR)  NOT NULL,
  TITULO          		VARCHAR2(1024 CHAR)  NOT NULL,
  SIGNATURAUDOC   	VARCHAR2(254 CHAR)  NOT NULL,
  EXPEDIENTEUDOC  	VARCHAR2(128 CHAR),
  ESTADO          		NUMBER(2)    NOT NULL,
  FESTADO         		DATE          NOT NULL,
  OBSERVACIONES        	VARCHAR2(1024 CHAR),
  MOTIVORECHAZO 	VARCHAR2(254 CHAR),
  IDUSRGESTOR        	VARCHAR2(32 CHAR) NOT NULL,
  IDALTA			VARCHAR2(32 CHAR)
);

CREATE TABLE ASGSEDIFICIO (
  ID            VARCHAR2(32 CHAR) NOT NULL,
  NOMBRE        VARCHAR2(64 CHAR) NOT NULL,
  UBICACION     VARCHAR2(254 CHAR),
  IDARCHIVO     VARCHAR2(32 CHAR) NOT NULL
);

CREATE TABLE ASGSSALA (
  ID              		VARCHAR2(32 CHAR) NOT NULL,
  NOMBRE          		VARCHAR2(64 CHAR) NOT NULL,
  DESCRIPCION     		VARCHAR2(254 CHAR),
  IDEDIFICIO      		VARCHAR2(32 CHAR) NOT NULL,
  EQUIPOINFORMATICO 	CHAR(1 CHAR) NOT NULL
);

CREATE TABLE ASGSMESA (
  ID            VARCHAR2(32 CHAR) NOT NULL,
  CODIGO        VARCHAR2(64 CHAR) NOT NULL,
  NUMORDEN      NUMBER NOT NULL,
  IDSALA        VARCHAR2(32 CHAR) NOT NULL,
  ESTADO        CHAR(1 CHAR) NOT NULL,
  FECHAESTADO   DATE NOT NULL,
  IDUSRCSALA	VARCHAR2(32 CHAR)
);

CREATE TABLE ASGSUSRCSALA (
  ID	 	  	  			VARCHAR2(32 CHAR) NOT NULL,
  TIPODOCIDENTIFICACION     NUMBER NOT NULL,
  NUMDOCIDENTIFICACION		VARCHAR2(32 CHAR) NOT NULL,
  NOMBRE			  	    VARCHAR2(64 CHAR) NOT NULL,
  APELLIDOS			  	    VARCHAR2(254 CHAR) NOT NULL,
  NACIONALIDAD	   	  	    VARCHAR2(64 CHAR),
  TELEFONOS					VARCHAR2(128 CHAR),
  EMAIL						VARCHAR2(128 CHAR),
  DIRECCION		            VARCHAR2(254 CHAR),
  FECHAALTA				    DATE NOT NULL,
  VIGENTE					CHAR(1 CHAR) NOT NULL,
  IDSCAUSR					VARCHAR2(32 CHAR)
);

CREATE TABLE ASGSUSRCSARCH (
  IDUSRCSALA  	  VARCHAR2(32 CHAR) NOT NULL,
  IDARCHIVO       VARCHAR2(64 CHAR) NOT NULL
);

CREATE TABLE ASGSREGCSALA (
  ID		  	  		VARCHAR2(32 CHAR) NOT NULL,
  IDUSRCSALA  	  		VARCHAR2(32 CHAR) NOT NULL,
  FENTRADA	      		DATE NOT NULL,
  FSALIDA	      		DATE,
  NUMDOCIDENTIFICACION	VARCHAR2(32 CHAR) NOT NULL,
  NOMBREAPELLIDOS		VARCHAR2(254 CHAR) NOT NULL,
  IDSCAUSR	  	  		VARCHAR2(32 CHAR),
  IDARCHIVO	  	  		VARCHAR2(32 CHAR) NOT NULL,
  MESAASIGNADA			VARCHAR2(254 CHAR) NOT NULL
);

CREATE TABLE ASGTUIREEACR (
  ID			  VARCHAR2(32 CHAR)  NOT NULL,
  IDRELENTREGA    VARCHAR2(32 CHAR)  NOT NULL,
  IDUIDEPOSITO    VARCHAR2(32 CHAR),
  SIGNATURAUI     VARCHAR2(16 CHAR),
  IDFORMATO       VARCHAR2(32 CHAR) NOT NULL,
  ORDEN			  NUMBER NOT NULL,
  ESTADOCOTEJO 	  NUMBER(1) DEFAULT 1 NOT NULL,
  NOTASCOTEJO	  VARCHAR2(256 CHAR),
  DEVOLUCION	  CHAR(1 CHAR) DEFAULT 'N',
  DESCRIPCION	  VARCHAR2(256 CHAR)
);

CREATE TABLE ASGTUDOCENUIREEACR (
  ID			  VARCHAR2(32 CHAR)  NOT NULL,
  IDUDOCORIGEN    VARCHAR2(32 CHAR)  NOT NULL,
  IDRELENTREGA    VARCHAR2(32 CHAR)  NOT NULL,
  IDUNIDADDOC     VARCHAR2(32 CHAR)  NOT NULL,
  IDUIREEACR	  VARCHAR2(32 CHAR),
  ASUNTO		  VARCHAR2(1024 CHAR) NOT NULL,
  UDOCCOMPLETA	  VARCHAR2(1 CHAR) NOT NULL,
  SIGNATURAUDOC   VARCHAR2(32 CHAR),
  POSUDOCENUI     NUMBER,
  NUMEXP          VARCHAR2(256 CHAR),
  NUMPARTE        NUMBER,
  FECHAINI        VARCHAR2(64 CHAR),
  FECHAFIN        VARCHAR2(64 CHAR),
  SIGNATURAUDOCORIGEN VARCHAR2(32 CHAR),
  DESCRIPCION	  VARCHAR2(256 CHAR)
);

CREATE TABLE ASGTUDOCREEACR (
  ID			  VARCHAR2(32 CHAR)  NOT NULL,
  IDRELENTREGA    VARCHAR2(32 CHAR)  NOT NULL,
  IDUNIDADDOC     VARCHAR2(32 CHAR)  NOT NULL,
  SIGNATURAUDOC	  VARCHAR2(32 CHAR)  NOT NULL,
  IDUIDEPOSITO	  VARCHAR2(32 CHAR)  NOT NULL,
  SIGNATURAUI	  VARCHAR2(16 CHAR)  NOT NULL
);

CREATE TABLE ASGFCTLGTBLTMP(
	ID NUMERIC(5)NOT NULL,
	NOMBRETABLA VARCHAR2(16 CHAR) NOT NULL,
	IDUSUARIO VARCHAR2(32 CHAR),
	ESTADO NUMERIC(1) default 0,
	FECHA DATE
);

