-- Procedimiento para gestionar las secuencias
CREATE PROCEDURE spac_nextval (IN sequence_name VARCHAR(512), OUT sequence_id INTEGER)
LANGUAGE SQL
BEGIN 
	DECLARE SQL_STRING VARCHAR(4000);
	--DECLARE STMT STATEMENT;
	DECLARE CUR CURSOR WITH HOLD FOR STMT;

	SET SQL_STRING = 'SELECT NEXTVAL FOR ' || sequence_name || ' FROM SYSIBM.SYSDUMMY1 FETCH FIRST 1 ROWS ONLY';

	PREPARE STMT FROM SQL_STRING;
	OPEN CUR;
	FETCH FROM CUR INTO sequence_id ;
	CLOSE CUR;
END
@