----------------
-- SECUENCIAS --
----------------

CREATE SEQUENCE sgl_sq_id_obras_menores AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE sgq_sq_id_quejas AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE sgs_sq_id_subvenciones AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_spac_tbl_010 AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_spac_tbl_011 AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_spac_tbl_012 AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_spac_tbl_013 AS INTEGER NO CACHE ORDER;