--
-- Secuencias
--

CREATE SEQUENCE spac_sq_datos_tarjeta_minus AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_forma_adjudicacion AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_id_actividad_clasifica AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_id_actividad_no_clasif AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_id_camb_titular_la AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_id_cert_urbanistico AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_id_clasificacion_activ AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_id_contrato AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_id_lotes AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_id_obra_menor AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_id_oferta AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_id_sancion AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_id_vado AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_id_vldtbl_san_califica AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_id_vldtbl_san_grado AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_rebaje_acera AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_reclamacion AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_tipo_contrato AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_tipo_tecnico AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_tipo_vado AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_visto_bueno AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_vldtbl_calif_suelo AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_vldtbl_clasif_suelo AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_vldtbl_tipo_desti AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_vldtbl_tipo_reclam AS INTEGER NO CACHE ORDER;
CREATE SEQUENCE spac_sq_vldtbl_tipo_tarjeta AS INTEGER NO CACHE ORDER;