--  Crear tablas para el conector de organización

CREATE TABLE dbo.AOESTRORG (
	ID VARCHAR(32) NOT NULL,
	CODIGO VARCHAR(64) NOT NULL,
	NOMBRE VARCHAR(254) NOT NULL,
	TIPO INT NOT NULL,
	NIVEL INT NOT NULL,
	IDORGPADRE VARCHAR(32),
	ESTADO INT NOT NULL,
	FINICIOVIGENCIA DATETIME,
	FFINVIGENCIA DATETIME,
	DESCRIPCION VARCHAR(254)
);

CREATE TABLE dbo.AOUSR (
	ID VARCHAR(64) NOT NULL,
	DIRECCION VARCHAR(254),
	EMAIL VARCHAR(254),
	NOMBRE VARCHAR(64),
	APELLIDOS VARCHAR(128),
	NOMBREUSUARIO VARCHAR(64) NOT NULL,
	PASSWORD VARCHAR(64) NOT NULL
);

CREATE TABLE dbo.AOUSRORGV (
	IDUSUARIO VARCHAR(64) NOT NULL,
	NOMBREUSUARIO VARCHAR(254) NOT NULL,
	IDORGANO VARCHAR(32) NOT NULL
);

-- Si las tablas se meten en un schema distinto del de archivo habría que ejecutar las siguientes sentencias:

-- CREATE TABLE ITDGUIDGEN (
--	cnode varchar(12),
--	clpid int
--);

-- INSERT INTO ITDGUIDGEN (CNODE, CLPID) VALUES ('000000000000', 1);