-- /***************************/
-- /* Actualización 4.5->4.7            */
-- /***************************/

INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.5->4.7',now());

DROP FUNCTION UPDATECODREF ( VARCHAR(32), VARCHAR(1), VARCHAR(1) );
DROP FUNCTION GETFINCODREFPADRE (VARCHAR(32),VARCHAR(1));
DROP FUNCTION GETCODREF(VARCHAR(32), VARCHAR(1));

CREATE TABLE ASGFCTLGTBLTMP(
	ID NUMERIC(5)NOT NULL,
	NOMBRETABLA VARCHAR(16) NOT NULL,
	IDUSUARIO VARCHAR(32),
	ESTADO NUMERIC(1) default 0,
	FECHA DATE
);

CREATE UNIQUE INDEX ASGFCTLGTBLTMP1 ON ASGFCTLGTBLTMP(ID);
CREATE UNIQUE INDEX ASGFCTLGTBLTMP2 ON ASGFCTLGTBLTMP(NOMBRETABLA);

CREATE UNIQUE INDEX ASGFFONDO2 ON ASGFFONDO(CODARCHIVO,IDENTPRODUCTORA);
