ALTER session SET nls_length_semantics=CHAR;

CREATE SEQUENCE SEQ_INFO
INCREMENT BY 1
MINVALUE 1
MAXVALUE 100000000000
START WITH 1;

CREATE TABLE AANAUDITACCION (
  MODULO	NUMBER  NOT NULL,
  ACCION  	NUMBER  NOT NULL,
  NIVEL		NUMBER  NOT NULL
  );

CREATE TABLE AANAUDITUSR (
  TIPOAUDITADO	VARCHAR2(32) NOT NULL,
  IDAUDITADO    VARCHAR2(32) NOT NULL,
  NIVEL         NUMBER NOT NULL
  );

CREATE TABLE AADATOSTRAZA (
  ID          VARCHAR2(32) NOT NULL,
  IDTRAZA     VARCHAR2(32) NOT NULL,
  CONTENIDO   CLOB,
  TIPOOBJETO  NUMBER,
  IDOBJETO    VARCHAR2(32)
  );

CREATE TABLE AATRAZA (
  ID         VARCHAR2(32)	NOT NULL,
  MODULO     NUMBER        	NOT NULL,
  ACCION     NUMBER			NOT NULL,
  TIMESTAMP  DATE			NOT NULL,
  DIRIP      VARCHAR2(32)	NOT NULL,
  IDUSUARIO  VARCHAR2(32),
  CODERROR   NUMBER
  );

CREATE TABLE AASESION (
  IDUSUARIO  VARCHAR2(32)	NOT NULL,
  KEEPALIVE  DATE			NOT NULL,
  ID         VARCHAR2(64)	NOT NULL
  );

CREATE TABLE ADAREA (
  ID           VARCHAR2(32)  NOT NULL,
  NOMBRE       VARCHAR2(128) NOT NULL,
  TIPONORMA    INTEGER       DEFAULT 0 NOT NULL,
  DESCRIPCION  VARCHAR2(254)
  );

CREATE TABLE ADCAMPODATO (
  ID           VARCHAR2(32)  NOT NULL,
  NOMBRE       VARCHAR2(64)  NOT NULL,
  TIPO         INTEGER       NOT NULL,
  TIPONORMA    INTEGER       NOT NULL,
  IDAREA       VARCHAR2(32),
  IDTBLPADRE   VARCHAR2(32),
  POSENTBL     INTEGER,
  ETIQUETAXML  VARCHAR2(128)  NOT NULL,
  DESCRIPCION  VARCHAR2(254)
  );

CREATE TABLE ADCAMPOTBL (
  ID           VARCHAR2(32)  NOT NULL,
  NOMBRE       VARCHAR2(64)  NOT NULL,
  TIPONORMA    INTEGER       NOT NULL,
  IDAREA       VARCHAR2(32),
  ETIQUETAXML  VARCHAR2(128)  NOT NULL,
  ETIQXMLFILA  VARCHAR2(128)  NOT NULL,
  DESCRIPCION  VARCHAR2(254)
  );

CREATE TABLE ADCTLGLISTAD (
  ID                 VARCHAR2(32)  	NOT NULL,
  NOMBRE             VARCHAR2(64)  	NOT NULL,
  TIPO               INTEGER		NOT NULL,
  TIPODESCRIPTOR     INTEGER  		NOT NULL,
  IDFICHADESCRPREF   VARCHAR2(32),
  IDFICHACLFDOCPREF  VARCHAR2(32),
  IDREPECMPREF         VARCHAR2(32),
  DESCRIPCION        VARCHAR2(254)
  );

CREATE TABLE ADCTLGTBLVLD (
  ID           	VARCHAR2(32)  NOT NULL,
  NOMBRE       	VARCHAR2(64)  NOT NULL,
  DESCRIPCION  	VARCHAR2(254),
  USOINTERNO	CHAR (1)
  );

CREATE TABLE ADDESCRIPTOR (
  ID              VARCHAR2(32)  NOT NULL,
  NOMBRE          VARCHAR2(512)  NOT NULL,
  IDLISTA         VARCHAR2(32)  NOT NULL,
  TIPO            INTEGER       NOT NULL,
  ESTADO          INTEGER       NOT NULL,
  IDSISTEXT       VARCHAR2(64),
  IDDESCRSISTEXT  VARCHAR2(32),
  TIMESTAMP       DATE          NOT NULL,
  IDFICHADESCR    VARCHAR2(32),
  TIENEDESCR      CHAR (1),
  EDITCLFDOCS     CHAR (1),
  IDREPECM          VARCHAR2(32),
  NIVELACCESO     NUMBER (2) NOT NULL,
  IDLCA           VARCHAR2(32)
  );

CREATE TABLE ADFICHA (
  ID           VARCHAR2(32) NOT NULL,
  NOMBRE       VARCHAR2(64) NOT NULL,
  DEFINICION   CLOB         NOT NULL,
  TIPONORMA    INTEGER		NOT NULL,
  TIPONIVEL    INTEGER      NOT NULL,
  SUBTIPONIVEL    INTEGER   DEFAULT 0 NOT NULL,
  DESCRIPCION  VARCHAR2(254)
  );

CREATE TABLE ADFMTFICHA (
  ID           VARCHAR2(32)  NOT NULL,
  NOMBRE       VARCHAR2(128)  NOT NULL,
  DEFINICION   CLOB          NOT NULL,
  IDFICHA      VARCHAR2(32)  NOT NULL,
  TIPO         NUMBER (1)    NOT NULL,
  NIVELACCESO  NUMBER (2)    NOT NULL,
  IDLCA        VARCHAR2(32),
  DESCRIPCION  VARCHAR2(254)
  );

CREATE TABLE ADFMTPREF (
  IDFICHA    VARCHAR2(32)  NOT NULL,
  IDUSUARIO  VARCHAR2(32)  NOT NULL,
  TIPOFMT    NUMBER (1)    NOT NULL,
  IDFMT      VARCHAR2(32)  NOT NULL
  );

CREATE TABLE ADOCCLASIFCF (
  ID            VARCHAR2(32)  NOT NULL,
  NOMBRE        VARCHAR2(128)  NOT NULL,
  IDCLFPADRE    VARCHAR2(32),
  IDELEMENTOCF  VARCHAR2(32)  NOT NULL,
  MARCAS        INTEGER       NOT NULL,
  ESTADO        INTEGER       NOT NULL,
  DESCRIPCION   VARCHAR2(512)
  );

CREATE TABLE ADOCCLASIFDESCR (
  ID            VARCHAR2(32)  NOT NULL,
  NOMBRE        VARCHAR2(128)  NOT NULL,
  IDCLFPADRE    VARCHAR2(32),
  IDDESCR       VARCHAR2(32)  NOT NULL,
  MARCAS        INTEGER       NOT NULL,
  ESTADO        INTEGER       NOT NULL,
  DESCRIPCION   VARCHAR2(254)
  );

CREATE TABLE ADOCDOCUMENTOCF (
  ID            VARCHAR2(32)  NOT NULL,
  NOMBRE        VARCHAR2(128)  NOT NULL,
  IDCLFPADRE    VARCHAR2(32),
  IDELEMENTOCF  VARCHAR2(32)  NOT NULL,
  TAMANOFICH    FLOAT          NOT NULL,
  NOMBREORGFICH VARCHAR2(254) NOT NULL,
  EXTFICH       VARCHAR2(16)  NOT NULL,
  IDEXTDEPOSITO VARCHAR2(32),
  IDFICH        VARCHAR2(128)  NOT NULL,
  ESTADO        INTEGER       NOT NULL,
  DESCRIPCION   VARCHAR2(254),
  IDREPECM      VARCHAR2(32)

  );

CREATE TABLE ADOCDOCUMENTODESCR (
  ID            VARCHAR2(32)  NOT NULL,
  NOMBRE        VARCHAR2(128)  NOT NULL,
  IDCLFPADRE    VARCHAR2(32),
  IDDESCR       VARCHAR2(32)  NOT NULL,
  TAMANOFICH    FLOAT          NOT NULL,
  NOMBREORGFICH VARCHAR2(254) NOT NULL,
  EXTFICH       VARCHAR2(16)  NOT NULL,
  IDFICH        VARCHAR2(128)  NOT NULL,
  ESTADO        INTEGER       NOT NULL,
  DESCRIPCION   VARCHAR2(254),
  IDREPECM      VARCHAR2(32)
  );

CREATE TABLE ADOCFICHACLF (
  ID           VARCHAR2(32)  NOT NULL,
  NOMBRE       VARCHAR2(64)  NOT NULL,
  DEFINICION   CLOB          NOT NULL,
  DESCRIPCION  VARCHAR2(254)
  );

CREATE TABLE ADOCTCAPTURA (
  ID           VARCHAR2(32)  NOT NULL,
  TIPOOBJ      INTEGER        NOT NULL,
  IDOBJ        VARCHAR2(32)  NOT NULL,
  IDUSRCAPTURA VARCHAR2(32)  NOT NULL,
  CODREFOBJ    VARCHAR2(1024),
  TITULOOBJ    VARCHAR2(1024) NOT NULL,
  ESTADO       INTEGER        NOT NULL,
  FECHAESTADO  DATE           NOT NULL,
  OBSERVACIONES VARCHAR2(254),
  MOTIVOERROR  VARCHAR2(254)
  );

CREATE TABLE ADPCDOCUMENTOVIT (
  ID           VARCHAR2(32)  NOT NULL,
  IDBDTERCEROS VARCHAR2(64)  NOT NULL,
  NUMIDENTIDAD VARCHAR2(32),
  IDENTIDAD    VARCHAR2(254),
  IDTIPODOCVIT VARCHAR2(32)  NOT NULL,
  FECHACAD     DATE,
  ESTADODOCVIT INTEGER        NOT NULL,
  FECHACR      DATE           NOT NULL,
  IDUSUARIOCR  VARCHAR2(32)  NOT NULL,
  FECHAVIG     DATE,
  IDUSUARIOVIG VARCHAR2(32),
  NUMACCESOS   INTEGER        NOT NULL,
  FECHAULTACCESO DATE,
  TAMANOFICH   FLOAT          NOT NULL,
  NOMBREORGFICH VARCHAR2(254) NOT NULL,
  EXTFICH      VARCHAR2(16)  NOT NULL,
  IDFICH       VARCHAR2(128)  NOT NULL,
  OBSERVACIONES VARCHAR2(254),
  IDREPECM		VARCHAR2(32)
  );

CREATE TABLE ADPCUSODOCVIT (
  IDDOCVIT     VARCHAR2(32)  NOT NULL,
  IDEXP        VARCHAR2(254)  NOT NULL,
  IDSIST       VARCHAR2(254)  NOT NULL,
  FECHAUSO     DATE            NOT NULL,
  USUARIO      VARCHAR2(254)  NOT NULL
  );

CREATE TABLE ADPCTIPODOCVIT (
  ID           VARCHAR2(32)  NOT NULL,
  NOMBRE       VARCHAR2(254)  NOT NULL,
  DESCRIPCION  VARCHAR2(512)
  );

CREATE TABLE ADPCTIPODOCPROC (
  IDTIPODOC    VARCHAR2(32)  NOT NULL,
  IDPROC       VARCHAR2(254)  NOT NULL
  );

CREATE TABLE ADTEXTTBLVLD (
  ID        VARCHAR2(32)  NOT NULL,
  VALOR     VARCHAR2(254)  NOT NULL,
  IDTBLVLD  VARCHAR2(32)  NOT NULL
  );

CREATE TABLE ADUSOOBJETO (
  IDOBJ           VARCHAR2(32)  NOT NULL,
  TIPOOBJ         INTEGER       NOT NULL,
  IDOBJUSUARIO    VARCHAR2(32)  NOT NULL,
  TIPOOBJUSUARIO  INTEGER       NOT NULL
  );

CREATE TABLE ADVCFECHACF (
  IDELEMENTOCF  VARCHAR2(32)  NOT NULL,
  IDCAMPO       VARCHAR2(32)  NOT NULL,
  VALOR         VARCHAR2(64),
  FECHAINI      DATE,
  FECHAFIN      DATE,
  CALIFICADOR   VARCHAR2(32),
  ORDEN         INTEGER       NOT NULL,
  TIMESTAMP     DATE          NOT NULL,
  FORMATO       VARCHAR2(16),
  SEP           CHAR (1)
  );

CREATE TABLE ADVCFECHADESCR (
  IDDESCR      VARCHAR2(32)  NOT NULL,
  IDCAMPO      VARCHAR2(32)  NOT NULL,
  VALOR        VARCHAR2(64),
  FECHAINI     DATE,
  FECHAFIN     DATE,
  FORMATO      VARCHAR2(16),
  SEP          CHAR (1),
  CALIFICADOR  VARCHAR2(32),
  ORDEN        INTEGER       NOT NULL,
  TIMESTAMP    DATE          NOT NULL
  );

CREATE TABLE ADVCNUMCF (
  IDELEMENTOCF  VARCHAR2(32)  NOT NULL,
  IDCAMPO       VARCHAR2(32)  NOT NULL,
  VALOR         NUMBER (20,4) NOT NULL,
  ORDEN         INTEGER       NOT NULL,
  TIMESTAMP     DATE          NOT NULL,
  TIPOMEDIDA    INTEGER,
  UNIDADMEDIDA  VARCHAR2(16)
  );

CREATE TABLE ADVCNUMDESCR (
  IDDESCR       VARCHAR2(32)  NOT NULL,
  IDCAMPO       VARCHAR2(32)  NOT NULL,
  VALOR         NUMBER (20,4) NOT NULL,
  ORDEN         INTEGER       NOT NULL,
  TIMESTAMP     DATE          NOT NULL,
  TIPOMEDIDA    INTEGER,
  UNIDADMEDIDA  VARCHAR2(16)
  );

CREATE TABLE ADVCREFCF (
  IDELEMENTOCF  VARCHAR2(32)  NOT NULL,
  IDCAMPO       VARCHAR2(32)  NOT NULL,
  TIPOOBJREF    INTEGER       NOT NULL,
  IDOBJREF      VARCHAR2(32)  NOT NULL,
  ORDEN         INTEGER       NOT NULL,
  TIMESTAMP     DATE          NOT NULL
  );

CREATE TABLE ADVCREFDESCR (
  IDDESCR     VARCHAR2(32)  NOT NULL,
  IDCAMPO     VARCHAR2(32)  NOT NULL,
  TIPOOBJREF  INTEGER       NOT NULL,
  IDOBJREF    VARCHAR2(32)  NOT NULL,
  ORDEN       INTEGER       NOT NULL,
  TIMESTAMP   DATE          NOT NULL
  );

CREATE TABLE ADVCTEXTCF (
  IDELEMENTOCF  VARCHAR2(32)  NOT NULL,
  IDCAMPO       VARCHAR2(32)  NOT NULL,
  VALOR         VARCHAR2(254)  NOT NULL,
  ORDEN         INTEGER       NOT NULL,
  TIMESTAMP     DATE          NOT NULL
  );


CREATE TABLE ADVCTEXTDESCR (
  IDDESCR    VARCHAR2(32)  NOT NULL,
  IDCAMPO    VARCHAR2(32)  NOT NULL,
  VALOR      VARCHAR2(254)  NOT NULL,
  ORDEN      INTEGER       NOT NULL,
  TIMESTAMP  DATE          NOT NULL
  );

CREATE TABLE ADVCTEXTLCF (
  IDELEMENTOCF  VARCHAR2(32)  NOT NULL,
  IDCAMPO       VARCHAR2(32)  NOT NULL,
  VALOR         CLOB          NOT NULL,
  ORDEN         INTEGER       NOT NULL,
  TIMESTAMP     DATE          NOT NULL
  );


CREATE TABLE ADVCTEXTLDESCR (
  IDDESCR    VARCHAR2(32)  NOT NULL,
  IDCAMPO    VARCHAR2(32)  NOT NULL,
  VALOR      CLOB          NOT NULL,
  ORDEN      INTEGER       NOT NULL,
  TIMESTAMP  DATE          NOT NULL
  );


CREATE TABLE AGARCHIVO (
  ID      VARCHAR2(32) NOT NULL,
  CODIGO  VARCHAR2(32) NOT NULL,
  NOMBRE  VARCHAR2(128) NOT NULL,
  IDNIVEL  VARCHAR2(32) NOT NULL,
  IDRECEPTORDEFECTO VARCHAR2(32),
  NOMBRECORTO VARCHAR2(25) NOT NULL,
  TIPOSIGNATURACION INTEGER DEFAULT 1 NOT NULL
  );

CREATE TABLE AGNIVELARCHIVO(
  ID VARCHAR2(32) NOT NULL,
  NOMBRE VARCHAR2(64) NOT NULL,
  DESCRIPCION VARCHAR2(254),
  ORDEN NUMBER NOT NULL
  );

CREATE TABLE AGFORMATO (
  ID          VARCHAR2(32)  NOT NULL,
  NOMBRE      VARCHAR2(64)  NOT NULL,
  TIPO        NUMBER (1)    NOT NULL,
  ESMULTIDOC  NUMBER (1)    NOT NULL,
  REGULAR     NUMBER (1)    NOT NULL,
  LONGITUD    NUMBER (8,2),
  XINFO       VARCHAR2(1024),
  VIGENTE     NUMBER (1)    NOT NULL
  );

CREATE TABLE AGOBJBLOQUEO (
  IDOBJ      VARCHAR2(32)  NOT NULL,
  TIPOOBJ    NUMBER        NOT NULL,
  MODULO     NUMBER        NOT NULL,
  TS         DATE          NOT NULL,
  IDUSUARIO  VARCHAR2(32)  NOT NULL
  );

CREATE TABLE ASCAGRUPO (
  ID           VARCHAR2(32)  NOT NULL,
  NOMBRE       VARCHAR2(254)  NOT NULL,
  IDARCHIVO    VARCHAR2(32),
  DESCRIPCION  VARCHAR2(254),
  INFO 		   VARCHAR2(1024) DEFAULT ''
  );

CREATE TABLE ASCALISTCA (
  ID           VARCHAR2(32)  NOT NULL,
  NOMBRE       VARCHAR2(254) NOT NULL,
  TIPO         NUMBER (1) NOT NULL,
  DESCRIPCION  VARCHAR2(512) NOT NULL
  );

CREATE TABLE ASCAORGANO (
  ID                 VARCHAR2(32)  NOT NULL,
  CODIGO             VARCHAR2(64) NOT NULL,
  NOMBRE             VARCHAR2(254) NOT NULL,
  NOMBRELARGO        VARCHAR2(1024),
  IDARCHIVORECEPTOR  VARCHAR2(32) NOT NULL,
  SISTEXTGESTOR      VARCHAR2(32) NOT NULL,
  IDORGSEXTGESTOR    VARCHAR2(64) NOT NULL,
  VIGENTE            CHAR (1) NOT NULL,
  DESCRIPCION        VARCHAR2(254)
  );

CREATE TABLE ASCAPERMGENROL (
  IDROL       VARCHAR2(32) NOT NULL,
  TIPOMODULO  NUMBER (2) NOT NULL,
  PERM        NUMBER (4) NOT NULL
  );

CREATE TABLE ASCAPERMLISTCA (
  IDLISTCA  VARCHAR2(32) NOT NULL,
  TIPODEST  NUMBER (1) NOT NULL,
  IDDEST    VARCHAR2(64) NOT NULL,
  PERM      NUMBER (4) NOT NULL
  );

CREATE TABLE ASCAROL (
  ID           VARCHAR2(32)  NOT NULL,
  NOMBRE       VARCHAR2(64) NOT NULL,
  TIPOMODULO   NUMBER (2),
  DESCRIPCION  VARCHAR2(254)
  );

CREATE TABLE ASCAROLUSR (
  IDROL       VARCHAR2(32) NOT NULL,
  TIPOMODULO  NUMBER (2) NOT NULL,
  IDUSUARIO   VARCHAR2(32) NOT NULL
  );

CREATE TABLE ASCAUSRGRP (
  IDUSUARIO  VARCHAR2(32) NOT NULL,
  IDGRUPO    VARCHAR2(32) NOT NULL
  );

CREATE TABLE ASCAUSRORG (
  IDUSUARIO  VARCHAR2(32) NOT NULL,
  IDORGANO   VARCHAR2(32) NOT NULL,
  FECHAINI   DATE,
  FECHAFIN   DATE
  );

CREATE TABLE ASCAUSUARIO (
  ID               VARCHAR2(32)  NOT NULL,
  NOMBRE           VARCHAR2(254) NOT NULL,
  APELLIDOS        VARCHAR2(254),
  EMAIL            VARCHAR2(254),
  DIRECCION        VARCHAR2(254),
  TIPO             CHAR (1) NOT NULL,
  HABILITADO       CHAR (1) NOT NULL,
  FMAXVIGENCIA     DATE,
  IDUSRSEXTGESTOR  VARCHAR2(64) NOT NULL,
  IDUSRSISTORG     VARCHAR2(64),
  DESCRIPCION      VARCHAR2(254)
  );

CREATE TABLE ASGDDEPOSITO (
  ID              VARCHAR2(32)  NOT NULL,
  IDTIPOELEMENTO  VARCHAR2(32)  NOT NULL,
  NUMORDEN        NUMBER NOT NULL,
  NOMBRE          VARCHAR2(64) NOT NULL,
  UBICACION       VARCHAR2(255) NOT NULL,
  MARCAS          NUMBER (10) NOT NULL,
  IDARCHIVO VARCHAR2(32) NOT NULL
  );

CREATE TABLE ASGDDEPOSITOELECTRONICO (
  ID              VARCHAR2(32)  NOT NULL,
  IDEXT           VARCHAR2(64)  NOT NULL,
  NOMBRE          VARCHAR2(64)  NOT NULL,
  DESCRIPCION     VARCHAR2(254),
  LOCALIZACION    CLOB           NOT NULL,
  USOFIRMA        VARCHAR2(1)  DEFAULT 'N' NOT NULL
  );

CREATE TABLE ASGDELEMASIG (
  ID              VARCHAR2(32)  NOT NULL,
  NOMBRE          VARCHAR2(64)  NOT NULL,
  IDTIPOELEMENTO  VARCHAR2(32)  NOT NULL,
  NUMORDEN        NUMBER        NOT NULL,
  IDELEMNAPADRE   VARCHAR2(32)  NOT NULL,
  IDDEPOSITO      VARCHAR2(32)  NOT NULL,
  LONGITUD        NUMBER (8,2)    NOT NULL,
  IDFORMATO       VARCHAR2(32)  NOT NULL,
  NUMHUECOS       NUMBER (5)    NOT NULL,
  CODORDEN        VARCHAR2(50) DEFAULT ' ' NOT NULL
  );

CREATE TABLE ASGDELEMNOASIG (
  ID              VARCHAR2(32)  NOT NULL,
  IDTIPOELEMENTO  VARCHAR2(32)  NOT NULL,
  NUMORDEN        NUMBER    NOT NULL,
  IDDEPOSITO      VARCHAR2(32)  NOT NULL,
  NOMBRE          VARCHAR2(64) NOT NULL,
  IDPADRE         VARCHAR2(32),
  MARCAS          NUMBER (10) NOT NULL,
  CODORDEN        VARCHAR2(50) DEFAULT ' ' NOT NULL
  );

CREATE TABLE ASGDHUECO (
  IDELEMAPADRE    VARCHAR2(32)  NOT NULL,
  IDDEPOSITO      VARCHAR2(32)  NOT NULL,
  NUMORDEN        NUMBER        NOT NULL,
  ESTADO          CHAR (1) NOT NULL,
  IDFORMATO       VARCHAR2(32) NOT NULL,
  IDUINSTALACION  VARCHAR2(32),
  IDRELENTREGA    VARCHAR2(32),
  FECHAESTADO     DATE NOT NULL,
  PATH            VARCHAR2(512) NOT NULL,
  ORDENENRELACION  NUMBER        DEFAULT 0,
  CODORDEN        VARCHAR2(50) DEFAULT ' ' NOT NULL ,
  TIPOORD         NUMBER(5) DEFAULT 1 NOT NULL,
  NUMERACION 	  VARCHAR2(16),
  MARCAS 		  NUMBER(2) DEFAULT 0 NOT NULL,
  IDUIREEACR	  VARCHAR2(32)
  );

CREATE TABLE ASGDSIGNUMORDEN (
  IDTIPOELEMPADRE  VARCHAR2(32),
  IDELEMPADRE      VARCHAR2(32),
  IDTIPOELEMENTO   VARCHAR2(32) NOT NULL,
  NUMORDEN         NUMBER  NOT NULL
  );

CREATE TABLE ASGDTIPOELEMENTO (
  ID           VARCHAR2(32)  NOT NULL,
  NOMBRE       VARCHAR2(64)  NOT NULL,
  NOMBREABREV  VARCHAR2(16),
  IDPADRE      VARCHAR2(32),
  ASIGNABLE    NUMBER (1)    NOT NULL,
  DESCRIPCION  VARCHAR2(254),
  CARACTERORDEN CHAR(1) DEFAULT ' ' NOT NULL ,
  TIPOORD      NUMBER(5) DEFAULT 1 NOT NULL
  );

CREATE TABLE ASGDUDOCENUI (
  IDUNIDADDOC     VARCHAR2(32),
  IDUINSTALACION  VARCHAR2(32)  NOT NULL,
  POSUDOCENUI     NUMBER (5)    NOT NULL,
  SIGNATURAUDOC   VARCHAR2(32)  NOT NULL,
  IDENTIFICACION  VARCHAR2(254)  NOT NULL,
  IDUDOCRE        VARCHAR2(32),
  DESCRIPCION     VARCHAR2(254)
  );

CREATE TABLE ASGDUINSTALACION (
  ID              VARCHAR2(32)  NOT NULL,
  IDFORMATO       VARCHAR2(32)  NOT NULL,
  SIGNATURAUI     VARCHAR2(16)  NOT NULL,
  IDENTIFICACION  VARCHAR2(254)  NOT NULL,
  MARCASBLOQUEO   NUMBER(10) DEFAULT 0 NOT NULL,
  FCREACION 	  DATE DEFAULT SYSDATE NOT NULL
  );

CREATE TABLE ASGDHISTUINSTALACION(
  ID              VARCHAR2(32) NOT NULL,
  IDARCHIVO       VARCHAR2(32) NOT NULL,
  IDFORMATO       VARCHAR2(32) NOT NULL,
  SIGNATURAUI	    VARCHAR2(16) NOT NULL,
  IDENTIFICACION  VARCHAR2(254)	NOT NULL,
  FELIMINACION    DATE NOT NULL,
  MOTIVO	        NUMBER(3) NOT NULL
  );

CREATE TABLE ASGFELEMENTOCF (
  ID             VARCHAR2(32)  NOT NULL,
  TIPO           NUMBER (1) NOT NULL,
  IDNIVEL        VARCHAR2(32) NOT NULL,
  CODIGO         VARCHAR2(128),
  TITULO         VARCHAR2(1024) NOT NULL,
  IDPADRE        VARCHAR2(32),
  IDFONDO        VARCHAR2(32),
  CODREFFONDO    VARCHAR2(254),
  FINALCODREFPADRE  VARCHAR2(1024),
  CODREFERENCIA  VARCHAR2(1024),
  ESTADO         NUMBER (1) NOT NULL,
  IDELIMINACION  VARCHAR2(32),
  IDFICHADESCR   VARCHAR2(32),
  TIENEDESCR     CHAR (1),
  EDITCLFDOCS	  CHAR (1),
  IDREPECM			  VARCHAR2(32),
  IDARCHIVO      VARCHAR2(32),
  NIVELACCESO    NUMBER (2) NOT NULL,
  IDLCA          VARCHAR2(32),
  SUBTIPO		 NUMBER(5) DEFAULT 0 NOT NULL,
  ORDPOS 		 VARCHAR2(32)
  );

CREATE TABLE ASGFENTPRODUCTORA (
  CODIGO          VARCHAR2(32)  NOT NULL,
  TIPO            NUMBER (1) NOT NULL,
  SISTGESTORORG   VARCHAR2(32),
  IDENTPRODSGORG  VARCHAR2(64),
  IDDESCR         VARCHAR2(32) NOT NULL
  );

CREATE TABLE ASGFESTRUCTJNIVCF (
  IDNIVELPADRE    VARCHAR2(32) NOT NULL,
  TIPONIVELPADRE  NUMBER (1) NOT NULL,
  IDNIVELHIJO     VARCHAR2(32) NOT NULL,
  TIPONIVELHIJO   NUMBER (1) NOT NULL
  );

CREATE TABLE ASGFFONDO (
  CODPAIS          VARCHAR2(16),
  CODCOMUNIDAD     VARCHAR2(16),
  CODARCHIVO       VARCHAR2(32),
  TIPO             NUMBER (1),
  IDENTPRODUCTORA  VARCHAR2(32),
  IDELEMENTOCF     VARCHAR2(32)  NOT NULL
  );

CREATE TABLE ASGFNIVELCF (
  ID                VARCHAR2(32)  NOT NULL,
  NOMBRE            VARCHAR2(64)  NOT NULL,
  TIPO              NUMBER (1)    NOT NULL,
  IDFICHADESCRPREF  VARCHAR2(32),
  IDFICHACLFDOCPREF VARCHAR2(32),
  IDREPECMPREF 		  VARCHAR2(32),
  SUBTIPO NUMBER(5) DEFAULT 0 NOT NULL
  );

CREATE TABLE ASGFORGPROD (
  IDDESCR        VARCHAR2(32)  NOT NULL,
  IDORG          VARCHAR2(32)  NOT NULL,
  IDENTPRODINST  VARCHAR2(32)  NOT NULL
  );

CREATE TABLE ASGFPRODSERIE (
  IDSERIE          VARCHAR2(32) NOT NULL,
  IDPROCEDIMIENTO  VARCHAR2(32),
  IDPRODUCTOR      VARCHAR2(32) NOT NULL,
  TIPOPRODUCTOR    NUMBER NOT NULL,
  FECHAINICIO      DATE NOT NULL,
  FECHAFINAL       DATE,
  IDLCAPREF        VARCHAR2(32),
  MARCAS NUMBER(10) DEFAULT 0
  );

CREATE TABLE ASGFSERIE (
  IDELEMENTOCF         VARCHAR2(32)  NOT NULL,
  IDFONDO              VARCHAR2(32)   NOT NULL,
  ESTADOSERIE          NUMBER (2),
  FECHAESTADO          DATE NOT NULL,
  ULTIMOESTADOAUTORIZ  NUMBER (2),
  IDUSRGESTOR          VARCHAR2(32),
  FEXTREMAINICIAL      DATE,
  FEXTREMAFINAL        DATE,
  IDPROCEDIMIENTO      VARCHAR2(32),
  TIPOPROCEDIMIENTO	  NUMBER(1),
  NUMUNIDADDOC         NUMBER (10)  NOT NULL,
  NUMUINSTALACION      NUMBER (10)  NOT NULL,
  VOLUMEN		NUMBER  NOT NULL,
  IDENTIFICACION       CLOB,
  OBSERVACIONES        VARCHAR2(254),
  INFOFICHAUDOCREPECM CLOB
  );

CREATE TABLE ASGFVOLUMENSERIE (
  IDSERIE VARCHAR2(32) NOT NULL,
  TIPODOCUMENTAL VARCHAR2(254) NOT NULL,
  CANTIDAD NUMBER NOT NULL
  );

CREATE TABLE ASGFSOLICITUDSERIE (
  ID                VARCHAR2(32) 	NOT NULL,
  IDSERIE           VARCHAR2(32),
  ETIQUETASERIE     VARCHAR2(254) 	NOT NULL,
  TIPO              NUMBER (1) 		NOT NULL,
  FECHA             DATE 			NOT NULL,
  INFO              VARCHAR2(2000),
  MOTIVOSOLICITUD   VARCHAR2(254),
  IDUSRSOLICITANTE  VARCHAR2(32) 	NOT NULL,
  ESTADO            NUMBER (1) 		NOT NULL,
  FECHAESTADO       DATE 			NOT NULL,
  IDUSRGESTOR       VARCHAR2(32),
  MOTIVORECHAZO     VARCHAR2(254)
  );

CREATE TABLE ASGFUNIDADDOC (
  IDELEMENTOCF      VARCHAR2(32) NOT NULL,
  IDSERIE           VARCHAR2(32) NOT NULL,
  IDFONDO           VARCHAR2(32) NOT NULL,
  TIPODOCUMENTAL	  VARCHAR2(254),
  NUMEXP            VARCHAR2(256),
  CODSISTPRODUCTOR  VARCHAR2(16),
  MARCASBLOQUEO     NUMBER DEFAULT 0 NOT NULL
  );

CREATE TABLE ASGFSNSEC (
  NUMSEC  NUMBER (10)   NOT NULL
  );

CREATE TABLE ASGFNUMSECVAL (
  IDSERIE  VARCHAR2(32) NOT NULL,
  NUMSEC   NUMBER(10)  NOT NULL
  );

CREATE TABLE ASGFNUMSECSEL (
  IDSERIE  VARCHAR2(32)  NOT NULL,
  NUMSEC   NUMBER (10) NOT NULL
  );

CREATE TABLE ASGFVALSERIE (
  ID                   VARCHAR2(32)  NOT NULL,
  IDSERIE              VARCHAR2(32)  NOT NULL,
  TITULO               VARCHAR2(254) NOT NULL,
  ESTADO               NUMBER (1)    NOT NULL,
  FECHAESTADO          DATE          NOT NULL,
  MOTIVORECHAZO        VARCHAR2(254),
  ORDSERIEPRIMERNIVEL  NUMBER,
  ORDSERIESEGNIVEL     NUMBER,
  SERIESPRECEDENTES    CLOB,
  SERIESRELACIONADAS   CLOB,
  DOCSRECOPILATORIOS   VARCHAR2(1024),
  VALORADMTIPO         NUMBER,
  VALORADMVIG          NUMBER,
  VALORADMJUST         VARCHAR2(1024),
  VALORLEGALTIPO       NUMBER,
  VALORLEGALVIG        NUMBER,
  VALORLEGALJUST       VARCHAR2(1024),
  VALORINFTIPO         NUMBER,
  VALORINFJUST         VARCHAR2(1024),
  VALORCIENTTIPO       NUMBER,
  VALORCIENTJUST       VARCHAR2(1024),
  VALORTECNTIPO        NUMBER,
  VALORTECNJUST        VARCHAR2(1024),
  VALORCULTTIPO        NUMBER,
  VALORCULTJUST        VARCHAR2(1024),
  TECNICAMUESTREO      NUMBER,
  NUMREGISTRO          NUMBER,
  FVALIDACION          DATE,
  FEVALUACION          DATE,
  FDICTAMEN            DATE,
  VALORDICTAMEN        NUMBER,
  VALORDICTJUST	       CLOB,
  FRESOLDICTAMEN       DATE,
  BOLETINDICTAMEN      VARCHAR2(128),
  FBOLETINDICTAMEN     DATE,
  IDUSRGESTORSERIE     VARCHAR2(32) NOT NULL,
  REGIMENACCESOTIPO    NUMBER NOT NULL,
  REGIMENACCESOJUST    VARCHAR2(1024),
  REGIMENACCESOVIG     NUMBER,
  INFOSERIE CLOB,
  REGIMENACCESOSUBTIPO NUMBER(5)
  );

CREATE TABLE ASGFELIMSERIE (
  ID               VARCHAR2(32)  NOT NULL,
  IDVALORACION     VARCHAR2(32)  NOT NULL,
  IDSERIE          VARCHAR2(32)  NOT NULL,
  TITULO           VARCHAR2(254)  NOT NULL,
  ESTADO           INTEGER       NOT NULL,
  FECHAESTADO      DATE          NOT NULL,
  MOTIVORECHAZO    VARCHAR2(254),
  NOTAS            VARCHAR2(1024),
  MAXANOSVIGENCIA  INTEGER       NOT NULL,
  CONDBUSQANADIDA  VARCHAR2(1024),
  TIPOELIMINACION  INTEGER       NOT NULL,
  SELECCIONUDOC    VARCHAR2(1)  NOT NULL,
  FEJECUCION       DATE,
  FAPROBACION      DATE,
  FDESTRUCCION     DATE,
  FFINALIZACION    DATE,
  IDARCHIVO VARCHAR2(32) NOT NULL
  );

CREATE TABLE ASGFELIMUDOCCONS (
  IDELIMINACION  VARCHAR2(32)  NOT NULL,
  IDUDOC         VARCHAR2(32)  NOT NULL,
  SIGNATURAUDOC  VARCHAR2(128)  NOT NULL,
  TITULOUDOC     VARCHAR2(1024)  NOT NULL,
  FECHAINIUDOC   DATE,
  FECHAFINUDOC   DATE
  );

CREATE TABLE ASGFELIMSELUDOC(
  IDELIMINACION VARCHAR2(32) NOT NULL,
  IDUDOC VARCHAR2(32) NOT NULL,
  IDFONDO VARCHAR2(32),
  CODREFERENCIA VARCHAR2(1024),
  CODIGO VARCHAR2(128),
  SIGNATURAUDOC VARCHAR2(32),
  EXPEDIENTEUDOC VARCHAR2(256),
  TITULO VARCHAR2(1024),
  CODSISTPRODUCTOR VARCHAR2(16),
  TIPODOCUMENTAL VARCHAR2(254),
  IDUINSTALACION VARCHAR2(32),
  UBICACION VARCHAR2(512),
  FECHAINIUDOC DATE,
  FECHAFINUDOC DATE,
  NUMERO VARCHAR2(10)
  );

CREATE TABLE ASGFHISTUDOC (
  IDELIMINACION   VARCHAR2(32)  NOT NULL,
  IDUDOC          VARCHAR2(32)  NOT NULL,
  SIGNATURAUDOC   VARCHAR2(128)  NOT NULL,
  TITULOUDOC      VARCHAR2(1024)  NOT NULL,
  NUMEXPUDOC      VARCHAR2(256),
  CODREFUDOC      VARCHAR2(1024)  NOT NULL,
  DATOSDESCRUDOC  CLOB
  );

CREATE TABLE ASGPCONSULTA (
  ID                 VARCHAR2(32)  NOT NULL,
  ANO                VARCHAR2(4)  NOT NULL,
  ORDEN              NUMBER (10)   NOT NULL,
  TIPOENTCONSULTORA  NUMBER (2)    NOT NULL,
  NORGCONSULTOR      VARCHAR2(254),
  NUSRCONSULTOR      VARCHAR2(254)  NOT NULL,
  FINICIALRESERVA    DATE,
  FENTREGA           DATE,
  FMAXFINCONSULTA    DATE,
  ESTADO             NUMBER (2)    NOT NULL,
  FESTADO            DATE          NOT NULL,
  MOTIVO             VARCHAR2(254),
  IDARCHIVO          VARCHAR2(32)  NOT NULL,
  IDUSRSOLICITANTE   VARCHAR2(32)  NOT NULL,
  INFORMACION        VARCHAR2(1024),
  TEMA               VARCHAR2(254),
  TIPO               NUMBER (2)    NOT NULL,
  TIPOENTREGA 	     VARCHAR2(254),
  DATOSAUTORIZADO    VARCHAR2(254),
  DATOSSOLICITANTE   VARCHAR2(512),
  OBSERVACIONES VARCHAR2(254),
  IDMOTIVO VARCHAR2(32),
  IDUSRCSALA VARCHAR2(32)
  );

CREATE TABLE ASGPMTVCONSULTA (
  ID            VARCHAR2(32) NOT NULL,
  TIPOENTIDAD   NUMBER (2)    NOT NULL,
  MOTIVO        VARCHAR2(254)  NOT NULL,
  TIPOCONSULTA  NUMBER (2) NOT NULL,
  VISIBILIDAD   NUMBER (3)
  );

CREATE TABLE ASGPMTVRECHAZO (
  ID             VARCHAR2(32) NOT NULL,
  TIPOSOLICITUD  NUMBER (2)    NOT NULL,
  MOTIVO         VARCHAR2(254)  NOT NULL
  );

CREATE TABLE ASGPPRESTAMO (
  ID                VARCHAR2(32)  NOT NULL,
  ANO               VARCHAR2(4)  NOT NULL,
  ORDEN             NUMBER (10)   NOT NULL,
  NORGSOLICITANTE   VARCHAR2(254)  NOT NULL,
  NUSRSOLICITANTE   VARCHAR2(254)  NOT NULL,
  IDUSRSOLICITANTE  VARCHAR2(32),
  FINICIALRESERVA   DATE,
  IDORGSOLICITANTE  VARCHAR2(32),
  FENTREGA          DATE,
  FMAXFINPRESTAMO   DATE,
  ESTADO            NUMBER (2)    NOT NULL,
  FESTADO           DATE          NOT NULL,
  IDARCHIVO         VARCHAR2(32)  NOT NULL,
  IDUSRGESTOR       VARCHAR2(32)  NOT NULL,
  NUMRECLAMACIONES  NUMBER (10)   NOT NULL,
  FRECLAMACION1     DATE,
  FRECLAMACION2     DATE,
  TIPOENTREGA 	    VARCHAR2(254),
  DATOSAUTORIZADO   VARCHAR2(254),
  DATOSSOLICITANTE  VARCHAR2(512),
  OBSERVACIONES     VARCHAR2(254),
  IDMOTIVO          VARCHAR2(32)
  );

CREATE TABLE ASGPMTVPRESTAMO (
  ID            VARCHAR2(32) NOT NULL,
  TIPOUSUARIO   NUMBER(3)    NOT NULL,
  MOTIVO        VARCHAR2(254)  NOT NULL,
  VISIBILIDAD   NUMBER(3)
  );

CREATE TABLE ASGPPRORROGA (
  ID             VARCHAR2(32)  NOT NULL,
  IDPRESTAMO     VARCHAR2(32)  NOT NULL,
  ESTADO         NUMBER (2)    NOT NULL,
  FESTADO        DATE          NOT NULL,
  MOTIVORECHAZO  VARCHAR2(254),
  IDMOTIVO       VARCHAR2(32),
  FECHAFINPRORROGA DATE,
  MOTIVOPRORROGA VARCHAR2(512)
  );

CREATE TABLE ASGPSNSEC (
  TIPO    NUMBER (10)   NOT NULL,
  ANO     VARCHAR2(4)  NOT NULL,
  NUMSEC  NUMBER (10)   NOT NULL
  );

CREATE TABLE ASGPSOLICITUDUDOC (
  IDSOLICITUD     VARCHAR2(32)  NOT NULL,
  TIPOSOLICITUD   NUMBER (2)    NOT NULL,
  IDUDOC          VARCHAR2(32)  NOT NULL,
  TITULO          VARCHAR2(1024)  NOT NULL,
  SIGNATURAUDOC   VARCHAR2(254)  NOT NULL,
  EXPEDIENTEUDOC  VARCHAR2(128),
  IDENTIFICACION  VARCHAR2(254)  NOT NULL,
  ESTADO          NUMBER (2)    NOT NULL,
  FESTADO         DATE          NOT NULL,
  FINICIALUSO     DATE,
  FFINALUSO       DATE,
  MOTIVORECHAZO   VARCHAR2(254),
  INFORMACION     VARCHAR2(1024),
  IDFONDO         VARCHAR2(32) NOT NULL,
  IDMOTIVO        VARCHAR2(32)
  );

CREATE TABLE ASGPTEMA (
  IDUSUARIO    VARCHAR2(32),
  TIPOENTIDAD  NUMBER (2)    NOT NULL,
  TEMA         VARCHAR2(254)  NOT NULL,
  IDUSRCSALA VARCHAR2(32)
  );

CREATE TABLE ASGTDETALLEPREV (
  ID                   VARCHAR2(32)  NOT NULL,
  IDPREVISION          VARCHAR2(32) NOT NULL,
  ORDEN                NUMBER (3) NOT NULL,
  CODSISTPRODUCTOR     VARCHAR2(16),
  NOMBRESISTPRODUCTOR  VARCHAR2(64),
  IDPROCEDIMIENTO      VARCHAR2(32),
  IDSERIEDESTINO       VARCHAR2(32) NOT NULL,
  ANOINIUDOC           CHAR (4) NOT NULL,
  ANOFINUDOC           CHAR (4) NOT NULL,
  NUMUINSTALACION      NUMBER (4) NOT NULL,
  IDFORMATOUI          VARCHAR2(32) NOT NULL,
  NUMRENTREGA          NUMBER (3),
  CERRADO              CHAR (1) NOT NULL,
  OBSERVACIONES        VARCHAR2(254),
  IDSERIEORIGEN VARCHAR2(32),
  INFO VARCHAR2(1024)
  );

CREATE TABLE ASGTPREVISION (
  ID                 CHAR (32)     NOT NULL,
  TIPOTRANSFERENCIA  NUMBER NOT NULL,
  TIPOPREVISION      NUMBER NOT NULL,
  IDORGREMITENTE     VARCHAR2(32) NOT NULL,
  ANO                VARCHAR2(4) NOT NULL,
  ORDEN              NUMBER (10) NOT NULL,
  IDFONDODESTINO     VARCHAR2(32) NOT NULL,
  FECHAINITRANS      DATE,
  FECHAFINTRANS      DATE,
  NUMUINSTALACION    NUMBER,
  ESTADO             NUMBER (1) NOT NULL,
  FECHAESTADO        DATE NOT NULL,
  IDARCHIVORECEPTOR  VARCHAR2(32) NOT NULL,
  IDUSRGESTOR        VARCHAR2(32) NOT NULL,
  MOTIVORECHAZO      VARCHAR2(254),
  OBSERVACIONES      VARCHAR2(254),
  IDARCHIVOREMITENTE VARCHAR2(32)
  );

CREATE TABLE ASGTRENTREGA (
  ID                   VARCHAR2(32)  NOT NULL,
  TIPOTRANSFERENCIA    NUMBER (1) NOT NULL,
  IDPREVISION          VARCHAR2(32) NOT NULL,
  IDDETPREVISION       VARCHAR2(32),
  IDORGANOREMITENTE    VARCHAR2(32) NOT NULL,
  ANO                  CHAR (4) NOT NULL,
  ORDEN                NUMBER (4) NOT NULL,
  IDFONDODESTINO       VARCHAR2(32) NOT NULL,
  CODSISTPRODUCTOR     VARCHAR2(16),
  NOMBRESISTPRODUCTOR  VARCHAR2(64),
  IDPROCEDIMIENTO      VARCHAR2(32),
  IDFORMATOUI          VARCHAR2(32) NOT NULL,
  TIPODOCUMENTAL		  VARCHAR2(254),
  ESTADO               NUMBER (2) NOT NULL,
  FECHAESTADO          DATE NOT NULL,
  IDARCHIVORECEPTOR    VARCHAR2(32) NOT NULL,
  FECHARECEPCION       DATE,
  IDUSRGESTORREM       VARCHAR2(32) NOT NULL,
  IDUSRGESTORARCHIVOREC   VARCHAR2(32),
  IDDEPOSITO           VARCHAR2(32),
  RESERVADEPOSITO      NUMBER (1),
  UIENDEPOSITO         CHAR (1),
  DEVOLUCIONUI         CHAR (1),
  REGENTRADA           VARCHAR2(64),
  OBSERVACIONES        VARCHAR2(2048),
  IDSERIEDESTINO       VARCHAR2(32) NOT NULL,
  IDELMTODRESERVA      VARCHAR2(32),
  IDDESCRORGPRODUCTOR  VARCHAR2(32),
  IDTIPOELMTODRESERVA  VARCHAR2(32),
  IDARCHIVOREMITENTE VARCHAR2(32),
  IDFONDOORIGEN VARCHAR2(32),
  IDSERIEORIGEN VARCHAR2(32),
  CORRECCIONENARCHIVO VARCHAR2(1) DEFAULT 'N' NOT NULL,
  IDNIVELDOCUMENTAL    VARCHAR2(32) NOT NULL,
  SINDOCSFISICOS VARCHAR2(1),
  IDFICHA VARCHAR2(32),
  CONREENCAJADO 	VARCHAR2(1) DEFAULT 'N' NOT NULL,
  IDFORMATORE		VARCHAR2(32)
  );

CREATE TABLE ASGTSNSEC (
  TIPO    NUMBER (1)  NOT NULL,
  ANO     CHAR (4)  NOT NULL,
  NUMSEC  NUMBER (10)  NOT NULL,
  IDARCHIVO  VARCHAR2(32) NOT NULL
  );

CREATE TABLE ASGTSNSECUI (
  NUMSEC  NUMBER NOT NULL,
  IDARCHIVO VARCHAR2(32)
  );

CREATE TABLE ASGTSNSECUDOC(
  NUMSEC  NUMBER NOT NULL
  );

CREATE TABLE ASGTUDOCENUI (
  IDRELENTREGA      CHAR (32)     NOT NULL,
  IDUNIDADDOC       CHAR (32) NOT NULL,
  IDUINSTALACIONRE  CHAR (32) NOT NULL,
  POSUDOCENUI       NUMBER (5) NOT NULL,
  UDOCCOMPLETA      CHAR (1) NOT NULL,
  ESTADOCOTEJO      NUMBER (1) NOT NULL,
  NOTASCOTEJO       VARCHAR2(254),
  SIGNATURAUDOC     VARCHAR2(32),
  NUMPARTEUDOC      NUMBER (2) NOT NULL,
  DESCCONTENIDO     VARCHAR2(254)
  );

CREATE TABLE ASGTUINSTALACIONRE (
  ID            VARCHAR2(32)  NOT NULL,
  IDRELENTREGA  VARCHAR2(32) NOT NULL,
  ORDEN         NUMBER NOT NULL,
  IDFORMATO     VARCHAR2(32) NOT NULL,
  SIGNATURAUI   VARCHAR2(16),
  ESTADOCOTEJO  NUMBER (1) NOT NULL,
  NOTASCOTEJO   VARCHAR2(254),
  DEVOLUCION    CHAR (1) NOT NULL,
  IDUIUBICADA 	VARCHAR2(32)
  );

CREATE TABLE ASGTUINSTALACIONREEA(
  IDUIDEPOSITO 	VARCHAR2(32) NOT NULL,
  IDRELENTREGA 	VARCHAR2(32) NOT NULL,
  ORDEN 	NUMBER NOT NULL,
  IDFORMATO 	VARCHAR2(32) NOT NULL,
  ESTADOCOTEJO 	NUMBER NOT NULL,
  NOTASCOTEJO 	VARCHAR2(254),
  DEVOLUCION 	VARCHAR2(1) NOT NULL,
  PATHDEPOSITOORIGEN VARCHAR2(512) NOT NULL,
  SIGNATURAUI VARCHAR2(16),
  IDELEMAPADREHUECOORIGEN VARCHAR2(32) NOT NULL,
  NUMORDENHUECOORIGEN NUMBER NOT NULL,
  SIGNATURAUIORIGEN VARCHAR2(16)
  );

CREATE TABLE ASGTUNIDADDOCRE (
  ID                VARCHAR2(32)  NOT NULL,
  IDRELENTREGA      VARCHAR2(32) NOT NULL,
  TIPOTRANSFERENCIA NUMBER (1) NOT NULL,
  NUMEXP            VARCHAR2(256),
  CODSISTPRODUCTOR  VARCHAR2(16),
  FECHAEXTINI       DATE,
  FECHAEXTFIN       DATE,
  ASUNTO            VARCHAR2(1024),
  VALIDADA          CHAR (1) NOT NULL,
  SINDOCSFISICOS    CHAR (1) NOT NULL,
  INFO              CLOB NOT NULL,
  NUMPARTES         NUMBER (2),
  ORDEN             NUMBER,
  MARCASBLOQUEO     NUMBER DEFAULT 0 NOT NULL
  );

CREATE TABLE ASGTUDOCSDF(
	ID VARCHAR2(32) NOT NULL,
	IDRELENTREGA VARCHAR2(32) NOT NULL,
	POSICION NUMBER(5) NOT NULL,
	ESTADOCOTEJO NUMBER(5) NOT NULL,
	NOTASCOTEJO VARCHAR2(254)
);

CREATE TABLE ASGFUDOCSDF (
	IDELEMENTOCF     VARCHAR2(32) NOT NULL,
	MARCASBLOQUEO   NUMBER(10) DEFAULT 0 NOT NULL
);

CREATE TABLE ASGTMAPDESCRUDOC (
	IDFICHA   VARCHAR2(32)  NOT NULL,
	INFO    CLOB  NOT NULL
);

CREATE TABLE ITDGUIDGEN (
  CNODE  VARCHAR2(12),
  CLPID  NUMBER
  );

CREATE TABLE AGINFOSISTEMA (
  AUTID NUMBER NOT NULL,
  NOMBRE VARCHAR2(32) NOT NULL,
  VALOR CLOB NOT NULL,
  FECHAACTUALIZACION DATE NOT NULL
);

CREATE TABLE ADVCFECHAUDOCRE (
	IDUDOCRE VARCHAR2(32) NOT NULL,
	IDCAMPO VARCHAR2(32) NOT NULL,
	VALOR VARCHAR2(64),
	FECHAINI DATE,
	FECHAFIN DATE,
	FORMATO VARCHAR2(16),
	SEP VARCHAR2(1),
	CALIFICADOR VARCHAR2(32),
	ORDEN NUMBER(3) NOT NULL,
	TIPOUDOC NUMBER(2) DEFAULT 1 NOT NULL
);

CREATE TABLE ADVCNUMUDOCRE (
	IDUDOCRE VARCHAR2(32) NOT NULL,
	IDCAMPO VARCHAR2(32) NOT NULL,
	VALOR NUMBER(8,2) NOT NULL,
	ORDEN NUMBER(3) NOT NULL,
	TIPOMEDIDA NUMBER,
	UNIDADMEDIDA VARCHAR2(16),
	TIPOUDOC NUMBER(2) DEFAULT 1 NOT NULL
);

CREATE TABLE ADVCREFUDOCRE (
	IDUDOCRE VARCHAR2(32) NOT NULL,
	IDCAMPO VARCHAR2(32) NOT NULL,
	TIPOOBJREF NUMBER(38) NOT NULL,
	IDOBJREF VARCHAR2(32) NOT NULL,
	ORDEN NUMBER(3) NOT NULL,
	TIPOUDOC NUMBER(2) DEFAULT 1 NOT NULL
);

CREATE TABLE ADVCTEXTLUDOCRE (
	IDUDOCRE VARCHAR2(32) NOT NULL,
	IDCAMPO VARCHAR2(32) NOT NULL,
	VALOR CLOB NOT NULL,
	ORDEN NUMBER(3) NOT NULL,
	TIPOUDOC NUMBER(2) DEFAULT 1 NOT NULL
);

CREATE TABLE ADVCTEXTUDOCRE (
	IDUDOCRE VARCHAR2(32) NOT NULL,
	IDCAMPO VARCHAR2(32) NOT NULL,
	VALOR VARCHAR2(254) NOT NULL,
	ORDEN NUMBER(3) NOT NULL,
	TIPOUDOC NUMBER(2) DEFAULT 1 NOT NULL
);

CREATE TABLE ASGFDIVISIONFS (
	IDFS VARCHAR2(32) NOT NULL,
	IDFICHA VARCHAR2(32) NULL,
	IDNIVELDOCUMENTAL VARCHAR2(32) NOT NULL,
	IDUSRGESTOR VARCHAR2(32) NOT NULL,
	ESTADO NUMBER(2) NOT NULL,
	INFO VARCHAR2(1024),
	FECHAESTADO DATE NOT NULL
	);

CREATE TABLE ASGFUDOCENDIVISIONFS (
		IDFS 			VARCHAR2(32) NOT NULL,
		IDUDOC 			VARCHAR2(32) NOT NULL,
		NUMEXP           VARCHAR2(256),
		FECHAEXTINI      DATE NOT NULL,
	FECHAEXTFIN      DATE NOT NULL,
	ASUNTO           VARCHAR2(1024) NOT NULL,
		ORDEN			NUMBER(5) NOT NULL,
	VALIDADA 		VARCHAR2(1) NOT NULL,
	INFO             CLOB
	);

CREATE TABLE ASGFPZTRVALSERIE(
	IDVALSERIE 		VARCHAR2(32) NOT NULL,
	PLAZO 			NUMBER  NOT NULL,
	IDNIVELARCHORG 	VARCHAR2(32) NOT NULL,
	IDNIVELARCHDST 	VARCHAR2(32) NOT NULL,
	ORDEN 			NUMBER NOT NULL
);

CREATE TABLE ASGDSIGNUMHUECO (
  IDARCHIVO 	VARCHAR2(32) NOT NULL,
  SIGNUMHUECO  	NUMBER(16) NOT NULL
);

CREATE TABLE ASGPREVDOCUDOC (
  IDREVDOC			VARCHAR2(32)  NOT NULL,
  IDUDOC          		VARCHAR2(32)  NOT NULL,
  TITULO          		VARCHAR2(1024)  NOT NULL,
  SIGNATURAUDOC   	VARCHAR2(254)  NOT NULL,
  EXPEDIENTEUDOC  	VARCHAR2(128),
  ESTADO          		NUMBER(2)    NOT NULL,
  FESTADO         		DATE          NOT NULL,
  OBSERVACIONES        	VARCHAR2(1024),
  MOTIVORECHAZO 	VARCHAR2(254),
  IDUSRGESTOR        	VARCHAR2(32) NOT NULL,
  IDALTA			VARCHAR2(32)
);

CREATE TABLE ASGSEDIFICIO (
  ID            VARCHAR2(32) NOT NULL,
  NOMBRE        VARCHAR2(64) NOT NULL,
  UBICACION     VARCHAR2(254),
  IDARCHIVO     VARCHAR2(32) NOT NULL
);

CREATE TABLE ASGSSALA (
  ID              		VARCHAR2(32) NOT NULL,
  NOMBRE          		VARCHAR2(64) NOT NULL,
  DESCRIPCION     		VARCHAR2(254),
  IDEDIFICIO      		VARCHAR2(32) NOT NULL,
  EQUIPOINFORMATICO 	CHAR (1) NOT NULL
);

CREATE TABLE ASGSMESA (
  ID            VARCHAR2(32) NOT NULL,
  CODIGO        VARCHAR2(64) NOT NULL,
  NUMORDEN      NUMBER NOT NULL,
  IDSALA        VARCHAR2(32) NOT NULL,
  ESTADO        CHAR (1) NOT NULL,
  FECHAESTADO   DATE NOT NULL,
  IDUSRCSALA	VARCHAR2(32)
);

CREATE TABLE ASGSUSRCSALA (
  ID	 	  	  			VARCHAR2(32) NOT NULL,
  TIPODOCIDENTIFICACION     NUMBER NOT NULL,
  NUMDOCIDENTIFICACION		VARCHAR2(32) NOT NULL,
  NOMBRE			  	    VARCHAR2(64) NOT NULL,
  APELLIDOS			  	    VARCHAR(254) NOT NULL,
  NACIONALIDAD	   	  	    VARCHAR2(64),
  TELEFONOS					VARCHAR2(128),
  EMAIL						VARCHAR2(128),
  DIRECCION		            VARCHAR2(254),
  FECHAALTA				    DATE NOT NULL,
  VIGENTE					CHAR (1) NOT NULL,
  IDSCAUSR					VARCHAR2(32)
);

CREATE TABLE ASGSUSRCSARCH (
  IDUSRCSALA  	  VARCHAR2(32) NOT NULL,
  IDARCHIVO       VARCHAR2(64) NOT NULL
);

CREATE TABLE ASGSREGCSALA (
  ID		  	  		VARCHAR2(32) NOT NULL,
  IDUSRCSALA  	  		VARCHAR2(32) NOT NULL,
  FENTRADA				DATE NOT NULL,
  FSALIDA				DATE,
  NUMDOCIDENTIFICACION	VARCHAR2(32) NOT NULL,
  NOMBREAPELLIDOS		VARCHAR2(254) NOT NULL,
  IDSCAUSR	  	  		VARCHAR2(32),
  IDARCHIVO	  	  		VARCHAR2(32) NOT NULL,
  MESAASIGNADA			VARCHAR2(254) NOT NULL
);

CREATE TABLE ASGTUIREEACR (
  ID			  VARCHAR2(32)  NOT NULL,
  IDRELENTREGA    VARCHAR2(32)  NOT NULL,
  IDUIDEPOSITO    VARCHAR2(32),
  SIGNATURAUI     VARCHAR2(16),
  IDFORMATO       VARCHAR2(32) NOT NULL,
  ORDEN			  NUMBER NOT NULL,
  ESTADOCOTEJO 	  NUMBER(1) DEFAULT 1 NOT NULL,
  NOTASCOTEJO	  VARCHAR2(256),
  DEVOLUCION	  CHAR (1) DEFAULT 'N',
  DESCRIPCION	  VARCHAR2(256)
);

CREATE TABLE ASGTUDOCENUIREEACR (
  ID			  VARCHAR2(32)  NOT NULL,
  IDUDOCORIGEN    VARCHAR2(32)  NOT NULL,
  IDRELENTREGA    VARCHAR2(32)  NOT NULL,
  IDUNIDADDOC     VARCHAR2(32)  NOT NULL,
  IDUIREEACR	  VARCHAR2(32),
  ASUNTO		  VARCHAR2(1024) NOT NULL,
  UDOCCOMPLETA	  VARCHAR2(1) NOT NULL,
  SIGNATURAUDOC   VARCHAR2(32),
  POSUDOCENUI     NUMBER,
  NUMEXP          VARCHAR2(256),
  NUMPARTE        NUMBER,
  FECHAINI        VARCHAR2(64),
  FECHAFIN        VARCHAR2(64),
  SIGNATURAUDOCORIGEN VARCHAR2(32),
  DESCRIPCION	  VARCHAR2(256)
);

CREATE TABLE ASGTUDOCREEACR (
  ID			  VARCHAR2(32)  NOT NULL,
  IDRELENTREGA    VARCHAR2(32)  NOT NULL,
  IDUNIDADDOC     VARCHAR2(32)  NOT NULL,
  SIGNATURAUDOC	  VARCHAR2(32)  NOT NULL,
  IDUIDEPOSITO	  VARCHAR2(32)  NOT NULL,
  SIGNATURAUI	  VARCHAR2(16)  NOT NULL
);

CREATE TABLE ASGFCTLGTBLTMP(
	ID NUMERIC(5)NOT NULL,
	NOMBRETABLA VARCHAR2(16) NOT NULL,
	IDUSUARIO VARCHAR2(32),
	ESTADO NUMERIC(1) default 0,
	FECHA DATE
);
