--/***************************/
--/* Versión 4.2             */
--/***************************/

    -- Insertar la versión actual de bd
	INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.0->4.2',CURRENT TIMESTAMP);

	-- Establecer el id de motivo como nulo
	CREATE TABLE ASGPCONSULTA2 (
		ID VARCHAR(32) NOT NULL,
		ANO VARCHAR(4) NOT NULL,
		ORDEN INTEGER NOT NULL,
		TIPOENTCONSULTORA SMALLINT NOT NULL,
		NORGCONSULTOR VARCHAR(254),
		NUSRCONSULTOR VARCHAR(254) NOT NULL,
		FINICIALRESERVA TIMESTAMP,
		FENTREGA TIMESTAMP,
		FMAXFINCONSULTA TIMESTAMP,
		ESTADO SMALLINT NOT NULL,
		FESTADO TIMESTAMP NOT NULL,
		MOTIVO VARCHAR(254),
		IDARCHIVO VARCHAR(32) NOT NULL,
		IDUSRSOLICITANTE VARCHAR(32) NOT NULL,
		INFORMACION VARCHAR(1024),
		TEMA VARCHAR(254),
		TIPO SMALLINT NOT NULL,
		TIPOENTREGA VARCHAR(254),
		DATOSAUTORIZADO VARCHAR(254),
		DATOSSOLICITANTE VARCHAR(512),
		OBSERVACIONES VARCHAR(254),
	    IDMOTIVO VARCHAR(32)) ;

	INSERT INTO ASGPCONSULTA2 SELECT ID,ANO,ORDEN,TIPOENTCONSULTORA,NORGCONSULTOR,NUSRCONSULTOR,FINICIALRESERVA,FENTREGA,FMAXFINCONSULTA,ESTADO,FESTADO,MOTIVO,IDARCHIVO,IDUSRSOLICITANTE,INFORMACION,TEMA,TIPO,TIPOENTREGA,DATOSAUTORIZADO,DATOSSOLICITANTE,OBSERVACIONES,IDMOTIVO FROM ASGPCONSULTA;
	DROP TABLE ASGPCONSULTA;
	RENAME TABLE ASGPCONSULTA2 TO ASGPCONSULTA;

	CREATE UNIQUE INDEX ASGPCONSULTA1 ON ASGPCONSULTA (ID);
	CREATE INDEX ASGPCONSULTA2 ON ASGPCONSULTA (NUSRCONSULTOR);
	CREATE INDEX ASGPCONSULTA3 ON ASGPCONSULTA (IDUSRSOLICITANTE);
	CREATE INDEX ASGPCONSULTA4 ON ASGPCONSULTA (ESTADO);

	-- Establecer el identificador de motivo en préstamos como nulo
	CREATE TABLE ASGPPRESTAMO2 (
		ID VARCHAR(32) NOT NULL,
		ANO VARCHAR(4) NOT NULL,
		ORDEN INTEGER NOT NULL,
		NORGSOLICITANTE VARCHAR(254) NOT NULL,
		NUSRSOLICITANTE VARCHAR(254) NOT NULL,
		IDUSRSOLICITANTE VARCHAR(32),
		FINICIALRESERVA TIMESTAMP,
		IDORGSOLICITANTE VARCHAR(32),
		FENTREGA TIMESTAMP,
		FMAXFINPRESTAMO TIMESTAMP,
		ESTADO SMALLINT NOT NULL,
		FESTADO TIMESTAMP NOT NULL,
		IDARCHIVO VARCHAR(32) NOT NULL,
		IDUSRGESTOR VARCHAR(32) NOT NULL,
		NUMRECLAMACIONES INTEGER NOT NULL,
		FRECLAMACION1 TIMESTAMP,
		FRECLAMACION2 TIMESTAMP,
		TIPOENTREGA VARCHAR(254),
		DATOSAUTORIZADO VARCHAR(254),
		DATOSSOLICITANTE VARCHAR(512),
		OBSERVACIONES VARCHAR(254),
	    IDMOTIVO VARCHAR(32));

	INSERT INTO ASGPPRESTAMO2 SELECT ID,ANO,ORDEN,NORGSOLICITANTE,NUSRSOLICITANTE,IDUSRSOLICITANTE,FINICIALRESERVA,IDORGSOLICITANTE,FENTREGA,FMAXFINPRESTAMO,ESTADO,FESTADO,IDARCHIVO,IDUSRGESTOR,NUMRECLAMACIONES,FRECLAMACION1,FRECLAMACION2,TIPOENTREGA,DATOSAUTORIZADO,DATOSSOLICITANTE,OBSERVACIONES,IDMOTIVO FROM ASGPPRESTAMO;
	DROP TABLE ASGPPRESTAMO;
	RENAME TABLE ASGPPRESTAMO2 TO ASGPPRESTAMO;

	CREATE UNIQUE INDEX ASGPPRESTAMO1 ON ASGPPRESTAMO (ID);
	CREATE INDEX ASGPPRESTAMO2 ON ASGPPRESTAMO (NUSRSOLICITANTE);
	CREATE INDEX ASGPPRESTAMO3 ON ASGPPRESTAMO (IDUSRSOLICITANTE);
	CREATE INDEX ASGPPRESTAMO4 ON ASGPPRESTAMO (ESTADO);

--/*************************/
--/* Versión 4.3           */
--/*************************/

	-- Insertar la versión actual de bd
	INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.2->4.3',CURRENT TIMESTAMP);

	--Añadir columna MARCASBLOQUEO
	ALTER TABLE ASGTUNIDADDOCRE ADD COLUMN MARCASBLOQUEO INTEGER DEFAULT 0 NOT NULL;

	--Añadir columna MARCASBLOQUEO
	ALTER TABLE ASGFUNIDADDOC ADD COLUMN MARCASBLOQUEO INTEGER DEFAULT 0 NOT NULL;

--/*************************/
--/* Versión 4.5           */
--/*************************/

	-- Insertar la versión actual de bd
	INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.3->4.5',CURRENT TIMESTAMP);

	-- Crear tabla de Edificios
	CREATE TABLE ASGSEDIFICIO (
	  ID			VARCHAR (32) NOT NULL,
	  NOMBRE        VARCHAR (64) NOT NULL,
	  UBICACION     VARCHAR (254),
	  IDARCHIVO   	VARCHAR (32) NOT NULL
	);

	-- Crear índices de la tabla de Edificios
	CREATE UNIQUE INDEX ASGSEDIFICIO1 ON ASGSEDIFICIO(ID);
	CREATE UNIQUE INDEX ASGSEDIFICIO2 ON ASGSEDIFICIO(NOMBRE);

	-- Crear tabla de Salas
	CREATE TABLE ASGSSALA (
	  ID	 	  	  		VARCHAR (32) NOT NULL,
	  NOMBRE          		VARCHAR (64) NOT NULL,
	  DESCRIPCION     		VARCHAR (254),
	  IDEDIFICIO   	  		VARCHAR (32) NOT NULL,
	  EQUIPOINFORMATICO     CHAR (1) NOT NULL
	);

	-- Crear índices de la tabla de Salas
	CREATE UNIQUE INDEX ASGSSALA1 ON ASGSSALA(ID);
	CREATE UNIQUE INDEX ASGSSALA2 ON ASGSSALA(IDEDIFICIO,NOMBRE);
	CREATE INDEX ASGSSALA3 ON ASGSSALA(IDEDIFICIO);

	-- Crear tabla de Mesas
	CREATE TABLE ASGSMESA (
	  ID	 	  	  VARCHAR (32) NOT NULL,
	  CODIGO          VARCHAR (64) NOT NULL,
	  NUMORDEN	  	  INTEGER NOT NULL,
	  IDSALA   	  	  VARCHAR (32) NOT NULL,
	  ESTADO          CHAR (1) NOT NULL,
	  FECHAESTADO     TIMESTAMP NOT NULL,
	  IDUSRCSALA   	  VARCHAR (32)
	);

	-- Crear índices de la tabla Mesas
	CREATE INDEX ASGSMESA1 ON ASGSMESA(IDSALA);
	CREATE UNIQUE INDEX ASGSMESA2 ON ASGSMESA(IDSALA,CODIGO);
	CREATE UNIQUE INDEX ASGSMESA3 ON ASGSMESA(IDSALA,NUMORDEN);
	CREATE INDEX ASGSMESA4 ON ASGSMESA(ESTADO);

	-- Crear tabla de usuarios investigadores de consulta de sala
	CREATE TABLE ASGSUSRCSALA (
	  ID	 	  	  			VARCHAR (32) NOT NULL,
	  TIPODOCIDENTIFICACION     INTEGER NOT NULL,
	  NUMDOCIDENTIFICACION		VARCHAR (32) NOT NULL,
	  NOMBRE			  	    VARCHAR (64) NOT NULL,
	  APELLIDOS			  	    VARCHAR (254) NOT NULL,
	  NACIONALIDAD	   	  	    VARCHAR (64),
	  TELEFONOS					VARCHAR (128),
	  EMAIL						VARCHAR (128),
	  DIRECCION		            VARCHAR (254),
	  FECHAALTA				    TIMESTAMP NOT NULL,
	  VIGENTE					CHAR (1) NOT NULL,
	  IDSCAUSR					VARCHAR (32)
	);

	-- Crear índices de la tabla usuarios investigadores
	CREATE UNIQUE INDEX ASGSUSRCSALA1 ON ASGSUSRCSALA(ID);
	CREATE INDEX ASGSUSRCSALA2 ON ASGSUSRCSALA(NUMDOCIDENTIFICACION);
	CREATE INDEX ASGSUSRCSALA3 ON ASGSUSRCSALA(VIGENTE);

	-- Crear tabla relación usuarios consulta y archivos
	CREATE TABLE ASGSUSRCSARCH (
	  IDUSRCSALA  	  VARCHAR (32) NOT NULL,
	  IDARCHIVO       VARCHAR (64) NOT NULL
	);

	-- Crear índices de la tabla de relación entre usuarios y archivos de consulta
	CREATE UNIQUE INDEX ASGSUSRCSARCH1 ON ASGSUSRCSARCH(IDUSRCSALA,IDARCHIVO);
	CREATE INDEX ASGSUSRCSARCH2 ON ASGSUSRCSARCH(IDUSRCSALA);

	-- Crear tabla de registro de consultas
	CREATE TABLE ASGSREGCSALA (
	  ID 					VARCHAR (32) NOT NULL,
	  IDUSRCSALA  	  		VARCHAR (32) NOT NULL,
	  FENTRADA	      		TIMESTAMP NOT NULL,
	  FSALIDA	      		TIMESTAMP,
	  NUMDOCIDENTIFICACION	VARCHAR (32) NOT NULL,
	  NOMBREAPELLIDOS		VARCHAR (254) NOT NULL,
	  IDSCAUSR				VARCHAR (32),
	  IDARCHIVO				VARCHAR (32) NOT NULL,
	  MESAASIGNADA			VARCHAR (254) NOT NULL
	);

	-- Crear índices de la tabla de registro de consultas
	CREATE UNIQUE INDEX ASGSREGCSALA1 ON ASGSREGCSALA(ID);
	CREATE INDEX ASGSREGCSALA2 ON ASGSREGCSALA(IDUSRCSALA);
	CREATE INDEX ASGSREGCSALA3 ON ASGSREGCSALA(NUMDOCIDENTIFICACION);

	--Añadir columna IDUSRCSALA
	ALTER TABLE ASGPCONSULTA ADD COLUMN IDUSRCSALA VARCHAR(32);

	--Añadir columna IDUSRCSALA
	ALTER TABLE ASGPTEMA ADD COLUMN IDUSRCSALA VARCHAR(32);

	--Añadir columnaS CONREENCAJADO E IDFORMATORE a la tabla de relaciones de entrega
	ALTER TABLE ASGTRENTREGA ADD CONREENCAJADO CHAR(1) DEFAULT 'N' NOT NULL;
	ALTER TABLE ASGTRENTREGA ADD IDFORMATORE VARCHAR(32);

	--Añadir columna IDUIREEACR a la tabla de huecos
	ALTER TABLE ASGDHUECO ADD IDUIREEACR VARCHAR(32);

	--Crear la tabla de unidades de instalación transferencias entre archivo con reencajado
	CREATE TABLE ASGTUIREEACR (
	  ID			  VARCHAR (32)  NOT NULL,
	  IDRELENTREGA    VARCHAR (32)  NOT NULL,
	  IDUIDEPOSITO    VARCHAR (32),
	  SIGNATURAUI     VARCHAR (16),
	  IDFORMATO       VARCHAR (32) NOT NULL,
	  ORDEN			  SMALLINT NOT NULL,
	  ESTADOCOTEJO 	  SMALLINT DEFAULT 1 NOT NULL,
	  NOTASCOTEJO	  VARCHAR (256),
	  DEVOLUCION	  CHAR (1) DEFAULT 'N',
	  DESCRIPCION	  VARCHAR (256)
	);

	--Crear la tabla de unidades documentales en unidad de instalacion de transferencias
	--entre archivos con reencajado
	CREATE TABLE ASGTUDOCENUIREEACR (
	  ID			  VARCHAR (32)  NOT NULL,
	  IDUDOCORIGEN    VARCHAR (32)  NOT NULL,
	  IDRELENTREGA    VARCHAR (32)  NOT NULL,
	  IDUNIDADDOC     VARCHAR (32)  NOT NULL,
	  IDUIREEACR	  VARCHAR (32),
	  ASUNTO		  VARCHAR (1024) NOT NULL,
	  UDOCCOMPLETA	  VARCHAR (1) NOT NULL,
	  SIGNATURAUDOC   VARCHAR (32),
	  POSUDOCENUI     SMALLINT,
	  NUMEXP          VARCHAR (256),
	  NUMPARTE        SMALLINT,
	  FECHAINI        VARCHAR (64),
	  FECHAFIN        VARCHAR (64),
	  SIGNATURAUDOCORIGEN VARCHAR (32),
	  DESCRIPCION	  VARCHAR (256)
	);

	--Tabla de unidades documentales originales en el reencajado
	CREATE TABLE ASGTUDOCREEACR (
	  ID			  VARCHAR (32)  NOT NULL,
	  IDRELENTREGA    VARCHAR (32)  NOT NULL,
	  IDUNIDADDOC     VARCHAR (32)  NOT NULL,
	  SIGNATURAUDOC	  VARCHAR (32)  NOT NULL,
	  IDUIDEPOSITO	  VARCHAR (32)  NOT NULL,
	  SIGNATURAUI	  VARCHAR (16)  NOT NULL
	);

	-- Tabla: ASGTUIREEACR
	CREATE UNIQUE INDEX ASGTUIREEACR1 ON ASGTUIREEACR (ID);
	CREATE INDEX ASGTUIREEACR2 ON ASGTUIREEACR (IDRELENTREGA);

	-- Tabla: ASGTUDOCENUIREEACR
	CREATE UNIQUE INDEX ASGTUDENUIREEACR1 ON ASGTUDOCENUIREEACR (ID);
	CREATE INDEX ASGTUDENUIREEACR2 ON ASGTUDOCENUIREEACR (IDUDOCORIGEN);
	CREATE INDEX ASGTUDENUIREEACR3 ON ASGTUDOCENUIREEACR (IDRELENTREGA);
	CREATE INDEX ASGTUDENUIREEACR4 ON ASGTUDOCENUIREEACR (IDUNIDADDOC);
	CREATE INDEX ASGTUDENUIREEACR5 ON ASGTUDOCENUIREEACR (IDUIREEACR);
	CREATE INDEX ASGTUDENUIREEACR6 ON ASGTUDOCENUIREEACR (IDRELENTREGA,IDUNIDADDOC);

	-- Tabla: ASGTUDOCREEACR
	CREATE UNIQUE INDEX ASGTUDOCREEACR1 ON ASGTUDOCREEACR (ID);
	CREATE INDEX ASGTUDOCREEACR2 ON ASGTUDOCREEACR (IDRELENTREGA);
	CREATE INDEX ASGTUDOCREEACR3 ON ASGTUDOCREEACR (IDRELENTREGA,IDUNIDADDOC);

--/*************************/
--/* Versión 4.7           */
--/*************************/

-- Insertar la versión actual de bd
INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.5->4.7',CURRENT TIMESTAMP);

--Catalogo de Tablas Temporales
--NOTA: Para esta funcionalidad necesario permiso de db_ddladmin o permisos para crear tablas. ya que la aplicacion necesita crear tablas en tiempo de ejecucion
CREATE TABLE ASGFCTLGTBLTMP(
	ID smallint	NOT NULL,
	NOMBRETABLA VARCHAR(16) NOT NULL,
	IDUSUARIO VARCHAR(32),
	ESTADO smallint default 0,
	FECHA datetime
);

CREATE UNIQUE INDEX ASGFCTLGTBLTMP1 ON ASGFCTLGTBLTMP(ID);
CREATE UNIQUE INDEX ASGFCTLGTBLTMP2 ON ASGFCTLGTBLTMP(NOMBRETABLA);

CREATE UNIQUE INDEX ASGFFONDO2 ON ASGFFONDO(CODARCHIVO,IDENTPRODUCTORA);


--/*************************/
--/* Versión 4.7->4.8      */
--/*************************/

-- Insertar la versión actual de bd
INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.7->4.8',CURRENT TIMESTAMP);


--Fecha devolución en prorroga
ALTER TABLE ASGPPRORROGA ADD COLUMN FECHAFINPRORROGA TIMESTAMP;

--Motivo por el cual se solicita la prorroga
ALTER TABLE ASGPPRORROGA ADD COLUMN MOTIVOPRORROGA VARCHAR(512);


DROP INDEX ASGFELIMSELUDOC1;
DROP INDEX ASGFELIMSELUDOC2;

--Modificar el nombre de la tabla ASGFELIMSELUDOC por ASGFELIMUDOCCONS
RENAME ASGFELIMSELUDOC TO ASGFELIMUDOCCONS;

-- Tabla: ASGFELIMSELUDOC
CREATE INDEX ASGFELIMUDOCCONS1 ON ASGFELIMUDOCCONS (IDELIMINACION);
CREATE INDEX ASGFELIMUDOCCONS2 ON ASGFELIMUDOCCONS (IDUDOC);


CREATE TABLE ASGFELIMSELUDOC(
    IDELIMINACION VARCHAR(32) NOT NULL,
    IDUDOC VARCHAR(32) NOT NULL,
    IDFONDO VARCHAR(32),
    CODREFERENCIA VARCHAR(1024),
    CODIGO VARCHAR(128),
    SIGNATURAUDOC VARCHAR(32),
    EXPEDIENTEUDOC VARCHAR(256),
    TITULO VARCHAR(1024),
    CODSISTPRODUCTOR VARCHAR(16),
    TIPODOCUMENTAL VARCHAR(254),
    IDUINSTALACION VARCHAR(32),
    UBICACION VARCHAR(512),
    FECHAINIUDOC TIMESTAMP,
    FECHAFINUDOC TIMESTAMP,
    NUMERO VARCHAR(10)
);

-- Tabla: ASGFELIMSELUDOC
CREATE INDEX ASGFELIMSELUDOC1 ON ASGFELIMSELUDOC (IDELIMINACION);
CREATE INDEX ASGFELIMSELUDOC2 ON ASGFELIMSELUDOC (IDUDOC);

-- Tabla: ASGFUNIDADDOC
CREATE INDEX ASGFUNIDADDOC4 ON ASGFUNIDADDOC(IDFONDO);

--/*************************/
--/* Versión 4.8->5.0      */
--/*************************/

-- Insertar la versión actual de bd
INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.8->5.0',CURRENT TIMESTAMP);

--Renombrar campo IDLVOLPREF A IDREPECMPREF en la tabla ADCTLGLISTAD
	CREATE TABLE ADCTLGLISTAD2 (
		ID VARCHAR(32) NOT NULL,
		NOMBRE VARCHAR(64) NOT NULL,
		TIPO INTEGER NOT NULL,
		TIPODESCRIPTOR INTEGER NOT NULL,
		IDFICHADESCRPREF VARCHAR(32),
		IDFICHACLFDOCPREF VARCHAR(32),
		IDREPECMPREF VARCHAR(32),
		DESCRIPCION VARCHAR(254)
	);

	INSERT INTO ADCTLGLISTAD2
	 (
	 	ID,
		NOMBRE,
		TIPO,
		TIPODESCRIPTOR,
		IDFICHADESCRPREF,
		IDFICHACLFDOCPREF,
		IDREPECMPREF,
		DESCRIPCION
	 )
	SELECT
		ID,
		NOMBRE,
		TIPO,
		TIPODESCRIPTOR,
		IDFICHADESCRPREF,
		IDFICHACLFDOCPREF,
		IDLVOLPREF,
		DESCRIPCION
	FROM ADCTLGLISTAD;

	DROP TABLE ADCTLGLISTAD;
	RENAME TABLE ADCTLGLISTAD2 TO ADCTLGLISTAD;

	-- Tabla: ADCTLGLISTAD
	CREATE UNIQUE INDEX ADCTLGLISTAD1 ON ADCTLGLISTAD (ID);
	CREATE INDEX ADCTLGLISTAD2 ON ADCTLGLISTAD (TIPODESCRIPTOR);


--Renombrar campo IDLVOL A IDREPECMIDREPECM en la tabla ADDESCRIPTOR
	--Crear nueva tabla
	CREATE TABLE ADDESCRIPTOR2 (
		ID VARCHAR(32) NOT NULL,
		NOMBRE VARCHAR(512) NOT NULL,
		IDLISTA VARCHAR(32) NOT NULL,
		TIPO INTEGER NOT NULL,
		ESTADO INTEGER NOT NULL,
		IDSISTEXT VARCHAR(64),
		IDDESCRSISTEXT VARCHAR(32),
		TIMESTAMP TIMESTAMP NOT NULL,
		IDFICHADESCR VARCHAR(32),
		TIENEDESCR CHAR(1),
		EDITCLFDOCS CHAR(1),
		IDREPECM VARCHAR(32),
		NIVELACCESO SMALLINT NOT NULL,
		IDLCA VARCHAR(32)
	);

	--Insert a Select
	INSERT INTO ADDESCRIPTOR2
	 (
	 	ID,
		NOMBRE,
		IDLISTA,
		TIPO,
		ESTADO,
		IDSISTEXT,
		IDDESCRSISTEXT,
		TIMESTAMP,
		IDFICHADESCR,
		TIENEDESCR,
		EDITCLFDOCS,
		IDREPECM,
		NIVELACCESO,
		IDLCA
	 )
	SELECT
		ID,
		NOMBRE,
		IDLISTA,
		TIPO,
		ESTADO,
		IDSISTEXT,
		IDDESCRSISTEXT,
		TIMESTAMP,
		IDFICHADESCR,
		TIENEDESCR,
		EDITCLFDOCS,
		IDLVOL,
		NIVELACCESO,
		IDLCA
	FROM ADDESCRIPTOR;

	--Eliminar la tabla anterior
	DROP TABLE ADDESCRIPTOR;

	--Renombrar la tabla nueva
	RENAME TABLE ADDESCRIPTOR2 TO ADDESCRIPTOR;

	-- Tabla: ADDESCRIPTOR
	CREATE UNIQUE INDEX ADDESCRIPTOR1 ON ADDESCRIPTOR (ID);
	CREATE INDEX ADDESCRIPTOR2 ON ADDESCRIPTOR (IDLISTA);
	CREATE INDEX ADDESCRIPTOR3 ON ADDESCRIPTOR (TIPO);
	CREATE INDEX ADDESCRIPTOR4 ON ADDESCRIPTOR (IDLISTA, NOMBRE);
	CREATE INDEX ADDESCRIPTOR5 ON ADDESCRIPTOR (NIVELACCESO);


--Renombrar campo IDLVOL A IDREPECMIDREPECM en la tabla ASGFELEMENTOCF
	--Renombrar campo IDLVOL A IDREPECM en la tabla ASGFELEMENTOCF
	--Añadir columna IDREPECM
	ALTER TABLE ASGFELEMENTOCF ADD COLUMN IDREPECM VARCHAR(32);

	--Actualizar los valores de la columna
	UPDATE ASGFELEMENTOCF SET IDREPECM = IDLVOL;

	--Eliminar el campo IDLVOL
	ALTER TABLE ASGFELEMENTOCF DROP COLUMN IDLVOL;



	--Crear nueva tabla
	/*
	CREATE TABLE ASGFELEMENTOCF2 (
		ID VARCHAR(32) NOT NULL,
		TIPO SMALLINT NOT NULL,
		IDNIVEL VARCHAR(32) NOT NULL,
		CODIGO VARCHAR(128),
		TITULO VARCHAR(1024) NOT NULL,
		IDPADRE VARCHAR(32),
		IDFONDO VARCHAR(32),
		CODREFFONDO VARCHAR(254),
		FINALCODREFPADRE VARCHAR(1024),
		CODREFERENCIA VARCHAR(1024),
		ESTADO SMALLINT NOT NULL,
		IDELIMINACION VARCHAR(32),
		IDFICHADESCR VARCHAR(32),
		TIENEDESCR CHAR(1),
		EDITCLFDOCS CHAR(1),
		IDREPECM VARCHAR(32),
		IDARCHIVO VARCHAR(32),
		NIVELACCESO SMALLINT NOT NULL,
		IDLCA VARCHAR(32),
		SUBTIPO SMALLINT DEFAULT 0 NOT NULL,
	  	ORDPOS 		 VARCHAR(32)
	);

	--Insert a Select
	INSERT INTO ASGFELEMENTOCF2
	 (
	 	ID,
		TIPO,
		IDNIVEL,
		CODIGO,
		TITULO,
		IDPADRE,
		IDFONDO,
		CODREFFONDO,
		FINALCODREFPADRE,
		CODREFERENCIA,
		ESTADO,
		IDELIMINACION,
		IDFICHADESCR,
		TIENEDESCR,
		EDITCLFDOCS,
		IDREPECM,
		IDARCHIVO,
		NIVELACCESO,
		IDLCA,
		SUBTIPO,
	  	ORDPOS
	 )
	SELECT
	ID,
		TIPO,
		IDNIVEL,
		CODIGO,
		TITULO,
		IDPADRE,
		IDFONDO,
		CODREFFONDO,
		FINALCODREFPADRE,
		CODREFERENCIA,
		ESTADO,
		IDELIMINACION,
		IDFICHADESCR,
		TIENEDESCR,
		EDITCLFDOCS,
		IDLVOL,
		IDARCHIVO,
		NIVELACCESO,
		IDLCA,
		SUBTIPO,
	  	ORDPOS
	FROM ASGFELEMENTOCF;

	--Eliminar la tabla anterior
	DROP TABLE ASGFELEMENTOCF;

	--Renombrar la tabla nueva
	RENAME TABLE ASGFELEMENTOCF2 TO ASGFELEMENTOCF;

	-- Tabla: ASGFELEMENTOCF
	CREATE UNIQUE INDEX ASGFELEMENTOCF1 ON ASGFELEMENTOCF (ID);
	CREATE UNIQUE INDEX ASGFELEMENTOCF2 ON ASGFELEMENTOCF (ID, TIPO);
	CREATE INDEX ASGFELEMENTOCF3 ON ASGFELEMENTOCF (IDPADRE);
	CREATE INDEX ASGFELEMENTOCF4 ON ASGFELEMENTOCF (ESTADO);
	CREATE INDEX ASGFELEMENTOCF5 ON ASGFELEMENTOCF (IDFONDO);
	CREATE INDEX ASGFELEMENTOCF6 ON ASGFELEMENTOCF (IDNIVEL);
	CREATE INDEX ASGFELEMENTOCF7 ON ASGFELEMENTOCF (NIVELACCESO, IDARCHIVO, IDLCA);
	*/

--Renombrar campo IDLVOLPREF A IDREPECMPREFIDREPECM en la tabla ASGFNIVELCF
	--Crear nueva tabla
	CREATE TABLE ASGFNIVELCF2 (
		ID VARCHAR(32) NOT NULL,
		NOMBRE VARCHAR(64) NOT NULL,
		TIPO SMALLINT NOT NULL,
		IDFICHADESCRPREF VARCHAR(32),
		IDFICHACLFDOCPREF VARCHAR(32),
		IDREPECMPREF VARCHAR(32),
		SUBTIPO SMALLINT DEFAULT 0 NOT NULL
	);

	--Insert a Select
	INSERT INTO ASGFNIVELCF2
	 (
	 	ID,
		NOMBRE,
		TIPO,
		IDFICHADESCRPREF,
		IDFICHACLFDOCPREF,
		IDREPECMPREF,
		SUBTIPO
	 )
	SELECT
		ID,
		NOMBRE,
		TIPO,
		IDFICHADESCRPREF,
		IDFICHACLFDOCPREF,
		IDLVOLPREF,
		SUBTIPO
	FROM ASGFNIVELCF;

	--Eliminar la tabla anterior
	DROP TABLE ASGFNIVELCF;

	--Renombrar la tabla nueva
	RENAME TABLE ASGFNIVELCF2 TO ASGFNIVELCF;

	--Tabla: ASGFNIVELCF
	CREATE UNIQUE INDEX ASGFNIVELCF1 ON ASGFNIVELCF (ID);
	CREATE INDEX ASGFNIVELCF2 ON ASGFNIVELCF (TIPO);


--Renombrar campo INFOFICHAUDOCLVOL A INFOFICHAUDOCLVOLIDREPECM en la tabla ASGFSERIE
	--Crear nueva tabla
	CREATE TABLE ASGFSERIE2 (
		IDELEMENTOCF VARCHAR(32) NOT NULL,
		IDFONDO VARCHAR(32) NOT NULL,
		ESTADOSERIE SMALLINT NOT NULL,
		FECHAESTADO TIMESTAMP NOT NULL,
		ULTIMOESTADOAUTORIZ SMALLINT,
		IDUSRGESTOR VARCHAR(32),
		FEXTREMAINICIAL TIMESTAMP,
		FEXTREMAFINAL TIMESTAMP,
		IDPROCEDIMIENTO VARCHAR(32),
		TIPOPROCEDIMIENTO SMALLINT,
		NUMUNIDADDOC INTEGER NOT NULL,
		NUMUINSTALACION INTEGER NOT NULL,
		VOLUMEN FLOAT NOT NULL,
		IDENTIFICACION CLOB,
		OBSERVACIONES VARCHAR(254),
		INFOFICHAUDOCREPECM CLOB
	);

	--Insert a Select
	INSERT INTO ASGFSERIE2
	 (
		IDELEMENTOCF,
		IDFONDO,
		ESTADOSERIE,
		FECHAESTADO,
		ULTIMOESTADOAUTORIZ,
		IDUSRGESTOR,
		FEXTREMAINICIAL,
		FEXTREMAFINAL,
		IDPROCEDIMIENTO,
		TIPOPROCEDIMIENTO,
		NUMUNIDADDOC,
		NUMUINSTALACION,
		VOLUMEN,
		IDENTIFICACION,
		OBSERVACIONES,
		INFOFICHAUDOCREPECM
	 )
	SELECT
		IDELEMENTOCF,
		IDFONDO,
		ESTADOSERIE,
		FECHAESTADO,
		ULTIMOESTADOAUTORIZ,
		IDUSRGESTOR,
		FEXTREMAINICIAL,
		FEXTREMAFINAL,
		IDPROCEDIMIENTO,
		TIPOPROCEDIMIENTO,
		NUMUNIDADDOC,
		NUMUINSTALACION,
		VOLUMEN,
		IDENTIFICACION,
		OBSERVACIONES,
		INFOFICHAUDOCLVOL
	FROM ASGFSERIE;

	--Eliminar la tabla anterior
	DROP TABLE ASGFSERIE;

	--Renombrar la tabla nueva
	RENAME TABLE ASGFSERIE2 TO ASGFSERIE;

	-- Tabla: ASGFSERIE
	CREATE UNIQUE INDEX ASGFSERIE1 ON ASGFSERIE (IDELEMENTOCF);
	CREATE INDEX ASGFSERIE2 ON ASGFSERIE (IDFONDO);
	CREATE INDEX ASGFSERIE3 ON ASGFSERIE (ESTADOSERIE);
	CREATE INDEX ASGFSERIE4 ON ASGFSERIE (TIPOPROCEDIMIENTO);


--Renombrar campo IDFICH A IDFICHIDREPECM en la tabla ADPCDOCUMENTOVIT
	--Crear nueva tabla
	CREATE TABLE ADPCDOCUMENTOVIT2 (
		ID VARCHAR(32) NOT NULL,
		IDBDTERCEROS VARCHAR(64) NOT NULL,
		NUMIDENTIDAD VARCHAR(32),
		IDENTIDAD VARCHAR(254),
		IDTIPODOCVIT VARCHAR(32) NOT NULL,
		FECHACAD TIMESTAMP,
		ESTADODOCVIT INTEGER NOT NULL,
		FECHACR TIMESTAMP NOT NULL,
		IDUSUARIOCR VARCHAR(32) NOT NULL,
		FECHAVIG TIMESTAMP,
		IDUSUARIOVIG VARCHAR(32),
		NUMACCESOS INTEGER NOT NULL,
		FECHAULTACCESO TIMESTAMP,
		TAMANOFICH FLOAT NOT NULL,
		NOMBREORGFICH VARCHAR(254) NOT NULL,
		EXTFICH VARCHAR(16) NOT NULL,
		IDFICH VARCHAR(128) NOT NULL,
		OBSERVACIONES VARCHAR(254),
		IDREPECM		VARCHAR(32)
	);

	--Insert a Select
	INSERT INTO ADPCDOCUMENTOVIT2
	 (
	 	ID,
		IDBDTERCEROS,
		NUMIDENTIDAD,
		IDENTIDAD,
		IDTIPODOCVIT,
		FECHACAD,
		ESTADODOCVIT,
		FECHACR,
		IDUSUARIOCR,
		FECHAVIG,
		IDUSUARIOVIG,
		NUMACCESOS,
		FECHAULTACCESO,
		TAMANOFICH,
		NOMBREORGFICH,
		EXTFICH,
		IDFICH,
		OBSERVACIONES
	 )
	SELECT
		ID,
		IDBDTERCEROS,
		NUMIDENTIDAD,
		IDENTIDAD,
		IDTIPODOCVIT,
		FECHACAD,
		ESTADODOCVIT,
		FECHACR,
		IDUSUARIOCR,
		FECHAVIG,
		IDUSUARIOVIG,
		NUMACCESOS,
		FECHAULTACCESO,
		TAMANOFICH,
		NOMBREORGFICH,
		EXTFICH,
		IDFICH,
		OBSERVACIONES
	FROM ADPCDOCUMENTOVIT;

	--Eliminar la tabla anterior
	DROP TABLE ADPCDOCUMENTOVIT;

	--Renombrar la tabla nueva
	RENAME TABLE ADPCDOCUMENTOVIT2 TO ADPCDOCUMENTOVIT;

	-- Tabla: ADPCDOCUMENTOVIT
	CREATE UNIQUE INDEX ADPCDOCUMENTOVIT1 ON ADPCDOCUMENTOVIT(ID);

--Añadir IDREPECM
ALTER TABLE ADOCDOCUMENTODESCR ADD IDREPECM VARCHAR(32);

--Añadir IDREPECM
ALTER TABLE ADOCDOCUMENTOCF ADD IDREPECM VARCHAR(32);

--Añadir el campo subtiponivel
ALTER TABLE ADFICHA ADD COLUMN SUBTIPONIVEL INTEGER DEFAULT 0 NOT NULL;

--Actualizar los valores de subtiponivel
UPDATE ADFICHA SET SUBTIPONIVEL=61 WHERE ID='1';
UPDATE ADFICHA SET SUBTIPONIVEL=62 WHERE ID='6';

--Nuevo Índice por etiquetaxml en campo tabla
CREATE UNIQUE INDEX ADCAMPOTBL5 ON ADCAMPOTBL (ETIQUETAXML);

--Actualizar valores de etiqueta duplicadas
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Documento_Fisico_Descripcion' WHERE ID='43' AND ETIQUETAXML = 'Descripcion';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Documento_Electronico_Descripcion' WHERE ID='50' AND ETIQUETAXML = 'Descripcion';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Identificacion' WHERE ID='1' AND ETIQUETAXML = 'Identificador';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Identificador_Recurso' WHERE ID='131' AND ETIQUETAXML = 'Identificador';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Entidad_Relacionada_Nombre' WHERE ID='114' AND ETIQUETAXML = 'Nombre';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Documento_Fisico_Nombre' WHERE ID='19' AND ETIQUETAXML = 'Nombre';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Productor_Nombre' WHERE ID='34' AND ETIQUETAXML = 'Nombre';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Documento_Electronico_Nombre' WHERE ID='49' AND ETIQUETAXML = 'Nombre';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Entidad_Relacionada_Tipo_Relacion' WHERE ID='115' AND ETIQUETAXML = 'Tipo_Relacion';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Entidad_Relacionada_Tipo_Relacion' WHERE ID='115' AND ETIQUETAXML = 'Tipo_Relación';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Naturaleza_Relacion' WHERE ID='133' AND ETIQUETAXML = 'Tipo_Relacion';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Naturaleza_Relacion' WHERE ID='133' AND ETIQUETAXML = 'Tipo_Relación';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Interesado_Validado' WHERE ID='12' AND ETIQUETAXML = 'Validado';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Emplazamiento_Validado' WHERE ID='212' AND ETIQUETAXML = 'Validado';

--Nuevo Índice por etiquetaxml en campo dato
CREATE UNIQUE INDEX ADCAMPODATO6 ON ADCAMPODATO (ETIQUETAXML);


--Modificado el tamaño del nombre del formato
--ALTER TABLE ADFMTFICHA MODIFY NOMBRE VARCHAR(128) NOT NULL;

--Nuevo Rol para el servicio web de transferencias
INSERT INTO ASCAROL (ID,NOMBRE, TIPOMODULO,DESCRIPCION)
VALUES('ID_ROL_WS_TRANSFERENCIAS','Servicio Web de Transferencias de Expedientes','2','Permisos necesarios para la ejecución del servicio web de transferencias');

-- Servicio Web de Transferencias

--Ampliado de Elaboración de Transferencias Ordinarias
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,201);

--Ubicación de Relaciones de Entrega
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,207);

-- Consulta de Cuadro de Clasificación
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,500);

--Solicitud de Alta de Serie
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,501);

-- Gestor de Serie
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,502);

-- Gestión de Solicitudes de Serie
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,503);

-- Creación en el Cuadro de Clasificación
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,505);

-- Consulta de Descripción en el Cuadro de Clasificación
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,600);

-- Edición de Descripción en el Cuadro de Clasificación
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,601);

-- Administración de Descripción
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,606);

-- Uso de Ficha Descriptiva en Altas/Relaciones
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,607);

--Administración de Usuarios, Órganos, Grupos y Perfiles
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,701);

-- Consulta de Documentos Electrónicos
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,900);

--Edición de Documentos Electrónicos
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,901);

--Tabla de Firmas
INSERT INTO ADCAMPOTBL (ID,NOMBRE,TIPONORMA,IDAREA,ETIQUETAXML, ETIQXMLFILA)
VALUES ('105','Firmas',1,'3','Firmas','Firma');

--Norma ENI
INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1001','Versión NTI',1,'1','3',NULL,NULL,'Version_NTI');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1002','Estado',1,'1','3',NULL,NULL,'Estado');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1003','Tipo de Firma',1,'1','3','105',1,'Tipo_Firma');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1004','Valor_CSV',2,'1','3','105',2,'Valor_CSV');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1005','Definición de Generación CSV',1,'1','3','105',3,'Definicion_Generacion_CSV');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1006','Identificador interno Firma',1,'1','3','105',4,'Id_Interno_Firma');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1011','Documento Electrónico: Versión NTI',1,'1','3','6',3, 'Documento_Electronico_Version_NTI');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1012','Documento Electrónico: Órgano',5,'1','3','6',4,'Documento_Electronico_Organo');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1013','Documento Electrónico: Fecha de Captura',3,'1','3','6',5,'Documento_Electronico_Fecha_Captura');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1014','Documento Electrónico: Origen',1,'1','3','6',6,'Documento_Electronico_Origen');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1015','Documento Electrónico: Estado Elaboración',1,'1','3','6',7,'Documento_Electronico_Estado_Elaboracion');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1016','Documento Electrónico: Nombre Formato',1,'1','3','6',8,'Documento_Electronico_Nombre_Formato');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1017','Documento Electrónico: Tipo Documental',1,'1','3','6',9,'Documento_Electronico_Tipo_Documental');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1018','Documento Electrónico: Tipo Firma',1,'1','3','6',10,'Documento_Electronico_Tipo_Firma');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1019','Documento Electrónico: Valor CSV',2,'1','3','6',11,'Documento_Electronico_Valor_CSV');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1020','Documento Electrónico: Definición Generación CSV',2,'1','3','6',12,'Documento_Electronico_Definicion_Generacion_CSV');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1021','Documento Electrónico: Identificador Documento Origen',1,'1','3','6',13,'Documento_Electronico_Identificador_Documento_Origen');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1022','Documento Electrónico: Id Interno',1,'1','3','6',14,'Documento_Electronico_Id_Interno');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1023','Documento Electrónico: Identificador interno Firma',1,'1','3','6',15,'Documento_Electronico_Id_Interno_Firma');


DROP INDEX SIGNUMORDEN1;
CREATE UNIQUE INDEX ASGDSIGNUMORDEN1 ON ASGDSIGNUMORDEN (IDTIPOELEMPADRE, IDELEMPADRE, IDTIPOELEMENTO);

CREATE INDEX ASGDUDOCENUI5 ON ASGDUDOCENUI (SIGNATURAUDOC);

CREATE INDEX ASGFDIVISIONFS2 ON ASGFDIVISIONFS (IDUSRGESTOR, ESTADO);

CREATE INDEX ASGFUDOCENDIVISIONFS2 ON ASGFUDOCENDIVISIONFS (IDUDOC);

CREATE INDEX ASGFSERIE5 ON ASGFSERIE (IDUSRGESTOR, ESTADOSERIE);



