--/*************************/
--/* Versión 4.3           */
--/*************************/

	-- Insertar la versión actual de bd
	INSERT INTO AGINFOSISTEMA (AUTID,NOMBRE,VALOR,FECHAACTUALIZACION) VALUES (SEQ_INFO.NextVal,'VERSIONBD','4.2->4.3',SYSDATE);

	--Añadir columna MARCASBLOQUEO
	ALTER TABLE ASGTUNIDADDOCRE ADD (MARCASBLOQUEO NUMBER DEFAULT 0 NOT NULL );

	--Añadir columna MARCASBLOQUEO
	ALTER TABLE ASGFUNIDADDOC ADD (MARCASBLOQUEO NUMBER DEFAULT 0 NOT NULL );
COMMIT;