DROP TABLE IVOLACTDIR;
DROP TABLE IVOLARCHLIST;
DROP TABLE IVOLFILEFTS;
DROP TABLE IVOLFILEHDR;
DROP TABLE IVOLLISTHDR;
DROP TABLE IVOLLISTVOL;
DROP TABLE IVOLNEXTID;
DROP TABLE IVOLREPHDR;
DROP TABLE IVOLVOLHDR;
DROP TABLE IVOLVOLTBL;

CREATE TABLE IVOLACTDIR (
	"VOLID" INTEGER NOT NULL ,
	"ACTDIR" INTEGER NOT NULL ,
	"NUMFILES" INTEGER NOT NULL
);


CREATE TABLE IVOLARCHLIST (
	"ARCHID" INTEGER NOT NULL ,
	"LISTID" INTEGER NOT NULL
);

CREATE TABLE IVOLFILEFTS (
	"ID" INTEGER NOT NULL ,
	"EXTID1" INTEGER NOT NULL ,
	"EXTID2" INTEGER NOT NULL ,
	"EXTID3" INTEGER NOT NULL ,
	"EXTID4" INTEGER NOT NULL ,
	"PATH" VARCHAR(254) NOT NULL ,
	"TIMESTAMP" TIMESTAMP NOT NULL
);


CREATE TABLE IVOLFILEHDR (
	"ID" INTEGER NOT NULL ,
	"VOLID" INTEGER NOT NULL ,
	"LOC" VARCHAR(254) NOT NULL ,
	"EXTID1" INTEGER NOT NULL ,
	"EXTID2" INTEGER NOT NULL ,
	"EXTID3" INTEGER NOT NULL ,
	"FLAGS" INTEGER NOT NULL ,
	"STAT" INTEGER NOT NULL ,
	"TIMESTAMP" TIMESTAMP ,
	"FILESIZE" FLOAT NOT NULL
);


CREATE TABLE IVOLLISTHDR (
	"ID" INTEGER NOT NULL ,
	"NAME" VARCHAR(32) NOT NULL ,
	"FLAGS" INTEGER NOT NULL ,
	"STAT" INTEGER NOT NULL ,
	"REMARKS" VARCHAR(254),
	"CRTRID" INTEGER NOT NULL ,
	"CRTNDATE" TIMESTAMP NOT NULL ,
	"UPDRID" INTEGER,
	"UPDDATE" TIMESTAMP
);


CREATE TABLE IVOLLISTVOL (
	"LISTID" INTEGER NOT NULL ,
	"VOLID" INTEGER NOT NULL ,
	"SORTORDER" INTEGER NOT NULL
);

CREATE TABLE IVOLNEXTID (
	"TYPE" INTEGER NOT NULL ,
	"ID" INTEGER NOT NULL
);

CREATE TABLE IVOLREPHDR (
	"ID" INTEGER NOT NULL ,
	"NAME" VARCHAR(32) NOT NULL ,
	"TYPE" INTEGER NOT NULL ,
	"INFO" VARCHAR(4096) NOT NULL , 
	"STAT" INTEGER NOT NULL ,
	"REMARKS" VARCHAR(254),
	"CRTRID" INTEGER NOT NULL ,
	"CRTNDATE" TIMESTAMP NOT NULL ,
	"UPDRID" INTEGER ,
	"UPDDATE" TIMESTAMP
);

CREATE TABLE IVOLVOLHDR (
	"ID" INTEGER NOT NULL ,
	"NAME" VARCHAR(32) NOT NULL ,
	"REPID" INTEGER NOT NULL ,
	"INFO" VARCHAR(4096) NOT NULL ,
	"ITEMP" INTEGER NOT NULL ,
	"ACTSIZE" VARCHAR(32) NOT NULL ,
	"NUMFILES" INTEGER NOT NULL ,
	"STAT" INTEGER NOT NULL ,
	"REMARKS" VARCHAR(254),
	"CRTRID" INTEGER NOT NULL ,
	"CRTNDATE" TIMESTAMP NOT NULL ,
	"UPDRID" INTEGER ,
	"UPDDATE" TIMESTAMP
);


CREATE TABLE IVOLVOLTBL (
	"LOCID" VARCHAR(32) NOT NULL ,
	"EXTID1" INTEGER NOT NULL ,
	"EXTID2" INTEGER NOT NULL ,
	"EXTID3" INTEGER NOT NULL ,
	"EXTID4" INTEGER NOT NULL ,
	"FILEEXT" VARCHAR(10) NOT NULL ,
	"FILEVAL" BLOB(2097152) LOGGED NOT COMPACT NOT NULL
);

CREATE  UNIQUE INDEX IVOLACTDIR1 ON IVOLACTDIR("VOLID" ASC);
CREATE  UNIQUE INDEX IVOLLISTHDR1 ON IVOLLISTHDR("ID" ASC);
CREATE  UNIQUE INDEX IVOLNEXTID1 ON IVOLNEXTID("TYPE" ASC);
CREATE  UNIQUE INDEX IVOLVOLHDR1 ON IVOLVOLHDR("ID" ASC);
CREATE  UNIQUE INDEX IVOLARCHLIST1 ON IVOLARCHLIST("ARCHID" ASC);
CREATE  INDEX IVOLARCHLIST2 ON IVOLARCHLIST("LISTID" ASC);
CREATE  UNIQUE INDEX IVOLFILEFTS1 ON IVOLFILEFTS("ID" ASC);
CREATE  UNIQUE INDEX IVOLFILEHDR1 ON IVOLFILEHDR("ID" ASC);
CREATE  INDEX IVOLFILEHDR2 ON IVOLFILEHDR("VOLID" ASC);
CREATE  INDEX IVOLLISTVOL1 ON IVOLLISTVOL("LISTID" ASC);
CREATE  INDEX IVOLLISTVOL2 ON IVOLLISTVOL("VOLID" ASC);
CREATE  UNIQUE INDEX IVOLREPHDR1 ON IVOLREPHDR("ID" ASC);
CREATE  INDEX IVOLVOLHDR2 ON IVOLVOLHDR("REPID" ASC);
CREATE  UNIQUE INDEX IVOLVOLTBL1 ON IVOLVOLTBL("LOCID" ASC);

INSERT INTO IVOLACTDIR(VOLID, ACTDIR, NUMFILES) VALUES (1, 1, 0);

INSERT INTO IVOLLISTHDR(ID, NAME, FLAGS, STAT, REMARKS, CRTRID, CRTNDATE, UPDRID, UPDDATE)
VALUES (6, 'ListaBD', 0, 0, null, 0, CURRENT_TIMESTAMP, null, null);

INSERT INTO IVOLLISTVOL(LISTID, VOLID, SORTORDER)
VALUES (6, 1, 1);

INSERT INTO IVOLNEXTID(TYPE, ID)
VALUES (1, 7);

INSERT INTO IVOLNEXTID(TYPE, ID)
VALUES (2, 7);

INSERT INTO IVOLNEXTID(TYPE, ID)
VALUES (3, 7);

INSERT INTO IVOLNEXTID(TYPE, ID)
VALUES (4, 130);

INSERT INTO IVOLREPHDR(ID, NAME, TYPE, INFO, STAT, REMARKS, CRTRID, CRTNDATE, UPDRID, UPDDATE)
VALUES (1, 'RepBD', 5, '"01.01"|""|5|0|0|0|0', 0, null, 0, CURRENT TIMESTAMP, null, null);

INSERT INTO IVOLVOLHDR(ID, NAME, REPID, INFO, ITEMP, ACTSIZE, NUMFILES, STAT, REMARKS, CRTRID, CRTNDATE, UPDRID, UPDDATE)
VALUES (1, 'RepBD', 1, '"01.01"|5|"IVOLVOLTBL,LOCID,varchar(32),FILEVAL,BLOB(0)"|"1073741824"|0', 0, '0', 0, 0, null, 0, CURRENT TIMESTAMP, NULL, NULL);

COMMIT;