

CREATE TABLE IVOLACTDIR (
	"VOLID" INTEGER NOT NULL ,
	"ACTDIR" INTEGER NOT NULL ,
	"NUMFILES" INTEGER NOT NULL
);


CREATE TABLE IVOLARCHLIST (
	"ARCHID" INTEGER NOT NULL ,
	"LISTID" INTEGER NOT NULL
);

CREATE TABLE IVOLFILEFTS (
	"ID" INTEGER NOT NULL ,
	"EXTID1" INTEGER NOT NULL ,
	"EXTID2" INTEGER NOT NULL ,
	"EXTID3" INTEGER NOT NULL ,
	"EXTID4" INTEGER NOT NULL ,
	"PATH" VARCHAR(254) NOT NULL ,
	"TIMESTAMP" TIMESTAMP NOT NULL
);


CREATE TABLE IVOLFILEHDR (
	"ID" INTEGER NOT NULL ,
	"VOLID" INTEGER NOT NULL ,
	"LOC" VARCHAR(254) NOT NULL ,
	"EXTID1" INTEGER NOT NULL ,
	"EXTID2" INTEGER NOT NULL ,
	"EXTID3" INTEGER NOT NULL ,
	"FLAGS" INTEGER NOT NULL ,
	"STAT" INTEGER NOT NULL ,
	"TIMESTAMP" TIMESTAMP ,
	"FILESIZE" FLOAT NOT NULL
);


CREATE TABLE IVOLLISTHDR (
	"ID" INTEGER NOT NULL ,
	"NAME" VARCHAR(32) NOT NULL ,
	"FLAGS" INTEGER NOT NULL ,
	"STAT" INTEGER NOT NULL ,
	"REMARKS" VARCHAR(254),
	"CRTRID" INTEGER NOT NULL ,
	"CRTNDATE" TIMESTAMP NOT NULL ,
	"UPDRID" INTEGER,
	"UPDDATE" TIMESTAMP
);


CREATE TABLE IVOLLISTVOL (
	"LISTID" INTEGER NOT NULL ,
	"VOLID" INTEGER NOT NULL ,
	"SORTORDER" INTEGER NOT NULL
);

CREATE TABLE IVOLNEXTID (
	"TYPE" INTEGER NOT NULL ,
	"ID" INTEGER NOT NULL
);

CREATE TABLE IVOLREPHDR (
	"ID" INTEGER NOT NULL ,
	"NAME" VARCHAR(32) NOT NULL ,
	"TYPE" INTEGER NOT NULL ,
	"INFO" VARCHAR(4096) NOT NULL , 
	"STAT" INTEGER NOT NULL ,
	"REMARKS" VARCHAR(254),
	"CRTRID" INTEGER NOT NULL ,
	"CRTNDATE" TIMESTAMP NOT NULL ,
	"UPDRID" INTEGER ,
	"UPDDATE" TIMESTAMP
);

CREATE TABLE IVOLVOLHDR (
	"ID" INTEGER NOT NULL ,
	"NAME" VARCHAR(32) NOT NULL ,
	"REPID" INTEGER NOT NULL ,
	"INFO" VARCHAR(4096) NOT NULL ,
	"ITEMP" INTEGER NOT NULL ,
	"ACTSIZE" VARCHAR(32) NOT NULL ,
	"NUMFILES" INTEGER NOT NULL ,
	"STAT" INTEGER NOT NULL ,
	"REMARKS" VARCHAR(254),
	"CRTRID" INTEGER NOT NULL ,
	"CRTNDATE" TIMESTAMP NOT NULL ,
	"UPDRID" INTEGER ,
	"UPDDATE" TIMESTAMP
);


CREATE TABLE IVOLVOLTBL (
	"LOCID" VARCHAR(32) NOT NULL ,
	"EXTID1" INTEGER NOT NULL ,
	"EXTID2" INTEGER NOT NULL ,
	"EXTID3" INTEGER NOT NULL ,
	"EXTID4" INTEGER NOT NULL ,
	"FILEEXT" VARCHAR(10) NOT NULL ,
	"FILEVAL" BLOB(2097152) LOGGED NOT COMPACT NOT NULL
);