INSERT INTO IVOLACTDIR(VOLID, ACTDIR, NUMFILES) VALUES (1, 1, 0);

INSERT INTO IVOLLISTHDR(ID, NAME, FLAGS, STAT, REMARKS, CRTRID, CRTNDATE, UPDRID, UPDDATE)
VALUES (6, 'ListaBD', 0, 0, null, 0, CURRENT_TIMESTAMP, null, null);

INSERT INTO IVOLLISTVOL(LISTID, VOLID, SORTORDER)
VALUES (6, 1, 1);

INSERT INTO IVOLNEXTID(TYPE, ID)
VALUES (1, 7);

INSERT INTO IVOLNEXTID(TYPE, ID)
VALUES (2, 7);

INSERT INTO IVOLNEXTID(TYPE, ID)
VALUES (3, 7);

INSERT INTO IVOLNEXTID(TYPE, ID)
VALUES (4, 130);

INSERT INTO IVOLREPHDR(ID, NAME, TYPE, INFO, STAT, REMARKS, CRTRID, CRTNDATE, UPDRID, UPDDATE)
VALUES (1, 'RepBD', 5, '"01.01"|""|5|0|0|0|0', 0, null, 0, CURRENT TIMESTAMP, null, null);

INSERT INTO IVOLVOLHDR(ID, NAME, REPID, INFO, ITEMP, ACTSIZE, NUMFILES, STAT, REMARKS, CRTRID, CRTNDATE, UPDRID, UPDDATE)
VALUES (1, 'RepBD', 1, '"01.01"|5|"IVOLVOLTBL,LOCID,varchar(32),FILEVAL,BLOB(0)"|"1073741824"|0', 0, '0', 0, 0, null, 0, CURRENT TIMESTAMP, NULL, NULL);

COMMIT;