package es.ieci.scsp.verifdata.model.mapping.scsp;

// Generated 06-mar-2012 7:54:31 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CoreTipoMensaje generated by hbm2java
 */
@Entity
@Table(name = "core_tipo_mensaje")
public class CoreTipoMensaje implements java.io.Serializable {

	private int tipo;
	private String descripcion;
	private Set<CoreTokenData> coreTokenDatas = new HashSet<CoreTokenData>(0);

	public CoreTipoMensaje() {
	}

	public CoreTipoMensaje(int tipo, String descripcion) {
		this.tipo = tipo;
		this.descripcion = descripcion;
	}

	public CoreTipoMensaje(int tipo, String descripcion,
			Set<CoreTokenData> coreTokenDatas) {
		this.tipo = tipo;
		this.descripcion = descripcion;
		this.coreTokenDatas = coreTokenDatas;
	}

	@Id
	@Column(name = "tipo", unique = true, nullable = false)
	public int getTipo() {
		return this.tipo;
	}

	public void setTipo(int tipo) {
		this.tipo = tipo;
	}

	@Column(name = "descripcion", nullable = false, length = 32)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coreTipoMensaje")
	public Set<CoreTokenData> getCoreTokenDatas() {
		return this.coreTokenDatas;
	}

	public void setCoreTokenDatas(Set<CoreTokenData> coreTokenDatas) {
		this.coreTokenDatas = coreTokenDatas;
	}

}
