package es.ieci.scsp.verifdata.model.mapping.scsp;

// Generated 06-mar-2012 7:54:31 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CoreClavePublica generated by hbm2java
 */
@Entity
@Table(name = "core_clave_publica")
public class CoreClavePublica implements java.io.Serializable {

	private String alias;
	private String nombre;
	private String numeroSerie;
	private Set<CoreServicio> coreServicios = new HashSet<CoreServicio>(0);

	public CoreClavePublica() {
	}

	public CoreClavePublica(String alias, String nombre, String numeroSerie) {
		this.alias = alias;
		this.nombre = nombre;
		this.numeroSerie = numeroSerie;
	}

	public CoreClavePublica(String alias, String nombre, String numeroSerie,
			Set<CoreServicio> coreServicios) {
		this.alias = alias;
		this.nombre = nombre;
		this.numeroSerie = numeroSerie;
		this.coreServicios = coreServicios;
	}

	@Id
	@Column(name = "alias", unique = true, nullable = false, length = 256)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Column(name = "nombre", nullable = false, length = 256)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "numeroSerie", nullable = false, length = 256)
	public String getNumeroSerie() {
		return this.numeroSerie;
	}

	public void setNumeroSerie(String numeroSerie) {
		this.numeroSerie = numeroSerie;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coreClavePublica")
	public Set<CoreServicio> getCoreServicios() {
		return this.coreServicios;
	}

	public void setCoreServicios(Set<CoreServicio> coreServicios) {
		this.coreServicios = coreServicios;
	}

}
