package es.ieci.scsp.verifdata.model.mapping.scsp;

// Generated 06-mar-2012 7:54:31 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CoreTokenDataId generated by hbm2java
 */
@Embeddable
public class CoreTokenDataId implements java.io.Serializable {

	private String idpeticion;
	private int tipomensaje;

	public CoreTokenDataId() {
	}

	public CoreTokenDataId(String idpeticion, int tipomensaje) {
		this.idpeticion = idpeticion;
		this.tipomensaje = tipomensaje;
	}

	@Column(name = "idpeticion", nullable = false, length = 26)
	public String getIdpeticion() {
		return this.idpeticion;
	}

	public void setIdpeticion(String idpeticion) {
		this.idpeticion = idpeticion;
	}

	@Column(name = "tipomensaje", nullable = false)
	public int getTipomensaje() {
		return this.tipomensaje;
	}

	public void setTipomensaje(int tipomensaje) {
		this.tipomensaje = tipomensaje;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CoreTokenDataId))
			return false;
		CoreTokenDataId castOther = (CoreTokenDataId) other;

		return ((this.getIdpeticion() == castOther.getIdpeticion()) || (this
				.getIdpeticion() != null
				&& castOther.getIdpeticion() != null && this.getIdpeticion()
				.equals(castOther.getIdpeticion())))
				&& (this.getTipomensaje() == castOther.getTipomensaje());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdpeticion() == null ? 0 : this.getIdpeticion()
						.hashCode());
		result = 37 * result + this.getTipomensaje();
		return result;
	}

}
