package es.ieci.scsp.verifdata.model.mapping.scsp;

// Generated 06-mar-2012 7:54:31 by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CoreModuloConfiguracion generated by hbm2java
 */
@Entity
@Table(name = "core_modulo_configuracion")
public class CoreModuloConfiguracion implements java.io.Serializable {

	private CoreModuloConfiguracionId id;
	private CoreServicio coreServicio;
	private CoreModulo coreModulo;
	private int activoEntrada;
	private int activoSalida;

	public CoreModuloConfiguracion() {
	}

	public CoreModuloConfiguracion(CoreModuloConfiguracionId id,
			CoreServicio coreServicio, CoreModulo coreModulo,
			int activoEntrada, int activoSalida) {
		this.id = id;
		this.coreServicio = coreServicio;
		this.coreModulo = coreModulo;
		this.activoEntrada = activoEntrada;
		this.activoSalida = activoSalida;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "modulo", column = @Column(name = "modulo", nullable = false, length = 256)),
			@AttributeOverride(name = "certificado", column = @Column(name = "certificado", nullable = false, length = 64)) })
	public CoreModuloConfiguracionId getId() {
		return this.id;
	}

	public void setId(CoreModuloConfiguracionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "certificado", nullable = false, insertable = false, updatable = false)
	public CoreServicio getCoreServicio() {
		return this.coreServicio;
	}

	public void setCoreServicio(CoreServicio coreServicio) {
		this.coreServicio = coreServicio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "modulo", nullable = false, insertable = false, updatable = false)
	public CoreModulo getCoreModulo() {
		return this.coreModulo;
	}

	public void setCoreModulo(CoreModulo coreModulo) {
		this.coreModulo = coreModulo;
	}

	@Column(name = "activoEntrada", nullable = false)
	public int getActivoEntrada() {
		return this.activoEntrada;
	}

	public void setActivoEntrada(int activoEntrada) {
		this.activoEntrada = activoEntrada;
	}

	@Column(name = "activoSalida", nullable = false)
	public int getActivoSalida() {
		return this.activoSalida;
	}

	public void setActivoSalida(int activoSalida) {
		this.activoSalida = activoSalida;
	}

}
