package es.ieci.scsp.verifdata.model.mapping.scsp;

// Generated 06-mar-2012 7:54:31 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CoreModulo generated by hbm2java
 */
@Entity
@Table(name = "core_modulo")
public class CoreModulo implements java.io.Serializable {

	private String nombre;
	private String descripcion;
	private int activoEntrada;
	private int activoSalida;
	private Set<CoreModuloConfiguracion> coreModuloConfiguracions = new HashSet<CoreModuloConfiguracion>(
			0);

	public CoreModulo() {
	}

	public CoreModulo(String nombre, int activoEntrada, int activoSalida) {
		this.nombre = nombre;
		this.activoEntrada = activoEntrada;
		this.activoSalida = activoSalida;
	}

	public CoreModulo(String nombre, String descripcion, int activoEntrada,
			int activoSalida,
			Set<CoreModuloConfiguracion> coreModuloConfiguracions) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.activoEntrada = activoEntrada;
		this.activoSalida = activoSalida;
		this.coreModuloConfiguracions = coreModuloConfiguracions;
	}

	@Id
	@Column(name = "nombre", unique = true, nullable = false, length = 256)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "descripcion", length = 512)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "activoEntrada", nullable = false)
	public int getActivoEntrada() {
		return this.activoEntrada;
	}

	public void setActivoEntrada(int activoEntrada) {
		this.activoEntrada = activoEntrada;
	}

	@Column(name = "activoSalida", nullable = false)
	public int getActivoSalida() {
		return this.activoSalida;
	}

	public void setActivoSalida(int activoSalida) {
		this.activoSalida = activoSalida;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coreModulo")
	public Set<CoreModuloConfiguracion> getCoreModuloConfiguracions() {
		return this.coreModuloConfiguracions;
	}

	public void setCoreModuloConfiguracions(
			Set<CoreModuloConfiguracion> coreModuloConfiguracions) {
		this.coreModuloConfiguracions = coreModuloConfiguracions;
	}

}
