package es.ieci.scsp.verifdata.model.mapping.scsp;

// Generated 06-mar-2012 7:54:31 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CoreEmisorCertificado generated by hbm2java
 */
@Entity
@Table(name = "core_emisor_certificado")
public class CoreEmisorCertificado implements java.io.Serializable {

	private String cif;
	private String nombre;
	private Set<CoreServicio> coreServicios = new HashSet<CoreServicio>(0);

	public CoreEmisorCertificado() {
	}

	public CoreEmisorCertificado(String cif, String nombre) {
		this.cif = cif;
		this.nombre = nombre;
	}

	public CoreEmisorCertificado(String cif, String nombre,
			Set<CoreServicio> coreServicios) {
		this.cif = cif;
		this.nombre = nombre;
		this.coreServicios = coreServicios;
	}

	@Id
	@Column(name = "cif", unique = true, nullable = false, length = 16)
	public String getCif() {
		return this.cif;
	}

	public void setCif(String cif) {
		this.cif = cif;
	}

	@Column(name = "nombre", nullable = false, length = 32)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coreEmisorCertificado")
	public Set<CoreServicio> getCoreServicios() {
		return this.coreServicios;
	}

	public void setCoreServicios(Set<CoreServicio> coreServicios) {
		this.coreServicios = coreServicios;
	}

}
