ALTER TABLE SIGEM_ETRAMITACION_000.SGMAFSESION_INFO
MODIFY(EMISOR_CERTIFICADO_SOLICITANTE VARCHAR2(256 BYTE));

ALTER TABLE SIGEM_ETRAMITACION_000.SGMAFSESION_INFO
MODIFY(SOLICITANTE_CERTIFICADO_SN VARCHAR2(256 BYTE)); 