

--  Drop Tables 
IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('IVOLACTDIR') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE IVOLACTDIR ;

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('IVOLARCHLIST') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE IVOLARCHLIST ;

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('IVOLFILEFTS') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE IVOLFILEFTS ;

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('IVOLFILEHDR') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE IVOLFILEHDR ;

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('IVOLLISTHDR') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE IVOLLISTHDR ;

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('IVOLLISTVOL') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE IVOLLISTVOL ;

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('IVOLNEXTID') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE IVOLNEXTID ;

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('IVOLREPHDR') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE IVOLREPHDR ;

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('IVOLVOLHDR') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE IVOLVOLHDR ;

IF EXISTS (SELECT * FROM dbo.SYSOBJECTS WHERE id = object_id('IVOLVOLTBL') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE IVOLVOLTBL ;


--  Create Tables 
CREATE TABLE IVOLACTDIR ( 
	VOLID int NOT NULL,
	ACTDIR int NOT NULL,
	NUMFILES int NOT NULL
) ;

CREATE TABLE IVOLARCHLIST ( 
	ARCHID int NOT NULL,
	LISTID int NOT NULL
) ;

CREATE TABLE IVOLFILEFTS ( 
	ID int NOT NULL,
	EXTID1 int NOT NULL,
	EXTID2 int NOT NULL,
	EXTID3 int NOT NULL,
	EXTID4 int NOT NULL,
	PATH varchar(254) NOT NULL,
	TIMESTAMP datetime NOT NULL
) ;

CREATE TABLE IVOLFILEHDR ( 
	ID int NOT NULL,
	VOLID int NOT NULL,
	LOC varchar(254) NOT NULL,
	EXTID1 int NOT NULL,
	EXTID2 int NOT NULL,
	EXTID3 int NOT NULL,
	FLAGS int NOT NULL,
	STAT int NOT NULL,
	TIMESTAMP datetime,
	FILESIZE float NOT NULL
) ;

CREATE TABLE IVOLLISTHDR ( 
	ID int NOT NULL,
	NAME varchar(32) NOT NULL,
	FLAGS int NOT NULL,
	STAT int NOT NULL,
	REMARKS varchar(254),
	CRTRID int NOT NULL,
	CRTNDATE datetime NOT NULL,
	UPDRID int,
	UPDDATE datetime
) ;

CREATE TABLE IVOLLISTVOL ( 
	LISTID int NOT NULL,
	VOLID int NOT NULL,
	SORTORDER int NOT NULL
) ;

CREATE TABLE IVOLNEXTID ( 
	TYPE int NOT NULL,
	ID int NOT NULL
) ;

CREATE TABLE IVOLREPHDR ( 
	ID int NOT NULL,
	NAME varchar(32) NOT NULL,
	TYPE int NOT NULL,
	INFO text NOT NULL,
	STAT int NOT NULL,
	REMARKS varchar(254),
	CRTRID int NOT NULL,
	CRTNDATE datetime NOT NULL,
	UPDRID int,
	UPDDATE datetime
) ;

CREATE TABLE IVOLVOLHDR ( 
	ID int NOT NULL,
	NAME varchar(32) NOT NULL,
	REPID int NOT NULL,
	INFO text NOT NULL,
	ITEMP int NOT NULL,
	ACTSIZE varchar(32) NOT NULL,
	NUMFILES int NOT NULL,
	STAT int NOT NULL,
	REMARKS varchar(254),
	CRTRID int NOT NULL,
	CRTNDATE datetime NOT NULL,
	UPDRID int,
	UPDDATE datetime
) ;

CREATE TABLE IVOLVOLTBL ( 
	LOCID varchar(32) NOT NULL,
	EXTID1 int NOT NULL,
	EXTID2 int NOT NULL,
	EXTID3 int NOT NULL,
	EXTID4 int NOT NULL,
	FILEEXT varchar(10) NOT NULL,
	FILEVAL image NOT NULL
) ;



--  Create Indexes 
CREATE UNIQUE CLUSTERED INDEX IVOLACTDIR1
ON IVOLACTDIR (VOLID ASC) ;

CREATE UNIQUE INDEX IVOLARCHLIST1
ON IVOLARCHLIST (ARCHID ASC) ;

CREATE INDEX IVOLARCHLIST2
ON IVOLARCHLIST (LISTID ASC) ;

CREATE UNIQUE INDEX IVOLFILEFTS1
ON IVOLFILEFTS (ID ASC) ;

CREATE UNIQUE INDEX IVOLFILEFTS2
ON IVOLFILEFTS (PATH ASC) ;

CREATE UNIQUE INDEX IVOLFILEHDR1
ON IVOLFILEHDR (ID ASC) ;

CREATE INDEX IVOLFILEHDR2
ON IVOLFILEHDR (VOLID ASC) ;

CREATE UNIQUE CLUSTERED INDEX IVOLLISTHDR1
ON IVOLLISTHDR (ID ASC) ;

CREATE INDEX IVOLLISTVOL1
ON IVOLLISTVOL (LISTID ASC) ;

CREATE INDEX IVOLLISTVOL2
ON IVOLLISTVOL (VOLID ASC) ;

CREATE UNIQUE CLUSTERED INDEX IVOLNEXTID1
ON IVOLNEXTID (TYPE ASC) ;

CREATE UNIQUE INDEX IVOLREPHDR1
ON IVOLREPHDR (ID ASC) ;

CREATE UNIQUE CLUSTERED INDEX IVOLVOLHDR1
ON IVOLVOLHDR (ID ASC) ;

CREATE INDEX IVOLVOLHDR2
ON IVOLVOLHDR (REPID ASC) ;

CREATE UNIQUE INDEX IVOLVOLTBL1
ON IVOLVOLTBL (LOCID ASC) ;


BEGIN TRANSACTION
INSERT INTO IVOLACTDIR(VOLID, ACTDIR, NUMFILES) VALUES (1, 1, 0);

INSERT INTO IVOLLISTHDR(ID, NAME, FLAGS, STAT, REMARKS, CRTRID, CRTNDATE, UPDRID, UPDDATE)
VALUES (6, 'LISTABD', 0, 0, NULL, 0, GETDATE(), NULL, NULL);

INSERT INTO IVOLLISTVOL(LISTID, VOLID, SORTORDER)
VALUES (6, 1, 1);

INSERT INTO IVOLNEXTID(TYPE, ID)
VALUES (1, 7);

INSERT INTO IVOLNEXTID(TYPE, ID)
VALUES (2, 7);

INSERT INTO IVOLNEXTID(TYPE, ID)
VALUES (3, 7);

INSERT INTO IVOLNEXTID(TYPE, ID)
VALUES (4, 130);

INSERT INTO IVOLREPHDR(ID, NAME, TYPE, INFO, STAT, REMARKS, CRTRID, CRTNDATE, UPDRID, UPDDATE)
VALUES (1, 'REPBD', 5, '"01.01"|""|5|0|0|0|0', 0, NULL, 0, GETDATE(), NULL, NULL);

INSERT INTO IVOLVOLHDR(ID, NAME, REPID, INFO, ITEMP, ACTSIZE, NUMFILES, STAT, REMARKS, CRTRID, CRTNDATE, UPDRID, UPDDATE)
VALUES (1, 'REPBD', 1, '"01.01"|5|"IVOLVOLTBL,LOCID,VARCHAR(32),FILEVAL,IMAGE"|"1073741824"|0', 0, '0', 0, 0, NULL, 0, GETDATE(), NULL, NULL);

COMMIT TRANSACTION;