-- /***************************/
-- /* Actualización 4.5->4.7            */
-- /***************************/

INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.5->4.7',now());

DROP FUNCTION UPDATECODREF ( VARCHAR(32), VARCHAR(1), VARCHAR(1) );
DROP FUNCTION GETFINCODREFPADRE (VARCHAR(32),VARCHAR(1));
DROP FUNCTION GETCODREF(VARCHAR(32), VARCHAR(1));

CREATE TABLE ASGFCTLGTBLTMP(
	ID NUMERIC(5)NOT NULL,
	NOMBRETABLA VARCHAR(16) NOT NULL,
	IDUSUARIO VARCHAR(32),
	ESTADO NUMERIC(1) default 0,
	FECHA DATE
);

CREATE UNIQUE INDEX ASGFCTLGTBLTMP1 ON ASGFCTLGTBLTMP(ID);
CREATE UNIQUE INDEX ASGFCTLGTBLTMP2 ON ASGFCTLGTBLTMP(NOMBRETABLA);

CREATE UNIQUE INDEX ASGFFONDO2 ON ASGFFONDO(CODARCHIVO,IDENTPRODUCTORA);

INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD_INICIAL','4.8',now());

CREATE VIEW VUNIDADDOCUMENTAL AS
SELECT
E.ID, E.TIPO, E.IDNIVEL, E.CODIGO,
E.TITULO, E.IDPADRE, E.IDFONDO, E.CODREFFONDO,
E.FINALCODREFPADRE, E.CODREFERENCIA, E.ESTADO,
E.IDELIMINACION, E.IDFICHADESCR, E.TIENEDESCR,
E.EDITCLFDOCS, E.IDLVOL, E.IDARCHIVO, E.NIVELACCESO,
E.IDLCA, E.SUBTIPO, E.ORDPOS,
F1.FECHAINI AS FI_FECHAINI,
F1.FECHAFIN AS FI_FECHAFIN,
F1.FORMATO AS FI_FORMATO,
F1.SEP AS FI_SEP,
F1.VALOR AS FI_VALOR,
F1.CALIFICADOR AS FI_CALIFICADOR,
F2.FECHAINI AS FF_FECHAINI,
F2.FECHAFIN AS FF_FECHAFIN,
F2.FORMATO AS FF_FORMATO,
F2.SEP AS FF_SEP,
F2.VALOR AS FF_VALOR,
F2.CALIFICADOR AS FF_CALIFICADOR,
U.NUMEXP,
N.NOMBRE AS NOMBRENIVEL
FROM ASGFELEMENTOCF AS E
LEFT OUTER JOIN ADVCFECHACF AS F1
	ON F1.IDELEMENTOCF = E.ID AND F1.IDCAMPO = '3'
LEFT OUTER JOIN ADVCFECHACF AS F2
	ON F2.IDELEMENTOCF = E.ID AND F2.IDCAMPO = '4'
LEFT OUTER JOIN ASGFUNIDADDOC AS U
	ON E.ID = U.IDELEMENTOCF
LEFT OUTER JOIN ASGFNIVELCF AS N
	ON E.IDNIVEL = N.ID
WHERE E.TIPO=6
