//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by iDocImgX.rc
//
#define IDR_MAINFRAME                   2
#define IDR_TRMAINFRAME                 3
#define IDS_PROJNAME                    100
#define IDS_ERRDSPL                     101
#define IDB_CONTROL                     102
#define IDS_NONE_BORDER                 102
#define IDR_CONTROL                     103
#define IDD_PRINT                       103
#define IDS_SIMPLE_BORDER               103
#define IDW_STATIC                      104
#define IDS_DOUBLE_BORDER               104
#define IDS_ANN_TEXT                    105
#define IDR_PRINTJOB                    106
#define IDS_ANN_NOTE                    106
#define IDS_GEN                         107
#define IDS_ERR_FILENOTE                108
#define IDS_ERR_DOWNLOAD_FILE           109
#define IDS_ERR_OPEN_IMG                110
#define IDS_ERR_CA                      111
#define IDS_ERR_CAD                     111
#define IDR_ANNOTATION                  140
#define IDC_ICONCUR                     148
#define IDC_ZOOM                        149
#define IDB_NOTE                        149
#define IDC_HHAND                       150
#define IDR_PROPERTY_MENU               153
#define IDD_PAGIR                       172
#define IDD_CONFIGURATION               175
#define IDD_TITLE_NOT                   201
#define IDC_NOT_TXT                     201
#define IDD_TITLE_EDNOT                 202
#define IDC_NOTE                        202
#define IDD_TITLE_TEXT                  203
#define IDC_ST_TXT_FONT                 203
#define IDC_ST_TXT_SIZE                 204
#define IDC_FONT                        205
#define IDR_DELETE_ANN                  205
#define IDC_ST_FONT                     206
#define IDD_ENDOSO                      206
#define IDC_ST_SIZE                     207
#define IDR_ACCELERATOR1                207
#define IDC_ST_JUSTIFY                  208
#define IDC_TXT_LEFT                    209
#define IDC_TXT_CENTER                  210
#define IDC_TXT_RIGHT                   211
#define IDC_ST_BORDER                   212
#define IDC_ST_BORDER_ALL               213
#define IDC_ST_BORDER_TOP               214
#define IDC_ST_BORDER_DOWN              215
#define IDC_ST_BORDER_LEFT              216
#define IDC_ST_BORDER_RIGHT             217
#define IDC_BORDER_ALL                  218
#define IDC_BORDER_TOP                  219
#define IDC_NUMBER                      219
#define IDC_BORDER_DOWN                 220
#define IDC_BORDER_LEFT                 221
#define IDC_BORDER_RIGHT                222
#define IDC_ONETOONE                    1000
#define IDC_ROT270                      1001
#define IDC_DOCNAME                     1003
#define IDC_SEL                         1059
#define IDC_ST_PAG                      2032
#define IDC_LISTPAGE                    2037
#define IDC_DrawMode                    2040
#define IDC_WHITE                       2041
#define IDC_BLACK                       2042
#define IDC_GRAY                        2043
#define IDC_FIT                         2044
#define IDC_WINDOW                      2045
#define IDC_HORZ                        2046
#define IDC_VERT                        2047
#define IDC_PAL                         2048
#define IDC_ROT                         2049
#define IDC_NOROT                       2050
#define IDC_ROT90                       2051
#define IDC_ROT180                      2052
#define IDM_SAVEAS                      32618
#define IDM_ENDOSO                      32619
#define IDM_INVERT                      32621
#define IDM_EDITANN                     32768
#define IDM_SHOWPALANN                  32769
#define ID_MAR                          32770
#define IDM_HAND                        32771
#define IDM_ZOOMINCR                    32772
#define IDM_ZOOMDECR                    32773
#define IDM_NORMALSIZE                  32774
#define IDM_FITWINDOW                   32775
#define IDM_FITHORZ                     32776
#define IDM_FITVERT                     32777
#define IDM_SAVEANN                     32778
#define IDM_ROTD90                      32779
#define IDM_ROTI90                      32780
#define IDM_PREVP                       32781
#define IDM_NEXTP                       32782
#define IDM_PRINT                       32783
#define IDM_ZOOMRECT                    32784
#define IDM_SHOWPAL                     32785
#define IDM_WHITEDRAW                   32786
#define IDM_BLACKDRAW                   32787
#define IDM_GRAYDRAW                    32788
#define IDM_FIRSTP                      32790
#define IDM_LASTP                       32791
#define IDM_CONFIG                      32792
#define IDM_GOTO                        32793
#define IDM_TINCRCLOCAL                 32794
#define IDM_TINCRGC                     32795
#define IDM_TRTD                        32796
#define IDM_TTWIDTH                     32797
#define IDM_TSUPFD                      32798
#define IDM_TSUPMTO                     32799
#define IDM_TSUPTT                      32800
#define IDM_TSUPMTC                     32801
#define IDM_TTF                         32802
#define IDM_TREL                        32803
#define IDM_TUNDO                       32804
#define IDM_SELECT                      32805
#define ID_SELECTOR                     32808
#define ID_NOTE                         32809
#define ID_ARROW                        32810
#define ID_HIGHLINE                     32811
#define ID_LINE                         32812
#define ID_TEXT                         32813
#define ID_MARK                         32814
#define IDM_M_PROPERTY                  32815
#define IDM_DELETEANN                   32816

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        208
#define _APS_NEXT_COMMAND_VALUE         32622
#define _APS_NEXT_CONTROL_VALUE         220
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
