/* TABLES OR VIEWS --------------------------------------- */
CREATE TABLE DIR_OFICINA (
	CODIGO_OFICINA                    	VARCHAR(9)         NOT NULL,
	DENOMINACION_OFICINA              	VARCHAR(300)       NOT NULL,
	CODIGO_UNIDAD_RESPONSABLE       	VARCHAR(9)         NULL,
	EXTERNO_FUENTE            			VARCHAR(40)        NULL,
	PROVINCIA	            			VARCHAR(100)       NULL,
	LOCALIDAD	            			VARCHAR(100)       NULL,
	DIRECCION	            			VARCHAR(300)       NULL
);


CREATE TABLE DIR_UNIDAD_ORGANICA (
	CODIGO_UNIDAD_ORGANICA                		VARCHAR(9)         NOT NULL,
	NOMBRE_UNIDAD_ORGANICA               		VARCHAR(300)       NOT NULL,
	CODIGO_UNIDAD_SUP_JERARQUICA     			VARCHAR(9)         NULL,
	DENOM_UNIDAD_SUP_JERARQUICA    				VARCHAR(300) 	   NULL,
	CODIGO_EXTERNO_FUENTE             			VARCHAR(40)        NULL
);

CREATE TABLE DIR_ESTADO_ACTUALIZACION (
	ID 											INTEGER 			NOT NULL,
	FECHA_ACTUALIZACION							TIMESTAMP  			NOT NULL,
	ESTADO										VARCHAR(10)			NOT NULL
);

CREATE TABLE DIR_RELAC_UNID_ORG_OFIC (
	CODIGO_OFICINA                    			VARCHAR(9)         NOT NULL,
	DENOMINACION_OFICINA              			VARCHAR(300)       NOT NULL,
	CODIGO_UNIDAD_ORGANICA                		VARCHAR(9)         NOT NULL,
	DENOM_UNIDAD_ORGANICA               		VARCHAR(300)       NOT NULL
);

/* PRIMARY KEYS --------------------------------------- */

ALTER TABLE DIR_OFICINA ADD CONSTRAINT PK_DIR_OFICINA PRIMARY KEY (CODIGO_OFICINA);

ALTER TABLE DIR_UNIDAD_ORGANICA ADD CONSTRAINT PK_DIR_UNIDAD_ORGANICA PRIMARY KEY (CODIGO_UNIDAD_ORGANICA);

ALTER TABLE DIR_ESTADO_ACTUALIZACION ADD CONSTRAINT PK_ESTADO_ACTUALIZACION PRIMARY KEY(ID);
