--Tabla: AOESTRORG
DROP INDEX AOESTRORG1 ON AOESTRORG;
DROP INDEX AOESTRORG2 ON AOESTRORG;

--Tabla: AOUSR
DROP INDEX AOUSR1 ON AOUSR;
DROP INDEX AOUSR2 ON AOUSR;

--Tabla: AOUSRORGV
DROP INDEX AOUSRORGV1 ON AOUSRORGV;
