package common;

public class ConfiguracionParametrosConstants {

	/* Posibles valores de configuracion */

	// Configuración Inicial
	public static final String CODIGO_UDOC_UNICO = "CODIGO_UDOC_UNICO";
	public static final String ENTIDAD_REQUERIDA = "ENTIDAD_REQUERIDA";
	public static final String PERMITIR_SIGNATURA_ALFANUMERICA = "PERMITIR_SIGNATURA_ALFANUMERICA";
	public static final String SIGNATURACION_POR_ARCHIVO = "SIGNATURACION_POR_ARCHIVO";

		//Gestor ECM
		public static final String ECM_EXTERNO = "ECM_EXTERNO";
		public static final String INVESDOC_V8 = "INVESDOC_V8";
		//public static final String INVESDOC_TABLES = "INVESDOC_TABLES";



		// Variables
		public static final String LAST_LEVEL_UBICACION_RESERVA = "LAST_LEVEL_UBICACION_RESERVA";
		public static final String LOCALE_DEFAULT = "LOCALE_DEFAULT";
		public static final String NIVELES_DEPOSITO_VISIBLES_CARTELAS = "NIVELES_DEPOSITO_VISIBLES_CARTELAS";
		public static final String SEPARADOR_CODIGO_TRANSFERENCIA = "SEPARADOR_CODIGO_TRANSFERENCIA";
		/**
			* Cadena que define el separador por defecto para las fechas de la
			* relaci&oacute;n (Inicial/Final)
			*/
		public static final String SEPARADOR_DEFECTO_FECHAS_RELACION_KEY = "SEPARADOR_DEFECTO_FECHAS_RELACION";
		public static final String SEPARADOR_VALORES_MULTIPLES = "SEPARADOR_VALORES_MULTIPLES";


	// Funcionalidades
	public static final String DEBUG = "DEBUG";
	public static final String MOSTRAR_AYUDA = "MOSTRAR_AYUDA";

		// Acceso
		public static final String MOSTRAR_CHECK_SUPERUSUARIO = "MOSTRAR_CHECK_SUPERUSUARIO";

		//Administracion
		public static final String MOSTRAR_ADMINISTRACION_ORGANIZACION = "MOSTRAR_ADMINISTRACION_ORGANIZACION";
		public static final String PERMITIR_SELECCION_SIGNATURACION = "PERMITIR_SELECCION_SIGNATURACION";

		// Cuadro de Clasificación
		public static final String DISTINGUIR_MAYUSCULAS_MINUSCULAS = "DISTINGUIR_MAYUSCULAS_MINUSCULAS";
		public static final String FORMATEAR_SIGNATURA_NUMERICA = "FORMATEAR_SIGNATURA_NUMERICA";
		public static final String HEREDAR_CONDICIONES_ACCESO = "HEREDAR_CONDICIONES_ACCESO";
		public static final String MOSTRAR_CAMPO_ORDENACION_CUADRO = "MOSTRAR_CAMPO_ORDENACION_CUADRO";
		public static final String OCULTAR_CLASIFICADORES_FONDOS_USUARIOS_OFICINA = "OCULTAR_CLASIFICADORES_FONDOS_USUARIOS_OFICINA";
		public static final String PERMITIR_CODIGO_CLASIFICADOR_NULO = "PERMITIR_CODIGO_CLASIFICADOR_NULO";


			//Series
			public static final String MOSTRAR_INFORMACION_IDENTIFICACION_EXTENDIDA = "MOSTRAR_INFORMACION_IDENTIFICACION_EXTENDIDA";


		// Búsquedas
		public static final String MOSTRAR_BUSQUEDA_AVANZADA = "MOSTRAR_BUSQUEDA_AVANZADA";

		// Transferencias
		public static final String PERMITIR_ALTA_DIRECTA_UNIDADES_DOCUMENTALES = "PERMITIR_ALTA_DIRECTA_UNIDADES_DOCUMENTALES";
		public static final String PERMITIR_FICHA_ALTA_RELACION = "PERMITIR_FICHA_ALTA_RELACION";
		public static final String PERMITIR_TRANSFERENCIAS_ENTRE_ARCHIVOS = "PERMITIR_TRANSFERENCIAS_ENTRE_ARCHIVOS";


			// Previsiones
			public static final String MOSTRAR_CALENDARIO_PREVISIONES = "MOSTRAR_CALENDARIO_PREVISIONES";
			public static final String COLORES_CALENDARIO_PREVISIONES = "COLORES_CALENDARIO_PREVISIONES";
			public static final String INTERVAL_CALENDARIO_PREVISIONES = "INTERVAL_CALENDARIO_PREVISIONES";

			//Relaciones de Entrega
			public static final String AGREGAR_DESCRIPCION_DOCUMENTOS = "AGREGAR_DESCRIPCION_DOCUMENTOS";
			public static final String PERMITIR_CARGA_XML_ALTA_UNIDADES_DOCUMENTALES = "PERMITIR_CARGA_XML_ALTA_UNIDADES_DOCUMENTALES";
			public static final String PERMITIR_CARGA_XML_RELACION_EXTRAORDINARIA_SIN_SIGNATURA = "PERMITIR_CARGA_XML_RELACION_EXTRAORDINARIA_SIN_SIGNATURA";
			public static final String PERMITIR_CARGA_XML_RELACION_EXTRAORDINARIA_CON_SIGNATURA = "PERMITIR_CARGA_XML_RELACION_EXTRAORDINARIA_CON_SIGNATURA";
			public static final String PERMITIR_REENCAJADO = "PERMITIR_REENCAJADO";


		//Depósito
		public static final String MANTENER_CAJA_COMPACTAR = "MANTENER_CAJA_COMPACTAR";
		public static final String MOSTRAR_TODAS_UBICACIONES = "MOSTRAR_TODAS_UBICACIONES";
		public static final String PERMITIR_SELECCIONAR_ELEMENTO_UBICACION = "PERMITIR_SELECCIONAR_ELEMENTO_UBICACION";
		public static final String PERMITIR_COMPACTAR_UDOCS_NO_CONSECUTIVAS = "PERMITIR_COMPACTAR_UDOCS_NO_CONSECUTIVAS";

		// Documentos
		public static final String USAR_VISOR_IMG_OCX = "USAR_VISOR_IMG_OCX";

		//Documentos Vitales
		public static final String MOSTRAR_DOC_VITALES = "MOSTRAR_DOC_VITALES";

		//Reprografía
		public static final String MOSTRAR_SALAS = "MOSTRAR_SALAS";

		//Servicios y Peticiones
		public static final String MARCAR_ARCHIVO_ORGANO_SOLICITUDES = "MARCAR_ARCHIVO_ORGANO_SOLICITUDES";
		public static final String IMPRIMIR_ETIQUETAS_PRESTAMO = "IMPRIMIR_ETIQUETAS_PRESTAMO";
		public static final String MOTIVO_SOLICITUD_OPCIONAL = "MOTIVO_SOLICITUD_OPCIONAL";
		public static final String PERMITIR_ENVIAR_SOLICITUD_NO_DISPONIBLE = "PERMITIR_ENVIAR_SOLICITUD_NO_DISPONIBLE";
		public static final String UDOCS_SOLICITUDES_HOJAS_SEPARADAS = "UDOCS_SOLICITUDES_HOJAS_SEPARADAS";
}