package common.navigation;

import java.util.HashMap;

/**
 * Clase que contiene las claves de las invocaciones.
 */
public class KeysClientsInvocations {

	static HashMap map = new HashMap();

	static int i = 0;

	/**
	 * Indica si un ClientInvocation se muestra en la barra de navegaci�n. Si
	 * no se define para el cliente si se muestra o no, por defecto se
	 * mostrar�.
	 *
	 * @param key
	 * @return
	 */
	public boolean isVisibleInNavigationToolBar(String key) {
		Boolean bool = (Boolean) map.get(key);
		if (bool != null)
			return bool.booleanValue();

		return true;
	}

	static public String getKeyToken() {
		return "NavigationKeyClient_";
	}

	static String getKey(String arg) {
		return new StringBuffer(getKeyToken()).append(arg).toString();
	}

	/*
	 * Por defecto todos se muestran en la toolbar excepto los que no se definan
	 * aqui
	 */
	public final static String KEY_HOME = getKey("KEY_HOME");

	/*
	 * Ejempl de defincion
	 */
	static {
		map.put(KEY_HOME, Boolean.TRUE);
	}

	/**
	 * CLAVES PARA EL DEPOSITO
	 */
	public static final String DEPOSITO_RESUMEN = getKey("DEPOSITO_RESUMEN");
	public static final String DEPOSITO_HOME = getKey("DEPOSITO_HOME");
	public static final String DEPOSITO_CREAR_ELEMENTO = getKey("DEPOSITO_CREAR_ELEMENTO");
	public static final String RESUMEN_ESTADO_DEPOSITO = getKey("RESUMEN_ESTADO_DEPOSITO");
	public static final String DEPOSITO_VER_ELEMENTO = getKey("DEPOSITO_VER_ELEMENTO");
	public static final String DEPOSITO_EDITAR_ELEMENTO = getKey("DEPOSITO_EDITAR_ELEMENTO");
	public static final String DEPOSITO_INFORME_OCUPACION = getKey("DEPOSITO_INFORME_OCUPACION");
	public static final String DEPOSITO_HABILITAR_HUECOS = getKey("DEPOSITO_HABILITAR_HUECOS");
	public static final String DEPOSITO_INHABILITAR_HUECOS = getKey("DEPOSITO_INHABILITAR_HUECOS");
	public static final String DEPOSITO_REUBICACION_UNIDADES_INSTALACION = getKey("DEPOSITO_REUBICACION_UNIDADES_INSTALACION");
	public static final String DEPOSITO_EDITAR_NUMERACION_HUECOS = getKey("DEPOSITO_EDITAR_NUMERACION_HUECOS");
	public static final String DEPOSITO_TIPO_ASIGNABLE_MODO_VISTA = getKey("DEPOSITO_TIPO_ASIGNABLE_MODO_VISTA");

	public static final String DEPOSITO_LISTADO_UDOCS = getKey("DEPOSITO_LISTADO_UDOCS");
	public static final String DEPOSITO_SELECCION_UDOCS_A_REUBICAR = getKey("DEPOSITO_SELECCION_UDOCS_A_REUBICAR");
	public static final String DEPOSITO_UDOCS_A_ORGANIZAR = getKey("DEPOSITO_UDOCS_A_ORGANIZAR");
	public static final String DEPOSITO_SELECCION_HUECO_DESTINO = getKey("DEPOSITO_SELECCION_HUECO_DESTINO");
	public static final String DEPOSITO_INFORME_REUBICACION_UDOCS = getKey("DEPOSITO_INFORME_REUBICACION_UDOCS");
	public static final String DEPOSITO_UDOCS_A_REUBICAR = getKey("DEPOSITO_UDOCS_A_REUBICAR");
	public static final String DEPOSITO_SELECCION_ELEMENTO_DESTINO = getKey("DEPOSITO_SELECCION_ELEMENTO_DESTINO");
	public static final String DEPOSITO_RESERVA_LISTA_RELACIONES = getKey("DEPOSITO_RESERVA_LISTA_RELACIONES");
	public static final String DEPOSITO_RESERVA_VER_NAVEGADOR = getKey("DEPOSITO_RESERVA_VER_NAVEGADOR");
	public static final String DEPOSITO_RESERVA_INFORME = getKey("DEPOSITO_RESERVA_INFORME");
	public static final String DEPOSITO_ACEPTAR_REUBICACION_UDOCS = getKey("DEPOSITO_ACEPTAR_REUBICACION_UDOCS");
	public static final String DEPOSITO_LISTADO_UDOCS_REUBICACION = getKey("DEPOSITO_LISTADO_UDOCS_REUBICACION");

	public static final String DEPOSITO_UBICACION_LISTA_RELACIONES = getKey("DEPOSITO_UBICACION_LISTA_RELACIONES");
	public static final String DEPOSITO_UBICACION_COMPROBAR_RESERVA = getKey("DEPOSITO_UBICACION_COMPROBAR_RESERVA");
	public static final String DEPOSITO_UBICACION_COMPROBAR_RESERVA_INGRESO = getKey("DEPOSITO_UBICACION_COMPROBAR_RESERVA_INGRESO");
	public static final String DEPOSITO_UBICACION_INFORME = getKey("DEPOSITO_UBICACION_INFORME");
	public static final String DEPOSITO_ELECTRONICO_HOME = getKey("DEPOSITO_ELECTRONICO_HOME");
	public static final String DEPOSITO_ELECTRONICO_VER_DEPOSITO = getKey("DEPOSITO_ELECTRONICO_VER_DEPOSITO");
	public static final String DEPOSITO_ELECTRONICO_CREAR_DEPOSITO = getKey("DEPOSITO_ELECTRONICO_CREAR_DEPOSITO");
	public static final String CUADRO_LISTADO_BUSQ_UDOCS = getKey("CUADRO_LISTADO_BUSQ_UDOCS");
	public static final String DEPOSITO_ELECTRONICO_EDITAR_DEPOSITO = getKey("DEPOSITO_ELECTRONICO_EDITAR_DEPOSITO");
	public static final String DEPOSITO_SELECCION_CARTELAS = getKey("DEPOSITO_SELECCION_CARTELAS");
	public static final String DEPOSITO_IMPRESION_CARTELAS = getKey("DEPOSITO_IMPRESION_CARTELAS");

	public static final String DEPOSITO_LISTADO_FORMATOS = getKey("DEPOSITO_LISTADO_FORMATOS");
	public static final String DEPOSITO_INFO_FORMATO = getKey("DEPOSITO_INFO_FORMATO");
	public static final String DEPOSITO_EDICION_ROL = getKey("DEPOSITO_EDICION_ROL");
	public static final String DEPOSITO_ALTA_FORMATO = getKey("DEPOSITO_ALTA_FORMATO");
	public static final String DEPOSITO_EDICION_FORMATO = getKey("DEPOSITO_EDICION_FORMATO");
	public static final String DEPOSITO_BUSQUEDA_UINST = getKey("DEPOSITO_BUSQUEDA_UINST");
	public static final String DEPOSITO_EDITAR_NUMERACION = getKey("DEPOSITO_EDITAR_NUMERACION");
	public static final String DEPOSITO_CONFIRMAR_NUMERACION = getKey("DEPOSITO_CONFIRMAR_NUMERACION");
	public static final String DEPOSITO_CONFIRMAR_CAMBIO_NUMERACION = getKey("DEPOSITO_CONFIRMAR_CAMBIO_NUMERACION");
	public static final String DEPOSITO_BUSQUEDA_UIS_ELIMINADAS = getKey("DEPOSITO_BUSQUEDA_UIS_ELIMINADAS");
	public static final String DEPOSITO_BUSQUEDA_UIS_ANIO_SERIE = getKey("DEPOSITO_BUSQUEDA_UIS_ANIO_SERIE");

	/**
	 * CLAVES PARA DESCRIPCION
	 */

	public static final String DESCRIPCION_FORM_BUSQ = getKey("DESCRIPCION_FORM_BUSQ");
	public static final String DESCRIPCION_FORM_BUSQ_AUT = getKey("DESCRIPCION_FORM_BUSQ_AUT");
	public static final String DESCRIPCION_BUSQ = getKey("DESCRIPCION_BUSQ");
	public static final String DESCRIPCION_BUSQ_AUT = getKey("DESCRIPCION_BUSQ_AUT");
	public static final String DESCRIPCION_RETRIEVE = getKey("DESCRIPCION_RETRIEVE");
	public static final String DESCRIPCION_RETRIEVE_DESCRIPTOR = getKey("DESCRIPCION_RETRIEVE_DESCRIPTOR");
	public static final String DESCRIPCION_EDIT_DESCRIPTOR = getKey("DESCRIPCION_EDIT_DESCRIPTOR");
	public static final String DESCRIPCION_EDIT = getKey("DESCRIPCION_EDIT");
	public static final String DESCRIPCION_EDITAR = getKey("DESCRIPCION_EDITAR");
	public static final String DESCRIPCION_RETRIEVE_ELEMENTO = getKey("DESCRIPCION_RETRIEVE_ELEMENTO");
	public static final String DESCRIPCION_EDIT_ELEMENTO = getKey("DESCRIPCION_EDIT_ELEMENTO");
	public static final String DESCRIPCION_EDIT_UDOCRE = getKey("DESCRIPCION_EDIT_UDOCRE");
	public static final String DESCRIPCION_EDIT_FSRE = getKey("DESCRIPCION_EDIT_FSRE");
	public static final String DESCRIPCION_EDIT_UDOCFS = getKey("DESCRIPCION_EDIT_UDOCFS");
	public static final String DESCRIPCION_EDIT_FSFS = getKey("DESCRIPCION_EDIT_FSFS");

	public static final String DESCRIPCION_TABLAS_VALIDACION = getKey("DESCRIPCION_TABLAS_VALIDACION");
	public static final String DESCRIPCION_TABLAS_VALIDACION_VIEW = getKey("DESCRIPCION_TABLAS_VALIDACION_VIEW");
	public static final String DESCRIPCION_TABLAS_VALIDACION_FORM = getKey("DESCRIPCION_TABLAS_VALIDACION_FORM");
	public static final String DESCRIPCION_TABLAS_VALIDACION_EDIT = getKey("DESCRIPCION_TABLAS_VALIDACION_EDIT");
	public static final String DESCRIPCION_TABLAS_VALIDACION_VALUE = getKey("DESCRIPCION_TABLAS_VALIDACION_VALUE");
	public static final String DESCRIPCION_LISTAS_DESCRIPTORAS = getKey("DESCRIPCION_LISTAS_DESCRIPTORAS");

	public static final String DESCRIPCION_LISTAS_DESCRIPTORAS_VIEW = getKey("DESCRIPCION_LISTAS_DESCRIPTORAS_VIEW");
	public static final String DESCRIPCION_LISTAS_DESCRIPTORAS_UNIFICAR = getKey("DESCRIPCION_LISTAS_DESCRIPTORAS_UNIFICAR");
	public static final String DESCRIPCION_LISTAS_DESCRIPTORAS_UNIFICAR_CONFIRMAR = getKey("DESCRIPCION_LISTAS_DESCRIPTORAS_UNIFICAR_CONFIRMAR");
	public static final String DESCRIPCION_LISTAS_DESCRIPTORAS_FORM = getKey("DESCRIPCION_LISTAS_DESCRIPTORAS_FORM");
	public static final String DESCRIPCION_LISTAS_DESCRIPTORAS_EDIT = getKey("DESCRIPCION_LISTAS_DESCRIPTORAS_EDIT");
	public static final String DESCRIPCION_LISTAS_DESCRIPTORAS_DESCRIPTOR_BUSQ = getKey("DESCRIPCION_LISTAS_DESCRIPTORAS_DESCRIPTOR_BUSQ");
	public static final String DESCRIPCION_LISTAS_DESCRIPTORAS_DESCRIPTOR_VIEW = getKey("DESCRIPCION_LISTAS_DESCRIPTORAS_DESCRIPTOR_VIEW");
	public static final String DESCRIPCION_LISTAS_DESCRIPTORAS_DESCRIPTOR_FORM = getKey("DESCRIPCION_LISTAS_DESCRIPTORAS_DESCRIPTOR_FORM");
	public static final String DESCRIPCION_LISTAS_DESCRIPTORAS_DESCRIPTOR_EDIT = getKey("DESCRIPCION_LISTAS_DESCRIPTORAS_DESCRIPTOR_EDIT");

	/**
	 * CLAVES PARA EL CUADRO DE CLASIFICACION
	 */
	public static final String CUADRO_LISTADO_BUSQUEDA_SERIES_DESTINO = getKey("CUADRO_LISTADO_BUSQUEDA_SERIES_DESTINO");
	public static final String CUADRO_VER_IDENTIFICACION = getKey("VER_IDENTIFICACION");
	public static final String CUADRO_PORTADA_GESTION_FONDOS = getKey("CUADRO_PORTADA_GESTION_FONDOS");
	public static final String CUADRO_RESUMEN_FONDOS = getKey("CUADRO_RESUMEN_FONDOS");
	public static final String EXPORTAR_CUADRO = getKey("EXPORTAR_CUADRO");
	public static final String VER_EN_CUADRO = getKey("VER_EN_CUADRO");

	public static final String CUADRO_FORM_BUSQUEDA_RAPIDA_ELEMENTOS = getKey("CUADRO_FORM_BUSQUEDA_RAPIDA_ELEMENTOS");
	public static final String CUADRO_FORM_BUSQUEDA_ESPECIFICA_ELEMENTOS = getKey("CUADRO_FORM_BUSQUEDA_ESPECIFICA_ELEMENTOS");
	public static final String CUADRO_FORM_BUSQUEDA_AVANZADA_ELEMENTOS = getKey("CUADRO_FORM_BUSQUEDA_AVANZADA_ELEMENTOS");
	public static final String CUADRO_LISTADO_BUSQUEDA_ELEMENTOS = getKey("CUADRO_LISTADO_BUSQUEDA_ELEMENTOS");
	public static final String CUADRO_FORM_BUSQUEDA_SERIE_DESTINO_DE_UDOCS = getKey("CUADRO_FORM_BUSQUEDA_SERIE_DESTINO_DE_UDOCS");
	public static final String CUADRO_INFORME_MOVIMIENTO_UDOCS = getKey("CUADRO_INFORME_MOVIMIENTO_UDOCS");
	public static final String CUADRO_VER_BUSCADOR = getKey("CUADRO_VER_BUSCADOR");
	public static final String CUADRO_BUSCAR_SERIE = getKey("CUADRO_BUSCAR_SERIE");
	public static final String CUADRO_SERIES_GESTOR = getKey("CUADRO_SERIES_GESTOR");
	public static final String CUADRO_SELECCIONAR_NUEVO_GESTOR = getKey("CUADRO_SELECCIONAR_NUEVO_GESTOR");
	public static final String CUADRO_VER_TIPOS_ASIGNACION = getKey("CUADRO_VER_TIPOS_ASIGNACION");
	public static final String CUADRO_SELECCION_TIPO_ASIGNACION = getKey("CUADRO_SELECCION_TIPO_ASIGNACION");

	public static final String CUADRO_SELECCION_SERIE = getKey("CUADRO_SELECCION_SERIE");
	public static final String CUADRO_PASO_SERIE_A_EN_ESTUDIO = getKey("CUADRO_PASO_SERIE_A_EN_ESTUDIO");
	public static final String CUADRO_PASO_SERIE_A_HISTORICA = getKey("CUADRO_PASO_SERIE_A_HISTORICA");
	public static final String CUADRO_PASO_SERIE_A_VIGENTE = getKey("CUADRO_PASO_SERIE_A_VIGENTE");
	public static final String CUADRO_SELECCION_GESTOR = getKey("CUADRO_SELECCION_GESTOR");
	public static final String CUADRO_LISTA_SOLICITUDES_APROBACION = getKey("CUADRO_LISTA_SOLICITUDES_APROBACION");

	public static final String CUADRO_MIS_SOLICITUDES_APROBACION = getKey("CUADRO_MIS_SOLICITUDES_APROBACION");
	public static final String CUADRO_VER_SOLICITUD = getKey("CUADRO_VER_SOLICITUD");
	public static final String CUADRO_VER_SERIE_SOLICITUD = getKey("CUADRO_VER_SERIE_SOLICITUD");
	// public static final String CUADRO_VER_FONDO = getKey("CUADRO_VER_FONDO");
	public static final String CUADRO_CREAR_FONDO = getKey("CUADRO_CREAR_FONDO");
	public static final String CUADRO_EDITAR_FONDO = getKey("CUADRO_EDITAR_FONDO");
	public static final String CUADRO_MOVER_FONDO = getKey("CUADRO_MOVER_FONDO");
	public static final String CUADRO_MOVER_CLASIFICADORSERIE = getKey("CUADRO_MOVER_CLASIFICADORSERIE");
	public static final String CUADRO_VER_SERIE = getKey("CUADRO_VER_SERIE");
	public static final String CUADRO_MOVER_SERIE = getKey("CUADRO_MOVER_SERIE");
	public static final String CUADRO_EDICION_SERIE = getKey("CUADRO_EDICION_SERIE");
	public static final String CUADRO_CONTENIDO_SERIE = getKey("CUADRO_CONTENIDO_SERIE");
	public static final String CUADRO_FILTRO_CONTENIDO_SERIE = getKey("CUADRO_FILTRO_CONTENIDO_SERIE");

	public static final String CUADRO_VER_FICHA = getKey("CUADRO_VER_FICHA");
	public static final String CUADRO_VER_UNIDAD_DOCUMENTAL = getKey("CUADRO_VER_UNIDAD_DOCUMENTAL");
	public static final String CUADRO_EDICION_UNIDAD_DOCUMENTAL = getKey("CUADRO_EDICION_UNIDAD_DOCUMENTAL");
	public static final String CUADRO_DIVIDIR_FRACCION_SERIE = getKey("CUADRO_DIVIDIR_FRACCION_SERIE");
	public static final String CUADRO_VER_FRACCION_SERIE = getKey("CUADRO_VER_FRACCION_SERIE");
	public static final String CUADRO_VER_UDOC_FRACCION_SERIE = getKey("CUADRO_VER_UDOC_FRACCION_SERIE");
	public static final String CUADRO_VER_FS_FRACCION_SERIE = getKey("CUADRO_VER_FS_FRACCION_SERIE");

	public final static String CUADRO_SOLICITUD_ALTA_SERIE = getKey("CUADRO_SOLICITUD_ALTA_SERIE");
	public static final String CUADRO_ACEPTACION_SOLICITUD = getKey("CUADRO_ACEPTACION_SOLICITUD");
	public static final String CUADRO_SOLICITUD_APROBACION_CAMBIOS = getKey("CUADRO_SOLICITUD_APROBACION_CAMBIOS");
	public static final String CUADRO_RECHAZO_SOLICITUD = getKey("CUADRO_RECHAZO_SOLICITUD");
	public static final String CUADRO_IDENTIFICACION_LISTA_SOPORTES = getKey("CUADRO_IDENTIFICACION_LISTA_SOPORTES");
	// public static final String CUADRO_VER_CLASIFICADOR_SERIES =
	// getKey("CUADRO_VER_CLASIFICADOR_SERIES");
	public final static String CUADRO_ELEMENTO_DEL_CUADRO = getKey("CUADRO_ELEMENTO_DEL_CUADRO");

	public final static String CUADRO_CREAR_CLSERIES = getKey("CUADRO_CREAR_CLSERIES");
	public final static String CUADRO_CREAR_CLFONDOS = getKey("CUADRO_CREAR_CLFONDOS");
	public final static String CUADRO_EDITAR_CLSERIES = getKey("CUADRO_EDITAR_CLSERIES");
	public final static String CUADRO_EDITAR_CLFONDOS = getKey("CUADRO_EDITAR_CLFONDOS");
	public final static String CUADRO_ANADIR_PROC = getKey("CUADRO_ANADIR_PROC");

	public final static String CUADRO_PANTALLA_IDENTIFICACION = getKey("CUADRO_PANTALLA_IDENTIFICACION");
	public final static String CUADRO_IDENTIFICACION_LISTA_PROCEDIMIENTOS = getKey("CUADRO_IDENTIFICACION_LISTA_PROCEDIMIENTOS");
	public final static String CUADRO_IDENTIFICACION_INSERTAR_PRODUCTORES_EN_SISTEMA = getKey("CUADRO_IDENTIFICACION_INSERTAR_PRODUCTORES_EN_SISTEMA");
	public static final String CUADRO_ACTULIZAR_IDENTIFICACION = getKey("CUADRO_ACTULIZAR_IDENTIFICACION");
	public final static String CUADRO_IDENTIFICACION_SELECCION_PRODUCTORES = getKey("CUADRO_IDENTIFICACION_LISTA_ORGANOS");
	public final static String CUADRO_BUSQ_UDOCS = getKey("CUADRO_BUSQ_UDOCS");

	public static final String CUADRO_NUEVO_INGRESO_DIRECTO = getKey("CUADRO_NUEVO_INGRESO_DIRECTO");
	public static final String CUADRO_EDICION_INGRESO_DIRECTO = getKey("CUADRO_EDICION_INGRESO_DIRECTO");
	public static final String CUADRO_VER_INGRESO = getKey("CUADRO_VER_INGRESO");
	public static final String CUADRO_LISTADO_INGRESOS_DIRECTOS = getKey("CUADRO_LISTADO_INGRESOS_DIRECTOS");
	public static final String CUADRO_SELECT_INGRESO_CEDER = getKey("CUADRO_SELECT_INGRESO_CEDER");
	public static final String CUADRO_SELECT_USUARIO_CEDER = getKey("CUADRO_SELECT_USUARIO_CEDER");
	public static final String CUADRO_VER_INGRESO_FRACCION_SERIE = getKey("CUADRO_VER_INGRESO_FRACCION_SERIE");
	public static final String CUADRO_LISTADO_DIVISIONES_FRACCIONSERIE = getKey("CUADRO_LISTADO_DIVISIONES_FRACCIONSERIE");
	public static final String CUADRO_DATOS_DIVISION_FRACCION_SERIE = getKey("CUADRO_DATOS_DIVISION_FRACCION_SERIE");
	public static final String CUADRO_DATOS_UDOC_EN_DIVISIONFS = getKey("CUADRO_DATOS_UDOC_EN_DIVISIONFS");
	public static final String CUADRO_NUEVA_UDOC_EN_DIVISIONFS = getKey("CUADRO_NUEVA_UDOC_EN_DIVISIONFS");
	public static final String CUADRO_NUEVA_FS_EN_DIVISIONFS = getKey("CUADRO_NUEVA_FS_EN_DIVISIONFS");

	public static final String SERIES_EN_IDENTIFICACION = getKey("SERIES_EN_IDENTIFICACION");
	public static final String SERIES_A_IDENTIFICAR = getKey("SERIES_A_IDENTIFICAR");
	public static final String SERIES_EN_VALORACION = getKey("SERIES_EN_VALORACION");
	public static final String SERIES_PRODUCTORES_SUSTITUIR = getKey("SERIES_PRODUCTORES_SUSTITUIR");
	public static final String SERIES_PRODUCTORES_CREAR = getKey("SERIES_PRODUCTORES_CREAR");
	public static final String SOLICITUD_SERIE_FORM_BUSQUEDA = getKey("SOLICITUD_SERIE_FORM_BUSQUEDA");
	public static final String SOLICITUD_SERIE_LISTADO_BUSQUEDA = getKey("SOLICITUD_SERIE_LISTADO_BUSQUEDA");

	public static final String SERIES_PRODUCTORES_A_HISTORICOS = getKey("SERIES_PRODUCTORES_A_HISTORICOS");

	/**
	 * CLAVES PARA LAS SOLICITUDES
	 */
	public static final String HOME_PRESTAMOS = getKey("HOME_PRESTAMOS");
	public static final String SOLICITUDES_LISTADO_PRESTAMOS = getKey("SOLICITUDES_LISTADO_PRESTAMOS");
	public static final String SOLICITUDES_LISTADO_PRESTAMOS_ENTREGAR = getKey("SOLICITUDES_LISTADO_PRESTAMOS_ENTREGAR");
	public static final String SOLICITUDES_LISTADO_PRESTAMOS_VER = getKey("SOLICITUDES_LISTADO_PRESTAMOS_VER");
	public static final String SOLICITUDES_CEDER_CONTROL = getKey("SOLICITUDES_CEDER_CONTROL");
	public static final String SOLICITUDES_BUSCAR_PRESTAMOS_USUARIO_ORIGEN = getKey("SOLICITUDES_BUSCAR_PRESTAMOS_USUARIO_ORIGEN");
	public static final String SOLICITUDES_VER_PRESTAMO = getKey("SOLICITUDES_VER_PRESTAMO");
	public static final String SOLICITUDES_IMPRIMIR_ENTRADA_PRESTAMO = getKey("SOLICITUDES_IMPRIMIR_ENTRADA_PRESTAMO");
	public static final String SOLICITUDES_IMPRIMIR_ENTRADA_CONSULTA = getKey("SOLICITUDES_IMPRIMIR_ENTRADA_CONSULTA");
	public static final String SOLICITUDES_NUEVO = getKey("SOLICITUDES_NUEVO");
	public static final String SOLICITUDES_EDICION = getKey("SOLICITUDES_EDICION");
	public static final String SOLICITUDES_SOLICITARDESDERESERVA = getKey("SOLICITUDES_SOLICITARDESDERESERVA");
	public static final String SOLICITUDES_VERUDOC = getKey("SOLICITUDES_VERUDOC");
	public static final String SOLICITUD_PRORROGA = getKey("SOLICITUD_PRORROGA");
	public static final String GESTION_PRORROGA = getKey("VER_PRORROGA");

	public static final String SOLICITUDES_AUTORIZARDETALLESPRESTAMOS = getKey("SOLICITUDES_AUTORIZARDETALLESPRESTAMOS");
	public static final String SOLICITUDES_DENEGARDETALLESPRESTAMOS = getKey("SOLICITUDES_DENEGARDETALLESPRESTAMOS");
	public static final String SOLICITUDES_ELIMINARDETALLES = getKey("SOLICITUDES_ELIMINARDETALLES");
	public static final String SOLICITUDES_NUEVODETALLE = getKey("SOLICITUDES_NUEVODETALLE");
	public static final String SOLICITUDES_FORMBUSQUEDA = getKey("SOLICITUDES_FORMBUSQUEDA");
	public static final String SOLICITUDES_BUSCAR = getKey("SOLICITUDES_BUSCAR");
	public static final String SOLICITUDES_CONSULTAR_UNIDADES_DOCUMENTALES = getKey("SOLICITUDES_CONSULTAR_UNIDADES_DOCUMENTALES");
	public static final String HOME_CONSULTAS = getKey("HOME_CONSULTAS");

	public static final String SOLICITUDES_DEVOLVERDETALLESPRESTAMOS = getKey("SOLICITUDES_DEVOLVERDETALLESPRESTAMOS");
	public static final String SOLICITUDES_DETALLESDEVUELTOS = getKey("SOLICITUDES_DETALLESDEVUELTOS");
	public static final String SOLICITUDES_DEVOLVERUDOCS = getKey("SOLICITUDES_DEVOLVERUDOCS");
	public static final String SOLICITUDES_DEVOLVER_SOLICITUDES_FORM = getKey("SOLICITUDES_DEVOLVER_SOLICITUDES_FORM");
	public static final String SOLICITUDES_CREAR = getKey("SOLICITUDES_CREAR");

	public static final String SOLICITUDES_LISTADO_CONSULTAS = getKey("SOLICITUDES_LISTADO_CONSULTAS");
	public static final String SOLICITUDES_LISTADO_CONSULTAS_ENTREGAR = getKey("SOLICITUDES_LISTADO_CONSULTAS_ENTREGAR");
	public static final String SOLICITUDES_LISTADO_CONSULTAS_VER = getKey("SOLICITUDES_LISTADO_CONSULTAS_VER");
	public static final String SOLICITUDES_VERCONSULTA = getKey("SOLICITUDES_VERCONSULTA");
	public static final String SOLICITUDES_ENVIARDESDEVISTACOMPROBADO = getKey("SOLICITUDES_ENVIARDESDEVISTACOMPROBADO");
	public static final String SOLICITUDES_FORMBUSQUEDACONSULTA = getKey("SOLICITUDES_FORMBUSQUEDACONSULTA");
	public static final String SOLICITUDES_BUSCARCONSULTAS = getKey("SOLICITUDES_BUSCARCONSULTAS");
	public static final String SOLICITUDES_CONSULTAS_ELIMINARDETALLES = getKey("SOLICITUDES_CONSULTAS_ELIMINARDETALLES");
	public static final String SOLICITUDES_AUTORIZARDETALLESCONSULTAS = getKey("SOLICITUDES_AUTORIZARDETALLESCONSULTAS");

	public static final String SOLICITUDES_DEVOLVERDETALLESCONSULTAS = getKey("SOLICITUDES_DEVOLVERDETALLESCONSULTAS");
	public static final String SOLICITUDES_DENEGARDETALLESCONSULTAS = getKey("SOLICITUDES_DENEGARDETALLESCONSULTAS");
	public static final String SOLICITUDES_EDICION_CONSULTA = getKey("SOLICITUDES_EDICION_CONSULTA");
	public static final String SOLICITUDES_CONSULTAS_NUEVO = getKey("SOLICITUDES_CONSULTAS_NUEVO");
	public static final String SOLICITUDES_SELECT_PRESTAMO_CEDER = getKey("SOLICITUDES_SELECT_PRESTAMO_CEDER");
	public static final String SOLICITUDES_SELECT_USUARIO_CEDER = getKey("SOLICITUDES_SELECT_USUARIO_CEDER");
	public static final String SOLICITUDES_SELECT_REV_DOCUMENTACION_CEDER = getKey("SOLICITUDES_SELECT_REV_DOCUMENTACION_CEDER");

	public static final String SOLICITUDES_SELECCIONAR_PRESTAMO = getKey("SOLICITUDES_SELECCIONAR_PRESTAMO");
	public static final String ANIADIR_DETALLES_A_PRESTAMO = getKey("ANIADIR_DETALLES_A_PRESTAMO");

	public static final String SOLICITUDES_SELECCIONAR_CONSULTA = getKey("SOLICITUDES_SELECCIONAR_CONSULTA");
	public static final String ANIADIR_DETALLES_A_CONSULTA = getKey("ANIADIR_DETALLES_A_CONSULTA");

	public static final String PRESTAMOS_LISTADO_REVISION_DOCUMENTACION = getKey("PRESTAMOS_LISTADO_REVISION_DOCUMENTACION");
	public static final String PRESTAMOS_REVISION_DOCUMENTACION = getKey("PRESTAMOS_REVISION_DOCUMENTACION");

	/**
	 * CLAVES PARA LAS TRANSFERENCIAS
	 */

	public static final String TRANSFERENCIAS_GESTION_PREVISIONES = getKey("TRANSFERENCIAS_GESTION_PREVISIONES");
	public static final String TRANSFERENCIAS_GESTION_RELACIONES = getKey("TRANSFERENCIAS_GESTION_RELACIONES");
	public static final String TRANSFERENCIAS_FORM_BUSQUEDA_PREVISIONES = getKey("TRANSFERENCIAS_FORM_BUSQUEDA_PREVISIONES");
	public static final String TRANSFERENCIAS_LISTADO_BUSQUEDA_PREVISIONES = getKey("TRANSFERENCIAS_LISTADO_BUSQUEDA_PREVISIONES");
	public static final String TRANSFERENCIAS_FORM_BUSQUEDA_RELACIONES = getKey("TRANSFERENCIAS_FORM_BUSQUEDA_RELACIONES");
	public static final String TRANSFERENCIAS_FORM_BUSQUEDA_INGRESOS_DIRECTOS = getKey("TRANSFERENCIAS_FORM_BUSQUEDA_INGRESOS_DIRECTOS");
	public static final String TRANSFERENCIAS_LISTADO_BUSQUEDA_RELACIONES = getKey("TRANSFERENCIAS_LISTADO_BUSQUEDA_RELACIONES");
	public static final String TRANSFERENCIAS_BUSCAR_SERIE = getKey("TRANSFERENCIAS_BUSCAR_SERIE");
	public static final String TRANSFERENCIAS_LISTADO_PREVISIONES_CREACION_RELACION = getKey("TRANSFERENCIAS_LISTADO_PREVISIONES_CREACION_RELACION");
	public static final String TRANSFERENCIAS_LISTADO_RELACIONES_ARCHIVO = getKey("TRANSFERENCIAS_LISTADO_RELACIONES_ARCHIVO");
	public static final String TRANSFERENCIAS_LISTADO_RELACIONES_OFICINA = getKey("TRANSFERENCIAS_LISTADO_RELACIONES_OFICINA");

	public static final String TRANSFERENCIAS_SELECCION_TIPO_NUEVA_PREVISION = getKey("TRANSFERENCIAS_NUEVA_PREVISION");
	public static final String TRANSFERENCIAS_NUEVA_PREVISION = getKey("TRANSFERENCIAS_NUEVA_PREVISION");
	public static final String TRANSFERENCIAS_VER_PREVISION = getKey("TRANSFERENCIAS_VER_PREVISION");
	public static final String TRANSFERENCIAS_PREVISIONES_EN_ELABORACION = getKey("TRANSFERENCIAS_PREVISIONES_EN_ELABORACION");
	public static final String TRANSFERENCIAS_PREVISIONES_EN_GESTION = getKey("TRANSFERENCIAS_PREVISIONES_EN_GESTION");
	public static final String TRANSFERENCIAS_MODIFICAR_FECHAS_PREVISION = getKey("TRANSFERENCIAS_MODIFICAR_FECHAS_PREVISION");
	public static final String TRANSFERENCIAS_EDICION_PREVISION = getKey("TRANSFERENCIAS_EDICION_PREVISION");
	public static final String TRANSFERENCIAS_ACEPTACION_PREVISION = getKey("TRANSFERENCIAS_ACEPTACION_PREVISION");
	public static final String TRANSFERENCIAS_RECHAZO_PREVISION = getKey("TRANSFERENCIAS_RECHAZO_PREVISION");
	public static final String TRANSFERENCIAS_CALENDARIO_PREVISIONES = getKey("TRANSFERENCIAS_CALENDARIO_PREVISIONES");
	public static final String TRANSFERENCIAS_CALENDARIO_PREVISIONES_MES = getKey("TRANSFERENCIAS_CALENDARIO_PREVISIONES_MES");
	public static final String TRANSFERENCIAS_VER_PREVISION_CALENDARIO_PREVISIONES = getKey("TRANSFERENCIAS_VER_PREVISION_CALENDARIO_PREVISIONES");

	public static final String TRANSFERENCIAS_NUEVA_RELACION = getKey("TRANSFERENCIAS_NUEVA_RELACION");
	public static final String TRANSFERENCIAS_VER_RELACION = getKey("TRANSFERENCIAS_VER_RELACION");
	public static final String TRANSFERENCIAS_VER_RELACIONES = getKey("TRANSFERENCIAS_VER_RELACIONES");
	public static final String TRANSFERENCIAS_DETALLE_PREVISION = getKey("TRANSFERENCIAS_DETALLE_PREVISION");
	public static final String TRANSFERENCIAS_ALTA_DETALLE_PREVISION = getKey("TRANSFERENCIAS_ALTA_DETALLE_PREVISION");
	public static final String TRANSFERENCIAS_EDICION_DETALLE_PREVISION = getKey("TRANSFERENCIAS_EDICION_DETALLE_PREVISION");
	public static final String TRANSFERENCIAS_VER_INFORME_UBICACION = getKey("TRANSFERENCIAS_VER_INFORME_UBICACION");
	public static final String TRANSFERENCIAS_VER_INFORME_RESERVAS = getKey("TRANSFERENCIAS_VER_INFORME_RESERVAS");
	public static final String TRANSFERENCIAS_VER_UNIDAD_DOCUMENTAL = getKey("TRANSFERENCIAS_VER_UNIDAD_DOCUMENTAL");
	public static final String TRANSFERENCIAS_SELECCION_EXPEDIENTES = getKey("TRANSFERENCIAS_SELECCION_EXPEDIENTES");
	public static final String TRANSFERENCIAS_CAJAS_A_COTEJAR = getKey("TRANSFERENCIAS_CAJAS_A_COTEJAR");
	public static final String TRANSFERENCIAS_CONTENIDO_CAJA_A_COTEJAR = getKey("TRANSFERENCIAS_CONTENIDO_CAJA_A_COTEJAR");
	public static final String TRANSFERENCIAS_IMPRESION_CARTELAS = getKey("TRANSFERENCIAS_IMPRESION_CARTELAS");
	public static final String TRANSFERENCIAS_UDOC_ELECTRONICAS_A_COTEJAR = getKey("TRANSFERENCIAS_UDOC_ELECTRONICAS_A_COTEJAR");
	public static final String TRANSFERENCIAS_RELACIONES_PREVISION = getKey("TRANSFERENCIAS_RELACIONES_PREVISION");
	public static final String TRANSFERENCIAS_EDICION_RELACION = getKey("TRANSFERENCIAS_EDICION_RELACION");
	public static final String TRANSFERENCIAS_NUEVA_UNIDAD_DOCUMENTAL = getKey("TRANSFERENCIAS_NUEVA_UNIDAD_DOCUMENTAL");
	public static final String TRANSFERENCIAS_IMPORT_UNIDADES_DOCUMENTALES = getKey("TRANSFERENCIAS_IMPORT_UNIDADES_DOCUMENTALES");
	public static final String TRANSFERENCIAS_IMPORT_UNIDADES_DOCUMENTALES_RESULT = getKey("TRANSFERENCIAS_IMPORT_UNIDADES_DOCUMENTALES_RESULT");
	public static final String TRANSFERENCIAS_EDICION_INTERESADOS = getKey("TRANSFERENCIAS_EDICION_INTERESADOS");
	public static final String TRANSFERENCIAS_INTERESADO = getKey("TRANSFERENCIAS_INTERESADO");
	public static final String TRANSFERENCIAS_EMPLAZAMIENTO = getKey("TRANSFERENCIAS_EMPLAZAMIENTO");
	public static final String TRANSFERENCIAS_EDICION_DESCRIPCION_PARTE = getKey("TRANSFERENCIAS_EDICION_DESCRIPCION_PARTE");
	public static final String TRANSFERENCIAS_EDICION_DESCRIPCION_CONTENIDO_CAJA = getKey("TRANSFERENCIAS_EDICION_DESCRIPCION_CONTENIDO_CAJA");
	public static final String TRANSFERENCIAS_ADD_UINST_REEA = getKey("TRANSFERENCIAS_ADD_UINST_REEA");
	public static final String TRANSFERENCIAS_NUEVA_FRACCION_SERIE = getKey("TRANSFERENCIAS_NUEVA_FRACCION_SERIE");
	public static final String TRANSFERENCIAS_VER_FRACCION_SERIE = getKey("TRANSFERENCIAS_VER_FRACCION_SERIE");
	public static final String TRANSFERENCIAS_VER_DATOS_FRACCION_SERIE = getKey("TRANSFERENCIAS_VER_DATOS_FRACCION_SERIE");
	public static final String TRANSFERENCIAS_ADD_UDOCS_ELECTRONICAS = getKey("TRANSFERENCIAS_ADD_UDOCS_ELECTRONICAS");
	public static final String TRANSFERENCIAS_FORMATO_REENCAJADO = getKey("TRANSFERENCIAS_FORMATO_REENCAJADO");

	public static final String TRANSFERENCIAS_CAJAS_REENCAJADO_A_COTEJAR = getKey("TRANSFERENCIAS_CAJAS_REENCAJADO_A_COTEJAR");

	public static final String DOCUMENTO = getKey("DOCUMENTO");
	public static final String SOPORTE = getKey("SOPORTE");
	public static final String TRANSFERENCIAS_ORGANIZACION_CAJAS = getKey("TRANSFERENCIAS_ORGANIZACION_CAJAS");
	public static final String TRANSFERENCIAS_NUEVA_CAJA = getKey("TRANSFERENCIAS_NUEVA_CAJA");
	public static final String TRANSFERENCIAS_EDICION_CAJA = getKey("TRANSFERENCIAS_EDICION_CAJA");
	public static final String TRANSFERENCIAS_INCORPORAR_A_CAJA = getKey("TRANSFERENCIAS_INCORPORAR_A_CAJA");
	public static final String TRANSFERENCIAS_RECIBIR_RELACION = getKey("TRANSFERENCIAS_RECIBIR_RELACION");
	public static final String TRANSFERENCIAS_RECHAZAR_RELACION = getKey("TRANSFERENCIAS_RECHAZAR_RELACION");
	public static final String TRANSFERENCIAS_MODIFICAR_UBICACION = getKey("TRANSFERENCIAS_MODIFICAR_UBICACION");
	public static final String TRANSFERENCIAS_ASIGNACION_GESTOR_PREVISION = getKey("TRANSFERENCIAS_ASIGNACION_GESTOR_PREVISION");
	public static final String TRANSFERENCIAS_SELECT_PREVISION_CEDER = getKey("TRANSFERENCIAS_SELECT_PREVISION_CEDER");
	public static final String TRANSFERENCIAS_SELECT_RELACION_CEDER = getKey("TRANSFERENCIAS_SELECT_RELACION_CEDER");
	public static final String TRANSFERENCIAS_SELECT_USUARIO_CEDER = getKey("TRANSFERENCIAS_SELECT_USUARIO_CEDER");
	public static final String TRANSFERENCIAS_DESCRIPCION_CONTENIDO = getKey("TRANSFERENCIAS_DESCRIPCION_CONTENIDO");
	public static final String TRANSFERENCIAS_SUSTITUCION_PRODUCTORES = getKey("TRANSFERENCIAS_SUSTITUCION_PRODUCTORES");
	public static final String TRANSFERENCIAS_ASOCIAR_CAJA = getKey("TRANSFERENCIAS_ASOCIAR_CAJA");
	public static final String TRANSFERENCIAS_DIVIDIR_UDOC = getKey("TRANSFERENCIAS_DIVIDIR_UDOC");

	/**
	 * CLAVES PARA AUDITORIA
	 */
	public static final String AUDITORIA_FORMBUSQUEDA = getKey("AUDITORIA_FORMBUSQUEDA");
	public static final String AUDITORIA_BUSCAR = getKey("AUDITORIA_BUSCAR");
	public static final String AUDITORIA_ACTIONLIST = getKey("AUDITORIA_ACTIONLIST");
	public static final String AUDITORIA_DETALLEPISTA = getKey("AUDITORIA_DETALLEPISTA");
	public static final String AUDITORIA_USERSLIST = getKey("AUDITORIA_USERSLIST");
	public static final String AUDITORIA_BUSCAR_EXTERNO = getKey("AUDITORIA_BUSCAR_EXTERNO");

	/**
	 * CLAVES PARA ADMINISTRACION Y CONTROL DE ACCESO
	 */
	public static final String USUARIOS_SELECCION_ORGANO = getKey("USUARIOS_SELECCION_ORGANO");;
	public static final String USUARIOS_ALTA_ORGANO = getKey("USUARIOS_ALTA_ORGANO");

	public static final String USUARIOS_EDICION_ORGANO = getKey("USUARIOS_EDICION_ORGANO");
	public static final String USUARIOS_INFO_ORGANO = getKey("USUARIOS_INFO_ORGANO");
	public static final String USUARIOS_LISTA_ORGANOS = getKey("USUARIOS_LISTA_ORGANOS");
	public static final String USUARIOS_SELECCION_PERMISOS_EN_LISTA = getKey("USUARIOS_SELECCION_PERMISOS_EN_LISTA");

	public static final String USUARIOS_SELECCION_USUARIO = getKey("USUARIOS_SELECCION_USUARIO");
	public static final String USUARIOS_NUEVO_USUARIO = getKey("USUARIOS_NUEVO_USUARIO");
	public static final String USUARIO_BUSQUEDA = getKey("USUARIO_BUSQUEDA");
	public static final String USUARIO_BUSQUEDA_ORGANO = getKey("USUARIO_BUSQUEDA_ORGANO");
	public static final String USUARIO_BUSCAR_USUARIOS = getKey("USUARIO_BUSCAR_USUARIOS");
	public static final String USUARIO_BUSCAR_ORGANO = getKey("USUARIO_BUSCAR_ORGANO");
	public static final String USUARIO_EDICION_USUARIO = getKey("USUARIO_EDICION_USUARIO");
	public static final String USUARIO_VER_USUARIO = getKey("USUARIO_VER_USUARIO");
	public static final String USUARIO_ADD_ROLE = getKey("USUARIO_ADD_ROLE");
	public static final String USUARIO_DELETE_ROLE = getKey("USUARIO_DELETE_ROLE");

	public static final String USUARIO_ADD_GRUPO = getKey("USUARIO_ADD_GRUPO");
	public static final String USUARIO_DELETE_GRUPO = getKey("USUARIO_DELETE_GRUPO");
	// public static final String USUARIO_ADD_USUARIOS_A_GRUPO =
	// getKey("USUARIO_ADD_USUARIOS_A_GRUPO");
	public static final String USUARIO_BUSQUEDA_GRUPOS = getKey("USUARIO_BUSQUEDA_GRUPOS");

	public static final String USUARIO_LISTA_LISTAS_ACCESO = getKey("USUARIO_LISTA_LISTAS_ACCESO");
	public static final String USUARIO_ALTA_LISTA_ACCESO = getKey("USUARIO_ALTA_LISTA_ACCESO");
	public static final String USUARIO_EDICION_LISTA_ACCESO = getKey("USUARIO_EDICION_LISTA_ACCESO");
	public static final String USUARIO_INFO_LISTA_ACCESO = getKey("USUARIO_INFO_LISTA_ACCESO");
	public static final String USUARIO_BUSQUEDA_LISTAS_ACCESO = getKey("USUARIO_BUSQUEDA_LISTAS_ACCESO");

	public static final String USUARIO_LISTADO = getKey("USUARIOS_USUARIO_LISTADO");

	public static final String USUARIOS_LISTA_ROLES = getKey("USUARIOS_LISTA_ROLES");
	public static final String USUARIOS_INFO_ROL = getKey("USUARIOS_INFO_ROL");
	public static final String USUARIOS_ALTA_ROL = getKey("USUARIOS_ALTA_ROL");
	public static final String USUARIOS_EDICION_ROL = getKey("USUARIOS_EDICION_ROL");
	public static final String USUARIOS_SELECCION_USUARIOS = getKey("USUARIOS_SELECCION_USUARIOS");
	public static final String USUARIOS_SELECCION_PERMISOS = getKey("USUARIOS_SELECCION_PERMISOS");

	public static final String USUARIOS_LISTA_GRUPOS = getKey("USUARIOS_LISTA_GRUPOS");
	public static final String USUARIOS_INFO_GRUPO = getKey("USUARIOS_INFO_GRUPO");
	public static final String USUARIOS_ALTA_GRUPO = getKey("USUARIOS_ALTA_GRUPO");
	public static final String USUARIOS_EDICION_GRUPO = getKey("USUARIOS_EDICION_GRUPO");
	public static final String USUARIO_ADD_GRUPO_A_LISTA = getKey("USUARIO_ADD_GRUPO_A_LISTA");
	public static final String USUARIOS_SELECCION_GRUPOS = getKey("USUARIOS_SELECCION_GRUPOS");
	public static final String USUARIOS_SELECCION_ORGANOS = getKey("USUARIOS_SELECCION_ORGANOS");

	public static final String FICHAS_LISTADO = getKey("FICHAS_LISTADO");
	public static final String FICHAS_EDICION = getKey("FICHAS_EDICION");
	public static final String FICHAS_IMPORTAR = getKey("FICHAS_IMPORTAR");
	public static final String FICHAS_EXPORTAR = getKey("FICHAS_EXPORTAR");
	public static final String FICHAS_EDICION_AVANZADA = getKey("FICHAS_EDICION_AVANZADA");
	public static final String DUPLICAR_FICHA = getKey("DUPLICAR_FICHA");


	public static final String FORMATO_FICHAS_CAMBIO_FORMATO_PREFERENTE = getKey("FORMATO_FICHAS_CAMBIO_FORMATO_PREFERENTE");

	public static final String FORMATO_FICHAS_LISTADO = getKey("FORMATO_FICHAS_LISTADO");
	public static final String FORMATO_FICHAS_EDICION = getKey("FORMATO_FICHAS_EDICION");
	public static final String FORMATO_FICHAS_IMPORTAR = getKey("FORMATO_FICHAS_IMPORTAR");
	public static final String FORMATO_FICHAS_EXPORTAR = getKey("FORMATO_FICHAS_EXPORTAR");
	public static final String FORMATO_FICHAS_BUSQUEDA = getKey("FORMATO_FICHAS_BUSQUEDA");

	public static final String AREAS_LISTADO = getKey("AREAS_LISTADO");
	public static final String AREAS_EDICION = getKey("AREAS_EDICION");

	public static final String CAMPOS_DATO_LISTADO = getKey("CAMPOS_DATO_LISTADO");
	public static final String CAMPOS_TABLA_LISTADO = getKey("CAMPOS_TABLA_LISTADO");
	public static final String CAMPOS_DATO_EDICION = getKey("CAMPOS_DATO_EDICION");
	public static final String CAMPOS_TABLA_EDICION = getKey("CAMPOS_TABLA_EDICION");
	public static final String CAMPOS_TABLA_EDIT_INFORMACION = getKey("CAMPOS_TABLA_EDIT_INFORMACION");

	/**
	 * CLAVES PARA DOCUMENTOS ELECTR�NICOS
	 */

	public static final String DOCUMENTOS_ELECTRONICOS_ENTRADA = getKey("DOCUMENTOS_ELECTRONICOS_ENTRADA");
	public static final String DOCUMENTOS_ELECTRONICOS_HOME = getKey("DOCUMENTOS_ELECTRONICOS_HOME");
	public static final String DOCUMENTOS_ELECTRONICOS_DOCUMENTO_EDIT = getKey("DOCUMENTOS_ELECTRONICOS_DOCUMENTO_EDIT");
	public static final String DOCUMENTOS_ELECTRONICOS_DOCUMENTO_FORM = getKey("DOCUMENTOS_ELECTRONICOS_DOCUMENTO_FORM");
	public static final String DOCUMENTOS_ELECTRONICOS_CLASIFICADOR_EDIT = getKey("DOCUMENTOS_ELECTRONICOS_CLASIFICADOR_EDIT");
	public static final String DOCUMENTOS_ELECTRONICOS_CLASIFICADOR_FORM = getKey("DOCUMENTOS_ELECTRONICOS_CLASIFICADOR_FORM");

	/**
	 * CLAVES PARA VALORACION Y ELIMINACION DE SERIES DOCUMENTALES
	 */
	public static final String VALORACION_PHANTON_NODE = getKey("VALORACION_PHANTON_NODE");
	public static final String VALORACION_VER_VALORACION = getKey("VALORACION_VER_VALORACION");
	public static final String VALORACION_SERIE_DICTAMINADA = getKey("VALORACION_SERIE_DICTAMINADA");
	public static final String VALORACION_VALORACIONES_EN_ELABORACION = getKey("VALORACION_VALORACIONES_EN_ELABORACION");
	public static final String VALORACION_VALORACIONES_A_GESTIONAR = getKey("VALORACION_VALORACIONES_A_GESTIONAR");
	public static final String VALORACION_EDICION_VALORACION = getKey("VALORACION_EDICION_VALORACION");
	public static final String VALORACION_NUEVA_VALORACION = getKey("VALORACION_NUEVA_VALORACION");
	public static final String VALORACION_SELECCION_SERIE = getKey("VALORACION_SELECCION_SERIE");

	public static final String SELECCION_SERIES = getKey("SELECCION_SERIES");
	public static final String ELIMINACION_NUEVA_ELIMINACION = getKey("ELIMINACION_NUEVA_ELIMINACION");
	public static final String ELIMINACION_EDICION_ELIMINACION = getKey("ELIMINACION_EDICION_ELIMINACION");
	public static final String ELIMINACION_SELECCION_SERIE = getKey("ELIMINACION_SELECCION_SERIE");
	public static final String VALORACION_SELECCION_SERIES_PRECEDENTES = getKey("VALORACION_SELECCION_SERIES_PRECEDENTES");
	public static final String VALORACION_SELECCION_SERIES_DESCENDIENTES = getKey("VALORACION_SELECCION_SERIES_DESCENDIENTES");
	public static final String VALORACION_SELECCION_SERIES_RELACIONADAS = getKey("VALORACION_SELECCION_SERIES_RELACIONADAS");
	public static final String ELIMINACION_ELIMINACIONES_EN_ELABORACION = getKey("ELIMINACION_ELIMINACIONES_EN_ELABORACION");
	public static final String VALORACION_VER_ELIMINACION = getKey("VALORACION_VER_ELIMINACION");
	public static final String VALORACION_EDICION_ELIMINACION = getKey("VALORACION_EDICION_ELIMINACION");
	public static final String VALORACION_EDICION_ELIMINACION_AVANZADA = getKey("VALORACION_EDICION_ELIMINACION_AVANZADA");
	public static final String VALORACION_SOCITAR_VALIDACION = getKey("VALORACION_SOCITAR_VALIDACION");
	public static final String VALORACION_RECHAZAR_VALIDACION = getKey("VALORACION_RECHAZAR_VALIDACION");
	public static final String VALORACION_AUTORIZAR_EVALUACION = getKey("VALORACION_AUTORIZAR_EVALUACION");
	public static final String VALORACION_RECHAZAR_EVALUACION = getKey("VALORACION_RECHAZAR_EVALUACION");
	public static final String VALORACION_DICTAMEN = getKey("VALORACION_DICTAMEN");
	// public static final String VALORACION_AUTORIZAR_DICTAMEN =
	// getKey("VALORACION_AUTORIZAR_DICTAMEN");
	// public static final String VALORACION_RECHAZAR_DICTAMEN =
	// getKey("VALORACION_RECHAZAR_DICTAMEN");
	public static final String ELIMINACION_VER_UDOCS = getKey("ELIMINACION_VER_UDOCS");
	public static final String VALORACION_FORMBUSQUEDA = getKey("VALORACION_FORMBUSQUEDA");
	public static final String VALORACIONES_BUSCAR = getKey("VALORACIONES_BUSCAR");
	public static final String VALORACION_DETALLEVALORACION = getKey("VALORACION_DETALLEVALORACION");
	public static final String ELIMINACION_FORMBUSQUEDA = getKey("ELIMINACION_FORMBUSQUEDA");
	public static final String ELIMINACIONES_BUSCAR = getKey("ELIMINACIONES_BUSCAR");
	public static final String ELIMINACION_DESTRUCCION_FISICA = getKey("ELIMINACION_DESTRUCCION_FISICA");
	public static final String ELIMINACION_RECHAZAR_SELECCION = getKey("ELIMINACION_RECHAZAR_SELECCION");
	public static final String ELIMINACION_SOLICITUD_APROBACION = getKey("ELIMINACION_SOLICITUD_APROBACION");
	public static final String ELECCION_ARCHIVO = getKey("ELECCION_ARCHIVO");
	public static final String LISTADO_UDOCS_SERIE_NO_CONSERVAR = getKey("LISTADO_UDOCS_SERIE_NO_CONSERVAR");

	/**
	 * CLAVES PARA DOCUMENTOS VITALES
	 */

	/**
	 * CLAVES PARA LA ORGANIZACION
	 */
	public static final String ORGANIZACION_RESUMEN = getKey("ORGANIZACION_RESUMEN");

	public static final String ORGANIZACION_HOME = getKey("ORGANIZACION_HOME");

	public static final String ORGANIZACION_CREAR_INSTITUCION = getKey("ORGANIZACION_CREAR_INSTITUCION");

	public static final String ORGANIZACION_CREAR_ORGANO = getKey("ORGANIZACION_CREAR_ORGANO");

	public static final String ORGANIZACION_CREAR_ORGANIZACION = getKey("ORGANIZACION_CREAR_ORGANIZACION");

	public static final String RESUMEN_ESTADO_ORGANIZACION = getKey("RESUMEN_ESTADO_ORGANIZACION");

	public static final String ORGANIZACION_FECHAS = getKey("ORGANIZACION_FECHAS");

	public static final String ORGANIZACION_VER_ELEMENTO = getKey("ORGANIZACION_VER_ELEMENTO");

	public static final String ORGANIZACION_MOVER = getKey("ORGANIZACION_MOVER");

	public static final String ORGANIZACION_EDITAR_ELEMENTO = getKey("ORGANIZACION_EDITAR_ELEMENTO");

	public static final String ORGANIZACION_INFORME_OCUPACION = getKey("ORGANIZACION_INFORME_OCUPACION");

	public static final String USUARIOS_SELECCION_ORGANIZACION = getKey("USUARIOS_SELECCION_ORGANIZACION");

	public static final String USUARIOS_ALTA_ORGANIZACION = getKey("USUARIOS_ALTA_ORGANIZACION");

	public static final String USUARIOS_LISTA_INSTITUCIONES = getKey("USUARIOS_LISTA_INSTITUCIONES");

	public static final String USUARIOS_LISTA_ORGANIZACIONES = getKey("USUARIOS_LISTA_ORGANIZACIONES");

	public static final String USUARIO_BUSQUEDA_ORGANIZACION = getKey("USUARIOS_BUSQUEDA_ORGANIZACION");

	public static final String USUARIOS_LISTA_USUARIOS = getKey("USUARIOS_LISTA_USUARIOS");

	public static final String SELECCION_NOMBRE_USUARIO = getKey("SELECCION_NOMBRE_USUARIO");

	public static final String DOCUMENTOS_VITALES_FORM_BUSQUEDA = getKey("DOCUMENTOS_VITALES_FORM_BUSQUEDA");
	public static final String DOCUMENTOS_VITALES_LISTADO_BUSQUEDA = getKey("DOCUMENTOS_VITALES_LISTADO_BUSQUEDA");
	public static final String DOCUMENTOS_VITALES_GESTIONAR_DOCUMENTOS = getKey("DOCUMENTOS_VITALES_GESTIONAR_DOCUMENTOS");
	public static final String DOCUMENTOS_VITALES_GESTIONAR_DOCUMENTOS_PENDIENTES = getKey("DOCUMENTOS_VITALES_GESTIONAR_DOCUMENTOS_PENDIENTES");
	public static final String DOCUMENTOS_VITALES_VER_DOCUMENTO = getKey("DOCUMENTOS_VITALES_VER_DOCUMENTO");
	public static final String DOCUMENTOS_VITALES_VER_DOCUMENTO_VIGENTE = getKey("DOCUMENTOS_VITALES_VER_DOCUMENTO_VIGENTE");
	public static final String DOCUMENTOS_VITALES_EDITAR_DOCUMENTO = getKey("DOCUMENTOS_VITALES_EDITAR_DOCUMENTO");
	public static final String DOCUMENTOS_VITALES_VER_TIPOS_DOCUMENTOS = getKey("DOCUMENTOS_VITALES_VER_TIPOS_DOCUMENTOS");
	public static final String DOCUMENTOS_VITALES_VER_TIPO_DOCUMENTO = getKey("DOCUMENTOS_VITALES_VER_TIPO_DOCUMENTO");
	public static final String DOCUMENTOS_VITALES_CREAR_TIPO_DOCUMENTO = getKey("DOCUMENTOS_VITALES_CREAR_TIPO_DOCUMENTO");
	public static final String DOCUMENTOS_VITALES_EDITAR_TIPO_DOCUMENTO = getKey("DOCUMENTOS_VITALES_EDITAR_TIPO_DOCUMENTO");
	public static final String DOCUMENTOS_VITALES_PASO1_CREAR_DOCUMENTO = getKey("DOCUMENTOS_VITALES_PASO1_CREAR_DOCUMENTO");
	public static final String DOCUMENTOS_VITALES_PASO2_CREAR_DOCUMENTO = getKey("DOCUMENTOS_VITALES_PASO2_CREAR_DOCUMENTO");

	/* digitalizacion */

	public static final String DIGITALIZACION_PASO1_CREAR_TAREA = getKey("DIGITALIZACION_PASO1_CREAR_TAREA");
	public static final String DIGITALIZACION_PASO2_CREAR_TAREA = getKey("DIGITALIZACION_PASO2_CREAR_TAREA");
	public static final String DIGITALIZACION_GESTION_TAREAS = getKey("DIGITALIZACION_GESTION_TAREAS");
	public static final String DIGITALIZACION_GESTION_TAREAS_PENDIENTES = getKey("DIGITALIZACION_GESTION_TAREAS_PENDIENTES");
	public static final String DIGITALIZACION_GESTION_TAREAS_GESTIONAR = getKey("DIGITALIZACION_GESTION_TAREAS_GESTIONAR");
	public static final String DIGITALIZACION_VER_TAREA = getKey("DIGITALIZACION_VER_TAREA");
	public static final String DIGITALIZACION_FINALIZAR_CAPTURA = getKey("DIGITALIZACION_FINALIZAR_CAPTURA");
	public static final String DIGITALIZACION_FINALIZAR_VALIDACION_CAPTURA = getKey("DIGITALIZACION_FINALIZAR_VALIDACION_CAPTURA");
	public static final String DIGITALIZACION_FORM_BUSQUEDA = getKey("DIGITALIZACION_FORM_BUSQUEDA");
	public static final String DIGITALIZACION_LISTADO_BUSQUEDA = getKey("DIGITALIZACION_LISTADO_BUSQUEDA");
	public static final String DIGITALIZACION_SELECT_TAREA_CEDER = getKey("DIGITALIZACION_SELECT_TAREA_CEDER");
	public static final String DIGITALIZACION_SELECT_USUARIO_CEDER = getKey("DIGITALIZACION_SELECT_USUARIO_CEDER");
	public static final String DIGITALIZACION_ELIMINACION_TAREA = getKey("DIGITALIZACION_ELIMINACION_TAREA");
	public static final String DIGITALIZACION_RESULTADO_CESION_TAREA = getKey("DIGITALIZACION_RESULTADO_CESION_TAREA");

	/* Niveles archivos */
	public static final String ARCHIVOS_NIVELES = getKey("ARCHIVOS_NIVELES");
	public static final String ARCHIVOS_NIVELES_EDICION = getKey("ARCHIVOS_NIVELES_EDICION");
	public static final String ARCHIVOS_NIVELES_ALTA = getKey("ARCHIVOS_NIVELES_ALTA");
	public static final String LISTA_ARCHIVOS_ASOCIADOS = getKey("LISTA_ARCHIVOS_ASOCIADOS");

	/* Archivos */
	public static final String ARCHIVOS = getKey("ARCHIVOS");
	public static final String ARCHIVOS_EDICION = getKey("ARCHIVOS_EDICION");
	public static final String ARCHIVOS_ALTA = getKey("ARCHIVOS_ALTA");

	/* Reemplazo */
	public static final String REEMPLAZO_SIMPLE = getKey("REEMPLAZO_SIMPLE");
	public static final String LISTADO_REEMPLAZO_SIMPLE = getKey("LISTADO_REEMPLAZO_SIMPLE");
	public static final String REEMPLAZO_AVANZADO = getKey("REEMPLAZO_AVANZADO");
	public static final String CONFIRMACION_REEMPLAZO = getKey("CONFIRMACION_REEMPLAZO");
	public static final String REEMPLAZO_SERIES_AFECTADAS = getKey("REEMPLAZO_SERIES_AFECTADAS");
	public static final String LISTADO_REEMPLAZO_AVANZADO = getKey("LISTADO_REEMPLAZO_AVANZADO");

	public static final String EXPORTAR_INFORME_LISTADO = getKey("EXPORTAR_INFORME_LISTADO");

	public static final String ERROR_MULTILINEA = getKey("ERROR_MULTILINEA");

	/* Cuadro Clasificacion - niveles */
	public static final String DEPOSITO_NIVELES = getKey("DEPOSITO_NIVELES");
	public static final String DEPOSITO_NIVELES_DATOS = getKey("DEPOSITO_NIVELES_DATOS");
	public static final String DEPOSITO_SUBNIVELES_DATOS = getKey("DEPOSITO_SUBNIVELES_DATOS");
	public static final String DEPOSITO_NIVELES_ALTA = getKey("DEPOSITO_NIVELES_ALTA");
	public static final String DEPOSITO_NIVELES_EDICION = getKey("DEPOSITO_NIVELES_EDICION");
	public static final String DEPOSITO_NIVELES_AGREGAR_NIVEL = getKey("DEPOSITO_NIVELES_AGREGAR_NIVEL");
	public static final String DEPOSITO_NIVELES_NUEVO_HIJO = getKey("DEPOSITO_NIVELES_NUEVO_HIJO");

	/* Cuadro Clasificacion - niveles */
	public static final String CUADRO_CLASIFICACION_NIVELES = getKey("CUADRO_CLASIFICACION_NIVELES");
	public static final String CUADRO_CLASIFICACION_NIVELES_DATOS = getKey("CUADRO_CLASIFICACION_NIVELES_DATOS");
	public static final String CUADRO_CLASIFICACION_NIVELES_ALTA = getKey("CUADRO_CLASIFICACION_NIVELES_ALTA");
	public static final String CUADRO_CLASIFICACION_NIVELES_EDICION = getKey("CUADRO_CLASIFICACION_NIVELES_EDICION");
	public static final String CUADRO_CLASIFICACION_NIVELES_AGREGAR_NIVEL = getKey("CUADRO_CLASIFICACION_NIVELES_AGREGAR_NIVEL");
	public static final String CUADRO_CLASIFICACION_NIVELES_NUEVO_HIJO = getKey("CUADRO_CLASIFICACION_NIVELES_NUEVO_HIJO");

	/* Motivos Prestamos y Consultas */
	public static final String MOTIVOS_CONSULTA = getKey("MOTIVOS_CONSULTA");
	public static final String MOTIVO_CONSULTA_ALTA = getKey("MOTIVO_CONSULTA_ALTA");
	public static final String MOTIVO_CONSULTA_DATOS = getKey("MOTIVO_CONSULTA_DATOS");
	public static final String MOTIVO_CONSULTA_EDICION = getKey("MOTIVO_CONSULTA_EDICION");

	public static final String MOTIVOS_PRESTAMO = getKey("MOTIVOS_PRESTAMO");
	public static final String MOTIVO_PRESTAMO_ALTA = getKey("MOTIVO_PRESTAMO_ALTA");
	public static final String MOTIVO_PRESTAMO_DATOS = getKey("MOTIVO_PRESTAMO_DATOS");
	public static final String MOTIVO_PRESTAMO_EDICION = getKey("MOTIVO_PRESTAMO_EDICION");

	public static final String MOTIVOS_RECHAZO = getKey("MOTIVOS_RECHAZO");
	public static final String MOTIVO_RECHAZO_ALTA = getKey("MOTIVO_RECHAZO_ALTA");
	public static final String MOTIVO_RECHAZO_DATOS = getKey("MOTIVO_RECHAZO_DATOS");
	public static final String MOTIVO_RECHAZO_EDICION = getKey("MOTIVO_RECHAZO_EDICION");

	/* Gestion de Salas */
	public static final String SALAS = getKey("SALAS");
	public static final String SALAS_USUARIOS_CONSULTA = getKey("SALAS_USUARIOS_CONSULTA");
	public static final String SALAS_VER_EDIFICIO = getKey("SALAS_VER_EDIFICIO");
	public static final String SALAS_CREAR_EDIFICIO = getKey("SALAS_CREAR_EDIFICIO");
	public static final String SALAS_EDITAR_EDIFICIO = getKey("SALAS_EDITAR_EDIFICIO");
	public static final String SALAS_LISTADO_SALAS = getKey("SALAS_LISTADO_SALAS");
	public static final String SALAS_VER_SALA = getKey("SALAS_VER_SALA");
	public static final String SALAS_CREAR_SALA = getKey("SALAS_CREAR_SALA");
	public static final String SALAS_EDITAR_SALA = getKey("SALAS_EDITAR_SALA");
	public static final String SALAS_HABILITAR_MESAS = getKey("SALAS_HABILITAR_MESAS");
	public static final String SALAS_INHABILITAR_MESAS = getKey("SALAS_INHABILITAR_MESAS");
	public static final String SALAS_CREAR_MESAS = getKey("SALAS_CREAR_MESAS");
	public static final String SALAS_SELECCION_MESAS = getKey("SALAS_SELECCION_MESAS");
	public static final String SALAS_REGISTRO_ENTRADA = getKey("SALAS_REGISTRO_ENTRADA");
	public static final String SALAS_CREAR_REGISTRO = getKey("SALAS_CREAR_REGISTRO");
	public static final String SALAS_CONFIRMAR_REGISTRO_ENTRADA = getKey("SALAS_CONFIRMAR_REGISTRO_ENTRADA");
	public static final String SALAS_CONFIRMAR_REGISTRO_SALIDA = getKey("SALAS_CONFIRMAR_REGISTRO_SALIDA");
	public static final String SALAS_REGISTRO_SALIDA = getKey("SALAS_REGISTRO_SALIDA");
	public static final String SALAS_DATOS_REGISTRO_ENTRADA = getKey("SALAS_DATOS_REGISTRO_ENTRADA");
	public static final String SALAS_CONSULTAS_USUARIO = getKey("SALAS_CONSULTAS_USUARIO");
	public static final String SALAS_USUARIOS_REGISTRADOS = getKey("SALAS_USUARIOS_REGISTRADOS");
	public static final String SALAS_BUSCAR_USUARIOS = getKey("SALAS_BUSCAR_USUARIOS");
	public static final String SALAS_BUSCAR_ASISTENCIA_USUARIOS = getKey("SALAS_BUSCAR_ASISTENCIA_USUARIOS");
	public static final String SALAS_RESULTADO_BUSQUEDA_USUARIOS = getKey("SALAS_RESULTADO_BUSQUEDA_USUARIOS");
	public static final String SALAS_BUSCAR_EXPEDIENTES = getKey("SALAS_BUSCAR_EXPEDIENTES");
	public static final String SALAS_RESUMEN_SERVICIOS = getKey("SALAS_RESUMEN_SERVICIOS");
	public static final String SALAS_TEMAS_INVESTIGACION = getKey("SALAS_TEMAS_INVESTIGACION");
	public static final String SALAS_UNIDADES_CONSULTADAS = getKey("SALAS_UNIDADES_CONSULTADAS");

	/* Usuarios salas de Consulta */
	public static final String SALAS_VER_USUARIO = getKey("SALAS_VER_USUARIO");
	public static final String SALAS_CREAR_USUARIO = getKey("SALAS_CREAR_USUARIO");
	public static final String SALAS_EDITAR_USUARIO = getKey("SALAS_EDITAR_USUARIO");
	public static final String SALAS_BUSCADOR_USUARIOS = getKey("SALAS_BUSCADOR_USUARIOS");

	public static final String SALAS_ANIADIR_USUARIOS_EXTERNOS = getKey("SALAS_ANIADIR_USUARIOS_EXTERNOS");

	public static final String FILTRO_UDOCS_SERIE = getKey("FILTRO_UDOCS_SERIE");
	public static final String RESULTADO_UDOCS_SERIE = getKey("RESULTADO_UDOCS_SERIE");
}