-------------
-- SISTEMA --
-------------
-- Tabla: AGARCHIVO
DROP INDEX AGARCHIVO1;

-- Tabla: AGNIVELARCHIVO
DROP INDEX AGNIVELARCHIVO01;
DROP INDEX AGNIVELARCHIVO02;

-- Tabla: AGOBJBLOQUEO
DROP INDEX AGOBJBLOQUEO1;

-- Tabla: AGINFOSISTEMA
DROP INDEX AGINFOSISTEMA1;

-----------------------
-- CONTROL DE ACCESO --
-----------------------

-- Tabla: ASCAORGANO
DROP INDEX ASCAORGANO1;
DROP INDEX ASCAORGANO2;
DROP INDEX ASCAORGANO3;

-- Tabla: ASCAUSRORG
DROP INDEX ASCAUSRORG1;

-- Tabla:  ASCAGRUPO
DROP INDEX ASCAGRUPO1;
DROP INDEX ASCAGRUPO2;

-- Tabla: ASCAUSRGRP
DROP INDEX ASCAUSRGRP1;
DROP INDEX ASCAUSRGRP2;

-- Tabla: ASCAUSUARIO
DROP INDEX ASCAUSUARIO1;

-- Tabla: ASCAROL
DROP INDEX ASCAROL1;
DROP INDEX ASCAROL2;

-- Tabla: ASCAPERMGENROL
DROP INDEX ASCAPERMGENROL1;
DROP INDEX ASCAPERMGENROL2;

-- Tabla: ASCAROLUSR
DROP INDEX ASCAROLUSR1;
DROP INDEX ASCAROLUSR2;

-- Tabla: ASCALISTCA
DROP INDEX ASCALISTCA1;
DROP INDEX ASCALISTCA2;

-- Tabla: ASCAPERMLISTCA
DROP INDEX ASCAPERMLISTCA1;
DROP INDEX ASCAPERMLISTCA2;
DROP INDEX ASCAPERMLISTCA3;

--------------------
-- TRANSFERENCIAS --
--------------------

-- Tabla: ASGTPREVISI; --
DROP INDEX ASGTPREVISION1;
DROP INDEX ASGTPREVISION2;
DROP INDEX ASGTPREVISION3;
DROP INDEX ASGTPREVISION4;
DROP INDEX ASGTPREVISION5;

-- Tabla:  ASGTDETALLEPREV
DROP INDEX ASGTDETALLEPREV1;
DROP INDEX ASGTDETALLEPREV2;

-- Tabla: ASGTRENTREGA
DROP INDEX ASGTRENTREGA1;
DROP INDEX ASGTRENTREGA2;
DROP INDEX ASGTRENTREGA3;
DROP INDEX ASGTRENTREGA4;
DROP INDEX ASGTRENTREGA5;
DROP INDEX ASGTRENTREGA6;

-- Tabla: ASGTSNSEC
DROP INDEX ASGTSNSEC1;

-- Tabla: ASGTUNIDADDOCRE
DROP INDEX ASGTUNIDADDOCRE1;
DROP INDEX ASGTUNIDADDOCRE2;
DROP INDEX ASGTUNIDADDOCRE3;
DROP INDEX ASGTUNIDADDOCRE4;

--Tabla: ASGTUINSTALACIONRE
DROP INDEX ASGTUINSTALRE1;
DROP INDEX ASGTUINSTALRE2;

--Tabla: ASGTUINSTALACIONREEA
DROP INDEX ASGTUINSTALREEA1;
DROP INDEX ASGTUINSTALREEA2;

-- Tabla: ASGTUDOCENUI
DROP INDEX ASGTUDOCENUI1;
DROP INDEX ASGTUDOCENUI2;
DROP INDEX ASGTUDOCENUI3;

-- Tabla: AGFORMATO
DROP INDEX AGFORMATO1;
DROP INDEX AGFORMATO2;

-- Tabla: ASGTUDOCSDF
DROP INDEX ASGTUDOCSDF1;
DROP INDEX ASGTUDOCSDF2;

--------------
-- DEPOSITO --
--------------

-- Tabla: ASGDTIPOELEMENTO
DROP INDEX ASGDTIPOELEMENTO1;
DROP INDEX ASGDTIPOELEMENTO2;

-- Tabla: ASGDDEPOSITO
DROP INDEX ASGDDEPOSITO1;
DROP INDEX ASGDDEPOSITO2;

-- Tabla: ASGDDEPOSITOELECTRONICO
DROP INDEX ASGDDEPOSITOELECT1;

-- Tabla: ASGDELEMNOASIG
DROP INDEX ASGDELEMNOASIG1;
DROP INDEX ASGDELEMNOASIG2;
DROP INDEX ASGDELEMNOASIG3;

-- Tabla: ASGDELEMASIG
DROP INDEX ASGDELEMASIG1;
DROP INDEX ASGDELEMASIG2;
DROP INDEX ASGDELEMASIG3;
DROP INDEX ASGDELEMASIG4;

-- Tabla: ASGDHUECO
DROP INDEX ASGDHUECO1;
DROP INDEX ASGDHUECO2;
DROP INDEX ASGDHUECO3;
DROP INDEX ASGDHUECO4;
DROP INDEX ASGDHUECO5;
DROP INDEX ASGDHUECO6;
DROP INDEX ASGDHUECO7;
DROP INDEX ASGDHUECO8;

-- Tabla: ASGDSIGNUMORDEN
DROP INDEX ASGDSIGNUMORDEN1;

-- Tabla: ASGDUINSTALACION
DROP INDEX ASGDUINSTALACION1;
DROP INDEX ASGDUINSTALACION2;
DROP INDEX ASGDUINSTALACION3;

-- Tabla: ASGDHISTUINSTALACION;
DROP INDEX ASGDHISTUINST1;
DROP INDEX ASGDHISTUINST2;
DROP INDEX ASGDHISTUINST3;
DROP INDEX ASGDHISTUINST4;

-- Tabla: ASGDUDOCENUI
DROP INDEX ASGDUDOCENUI1;
DROP INDEX ASGDUDOCENUI2;
DROP INDEX ASGDUDOCENUI3;
DROP INDEX ASGDUDOCENUI4;

-----------------
-- SOLICUTUDES --
-----------------

-- Tabla: ASGPPRESTAMO
DROP INDEX ASGPPRESTAMO1;
DROP INDEX ASGPPRESTAMO2;
DROP INDEX ASGPPRESTAMO3;
DROP INDEX ASGPPRESTAMO4;

-- Tabla: ASGPMTVPRESTAMO
DROP INDEX ASGPMTVPRESTAMO1;

-- Tabla:  ASGPSOLICITUDUDOC
DROP INDEX ASGPSOLICITUDUDOC1;
DROP INDEX ASGPSOLICITUDUDOC2;
DROP INDEX ASGPSOLICITUDUDOC3;
DROP INDEX ASGPSOLICITUDUDOC4;
DROP INDEX ASGPSOLICITUDUDOC5;

-- Tabla: ASGPSNSEC
DROP INDEX ASGPSNSEC1;

-- Tabla: ASGPPRORROGA
DROP INDEX ASGPPRORROGA1;

-- Tabla: ASGPCSULTA
DROP INDEX ASGPCONSULTA1;
DROP INDEX ASGPCONSULTA2;
DROP INDEX ASGPCONSULTA3;
DROP INDEX ASGPCONSULTA4;

-- Tabla: ASGPMTVCONSULTA
DROP INDEX ASGPMTVCONSULTA1;
DROP INDEX ASGPMTVCONSULTA2;

-- Tabla: ASGPMTVRECHAZO
DROP INDEX ASGPMTVRECHAZO1;
DROP INDEX ASGPMTVRECHAZO2;

-- Tabla: ASGPTEMA
DROP INDEX ASGPTEMA1;

-- ASGPREVDOCUDOC
DROP INDEX ASGPREVDOCUDOC1;
DROP INDEX ASGPREVDOCUDOC2;
DROP INDEX ASGPREVDOCUDOC3;

-----------------
-- DESCRIPCION --
-----------------

-- Tabla: ADAREA
DROP INDEX ADAREA1;
DROP INDEX ADAREA2;
DROP INDEX ADAREA3;

-- Tabla: ADCAMPOTBL
DROP INDEX ADCAMPOTBL1;
DROP INDEX ADCAMPOTBL2;
DROP INDEX ADCAMPOTBL3;
DROP INDEX ADCAMPOTBL4;
DROP INDEX ADCAMPOTBL5;

-- Tabla: ADCAMPODATO
DROP INDEX ADCAMPODATO1;
DROP INDEX ADCAMPODATO2;
DROP INDEX ADCAMPODATO3;
DROP INDEX ADCAMPODATO4;
DROP INDEX ADCAMPODATO5;
DROP INDEX ADCAMPODATO6;

-- Tabla: ADFICHA
DROP INDEX ADFICHA1;
DROP INDEX ADFICHA2;
DROP INDEX ADFICHA3;

-- Tabla: ADFMTFICHA
DROP INDEX ADFMTFICHA1;
DROP INDEX ADFMTFICHA2;

-- Tabla: ADFMTPREF
DROP INDEX ADFMTPREF1;

-- Tabla: ADTEXTTBLVLD
DROP INDEX ADTEXTTBLVLD1;
DROP INDEX ADTEXTTBLVLD2;

-- Tabla: ADCTLGLISTAD
DROP INDEX ADCTLGLISTAD1;
DROP INDEX ADCTLGLISTAD2;

-- Tabla: ADCTLGTBLVLD
DROP INDEX ADCTLGTBLVLD1;

-- Tabla: ADDESCRIPTOR
DROP INDEX ADDESCRIPTOR1;
DROP INDEX ADDESCRIPTOR2;
DROP INDEX ADDESCRIPTOR3;
DROP INDEX ADDESCRIPTOR4;
DROP INDEX ADDESCRIPTOR5;

-- Tabla: ADUSOOBJETO
DROP INDEX ADUSOOBJETO1;

-- Tabla: ADVCTEXTCF
DROP INDEX ADVCTEXTCF1;
DROP INDEX ADVCTEXTCF2;
DROP INDEX ADVCTEXTCF3;

-- Tabla: ADVCTEXTLCF
DROP INDEX ADVCTEXTLCF1;
DROP INDEX ADVCTEXTLCF2;

-- Tabla: ADVCNUMCF
DROP INDEX ADVCNUMCF1;
DROP INDEX ADVCNUMCF2;
DROP INDEX ADVCNUMCF3;

-- Tabla: ADVCFECHACF
DROP INDEX ADVCFECHACF1;
DROP INDEX ADVCFECHACF2;
DROP INDEX ADVCFECHACF3;
DROP INDEX ADVCFECHACF4;
DROP INDEX ADVCFECHACF5;

-- Tabla: ADVCREFCF
DROP INDEX ADVCREFCF1;
DROP INDEX ADVCREFCF2;
DROP INDEX ADVCREFCF3;
DROP INDEX ADVCREFCF4;
DROP INDEX ADVCREFCF5;

-- Tabla: ADVCTEXTDESCR
DROP INDEX ADVCTEXTDESCR1;
DROP INDEX ADVCTEXTDESCR2;
DROP INDEX ADVCTEXTDESCR3;

-- Tabla: ADVCTEXTLDESCR
DROP INDEX ADVCTEXTLDESCR1;
DROP INDEX ADVCTEXTLDESCR2;

-- Tabla: ADVCNUMDESCR
DROP INDEX ADVCNUMDESCR1;
DROP INDEX ADVCNUMDESCR2;
DROP INDEX ADVCNUMDESCR3;

-- Tabla: ADVCFECHADESCR
DROP INDEX ADVCFECHADESCR1;
DROP INDEX ADVCFECHADESCR2;
DROP INDEX ADVCFECHADESCR3;
DROP INDEX ADVCFECHADESCR4;
DROP INDEX ADVCFECHADESCR5;

-- Tabla: ADVCREFDESCR
DROP INDEX ADVCREFDESCR1;
DROP INDEX ADVCREFDESCR2;
DROP INDEX ADVCREFDESCR3;
DROP INDEX ADVCREFDESCR4;

-- Tabla: ASGTMAPDESCRUDOC
DROP INDEX ASGTMAPDESCRUDOC1;

------------
-- FONDOS --
------------

--Tabla: ASGFNIVELCF
DROP INDEX ASGFNIVELCF1;
DROP INDEX ASGFNIVELCF2;

-- Tabla: ASGFESTRUCTJNIVCF
DROP INDEX ASGFESTRUCTJNIVCF1;
DROP INDEX ASGFESTRUCTJNIVCF2;

-- Tabla: ASGFELEMENTOCF
DROP INDEX ASGFELEMENTOCF1;
DROP INDEX ASGFELEMENTOCF2;
DROP INDEX ASGFELEMENTOCF3;
DROP INDEX ASGFELEMENTOCF4;
DROP INDEX ASGFELEMENTOCF5;
DROP INDEX ASGFELEMENTOCF6;
DROP INDEX ASGFELEMENTOCF7;

-- Tabla: ASGFSERIE
DROP INDEX ASGFSERIE1;
DROP INDEX ASGFSERIE2;
DROP INDEX ASGFSERIE3;
DROP INDEX ASGFSERIE4;

-- Tabla: ASGFVOLUMENSERIE
DROP INDEX ASGFVOLUMENSERIE1;

-- Tabla:  ASGFENTPRODUCTORA
DROP INDEX ASGFENTPRODUCTORA1;

-- Tabla:  ASGFFONDO
DROP INDEX ASGFFONDO1;
DROP INDEX ASGFFONDO2;

-- Tabla: ASGFNUMSECVAL
DROP INDEX ASGFNUMSECVAL1;

-- Tabla: ASGFNUMSECSEL
DROP INDEX ASGFNUMSECSEL1;

-- Tabla:  ASGFPRODSERIE
DROP INDEX ASGFPRODSERIE1;
DROP INDEX ASGFPRODSERIE2;

-- Tabla: ASGFUNIDADDOC
DROP INDEX ASGFUNIDADDOC1;
DROP INDEX ASGFUNIDADDOC2;
DROP INDEX ASGFUNIDADDOC3;
DROP INDEX ASGFUNIDADDOC4;

-- Tabla:  ASGFSOLICITUDSERIE
DROP INDEX ASGFSOLICITUDSER1;
DROP INDEX ASGFSOLICITUDSER2;

-- Tabla: ASGFORGPROD
DROP INDEX ASGFORGPROD1;

-- Tabla: ASGFVALSERIE
DROP INDEX ASGFVALSERIE1;
DROP INDEX ASGFVALSERIE2;
DROP INDEX ASGFVALSERIE3;
DROP INDEX ASGFVALSERIE4;

-- Tabla: ASGFELIMSERIE
DROP INDEX ASGFELIMSERIE1;
DROP INDEX ASGFELIMSERIE2;

-- Tabla: ASGFELIMSELUDOC
DROP INDEX ASGFELIMSELUDOC1;
DROP INDEX ASGFELIMSELUDOC2;

-- Tabla: ASGFELIMUDOCCONS
DROP INDEX ASGFELIMUDOCCONS1;
DROP INDEX ASGFELIMUDOCCONS2;


-- Tabla: ASGFHISTUDOC
DROP INDEX ASGFHISTUDOC1;
DROP INDEX ASGFHISTUDOC2;

-- Tabla: ASGFUDOCSDF
DROP INDEX ASGFUDOCSDF1;

-----------------------------
-- DOCUMENTOS ELECTRONICOS --
-----------------------------

-- Tabla: ADOCCLASIFCF
DROP INDEX ADOCCLASIFCF1;
DROP INDEX ADOCCLASIFCF2;
DROP INDEX ADOCCLASIFCF3;
DROP INDEX ADOCCLASIFCF4;

-- Tabla: ADOCDOCUMENTOCF
DROP INDEX ADOCDOCUMENTOCF1;
DROP INDEX ADOCDOCUMENTOCF2;
DROP INDEX ADOCDOCUMENTOCF3;

-- Tabla: ADOCCLASIFDESCR
DROP INDEX ADOCCLASIFDESCR1;
DROP INDEX ADOCCLASIFDESCR2;
DROP INDEX ADOCCLASIFDESCR3;
DROP INDEX ADOCCLASIFDESCR4;

-- Tabla: ADOCDOCUMENTODESCR
DROP INDEX ADOCDOCUMENTODESC1;
DROP INDEX ADOCDOCUMENTODESC2;
DROP INDEX ADOCDOCUMENTODESC3;

-- Tabla: ADOCFICHACLF
DROP INDEX ADOCFICHACLF1;

-- Tabla: ADOCTCAPTURA
DROP INDEX ADOCTCAPTURA1;
DROP INDEX ADOCTCAPTURA2;
DROP INDEX ADOCTCAPTURA3;

-- Tabla: ADPCDOCUMENTOVIT
DROP INDEX ADPCDOCUMENTOVIT1;

-- Tabla: ADPCUSODOCVIT
DROP INDEX ADPCUSODOCVIT1;

-- Tabla: ADPCTIPODOCVIT
DROP INDEX ADPCTIPODOCVIT1;

-- Tabla: ADPCTIPODOCPROC
DROP INDEX ADPCTIPODOCPROC1;

---------------
-- AUDITORIA --
---------------

-- Tabla: AATRAZA
DROP INDEX AATRAZA1;
DROP INDEX AATRAZA2;
DROP INDEX AATRAZA3;

-- Tabla: AADATOSTRAZA
DROP INDEX AADATOSTRAZA1;
DROP INDEX AADATOSTRAZA2;

-- Tabla: AANAUDITUSR
DROP INDEX AANAUDITUSR1;

-- Tabla: AANAUDITACCION
DROP INDEX AANAUDITACCION1;


---------------------------------------------------------------------------------------------
-- Índices de las tablas para almacenar los campos descriptivos de unidades en alta/relación
---------------------------------------------------------------------------------------------
--Tabla: ADVCFECHAUDOCRE
DROP INDEX ADVCFECHAUDOCRE1;
DROP INDEX ADVCFECHAUDOCRE2;
DROP INDEX ADVCFECHAUDOCRE3;
DROP INDEX ADVCFECHAUDOCRE4;
DROP INDEX ADVCFECHAUDOCRE5;

--Tabla: ADVCNUMUDOCRE
DROP INDEX ADVCNUMUDOCRE1;
DROP INDEX ADVCNUMUDOCRE2;
DROP INDEX ADVCNUMUDOCRE3;

--Tabla: ADVCREFUDOCRE
DROP INDEX ADVCREFUDOCRE1;
DROP INDEX ADVCREFUDOCRE2;
DROP INDEX ADVCREFUDOCRE3;
DROP INDEX ADVCREFUDOCRE4;

--Tabla: ADVCTEXTLUDOCRE
DROP INDEX ADVCTEXTLUDOCRE1;
DROP INDEX ADVCTEXTLUDOCRE2;

--Tabla: ADVCTEXTUDOCRE
DROP INDEX ADVCTEXTUDOCRE1;
DROP INDEX ADVCTEXTUDOCRE2;


--Tabla: ASGFDIVISIONFS
DROP INDEX ASGFDIVISIONFS1;


--Tabla: ASGFUDOCENDIVISIONFS
DROP INDEX ASGFUDOCENDIVFS1;


-- Tabla: ASGDSIGNUMHUECO
DROP INDEX ASGDSIGNUMHUECO1;

-- Tabla: ASGSEDIFICIO
DROP INDEX ASGSEDIFICIO1;
DROP INDEX ASGSEDIFICIO2;

-- Tabla: ASGSSALA
DROP INDEX ASGSSALA1;
DROP INDEX ASGSSALA2;
DROP INDEX ASGSSALA3;

-- Tabla: ASGSMESA
DROP INDEX ASGSMESA1;
DROP INDEX ASGSMESA2;
DROP INDEX ASGSMESA3;
DROP INDEX ASGSMESA4;

-- Tabla: ASGSUSRCSALA
DROP INDEX ASGSUSRCSALA1;
DROP INDEX ASGSUSRCSALA2;
DROP INDEX ASGSUSRCSALA3;

-- Tabla: ASGSUSRCSARCH
DROP INDEX ASGSUSRCSARCH1;
DROP INDEX ASGSUSRCSARCH2;

-- Tabla: ASGSREGCSALA
DROP INDEX ASGSREGCSALA1;
DROP INDEX ASGSREGCSALA2;
DROP INDEX ASGSREGCSALA3;

-- Tabla: ASGTUIREEACR
DROP INDEX ASGTUIREEACR1;
DROP INDEX ASGTUIREEACR2;

-- Tabla: ASGTUDOCENUIREEACR
DROP INDEX ASGTUDENUIREEACR1;
DROP INDEX ASGTUDENUIREEACR2;
DROP INDEX ASGTUDENUIREEACR3;
DROP INDEX ASGTUDENUIREEACR4;
DROP INDEX ASGTUDENUIREEACR5;
DROP INDEX ASGTUDENUIREEACR6;

-- Tabla: ASGTUDOCREEACR
DROP INDEX ASGTUDOCREEACR1;
DROP INDEX ASGTUDOCREEACR2;
DROP INDEX ASGTUDOCREEACR3;

-- Tabla: ASGFCTLGTBLTMP
DROP INDEX ASGFCTLGTBLTMP1;
DROP INDEX ASGFCTLGTBLTMP2;
