/**
 * ServicioRegistroWebService.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package ieci.tecdoc.sgm.registropresencial.ws.server;

public interface ServicioRegistroWebService extends java.rmi.Remote {
    public ieci.tecdoc.sgm.registropresencial.ws.server.DistributionInfo getDistribution(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.DistributionInfo distributionInfo, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.registropresencial.ws.server.RegisterInfo createFolder(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.PersonInfo[] inter, ieci.tecdoc.sgm.registropresencial.ws.server.Folder folder, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.registropresencial.ws.server.RegisterInfo updateFolder(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.PersonInfo[] inter, ieci.tecdoc.sgm.registropresencial.ws.server.Folder folder, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.registropresencial.ws.server.RegisterInfo importFolder(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.PersonInfo[] inter, ieci.tecdoc.sgm.registropresencial.ws.server.Folder folder, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.registropresencial.ws.server.RegisterInfo consolidateFolder(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.PersonInfo[] inter, ieci.tecdoc.sgm.registropresencial.ws.server.Folder folder, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.registropresencial.ws.server.RegistersInfo findFolder(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.FolderSearchCriteria folderQuery, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.registropresencial.ws.server.Folder getInputFolderForNumber(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.Folder folder, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.registropresencial.ws.server.FolderWithPersonInfo getInputRegister(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.Folder folder, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.registropresencial.ws.server.Folder getOutputFolderForNumber(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.Folder folder, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.registropresencial.ws.server.FolderWithPersonInfo getOutputRegister(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.Folder folder, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.registropresencial.ws.server.Document getDocumentFolder(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.Document document, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.registropresencial.ws.server.DistributionsInfo getInputDistribution(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.DistributionSearchCriteria criteria, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.registropresencial.ws.server.DistributionsInfo getOutputDistribution(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.DistributionSearchCriteria criteria, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.registropresencial.ws.server.DistributionCountInfo countInputDistribution(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.DistributionSearchCriteria criteria, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.registropresencial.ws.server.DistributionCountInfo countOutputDistribution(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.DistributionSearchCriteria criteria, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.core.services.dto.RetornoServicio acceptDistribution(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.Folder folder, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.core.services.dto.RetornoServicio acceptDistributionEx(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.DistributionInfo distributionInfo, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.core.services.dto.RetornoServicio archiveDistribution(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.Folder folder, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.core.services.dto.RetornoServicio archiveDistributionEx(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.DistributionInfo distributionInfo, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.core.services.dto.RetornoServicio rejectDistribution(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.Folder folder, ieci.tecdoc.sgm.registropresencial.ws.server.DistributionOptions options, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.core.services.dto.RetornoServicio rejectDistributionEx(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.DistributionInfo distributionInfo, ieci.tecdoc.sgm.registropresencial.ws.server.DistributionOptions options, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.core.services.dto.RetornoServicio changeInputDistribution(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.Folder folder, ieci.tecdoc.sgm.registropresencial.ws.server.DistributionOptions options, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.core.services.dto.RetornoServicio changeOutputDistribution(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.Folder folder, ieci.tecdoc.sgm.registropresencial.ws.server.DistributionOptions options, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.registropresencial.ws.server.RetornoServicio addDocument(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.Folder folder, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.registropresencial.ws.server.ListaPersonInfo getInterestedInputRegister(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.Folder folder, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.registropresencial.ws.server.ListaPersonInfo getInterestedOutputRegister(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.Folder folder, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.registropresencial.ws.server.RetornoServicio canCreateRegister(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.SearchCriteria criteria, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.registropresencial.ws.server.BooksInfo getBooksForType(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.SearchCriteria criteria, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.registropresencial.ws.server.OfficesInfo getOfficeCanCreateRegisterByUser(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, ieci.tecdoc.sgm.registropresencial.ws.server.Folder folder, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
    public ieci.tecdoc.sgm.registropresencial.ws.server.RetornoServicio existMatterTypeInOffice(ieci.tecdoc.sgm.registropresencial.ws.server.UserInfo user, java.lang.String matterTypeCode, java.lang.String officeCode, ieci.tecdoc.sgm.core.services.dto.Entidad entidad) throws java.rmi.RemoteException;
}
