--  Crear tablas para el conector de organización

CREATE TABLE AOESTRORG(
	ID               VARCHAR(32) NOT NULL,
	CODIGO           VARCHAR(64) NOT NULL,
	NOMBRE           VARCHAR(254) NOT NULL,
	TIPO             INTEGER NOT NULL,
	NIVEL            INTEGER NOT NULL,
	IDORGPADRE       VARCHAR(32),
	ESTADO           INTEGER NOT NULL,
	FINICIOVIGENCIA  TIMESTAMP,
	FFINVIGENCIA     TIMESTAMP,
	DESCRIPCION      VARCHAR(254)
);

CREATE TABLE AOUSR(
	ID             VARCHAR(64) NOT NULL,
	DIRECCION      VARCHAR(254),
	EMAIL          VARCHAR(254),
	NOMBRE         VARCHAR(64),
	APELLIDOS      VARCHAR(128),
	NOMBREUSUARIO  VARCHAR(64) NOT NULL,
	PASSWORD       VARCHAR(64) NOT NULL
);

CREATE TABLE AOUSRORGV(
	IDUSUARIO      VARCHAR(64) NOT NULL,
	NOMBREUSUARIO  VARCHAR(254) NOT NULL,
	IDORGANO       VARCHAR(32) NOT NULL
);

CREATE UNIQUE INDEX ORGANIZACION1 ON AOESTRORG (ID);
CREATE UNIQUE INDEX ORGANIZACION2 ON AOESTRORG (CODIGO);

CREATE INDEX USUARIO1 ON AOUSR (NOMBRE);
CREATE UNIQUE INDEX USUARIO2 ON AOUSR (NOMBREUSUARIO);

CREATE UNIQUE INDEX USRORGANO1 ON AOUSRORGV (IDUSUARIO);

-- Si las tablas se meten en un schema distinto del de archivo habría que ejecutar las siguientes sentencias:

-- CREATE TABLE ITDGUIDGEN(
-- 	cnode  VARCHAR(12),
--	clpid  INTEGER
-- );

-- INSERT INTO ITDGUIDGEN (CNODE, CLPID) VALUES ('000000000000', 1);

--INSTITUCIONES
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('IARCHIDOC','IARCHIDOC','ARCHIDOC',1,0,NULL,2,CURRENT TIMESTAMP,NULL,NULL);
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('INST1','INST1','Institución 1',1,0,NULL,2,CURRENT TIMESTAMP,NULL,'Institución 1');
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('INST2','INST2','Institución 2',1,0,NULL,2,CURRENT TIMESTAMP,NULL,'Institución 2');
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('INST3','INST3','Institución 3',1,0,NULL,2,CURRENT TIMESTAMP,NULL,'Institución 3');
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('INST4','INST4','Institución 4',1,0,NULL,2,CURRENT TIMESTAMP,NULL,'Institución 4');
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('INST5','INST5','Institución 5',1,0,NULL,2,CURRENT TIMESTAMP,NULL,'Institución 5');
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('INST6','INST6','Institución 6',1,0,NULL,2,CURRENT TIMESTAMP,NULL,'Institución 6');
-- 6 INSTITUCIONES

--ORGANOS
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('ORG1','ORG1','Órgano 1',2,1,'INST1',2,CURRENT TIMESTAMP,NULL,'Órgano 1');
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('ORG2','ORG2','Órgano 2',2,1,'INST2',2,CURRENT TIMESTAMP,NULL,'Órgano 2');
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('ORG3','ORG3','Órgano 3',2,1,'INST3',2,CURRENT TIMESTAMP,NULL,'Órgano 3');
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('ORG4','ORG4','Órgano 4',2,1,'INST4',2,CURRENT TIMESTAMP,NULL,'Órgano 4');
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('ORG5','ORG5','Órgano 5',2,1,'INST5',2,CURRENT TIMESTAMP,NULL,'Órgano 5');
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('ORG6','ORG6','Órgano 6',2,1,'INST6',2,CURRENT TIMESTAMP,NULL,'Órgano 6');
-- 6 ÓRGANOS

--USUARIOS
INSERT INTO AOUSRORGV (IDUSUARIO,NOMBREUSUARIO,IDORGANO) VALUES ('USR1','Administrador de Series','ORG1');
INSERT INTO AOUSRORGV (IDUSUARIO,NOMBREUSUARIO,IDORGANO) VALUES ('USR2','Administrador de Fondos','ORG2');
INSERT INTO AOUSRORGV (IDUSUARIO,NOMBREUSUARIO,IDORGANO) VALUES ('USR3','Administrador de Préstamos','ORG3');
INSERT INTO AOUSRORGV (IDUSUARIO,NOMBREUSUARIO,IDORGANO) VALUES ('USR4','Administrador de Depósito','ORG4');
INSERT INTO AOUSRORGV (IDUSUARIO,NOMBREUSUARIO,IDORGANO) VALUES ('USR5','Administrador de Archivo','ORG5');
INSERT INTO AOUSRORGV (IDUSUARIO,NOMBREUSUARIO,IDORGANO) VALUES ('USR6','Administrador de Oficina','ORG6');
--INSERT INTO AOUSRORGV (IDUSUARIO,NOMBREUSUARIO,IDORGANO) VALUES ('USR7','nacho','ORG1');
--INSERT INTO AOUSRORGV (IDUSUARIO,NOMBREUSUARIO,IDORGANO) VALUES ('USR8','lucas','ORG2');
--INSERT INTO AOUSRORGV (IDUSUARIO,NOMBREUSUARIO,IDORGANO) VALUES ('USR9','david','ORG3');
--INSERT INTO AOUSRORGV (IDUSUARIO,NOMBREUSUARIO,IDORGANO) VALUES ('USR10','laura','ORG4');
--INSERT INTO AOUSRORGV (IDUSUARIO,NOMBREUSUARIO,IDORGANO) VALUES ('USR11','omar','ORG5');
--INSERT INTO AOUSRORGV (IDUSUARIO,NOMBREUSUARIO,IDORGANO) VALUES ('USR12','alicia','ORG6');