package ieci.tecdoc.sgm.admsistema.temporal;

import java.util.ArrayList;
import java.util.List;

public class GestorLocalidades {
	
	public static List obtenerLocalidades (String idProvincia) {
		List localidades = new ArrayList();
		localidades.add(new Municipio(idProvincia, "", ""));
		
		if (idProvincia.equals("01")) {
			localidades.add(new Municipio("01", "0014", "Alegría-Dulantzi"));
			localidades.add(new Municipio("01", "0029", "Amurrio"));
			localidades.add(new Municipio("01", "0493", "Añana"));
			localidades.add(new Municipio("01", "0035", "Aramaio"));
			localidades.add(new Municipio("01", "0066", "Armiñón"));
			localidades.add(new Municipio("01", "0376", "Arraia-Maeztu"));
			localidades.add(new Municipio("01", "0088", "Arrazua-Ubarrundia"));
			localidades.add(new Municipio("01", "0040", "Artziniega"));
			localidades.add(new Municipio("01", "0091", "Asparrena"));
			localidades.add(new Municipio("01", "0105", "Ayala/Aiara"));
			localidades.add(new Municipio("01", "0112", "Baños de Ebro/Mañueta"));
			localidades.add(new Municipio("01", "0133", "Barrundia"));
			localidades.add(new Municipio("01", "0148", "Berantevilla"));
			localidades.add(new Municipio("01", "0164", "Bernedo"));
			localidades.add(new Municipio("01", "0170", "Campezo/Kanpezu"));
			localidades.add(new Municipio("01", "0210", "Elburgo/Burgelu"));
			localidades.add(new Municipio("01", "0225", "Elciego"));
			localidades.add(new Municipio("01", "0231", "Elvillar/Bilar"));
			localidades.add(new Municipio("01", "0565", "Harana/Valle de Arana"));
			localidades.add(new Municipio("01", "9015", "Iruña Oka/Iruña de Oca"));
			localidades.add(new Municipio("01", "0278", "Iruraiz-Gauna"));
			localidades.add(new Municipio("01", "0199", "Kripan"));
			localidades.add(new Municipio("01", "0203", "Kuartango"));
			localidades.add(new Municipio("01", "0284", "Labastida/Bastida"));
			localidades.add(new Municipio("01", "0301", "Lagrán"));
			localidades.add(new Municipio("01", "0318", "Laguardia"));
			localidades.add(new Municipio("01", "0323", "Lanciego/Lantziego"));
			localidades.add(new Municipio("01", "9020", "Lantarón"));
			localidades.add(new Municipio("01", "0339", "Lapuebla de Labarca"));
			localidades.add(new Municipio("01", "0360", "Laudio/Llodio"));
			localidades.add(new Municipio("01", "0587", "Legutiano"));
			localidades.add(new Municipio("01", "0344", "Leza"));
			localidades.add(new Municipio("01", "0395", "Moreda de Álava"));
			localidades.add(new Municipio("01", "0416", "Navaridas"));
			localidades.add(new Municipio("01", "0421", "Okondo"));
			localidades.add(new Municipio("01", "0437", "Oyón-Oion"));
			localidades.add(new Municipio("01", "0442", "Peñacerrada-Urizaharra"));
			localidades.add(new Municipio("01", "0468", "Ribera Alta"));
			localidades.add(new Municipio("01", "0474", "Ribera Baja/Erribera Beitia"));
			localidades.add(new Municipio("01", "0513", "Salvatierra/Agurain"));
			localidades.add(new Municipio("01", "0528", "Samaniego"));
			localidades.add(new Municipio("01", "0534", "San Millán/Donemiliaga"));
			localidades.add(new Municipio("01", "0549", "Urkabustaiz"));
			localidades.add(new Municipio("01", "0552", "Valdegovía/Gaubea"));
			localidades.add(new Municipio("01", "0571", "Villabuena de Álava/Eskuernaga"));
			localidades.add(new Municipio("01", "0590", "Vitoria-Gasteiz"));
			localidades.add(new Municipio("01", "0604", "Yécora/Iekora"));
			localidades.add(new Municipio("01", "0611", "Zalduondo"));
			localidades.add(new Municipio("01", "0626", "Zambrana"));
			localidades.add(new Municipio("01", "0186", "Zigoitia"));
			localidades.add(new Municipio("01", "0632", "Zuia"));
		} else if (idProvincia.equals("02")) {
			localidades.add(new Municipio("02", "0019", "Abengibre"));
			localidades.add(new Municipio("02", "0024", "Alatoz"));
			localidades.add(new Municipio("02", "0030", "Albacete"));
			localidades.add(new Municipio("02", "0045", "Albatana"));
			localidades.add(new Municipio("02", "0058", "Alborea"));
			localidades.add(new Municipio("02", "0061", "Alcadozo"));
			localidades.add(new Municipio("02", "0077", "Alcalá del Júcar"));
			localidades.add(new Municipio("02", "0083", "Alcaraz"));
			localidades.add(new Municipio("02", "0096", "Almansa"));
			localidades.add(new Municipio("02", "0100", "Alpera"));
			localidades.add(new Municipio("02", "0117", "Ayna"));
			localidades.add(new Municipio("02", "0122", "Balazote"));
			localidades.add(new Municipio("02", "0143", "Ballestero (El)"));
			localidades.add(new Municipio("02", "0138", "Balsa de Ves"));
			localidades.add(new Municipio("02", "0156", "Barrax"));
			localidades.add(new Municipio("02", "0169", "Bienservida"));
			localidades.add(new Municipio("02", "0175", "Bogarra"));
			localidades.add(new Municipio("02", "0181", "Bonete"));
			localidades.add(new Municipio("02", "0194", "Bonillo (El)"));
			localidades.add(new Municipio("02", "0208", "Carcelén"));
			localidades.add(new Municipio("02", "0215", "Casas de Juan Núñez"));
			localidades.add(new Municipio("02", "0220", "Casas de Lázaro"));
			localidades.add(new Municipio("02", "0236", "Casas de Ves"));
			localidades.add(new Municipio("02", "0241", "Casas-Ibáñez"));
			localidades.add(new Municipio("02", "0254", "Caudete"));
			localidades.add(new Municipio("02", "0267", "Cenizate"));
			localidades.add(new Municipio("02", "0292", "Chinchilla de Monte-Aragón"));
			localidades.add(new Municipio("02", "0273", "Corral-Rubio"));
			localidades.add(new Municipio("02", "0289", "Cotillas"));
			localidades.add(new Municipio("02", "0306", "Elche de la Sierra"));
			localidades.add(new Municipio("02", "0313", "Férez"));
			localidades.add(new Municipio("02", "0328", "Fuensanta"));
			localidades.add(new Municipio("02", "0334", "Fuente-Álamo"));
			localidades.add(new Municipio("02", "0349", "Fuentealbilla"));
			localidades.add(new Municipio("02", "0352", "Gineta (La)"));
			localidades.add(new Municipio("02", "0365", "Golosalvo"));
			localidades.add(new Municipio("02", "0371", "Hellín"));
			localidades.add(new Municipio("02", "0387", "Herrera (La)"));
			localidades.add(new Municipio("02", "0390", "Higueruela"));
			localidades.add(new Municipio("02", "0404", "Hoya-Gonzalo"));
			localidades.add(new Municipio("02", "0411", "Jorquera"));
			localidades.add(new Municipio("02", "0426", "Letur"));
			localidades.add(new Municipio("02", "0432", "Lezuza"));
			localidades.add(new Municipio("02", "0447", "Liétor"));
			localidades.add(new Municipio("02", "0450", "Madrigueras"));
			localidades.add(new Municipio("02", "0463", "Mahora"));
			localidades.add(new Municipio("02", "0479", "Masegoso"));
			localidades.add(new Municipio("02", "0485", "Minaya"));
			localidades.add(new Municipio("02", "0498", "Molinicos"));
			localidades.add(new Municipio("02", "0501", "Montalvos"));
			localidades.add(new Municipio("02", "0518", "Montealegre del Castillo"));
			localidades.add(new Municipio("02", "0523", "Motilleja"));
			localidades.add(new Municipio("02", "0539", "Munera"));
			localidades.add(new Municipio("02", "0544", "Navas de Jorquera"));
			localidades.add(new Municipio("02", "0557", "Nerpio"));
			localidades.add(new Municipio("02", "0560", "Ontur"));
			localidades.add(new Municipio("02", "0576", "Ossa de Montiel"));
			localidades.add(new Municipio("02", "0582", "Paterna del Madera"));
			localidades.add(new Municipio("02", "0609", "Peñas de San Pedro"));
			localidades.add(new Municipio("02", "0595", "Peñascosa"));
			localidades.add(new Municipio("02", "0616", "Pétrola"));
			localidades.add(new Municipio("02", "0621", "Povedilla"));
			localidades.add(new Municipio("02", "9010", "Pozo Cañada"));
			localidades.add(new Municipio("02", "0637", "Pozohondo"));
			localidades.add(new Municipio("02", "0642", "Pozo-Lorente"));
			localidades.add(new Municipio("02", "0655", "Pozuelo"));
			localidades.add(new Municipio("02", "0668", "Recueja (La)"));
			localidades.add(new Municipio("02", "0674", "Riópar"));
			localidades.add(new Municipio("02", "0680", "Robledo"));
			localidades.add(new Municipio("02", "0693", "Roda (La)"));
			localidades.add(new Municipio("02", "0707", "Salobre"));
			localidades.add(new Municipio("02", "0714", "San Pedro"));
			localidades.add(new Municipio("02", "0729", "Socovos"));
			localidades.add(new Municipio("02", "0735", "Tarazona de la Mancha"));
			localidades.add(new Municipio("02", "0740", "Tobarra"));
			localidades.add(new Municipio("02", "0753", "Valdeganga"));
			localidades.add(new Municipio("02", "0766", "Vianos"));
			localidades.add(new Municipio("02", "0772", "Villa de Ves"));
			localidades.add(new Municipio("02", "0788", "Villalgordo del Júcar"));
			localidades.add(new Municipio("02", "0791", "Villamalea"));
			localidades.add(new Municipio("02", "0805", "Villapalacios"));
			localidades.add(new Municipio("02", "0812", "Villarrobledo"));
			localidades.add(new Municipio("02", "0827", "Villatoya"));
			localidades.add(new Municipio("02", "0833", "Villavaliente"));
			localidades.add(new Municipio("02", "0848", "Villaverde de Guadalimar"));
			localidades.add(new Municipio("02", "0851", "Viveros"));
			localidades.add(new Municipio("02", "0864", "Yeste"));
		} else if (idProvincia.equals("03")) {
			localidades.add(new Municipio("03", "0015", "Adsubia"));
			localidades.add(new Municipio("03", "0020", "Agost"));
			localidades.add(new Municipio("03", "0036", "Agres"));
			localidades.add(new Municipio("03", "0041", "Aigües"));
			localidades.add(new Municipio("03", "0054", "Albatera"));
			localidades.add(new Municipio("03", "0067", "Alcalalí"));
			localidades.add(new Municipio("03", "0073", "Alcocer de Planes"));
			localidades.add(new Municipio("03", "0089", "Alcoleja"));
			localidades.add(new Municipio("03", "0092", "Alcoy/Alcoi"));
			localidades.add(new Municipio("03", "0106", "Alfafara"));
			localidades.add(new Municipio("03", "0113", "Alfàs del Pi (l')"));
			localidades.add(new Municipio("03", "0128", "Algorfa"));
			localidades.add(new Municipio("03", "0134", "Algueña"));
			localidades.add(new Municipio("03", "0149", "Alicante/Alacant"));
			localidades.add(new Municipio("03", "0152", "Almoradí"));
			localidades.add(new Municipio("03", "0165", "Almudaina"));
			localidades.add(new Municipio("03", "0171", "Alqueria d'Asnar (l')"));
			localidades.add(new Municipio("03", "0187", "Altea"));
			localidades.add(new Municipio("03", "0190", "Aspe"));
			localidades.add(new Municipio("03", "0204", "Balones"));
			localidades.add(new Municipio("03", "0211", "Banyeres de Mariola"));
			localidades.add(new Municipio("03", "0226", "Benasau"));
			localidades.add(new Municipio("03", "0232", "Beneixama"));
			localidades.add(new Municipio("03", "0247", "Benejúzar"));
			localidades.add(new Municipio("03", "0250", "Benferri"));
			localidades.add(new Municipio("03", "0263", "Beniarbeig"));
			localidades.add(new Municipio("03", "0279", "Beniardá"));
			localidades.add(new Municipio("03", "0285", "Beniarrés"));
			localidades.add(new Municipio("03", "0302", "Benidoleig"));
			localidades.add(new Municipio("03", "0319", "Benidorm"));
			localidades.add(new Municipio("03", "0324", "Benifallim"));
			localidades.add(new Municipio("03", "0330", "Benifato"));
			localidades.add(new Municipio("03", "0298", "Benigembla"));
			localidades.add(new Municipio("03", "0345", "Benijófar"));
			localidades.add(new Municipio("03", "0358", "Benilloba"));
			localidades.add(new Municipio("03", "0361", "Benillup"));
			localidades.add(new Municipio("03", "0377", "Benimantell"));
			localidades.add(new Municipio("03", "0383", "Benimarfull"));
			localidades.add(new Municipio("03", "0396", "Benimassot"));
			localidades.add(new Municipio("03", "0400", "Benimeli"));
			localidades.add(new Municipio("03", "0417", "Benissa"));
			localidades.add(new Municipio("03", "0422", "Benitachell/Poble Nou de Benitatxell (el)"));
			localidades.add(new Municipio("03", "0438", "Biar"));
			localidades.add(new Municipio("03", "0443", "Bigastro"));
			localidades.add(new Municipio("03", "0456", "Bolulla"));
			localidades.add(new Municipio("03", "0469", "Busot"));
			localidades.add(new Municipio("03", "0494", "Callosa de Segura"));
			localidades.add(new Municipio("03", "0481", "Callosa d'En Sarrià"));
			localidades.add(new Municipio("03", "0475", "Calpe/Calp"));
			localidades.add(new Municipio("03", "0507", "Campello (el)"));
			localidades.add(new Municipio("03", "0514", "Campo de Mirra/Camp de Mirra (el)"));
			localidades.add(new Municipio("03", "0529", "Cañada"));
			localidades.add(new Municipio("03", "0535", "Castalla"));
			localidades.add(new Municipio("03", "0540", "Castell de Castells"));
			localidades.add(new Municipio("03", "0759", "Castell de Guadalest (el)"));
			localidades.add(new Municipio("03", "0553", "Catral"));
			localidades.add(new Municipio("03", "0566", "Cocentaina"));
			localidades.add(new Municipio("03", "0572", "Confrides"));
			localidades.add(new Municipio("03", "0588", "Cox"));
			localidades.add(new Municipio("03", "0591", "Crevillent"));
			localidades.add(new Municipio("03", "0612", "Daya Nueva"));
			localidades.add(new Municipio("03", "0627", "Daya Vieja"));
			localidades.add(new Municipio("03", "0633", "Dénia"));
			localidades.add(new Municipio("03", "0648", "Dolores"));
			localidades.add(new Municipio("03", "0651", "Elche/Elx"));
			localidades.add(new Municipio("03", "0664", "Elda"));
			localidades.add(new Municipio("03", "0670", "Facheca"));
			localidades.add(new Municipio("03", "0686", "Famorca"));
			localidades.add(new Municipio("03", "0699", "Finestrat"));
			localidades.add(new Municipio("03", "0778", "Fondó de les Neus (el)/Hondón de las Nieves"));
			localidades.add(new Municipio("03", "0703", "Formentera del Segura"));
			localidades.add(new Municipio("03", "0725", "Gaianes"));
			localidades.add(new Municipio("03", "0710", "Gata de Gorgos"));
			localidades.add(new Municipio("03", "0731", "Gorga"));
			localidades.add(new Municipio("03", "0746", "Granja de Rocamora"));
			localidades.add(new Municipio("03", "0762", "Guardamar del Segura"));
			localidades.add(new Municipio("03", "0784", "Hondón de los Frailes"));
			localidades.add(new Municipio("03", "0797", "Ibi"));
			localidades.add(new Municipio("03", "0801", "Jacarilla"));
			localidades.add(new Municipio("03", "0823", "Jávea/Xàbia"));
			localidades.add(new Municipio("03", "0839", "Jijona/Xixona"));
			localidades.add(new Municipio("03", "0857", "Llíber"));
			localidades.add(new Municipio("03", "0844", "Lorcha/Orxa (l')"));
			localidades.add(new Municipio("03", "0860", "Millena"));
			localidades.add(new Municipio("03", "0882", "Monforte del Cid"));
			localidades.add(new Municipio("03", "0895", "Monóvar/Monòver"));
			localidades.add(new Municipio("03", "9037", "Montesinos (Los)"));
			localidades.add(new Municipio("03", "0916", "Murla"));
			localidades.add(new Municipio("03", "0921", "Muro de Alcoy"));
			localidades.add(new Municipio("03", "0909", "Mutxamel"));
			localidades.add(new Municipio("03", "0937", "Novelda"));
			localidades.add(new Municipio("03", "0942", "Nucia (la)"));
			localidades.add(new Municipio("03", "0955", "Ondara"));
			localidades.add(new Municipio("03", "0968", "Onil"));
			localidades.add(new Municipio("03", "0974", "Orba"));
			localidades.add(new Municipio("03", "0993", "Orihuela"));
			localidades.add(new Municipio("03", "0980", "Orxeta"));
			localidades.add(new Municipio("03", "1007", "Parcent"));
			localidades.add(new Municipio("03", "1014", "Pedreguer"));
			localidades.add(new Municipio("03", "1029", "Pego"));
			localidades.add(new Municipio("03", "1035", "Penàguila"));
			localidades.add(new Municipio("03", "1040", "Petrer"));
			localidades.add(new Municipio("03", "9021", "Pilar de la Horadada"));
			localidades.add(new Municipio("03", "1053", "Pinós (el)/Pinoso"));
			localidades.add(new Municipio("03", "1066", "Planes"));
			localidades.add(new Municipio("03", "9016", "Poblets (els)"));
			localidades.add(new Municipio("03", "1072", "Polop"));
			localidades.add(new Municipio("03", "0605", "Quatretondeta"));
			localidades.add(new Municipio("03", "1091", "Rafal"));
			localidades.add(new Municipio("03", "1105", "Ràfol d'Almúnia (El)"));
			localidades.add(new Municipio("03", "1112", "Redován"));
			localidades.add(new Municipio("03", "1127", "Relleu"));
			localidades.add(new Municipio("03", "1133", "Rojales"));
			localidades.add(new Municipio("03", "1148", "Romana (la)"));
			localidades.add(new Municipio("03", "1151", "Sagra"));
			localidades.add(new Municipio("03", "1164", "Salinas"));
			localidades.add(new Municipio("03", "1186", "San Fulgencio"));
			localidades.add(new Municipio("03", "9042", "San Isidro"));
			localidades.add(new Municipio("03", "1203", "San Miguel de Salinas"));
			localidades.add(new Municipio("03", "1225", "San Vicente del Raspeig/Sant Vicent del Raspeig"));
			localidades.add(new Municipio("03", "1170", "Sanet y Negrals"));
			localidades.add(new Municipio("03", "1199", "Sant Joan d'Alacant"));
			localidades.add(new Municipio("03", "1210", "Santa Pola"));
			localidades.add(new Municipio("03", "1231", "Sax"));
			localidades.add(new Municipio("03", "1246", "Sella"));
			localidades.add(new Municipio("03", "1259", "Senija"));
			localidades.add(new Municipio("03", "1278", "Tàrbena"));
			localidades.add(new Municipio("03", "1284", "Teulada"));
			localidades.add(new Municipio("03", "1297", "Tibi"));
			localidades.add(new Municipio("03", "1301", "Tollos"));
			localidades.add(new Municipio("03", "1318", "Tormos"));
			localidades.add(new Municipio("03", "1323", "Torremanzanas/Torre de les Maçanes (la)"));
			localidades.add(new Municipio("03", "1339", "Torrevieja"));
			localidades.add(new Municipio("03", "1344", "Vall d'Alcalà (la)"));
			localidades.add(new Municipio("03", "1360", "Vall de Gallinera"));
			localidades.add(new Municipio("03", "1376", "Vall de Laguar (la)"));
			localidades.add(new Municipio("03", "1357", "Vall d'Ebo (la)"));
			localidades.add(new Municipio("03", "1382", "Verger (el)"));
			localidades.add(new Municipio("03", "1395", "Villajoyosa/Vila Joiosa (la)"));
			localidades.add(new Municipio("03", "1409", "Villena"));
			localidades.add(new Municipio("03", "0818", "Xaló"));
		} else if (idProvincia.equals("04")) {
			localidades.add(new Municipio("04", "0010", "Abla"));
			localidades.add(new Municipio("04", "0025", "Abrucena"));
			localidades.add(new Municipio("04", "0031", "Adra"));
			localidades.add(new Municipio("04", "0046", "Albánchez"));
			localidades.add(new Municipio("04", "0059", "Alboloduy"));
			localidades.add(new Municipio("04", "0062", "Albox"));
			localidades.add(new Municipio("04", "0078", "Alcolea"));
			localidades.add(new Municipio("04", "0084", "Alcóntar"));
			localidades.add(new Municipio("04", "0097", "Alcudia de Monteagud"));
			localidades.add(new Municipio("04", "0101", "Alhabia"));
			localidades.add(new Municipio("04", "0118", "Alhama de Almería"));
			localidades.add(new Municipio("04", "0123", "Alicún"));
			localidades.add(new Municipio("04", "0139", "Almería"));
			localidades.add(new Municipio("04", "0144", "Almócita"));
			localidades.add(new Municipio("04", "0157", "Alsodux"));
			localidades.add(new Municipio("04", "0160", "Antas"));
			localidades.add(new Municipio("04", "0176", "Arboleas"));
			localidades.add(new Municipio("04", "0182", "Armuña de Almanzora"));
			localidades.add(new Municipio("04", "0195", "Bacares"));
			localidades.add(new Municipio("04", "0209", "Bayárcal"));
			localidades.add(new Municipio("04", "0216", "Bayarque"));
			localidades.add(new Municipio("04", "0221", "Bédar"));
			localidades.add(new Municipio("04", "0237", "Beires"));
			localidades.add(new Municipio("04", "0242", "Benahadux"));
			localidades.add(new Municipio("04", "0268", "Benitagla"));
			localidades.add(new Municipio("04", "0274", "Benizalón"));
			localidades.add(new Municipio("04", "0280", "Bentarique"));
			localidades.add(new Municipio("04", "0293", "Berja"));
			localidades.add(new Municipio("04", "0307", "Canjáyar"));
			localidades.add(new Municipio("04", "0314", "Cantoria"));
			localidades.add(new Municipio("04", "0329", "Carboneras"));
			localidades.add(new Municipio("04", "0335", "Castro de Filabres"));
			localidades.add(new Municipio("04", "0366", "Chercos"));
			localidades.add(new Municipio("04", "0372", "Chirivel"));
			localidades.add(new Municipio("04", "0340", "Cóbdar"));
			localidades.add(new Municipio("04", "0353", "Cuevas del Almanzora"));
			localidades.add(new Municipio("04", "0388", "Dalías"));
			localidades.add(new Municipio("04", "9026", "Ejido (El)"));
			localidades.add(new Municipio("04", "0412", "Enix"));
			localidades.add(new Municipio("04", "0433", "Felix"));
			localidades.add(new Municipio("04", "0448", "Fines"));
			localidades.add(new Municipio("04", "0451", "Fiñana"));
			localidades.add(new Municipio("04", "0464", "Fondón"));
			localidades.add(new Municipio("04", "0470", "Gádor"));
			localidades.add(new Municipio("04", "0486", "Gallardos (Los)"));
			localidades.add(new Municipio("04", "0499", "Garrucha"));
			localidades.add(new Municipio("04", "0502", "Gérgal"));
			localidades.add(new Municipio("04", "0519", "Huécija"));
			localidades.add(new Municipio("04", "0524", "Huércal de Almería"));
			localidades.add(new Municipio("04", "0530", "Huércal-Overa"));
			localidades.add(new Municipio("04", "0545", "Illar"));
			localidades.add(new Municipio("04", "0558", "Instinción"));
			localidades.add(new Municipio("04", "0561", "Laroya"));
			localidades.add(new Municipio("04", "0577", "Láujar de Andarax"));
			localidades.add(new Municipio("04", "0583", "Líjar"));
			localidades.add(new Municipio("04", "0596", "Lubrín"));
			localidades.add(new Municipio("04", "0600", "Lucainena de las Torres"));
			localidades.add(new Municipio("04", "0617", "Lúcar"));
			localidades.add(new Municipio("04", "0622", "Macael"));
			localidades.add(new Municipio("04", "0638", "María"));
			localidades.add(new Municipio("04", "0643", "Mojácar"));
			localidades.add(new Municipio("04", "9032", "Mojonera (La)"));
			localidades.add(new Municipio("04", "0656", "Nacimiento"));
			localidades.add(new Municipio("04", "0669", "Níjar"));
			localidades.add(new Municipio("04", "0675", "Ohanes"));
			localidades.add(new Municipio("04", "0681", "Olula de Castro"));
			localidades.add(new Municipio("04", "0694", "Olula del Río"));
			localidades.add(new Municipio("04", "0708", "Oria"));
			localidades.add(new Municipio("04", "0715", "Padules"));
			localidades.add(new Municipio("04", "0720", "Partaloa"));
			localidades.add(new Municipio("04", "0736", "Paterna del Río"));
			localidades.add(new Municipio("04", "0741", "Pechina"));
			localidades.add(new Municipio("04", "0754", "Pulpí"));
			localidades.add(new Municipio("04", "0767", "Purchena"));
			localidades.add(new Municipio("04", "0773", "Rágol"));
			localidades.add(new Municipio("04", "0789", "Rioja"));
			localidades.add(new Municipio("04", "0792", "Roquetas de Mar"));
			localidades.add(new Municipio("04", "0806", "Santa Cruz de Marchena"));
			localidades.add(new Municipio("04", "0813", "Santa Fe de Mondújar"));
			localidades.add(new Municipio("04", "0828", "Senés"));
			localidades.add(new Municipio("04", "0834", "Serón"));
			localidades.add(new Municipio("04", "0849", "Sierro"));
			localidades.add(new Municipio("04", "0849", "Sierro"));
			localidades.add(new Municipio("04", "0849", "Sierro"));
			localidades.add(new Municipio("04", "0852", "Somontín"));
			localidades.add(new Municipio("04", "0865", "Sorbas"));
			localidades.add(new Municipio("04", "0871", "Suflí"));
			localidades.add(new Municipio("04", "0887", "Tabernas"));
			localidades.add(new Municipio("04", "0890", "Taberno"));
			localidades.add(new Municipio("04", "0904", "Tahal"));
			localidades.add(new Municipio("04", "0911", "Terque"));
			localidades.add(new Municipio("04", "0926", "Tíjola"));
			localidades.add(new Municipio("04", "9011", "Tres Villas (Las)"));
			localidades.add(new Municipio("04", "0932", "Turre"));
			localidades.add(new Municipio("04", "0947", "Turrillas"));
			localidades.add(new Municipio("04", "0950", "Uleila del Campo"));
			localidades.add(new Municipio("04", "0963", "Urrácal"));
			localidades.add(new Municipio("04", "0979", "Velefique"));
			localidades.add(new Municipio("04", "0985", "Vélez-Blanco"));
			localidades.add(new Municipio("04", "0998", "Vélez-Rubio"));
			localidades.add(new Municipio("04", "1002", "Vera"));
			localidades.add(new Municipio("04", "1019", "Viator"));
			localidades.add(new Municipio("04", "1024", "Vícar"));
			localidades.add(new Municipio("04", "1030", "Zurgena"));
		}
		
		return localidades;
	}
	
	public static List obtenerProvincias () {
		List provincias = new ArrayList();;
		
		provincias.add(new Provincia("",""));
		provincias.add(new Provincia("01","Álava"));
		provincias.add(new Provincia("02","Albacete"));
		provincias.add(new Provincia("03","Alicante/Alacant"));
		provincias.add(new Provincia("04","Almería"));
		
		return provincias;
	}

}
