package com.ieci.tecdoc.common.entity.dao;

import java.text.SimpleDateFormat;

public class DBEntityDAOKeys {

	protected static String WHERE = "WHERE";
	protected static String BETWEEN = "BETWEEN";
	protected static String LIKE = "LIKE";
	protected static String IGUAL = "=";
	protected static String PUNTO_COMA = ";";
	protected static String PAR_IZQ = "(";
	protected static String PAR_DER = ")";
	public static String OR = "OR";
	public static String AND = "AND";
	protected static String ESPACIO = " ";
	protected static String INTERROGACION = "?";
	protected static String IS_NULL = "is null";

	protected static String FDRID_FIELD = "fdrid";
	protected static String OFFICEID_FIELD = "officeid";
	protected static String STATE_FIELD = "state";

	// protected static String AXSF_FINDALL_SENTENCE = "SELECT fdrid FROM {0}
	// {1} ORDER BY fld1";
	protected static String AXSF_FINDALL_SENTENCE = "SELECT fdrid FROM {0} {1}";

	protected static String AXSF_FINDALL_SIZE_SENTENCE = "SELECT count(*) FROM {0} {1}";

	protected static String AXSF_FIND_LASTFORUSER = "SELECT MAX(FDRID) AS FDRID FROM {0} {1}";

	protected static String UPDATE_NEXT_ID_3 = "UPDATE IDOCXNEXTID SET ID=ID+1 WHERE TYPE=3 AND PARENTID=?";

	protected static String UPDATE_LOCK_NEXT_ID_3 = "UPDATE IDOCXNEXTID SET ID=ID WHERE TYPE=3 AND PARENTID=?";

	protected static String INSERT_NEXT_ID_3 = "INSERT INTO IDOCXNEXTID(ID,TYPE,PARENTID) VALUES(1,3,?)";

	protected static String SELECT_NEXT_ID_3 = "SELECT ID FROM IDOCXNEXTID WHERE TYPE=3 AND PARENTID=?";

	protected static String UPDATE_NEXT_ID_5 = "UPDATE IDOCXNEXTID SET ID=ID+1 WHERE TYPE=5 AND PARENTID=?";

	protected static String UPDATE_LOCK_NEXT_ID_5 = "UPDATE IDOCXNEXTID SET ID=ID WHERE TYPE=5 AND PARENTID=?";

	protected static String INSERT_NEXT_ID_5 = "INSERT INTO IDOCXNEXTID(ID,TYPE,PARENTID) VALUES(1,5,?)";

	protected static String UPDATE_NEXT_ID_7 = "UPDATE IDOCXNEXTID SET ID=ID+1 WHERE TYPE=7 AND PARENTID=?";

	protected static String UPDATE_LOCK_NEXT_ID_7 = "UPDATE IDOCXNEXTID SET ID=ID WHERE TYPE=7 AND PARENTID=?";

	protected static String INSERT_NEXT_ID_7 = "INSERT INTO IDOCXNEXTID(ID,TYPE,PARENTID) VALUES(1,7,?)";

	protected static String SELECT_NEXT_ID_7 = "SELECT ID FROM IDOCXNEXTID WHERE TYPE=7 AND PARENTID=?";

	protected static String SELECT_NEXT_ID_5 = "SELECT ID FROM IDOCXNEXTID WHERE TYPE=5 AND PARENTID=?";

	protected static String UPDATE_SCR_CNTCENTRAL = "UPDATE SCR_CNTCENTRAL SET NUM_REG=NUM_REG+1 WHERE AN=? AND ID_ARCH=?";

	protected static String UPDATE_SCR_CNTOFICINA = "UPDATE SCR_CNTOFICINA SET NUM_REG=NUM_REG+1 WHERE AN=? AND ID_ARCH=? AND OFICINA=?";

	protected static String SELECT_NUMREG_SCR_CNTCENTRAL = "SELECT NUM_REG FROM SCR_CNTCENTRAL WHERE AN=? AND ID_ARCH=?";

	protected static String SELECT_NUMREG_SCR_CNTOFICINA = "SELECT NUM_REG FROM SCR_CNTOFICINA WHERE AN=? AND ID_ARCH=? AND OFICINA=?";

	protected static String DELETE_USER_CONFIG = "DELETE FROM SCR_USERCONFIG WHERE USERID=?";

	protected static String INSERT_USER_CONFIG = "INSERT INTO SCR_USERCONFIG(USERID,DATA) VALUES(?,?)";

	protected static String UPDATE_USER_CONFIG = "UPDATE SCR_USERCONFIG SET DATA=? WHERE USERID=?";

	protected static String LOCK_SCR_CNTCENTRAL = "UPDATE SCR_CNTCENTRAL SET NUM_REG=NUM_REG WHERE AN=?";

	protected static String LOCK_SCR_DISTREG = "UPDATE SCR_DISTREG SET ID=ID WHERE ID=?";

	protected static String LOCK_SCR_CNTOFICINA = "UPDATE SCR_CNTOFICINA SET NUM_REG=NUM_REG WHERE AN=?";

	protected static String SCR_LOCK_RELATIONS = "UPDATE SCR_LOCKRELATIONS SET TYPEBOOK=TYPEBOOK WHERE TYPEBOOK=? AND TYPEREL=? AND IDOFIC=?";

	protected static String INSERT_SCR_CNTCENTRAL = "INSERT INTO SCR_CNTCENTRAL(AN,NUM_REG,ID_ARCH) VALUES (?,1,?)";

	protected static String INSERT_SCR_CNTOFICINA_OFIC = "INSERT INTO SCR_CNTOFICINA(AN,OFICINA,NUM_REG,ID_ARCH) VALUES (?,?,1,?)";

	protected static String INSERT_SCR_RELATIONS = "INSERT INTO SCR_RELATIONS(TYPEBOOK,TYPEREL,RELYEAR,RELMONTH,RELDAY,IDOFIC,RELDATE,IDUNIT,NREL) VALUES (?,?,?,?,?,?,?,?,?)";

	protected static String SELECT_RELATIONS_NEW_NUMBER = "SELECT MAX(NREL)  FROM SCR_RELATIONS WHERE TYPEBOOK=? AND TYPEREL=? AND IDOFIC=? AND IDUNIT=? AND RELYEAR=?";
	// /////// TODO SCR_LASTCONNECTION /////////
	protected static String SELECT_USER_LASTCONNECTION = "SELECT CONNECT_DATE  FROM SCR_LASTCONNECTION WHERE IDUSER=?";
	protected static String DELETE_USER_LASTCONNECTION = "DELETE FROM SCR_LASTCONNECTION WHERE IDUSER=?";
	protected static String INSERT_USER_LASTCONNECTION = "INSERT INTO SCR_LASTCONNECTION (IDUSER, CONNECT_DATE) VALUES(?,?)";

	// /////// TODO SCR_LASTREGISTER /////////
	protected static String SELECT_USER_LASTREGISTER = "SELECT *  FROM SCR_LASTREGISTER WHERE BOOKID=? AND USERID=?";
	protected static String UPDATE_USER_LASTREGISTER = "UPDATE SCR_LASTREGISTER SET FDRID=? WHERE BOOKID=? AND USERID=?";
	protected static String INSERT_USER_LASTREGISTER = "INSERT INTO SCR_LASTREGISTER (BOOKID, FDRID, USERID) VALUES(?,?,?)";

	// ////// TODO SCR_DISTACCEPT
	protected static String SELECT_DIST_DISTACCEPT = "SELECT *  FROM SCR_DISTACCEPT WHERE BOOKID=? AND REGID=?";
	protected static String DELETE_DIST_DISTACCEPT = "DELETE FROM SCR_DISTACCEPT WHERE BOOKID=? AND REGID=?";
	protected static String UPDATE_DIST_DISTACCEPT = "UPDATE SCR_DISTACCEPT SET OFFICEID=?, STATE=?, ACCUSER=?, ACCDATE=? WHERE BOOKID=? AND REGID=?";
	protected static String INSERT_DIST_DISTACCEPT = "INSERT INTO SCR_DISTACCEPT (BOOKID, REGID, OFFICEID, DISTDATE, ACCDATE, ACCUSER, STATE) VALUES (?,?,?,?,?,?,?)";

	// /////// TODO SCR_PAGEINFO /////////
	protected static String SELECT_HASH_PAGE = "SELECT HASH  FROM SCR_PAGEINFO WHERE BOOKID=? AND REGID=? AND PAGEID=?";
	protected static String DELETE_HASH_PAGE = "DELETE FROM SCR_PAGEINFO WHERE BOOKID=? AND REGID=? AND PAGEID=?";
	protected static String UPDATE_HASH_PAGE = "UPDATE SCR_PAGEINFO SET HASH=? WHERE BOOKID=? AND REGID=? AND PAGEID=?";

	// /////// TODO SCR_PAGEREPOSITORY /////////
	protected static String SELECT_SCR_PAGEREPOSITORY = "SELECT DOCUID  FROM SCR_PAGEREPOSITORY WHERE BOOKID=? AND FDRID=? AND PAGEID=?";
	protected static String INSERT_SCR_PAGEREPOSITORY = "INSERT INTO SCR_PAGEREPOSITORY(BOOKID,FDRID,PAGEID,DOCUID) VALUES (?,?,?,?)";
	protected static String DELETE_SCR_PAGEREPOSITORY = "DELETE FROM SCR_PAGEREPOSITORY WHERE BOOKID=? and FDRID=? and PAGEID=?";


	protected static String INSERT_SCR_SHAREDFILES = "INSERT INTO SCR_SHAREDFILES (FILEID, OWNERBOOKID, OWNERREGID, BOOKID, REGID) VALUES(?,?,?,?,?)";
	// LDAP
	protected static String UPDATE_NEXT_ID_IUSER = "UPDATE IUSERNEXTID SET ID=ID+1 WHERE TYPE=1";
	protected static String SELECT_NEXT_ID_IUSER = "SELECT ID FROM IUSERNEXTID WHERE TYPE=1";
	protected static String INSERT_NEXT_ID_IUSER = "INSERT INTO IUSERLDAPUSERHDR(ID,LDAPGUID,LDAPFULLNAME) VALUES(?,?,?)";

	protected static String UPDATE_IUSERUSERTYPE = "UPDATE IUSERUSERTYPE SET TYPE =? WHERE USERID=? AND PRODID=?";
	protected static String UPDATE_IUSERLDAPUSERHDR = "UPDATE IUSERLDAPUSERHDR SET LDAPFULLNAME =? WHERE ID=?";
	// FOR CHANGEOFFICE
	protected static String DELETE_IDOCFDRSTAT = "DELETE FROM IDOCFDRSTAT WHERE USERID=?";
	protected static String DELETE_SCR_SEQCNT = "DELETE FROM SCR_SEQCNT WHERE USERID=?";
	// FOR EMAIL
	protected static String SELECT_SCR_EMAIL_USRLOC = "SELECT EMAIL FROM SCR_USRLOC WHERE USERID=?";
	protected static String SELECT_SCR_EMAIL_OFIC = "SELECT EMAIL FROM SCR_DIROFIC WHERE ID_OFIC=?";
	protected static String DELETE_SCR_EMAIL = "DELETE FROM SCR_EMAIL WHERE ID=?";

	protected static String UPDATE_USER_CONFIG_IDOFICPREF = "UPDATE SCR_USERCONFIG SET IDOFICPREF=? WHERE USERID=?";

	protected static final SimpleDateFormat FORMATTER = new SimpleDateFormat(
			"dd/MM/yyyy");

	protected static final SimpleDateFormat FORMATTERSTAMP = new SimpleDateFormat(
			"dd/MM/yyyy HH:mm");

	protected static final SimpleDateFormat FORMATTERSTAMPAL = new SimpleDateFormat(
			"dd/MM/yyyy HH:mm:ss");

	protected static String INSERT_SCR_REGINT = "INSERT INTO SCR_REGINT(ID,ID_ARCH,ID_FDR,NAME,ID_PERSON,ID_ADDRESS,ORD) VALUES (?,?,?,?,?,?,?)";
	protected static String SELECT_SCR_REGINT = "SELECT * FROM SCR_REGINT WHERE ID_ARCH=? AND ID_FDR=?";
	protected static String DELETE_SCR_REGINT = "DELETE FROM SCR_REGINT WHERE ID_ARCH=? AND ID_FDR=?";
	protected static String ORDER_SCR_REGINT = " ORDER BY ORD";

	protected static String SELECT_REPOSITORY_DOCUMENT_ID = "SELECT DOCUID FROM SCR_REPOSITORYDOCS WHERE ID = ?";
	protected static String INSERT_SCR_DOCUMENTREPOSITORY = "INSERT INTO SCR_REPOSITORYDOCS(ID, DOCUID) VALUES (?,?)";
	protected static String SELECT_NEXT_ID_SCR_DOCUMENTREPOSITORY = "SELECT MAX(ID) + 1 FROM SCR_REPOSITORYDOCS";

	protected static String SELECT_REPOSITORY_BOOK_TYPE = "SELECT ID_REP_CONF FROM SCR_REPOBOOKTYPE WHERE BOOK_TYPE = ?";
	protected static String SELECT_REPOSITORY_CONFIGURATION_DATA = "SELECT DATA FROM SCR_REPOSITORYCONF WHERE ID = ?";

	// /////// TODO SCR_DOCLOCATOR /////////
	protected static String INSERT_SCR_DOCLOCATOR = "INSERT INTO SCR_DOCLOCATOR(bookID, folderID, pageID, locator) VALUES (?,?,?,?)";
}
