BEGIN TRANSACTION;

CREATE TABLE IVOLACTDIR
(
  volid INTEGER NOT NULL,
  actdir INTEGER NOT NULL,
  numfiles INTEGER NOT NULL
);

CREATE TABLE IVOLARCHLIST
(
  archid INTEGER NOT NULL,
  listid INTEGER NOT NULL
); 

CREATE TABLE IVOLFILEFTS
(
  id INTEGER NOT NULL,
  extid1 INTEGER NOT NULL,
  extid2 INTEGER NOT NULL,
  extid3 INTEGER NOT NULL,
  extid4 INTEGER NOT NULL,
  path CHARACTER VARYING(254) NOT NULL,
  "timestamp" TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IVOLFILEHDR
(
  id INTEGER NOT NULL,
  volid INTEGER NOT NULL,
  loc CHARACTER VARYING(254) NOT NULL,
  extid1 INTEGER NOT NULL,
  extid2 INTEGER NOT NULL,
  extid3 INTEGER NOT NULL,
  flags INTEGER NOT NULL,
  stat INTEGER NOT NULL,
  "timestamp" TIMESTAMP WITHOUT TIME ZONE,
  filesize DOUBLE PRECISION NOT NULL
);

CREATE TABLE IVOLLISTHDR
(
  id INTEGER NOT NULL,
  name CHARACTER VARYING(32) NOT NULL,
  flags INTEGER NOT NULL,
  stat INTEGER NOT NULL,
  remarks CHARACTER VARYING(254),
  crtrid INTEGER NOT NULL,
  crtndate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  updrid INTEGER,
  upddate TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IVOLLISTVOL
(
  listid INTEGER NOT NULL,
  volid INTEGER NOT NULL,
  sortorder INTEGER NOT NULL
);

CREATE TABLE IVOLNEXTID
(
  "type" INTEGER NOT NULL,
  id INTEGER NOT NULL
);

CREATE TABLE IVOLREPHDR
(
  id INTEGER NOT NULL,
  name CHARACTER VARYING(32) NOT NULL,
  "type" INTEGER NOT NULL,
  info TEXT NOT NULL,
  stat INTEGER NOT NULL,
  remarks CHARACTER VARYING(254),
  crtrid INTEGER NOT NULL,
  crtndate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  updrid INTEGER,
  upddate TIMESTAMP WITHOUT TIME ZONE
);   
  
CREATE TABLE IVOLVOLHDR
(
  id INTEGER NOT NULL,
  name CHARACTER VARYING(32) NOT NULL,
  repid INTEGER NOT NULL,
  info TEXT NOT NULL,
  itemp INTEGER NOT NULL,
  actsize CHARACTER VARYING(32) NOT NULL,
  numfiles INTEGER NOT NULL,
  stat INTEGER NOT NULL,
  remarks CHARACTER VARYING(254),
  crtrid INTEGER NOT NULL,
  crtndate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  updrid INTEGER,
  upddate TIMESTAMP WITHOUT TIME ZONE
); 

CREATE TABLE IVOLVOLTBL
(
  locid CHARACTER VARYING(32) NOT NULL,
  extid1 INTEGER NOT NULL,
  extid2 INTEGER NOT NULL,
  extid3 INTEGER NOT NULL,
  extid4 INTEGER NOT NULL,
  fileext CHARACTER VARYING(10) NOT NULL,
  fileval BYTEA NOT NULL
);

CREATE UNIQUE INDEX IVOLACTDIR1 ON IVOLACTDIR(volid); 

CREATE UNIQUE INDEX IVOLARCHLIST1 ON IVOLARCHLIST(archid); 

CREATE INDEX IVOLARCHLIST2 ON IVOLARCHLIST(listid); 

CREATE UNIQUE INDEX IVOLFILEFTS1 ON IVOLFILEFTS(id); 

CREATE UNIQUE INDEX IVOLFILEHDR1 ON IVOLFILEHDR(id); 

CREATE INDEX IVOLFILEHDR2 ON IVOLFILEHDR(volid); 

CREATE UNIQUE INDEX IVOLLISTHDR1 ON IVOLLISTHDR(id); 

CREATE INDEX IVOLLISTVOL1 ON IVOLLISTVOL(listid); 

CREATE INDEX IVOLLISTVOL2 ON IVOLLISTVOL(volid); 

CREATE UNIQUE INDEX IVOLNEXTID1 ON IVOLNEXTID("type"); 

CREATE UNIQUE INDEX IVOLREPHDR1 ON IVOLREPHDR(id); 

CREATE UNIQUE INDEX IVOLVOLHDR1 ON IVOLVOLHDR(id); 

CREATE INDEX IVOLVOLHDR2 ON IVOLVOLHDR(repid); 

CREATE UNIQUE INDEX IVOLVOLTBL1 ON IVOLVOLTBL(locid); 

-- REVISAR PORQUÉ ESTÁ FALLANDO ESTE ÍNDICE
-- CREATE INDEX IVOLVOLTBLFTS ON IVOLVOLTBL(fileval);  

INSERT INTO IVOLACTDIR ( volid, actdir, numfiles ) VALUES (1, 1, 0); 
 
INSERT INTO IVOLLISTHDR ( id, name, flags, stat, remarks, crtrid, crtndate, updrid,
upddate ) VALUES (6, 'ListBD', 0, 0, NULL, 0,  now(), NULL, NULL); 
 
INSERT INTO IVOLLISTVOL ( listid, volid, sortorder ) VALUES (6, 1, 1);  
 
INSERT INTO IVOLNEXTID ( "type", id ) VALUES (1, 7); 
INSERT INTO IVOLNEXTID ( "type", id ) VALUES (2, 7); 
INSERT INTO IVOLNEXTID ( "type", id ) VALUES (3, 7); 
INSERT INTO IVOLNEXTID ( "type", id ) VALUES (4, 130); 

INSERT INTO IVOLREPHDR ( id, name, "type", info, stat, remarks, crtrid, crtndate, updrid,
upddate ) VALUES (1, 'RepBD', 5, '"01.01"|""|5|0|0|0|0' , 0, NULL, 0, now(), NULL, NULL); 

INSERT INTO IVOLVOLHDR ( id, name, repid, info, itemp, actsize, numfiles, stat, remarks, crtrid, crtndate,
updrid, upddate ) VALUES (1, 'RepBD', 1, '"01.01"|5|"IVOLVOLTBL,LOCID,varchar(32),FILEVAL,image"|"1073741824"|0', 0, '0', 0, 0, NULL, 0,  now(), 0,  now()); 

COMMIT;