CREATE TABLE IVOLACTDIR
(
  volid INTEGER NOT NULL,
  actdir INTEGER NOT NULL,
  numfiles INTEGER NOT NULL
);

CREATE TABLE IVOLARCHLIST
(
  archid INTEGER NOT NULL,
  listid INTEGER NOT NULL
); 

CREATE TABLE IVOLFILEFTS
(
  id INTEGER NOT NULL,
  extid1 INTEGER NOT NULL,
  extid2 INTEGER NOT NULL,
  extid3 INTEGER NOT NULL,
  extid4 INTEGER NOT NULL,
  path CHARACTER VARYING(254) NOT NULL,
  "timestamp" TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IVOLFILEHDR
(
  id INTEGER NOT NULL,
  volid INTEGER NOT NULL,
  loc CHARACTER VARYING(254) NOT NULL,
  extid1 INTEGER NOT NULL,
  extid2 INTEGER NOT NULL,
  extid3 INTEGER NOT NULL,
  flags INTEGER NOT NULL,
  stat INTEGER NOT NULL,
  "timestamp" TIMESTAMP WITHOUT TIME ZONE,
  filesize DOUBLE PRECISION NOT NULL
);

CREATE TABLE IVOLLISTHDR
(
  id INTEGER NOT NULL,
  name CHARACTER VARYING(32) NOT NULL,
  flags INTEGER NOT NULL,
  stat INTEGER NOT NULL,
  remarks CHARACTER VARYING(254),
  crtrid INTEGER NOT NULL,
  crtndate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  updrid INTEGER,
  upddate TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IVOLLISTVOL
(
  listid INTEGER NOT NULL,
  volid INTEGER NOT NULL,
  sortorder INTEGER NOT NULL
);

CREATE TABLE IVOLNEXTID
(
  "type" INTEGER NOT NULL,
  id INTEGER NOT NULL
);

CREATE TABLE IVOLREPHDR
(
  id INTEGER NOT NULL,
  name CHARACTER VARYING(32) NOT NULL,
  "type" INTEGER NOT NULL,
  info TEXT NOT NULL,
  stat INTEGER NOT NULL,
  remarks CHARACTER VARYING(254),
  crtrid INTEGER NOT NULL,
  crtndate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  updrid INTEGER,
  upddate TIMESTAMP WITHOUT TIME ZONE
);   
  
CREATE TABLE IVOLVOLHDR
(
  id INTEGER NOT NULL,
  name CHARACTER VARYING(32) NOT NULL,
  repid INTEGER NOT NULL,
  info TEXT NOT NULL,
  itemp INTEGER NOT NULL,
  actsize CHARACTER VARYING(32) NOT NULL,
  numfiles INTEGER NOT NULL,
  stat INTEGER NOT NULL,
  remarks CHARACTER VARYING(254),
  crtrid INTEGER NOT NULL,
  crtndate TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  updrid INTEGER,
  upddate TIMESTAMP WITHOUT TIME ZONE
); 

CREATE TABLE IVOLVOLTBL
(
  locid CHARACTER VARYING(32) NOT NULL,
  extid1 INTEGER NOT NULL,
  extid2 INTEGER NOT NULL,
  extid3 INTEGER NOT NULL,
  extid4 INTEGER NOT NULL,
  fileext CHARACTER VARYING(10) NOT NULL,
  fileval BYTEA NOT NULL
);

