CREATE UNIQUE INDEX IVOLACTDIR1 ON IVOLACTDIR(volid); 

CREATE UNIQUE INDEX IVOLARCHLIST1 ON IVOLARCHLIST(archid); 

CREATE INDEX IVOLARCHLIST2 ON IVOLARCHLIST(listid); 

CREATE UNIQUE INDEX IVOLFILEFTS1 ON IVOLFILEFTS(id); 

CREATE UNIQUE INDEX IVOLFILEHDR1 ON IVOLFILEHDR(id); 

CREATE INDEX IVOLFILEHDR2 ON IVOLFILEHDR(volid); 

CREATE UNIQUE INDEX IVOLLISTHDR1 ON IVOLLISTHDR(id); 

CREATE INDEX IVOLLISTVOL1 ON IVOLLISTVOL(listid); 

CREATE INDEX IVOLLISTVOL2 ON IVOLLISTVOL(volid); 

CREATE UNIQUE INDEX IVOLNEXTID1 ON IVOLNEXTID("type"); 

CREATE UNIQUE INDEX IVOLREPHDR1 ON IVOLREPHDR(id); 

CREATE UNIQUE INDEX IVOLVOLHDR1 ON IVOLVOLHDR(id); 

CREATE INDEX IVOLVOLHDR2 ON IVOLVOLHDR(repid); 

CREATE UNIQUE INDEX IVOLVOLTBL1 ON IVOLVOLTBL(locid); 

-- REVISAR PORQUÉ ESTÁ FALLANDO ESTE ÍNDICE
-- CREATE INDEX IVOLVOLTBLFTS ON IVOLVOLTBL(fileval); 