package es.ieci.scsp.verifdata.model.mapping.clienteligero;

// Generated 05-mar-2012 13:26:17 by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CertificadosAutorizaciones generated by hbm2java
 */
@Entity
@Table(name = "certificados_autorizaciones")
public class CertificadosAutorizaciones implements java.io.Serializable {

	private String codigoCertificado;
	private String descripcion;
	private String xpathAdjunto;
	private String mimeTypeAdjunto;
	private String xmlTemplate;
	private String classDatosEspecificos;
	private String classExcelProcesador;
	private String excelTemplate;
	private Boolean directo;
	private String classExcelRespProcesador;
	private String excelTemplateRespuesta;
	private Set<Preprocesadores> preprocesadoreses = new HashSet<Preprocesadores>(
			0);
	private Set<Postprocesadores> postprocesadoreses = new HashSet<Postprocesadores>(
			0);
	private Set<Sinonimos> sinonimoses = new HashSet<Sinonimos>(0);

	public CertificadosAutorizaciones() {
	}

	public CertificadosAutorizaciones(String codigoCertificado) {
		this.codigoCertificado = codigoCertificado;
	}

	public CertificadosAutorizaciones(String codigoCertificado,
			String descripcion, String xpathAdjunto, String mimeTypeAdjunto,
			String xmlTemplate, String classDatosEspecificos,
			String classExcelProcesador, String excelTemplate, Boolean directo,
			String classExcelRespProcesador, String excelTemplateRespuesta,
			Set<Preprocesadores> preprocesadoreses,
			Set<Postprocesadores> postprocesadoreses, Set<Sinonimos> sinonimoses) {
		this.codigoCertificado = codigoCertificado;
		this.descripcion = descripcion;
		this.xpathAdjunto = xpathAdjunto;
		this.mimeTypeAdjunto = mimeTypeAdjunto;
		this.xmlTemplate = xmlTemplate;
		this.classDatosEspecificos = classDatosEspecificos;
		this.classExcelProcesador = classExcelProcesador;
		this.excelTemplate = excelTemplate;
		this.directo = directo;
		this.classExcelRespProcesador = classExcelRespProcesador;
		this.excelTemplateRespuesta = excelTemplateRespuesta;
		this.preprocesadoreses = preprocesadoreses;
		this.postprocesadoreses = postprocesadoreses;
		this.sinonimoses = sinonimoses;
	}

	@Id
	@Column(name = "codigo_certificado", unique = true, nullable = false, length = 64)
	public String getCodigoCertificado() {
		return this.codigoCertificado;
	}

	public void setCodigoCertificado(String codigoCertificado) {
		this.codigoCertificado = codigoCertificado;
	}

	@Column(name = "descripcion", length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "xpath_adjunto", length = 256)
	public String getXpathAdjunto() {
		return this.xpathAdjunto;
	}

	public void setXpathAdjunto(String xpathAdjunto) {
		this.xpathAdjunto = xpathAdjunto;
	}

	@Column(name = "mime_type_adjunto", length = 256)
	public String getMimeTypeAdjunto() {
		return this.mimeTypeAdjunto;
	}

	public void setMimeTypeAdjunto(String mimeTypeAdjunto) {
		this.mimeTypeAdjunto = mimeTypeAdjunto;
	}

	@Column(name = "xml_template", length = 256)
	public String getXmlTemplate() {
		return this.xmlTemplate;
	}

	public void setXmlTemplate(String xmlTemplate) {
		this.xmlTemplate = xmlTemplate;
	}

	@Column(name = "class_datos_especificos", length = 256)
	public String getClassDatosEspecificos() {
		return this.classDatosEspecificos;
	}

	public void setClassDatosEspecificos(String classDatosEspecificos) {
		this.classDatosEspecificos = classDatosEspecificos;
	}

	@Column(name = "class_excel_procesador", length = 256)
	public String getClassExcelProcesador() {
		return this.classExcelProcesador;
	}

	public void setClassExcelProcesador(String classExcelProcesador) {
		this.classExcelProcesador = classExcelProcesador;
	}

	@Column(name = "excel_template", length = 256)
	public String getExcelTemplate() {
		return this.excelTemplate;
	}

	public void setExcelTemplate(String excelTemplate) {
		this.excelTemplate = excelTemplate;
	}

	@Column(name = "directo")
	public Boolean getDirecto() {
		return this.directo;
	}

	public void setDirecto(Boolean directo) {
		this.directo = directo;
	}

	@Column(name = "class_excel_resp_procesador", length = 256)
	public String getClassExcelRespProcesador() {
		return this.classExcelRespProcesador;
	}

	public void setClassExcelRespProcesador(String classExcelRespProcesador) {
		this.classExcelRespProcesador = classExcelRespProcesador;
	}

	@Column(name = "excel_template_respuesta", length = 256)
	public String getExcelTemplateRespuesta() {
		return this.excelTemplateRespuesta;
	}

	public void setExcelTemplateRespuesta(String excelTemplateRespuesta) {
		this.excelTemplateRespuesta = excelTemplateRespuesta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "certificadosAutorizaciones")
	public Set<Preprocesadores> getPreprocesadoreses() {
		return this.preprocesadoreses;
	}

	public void setPreprocesadoreses(Set<Preprocesadores> preprocesadoreses) {
		this.preprocesadoreses = preprocesadoreses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "certificadosAutorizaciones")
	public Set<Postprocesadores> getPostprocesadoreses() {
		return this.postprocesadoreses;
	}

	public void setPostprocesadoreses(Set<Postprocesadores> postprocesadoreses) {
		this.postprocesadoreses = postprocesadoreses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "certificadosAutorizaciones")
	public Set<Sinonimos> getSinonimoses() {
		return this.sinonimoses;
	}

	public void setSinonimoses(Set<Sinonimos> sinonimoses) {
		this.sinonimoses = sinonimoses;
	}

}
