package es.ieci.scsp.verifdata.model.mapping.clienteligero;

// Generated 05-mar-2012 13:26:17 by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Preprocesadores generated by hbm2java
 */
@Entity
@Table(name = "preprocesadores")
public class Preprocesadores implements java.io.Serializable {

	private PreprocesadoresId id;
	private CertificadosAutorizaciones certificadosAutorizaciones;
	private String clase;

	public Preprocesadores() {
	}

	public Preprocesadores(PreprocesadoresId id,
			CertificadosAutorizaciones certificadosAutorizaciones, String clase) {
		this.id = id;
		this.certificadosAutorizaciones = certificadosAutorizaciones;
		this.clase = clase;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "certificado", column = @Column(name = "certificado", nullable = false, length = 64)),
			@AttributeOverride(name = "preprocesadorOrden", column = @Column(name = "preprocesador_orden", nullable = false)) })
	public PreprocesadoresId getId() {
		return this.id;
	}

	public void setId(PreprocesadoresId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "certificado", nullable = false, insertable = false, updatable = false)
	public CertificadosAutorizaciones getCertificadosAutorizaciones() {
		return this.certificadosAutorizaciones;
	}

	public void setCertificadosAutorizaciones(
			CertificadosAutorizaciones certificadosAutorizaciones) {
		this.certificadosAutorizaciones = certificadosAutorizaciones;
	}

	@Column(name = "clase", nullable = false, length = 256)
	public String getClase() {
		return this.clase;
	}

	public void setClase(String clase) {
		this.clase = clase;
	}

}
