package es.ieci.scsp.verifdata.model.mapping.clienteligero;

// Generated 05-mar-2012 13:26:17 by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Sinonimos generated by hbm2java
 */
@Entity
@Table(name = "sinonimos")
public class Sinonimos implements java.io.Serializable {

	private SinonimosId id;
	private CertificadosAutorizaciones certificadosAutorizaciones;
	private String valor;

	public Sinonimos() {
	}

	public Sinonimos(SinonimosId id,
			CertificadosAutorizaciones certificadosAutorizaciones) {
		this.id = id;
		this.certificadosAutorizaciones = certificadosAutorizaciones;
	}

	public Sinonimos(SinonimosId id,
			CertificadosAutorizaciones certificadosAutorizaciones, String valor) {
		this.id = id;
		this.certificadosAutorizaciones = certificadosAutorizaciones;
		this.valor = valor;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "certificado", column = @Column(name = "certificado", nullable = false, length = 64)),
			@AttributeOverride(name = "clave", column = @Column(name = "clave", nullable = false, length = 256)) })
	public SinonimosId getId() {
		return this.id;
	}

	public void setId(SinonimosId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "certificado", nullable = false, insertable = false, updatable = false)
	public CertificadosAutorizaciones getCertificadosAutorizaciones() {
		return this.certificadosAutorizaciones;
	}

	public void setCertificadosAutorizaciones(
			CertificadosAutorizaciones certificadosAutorizaciones) {
		this.certificadosAutorizaciones = certificadosAutorizaciones;
	}

	@Column(name = "valor", length = 1024)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

}
