package es.ieci.scsp.verifdata.model.mapping.clienteligero;

// Generated 05-mar-2012 13:26:35 by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UsuariosAutorizaciones generated by hbm2java
 */
@Entity
@Table(name = "usuarios_autorizaciones")
public class UsuariosAutorizaciones implements java.io.Serializable {

	private UsuariosAutorizacionesId id;

	public UsuariosAutorizaciones() {
	}

	public UsuariosAutorizaciones(UsuariosAutorizacionesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idUsuario", column = @Column(name = "id_usuario", nullable = false, length = 14)),
			@AttributeOverride(name = "codigoProcedimiento", column = @Column(name = "codigo_procedimiento", nullable = false)),
			@AttributeOverride(name = "codigoCertificado", column = @Column(name = "codigo_certificado", nullable = false)) })
	public UsuariosAutorizacionesId getId() {
		return this.id;
	}

	public void setId(UsuariosAutorizacionesId id) {
		this.id = id;
	}

}
