package es.ieci.scsp.verifdata.model.mapping.clienteligero;

// Generated 05-mar-2012 13:26:35 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuariosAutorizacionesId generated by hbm2java
 */
@Embeddable
public class UsuariosAutorizacionesId implements java.io.Serializable {

	private String idUsuario;
	private String codigoProcedimiento;
	private String codigoCertificado;

	public UsuariosAutorizacionesId() {
	}

	public UsuariosAutorizacionesId(String idUsuario,
			String codigoProcedimiento, String codigoCertificado) {
		this.idUsuario = idUsuario;
		this.codigoProcedimiento = codigoProcedimiento;
		this.codigoCertificado = codigoCertificado;
	}

	@Column(name = "id_usuario", nullable = false, length = 14)
	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "codigo_procedimiento", nullable = false)
	public String getCodigoProcedimiento() {
		return this.codigoProcedimiento;
	}

	public void setCodigoProcedimiento(String codigoProcedimiento) {
		this.codigoProcedimiento = codigoProcedimiento;
	}

	@Column(name = "codigo_certificado", nullable = false)
	public String getCodigoCertificado() {
		return this.codigoCertificado;
	}

	public void setCodigoCertificado(String codigoCertificado) {
		this.codigoCertificado = codigoCertificado;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuariosAutorizacionesId))
			return false;
		UsuariosAutorizacionesId castOther = (UsuariosAutorizacionesId) other;

		return ((this.getIdUsuario() == castOther.getIdUsuario()) || (this
				.getIdUsuario() != null
				&& castOther.getIdUsuario() != null && this.getIdUsuario()
				.equals(castOther.getIdUsuario())))
				&& ((this.getCodigoProcedimiento() == castOther
						.getCodigoProcedimiento()) || (this
						.getCodigoProcedimiento() != null
						&& castOther.getCodigoProcedimiento() != null && this
						.getCodigoProcedimiento().equals(
								castOther.getCodigoProcedimiento())))
				&& ((this.getCodigoCertificado() == castOther
						.getCodigoCertificado()) || (this
						.getCodigoCertificado() != null
						&& castOther.getCodigoCertificado() != null && this
						.getCodigoCertificado().equals(
								castOther.getCodigoCertificado())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdUsuario() == null ? 0 : this.getIdUsuario().hashCode());
		result = 37
				* result
				+ (getCodigoProcedimiento() == null ? 0 : this
						.getCodigoProcedimiento().hashCode());
		result = 37
				* result
				+ (getCodigoCertificado() == null ? 0 : this
						.getCodigoCertificado().hashCode());
		return result;
	}

}
