-----------------------------
-- INDEX KEYS INVESDOC     --
-----------------------------
CREATE UNIQUE INDEX IDOCAPPEVENT1
ON IDOCAPPEVENT (APPID, EVENTID)
;
CREATE INDEX IDOCARCHDET1
ON IDOCARCHDET (ARCHID, DETTYPE)
;
CREATE INDEX IDOCARCHDET2
ON IDOCARCHDET (ARCHID)
;
CREATE INDEX IDOCARCHHDR1
ON IDOCARCHHDR (ID)
;
CREATE INDEX IDOCARCHHDR2
ON IDOCARCHHDR (TYPE)
;
CREATE UNIQUE INDEX IDOCAUTONUMCTLG1
ON IDOCAUTONUMCTLG (ID)
;
CREATE UNIQUE INDEX IDOCAUTONUMCTLG2
ON IDOCAUTONUMCTLG (NAME)
;
CREATE UNIQUE INDEX IDOCBTBLCTLG1
ON IDOCBTBLCTLG (ID)
;
CREATE INDEX IDOCCOMPUSG1
ON IDOCCOMPUSG (COMPID, COMPTYPE)
;
CREATE INDEX IDOCDATNODE1
ON IDOCDATNODE (ID, TYPE)
;
CREATE INDEX IDOCDATNODE2
ON IDOCDATNODE (PARENTID)
;
CREATE INDEX IDOCDATNODE3
ON IDOCDATNODE (TYPE)
;
CREATE UNIQUE INDEX IDOCDBCTLG1
ON IDOCDBCTLG (ID)
;
CREATE UNIQUE INDEX IDOCDBCTLG2
ON IDOCDBCTLG (NAME)
;
CREATE INDEX IDOCDIRHDR1
ON IDOCDIRHDR (ID)
;
CREATE INDEX IDOCDIRHDR2
ON IDOCDIRHDR (TYPE)
;
CREATE INDEX IDOCFDRLINK1
ON IDOCFDRLINK (ID)
;
CREATE INDEX IDOCFDRLINK2
ON IDOCFDRLINK (CNTRDBID, CNTRARCHID, CNTRFDRID, CNTRCLFID)
;
CREATE INDEX IDOCFDRLINK3
ON IDOCFDRLINK (SRVRDBID, SRVRARCHID, SRVRFDRID)
;
CREATE INDEX IDOCFDRLINKX1
ON IDOCFDRLINKX (ID)
;
CREATE INDEX IDOCFDRLINKX2
ON IDOCFDRLINKX (CNTRDBID, CNTRARCHID, CNTRFDRID, CNTRCLFID)
;
CREATE INDEX IDOCFDRLINKX3
ON IDOCFDRLINKX (SRVRDBID, SRVRARCHID, SRVRFDRID)
;
CREATE INDEX IDOCFDRSTAT1
ON IDOCFDRSTAT (ARCHID, FDRID)
;
CREATE INDEX IDOCFDRSTAT2
ON IDOCFDRSTAT (STAT)
;
CREATE UNIQUE INDEX IDOCFIAUXTBLCTLG1
ON IDOCFIAUXTBLCTLG (ID)
;
CREATE INDEX IDOCFIAUXTBLCTLG2
ON IDOCFIAUXTBLCTLG (NAME)
;
CREATE INDEX IDOCFIAUXTBLCTLG3
ON IDOCFIAUXTBLCTLG (USERID)
;
CREATE UNIQUE INDEX IDOCFMT1
ON IDOCFMT (ID)
;
CREATE INDEX IDOCFMT2
ON IDOCFMT (ARCHID, TYPE)
;
CREATE INDEX IDOCGLBDOCH1
ON IDOCGLBDOCH (ID)
;
CREATE INDEX IDOCGLBDOCH2
ON IDOCGLBDOCH (ARCHID, FDRID)
;
CREATE INDEX IDOCGLBDOCH3
ON IDOCGLBDOCH (ARCHID, FDRID, CLFID)
;
CREATE UNIQUE INDEX IDOCMACRO1
ON IDOCMACRO (ID)
;
CREATE UNIQUE INDEX IDOCMACRO2
ON IDOCMACRO (NAME)
;
CREATE UNIQUE INDEX IDOCNEXTID1
ON IDOCNEXTID (TYPE)
;
CREATE UNIQUE INDEX IDOCPAGEANNS1
ON IDOCPAGEANNS (ID)
;
CREATE UNIQUE INDEX IDOCPICT1
ON IDOCPICT (ID)
;
CREATE UNIQUE INDEX IDOCPICT2
ON IDOCPICT (NAME)
;
CREATE UNIQUE INDEX IDOCPREFFMT1
ON IDOCPREFFMT (ARCHID, FMTTYPE, USERID)
;
CREATE UNIQUE INDEX IDOCPREFWFMT1
ON IDOCPREFWFMT (ARCHID, FMTTYPE, USERID)
;
CREATE INDEX IDOCRPT1
ON IDOCRPT (ID)
;
CREATE INDEX IDOCRPT2
ON IDOCRPT (ARCHID)
;
CREATE UNIQUE INDEX IDOCRPTAUXTBL1
ON IDOCRPTAUXTBL (FDRID)
;
CREATE INDEX IDOCSRVSTATEDET1
ON IDOCSRVSTATEDET (ID)
;
CREATE INDEX IDOCSRVSTATEDET2
ON IDOCSRVSTATEDET (SESSIONID)
;
CREATE INDEX IDOCSRVSTATEDET3
ON IDOCSRVSTATEDET (PARENTID)
;
CREATE UNIQUE INDEX IDOCSRVSTATEHDR1
ON IDOCSRVSTATEHDR (ID)
;
CREATE INDEX IDOCSRVSTATEHDR2
ON IDOCSRVSTATEHDR (USERID, PRODID)
;
CREATE INDEX IDOCSRVSTATEHDR3
ON IDOCSRVSTATEHDR (timestamp)
;
CREATE UNIQUE INDEX IDOCVTBLCTLG1
ON IDOCVTBLCTLG (ID)
;
CREATE UNIQUE INDEX IDOCWMACRO1
ON IDOCWMACRO (ID)
;
CREATE UNIQUE INDEX IDOCWMACRO2
ON IDOCWMACRO (NAME)
;
CREATE UNIQUE INDEX IDOCXNEXTID1
ON IDOCXNEXTID (TYPE, PARENTID)
;
CREATE INDEX ITDSMSSESS1
ON ITDSMSSESS (CID)
;
CREATE INDEX ITDSMSSESS2
ON ITDSMSSESS (CAPPID)
;
CREATE INDEX ITDSMSSESS3
ON ITDSMSSESS (CUSERID)
;
CREATE UNIQUE INDEX IUSERCURRCNT1
ON IUSERCURRCNT (ID)
;
CREATE UNIQUE INDEX IUSERCURRCNT2
ON IUSERCURRCNT (USERID, PRODID, APPID)
;
CREATE UNIQUE INDEX IUSERDEPTHDR1
ON IUSERDEPTHDR (ID)
;
CREATE INDEX IUSERDEPTHDR2
ON IUSERDEPTHDR (NAME)
;
CREATE INDEX IUSERDEPTHDR3
ON IUSERDEPTHDR (PARENTID)
;
CREATE INDEX IUSERDEPTHDR4
ON IUSERDEPTHDR (MGRID)
;
CREATE INDEX IUSERDEPTHDR5
ON IUSERDEPTHDR (TYPE)
;
CREATE INDEX IUSERGENPERMS1
ON IUSERGENPERMS (DSTTYPE, DSTID)
;
CREATE INDEX IUSERGENPERMS2
ON IUSERGENPERMS (DSTTYPE, DSTID, PRODID)
;
CREATE UNIQUE INDEX IUSERGROUPHDR1
ON IUSERGROUPHDR (ID)
;
CREATE INDEX IUSERGROUPHDR2
ON IUSERGROUPHDR (NAME)
;
CREATE INDEX IUSERGROUPHDR3
ON IUSERGROUPHDR (MGRID)
;
CREATE INDEX IUSERGROUPHDR4
ON IUSERGROUPHDR (TYPE)
;
CREATE INDEX IUSERGROUPUSER1
ON IUSERGROUPUSER (GROUPID)
;
CREATE INDEX IUSERGROUPUSER2
ON IUSERGROUPUSER (USERID)
;
CREATE UNIQUE INDEX IUSERLDAPGRPHDR1
ON IUSERLDAPGRPHDR (ID)
;
CREATE UNIQUE INDEX IUSERLDAPGRPHDR2
ON IUSERLDAPGRPHDR (LDAPGUID)
;
CREATE UNIQUE INDEX IUSERLDAPUSERHDR1
ON IUSERLDAPUSERHDR (ID)
;
CREATE UNIQUE INDEX IUSERLDAPUSERHDR2
ON IUSERLDAPUSERHDR (LDAPGUID)
;
CREATE UNIQUE INDEX IUSERNEXTID1
ON IUSERNEXTID (TYPE)
;
CREATE INDEX IUSEROBJHDR1
ON IUSEROBJHDR (ID)
;
CREATE INDEX IUSEROBJHDR2
ON IUSEROBJHDR (OWNERTYPE, OWNERID)
;
CREATE INDEX IUSEROBJHDR3
ON IUSEROBJHDR (PRODID)
;
CREATE INDEX IUSEROBJHDR4
ON IUSEROBJHDR (PRODID, TYPE)
;
CREATE INDEX IUSEROBJHDR5
ON IUSEROBJHDR (PRODID, TYPE, EXTID1)
;
CREATE INDEX IUSEROBJPERM1
ON IUSEROBJPERM (DSTTYPE, DSTID)
;
CREATE INDEX IUSEROBJPERM2
ON IUSEROBJPERM (OBJID)
;
CREATE INDEX IUSEROBJPERM3
ON IUSEROBJPERM (DSTTYPE, DSTID, OBJID)
;
CREATE UNIQUE INDEX IUSERREMUSER1
ON IUSERREMUSER (ID)
;
CREATE UNIQUE INDEX IUSERUSERHDR1
ON IUSERUSERHDR (ID)
;
CREATE INDEX IUSERUSERHDR2
ON IUSERUSERHDR (NAME)
;
CREATE INDEX IUSERUSERHDR3
ON IUSERUSERHDR (DEPTID)
;
CREATE INDEX IUSERUSERMAP1
ON IUSERUSERMAP (SRCDBID, SRCUSERID)
;
CREATE INDEX IUSERUSERMAP2
ON IUSERUSERMAP (DSTDBID, DSTUSERID)
;
CREATE INDEX IUSERUSERMAP3
ON IUSERUSERMAP (SRCDBID, SRCUSERID, DSTDBID)
;
CREATE INDEX IUSERUSERPWDS1
ON IUSERUSERPWDS (USERID)
;
CREATE INDEX IUSERUSERPWDS2
ON IUSERUSERPWDS (PASSWORD)
;
CREATE INDEX IUSERUSERTYPE1
ON IUSERUSERTYPE (USERID)
;
CREATE INDEX IUSERUSERTYPE2
ON IUSERUSERTYPE (USERID, PRODID)
;
CREATE UNIQUE INDEX IVOLACTDIR1
ON IVOLACTDIR (VOLID)
;
CREATE INDEX IVOLARCHLIST1
ON IVOLARCHLIST (ARCHID)
;
CREATE INDEX IVOLARCHLIST2
ON IVOLARCHLIST (LISTID)
;
CREATE UNIQUE INDEX IVOLFILEFTS1
ON IVOLFILEFTS (ID)
;
CREATE INDEX IVOLFILEHDR1
ON IVOLFILEHDR (ID)
;
CREATE INDEX IVOLFILEHDR2
ON IVOLFILEHDR (VOLID)
;
CREATE UNIQUE INDEX IVOLLISTHDR1
ON IVOLLISTHDR (ID)
;
CREATE INDEX IVOLLISTVOL1
ON IVOLLISTVOL (LISTID)
;
CREATE INDEX IVOLLISTVOL2
ON IVOLLISTVOL (VOLID)
;
CREATE UNIQUE INDEX IVOLNEXTID1
ON IVOLNEXTID (TYPE)
;
CREATE UNIQUE INDEX IVOLREPHDR1
ON IVOLREPHDR (ID)
;
CREATE INDEX IVOLVOLHDR1
ON IVOLVOLHDR (ID)
;
CREATE INDEX IVOLVOLHDR2
ON IVOLVOLHDR (REPID)
;
CREATE UNIQUE INDEX IVOLVOLTBL1
ON IVOLVOLTBL (LOCID)
;

-----------------------------
-- END INDEX KEYS INVESDOC --
-----------------------------

---------------------------------
-- INDEX KEYS ARCHIVADORES     --
---------------------------------
CREATE INDEX A1CLFH1
ON A1CLFH (FDRID, ID)
;
CREATE INDEX A1CLFH2
ON A1CLFH (FDRID)
;
CREATE INDEX A1CLFHX1
ON A1CLFHX (FDRID, ID)
;
CREATE INDEX A1CLFHX2
ON A1CLFHX (FDRID)
;
CREATE INDEX A1DOCH1
ON A1DOCH (ID)
;
CREATE INDEX A1DOCH2
ON A1DOCH (FDRID)
;
CREATE INDEX A1DOCH3
ON A1DOCH (FDRID, CLFID)
;
CREATE INDEX A1DOCHX1
ON A1DOCHX (ID)
;
CREATE INDEX A1DOCHX2
ON A1DOCHX (FDRID)
;
CREATE INDEX A1DOCHX3
ON A1DOCHX (FDRID, CLFID)
;
CREATE UNIQUE INDEX A1FDRH1
ON A1FDRH (ID)
;
CREATE INDEX A1PAGEH1
ON A1PAGEH (FDRID, ID)
;
CREATE INDEX A1PAGEH2
ON A1PAGEH (FDRID)
;
CREATE INDEX A1PAGEH3
ON A1PAGEH (FDRID, DOCID)
;
CREATE INDEX A1PAGEH4
ON A1PAGEH (FILEID)
;
CREATE INDEX A1PAGEHX1
ON A1PAGEHX (FDRID, ID)
;
CREATE INDEX A1PAGEHX2
ON A1PAGEHX (FDRID)
;
CREATE INDEX A1PAGEHX3
ON A1PAGEHX (FDRID, DOCID)
;
CREATE INDEX A1PAGEHX4
ON A1PAGEHX (FILEID)
;
CREATE UNIQUE INDEX A1SF0
ON A1SF (FDRID)
;
CREATE INDEX A1SF1
ON A1SF (FLD1)
;
CREATE INDEX A1SF2
ON A1SF (FLD2)
;
CREATE INDEX A1SF3
ON A1SF (FLD4)
;
CREATE INDEX A1SF4
ON A1SF (FLD6)
;
CREATE INDEX A1SF5
ON A1SF (FLD7)
;
CREATE INDEX A1SF6
ON A1SF (FLD8)
;
CREATE INDEX A1SF7
ON A1SF (FLD9)
;
CREATE INDEX A1SF8
ON A1SF (FLD5)
;
CREATE UNIQUE INDEX A1XF1
ON A1XF (ID)
;
CREATE INDEX A1XF2
ON A1XF (FDRID, FLDID)
;
CREATE INDEX A1XF3
ON A1XF (FDRID)
;
CREATE UNIQUE INDEX A1XNID1
ON A1XNID (TYPE, PARENTID)
;
CREATE INDEX A2CLFH1
ON A2CLFH (FDRID, ID)
;
CREATE INDEX A2CLFH2
ON A2CLFH (FDRID)
;
CREATE INDEX A2CLFHX1
ON A2CLFHX (FDRID, ID)
;
CREATE INDEX A2CLFHX2
ON A2CLFHX (FDRID)
;
CREATE INDEX A2DOCH1
ON A2DOCH (ID)
;
CREATE INDEX A2DOCH2
ON A2DOCH (FDRID)
;
CREATE INDEX A2DOCH3
ON A2DOCH (FDRID, CLFID)
;
CREATE INDEX A2DOCHX1
ON A2DOCHX (ID)
;
CREATE INDEX A2DOCHX2
ON A2DOCHX (FDRID)
;
CREATE INDEX A2DOCHX3
ON A2DOCHX (FDRID, CLFID)
;
CREATE UNIQUE INDEX A2FDRH1
ON A2FDRH (ID)
;
CREATE INDEX A2PAGEH1
ON A2PAGEH (FDRID, ID)
;
CREATE INDEX A2PAGEH2
ON A2PAGEH (FDRID)
;
CREATE INDEX A2PAGEH3
ON A2PAGEH (FDRID, DOCID)
;
CREATE INDEX A2PAGEH4
ON A2PAGEH (FILEID)
;
CREATE INDEX A2PAGEHX1
ON A2PAGEHX (FDRID, ID)
;
CREATE INDEX A2PAGEHX2
ON A2PAGEHX (FDRID)
;
CREATE INDEX A2PAGEHX3
ON A2PAGEHX (FDRID, DOCID)
;
CREATE INDEX A2PAGEHX4
ON A2PAGEHX (FILEID)
;
CREATE UNIQUE INDEX A2SF0
ON A2SF (FDRID)
;
CREATE INDEX A2SF1
ON A2SF (FLD1)
;
CREATE INDEX A2SF2
ON A2SF (FLD2)
;
CREATE INDEX A2SF3
ON A2SF (FLD4)
;
CREATE INDEX A2SF4
ON A2SF (FLD6)
;
CREATE INDEX A2SF5
ON A2SF (FLD7)
;
CREATE INDEX A2SF6
ON A2SF (FLD8)
;
CREATE INDEX A2SF7
ON A2SF (FLD9)
;
CREATE INDEX A2SF8
ON A2SF (FLD5)
;
CREATE UNIQUE INDEX A2XF1
ON A2XF (ID)
;
CREATE INDEX A2XF2
ON A2XF (FDRID, FLDID)
;
CREATE INDEX A2XF3
ON A2XF (FDRID)
;
CREATE UNIQUE INDEX A2XNID1
ON A2XNID (TYPE, PARENTID)
;
CREATE INDEX A3CLFH1
ON A3CLFH (FDRID, ID)
;
CREATE INDEX A3CLFH2
ON A3CLFH (FDRID)
;
CREATE INDEX A3CLFHX1
ON A3CLFHX (FDRID, ID)
;
CREATE INDEX A3CLFHX2
ON A3CLFHX (FDRID)
;
CREATE INDEX A3DOCH1
ON A3DOCH (ID)
;
CREATE INDEX A3DOCH2
ON A3DOCH (FDRID)
;
CREATE INDEX A3DOCH3
ON A3DOCH (FDRID, CLFID)
;
CREATE INDEX A3DOCHX1
ON A3DOCHX (ID)
;
CREATE INDEX A3DOCHX2
ON A3DOCHX (FDRID)
;
CREATE INDEX A3DOCHX3
ON A3DOCHX (FDRID, CLFID)
;
CREATE UNIQUE INDEX A3FDRH1
ON A3FDRH (ID)
;
CREATE INDEX A3PAGEH1
ON A3PAGEH (FDRID, ID)
;
CREATE INDEX A3PAGEH2
ON A3PAGEH (FDRID)
;
CREATE INDEX A3PAGEH3
ON A3PAGEH (FDRID, DOCID)
;
CREATE INDEX A3PAGEH4
ON A3PAGEH (FILEID)
;
CREATE INDEX A3PAGEHX1
ON A3PAGEHX (FDRID, ID)
;
CREATE INDEX A3PAGEHX2
ON A3PAGEHX (FDRID)
;
CREATE INDEX A3PAGEHX3
ON A3PAGEHX (FDRID, DOCID)
;
CREATE INDEX A3PAGEHX4
ON A3PAGEHX (FILEID)
;
CREATE INDEX A3SF0
ON A3SF (FDRID)
;
CREATE INDEX A3SF1
ON A3SF (FLD1)
;
CREATE INDEX A3SF2
ON A3SF (FLD4)
;
CREATE UNIQUE INDEX A3XF1
ON A3XF (ID)
;
CREATE INDEX A3XF2
ON A3XF (FDRID, FLDID)
;
CREATE INDEX A3XF3
ON A3XF (FDRID)
;
CREATE UNIQUE INDEX A3XNID1
ON A3XNID (TYPE, PARENTID)
;
CREATE INDEX A4CLFH1
ON A4CLFH (FDRID, ID)
;
CREATE INDEX A4CLFH2
ON A4CLFH (FDRID)
;
CREATE INDEX A4CLFHX1
ON A4CLFHX (FDRID, ID)
;
CREATE INDEX A4CLFHX2
ON A4CLFHX (FDRID)
;
CREATE INDEX A4DOCH1
ON A4DOCH (ID)
;
CREATE INDEX A4DOCH2
ON A4DOCH (FDRID)
;
CREATE INDEX A4DOCH3
ON A4DOCH (FDRID, CLFID)
;
CREATE INDEX A4DOCHX1
ON A4DOCHX (ID)
;
CREATE INDEX A4DOCHX2
ON A4DOCHX (FDRID)
;
CREATE INDEX A4DOCHX3
ON A4DOCHX (FDRID, CLFID)
;
CREATE UNIQUE INDEX A4FDRH1
ON A4FDRH (ID)
;
CREATE INDEX A4PAGEH1
ON A4PAGEH (FDRID, ID)
;
CREATE INDEX A4PAGEH2
ON A4PAGEH (FDRID)
;
CREATE INDEX A4PAGEH3
ON A4PAGEH (FDRID, DOCID)
;
CREATE INDEX A4PAGEH4
ON A4PAGEH (FILEID)
;
CREATE INDEX A4PAGEHX1
ON A4PAGEHX (FDRID, ID)
;
CREATE INDEX A4PAGEHX2
ON A4PAGEHX (FDRID)
;
CREATE INDEX A4PAGEHX3
ON A4PAGEHX (FDRID, DOCID)
;
CREATE INDEX A4PAGEHX4
ON A4PAGEHX (FILEID)
;
CREATE INDEX A4SF0
ON A4SF (FDRID)
;
CREATE INDEX A4SF1
ON A4SF (FLD1)
;
CREATE UNIQUE INDEX A4XF1
ON A4XF (ID)
;
CREATE INDEX A4XF2
ON A4XF (FDRID, FLDID)
;
CREATE INDEX A4XF3
ON A4XF (FDRID)
;
CREATE UNIQUE INDEX A4XNID1
ON A4XNID (TYPE, PARENTID)
;
---------------------------------
-- END INDEX KEYS ARCHIVADORES --
---------------------------------