-----------------------------------------------
-- Recursos de las entidades principales en CA
-----------------------------------------------

-- Deshabilitar los recursos anteriores, si los hay
UPDATE spac_ct_entidades_resources SET IDIOMA='_ca' WHERE ID_ENT IN (1, 2, 3, 7) AND IDIOMA='ca';

-- Entidad EXPEDIENTES
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'ASUNTO', 'Assumpte');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'CIUDAD', 'Ciutat');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'CODPROCEDIMIENTO', 'Cod. de Procediment');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'CPOSTAL', 'Codi Postal');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'DIRECCIONTELEMATICA', 'Adreça Telemàtica');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'DOMICILIO', 'Adreça Postal');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'EFECTOSDELSILENCIO', 'Efecte del Silenci Administratiu');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'ESTADOADM', 'Estat Administratiu');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'ESTADOINFO', 'Informació d''Estat');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'EXPRELACIONADOS', 'Expedients Relacionats');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'FAPERTURA', 'Data Obertura');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'FCIERRE', 'Data Tancament');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'FESTADO', 'Data d''Estat');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'FINICIOPLAZO', 'Data Inicio Termini');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'FORMATERMINACION', 'Forma Terminació');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'FREG', 'Data de Registre');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'FUNCIONACTIVIDAD', 'Funció/Activitat');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'HAYRECURSO', 'Recurs');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'IDDIRECCIONPOSTAL', 'Id. d''Adreça Postal');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'IDENTIDADTITULAR', 'Identitat');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'ID_PCD', 'Id. de Procediment');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'IDPROCESO', 'Id. de Procés');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'IDSECCIONINICIADORA', 'de Secció Iniciadora');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'IDTITULAR', 'Id. d''Interessat');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'IDUNIDADTRAMITADORA', 'Id. de Secció Tramitadora');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'LBL_CONFIRMADA', 'Verificada');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'LBL_LIBRE', 'Lliure');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'LBL_NO_VALIDADO', 'No Validat');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'LBL_VALIDADO', 'Validat');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'LOCALIZACION', 'Localització');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'MATERIAS', 'Matèries');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'MUNICIPIO', 'Municipi');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'NIFCIFTITULAR', 'NIF/CIF');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'NOMBREPROCEDIMIENTO', 'Procediment');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'NREG', 'Nº de Registre');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'NUMEXP', 'Nº Expedient');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'NVERSION', 'Versió');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'OBSERVACIONES', 'Observacions');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'PALABRASCLAVE', 'Paraules Clau');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'PLAZO', 'Termini de Resolució');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'POBLACION', 'Població');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'REFERENCIA_INTERNA', 'Referència Interna');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'REGIONPAIS', 'Regió/País');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'ROLTITULAR', 'Relació');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'SECCIONINICIADORA', 'Secció Iniciadora');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'SEP_DIRECCIONES', 'ADREÇA NOTIFICACIÓ');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'SEP_INTERESADO_PRINCIPAL', 'INTERESSAT PRINCIPAL');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'SEP_TERRITORIO', 'TERRITORI');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'SERVPRESACTUACIONES', 'Serv. Pres. Actuacions');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'SPAC_EXPEDIENTES', 'Expedient');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'SPAC_EXPEDIENTES_TAB_DATOS_EXPEDIENTE', 'Dades de l''Expedient');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'SPAC_EXPEDIENTES_TAB_INFORMACION_ADICIONAL', 'Informació addicional');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'TFNOFIJO', 'Tfn. Fix');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'TFNOMOVIL', 'Tfn. Mòbil');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'TIPODEDOCUMENTAL', 'Tipus de Documental');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'TIPODIRECCIONINTERESADO', 'Tipus Adreça Notificació');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'TIPOPERSONA', 'Tipus de Persona');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'UPLAZO', 'Unitat del Termini de Resolució');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 1, 'ca', 'UTRAMITADORA', 'Secció Tramitadora');

-- Entidad DOCUMENTOS
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'AUTOR', 'Autor');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'AUTOR_INFO', 'Informació de l''Autor');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'BLOQUEO', 'Estat de Bloqueig');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'DESCRIPCION', 'Descripció');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'DESTINO', 'Destinació');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'DESTINO_ID', 'Id. de Destinació');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'DESTINO_TIPO', 'Tipus de la Destinació');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'DOCUMENTO', 'Document');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'ESTADO', 'Estat');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'ESTADOFIRMA', 'Estat de Signatura');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'ESTADONOTIFICACION', 'Estat Notificació');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'EXTENSION', 'Extensió');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'EXTENSION_RDE', 'Extensió documento signat');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'FAPROBACION', 'Data Aprovació');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'FDOC', 'Data Generació');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'FFIRMA', 'Data Estat de Signatura');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'FNOTIFICACION', 'Data Notificació');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'FREG', 'Data de Registre');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'ID_ENTIDAD', 'Id. Entitat');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'ID_FASE', 'Id. de Fase');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'ID_FASE_PCD', 'Id. de Fase en el Procediment');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'ID_NOTIFICACION', 'Id. de Notificació');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'ID_PLANTILLA', 'Id. de Plantilla');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'ID_REG_ENTIDAD', 'Id. Reg. Entitat');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'ID_TPDOC', 'Id. de Tipus de Document');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'ID_TRAMITE', 'Id. de Tràmit');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'ID_TRAMITE_PCD', 'Id. de Tràmit en el Procediment');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'INFOPAG', 'Referencia Gestor Documental');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'INFOPAG_RDE', 'Referencia Gestor Documental de Documents Electrònics');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'NOMBRE', 'Nom');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'NREG', 'Nº de Registre');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'ORIGEN', 'Origen');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'ORIGEN_ID', 'Id. de Origen');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'ORIGEN_TIPO', 'Tipus de l''Origen');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'REPOSITORIO', 'Repositori');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'SPAC_DT_DOCUMENTOS', 'Document');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 2, 'ca', 'TP_REG', 'Tipus de Registre');

-- Entidad PARTICIPANTES
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'CAUT', 'Regió/País');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'C_POSTAL', 'Codi Postal');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'DIRECCIONTELEMATICA', 'Adreça Telemàtica');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'DIRNOT', 'Adreça Postal');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'EMAIL', 'E-Mail');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'IDDIRECCIONPOSTAL', 'Id. de Adreça Postal');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'ID_EXT', 'Referència Externa');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'IMAGEN', 'user');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'LBL_CONFIRMADA', 'Verificada');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'LBL_LIBRE', 'Lliure');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'LBL_NO_VALIDADO', 'No Validat');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'LBL_VALIDADO', 'Validat');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'LISTA', 'LLISTAT DE PARTICIPANTS');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'LOCALIDAD', 'Ciutat');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'NDOC', 'NIF/CIF');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'NOMBRE', 'Nom');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'NUMDOCUMENTO', 'Nº Document');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'ROL', 'Relació');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'SEP_DIRECCIONES', 'ADREÇA NOTIFICACIÓ');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'SPAC_DT_INTERVINIENTES', 'Participants');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'SPAC_DT_INTERVINIENTES_TAB_DATOS_PARTICIPANTE', 'Dades de Participant');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'TFNO_FIJO', 'Tfn. Fix');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'TFNO_MOVIL', 'Tfno. Mòbil');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'TIPO', 'Tipus');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'TIPO_DIRECCION', 'Tipus Adreça Notificació');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 3, 'ca', 'TIPO_PERSONA', 'Tipus de Persona');

-- Entidad TRAMITES
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'COD_ACTO', 'Cod. d''Acte');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'DESCRIPCION', 'Descripció');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'ESTADO', 'Estat');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'ESTADO_INFO', 'Informació d''Estat');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'FASE_PCD', 'Fase en el Procediment');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'FECHA_CIERRE', 'Data de Tancament');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'FECHA_FIN', 'Data de Finalització');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'FECHA_INICIO', 'Data de Creació');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'FECHA_INICIO_PLAZO', 'Data Inicio Termini');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'FECHA_LIMITE', 'Data Alarma');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'ID_FASE_EXP', 'Id. de la Fase Activa');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'ID_FASE_PCD', 'Id. de la Fase en el Procediment');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'ID_SUBPROCESO', 'Id. de Subproceso');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'ID_TRAM_CTL', 'Id. del Tràmit al Catàleg');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'ID_TRAM_EXP', 'Id. del Tràmit Actiu');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'ID_TRAM_PCD', 'Id. del Tràmit en el Procediment');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'INICIADO', 'Iniciat');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'NOMBRE', 'Tràmit');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'NUM_ACTO', 'Nº d''Acte');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'OBSERVACIONES', 'Observacions');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'PLAZO', 'Termini');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'SPAC_DT_TRAMITES', 'Tràmit');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'TRAMITE', 'TRÀMIT');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'TRAMRESPONSABLE', 'Tramitador Responsable');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'UND_RESP', 'Departament Responsable');
INSERT INTO spac_ct_entidades_resources (id, id_ent, idioma, clave, valor) VALUES (nextval('spac_sq_id_entidadesresources'), 7, 'ca', 'UPLAZO', 'Uts. Termini');
