
DECLARE

id2 number;
stmt varchar (512);
BEGIN
execute immediate 'SELECT id from spac_ct_jerarquias where nombre=''' || 'Sesion-Propuesta' || '''' into id2;
EXECUTE IMMEDIATE 'CREATE OR REPLACE VIEW SPAC_CT_JERARQUIA_' || id2 || ' AS SELECT SEC_PROPUESTA_SESION.ID AS id, SEC_SESION_PLENARIA.ID AS id_padre ,  SEC_PROPUESTA_SESION.ID_PROPUESTA AS id_hija FROM SEC_PROPUESTA_SESION , SEC_SESION_PLENARIA WHERE SEC_SESION_PLENARIA.NUMEXP=SEC_PROPUESTA_SESION.NUMEXP';

---Actualización de las vistas
execute immediate '
CREATE OR REPLACE VIEW SEC_TBL_VIEW_PROPUESTA (ID, VALOR, SUSTITUTO, VIGENTE, ORDEN) AS
SELECT  id , CAST ( (id) AS CHARACTER VARYING (256)) ,
 CAST(( titulo) AS CHARACTER VARYING (256)), CAST (1 AS NUMERIC(1,0)) , CAST( (id) AS NUMERIC(10,0))
 FROM SEC_PROPUESTA';



execute immediate 'CREATE OR REPLACE VIEW SEC_TBL_VIEW_SESION_P (ID, VALOR, SUSTITUTO, VIGENTE, ORDEN) AS
SELECT  id , CAST ( (id) AS CHARACTER VARYING (256)) ,
 CAST(( NUMEXP) AS CHARACTER VARYING (30)), CAST (1 AS NUMERIC(1,0)) , CAST( (id) AS NUMERIC(10,0))
 FROM SEC_SESION_PLENARIA';

END;
/









