--
-- SECUENCIAS
--
DROP SEQUENCE SPAC_SQ_DATOS_TARJETA_MINUS;
DROP SEQUENCE SPAC_SQ_FORMA_ADJUDICACION;
DROP SEQUENCE SPAC_SQ_ID_ACTIVIDAD_CLASIFICA;
DROP SEQUENCE SPAC_SQ_ID_ACTIVIDAD_NO_CLASIF;
DROP SEQUENCE SPAC_SQ_ID_CAMB_TITULAR_LA;
DROP SEQUENCE SPAC_SQ_ID_CERT_URBANISTICO;
DROP SEQUENCE SPAC_SQ_ID_CLASIFICACION_ACTIV;
DROP SEQUENCE SPAC_SQ_ID_CONTRATO;
DROP SEQUENCE SPAC_SQ_ID_LOTES;
DROP SEQUENCE SPAC_SQ_ID_OBRA_MENOR;
DROP SEQUENCE SPAC_SQ_ID_OFERTA;
DROP SEQUENCE SPAC_SQ_ID_SANCION;
DROP SEQUENCE SPAC_SQ_ID_VADO;
DROP SEQUENCE SPAC_SQ_ID_VLDTBL_SAN_CALIFICA;
DROP SEQUENCE SPAC_SQ_ID_VLDTBL_SAN_GRADO;
DROP SEQUENCE SPAC_SQ_REBAJE_ACERA;
DROP SEQUENCE SPAC_SQ_RECLAMACION;
DROP SEQUENCE SPAC_SQ_TIPO_CONTRATO;
DROP SEQUENCE SPAC_SQ_TIPO_TECNICO;
DROP SEQUENCE SPAC_SQ_TIPO_VADO;
DROP SEQUENCE SPAC_SQ_VISTO_BUENO;
DROP SEQUENCE SPAC_SQ_VLDTBL_CALIF_SUELO;
DROP SEQUENCE SPAC_SQ_VLDTBL_CLASIF_SUELO;
DROP SEQUENCE SPAC_SQ_VLDTBL_TIPO_DESTI;
DROP SEQUENCE SPAC_SQ_VLDTBL_TIPO_RECLAM;
DROP SEQUENCE SPAC_SQ_VLDTBL_TIPO_TARJETA;


--
-- TABLAS
--
DROP TABLE ACTIVIDAD_CLASIFICADA;
DROP TABLE ACTIVIDAD_NO_CLASIFICADA;
DROP TABLE CAMB_TITULAR_LA;
DROP TABLE CERT_URBANISTICO;
DROP TABLE CLASIFICACION_ACTIVIDADES;
DROP TABLE CONTRATO;
DROP TABLE DATOS_TARJETA_MINUS;
DROP TABLE FORMA_ADJUDICACION;
DROP TABLE LOTES;
DROP TABLE OBRA_MENOR;
DROP TABLE OFERTA;
DROP TABLE REBAJE_ACERA;
DROP TABLE RECLAMACION;
DROP TABLE SANCION;
DROP TABLE TIPO_CONTRATO;
DROP TABLE TIPO_TECNICO;
DROP TABLE TIPO_VADO;
DROP TABLE VADO;
DROP TABLE VISTO_BUENO;
DROP TABLE VLDTBL_CALIF_SUELO;
DROP TABLE VLDTBL_CLASIF_SUELO;
DROP TABLE VLDTBL_SAN_CALIFICACION;
DROP TABLE VLDTBL_SAN_GRADO;
DROP TABLE VLDTBL_TIPO_DESTI;
DROP TABLE VLDTBL_TIPO_RECLAM;
DROP TABLE VLDTBL_TIPO_TARJETA;
