--
-- SECUENCIAS
--
DROP SEQUENCE SGL_SQ_ID_OBRAS_MENORES;
DROP SEQUENCE SGQ_SQ_ID_QUEJAS;
DROP SEQUENCE SGS_SQ_ID_SUBVENCIONES;
-- Secuencias para las tablas de validacion
DROP SEQUENCE SPAC_SQ_SPAC_TBL_010;
DROP SEQUENCE SPAC_SQ_SPAC_TBL_011;
DROP SEQUENCE SPAC_SQ_SPAC_TBL_012;
DROP SEQUENCE SPAC_SQ_SPAC_TBL_013;


--
-- TABLAS
--
DROP TABLE SGL_OBRAS_MENORES;
DROP TABLE SGQ_QUEJAS;
DROP TABLE SGS_SUBVENCIONES;
DROP TABLE SPAC_TBL_010;
DROP TABLE SPAC_TBL_011;
DROP TABLE SPAC_TBL_012;
DROP TABLE SPAC_TBL_013;
