--
-- Secuencias para las tablas internas
--
CREATE SEQUENCE SPAC_SQ_ID_ANOTACIONES				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_AVISOS_ELECTRONICOS		START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_CTAPLICACIONES			START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_CTENTIDADES				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_CTFASES					START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_CTFRMBUSQUEDA			START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_CTFRMBUSQUEDA_ORG		START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_CTFSTR					START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_CTOS_FIRMA				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_CTOS_FIRMA_CABECERA		START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_CTOS_FIRMA_DETALLE		START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_CTOS_FIRMA_INSTANCE		START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_CTPCDORG					START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_CTREGLAS					START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_CTTPDOC					START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_CTTRAMITES				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_CTTRTD					START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_DOCOBJ					START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_DTDOCUMENTOS				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_DTINTERVINIENTES			START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_DTTRAMITES				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_ENTIDADESRESOURCES		START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_EXP_RELACIONADO			START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_EXPEDIENTES				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_REGISTROSES				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_FASES					START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_HITOS					START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_INFOTRAMITE				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_INFOSISTEMA				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_P_PLANTILLAS				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_PENTIDADES				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_PEVENTOS					START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
--CREATE SEQUENCE SPAC_SQ_ID_PFASES					START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_PFLUJOS					START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_PFRMFASES				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_PFRMTRAMITES				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_PFSTD					START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_PNODOS					START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_PPLANTILLAS				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_PPLAZOS					START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_PPROCEDIMIENTOS			START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_PROCESOS					START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_PTRAMITES				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_PDEPTRAMITES				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_SINCNODOS				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_SSFUNCIONES				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_SSPERMISOS				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_SSSUPERV					START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_SVARS					START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_TRAMITACION_AGRUPADA		START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_TRAMTCS_GROUP_EXPS 			START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_TRAMITES 				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_VARS 					START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_PCTOSFIRMA 				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_CALENDARIOS				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_SSSUSTITUCION			START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_SSFECHSUSTITUCIONES		START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_SSSUSTITUCIONFECHA		START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_CTINFORMES				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_CTINFORMES_ORG			START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_CTJERARQUIAS				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_AYUDAS 					START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;


--
-- Secuencias para las tablas de validacion
--
CREATE SEQUENCE SPAC_SQ_SPAC_TBL_001				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_SPAC_TBL_002				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_SPAC_TBL_003				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_SPAC_TBL_004				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_SPAC_TBL_005				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_SPAC_TBL_006				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_SPAC_TBL_007				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_SPAC_TBL_008				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_SPAC_TBL_009				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_SPAC_VLDTBL_ACTS_FUNCS 		START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_SPAC_VLDTBL_EFEC_SLNC 		START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_SPAC_VLDTBL_FORMA_INIC 		START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_SPAC_VLDTBL_MATS_COMP 		START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_SPAC_VLDTBL_RECURSOS 		START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_SPAC_VLDTBL_SIST_PROD 		START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_SPAC_VLDTBL_SIT_TLM			START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_SPAC_VLDTBL_TIPOREG			START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_SPAC_VLDTBL_TIPOS_DOCS		START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_SPAC_VLDTBL_TIPOS_TRAM		START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_VLDTBL_TIPO_NOTIF			START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;


--
-- Secuencias para el publicador
--
CREATE SEQUENCE PUB_SQ_ID_ACCIONES 					START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE PUB_SQ_ID_APLICACIONES_HITOS 		START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE PUB_SQ_ID_CONDICIONES 				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE PUB_SQ_ID_REGLAS 					START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
