ALTER session SET nls_length_semantics = CHAR;

--
-- TABLAS DEL PUBLICADOR
--
CREATE TABLE PUB_ACCIONES (
    ID NUMBER NOT NULL,
    NOMBRE VARCHAR2(255 CHAR),
    CLASE VARCHAR2(255 CHAR),
    ACTIVA NUMBER(3) DEFAULT 0,
    DESCRIPCION VARCHAR2(255 CHAR),
    TIPO NUMBER(3) DEFAULT 1
);

CREATE TABLE PUB_APLICACIONES_HITOS (
    ID NUMBER NOT NULL,
    NOMBRE VARCHAR2(255 CHAR),
    ACTIVA NUMBER(3)
);

CREATE TABLE PUB_CONDICIONES (
    ID NUMBER NOT NULL,
    NOMBRE VARCHAR2(255 CHAR),
    CLASE VARCHAR2(255 CHAR),
    DESCRIPCION VARCHAR2(255 CHAR)
);

CREATE TABLE PUB_ERRORES (
    ID_HITO NUMBER NOT NULL,
    ID_APLICACION NUMBER NOT NULL,
    ID_SISTEMA VARCHAR2(32 CHAR) NOT NULL,
    ID_OBJETO VARCHAR2(64 CHAR) NOT NULL,
    DESCRIPCION VARCHAR2(255 CHAR),
    ID_ERROR NUMBER
);

CREATE TABLE PUB_HITOS_ACTIVOS (
    ID_HITO NUMBER NOT NULL,
    ID_PCD NUMBER,
    ID_FASE NUMBER,
    ID_TRAMITE NUMBER,
    TIPO_DOC NUMBER,
    ID_OBJETO VARCHAR2(64 CHAR),
    ID_EVENTO NUMBER,
    ESTADO NUMBER(3),
    ID_APLICACION NUMBER NOT NULL,
    IP_MAQUINA VARCHAR2(15 CHAR),
    FECHA DATE ,
    ID_SISTEMA VARCHAR2(32 CHAR) NOT NULL,
    INFO_AUX CLOB,
    ID_INFO NUMBER
);

CREATE TABLE PUB_REGLAS (
    ID NUMBER NOT NULL,
    ID_PCD NUMBER,
    ID_FASE NUMBER,
    ID_TRAMITE NUMBER,
    TIPO_DOC NUMBER,
    ID_EVENTO NUMBER,
    ID_ACCION NUMBER,
    ID_CONDICION NUMBER,
    ATRIBUTOS CLOB,
    ID_APLICACION NUMBER,
    ORDEN NUMBER,
    ID_INFO NUMBER
);

CREATE TABLE PUB_ULTIMO_HITO_TRATADO (
    ID_SISTEMA VARCHAR2(32 CHAR) NOT NULL,
    ID_HITO NUMBER
);


--
-- TABLAS INTERNAS DEL TRAMITADOR
--
CREATE TABLE SPAC_ANOTACIONES (
    ID NUMBER NOT NULL,
    ID_EXP NUMBER,
    ID_FASE NUMBER,
    ID_TRAMITE NUMBER,
    FECHA DATE ,
    AUTOR VARCHAR2(250 CHAR),
    CLOB VARCHAR2(4000 CHAR)
);

CREATE TABLE SPAC_AVISOS_ELECTRONICOS (
    ID_AVISO NUMBER NOT NULL,
    ID_PROC NUMBER,
    ID_RESP NUMBER,
    TIPO_DESTINATARIO NUMBER(3),
    ID_DESTINATARIO NUMBER,
    FECHA DATE,
    ID_EXPEDIENTE VARCHAR2(64 CHAR),
    ID_FASE NUMBER,
    ID_TRAMITE NUMBER,
    ID_FASE_PCD NUMBER,
    ID_TRAMITE_PCD NUMBER,
    ESTADO_AVISO NUMBER(3),
    MENSAJE VARCHAR2(254 CHAR),
    TIPO_AVISO VARCHAR2(64 CHAR),
    ID_MPROC NUMBER,
    UID_RESP VARCHAR2(250 CHAR),
    UID_DESTINATARIO VARCHAR2(250 CHAR)
);

CREATE TABLE SPAC_CALENDARIOS (
  ID NUMBER NOT NULL, -- IDENTIFICADOR UNICO DEL CALENDARIO
  CALENDARIO CLOB, -- CALENDARIOS DE FESTIVOS
  NOMBRE VARCHAR2(256 CHAR)
);

CREATE TABLE SPAC_CT_APLICACIONES (
    ID NUMBER NOT NULL,
    NOMBRE VARCHAR2(100 CHAR),
    DESCRIPCION VARCHAR2(250 CHAR),
    CLASE VARCHAR2(250 CHAR),
    PAGINA VARCHAR2(250 CHAR),
    PARAMETROS CLOB,
    FORMATEADOR VARCHAR2(250 CHAR),
	XML_FORMATEADOR CLOB,
    FRM_JSP CLOB,
    FRM_VERSION NUMBER(3),
    ENT_PRINCIPAL_ID NUMBER,
    ENT_PRINCIPAL_NOMBRE VARCHAR2(100 CHAR),
    DOCUMENTOS VARCHAR2(2 CHAR) DEFAULT 'NO'
);

CREATE TABLE SPAC_CT_ENTIDADES (
    ID NUMBER NOT NULL,
    TIPO NUMBER(3),
    NOMBRE VARCHAR2(100 CHAR),
    CAMPO_PK VARCHAR2(100 CHAR),
    CAMPO_NUMEXP VARCHAR2(100 CHAR),
    SCHEMA_EXPR VARCHAR2(100 CHAR),
    FRM_EDIT NUMBER,
    DESCRIPCION VARCHAR2(250 CHAR),
    SEC_PK VARCHAR2(100 CHAR),
    DEFINICION CLOB,
    FRM_JSP CLOB,
    FECHA DATE
);

CREATE TABLE SPAC_CT_ENTIDADES_RESOURCES (
    ID NUMBER NOT NULL,
    ID_ENT NUMBER NOT NULL,
    IDIOMA VARCHAR2(5 CHAR),
    CLAVE VARCHAR2(250 CHAR),
    VALOR VARCHAR2(250 CHAR)
);

CREATE TABLE SPAC_CT_FASES (
    ID NUMBER NOT NULL,
    NOMBRE VARCHAR2(250 CHAR),
    ORDEN NUMBER,
    COD_FASE VARCHAR2(16 CHAR),
    FALTA DATE ,
    DESCRIPCION VARCHAR2(1024 CHAR),
    OBSERVACIONES VARCHAR2(500 CHAR),
    AUTOR VARCHAR2(64 CHAR)
);

CREATE TABLE SPAC_CT_FRMBUSQUEDA (
    ID NUMBER NOT NULL,
    DESCRIPCION VARCHAR2(250 CHAR),
    AUTOR VARCHAR2(100 CHAR),
    FECHA DATE ,
    FRM_BSQ CLOB,
    TIPO NUMBER(3)
);

CREATE TABLE SPAC_CT_FRMBUSQUEDA_ORG (
  ID NUMBER NOT NULL,
  ID_SEARCHFRM NUMBER,
  UID_USR VARCHAR2(32 CHAR)
);

CREATE TABLE SPAC_CT_FSTR (
    ID NUMBER NOT NULL,
    ID_FASE NUMBER,
    ID_TRAMITE NUMBER
);

CREATE TABLE SPAC_CT_PCDORG (
    ID NUMBER NOT NULL,
    COD_PCD VARCHAR2(100 CHAR) NOT NULL,
    ID_UNIDAD_TRAMITADORA VARCHAR2(250 CHAR) NOT NULL,
    FECHA_INI_PROD DATE,
    ORDEN NUMBER
);

CREATE TABLE SPAC_CT_PROCEDIMIENTOS (
    ID NUMBER NOT NULL,
    COD_PCD VARCHAR2(100 CHAR),
    NOMBRE VARCHAR2(250 CHAR),
    ID_PADRE NUMBER,
    TITULO VARCHAR2(254 CHAR),
    OBJETO VARCHAR2(254 CHAR),
    ASUNTO VARCHAR2(512 CHAR),
    ACT_FUNC VARCHAR2(2 CHAR),
    MTRS_COMP VARCHAR2(2 CHAR),
    SIT_TLM VARCHAR2(2 CHAR),
    URL VARCHAR2(254 CHAR),
    INTERESADO VARCHAR2(64 CHAR),
    TP_REL VARCHAR2(4 CHAR),
    ORG_RSLTR VARCHAR2(80 CHAR),
    FORMA_INIC VARCHAR2(1 CHAR),
    PLZ_RESOL NUMBER,
    UNID_PLZ VARCHAR2(1 CHAR),
    FINICIO DATE ,
    FFIN DATE ,
    EFEC_SILEN VARCHAR2(1 CHAR),
    FIN_VIA_ADMIN VARCHAR2(2 CHAR),
    RECURSOS VARCHAR2(500 CHAR),
    FCATALOG DATE ,
    AUTOR VARCHAR2(64 CHAR),
    ESTADO VARCHAR2(1 CHAR),
    NVERSION NUMBER(3),
    OBSERVACIONES VARCHAR2(500 CHAR),
    LUGAR_PRESENT VARCHAR2(500 CHAR),
    CNDS_ECNMCS VARCHAR2(500 CHAR),
    INGRESOS VARCHAR2(1024 CHAR),
    F_CBR_PGO VARCHAR2(1024 CHAR),
    INFR_SANC VARCHAR2(1024 CHAR),
    CALENDARIO VARCHAR2(1024 CHAR),
    DSCR_TRAM VARCHAR2(1024 CHAR),
    NORMATIVA VARCHAR2(1024 CHAR),
    CND_PARTICIP VARCHAR2(500 CHAR),
    DOCUMENTACION CLOB,
    GRUPOS_DELEGACION VARCHAR2(1000 CHAR),
    COD_SISTEMA_PRODUCTOR VARCHAR2(2 CHAR) DEFAULT '00',
    MAPEO_RT CLOB
);

CREATE TABLE SPAC_CT_REGLAS (
    ID NUMBER NOT NULL,
    NOMBRE VARCHAR2(100 CHAR),
    DESCRIPCION VARCHAR2(250 CHAR),
    CLASE VARCHAR2(250 CHAR),
    TIPO NUMBER(3)
);

CREATE TABLE SPAC_CT_TPDOC (
    ID NUMBER NOT NULL,
    NOMBRE VARCHAR2(100 CHAR),
    COD_TPDOC VARCHAR2(16 CHAR),
    TIPO VARCHAR2(64 CHAR),
    AUTOR VARCHAR2(64 CHAR),
    DESCRIPCION VARCHAR2(1024 CHAR),
    FECHA DATE ,
    TIPOREG VARCHAR2(64 CHAR),
    OBSERVACIONES VARCHAR2(512 CHAR)
);

CREATE TABLE SPAC_CT_TRAMITES (
    ID NUMBER NOT NULL,
    NOMBRE VARCHAR2(250 CHAR),
    COD_TRAM VARCHAR2(16 CHAR),
    DESCRIPCION VARCHAR2(1024 CHAR),
    TIPO VARCHAR2(32 CHAR),
    ORDENACION VARCHAR2(2 CHAR),
    OBSERVACIONES VARCHAR2(512 CHAR),
    FCREACION DATE ,
    AUTOR VARCHAR2(64 CHAR),
    ID_SUBPROCESO NUMBER
);

CREATE TABLE SPAC_CT_TRTD (
    ID NUMBER NOT NULL,
    ID_TRAMITE NUMBER,
    ID_TPDOC NUMBER
);

CREATE TABLE SPAC_CTOS_FIRMA (
    ID NUMBER NOT NULL,
    ID_INSTANCIA_CIRCUITO NUMBER,
    FECHA DATE,
    ID_DOCUMENTO NUMBER,
    ID_CIRCUITO NUMBER,
    ID_PASO NUMBER,
    ID_FIRMANTE VARCHAR2(128 CHAR),
    NOMBRE_FIRMANTE VARCHAR2(32 CHAR),
    ESTADO NUMBER(3)
);

CREATE TABLE SPAC_CTOS_FIRMA_CABECERA (
    ID_CIRCUITO NUMBER NOT NULL,
    NUM_PASOS NUMBER(3),
    DESCRIPCION VARCHAR2(256 CHAR),
	TIPO NUMBER,
	SISTEMA VARCHAR2(64 CHAR),
	SECUENCIA VARCHAR2(64 CHAR),
	APLICACION VARCHAR2(64 CHAR)
);

CREATE TABLE SPAC_P_CTOSFIRMA (
    ID NUMBER NOT NULL,
    ID_CIRCUITO NUMBER,
    ID_PCD NUMBER
);

CREATE TABLE SPAC_CTOS_FIRMA_DETALLE (
    ID NUMBER NOT NULL,
    ID_CIRCUITO NUMBER,
    ID_PASO NUMBER,
    ID_FIRMANTE VARCHAR2(128 CHAR),
    NOMBRE_FIRMANTE VARCHAR2(32 CHAR),
	TIPO_NOTIF VARCHAR2(2 CHAR),
	DIR_NOTIF VARCHAR2(64 CHAR),
	TIPO_FIRMANTE VARCHAR2(16 CHAR)
);

CREATE TABLE SPAC_DOCOBJ (
    ID NUMBER NOT NULL,
    TAM NUMBER,
    OBJ BLOB,
    MIMETYPE VARCHAR2(40 CHAR)
);

CREATE TABLE SPAC_DT_DOCUMENTOS (
    ID NUMBER NOT NULL,
    NUMEXP VARCHAR2(30 CHAR),
    FDOC DATE ,
    NOMBRE VARCHAR2(100 CHAR),
    AUTOR VARCHAR2(250 CHAR),
    ID_FASE NUMBER,
    ID_TRAMITE NUMBER,
    ID_TPDOC NUMBER,
    TP_REG VARCHAR2(16 CHAR),
    NREG VARCHAR2(64 CHAR),
    FREG DATE ,
    INFOPAG VARCHAR2(100 CHAR),
    ID_FASE_PCD NUMBER,
    ID_TRAMITE_PCD NUMBER,
    ESTADO VARCHAR2(16 CHAR),
    ORIGEN VARCHAR2(250 CHAR),
    DESCRIPCION VARCHAR2(250 CHAR),
    ORIGEN_ID VARCHAR2(20 CHAR),
    DESTINO VARCHAR2(250 CHAR),
    AUTOR_INFO VARCHAR2(250 CHAR),
    ESTADOFIRMA VARCHAR2(2 CHAR),
	ID_NOTIFICACION VARCHAR2(64 CHAR),
    ESTADONOTIFICACION VARCHAR2(2 CHAR),
    DESTINO_ID VARCHAR2(20 CHAR),
    FNOTIFICACION DATE ,
    FAPROBACION DATE ,
    ORIGEN_TIPO VARCHAR2(1 CHAR),
    DESTINO_TIPO VARCHAR2(1 CHAR),
    ID_PLANTILLA NUMBER,
    BLOQUEO CHARACTER(2),
    REPOSITORIO VARCHAR2(8 CHAR),
    EXTENSION VARCHAR2(64 CHAR),
    FFIRMA DATE ,
    INFOPAG_RDE VARCHAR2(256 CHAR),
    EXTENSION_RDE VARCHAR2(64 CHAR),
	ID_REG_ENTIDAD NUMBER,
	ID_ENTIDAD NUMBER,
	COD_COTEJO VARCHAR2(50 CHAR),
	ID_PROCESO_FIRMA CLOB,
    ID_CIRCUITO NUMBER,
    HASH VARCHAR2(512 CHAR),
    FUNCION_HASH VARCHAR2(128 CHAR)
);

CREATE TABLE SPAC_DT_INTERVINIENTES (
    ID NUMBER NOT NULL,
    ID_EXT VARCHAR2(32 CHAR),
    NUMEXP VARCHAR2(30 CHAR),
    ROL VARCHAR2(4 CHAR),
    TIPO NUMBER(3),
    TIPO_PERSONA VARCHAR2(1 CHAR),
    NDOC VARCHAR2(12 CHAR),
    NOMBRE VARCHAR2(250 CHAR),
    IDDIRECCIONPOSTAL VARCHAR2(32 CHAR),
    DIRNOT VARCHAR2(250 CHAR),
    EMAIL VARCHAR2(250 CHAR),
    C_POSTAL VARCHAR2(10 CHAR),
    LOCALIDAD VARCHAR2(150 CHAR),
    CAUT VARCHAR2(150 CHAR),
    TFNO_FIJO VARCHAR2(32 CHAR),
    TFNO_MOVIL VARCHAR2(32 CHAR),
    TIPO_DIRECCION CHARACTER(1),
    DIRECCIONTELEMATICA VARCHAR2(60 CHAR)
);

CREATE TABLE SPAC_DT_TRAMITES (
    ID NUMBER NOT NULL,
    NUMEXP VARCHAR2(30 CHAR),
    NOMBRE VARCHAR2(250 CHAR),
    ESTADO NUMBER(3),
    ID_TRAM_PCD NUMBER,
    ID_FASE_PCD NUMBER,
    ID_FASE_EXP NUMBER,
    ID_TRAM_EXP NUMBER,
    ID_TRAM_CTL NUMBER,
    NUM_ACTO VARCHAR2(16 CHAR),
    COD_ACTO VARCHAR2(16 CHAR),
    ESTADO_INFO VARCHAR2(100 CHAR),
    FECHA_INICIO DATE ,
    FECHA_CIERRE DATE ,
    FECHA_LIMITE DATE ,
    FECHA_FIN DATE ,
    FECHA_INICIO_PLAZO DATE ,
    PLAZO NUMBER,
    UPLAZO VARCHAR2(1 CHAR),
    OBSERVACIONES VARCHAR2(254 CHAR),
    DESCRIPCION VARCHAR2(100 CHAR),
    UND_RESP VARCHAR2(250 CHAR),
    FASE_PCD VARCHAR2(250 CHAR),
    ID_SUBPROCESO NUMBER,
    ID_RESP_CLOSED VARCHAR2(250 CHAR)
);

CREATE TABLE SPAC_REGISTROS_ES (
    ID NUMBER NOT NULL,
    NUMEXP VARCHAR2(30 CHAR),
    NREG VARCHAR2(32 CHAR),
    FREG DATE,
    ASUNTO CLOB,
    ID_INTERESADO VARCHAR2(32 CHAR),
    INTERESADO VARCHAR2(128 CHAR),
    TP_REG VARCHAR2(16 CHAR),
    ID_TRAMITE NUMBER,
    ORIGINO_EXPEDIENTE VARCHAR2(2 CHAR)
);

CREATE TABLE SPAC_EXP_RELACIONADOS (
    ID NUMBER NOT NULL,
    NUMEXP_PADRE VARCHAR2(30 CHAR) NOT NULL,
    NUMEXP_HIJO VARCHAR2(30 CHAR) NOT NULL,
    RELACION VARCHAR2(64 CHAR)
);

CREATE TABLE SPAC_EXPEDIENTES (
    ID NUMBER NOT NULL,
    ID_PCD NUMBER,
    NUMEXP VARCHAR2(30 CHAR),
    REFERENCIA_INTERNA VARCHAR2(30 CHAR),
    NREG VARCHAR2(64 CHAR),
    FREG DATE ,
    ESTADOINFO VARCHAR2(128 CHAR),
    FESTADO DATE ,
    NIFCIFTITULAR VARCHAR2(16 CHAR),
    IDTITULAR VARCHAR2(32 CHAR),
    IDDIRECCIONPOSTAL VARCHAR2(32 CHAR),
    DOMICILIO VARCHAR2(128 CHAR),
    CIUDAD VARCHAR2(64 CHAR),
    REGIONPAIS VARCHAR2(64 CHAR),
    CPOSTAL VARCHAR2(5 CHAR),
    IDENTIDADTITULAR VARCHAR2(128 CHAR),
    TIPOPERSONA VARCHAR2(1 CHAR),
    ROLTITULAR VARCHAR2(4 CHAR),
    ASUNTO VARCHAR2(512 CHAR),
    FINICIOPLAZO DATE ,
    POBLACION VARCHAR2(64 CHAR),
    MUNICIPIO VARCHAR2(64 CHAR),
    LOCALIZACION VARCHAR2(256 CHAR),
    EXPRELACIONADOS VARCHAR2(256 CHAR),
    CODPROCEDIMIENTO VARCHAR2(16 CHAR),
    NOMBREPROCEDIMIENTO VARCHAR2(128 CHAR),
    PLAZO NUMBER,
    UPLAZO VARCHAR2(1 CHAR),
    FORMATERMINACION VARCHAR2(1 CHAR),
    UTRAMITADORA VARCHAR2(256 CHAR),
    FUNCIONACTIVIDAD VARCHAR2(80 CHAR),
    MATERIAS VARCHAR2(2 CHAR),
    SERVPRESACTUACIONES VARCHAR2(128 CHAR),
    TIPODEDOCUMENTAL VARCHAR2(16 CHAR),
    PALABRASCLAVE VARCHAR2(64 CHAR),
    FCIERRE DATE ,
    ESTADOADM VARCHAR2(128 CHAR),
    HAYRECURSO VARCHAR2(2 CHAR),
    EFECTOSDELSILENCIO VARCHAR2(1 CHAR),
    FAPERTURA DATE ,
    OBSERVACIONES VARCHAR2(256 CHAR),
    IDUNIDADTRAMITADORA VARCHAR2(250 CHAR),
    IDPROCESO NUMBER,
    TIPODIRECCIONINTERESADO VARCHAR2(16 CHAR),
    NVERSION VARCHAR2(16 CHAR),
    IDSECCIONINICIADORA VARCHAR2(64 CHAR),
    SECCIONINICIADORA VARCHAR2(250 CHAR),
    TFNOFIJO VARCHAR2(32 CHAR),
    TFNOMOVIL VARCHAR2(32 CHAR),
    DIRECCIONTELEMATICA VARCHAR2(60 CHAR)
);

CREATE TABLE SPAC_FASES (
    ID NUMBER NOT NULL,
    ID_FASE_BPM VARCHAR2(64 CHAR),
    ID_EXP NUMBER,
    ID_PCD NUMBER,
    ID_FASE NUMBER,
    NUMEXP VARCHAR2(30 CHAR),
    FECHA_INICIO DATE,
    FECHA_LIMITE DATE,
    ESTADO NUMBER(3),
    OBSERVACIONES VARCHAR2(4000 CHAR),
    ID_RESP VARCHAR2(250 CHAR),
    RESP VARCHAR2 (250 CHAR),
    ID_RESP_SEC VARCHAR2(250 CHAR),
	RESP_SEC VARCHAR2(250 CHAR),
    ESTADO_PLAZO NUMBER,
    FECHA_INICIO_PLAZO DATE,
    NUM_DIAS_PLAZO NUMBER,
    ID_CALENDARIO NUMBER,
    TIPO NUMBER(1),
	ESTADO_ANTERIOR NUMBER(3)
);

CREATE TABLE SPAC_GESTION_APLICACIONES (
    ID NUMBER NOT NULL,
    NOMBRE_APLICACION_GESTION VARCHAR2(100 CHAR),
    ENLACE VARCHAR2(50 CHAR),
    CLSID VARCHAR2(50 CHAR),
    CODEBASE VARCHAR2(50 CHAR)
);

CREATE TABLE SPAC_GESTION_FASES (
    ID NUMBER NOT NULL,
    ID_PCD NUMBER NOT NULL,
    ID_FASE NUMBER,
    ID_APLICACION_GESTION NUMBER NOT NULL
);

CREATE TABLE SPAC_HITOS (
    ID NUMBER NOT NULL,
    ID_EXP NUMBER,
    ID_FASE NUMBER,
    ID_TRAMITE NUMBER,
    HITO NUMBER,
    FECHA DATE ,
    FECHA_LIMITE DATE ,
    INFO CLOB,
    AUTOR VARCHAR2(250 CHAR),
    DESCRIPCION VARCHAR2(250 CHAR),
    ID_INFO NUMBER
);

CREATE TABLE SPAC_INFOTRAMITE (
    ID NUMBER NOT NULL,
    NUMEXP VARCHAR2(30 CHAR),
    ID_TRAMITE NUMBER,
    ID_CT_TRAMITE NUMBER,
    ID_PCD NUMBER,
    ID_P_FASE NUMBER,
    INFO CLOB
);

CREATE TABLE SPAC_INFOSISTEMA (
	ID NUMBER NOT NULL,
  	CODIGO VARCHAR2 (16 CHAR) NOT NULL,
	VALOR VARCHAR2 (16 CHAR) NOT NULL,
	FECHA_ACTUALIZACION DATE NOT NULL
);

CREATE TABLE SPAC_P_BLP (
    ID NUMBER NOT NULL,
    NBYTES NUMBER,
    BLOQUE BLOB,
    MIMETYPE VARCHAR2(40 CHAR)
);

CREATE TABLE SPAC_P_ENTIDADES (
    ID NUMBER NOT NULL,
    ID_ENT NUMBER,
    ID_PCD NUMBER,
    TP_REL NUMBER,
    ORDEN NUMBER,
    FRM_EDIT NUMBER,
    FRM_READONLY NUMBER(1),
    ID_RULE_FRM NUMBER,
    ID_RULE_VISIBLE NUMBER
);

CREATE TABLE SPAC_P_EVENTOS (
    ID_OBJ NUMBER NOT NULL,
    TP_OBJ NUMBER NOT NULL,
    EVENTO NUMBER NOT NULL,
    ORDEN NUMBER NOT NULL,
    ID_REGLA NUMBER,
	CONDICION CLOB
);

CREATE TABLE SPAC_P_FASES (
    ID NUMBER NOT NULL,
    ID_CTFASE NUMBER,
    ID_PCD NUMBER,
    NOMBRE VARCHAR2(250 CHAR),
    ID_RESP VARCHAR2(250 CHAR),
    ID_RESP_SEC VARCHAR2(250 CHAR)
);

CREATE TABLE SPAC_P_FLUJOS (
    ID NUMBER NOT NULL,
    ID_PCD NUMBER,
    ID_ORIGEN NUMBER,
    ID_DESTINO NUMBER,
    ID_FLUJO_BPM VARCHAR2(64 CHAR)
);

CREATE TABLE SPAC_P_FRMFASES (
    ID NUMBER NOT NULL,
    ID_ENT NUMBER,
    ID_FASE NUMBER,
    FRM_EDIT NUMBER,
    FRM_READONLY NUMBER(1),
    ID_RULE_FRM NUMBER,
    ID_RULE_VISIBLE NUMBER
);

CREATE TABLE SPAC_P_FRMTRAMITES (
    ID NUMBER NOT NULL,
    ID_ENT NUMBER,
    ID_TRAMITE NUMBER,
    FRM_EDIT NUMBER,
    FRM_READONLY NUMBER(1),
    ID_RULE_FRM NUMBER,
    ID_RULE_VISIBLE NUMBER
);

CREATE TABLE SPAC_P_FSTD (
    ID NUMBER NOT NULL,
    ID_FASE NUMBER,
    ID_TPDOC NUMBER
);

CREATE TABLE SPAC_P_NODOS (
    ID NUMBER NOT NULL,
    ID_NODO_BPM VARCHAR2(64 CHAR),
    ID_PCD NUMBER,
    TIPO NUMBER,
    G_INFO VARCHAR2(4000 CHAR)
);

CREATE TABLE SPAC_P_PLANTDOC (
    ID NUMBER NOT NULL,
    ID_TPDOC NUMBER,
    FECHA DATE ,
    NOMBRE VARCHAR2(250 CHAR),
	COD_PLANT VARCHAR2(16 CHAR),
    EXPRESION VARCHAR2(2000 CHAR),
    MIMETYPE VARCHAR2(60 CHAR),
    PATH VARCHAR2(250 CHAR),
    ESTACION VARCHAR2(250 CHAR)
);

CREATE TABLE SPAC_P_PLANTILLAS (
    ID NUMBER NOT NULL,
    ID_P_PLANTDOC NUMBER,
    ID_PCD NUMBER
);

CREATE TABLE SPAC_P_PLAZOS (
    ID NUMBER NOT NULL,
    PLAZO VARCHAR2(250 CHAR)
);

CREATE TABLE SPAC_P_PROCEDIMIENTOS (
    ID NUMBER NOT NULL,
    ID_PCD_BPM VARCHAR2(64 CHAR),
    NVERSION NUMBER(3),
    NOMBRE VARCHAR2(250 CHAR),
    ESTADO NUMBER(3),
    ID_RESP VARCHAR2(250 CHAR),
    ID_RESP_SEC VARCHAR2(250 CHAR),
    ID_GROUP NUMBER,
    ID_CRT VARCHAR2(250 CHAR),
	NOMBRE_CRT VARCHAR2(250 CHAR),
    TS_CRT DATE,
    ID_UPD VARCHAR2(250 CHAR),
	NOMBRE_UPD VARCHAR2(250 CHAR),
    TS_UPD DATE,
    TIPO NUMBER(1) DEFAULT 1
);

CREATE TABLE SPAC_P_RELPLAZOS (
    ID NUMBER NOT NULL,
    TP_OBJ NUMBER NOT NULL,
    ID_OBJ NUMBER NOT NULL
);

CREATE TABLE SPAC_P_SINCNODO (
    ID NUMBER NOT NULL,
    ID_PCD NUMBER,
    TIPO NUMBER(3)
);

CREATE TABLE SPAC_P_TRAMITES (
    ID NUMBER NOT NULL,
    ID_CTTRAMITE NUMBER,
    ID_TRAMITE_BPM VARCHAR2(64 CHAR),
    ID_PCD NUMBER,
    ID_FASE NUMBER,
    NOMBRE VARCHAR2(250 CHAR),
	ORDEN NUMBER,
	OBLIGATORIO NUMBER,
    LIBRE NUMBER(3),
    ID_RESP VARCHAR2(250 CHAR),
    ID_RESP_SEC VARCHAR2(250 CHAR),
    ID_PCD_SUB NUMBER
);

CREATE TABLE SPAC_P_DEP_TRAMITES (
    ID NUMBER NOT NULL,
    ID_TRAMITE_PADRE NUMBER NOT NULL,
    ID_TRAMITE_HIJO NUMBER NOT NULL
);

CREATE TABLE SPAC_P_VERSPLANT (
    ID NUMBER NOT NULL,
    ID_PLANT NUMBER,
    FECHA DATE ,
    USUARIO VARCHAR2(250 CHAR),
    ESTADO NUMBER(3)
);

CREATE TABLE SPAC_PROCESOS (
    ID NUMBER NOT NULL,
    ID_PROCESO_BPM VARCHAR2(64 CHAR),
    ID_PCD NUMBER,
    NUMEXP VARCHAR2(30 CHAR),
    ESTADO NUMBER(3),
    FECHA_INICIO DATE ,
    FECHA_LIMITE DATE ,
    FECHA_CIERRE DATE ,
    ID_RESP VARCHAR2(250 CHAR),
	RESP VARCHAR2 (250 CHAR),
    ID_RESP_SEC VARCHAR2(250 CHAR),
	RESP_SEC VARCHAR2(250 CHAR),
    ESTADO_PLAZO NUMBER,
    FECHA_INICIO_PLAZO DATE,
    NUM_DIAS_PLAZO NUMBER,
    ID_CALENDARIO NUMBER,
    TIPO NUMBER(1),
	FECHA_ELIMINACION DATE,
	ESTADO_ANTERIOR NUMBER(3)
);

CREATE TABLE SPAC_S_BLOQUEOS (
    ID VARCHAR2(200 CHAR),
    TP_OBJ NUMBER NOT NULL,
    ID_OBJ NUMBER NOT NULL,
    NUMEXP VARCHAR2(30 CHAR) NOT NULL,
    FECHA DATE
);

CREATE TABLE SPAC_S_SESIONES (
    ID VARCHAR2(200 CHAR) NOT NULL,
    FECHA DATE ,
    DATOS VARCHAR2(4000 CHAR),
    USUARIO VARCHAR2(250 CHAR),
    HITS NUMBER,
    TIEMPO_OP NUMBER,
    TIEMPO_SS NUMBER,
    HOST VARCHAR2(150 CHAR),
    KEEP_ALIVE DATE ,
    APLICACION VARCHAR2(32 CHAR)
);

CREATE TABLE SPAC_S_VARS (
    ID NUMBER NOT NULL,
    NOMBRE VARCHAR2(60 CHAR),
    VALOR VARCHAR2(4000 CHAR),
    ID_SES VARCHAR2(200 CHAR)
);

CREATE TABLE SPAC_SINCNODO (
    ID NUMBER NOT NULL,
    ID_EXP NUMBER,
    ID_NODO NUMBER,
    ESTADO VARCHAR2(4000 CHAR),
    ID_PCD NUMBER,
    TIPO NUMBER(3)
);

CREATE TABLE SPAC_SS_FUNCIONES (
    ID NUMBER NOT NULL,
    UID_USR VARCHAR2(120 CHAR),
    FUNCION NUMBER
);

CREATE TABLE SPAC_SS_PERMISOS (
    ID NUMBER NOT NULL,
    ID_PCD NUMBER,
    UID_USR VARCHAR2(120 CHAR),
    PERMISO NUMBER
);

CREATE TABLE SPAC_SS_SUPERVISION (
    ID NUMBER NOT NULL,
    UID_SUPERVISOR VARCHAR2(120 CHAR),
    UID_SUPERVISADO VARCHAR2(120 CHAR),
    TIPO NUMBER
);

CREATE TABLE SPAC_TBL_001 (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(1 CHAR),
    SUSTITUTO VARCHAR2(64 CHAR),
    VIGENTE NUMBER(1),
	ORDEN NUMBER(10)
);

CREATE TABLE SPAC_TBL_002 (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(4 CHAR),
    SUSTITUTO VARCHAR2(64 CHAR),
    VIGENTE NUMBER(1),
	ORDEN NUMBER(10)
);

CREATE TABLE SPAC_TBL_003 (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(8 CHAR),
    SUSTITUTO VARCHAR2(64 CHAR),
    VIGENTE NUMBER(1),
	ORDEN NUMBER(10)
);

CREATE TABLE SPAC_TBL_004 (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(8 CHAR),
    SUSTITUTO VARCHAR2(64 CHAR),
    VIGENTE NUMBER(1),
	ORDEN NUMBER(10)
);

CREATE TABLE SPAC_TBL_005 (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(8 CHAR),
    SUSTITUTO VARCHAR2(64 CHAR),
    VIGENTE NUMBER(1),
	ORDEN NUMBER(10)
);

CREATE TABLE SPAC_TBL_006 (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(8 CHAR),
    SUSTITUTO VARCHAR2(64 CHAR),
    VIGENTE NUMBER(1),
	ORDEN NUMBER(10)
);

CREATE TABLE SPAC_TBL_007 (
    ID NUMBER,
    VALOR VARCHAR2(64 CHAR),
    VIGENTE NUMBER(1),
	ORDEN NUMBER(10)
);

CREATE TABLE SPAC_TBL_008 (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(8 CHAR),
    SUSTITUTO VARCHAR2(64 CHAR),
    VIGENTE NUMBER(1),
	ORDEN NUMBER(10)
);

CREATE TABLE SPAC_TBL_009 (
  	ID NUMBER NOT NULL,
    VALOR VARCHAR2(2 CHAR),
    VIGENTE NUMBER(1),
	ORDEN NUMBER(10)
);

CREATE TABLE SPAC_TRAMITACIONES_AGRUPADAS (
    ID NUMBER NOT NULL,
    ID_RESP VARCHAR2(250 CHAR),
    ESTADO NUMBER(3),
    ID_FASE NUMBER,
    ID_ULTIMO_TRAMITE NUMBER,
    ID_ULTIMO_TIPODOC NUMBER,
    ID_ULTIMO_TEMPLATE NUMBER,
    FECHA_CREACION DATE
);

CREATE TABLE SPAC_TRAMITCS_AGRUPADAS_EXPS (
    ID NUMBER NOT NULL,
    ID_TRAM_AGRUP NUMBER NOT NULL,
    NUMEXP VARCHAR2(30 CHAR)
);

CREATE TABLE SPAC_TRAMITES (
    ID NUMBER NOT NULL,
    ID_TRAMITE_BPM VARCHAR2(64 CHAR),
    ID_EXP NUMBER,
    ID_PCD NUMBER,
    ID_FASE_EXP NUMBER,
    ID_FASE_PCD NUMBER,
    ID_TRAMITE NUMBER,
    ID_CTTRAMITE NUMBER,
    NUMEXP VARCHAR2(30 CHAR),
    NOMBRE VARCHAR2(250 CHAR),
    FECHA_INICIO DATE,
    FECHA_LIMITE DATE,
    ESTADO NUMBER(3),
    OBSERVACIONES VARCHAR2(4000 CHAR),
    ID_RESP VARCHAR2(250 CHAR),
	RESP VARCHAR2(250 CHAR),
    ID_RESP_SEC VARCHAR2(250 CHAR),
	RESP_SEC VARCHAR2(250 CHAR),
    ESTADO_PLAZO NUMBER,
    FECHA_INICIO_PLAZO DATE,
    NUM_DIAS_PLAZO NUMBER,
    ID_CALENDARIO NUMBER,
    TIPO NUMBER(1),
    ID_SUBPROCESO NUMBER,
	ESTADO_ANTERIOR NUMBER(3)
);

CREATE TABLE SPAC_VARS (
    ID NUMBER NOT NULL,
    NOMBRE VARCHAR2(64 CHAR),
    VALOR CLOB,
    DESCRIPCION VARCHAR2(256 CHAR)
);

CREATE TABLE SPAC_VLDTBL_ACTS_FUNCS (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(2 CHAR),
    SUSTITUTO VARCHAR2(64 CHAR),
    VIGENTE NUMBER(1),
	ORDEN NUMBER(10)
);

CREATE TABLE SPAC_VLDTBL_EFEC_SLNCIO (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(1 CHAR),
    SUSTITUTO VARCHAR2(64 CHAR),
    VIGENTE NUMBER(1),
	ORDEN NUMBER(10)
);

CREATE TABLE SPAC_VLDTBL_FORMA_INIC (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(1 CHAR),
    SUSTITUTO VARCHAR2(64 CHAR),
    VIGENTE NUMBER(1),
	ORDEN NUMBER(10)
);

CREATE TABLE SPAC_VLDTBL_MATS_COMP (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(2 CHAR),
    SUSTITUTO VARCHAR2(64 CHAR),
    VIGENTE NUMBER(1),
	ORDEN NUMBER(10)
);

CREATE TABLE SPAC_VLDTBL_RECURSOS (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(2 CHAR),
    SUSTITUTO VARCHAR2(64 CHAR),
    VIGENTE NUMBER(1),
	ORDEN NUMBER(10)
);

CREATE TABLE SPAC_VLDTBL_SIST_PRODUCTORES (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(2 CHAR),
    SUSTITUTO VARCHAR2(64 CHAR),
    VIGENTE NUMBER(1),
	ORDEN NUMBER(10)
);

CREATE TABLE SPAC_VLDTBL_SIT_TLM (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(2 CHAR),
    SUSTITUTO VARCHAR2(64 CHAR),
    VIGENTE NUMBER(1),
	ORDEN NUMBER(10)
);

CREATE TABLE SPAC_VLDTBL_TIPOREG (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(10 CHAR),
    VIGENTE NUMBER(1),
	ORDEN NUMBER(10)
);

CREATE TABLE SPAC_VLDTBL_TIPOS_DOCS (
    ID NUMBER,
    VALOR VARCHAR2(64 CHAR),
    VIGENTE NUMBER(1),
	ORDEN NUMBER(10)
);

CREATE TABLE SPAC_VLDTBL_TIPOS_TRAM (
    ID NUMBER,
    VALOR VARCHAR2(32 CHAR),
    VIGENTE NUMBER(1),
	ORDEN NUMBER(10)
);

CREATE TABLE SPAC_VLDTBL_TIPO_NOTIF (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(2 CHAR),
    SUSTITUTO VARCHAR2(64 CHAR),
    VIGENTE NUMBER(1),
	ORDEN NUMBER(10)
);

CREATE TABLE SPAC_SS_SUSTITUCION (
	ID NUMBER NOT NULL,
	UID_SUSTITUTO VARCHAR2(120 CHAR),
	UID_SUSTITUIDO VARCHAR2(120 CHAR)
);

CREATE TABLE SPAC_SS_FECHSUSTITUCIONES (
	ID NUMBER NOT NULL,
	FECHA_INICIO DATE,
	FECHA_FIN DATE,
	DESCRIPCION VARCHAR2(255 CHAR)
);

CREATE TABLE SPAC_SS_SUSTITUCIONFECHA (
	ID NUMBER NOT NULL,
	ID_SUSTITUCION NUMBER,
	ID_FECHSUSTITUCION NUMBER
);

CREATE TABLE SPAC_NUMEXP_CONTADOR (
	ANIO NUMBER NOT NULL,
	CONTADOR NUMBER,
	FORMATO VARCHAR2(32 CHAR),
	ID_PCD NUMBER DEFAULT -1 NOT NULL
);

CREATE TABLE SPAC_CT_INFORMES (
	ID NUMBER NOT NULL,
	NOMBRE VARCHAR(100),
	DESCRIPCION VARCHAR(255),
	XML CLOB,
	FECHA DATE,
	TIPO NUMBER,
	FILAS NUMBER(2),
	COLUMNAS NUMBER(2),
	FRM_PARAMS CLOB,
	VISIBILIDAD NUMBER(2) DEFAULT 0
);

CREATE TABLE SPAC_CT_INFORMES_ORG (
	ID NUMBER NOT NULL,
	ID_INFORME NUMBER,
	UID_USR VARCHAR(32)
);

CREATE TABLE SPAC_P_INFORMES (
  	ID_OBJ NUMBER NOT NULL,
  	TP_OBJ NUMBER NOT NULL,
  	ID_INFORME NUMBER NOT NULL
);

CREATE TABLE SPAC_CT_FRMBUSQ_INFORMES (
  	ID_FMRBUSQUEDA NUMBER NOT NULL,
  	ID_INFORME NUMBER NOT NULL
);

CREATE TABLE SPAC_CT_JERARQUIAS (
	ID NUMBER NOT NULL,
	ID_ENTIDAD_PADRE NUMBER,
	ID_ENTIDAD_HIJA NUMBER,
	NOMBRE VARCHAR2(64 CHAR),
	DESCRIPCION VARCHAR2(4000 CHAR),
	TIPO NUMBER(1) DEFAULT 1
);

CREATE TABLE SPAC_AYUDAS (
	ID NUMBER NOT NULL,
	NOMBRE VARCHAR(100),
	TIPO_OBJ NUMBER,
	ID_OBJ NUMBER,
	IDIOMA VARCHAR(5),
	CONTENIDO CLOB
);

CREATE TABLE SPAC_PERMISOS (
   TP_OBJ NUMBER NOT NULL,
   ID_OBJ NUMBER NOT NULL,
   ID_RESP VARCHAR2(250 CHAR) NOT NULL,
   RESP_NAME VARCHAR2(250 CHAR) NOT NULL,
   PERMISO NUMBER NOT NULL
);
