ALTER session SET nls_length_semantics = CHAR;

--
-- Tablas de Entidades
--
CREATE TABLE SGL_OBRAS_MENORES (
    ID NUMBER NOT NULL,
    NUMEXP VARCHAR2(30 CHAR),
    TIPO_OBJETO VARCHAR2(15 CHAR),
    TIPO_LOCALIZADOR VARCHAR2(15 CHAR),
    LOCALIZADOR VARCHAR2(15 CHAR),
    ACTUACION_CASCO_HISTORICO VARCHAR2(2 CHAR),
    TIPO_FINCA VARCHAR2(15 CHAR),
    TIPO_SUELO VARCHAR2(15 CHAR),
    UBICACION_INMUEBLE VARCHAR2(512 CHAR),
    REFERENCIA_CATASTRAL VARCHAR2(20 CHAR),
    LOCALIZACION VARCHAR2(15 CHAR),
    DESCRIPCION CLOB,
    PRESUPUESTO_TOTAL NUMBER(15,2),
    FECHA_INICIO DATE,
    FECHA_TERMINACION DATE,
    OCUPACION_VIA_PUBLICA VARCHAR2(2 CHAR)
);

CREATE TABLE SGQ_QUEJAS (
    ID NUMBER NOT NULL,
    NUMEXP VARCHAR2(30 CHAR),
    ID_ORGANO_OBJETO VARCHAR2(64 CHAR),
    ORGANO_OBJETO VARCHAR2(512 CHAR),
    TIPO_OBJETO VARCHAR2(10 CHAR),
    LOCALIZADOR_OBJETO VARCHAR2(64 CHAR),
    ASUNTO CLOB,
    TIPO_ORGANO_DESTINO VARCHAR2(8 CHAR),
    ID_ORGANO_INFORME VARCHAR2(64 CHAR),
    ORGANO_INFORME VARCHAR2(512 CHAR)
);

CREATE TABLE SGS_SUBVENCIONES (
    ID NUMBER NOT NULL,
    NUMEXP VARCHAR2(30 CHAR),
    ID_PCD NUMBER,
    ANIO_PRESUPUESTARIO NUMBER(4,0),
    TIPO_SUBVENCION VARCHAR2(8 CHAR),
    FECHA_CONVOCATORIA DATE,
    DENOMINACION_PROYECTO VARCHAR2(120 CHAR),
    RESUMEN_PROYECTO CLOB,
    FECHA_INICIO_EJECUCION DATE,
    FECHA_FIN_EJECUCION DATE,
    DURACION_PROYECTO NUMBER(2,0),
    COLECTIVO_DESTINO VARCHAR2(64 CHAR),
    IMPORTE_SOLICITADO NUMBER(13,2),
    IMPORTE_CONCEDIDO NUMBER(13,2),
    PREVISION_GASTOS CLOB,
    IMPORTE_GASTOS NUMBER(10,2),
    TOTAL_GASTOS NUMBER(10,2),
    APORTACION_AYTO NUMBER(13,2),
    APORTACION_ENTIDAD NUMBER(13,2),
    OTRAS_APORTACIONES NUMBER(13,2),
    TOTAL_APORTACIONES NUMBER(13,2),
    FINALIDAD_SUBVENCION CLOB,
    OBSERVACIONES CLOB
);


--
-- Tablas de Validacion
--

-------------------
-- OBRAS MENORES --
-------------------

-- Tabla de validacion para Tipos de Suelo
CREATE TABLE SPAC_TBL_010 (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(8 CHAR),
    SUSTITUTO VARCHAR2(64 CHAR),
    VIGENTE NUMBER(1),
	ORDEN NUMBER(10)
);

-- Tabla de validacion para Tipos de Finca
CREATE TABLE SPAC_TBL_011 (
  	ID NUMBER NOT NULL,
  	VALOR VARCHAR2(8 CHAR),
  	SUSTITUTO VARCHAR2(64 CHAR),
  	VIGENTE NUMBER(1),
	ORDEN NUMBER(10)
);

-- Tabla de validacion para Localizacion de Obras
CREATE TABLE SPAC_TBL_012 (
  	ID NUMBER NOT NULL,
  	VALOR VARCHAR2(8 CHAR),
  	SUSTITUTO VARCHAR2(64 CHAR),
  	VIGENTE NUMBER(1),
	ORDEN NUMBER(10)
);


------------------
-- SUBVENCIONES --
------------------

-- Tabla de validacion para Tipos de Subvencion
CREATE TABLE SPAC_TBL_013 (
  	ID NUMBER NOT NULL,
  	VALOR VARCHAR2(8 CHAR),
  	SUSTITUTO VARCHAR2(64 CHAR),
  	VIGENTE NUMBER(1),
	ORDEN NUMBER(10)
);
