--
-- CLAVES PRIMARIAS
--
ALTER TABLE SGL_OBRAS_MENORES
    ADD CONSTRAINT PK_SGL_OBRAS_MENO PRIMARY KEY (ID);
ALTER TABLE SGQ_QUEJAS
    ADD CONSTRAINT PK_SGQ_QUEJAS PRIMARY KEY (ID);
ALTER TABLE SGS_SUBVENCIONES
    ADD CONSTRAINT PK_SGS_SUBV PRIMARY KEY (ID);

ALTER TABLE SPAC_TBL_010
    ADD CONSTRAINT PK_SPAC_TBL_010 PRIMARY KEY (ID);
ALTER TABLE SPAC_TBL_011
    ADD CONSTRAINT PK_SPAC_TBL_011 PRIMARY KEY (ID);
ALTER TABLE SPAC_TBL_012
    ADD CONSTRAINT PK_SPAC_TBL_012 PRIMARY KEY (ID);
ALTER TABLE SPAC_TBL_013
    ADD CONSTRAINT PK_SPAC_TBL_013 PRIMARY KEY (ID);
