--
-- INSERCION DE DATOS CLOB (longitud maxima de 32k en la cadena asignada a la variable clob)
--

--
-- Formularios
--
declare
datoa clob;
datob clob;
datoc clob;

begin

-- Formulario para Obra Menor
datoa:='<%@ taglib uri="/WEB-INF/struts-bean.tld" prefix="bean" %><%@ taglib uri="/WEB-INF/struts-html.tld" prefix="html" %><%@ taglib uri="/WEB-INF/struts-logic.tld" prefix="logic" %><%@ taglib uri="/WEB-INF/ispac-util.tld" prefix="ispac" %><%@ taglib uri="/WEB-INF/struts-tiles.tld" prefix="tiles" %><!-- DEFINICION DE LAS ANCLAS A LOS BLOQUES DE CAMPOS --><table border="0" cellspacing="0" cellpadding="0"><tr><td class="select" id="tdlink1" align="center"><nobr><bean:write name="defaultForm" property="entityApp.label(SGL_OBRAS_MENORES:SGL_OBRAS_MENORES)" /></nobr></td></tr></table><table width="100%" border="0" class="formtable" cellspacing="0" cellpadding="0"><tr><td><img height="8" src=''<ispac:rewrite href="img/pixel.gif"/>''/></td></tr><tr><td><!-- BLOQUE1 DE CAMPOS --><div style="display:block" id="block1"><div id="dataBlock_SGL_OBRAS_MENORES" style="position: relative; height: 320px; width: 600px;"><div id="label_SGL_OBRAS_MENORES:TIPO_OBJETO" style="position: absolute; top: 61px; left: 10px;" class="formsTitleB"><nobr><bean:write name="defaultForm" property="entityApp.label(SGL_OBRAS_MENORES:TIPO_OBJETO)" />:</nobr></div><div id="data_SGL_OBRAS_MENORES:TIPO_OBJETO" style="position: absolute; top: 58px; left: 150px;"><ispac:htmlText property="property(SGL_OBRAS_MENORES:TIPO_OBJETO)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="25" maxlength="15" tabindex="102"></ispac:htmlText></div><div id="label_SGL_OBRAS_MENORES:TIPO_LOCALIZADOR" style="position: absolute; top: 61px; left: 310px;" class="formsTitleB"><nobr><bean:write name="defaultForm" property="entityApp.label(SGL_OBRAS_MENORES:TIPO_LOCALIZADOR)" />:</nobr></div><div id="data_SGL_OBRAS_MENORES:TIPO_LOCALIZADOR" style="position: absolute; top: 58px; left: 440px;"><ispac:htmlText property="property(SGL_OBRAS_MENORES:TIPO_LOCALIZADOR)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="25" maxlength="15" tabindex="103"></ispac:htmlText></div>
<div id="label_SGL_OBRAS_MENORES:LOCALIZADOR" style="position: absolute; top: 92px; left: 10px;" class="formsTitleB"><nobr><bean:write name="defaultForm" property="entityApp.label(SGL_OBRAS_MENORES:LOCALIZADOR)" />:</nobr></div><div id="data_SGL_OBRAS_MENORES:LOCALIZADOR" style="position: absolute; top: 89px; left: 150px;"><ispac:htmlText property="property(SGL_OBRAS_MENORES:LOCALIZADOR)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="25" maxlength="15" tabindex="104"></ispac:htmlText></div><div id="label_SGL_OBRAS_MENORES:ACTUACION_CASCO_HISTORICO" style="position: absolute; top: 222px; left: 10px; width: 130px;" class="formsTitleB"><bean:write name="defaultForm" property="entityApp.label(SGL_OBRAS_MENORES:ACTUACION_CASCO_HISTORICO)" />:</div><div id="data_SGL_OBRAS_MENORES:ACTUACION_CASCO_HISTORICO" style="position: absolute; top: 219px; left: 150px;"><nobr><ispac:htmlTextImageFrame property="property(SGL_OBRAS_MENORES:ACTUACION_CASCO_HISTORICO)" readonly="true" readonlyTag="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="5" id="SEARCH_SGL_OBRAS_MENORES_ACTUACION_CASCO_HISTORICO" target="workframe" action="selectValue.do?entity=SPAC_TBL_009" image="img/search-mg.gif" titleKeyLink="title.link.data.selection" imageDelete="img/borrar.gif" titleKeyImageDelete="title.delete.data.selection" styleClassDeleteLink="tdlink" confirmDeleteKey="msg.delete.data.selection" showDelete="true" showFrame="true" width="640" height="480" tabindex="110"><ispac:parameter name="SEARCH_SGL_OBRAS_MENORES_ACTUACION_CASCO_HISTORICO" id="property(SGL_OBRAS_MENORES:ACTUACION_CASCO_HISTORICO)" property="VALOR" /></ispac:htmlTextImageFrame></nobr></div>
<div id="label_SGL_OBRAS_MENORES:TIPO_FINCA" style="position: absolute; top: 189px; left: 10px;" class="formsTitleB"><nobr><bean:write name="defaultForm" property="entityApp.label(SGL_OBRAS_MENORES:TIPO_FINCA)" />:</nobr></div><div id="data_SGL_OBRAS_MENORES:TIPO_FINCA" style="position: absolute; top: 186px; left: 150px;"><html:hidden property="property(SGL_OBRAS_MENORES:TIPO_FINCA)" /><nobr><ispac:htmlTextImageFrame property="property(TIPO_FINCA_SPAC_TBL_011:SUSTITUTO)" readonly="true" readonlyTag="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="18" id="SEARCH_SGL_OBRAS_MENORES_TIPO_FINCA" target="workframe" action="selectSubstitute.do?entity=SPAC_TBL_011" image="img/search-mg.gif" titleKeyLink="title.link.data.selection" imageDelete="img/borrar.gif" titleKeyImageDelete="title.delete.data.selection" styleClassDeleteLink="tdlink" confirmDeleteKey="msg.delete.data.selection" showDelete="true" showFrame="true" width="640" height="480" tabindex="108"><ispac:parameter name="SEARCH_SGL_OBRAS_MENORES_TIPO_FINCA" id="property(SGL_OBRAS_MENORES:TIPO_FINCA)" property="VALOR" /><ispac:parameter name="SEARCH_SGL_OBRAS_MENORES_TIPO_FINCA" id="property(TIPO_FINCA_SPAC_TBL_011:SUSTITUTO)" property="SUSTITUTO" /></ispac:htmlTextImageFrame></nobr></div><div id="label_SGL_OBRAS_MENORES:TIPO_SUELO" style="position: absolute; top: 189px; left: 310px;" class="formsTitleB"><nobr><bean:write name="defaultForm" property="entityApp.label(SGL_OBRAS_MENORES:TIPO_SUELO)" />:</nobr></div>
<div id="data_SGL_OBRAS_MENORES:TIPO_SUELO" style="position: absolute; top: 186px; left: 440px;"><html:hidden property="property(SGL_OBRAS_MENORES:TIPO_SUELO)" /><nobr><ispac:htmlTextImageFrame property="property(TIPO_SUELO_SPAC_TBL_010:SUSTITUTO)" readonly="true" readonlyTag="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="18" id="SEARCH_SGL_OBRAS_MENORES_TIPO_SUELO" target="workframe" action="selectSubstitute.do?entity=SPAC_TBL_010" image="img/search-mg.gif" titleKeyLink="title.link.data.selection" imageDelete="img/borrar.gif" titleKeyImageDelete="title.delete.data.selection" styleClassDeleteLink="tdlink" confirmDeleteKey="msg.delete.data.selection" showDelete="true" showFrame="true" width="640" height="480" tabindex="109"><ispac:parameter name="SEARCH_SGL_OBRAS_MENORES_TIPO_SUELO" id="property(SGL_OBRAS_MENORES:TIPO_SUELO)" property="VALOR" /><ispac:parameter name="SEARCH_SGL_OBRAS_MENORES_TIPO_SUELO" id="property(TIPO_SUELO_SPAC_TBL_010:SUSTITUTO)" property="SUSTITUTO" /></ispac:htmlTextImageFrame></nobr></div><div id="label_SGL_OBRAS_MENORES:UBICACION_INMUEBLE" style="position: absolute; top: 123px; left: 10px;" class="formsTitleB"><nobr><bean:write name="defaultForm" property="entityApp.label(SGL_OBRAS_MENORES:UBICACION_INMUEBLE)" />:</nobr></div><div id="data_SGL_OBRAS_MENORES:UBICACION_INMUEBLE" style="position: absolute; top: 120px; left: 150px;"><ispac:htmlText property="property(SGL_OBRAS_MENORES:UBICACION_INMUEBLE)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="83" maxlength="512" tabindex="105"></ispac:htmlText></div><div id="label_SGL_OBRAS_MENORES:REFERENCIA_CATASTRAL" style="position: absolute; top: 155px; left: 10px;" class="formsTitleB"><nobr><bean:write name="defaultForm" property="entityApp.label(SGL_OBRAS_MENORES:REFERENCIA_CATASTRAL)" />:</nobr></div>
<div id="data_SGL_OBRAS_MENORES:REFERENCIA_CATASTRAL" style="position: absolute; top: 152px; left: 150px;"><ispac:htmlText property="property(SGL_OBRAS_MENORES:REFERENCIA_CATASTRAL)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="25" maxlength="20" tabindex="106"></ispac:htmlText></div><div id="label_SGL_OBRAS_MENORES:LOCALIZACION" style="position: absolute; top: 155px; left: 310px;" class="formsTitleB"><nobr><bean:write name="defaultForm" property="entityApp.label(SGL_OBRAS_MENORES:LOCALIZACION)" />:</nobr></div><div id="data_SGL_OBRAS_MENORES:LOCALIZACION" style="position: absolute; top: 152px; left: 440px;"><html:hidden property="property(SGL_OBRAS_MENORES:LOCALIZACION)" /><nobr><ispac:htmlTextImageFrame property="property(LOCALIZACION_SPAC_TBL_012:SUSTITUTO)" readonly="true" readonlyTag="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="18" id="SEARCH_SGL_OBRAS_MENORES_LOCALIZACION" target="workframe" action="selectSubstitute.do?entity=SPAC_TBL_012" image="img/search-mg.gif" titleKeyLink="title.link.data.selection" imageDelete="img/borrar.gif" titleKeyImageDelete="title.delete.data.selection" styleClassDeleteLink="tdlink" confirmDeleteKey="msg.delete.data.selection" showDelete="true" showFrame="true" width="640" height="480" tabindex="107"><ispac:parameter name="SEARCH_SGL_OBRAS_MENORES_LOCALIZACION" id="property(SGL_OBRAS_MENORES:LOCALIZACION)" property="VALOR" /><ispac:parameter name="SEARCH_SGL_OBRAS_MENORES_LOCALIZACION" id="property(LOCALIZACION_SPAC_TBL_012:SUSTITUTO)" property="SUSTITUTO" /></ispac:htmlTextImageFrame></nobr></div>
<div id="label_SGL_OBRAS_MENORES:DESCRIPCION" style="position: absolute; top: 20px; left: 10px;" class="formsTitleB"><nobr><bean:write name="defaultForm" property="entityApp.label(SGL_OBRAS_MENORES:DESCRIPCION)" />:</nobr></div><div id="data_SGL_OBRAS_MENORES:DESCRIPCION" style="position: absolute; top: 17px; left: 150px;"><ispac:htmlTextarea property="property(SGL_OBRAS_MENORES:DESCRIPCION)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" rows="2" cols="82" tabindex="101"></ispac:htmlTextarea></div><div id="label_SGL_OBRAS_MENORES:PRESUPUESTO_TOTAL" style="position: absolute; top: 254px; left: 10px; width: 120px;" class="formsTitleB"><bean:write name="defaultForm" property="entityApp.label(SGL_OBRAS_MENORES:PRESUPUESTO_TOTAL)" />:</div><div id="data_SGL_OBRAS_MENORES:PRESUPUESTO_TOTAL" style="position: absolute; top: 251px; left: 150px;" class="formsTitleB"><ispac:htmlText property="property(SGL_OBRAS_MENORES:PRESUPUESTO_TOTAL)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="18" maxlength="15" tabindex="112"></ispac:htmlText>&nbsp;<bean:message key="common.message.currency"/></div><div id="label_SGL_OBRAS_MENORES:FECHA_INICIO" style="position: absolute; top: 289px; left: 10px;" class="formsTitleB"><nobr><bean:write name="defaultForm" property="entityApp.label(SGL_OBRAS_MENORES:FECHA_INICIO)" />:</nobr></div><div id="data_SGL_OBRAS_MENORES:FECHA_INICIO" style="position: absolute; top: 286px; left: 150px;"><nobr><ispac:htmlTextCalendar property="property(SGL_OBRAS_MENORES:FECHA_INICIO)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="14" maxlength="10" image=''<%= buttoncalendar %>'' format="dd/mm/yyyy" enablePast="true" tabindex="113"></ispac:htmlTextCalendar></nobr></div>
<div id="label_SGL_OBRAS_MENORES:FECHA_TERMINACION" style="position: absolute; top: 289px; left: 310px;" class="formsTitleB"><nobr><bean:write name="defaultForm" property="entityApp.label(SGL_OBRAS_MENORES:FECHA_TERMINACION)" />:</nobr></div><div id="data_SGL_OBRAS_MENORES:FECHA_TERMINACION" style="position: absolute; top: 286px; left: 440px;"><nobr><ispac:htmlTextCalendar property="property(SGL_OBRAS_MENORES:FECHA_TERMINACION)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="14" maxlength="10" image=''<%= buttoncalendar %>'' format="dd/mm/yyyy" enablePast="true" tabindex="114"></ispac:htmlTextCalendar></nobr></div><div id="label_SGL_OBRAS_MENORES:OCUPACION_VIA_PUBLICA" style="position: absolute; top: 222px; left: 310px; width: 130px;" class="formsTitleB"><bean:write name="defaultForm" property="entityApp.label(SGL_OBRAS_MENORES:OCUPACION_VIA_PUBLICA)" />:</div><div id="data_SGL_OBRAS_MENORES:OCUPACION_VIA_PUBLICA" style="position: absolute; top: 219px; left: 440px;"><nobr><ispac:htmlTextImageFrame property="property(SGL_OBRAS_MENORES:OCUPACION_VIA_PUBLICA)" readonly="true" readonlyTag="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="5" id="SEARCH_SGL_OBRAS_MENORES_OCUPACION_VIA_PUBLICA" target="workframe" action="selectValue.do?entity=SPAC_TBL_009" image="img/search-mg.gif" titleKeyLink="title.link.data.selection" imageDelete="img/borrar.gif" titleKeyImageDelete="title.delete.data.selection" styleClassDeleteLink="tdlink" confirmDeleteKey="msg.delete.data.selection" showDelete="true" showFrame="true" width="640" height="480" tabindex="111"><ispac:parameter name="SEARCH_SGL_OBRAS_MENORES_OCUPACION_VIA_PUBLICA" id="property(SGL_OBRAS_MENORES:OCUPACION_VIA_PUBLICA)" property="VALOR" /></ispac:htmlTextImageFrame></nobr></div></div></div></td></tr><tr><td height="15"><img src=''<ispac:rewrite href="img/pixel.gif"/>''/></td></tr></table>';

-- Formulario para Queja
datob:='<%@ taglib uri="/WEB-INF/struts-bean.tld" prefix="bean" %><%@ taglib uri="/WEB-INF/struts-html.tld" prefix="html" %><%@ taglib uri="/WEB-INF/struts-logic.tld" prefix="logic" %><%@ taglib uri="/WEB-INF/ispac-util.tld" prefix="ispac" %><%@ taglib uri="/WEB-INF/struts-tiles.tld" prefix="tiles" %><!-- DEFINICION DE LAS ANCLAS A LOS BLOQUES DE CAMPOS --><table border="0" cellspacing="0" cellpadding="0"><tr><td class="select" id="tdlink1" align="center"><nobr><bean:write name="defaultForm" property="entityApp.label(SGQ_QUEJAS:SGQ_QUEJAS)" /></nobr></td></tr></table><table width="100%" border="0" class="formtable" cellspacing="0" cellpadding="0"><tr><td><img height="8" src=''<ispac:rewrite href="img/pixel.gif"/>''/></td></tr><tr><td><!-- BLOQUE1 DE CAMPOS --><div style="display:block" id="block1"><div id="dataBlock_SGQ_QUEJAS" style="position: relative; height: 235px; width: 600px;"><div id="label_SGQ_QUEJAS:ID_ORGANO_OBJETO" style="position: absolute; top: 203px; left: 10px;" class="formsTitleB"><nobr><bean:write name="defaultForm" property="entityApp.label(SGQ_QUEJAS:ID_ORGANO_OBJETO)" />:</nobr></div><div id="data_SGQ_QUEJAS:ID_ORGANO_OBJETO" style="position: absolute; top: 200px; left: 150px;"><html:hidden property="property(SGQ_QUEJAS:ID_ORGANO_OBJETO)"/><nobr>
<ispac:htmlTextImageFrame property="property(SGQ_QUEJAS:ORGANO_OBJETO)"			  readonly="true"			  readonlyTag="false"			  propertyReadonly="readonly"			  styleClass="input"			  styleClassReadonly="inputReadOnly"			  size="46"			  id="SELECT_SGQ_QUEJAS_ORGANO_OBJETO"			  target="workframe"			  action="viewUsersManager.do?captionkey=app.selectOrg.seleccionar&noviewusers=true&noviewgroups=true"			  image="img/search-mg.gif"			  showFrame="true" tabindex="102">	<ispac:parameter name="SELECT_SGQ_QUEJAS_ORGANO_OBJETO" id="property(SGQ_QUEJAS:ID_ORGANO_OBJETO)" property="UID"/>	<ispac:parameter name="SELECT_SGQ_QUEJAS_ORGANO_OBJETO" id="property(SGQ_QUEJAS:ORGANO_OBJETO)" property="NAME"/></ispac:htmlTextImageFrame></nobr></div><div id="label_SGQ_QUEJAS:ASUNTO" style="position: absolute; top: 20px; left: 10px;" class="formsTitleB"><nobr><bean:write name="defaultForm" property="entityApp.label(SGQ_QUEJAS:ASUNTO)" />:</nobr></div><div id="data_SGQ_QUEJAS:ASUNTO" style="position: absolute; top: 37px; left: 11px;"><ispac:htmlTextarea property="property(SGQ_QUEJAS:ASUNTO)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" rows="12" cols="80" tabindex="101"></ispac:htmlTextarea></div></div></div></td></tr><tr><td height="15"><img src=''<ispac:rewrite href="img/pixel.gif"/>''/></td></tr></table>';

-- Formulario para Subvencion
datoc:='<%@ taglib uri="/WEB-INF/struts-bean.tld" prefix="bean" %><%@ taglib uri="/WEB-INF/struts-html.tld" prefix="html" %><%@ taglib uri="/WEB-INF/struts-logic.tld" prefix="logic" %><%@ taglib uri="/WEB-INF/ispac-util.tld" prefix="ispac" %><%@ taglib uri="/WEB-INF/struts-tiles.tld" prefix="tiles" %><!-- DEFINICION DE LAS ANCLAS A LOS BLOQUES DE CAMPOS --><table border="0" cellspacing="0" cellpadding="0"><tr><td class="select" id="tdlink1" align="center"><nobr><bean:write name="defaultForm" property="entityApp.label(SGS_SUBVENCIONES:SGS_SUBVENCIONES)" /></nobr></td></tr></table><table width="100%" border="0" class="formtable" cellspacing="0" cellpadding="0"><tr><td><img height="8" src=''<ispac:rewrite href="img/pixel.gif"/>''/></td></tr><tr><td><!-- BLOQUE1 DE CAMPOS --><div style="display:block" id="block1"><div id="dataBlock_SGS_SUBVENCIONES" style="position: relative; height: 550px; width: 640px;">  <div id="label_SGS_SUBVENCIONES:ANIO_PRESUPUESTARIO" style="position: absolute; top: 23px; left: 10px;" class="formsTitleB"><nobr><bean:write name="defaultForm" property="entityApp.label(SGS_SUBVENCIONES:ANIO_PRESUPUESTARIO)" />:</nobr></div><div id="data_SGS_SUBVENCIONES:ANIO_PRESUPUESTARIO" style="position: absolute; top: 20px; left: 190px;"><ispac:htmlText property="property(SGS_SUBVENCIONES:ANIO_PRESUPUESTARIO)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="10" maxlength="4" tabindex="101"></ispac:htmlText></div>
<div id="label_SGS_SUBVENCIONES:TIPO_SUBVENCION" style="position: absolute; top: 53px; left: 10px;" class="formsTitleB"><nobr><bean:write name="defaultForm" property="entityApp.label(SGS_SUBVENCIONES:TIPO_SUBVENCION)" />:</nobr></div><div id="data_SGS_SUBVENCIONES:TIPO_SUBVENCION" style="position: absolute; top: 50px; left: 190px;"><html:hidden property="property(SGS_SUBVENCIONES:TIPO_SUBVENCION)" /><nobr><ispac:htmlTextImageFrame property="property(TIPO_SUBVENCION_SPAC_TBL_013:SUSTITUTO)" readonly="true" readonlyTag="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="50" id="SEARCH_SGS_SUBVENCIONES_TIPO_SUBVENCION" target="workframe" action="selectSubstitute.do?entity=SPAC_TBL_013" image="img/search-mg.gif" titleKeyLink="title.link.data.selection" imageDelete="img/borrar.gif" titleKeyImageDelete="title.delete.data.selection" styleClassDeleteLink="tdlink" confirmDeleteKey="msg.delete.data.selection" showDelete="true" showFrame="true" width="640" height="480" tabindex="103"><ispac:parameter name="SEARCH_SGS_SUBVENCIONES_TIPO_SUBVENCION" id="property(SGS_SUBVENCIONES:TIPO_SUBVENCION)" property="VALOR" /><ispac:parameter name="SEARCH_SGS_SUBVENCIONES_TIPO_SUBVENCION" id="property(TIPO_SUBVENCION_SPAC_TBL_013:SUSTITUTO)" property="SUSTITUTO" /></ispac:htmlTextImageFrame></nobr></div>
<div id="label_SGS_SUBVENCIONES:FECHA_CONVOCATORIA" style="position: absolute; top: 23px; left: 352px;" class="formsTitleB">
<nobr>
<bean:write name="defaultForm" property="entityApp.label(SGS_SUBVENCIONES:FECHA_CONVOCATORIA)" />:</nobr>
</div>
<div id="data_SGS_SUBVENCIONES:FECHA_CONVOCATORIA" style="position: absolute; top: 20px; left: 490px;">
<nobr>
<ispac:htmlTextCalendar property="property(SGS_SUBVENCIONES:FECHA_CONVOCATORIA)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="14" maxlength="10" image=''<%= buttoncalendar %>'' format="dd/mm/yyyy" enablePast="true" tabindex="102">
</ispac:htmlTextCalendar>
</nobr>
</div>
<div id="label_SGS_SUBVENCIONES:DENOMINACION_PROYECTO" style="position: absolute; top: 113px; left: 10px;" class="formsTitleB">
<nobr>
<bean:write name="defaultForm" property="entityApp.label(SGS_SUBVENCIONES:DENOMINACION_PROYECTO)" />:</nobr>
</div>
<div id="data_SGS_SUBVENCIONES:DENOMINACION_PROYECTO" style="position: absolute; top: 110px; left: 190px;">
<ispac:htmlText property="property(SGS_SUBVENCIONES:DENOMINACION_PROYECTO)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="80" maxlength="120" tabindex="105">
</ispac:htmlText>
</div>
<div id="label_SGS_SUBVENCIONES:RESUMEN_PROYECTO" style="position: absolute; top: 143px; left: 10px;" class="formsTitleB">
<nobr>
<bean:write name="defaultForm" property="entityApp.label(SGS_SUBVENCIONES:RESUMEN_PROYECTO)" />:</nobr>
</div>
<div id="data_SGS_SUBVENCIONES:RESUMEN_PROYECTO" style="position: absolute; top: 140px; left: 190px;">
<ispac:htmlTextarea property="property(SGS_SUBVENCIONES:RESUMEN_PROYECTO)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" rows="2" cols="80" tabindex="106">
</ispac:htmlTextarea>
</div>
<div id="label_SGS_SUBVENCIONES:FECHA_INICIO_EJECUCION" style="position: absolute; top: 183px; left: 10px;" class="formsTitleB">
<nobr>
<bean:write name="defaultForm" property="entityApp.label(SGS_SUBVENCIONES:FECHA_INICIO_EJECUCION)" />:</nobr>
</div>
<div id="data_SGS_SUBVENCIONES:FECHA_INICIO_EJECUCION" style="position: absolute; top: 180px; left: 190px;">
<nobr>
<ispac:htmlTextCalendar property="property(SGS_SUBVENCIONES:FECHA_INICIO_EJECUCION)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="14" maxlength="10" image=''<%= buttoncalendar %>'' format="dd/mm/yyyy" enablePast="true" tabindex="107">
</ispac:htmlTextCalendar>
</nobr>
</div>
<div id="label_SGS_SUBVENCIONES:FECHA_FIN_EJECUCION" style="position: absolute; top: 183px; left: 354px;" class="formsTitleB">
<nobr>
<bean:write name="defaultForm" property="entityApp.label(SGS_SUBVENCIONES:FECHA_FIN_EJECUCION)" />:</nobr>
</div>
<div id="data_SGS_SUBVENCIONES:FECHA_FIN_EJECUCION" style="position: absolute; top: 180px; left: 490px;">
<nobr>
<ispac:htmlTextCalendar property="property(SGS_SUBVENCIONES:FECHA_FIN_EJECUCION)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="14" maxlength="10" image=''<%= buttoncalendar %>'' format="dd/mm/yyyy" enablePast="true" tabindex="108">
</ispac:htmlTextCalendar>
</nobr>
</div>
<div id="label_SGS_SUBVENCIONES:DURACION_PROYECTO" style="position: absolute; top: 213px; left: 10px;" class="formsTitleB">
<nobr>
<bean:write name="defaultForm" property="entityApp.label(SGS_SUBVENCIONES:DURACION_PROYECTO)" />:</nobr>
</div>
<div id="data_SGS_SUBVENCIONES:DURACION_PROYECTO" style="position: absolute; top: 210px; left: 190px;" class="formsTitleB">
<ispac:htmlText property="property(SGS_SUBVENCIONES:DURACION_PROYECTO)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="5" maxlength="2" tabindex="109">
</ispac:htmlText>
&nbsp;<bean:message key="common.message.months"/>
</div>
<div id="label_SGS_SUBVENCIONES:COLECTIVO_DESTINO" style="position: absolute; top: 83px; left: 10px;" class="formsTitleB">
<nobr>
<bean:write name="defaultForm" property="entityApp.label(SGS_SUBVENCIONES:COLECTIVO_DESTINO)" />:</nobr>
</div>
<div id="data_SGS_SUBVENCIONES:COLECTIVO_DESTINO" style="position: absolute; top: 80px; left: 190px;">
<ispac:htmlText property="property(SGS_SUBVENCIONES:COLECTIVO_DESTINO)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="80" maxlength="64" tabindex="104">
</ispac:htmlText>
</div>
<div id="label_SGS_SUBVENCIONES:IMPORTE_SOLICITADO" style="position: absolute; top: 243px; left: 10px;" class="formsTitleB">
<nobr>
<bean:write name="defaultForm" property="entityApp.label(SGS_SUBVENCIONES:IMPORTE_SOLICITADO)" />:</nobr>
</div>
<div id="data_SGS_SUBVENCIONES:IMPORTE_SOLICITADO" style="position: absolute; top: 240px; left: 190px;" class="formsTitleB">
<ispac:htmlText property="property(SGS_SUBVENCIONES:IMPORTE_SOLICITADO)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="15" maxlength="17" tabindex="110">
</ispac:htmlText>
&nbsp;<bean:message key="common.message.currency"/>
</div>
<div id="label_SGS_SUBVENCIONES:IMPORTE_CONCEDIDO" style="position: absolute; top: 243px; left: 372px;" class="formsTitleB">
<nobr>
<bean:write name="defaultForm" property="entityApp.label(SGS_SUBVENCIONES:IMPORTE_CONCEDIDO)" />:</nobr>
</div>
<div id="data_SGS_SUBVENCIONES:IMPORTE_CONCEDIDO" style="position: absolute; top: 240px; left: 490px;" class="formsTitleB">
<ispac:htmlText property="property(SGS_SUBVENCIONES:IMPORTE_CONCEDIDO)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="15" maxlength="17" tabindex="111">
</ispac:htmlText>
&nbsp;<bean:message key="common.message.currency"/>
</div>
<div id="label_SGS_SUBVENCIONES:PREVISION_GASTOS" style="position: absolute; top: 273px; left: 10px;" class="formsTitleB">
<nobr>
<bean:write name="defaultForm" property="entityApp.label(SGS_SUBVENCIONES:PREVISION_GASTOS)" />:</nobr>
</div>
<div id="data_SGS_SUBVENCIONES:PREVISION_GASTOS" style="position: absolute; top: 270px; left: 190px;">
<ispac:htmlTextarea property="property(SGS_SUBVENCIONES:PREVISION_GASTOS)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" rows="2" cols="80" tabindex="112">
</ispac:htmlTextarea>
</div>
<div id="label_SGS_SUBVENCIONES:IMPORTE_GASTOS" style="position: absolute; top: 313px; left: 10px;" class="formsTitleB">
<nobr>
<bean:write name="defaultForm" property="entityApp.label(SGS_SUBVENCIONES:IMPORTE_GASTOS)" />:</nobr>
</div>
<div id="data_SGS_SUBVENCIONES:IMPORTE_GASTOS" style="position: absolute; top: 310px; left: 190px;" class="formsTitleB">
<ispac:htmlText property="property(SGS_SUBVENCIONES:IMPORTE_GASTOS)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="15" maxlength="13" tabindex="113">
</ispac:htmlText>
&nbsp;<bean:message key="common.message.currency"/>
</div>
<div id="label_SGS_SUBVENCIONES:APORTACION_AYTO" style="position: absolute; top: 343px; left: 10px;" class="formsTitleB">
<nobr>
<bean:write name="defaultForm" property="entityApp.label(SGS_SUBVENCIONES:APORTACION_AYTO)" />:</nobr>
</div>
<div id="data_SGS_SUBVENCIONES:APORTACION_AYTO" style="position: absolute; top: 340px; left: 190px;" class="formsTitleB">
<ispac:htmlText property="property(SGS_SUBVENCIONES:APORTACION_AYTO)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="15" maxlength="17" tabindex="114">
</ispac:htmlText>
&nbsp;<bean:message key="common.message.currency"/>
</div>
<div id="label_SGS_SUBVENCIONES:APORTACION_ENTIDAD" style="position: absolute; top: 373px; left: 10px;" class="formsTitleB">
<nobr>
<bean:write name="defaultForm" property="entityApp.label(SGS_SUBVENCIONES:APORTACION_ENTIDAD)" />:</nobr>
</div>
<div id="data_SGS_SUBVENCIONES:APORTACION_ENTIDAD" style="position: absolute; top: 370px; left: 190px;" class="formsTitleB">
<ispac:htmlText property="property(SGS_SUBVENCIONES:APORTACION_ENTIDAD)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="15" maxlength="17" tabindex="115">
</ispac:htmlText>
&nbsp;<bean:message key="common.message.currency"/>
</div>
<div id="label_SGS_SUBVENCIONES:OTRAS_APORTACIONES" style="position: absolute; top: 403px; left: 10px;" class="formsTitleB">
<nobr>
<bean:write name="defaultForm" property="entityApp.label(SGS_SUBVENCIONES:OTRAS_APORTACIONES)" />:</nobr>
</div>
<div id="data_SGS_SUBVENCIONES:OTRAS_APORTACIONES" style="position: absolute; top: 400px; left: 190px;" class="formsTitleB">
<ispac:htmlText property="property(SGS_SUBVENCIONES:OTRAS_APORTACIONES)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" size="15" maxlength="17" tabindex="116">
</ispac:htmlText>
&nbsp;<bean:message key="common.message.currency"/>
</div>
<div id="label_SGS_SUBVENCIONES:TOTAL_APORTACIONES" style="position: absolute; top: 433px; left: 10px;" class="formsTitleB">
<nobr>
<bean:write name="defaultForm" property="entityApp.label(SGS_SUBVENCIONES:TOTAL_APORTACIONES)" />:</nobr>
</div>
<div id="data_SGS_SUBVENCIONES:TOTAL_APORTACIONES" style="position: absolute; top: 430px; left: 190px;" class="formsTitleB">
<logic:empty name="defaultForm" property="property(SGS_SUBVENCIONES:TOTAL_APORTACIONES)">0</logic:empty>
<logic:notEmpty name="defaultForm" property="property(SGS_SUBVENCIONES:TOTAL_APORTACIONES)">
	<bean:write name="defaultForm" property="property(SGS_SUBVENCIONES:TOTAL_APORTACIONES)" />
</logic:notEmpty>
&nbsp;<bean:message key="common.message.currency"/>
</div>
<div id="label_SGS_SUBVENCIONES:FINALIDAD_SUBVENCION" style="position: absolute; top: 463px; left: 10px;" class="formsTitleB">
<nobr>
<bean:write name="defaultForm" property="entityApp.label(SGS_SUBVENCIONES:FINALIDAD_SUBVENCION)" />:</nobr>
</div>
<div id="data_SGS_SUBVENCIONES:FINALIDAD_SUBVENCION" style="position: absolute; top: 460px; left: 190px;">
<ispac:htmlTextarea property="property(SGS_SUBVENCIONES:FINALIDAD_SUBVENCION)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" rows="2" cols="80" tabindex="117">
</ispac:htmlTextarea>
</div>
<div id="label_SGS_SUBVENCIONES:OBSERVACIONES" style="position: absolute; top: 503px; left: 10px;" class="formsTitleB">
<nobr>
<bean:write name="defaultForm" property="entityApp.label(SGS_SUBVENCIONES:OBSERVACIONES)" />:</nobr>
</div>
<div id="data_SGS_SUBVENCIONES:OBSERVACIONES" style="position: absolute; top: 500px; left: 190px;">
<ispac:htmlTextarea property="property(SGS_SUBVENCIONES:OBSERVACIONES)" readonly="false" propertyReadonly="readonly" styleClass="input" styleClassReadonly="inputReadOnly" rows="2" cols="80" tabindex="118">
</ispac:htmlTextarea>
</div>
</div>
</div>
</td>
</tr>
<tr>
<td height="15"><img src=''<ispac:rewrite href="img/pixel.gif"/>''/></td>
</tr>
</table>';

UPDATE spac_ct_aplicaciones SET frm_jsp = datoa, frm_version = 1 WHERE id = 10;
UPDATE spac_ct_aplicaciones SET frm_jsp = datob, frm_version = 1 WHERE id = 11;
UPDATE spac_ct_aplicaciones SET frm_jsp = datoc, frm_version = 1 WHERE id = 12;

end;
/


--
-- Ayudas
--
declare
datoa clob;
datob clob;
datoc clob;

begin

-- Procedimiento de Reclamaciones, quejas y sugerencias
datoa:='<div class="cabecera_seccion"><h4>FORMULARIO EXPEDIENTE</h4></div><p>La pantalla que se muestra es la del &#147;expediente abierto&#148;, es decir, es como si se abriera una carpeta física con un expediente en formato papel y tuviera unos separadores por: <b>Expediente, Datos específicos, Participantes y Documentos</b>.</p><p><ul><li><b>Expediente</b>: Se muestran los datos principales del expediente, en la zona superior, y del Interesado principal, en la zona inferior.</li><p><li><b>Datos específicos</b>:se muestran los datos particulares del procedimiento que se está tramitando.</li><p><li><b>Participantes</b>: se muestra el formulario para dar de alta o consultar los datos de las personas relacionadas con el Expediente.</li><p><li><b>Documentos</b>: consta de dos zonas, la superior donde se ven, en este caso los documentos con todos sus campos y se podrá acceder a abrir su imagen y la parte inferior en donde se muestran en formato tabla, todos los documentos del expediente.
<p>Los documentos se añaden al expediente, generalmente, desde los trámites de cada fase, pero hay expedientes que se diseñan de manera que se le pueden añadir documentos desde esta pestaña de Documentos.</p><p>Para ver todos los campos de información de un documento y sus imágenes, se seleccionará de la lista inferior, pulsando sobre su nombre. Se comprobará que sus datos se muestran en la parte superior. Seleccionando el botón <b>Ver documento</b> (situado debajo de las pestañas), se abrirá el documento.</p></li></ul><p>Desde el menú de la izquierda de la pantalla se podrán realizar las siguientes acciones:</p><p><ul><li>Pulsando el botón <b>Acciones</b> se podrá <b>Delegar fase</b> o <b>Clonar expediente</b>.</li><p><li>Crear un <b>Nuevo trámite</b> pulsando el botón del mismo nombre.</li><p><li>Pulsar el botón <b>Avanzar fase</b> para que el expediente que hay en pantalla avance de fase.</li><p><li>Pulsar <b> Trámites</b>  para visualizar los trámites por los que
ha pasado el expediente.</li><p><li>Pulsar <b>Expedientes relacionados</b> para visualizar los expedientes relacionados.</li></ul><div class="titulo_ayuda"><label class="popUpInfo" >Información del trámite</label></div><p>Debajo de la etiqueta <b>Trámite/Documento</b>, hay una línea informativa en donde se visualiza: el nombre del trámite actual y la fecha interna de iniciación.<p>Debajo de esa línea se encuentran los siguientes campos del Trámite:<p><ul><li><b>Departamento responsable</b>:campo que rellena la aplicación con el valor del departamento que realiza el trámite</li><p><li><b>Tramitador responsable</b>:campo que rellena la aplicación, con el nombre del usuario que lo realiza</li><p><li><b>Fecha inicio plazo</b>:campo que rellenará el usuario, seleccionando una fecha desde el  icono calendario</li><p><li><b>Plazo</b>:un número de unidades: días, meses, años para el plazo</li><p><li><b>Unidades de Plazo</b>:se seleccionará el icono Lupa y se mostrarán en una
nueva ventana, las distintas unidades de plazo existentes, de las cuales se seleccionará el valor correspondiente</li><p><li><b>Fecha Alarma</b>:este campo lo cumplimenta la aplicación y será el que se utilice para avisar al usuario tramitador, que le vence un plazo</li></ul><p>En la parte inferior de la pantalla,bajo la etiqueta: <B>DOCUMENTOS ADJUNTOS</b>, se encuentra la zona de documentos del trámite, en donde se visualizarán los documentos del trámite si los hubiera.<p>Desde esta pantalla se podrán realizar las siguientes acciones para <b>Generar documentos</b>:<p><ul><li>Pulsar <b>Desde plantilla</b> para seleccionar una plantilla de la lista de plantillas asociadas al trámite<p>El usuario pulsará sobre la que corresponda y se mostrará el documento normalizado, con los datos del expediente incluidos en él<p>Este documento, a no ser que se defina en el trámite de otra manera, es modificable, por si se quiere complementar con algún dato, cambiar una expresión, etc.
</li><p><li>Pulsar <b>Anexar fichero</b> para selección del tipo de documento que se va a anexar en el trámite</li></ul><p>Tanto si se genera un documento desde una plantilla o anexando un fichero, en la parte inferior de la pantalla de trámites se muestra el trámite con el fichero anexado y en la parte izquierda el nuevo trámite en la lista de trámites.<p>Para borrar un documento, en un trámite abierto, si se ha generado o anexado por error. Se seleccionará en la pantalla anterior el documento que se quiera borrar y se pulsará<b>Borrar documento</b>.<p>Para finalizar el trámite se pulsará <b>Terminar trámite</b>.<p>Un trámite se puede eliminar siempre que se encuentre abierto, una vez realizado, no es ni modificable. Para borrar un trámite, se seleccionará el botón de la pantalla de realización de trámites: <b>Eliminar trámite</b>.<p>Para delegar un trámite se pulsará el botón <b>Delegar</b> y se seleccionará el Destinatario.</p>
<div class="cabecera_seccion"><h4>FICHA DEL PROCEDIMIENTO</h4></div><table><tr><td colspan=4><b>DATOS TÉCNICOS DEL PROCEDIMIENTO</B></td></tr><tr><td><b>FASES</b></td><td><b>Inicio</b></td><td>Trámites</td><td>Admisión a Trámite</td></tr><tr><td colspan=3></td><td>Comunicación de apertura</td></tr><tr><td></td><td><b>Instrucción</b></td><td>Trámites</td><td>Emisión Oficio de Respuesta</td></tr><tr><td colspan=3></td><td>Notificación Oficio de Respuesta</td></tr><tr><td colspan=3></td><td>Emisión Informe</td></tr><tr><td></td><td><b>Terminación</b></td><td>Trámites</td><td>Remisión Documentación</td></tr><tr><td colspan=3></td><td>Comunicación al interesado</td></tr><tr><td colspan=3></td><td>Emisión Oficio No Admisión</td></tr><tr><td colspan=3></td><td>Notificación</td></tr><tr><td colspan=3></td><td>Archivo de Expediente</td></tr><tr><td colspan=3><b>Resolución</b></td><td>Responsable Área de Atención al Cliente</td></tr><tr><td colspan=3><b>Plazo máximo de Notificación</b></td><td>3 meses
desde la entrada de la Solicitud en el Registro</td></tr><tr><td colspan=3><b>Tipo de Tramitación</b></td><td>Presencial y Telemática</td></tr><tr><td colspan=3><b>Efectos del Silencio Administrativo</b></td><td>Estimatorio, excepto que su concesión sea contraria a la legislación urbanística o se concedan al solicitante o a terceros facultades relativas al dominio o al servicio público</td></tr><tr><td colspan=3><b>Documentación Requerida</b></td><td>Solicitud de la Reclamación, Queja o Sugerencia</td></tr><tr><td colspan=4><b>NORMATIVA APLICABLE</b></td></tr><tr><td><b>Título</b></td><td colspan=3>Ejemplo: Plan General o Ley </td></tr><tr><td><b>Ámbito</b></td><td colspan=3></td></tr><tr><td><b>Fecha Vigor</b></td><td></td><td><b>Fecha publicación</b></td><td></td></table>';

-- Procedimiento de Concesion de subvencion
datob:='<div class="cabecera_seccion"><h4>FORMULARIO EXPEDIENTE</h4></div><p>La pantalla que se muestra es la del &#147;expediente abierto&#148;, es decir, es como si se abriera una carpeta física con un expediente en formato papel y tuviera unos separadores por: <b>Expediente, Datos específicos, Participantes y Documentos</b>.</p><p><ul><li><b>Expediente</b>: Se muestran los datos principales del expediente, en la zona superior, y del Interesado principal, en la zona inferior.</li><p><li><b>Datos específicos</b>:se muestran los datos particulares del procedimiento que se está tramitando.</li><p><li><b>Participantes</b>: se muestra el formulario para dar de alta o consultar los datos de las personas relacionadas con el Expediente.</li><p><li><b>Documentos</b>: consta de dos zonas, la superior donde se ven, en este caso los documentos con todos sus campos y se podrá acceder a abrir su imagen y la parte inferior en donde se muestran en formato tabla, todos los documentos del expediente.
<p>Los documentos se añaden al expediente, generalmente, desde los trámites de cada fase, pero hay expedientes que se diseñan de manera que se le pueden añadir documentos desde esta pestaña de Documentos.</p><p>Para ver todos los campos de información de un documento y sus imágenes, se seleccionará de la lista inferior, pulsando sobre su nombre. Se comprobará que sus datos se muestran en la parte superior. Seleccionando el botón <b>Ver documento</b> (situado debajo de las pestañas), se abrirá el documento.</p></li></ul><p>Desde el menú de la izquierda de la pantalla se podrán realizar las siguientes acciones:</p><p><ul><li>Pulsando el botón <b>Acciones</b> se podrá <b>Delegar fase</b> o <b>Clonar expediente</b>.</li><p><li>Crear un <b>Nuevo trámite</b> pulsando el botón del mismo nombre.</li><p><li>Pulsar el botón <b>Avanzar fase</b> para que el expediente que hay en pantalla avance de fase.</li><p><li>Pulsar <b> Trámites</b>  para visualizar los trámites por los que
ha pasado el expediente.</li><p><li>Pulsar <b>Expedientes relacionados</b> para visualizar los expedientes relacionados.</li></ul><div class="titulo_ayuda"><label class="popUpInfo" >Información del trámite</label></div><p>Debajo de la etiqueta <b>Trámite/Documento</b>, hay una línea informativa en donde se visualiza: el nombre del trámite actual y la fecha interna de iniciación.<p>Debajo de esa línea se encuentran los siguientes campos del Trámite:<p><ul><li><b>Departamento responsable</b>:campo que rellena la aplicación con el valor del departamento que realiza el trámite</li><p><li><b>Tramitador responsable</b>:campo que rellena la aplicación, con el nombre del usuario que lo realiza</li><p><li><b>Fecha inicio plazo</b>:campo que rellenará el usuario, seleccionando una fecha desde el  icono calendario</li><p><li><b>Plazo</b>:un número de unidades: días, meses, años para el plazo</li><p><li><b>Unidades de Plazo</b>:se seleccionará el icono Lupa y se mostrarán en una
nueva ventana, las distintas unidades de plazo existentes, de las cuales se seleccionará el valor correspondiente</li><p><li><b>Fecha Alarma</b>:este campo lo cumplimenta la aplicación y será el que se utilice para avisar al usuario tramitador, que le vence un plazo</li></ul><p>En la parte inferior de la pantalla,bajo la etiqueta: <B>DOCUMENTOS ADJUNTOS</b>, se encuentra la zona de documentos del trámite, en donde se visualizarán los documentos del trámite si los hubiera.<p>Desde esta pantalla se podrán realizar las siguientes acciones para <b>Generar documentos</b>:<p><ul><li>Pulsar <b>Desde plantilla</b> para seleccionar una plantilla de la lista de plantillas asociadas al trámite<p>El usuario pulsará sobre la que corresponda y se mostrará el documento normalizado, con los datos del expediente incluidos en él<p>Este documento, a no ser que se defina en el trámite de otra manera, es modificable, por si se quiere complementar con algún dato, cambiar una expresión, etc.
</li><p><li>Pulsar <b>Anexar fichero</b> para selección del tipo de documento que se va a anexar en el trámite</li></ul><p>Tanto si se genera un documento desde una plantilla o anexando un fichero, en la parte inferior de la pantalla de trámites se muestra el trámite con el fichero anexado y en la parte izquierda el nuevo trámite en la lista de trámites.<p>Para borrar un documento, en un trámite abierto, si se ha generado o anexado por error. Se seleccionará en la pantalla anterior el documento que se quiera borrar y se pulsará<b>Borrar documento</b>.<p>Para finalizar el trámite se pulsará <b>Terminar trámite</b>.<p>Un trámite se puede eliminar siempre que se encuentre abierto, una vez realizado, no es ni modificable. Para borrar un trámite, se seleccionará el botón de la pantalla de realización de trámites: <b>Eliminar trámite</b>.<p>Para delegar un trámite se pulsará el botón <b>Delegar</b> y se seleccionará el Destinatario.</p>
<div class="cabecera_seccion"><h4>FICHA DEL PROCEDIMIENTO</h4></div><table><tr><td colspan=2><b>Nombre</b></td><td colspan=2><b>Descripción</b></td></tr><tr><td colspan=2>TSUB</td><td colspan=2>Subvención genérica</td></tr><tr><td colspan=2><b>Familia de Procedimientos</b></td><td colspan=2><b>Descripción</b></td></tr><tr><td colspan=2>Subvenciones</td><td colspan=2>Procedimiento de concesión de una Subvención</td></tr><tr><td colspan=2><b>Organismo al que pertenece</b></td><td colspan=2>Unidad organizativa concesionaria de la Subvención</td></tr><tr><td colspan=2><b>Organismo competente</b></td><td colspan=2>Área de Concesión de Subvenciones</td></tr><tr><td colspan=2><b>Organismo que tramita</b></td><td colspan=2>Área de Concesión de Subvenciones</td></tr><tr><td colspan=2><b>Organismo que resuelve</b></td><td colspan=2>Área de Concesión de Subvenciones</td></tr><tr><td colspan=2><b>Objeto</b></td>
<td colspan=2>Procedimiento administrativo para la concesión de una Subvención</td></tr><tr><td colspan=4><b>DATOS TÉCNICOS DEL PROCEDIMIENTO</b></td></tr><tr><td><b>FASES</b></td><td><b>Inicio</b></td><td>Trámites</td><td>Solicitud Subsanación</td></tr><tr><td></td><td><b>Instrucción</b></td><td>Trámites</td><td>Propuesta de Resolución</td></tr><tr><td colspan=3></td><td>Acuerdo Consejo Gobierno</td></tr><tr><td colspan=3></td><td>Notificación</td></tr><tr><td colspan=3></td><td>Alegaciones</td></tr><tr><td></td><td><b>Terminación</b></td><td>Trámites</td><td>Decreto de concesión</td></tr><tr><td colspan=3></td><td>Notificación</td></tr><tr><td colspan=3></td><td>Archivo de Expediente</td></tr><tr><td colspan=3><b>Resolución</b></td><td>Responsable Área de Atención al Cliente</td></tr><tr><td colspan=3><b>Plazo máximo de Notificación</b></td><td>3 meses desde la entrada de la Solicitud en el Registro</td></tr>
<tr><td colspan=3><b>Tipo de Tramitación</b></td><td>Presencial y Telemática</td></tr><tr><td colspan=3><b>fectos del Silencio Administrativo</b></td><td>Estimatorio, excepto que su concesión sea contraria a la legislación urbanística o se concedan al solicitante o a terceros facultades relativas al dominio o al servicio público</td></tr><tr><td colspan=3><b>Documentación Requerida</b></td><td>Solicitud de la Subvención</td></tr><tr><td colspan=3></td><td>Documentos relativos a la Subvención </td></tr><tr><td colspan=4><b>NORMATIVA APLICABLE</b></td></tr><tr><td><b>Título</b></td><td colspan=3>Ejemplo: Plan General o Ley </td></tr><tr><td><b>Ámbito</b></td><td colspan=3></td></tr><tr><td><b>Fecha Vigor</b></td><td></td><td><b>Fecha publicación</b></td><td></td></table>';

-- Procedimiento de Obras menores
datoc:='<div class="cabecera_seccion"><h4>FORMULARIO EXPEDIENTE</h4></div><p>La pantalla que se muestra es la del &#147;expediente abierto&#148;, es decir, es como si se abriera una carpeta física con un expediente en formato papel y tuviera unos separadores por: <b>Expediente, Datos específicos, Participantes y Documentos</b>.</p><p><ul><li><b>Expediente</b>: Se muestran los datos principales del expediente, en la zona superior, y del Interesado principal, en la zona inferior.</li><p><li><b>Datos específicos</b>:se muestran los datos particulares del procedimiento que se está tramitando.</li><p><li><b>Participantes</b>: se muestra el formulario para dar de alta o consultar los datos de las personas relacionadas con el Expediente.</li><p><li><b>Documentos</b>: consta de dos zonas, la superior donde se ven, en este caso los documentos con todos sus campos y se podrá acceder a abrir su imagen y la parte inferior en donde se muestran en formato tabla, todos los documentos del expediente.
<p>Los documentos se añaden al expediente, generalmente, desde los trámites de cada fase, pero hay expedientes que se diseñan de manera que se le pueden añadir documentos desde esta pestaña de Documentos.</p><p>Para ver todos los campos de información de un documento y sus imágenes, se seleccionará de la lista inferior, pulsando sobre su nombre. Se comprobará que sus datos se muestran en la parte superior. Seleccionando el botón <b>Ver documento</b> (situado debajo de las pestañas), se abrirá el documento.</p></li></ul><p>Desde el menú de la izquierda de la pantalla se podrán realizar las siguientes acciones:</p><p><ul><li>Pulsando el botón <b>Acciones</b> se podrá <b>Delegar fase</b> o <b>Clonar expediente</b>.</li><p><li>Crear un <b>Nuevo trámite</b> pulsando el botón del mismo nombre.</li><p><li>Pulsar el botón <b>Avanzar fase</b> para que el expediente que hay en pantalla avance de fase.</li><p><li>Pulsar <b> Trámites</b>  para visualizar los trámites por los que
ha pasado el expediente.</li><p><li>Pulsar <b>Expedientes relacionados</b> para visualizar los expedientes relacionados.</li></ul><div class="titulo_ayuda"><label class="popUpInfo" >Información del trámite</label></div><p>Debajo de la etiqueta <b>Trámite/Documento</b>, hay una línea informativa en donde se visualiza: el nombre del trámite actual y la fecha interna de iniciación.<p>Debajo de esa línea se encuentran los siguientes campos del Trámite:<p><ul><li><b>Departamento responsable</b>:campo que rellena la aplicación con el valor del departamento que realiza el trámite</li><p><li><b>Tramitador responsable</b>:campo que rellena la aplicación, con el nombre del usuario que lo realiza</li><p><li><b>Fecha inicio plazo</b>:campo que rellenará el usuario, seleccionando una fecha desde el  icono calendario</li><p><li><b>Plazo</b>:un número de unidades: días, meses, años para el plazo</li><p><li><b>Unidades de Plazo</b>:se seleccionará el icono Lupa y se mostrarán en una
nueva ventana, las distintas unidades de plazo existentes, de las cuales se seleccionará el valor correspondiente</li><p><li><b>Fecha Alarma</b>:este campo lo cumplimenta la aplicación y será el que se utilice para avisar al usuario tramitador, que le vence un plazo</li></ul><p>En la parte inferior de la pantalla,bajo la etiqueta: <B>DOCUMENTOS ADJUNTOS</b>, se encuentra la zona de documentos del trámite, en donde se visualizarán los documentos del trámite si los hubiera.<p>Desde esta pantalla se podrán realizar las siguientes acciones para <b>Generar documentos</b>:<p><ul><li>Pulsar <b>Desde plantilla</b> para seleccionar una plantilla de la lista de plantillas asociadas al trámite<p>El usuario pulsará sobre la que corresponda y se mostrará el documento normalizado, con los datos del expediente incluidos en él<p>Este documento, a no ser que se defina en el trámite de otra manera, es modificable, por si se quiere complementar con algún dato, cambiar una expresión, etc.
</li><p><li>Pulsar <b>Anexar fichero</b> para selección del tipo de documento que se va a anexar en el trámite</li></ul><p>Tanto si se genera un documento desde una plantilla o anexando un fichero, en la parte inferior de la pantalla de trámites se muestra el trámite con el fichero anexado y en la parte izquierda el nuevo trámite en la lista de trámites.<p>Para borrar un documento, en un trámite abierto, si se ha generado o anexado por error. Se seleccionará en la pantalla anterior el documento que se quiera borrar y se pulsará<b>Borrar documento</b>.<p>Para finalizar el trámite se pulsará <b>Terminar trámite</b>.<p>Un trámite se puede eliminar siempre que se encuentre abierto, una vez realizado, no es ni modificable. Para borrar un trámite, se seleccionará el botón de la pantalla de realización de trámites: <b>Eliminar trámite</b>.<p>Para delegar un trámite se pulsará el botón <b>Delegar</b> y se seleccionará el Destinatario.</p>
<div class="cabecera_seccion"><h4>FICHA DEL PROCEDIMIENTO</h4></div><table><tr><td colspan=2><b>Nombre</b></td><td colspan=2><b>Descripción</b></td></tr><tr><td colspan=2>TLOM</td><td colspan=2>Licencia de Obra Menor</td></tr><tr><td colspan=2><b>Familia de Procedimientos</b></td><td colspan=2><b>Descripción</b></td></tr><tr><td colspan=2>Urbanismo</td><td colspan=2>Procedimiento de Urbanismo y Área Técnica</td></tr><tr><td colspan=2><b>Organismo al que pertenece</b></td><td colspan=2>Urbanismo y Área Técnica</td></tr><tr><td colspan=2><b>Organismo competente</b></td><td colspan=2>Urbanismo y Área Técnica</td></tr><tr><td colspan=2><b>Organismo que tramita</b></td><td colspan=2>Urbanismo y Área Técnica</td></tr><tr><td colspan=2><b>Organismo que resuelve</b></td><td colspan=2>Urbanismo y Área Técnica</td></tr><tr><td colspan=2><b<Objeto</b></td><td colspan=2>Procedimiento administrativo para la concesión de Licencia de Obra Menor</td></tr>
<tr><td colspan=4><b>DATOS TÉCNICOS DEL PROCEDIMIENTO</b></td></tr><tr><td><b>FASES</b></td><td><b>Inicio</b></td><td>Trámites</td><td>Solicitud subsanación</td></tr><tr><td></td><td><b>Instrucción</b></td><td>Trámites</td><td>Emisión informe</td></tr><tr><td colspan=3></td><td>Propuesta de resolución</td></tr><tr><td colspan=3></td><td>Notificación</td></tr><tr><td colspan=3></td><td>Alegaciones</td></tr><tr><td></td><td><b>Terminación</b></td><td>Trámites</td><td>Archivo del expediente</td></tr><tr><td colspan=3></td><td>Resolución expediente</td></tr><tr><td colspan=3></td><td>Notificación resolución</td></tr><tr><td colspan=3><b>Resolución</b></td><td>TTE. Alcalde delegado de Urbanismo por delegación del Alcalde-Presidente</td></tr><tr><td colspan=3><b>Plazo máximo de Notificación</b></td><td>3 meses desde la entrada de la Solicitud en el Registro</td></tr><tr><td colspan=3><b>Tipo de Tramitación</b></td><td>Presencial y Telemática</td></tr>
<tr><td colspan=3><b>Efectos del Silencio Administrativo</b></td><td>Estimatorio, excepto que su concesión sea contraria a la legislación urbanística o se concedan al solicitante o a terceros facultades relativas al dominio o al servicio público</td></tr><tr><td colspan=3><b>Documentación Requerida</b></td><td>Solicitud de la Licencia de Obra Menor</td></tr><tr><td colspan=3></td><td>Nota Simple Registral o</td></tr><tr><td colspan=3></td><td>Certificado de la Comisión Local de Casco Histórico (vivienda en casco histórico)</td></tr><tr><td colspan=4><b>NORMATIVA APLICABLE</b></td></tr><tr><td><b>Título</b></td><td colspan=3>Ejemplo: Plan General o Ley </td></tr><tr><td><b>Ámbito</b></td><td colspan=3>de Ordenación Urbana de ...</td></tr><tr><td><b>Fecha Vigor<b></td><td></td><td><b>Fecha publicación</b></td><td></td></table>';

UPDATE spac_ayudas SET contenido = datoa WHERE idioma IS NULL AND tipo_obj=3 AND id_obj=3;
UPDATE spac_ayudas SET contenido = datob WHERE idioma IS NULL AND tipo_obj=3 AND id_obj=4;
UPDATE spac_ayudas SET contenido = datoc WHERE idioma IS NULL AND tipo_obj=3 AND id_obj=5;

end;
/
