ALTER session SET nls_length_semantics = CHAR;

--
-- Tablas
--
CREATE TABLE ACTIVIDAD_CLASIFICADA (
    ACTIVIDAD VARCHAR2(254 CHAR),
    CLASIFICACION VARCHAR2(254 CHAR),
    EMPLAZAMIENTO CLOB,
    TASAS NUMBER(14,2),
    NUMEXP VARCHAR2(30 CHAR) NOT NULL,
    ID NUMBER NOT NULL,
    ORDEN NUMBER
);

CREATE TABLE ACTIVIDAD_NO_CLASIFICADA (
    ACTIVIDAD VARCHAR2(254 CHAR),
    EMPLAZAMIENTO CLOB,
    TASAS NUMBER(14,2),
    NUMEXP VARCHAR2(30 CHAR) NOT NULL,
    ID NUMBER NOT NULL,
    ORDEN NUMBER
);

CREATE TABLE CAMB_TITULAR_LA (
    ACTIVIDAD VARCHAR2(254 CHAR),
    EMPLAZAMIENTO CLOB,
    TASAS NUMBER(14,2),
    NUMEXP VARCHAR2(30 CHAR) NOT NULL,
    ID NUMBER NOT NULL,
    FECHA_LICENCIA DATE,
    FECHA_APROBACION DATE,
    DENOMINACION VARCHAR2(254 CHAR),
    ORDEN NUMBER
);

CREATE TABLE CERT_URBANISTICO (
    FECHA_EMISION DATE,
    SITUACION VARCHAR2(500 CHAR),
    TECNICO_NOMBRE VARCHAR2(100 CHAR),
    TECNICO_CARGO VARCHAR2(50 CHAR),
    NUMEXP VARCHAR2(30 CHAR) NOT NULL,
    ID NUMBER NOT NULL,
    ORDEN NUMBER
);

CREATE TABLE CLASIFICACION_ACTIVIDADES (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(20 CHAR),
    SUSTITUTO VARCHAR2(500 CHAR),
    VIGENTE NUMBER(1,0),
    ORDEN NUMBER
);

CREATE TABLE CONTRATO (
    ID NUMBER NOT NULL,
    NUMEXP VARCHAR2(30 CHAR) NOT NULL,
    TIPO VARCHAR2(100 CHAR),
    FORMA_ADJUDICACION VARCHAR2(100 CHAR),
    PRESUPUESTO_MAXIMO NUMBER(20,2),
    APLICACION VARCHAR2(250 CHAR),
    PRECIO_ADJUDICACION NUMBER(20,2),
    PLAZO_EJECUCION INTEGER,
    UD_PLAZO VARCHAR2(1 CHAR),
    GARANTIA_PROVISIONAL NUMBER(20,2),
    GARANTIA_DEFINITIVA NUMBER(20,2),
    CLASIFICACION VARCHAR2(500 CHAR),
    FECHA_FIN_EJECUCION DATE,
    FECHA_FIN_GARANTIA DATE,
    ORDEN NUMBER
);

CREATE TABLE DATOS_TARJETA_MINUS (
    TIPO_TARJETA VARCHAR2(100 CHAR),
    FECHA_CADUCIDAD DATE,
    NUMEXP VARCHAR2(30 CHAR) NOT NULL,
    ID NUMBER NOT NULL,
    ORDEN NUMBER
);

CREATE TABLE FORMA_ADJUDICACION (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(100 CHAR),
    VIGENTE NUMBER(1,0),
    ORDEN NUMBER
);

CREATE TABLE LOTES (
    ID NUMBER NOT NULL,
    NUMEXP VARCHAR2(30 CHAR) NOT NULL,
    NOMBRE VARCHAR2(250 CHAR),
    PRESUPUESTO NUMBER(20,2),
    ORDEN NUMBER
);

CREATE TABLE OBRA_MENOR (
    ID NUMBER NOT NULL,
    NUMEXP VARCHAR2(30 CHAR) NOT NULL,
    OBRA_SOLICITADA CLOB,
    SITUACION_OBRA VARCHAR2(500 CHAR),
    PROMOTOR VARCHAR2(100 CHAR),
    DIRECTOR_OBRA VARCHAR2(100 CHAR),
    DIRECTOR_EJECUCION VARCHAR2(100 CHAR),
    PRESUPUESTO_PROMOTOR NUMBER(14,2),
    "PRESUPUESTO_TÉCNICO_MUNICIPAL" NUMBER(14,2),
    AUTOR_PROYECTO VARCHAR2(100 CHAR),
    USO_OBRA VARCHAR2(200 CHAR),
    CLASIFICACION_SUELO VARCHAR2(100 CHAR),
    CUALIFICACION_SUELO VARCHAR2(100 CHAR),
    IMPORTE_TASAS NUMBER(14,2),
    IMPORTE_ICIO NUMBER(14,2),
    TOTAL_LIQUIDACION NUMBER(14,2),
    ORDEN NUMBER
);

CREATE TABLE OFERTA (
    ID_LICITADOR INTEGER,
    IMPORTE NUMBER(20,2),
    PLAZO INTEGER,
    UD_PLAZO VARCHAR2(1 CHAR),
    NUMEXP VARCHAR2(30 CHAR) NOT NULL,
    ID NUMBER NOT NULL,
    ORDEN NUMBER
);

CREATE TABLE REBAJE_ACERA (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(100 CHAR),
    VIGENTE NUMBER(1,0),
    ORDEN NUMBER
);

CREATE TABLE RECLAMACION (
    ID NUMBER NOT NULL,
    NUMEXP VARCHAR2(30 CHAR) NOT NULL,
    TIPO VARCHAR2(64 CHAR),
    DESCRIPCION CLOB,
    DESTINATARIO VARCHAR2(32 CHAR),
    ACEPTADA VARCHAR2(2 CHAR),
    ORDEN NUMBER
);

CREATE TABLE SANCION (
    INSTRUCTOR VARCHAR2(254 CHAR),
    CALIFICACION VARCHAR2(100 CHAR),
    IMPORTE NUMBER(20,2),
    GRADO VARCHAR2(100 CHAR),
    INFRACCION CLOB,
    HECHOS CLOB,
    ACTUACION CLOB,
    NUMEXP VARCHAR2(30 CHAR) NOT NULL,
    ID NUMBER NOT NULL,
    ORDEN NUMBER
);

CREATE TABLE TIPO_CONTRATO (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(100 CHAR),
    VIGENTE NUMBER(1,0),
    ORDEN NUMBER
);

CREATE TABLE TIPO_TECNICO (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(10 CHAR),
    SUSTITUTO VARCHAR2(64 CHAR),
    VIGENTE NUMBER(1,0),
    ORDEN NUMBER
);

CREATE TABLE TIPO_VADO (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(100 CHAR),
    VIGENTE NUMBER(1,0),
    ORDEN NUMBER
);

CREATE TABLE VADO (
    NUMLICENCIA VARCHAR2(100 CHAR),
    UBICACION VARCHAR2(250 CHAR),
    TIPO VARCHAR2(100 CHAR),
    LARGOENTRADA NUMBER(14,2),
    ANCHOACERA NUMBER(14,2),
    SUPERFICIEACERA NUMBER(14,2),
    SUPERFICIELOCAL NUMBER(14,2),
    ACTIVIDAD VARCHAR2(250 CHAR),
    REBAJE VARCHAR2(100 CHAR),
    TASAS NUMBER(14,2),
    NUMEXP VARCHAR2(30 CHAR) NOT NULL,
    ID NUMBER NOT NULL,
    NUMVEHICULOS NUMBER(20,0),
    ORDEN NUMBER
);

CREATE TABLE VISTO_BUENO (
    ID NUMBER NOT NULL,
    NUMEXP VARCHAR2(30 CHAR) NOT NULL,
    TASK_NAME VARCHAR2(250 CHAR),
    VB VARCHAR2(2 CHAR),
    TASK_ID INTEGER,
    STAGE_NAME VARCHAR2(250 CHAR),
    ID_TRAM_EXP INTEGER,
    OBSERVACIONES CLOB,
    ORDEN NUMBER
);

CREATE TABLE VLDTBL_CALIF_SUELO (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(10 CHAR),
    SUSTITUTO VARCHAR2(100 CHAR),
    VIGENTE NUMBER(1,0),
    ORDEN NUMBER
);

CREATE TABLE VLDTBL_CLASIF_SUELO (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(10 CHAR),
    SUSTITUTO VARCHAR2(100 CHAR),
    VIGENTE NUMBER(1,0),
    ORDEN NUMBER
);

CREATE TABLE VLDTBL_SAN_CALIFICACION (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(100 CHAR),
    VIGENTE NUMBER(1,0),
    ORDEN NUMBER
);

CREATE TABLE VLDTBL_SAN_GRADO (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(100 CHAR),
    VIGENTE NUMBER(1,0),
    ORDEN NUMBER
);

CREATE TABLE VLDTBL_TIPO_DESTI (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(32 CHAR),
    VIGENTE NUMBER(1,0),
    ORDEN NUMBER
);

CREATE TABLE VLDTBL_TIPO_RECLAM (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(64 CHAR),
    VIGENTE NUMBER(1,0),
    ORDEN NUMBER
);

CREATE TABLE VLDTBL_TIPO_TARJETA (
    ID NUMBER NOT NULL,
    VALOR VARCHAR2(100 CHAR),
    VIGENTE NUMBER(1,0),
    ORDEN NUMBER
);
