--
-- Secuencias
--
CREATE SEQUENCE SPAC_SQ_DATOS_TARJETA_MINUS 	START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_FORMA_ADJUDICACION 		START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_ACTIVIDAD_CLASIFICA 	START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_ACTIVIDAD_NO_CLASIF 	START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_CAMB_TITULAR_LA 		START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_CERT_URBANISTICO 	START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_CLASIFICACION_ACTIV 	START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_CONTRATO 			START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_LOTES 				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_OBRA_MENOR 			START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_OFERTA 				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_SANCION 				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_VADO 				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_VLDTBL_SAN_CALIFICA 	START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_ID_VLDTBL_SAN_GRADO 	START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_REBAJE_ACERA 			START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_RECLAMACION 			START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_TIPO_CONTRATO 			START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_TIPO_TECNICO 			START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_TIPO_VADO 				START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_VISTO_BUENO 			START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_VLDTBL_CALIF_SUELO 		START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_VLDTBL_CLASIF_SUELO 	START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_VLDTBL_TIPO_DESTI 		START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_VLDTBL_TIPO_RECLAM 		START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
CREATE SEQUENCE SPAC_SQ_VLDTBL_TIPO_TARJETA 	START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  ORDER ;
