CREATE TABLE <username>.PUB_ACCIONES (
	ID int NOT NULL ,
	NOMBRE varchar (255) NULL ,
	CLASE varchar (255) NULL ,
	ACTIVA int NULL DEFAULT (0),
	DESCRIPCION varchar (255) NULL ,
	TIPO int NULL 	DEFAULT (1)
)
GO
CREATE TABLE <username>.PUB_APLICACIONES_HITOS (
	ID int NOT NULL ,
	NOMBRE varchar (255) NULL ,
	ACTIVA int NULL
)
GO
CREATE TABLE <username>.PUB_CONDICIONES (
	ID int NOT NULL ,
	NOMBRE varchar (255) NULL ,
	CLASE varchar (255) NULL ,
	DESCRIPCION varchar (255) NULL
)
GO
CREATE TABLE <username>.PUB_ERRORES (
	ID_HITO int NOT NULL ,
	ID_APLICACION int NOT NULL ,
	ID_SISTEMA varchar (32) NOT NULL ,
	ID_OBJETO varchar (64) NOT NULL ,
	DESCRIPCION varchar (255) NULL ,
	ID_ERROR int NULL
)
GO
CREATE TABLE <username>.PUB_HITOS_ACTIVOS (
	ID_HITO int NOT NULL ,
	ID_PCD int NULL ,
	ID_FASE int NULL ,
	ID_TRAMITE int NULL ,
	TIPO_DOC int NULL ,
	ID_OBJETO varchar (64) NULL ,
	ID_EVENTO int NULL ,
	ESTADO int NULL ,
	ID_APLICACION int NOT NULL ,
	IP_MAQUINA varchar (15) NULL ,
	FECHA datetime NULL ,
	ID_SISTEMA varchar (32) NOT NULL ,
	INFO_AUX text NULL ,
	ID_INFO int NULL
)
GO
CREATE TABLE <username>.PUB_REGLAS (
	ID int NOT NULL ,
	ID_PCD int NULL ,
	ID_FASE int NULL ,
	ID_TRAMITE int NULL ,
	TIPO_DOC int NULL ,
	ID_EVENTO int NULL ,
	ID_ACCION int NULL ,
	ID_CONDICION int NULL ,
	ATRIBUTOS text NULL ,
	ID_APLICACION int NULL ,
	ORDEN int NULL ,
	ID_INFO int NULL
)
GO
CREATE TABLE <username>.PUB_ULTIMO_HITO_TRATADO (
	ID_SISTEMA varchar (32) NOT NULL ,
	ID_HITO int NULL
)
GO

--
-- Tablas internas del tramitador
--
CREATE TABLE <username>.SPAC_ANOTACIONES (
	ID int NOT NULL ,
	ID_EXP int NULL ,
	ID_FASE int NULL ,
	ID_TRAMITE int NULL ,
	FECHA datetime NULL ,
	AUTOR varchar (250) NULL ,
	TEXTO varchar (4000) NULL
)
GO
CREATE TABLE <username>.SPAC_AVISOS_ELECTRONICOS (
	ID_AVISO decimal(10, 0) NOT NULL ,
	ID_PROC decimal(10, 0) NULL ,
	ID_RESP decimal(10, 0) NULL ,
	TIPO_DESTINATARIO decimal(10, 0) NULL ,
	ID_DESTINATARIO decimal(10, 0) NULL ,
	FECHA datetime NULL ,
	ID_EXPEDIENTE varchar (64) NULL ,
	ID_FASE decimal(10, 0) NULL ,
	ID_TRAMITE decimal(10, 0) NULL ,
	ID_FASE_PCD decimal(10, 0) NULL ,
	ID_TRAMITE_PCD decimal(10, 0) NULL ,
	ESTADO_AVISO decimal(10, 0) NULL ,
	MENSAJE varchar (254) NULL ,
	TIPO_AVISO varchar (64) NULL ,
	ID_MPROC decimal(10, 0) NULL ,
	UID_RESP varchar (250) NULL ,
	UID_DESTINATARIO varchar (250) NULL
)
GO
CREATE TABLE <username>.SPAC_CALENDARIOS (
	ID int NOT NULL ,
	CALENDARIO text NULL ,
	NOMBRE varchar (256) NULL

)
GO
CREATE TABLE <username>.SPAC_CT_APLICACIONES (
	ID int NOT NULL ,
	NOMBRE varchar (100) NULL ,
	DESCRIPCION varchar (250) NULL ,
	CLASE varchar (250) NULL ,
	PAGINA varchar (250) NULL ,
	PARAMETROS text NULL ,
	FORMATEADOR varchar (250) NULL ,
	XML_FORMATEADOR text NULL,
	FRM_JSP text NULL ,
	FRM_VERSION int NULL ,
	ENT_PRINCIPAL_ID int NULL ,
	ENT_PRINCIPAL_NOMBRE varchar (100) NULL ,
	DOCUMENTOS varchar (2) NULL DEFAULT ('NO')
)
GO
CREATE TABLE <username>.SPAC_CT_ENTIDADES (
	ID int NOT NULL ,
	TIPO int NULL ,
	NOMBRE varchar (100) NULL ,
	CAMPO_PK varchar (100) NULL ,
	CAMPO_NUMEXP varchar (100) NULL ,
	SCHEMA_EXPR varchar (100) NULL ,
	FRM_EDIT int NULL ,
	DESCRIPCION varchar (250) NULL ,
	SEC_PK varchar (100) NULL ,
	DEFINICION text NULL ,
	FRM_JSP text NULL ,
	FECHA datetime NULL
)
GO
CREATE TABLE <username>.SPAC_CT_ENTIDADES_RESOURCES (
	ID int NOT NULL ,
	ID_ENT int NOT NULL ,
	IDIOMA varchar (5) NULL ,
	CLAVE varchar (256) NULL ,
	VALOR varchar (250) NULL
)
GO
CREATE TABLE <username>.SPAC_CT_FASES (
	ID int NOT NULL ,
	NOMBRE varchar (250) NULL ,
	ORDEN int NULL ,
	COD_FASE varchar (16) NULL ,
	FALTA datetime NULL ,
	DESCRIPCION varchar (1024) NULL ,
	OBSERVACIONES varchar (500) NULL ,
	AUTOR varchar (64) NULL
)
GO
CREATE TABLE <username>.SPAC_CT_FRMBUSQUEDA (
	ID int NOT NULL ,
	DESCRIPCION varchar (250) NULL ,
	AUTOR varchar (100) NULL ,
	FECHA datetime NULL ,
	FRM_BSQ text NULL,
	TIPO INT
)
GO
CREATE TABLE <username>.SPAC_CT_FRMBUSQUEDA_ORG(
	ID int NOT NULL ,
	ID_SEARCHFRM int,
	UID_USR varchar(32)
)
GO
CREATE TABLE <username>.SPAC_CT_FSTR (
	ID int NOT NULL ,
	ID_FASE int NULL ,
	ID_TRAMITE int NULL
)
GO
--CREATE TABLE <username>.SPAC_CT_JERARQUIAS (
--	ID int NOT NULL ,
--	ID_ENTIDAD_PADRE int NULL ,
--	ID_ENTIDAD_HIJA int NULL ,
--	NOMBRE varchar (64) NULL ,
--	DESCRIPCION text NULL ,
--	CONSTRAINT PK_SPAC_CT_JERARQUIAS PRIMARY KEY  CLUSTERED(ID)
--)
GO
CREATE TABLE <username>.SPAC_CT_PCDORG (
	ID int NOT NULL ,
	COD_PCD varchar (100) NOT NULL ,
	ID_UNIDAD_TRAMITADORA varchar (250) NOT NULL ,
	FECHA_INI_PROD datetime NULL ,
	ORDEN int NULL
)
GO
CREATE TABLE <username>.SPAC_CT_PROCEDIMIENTOS (
	ID int NOT NULL ,
	COD_PCD varchar (100) NULL ,
	NOMBRE varchar (250) NULL ,
	ID_PADRE int NULL ,
	TITULO varchar (254) NULL ,
	OBJETO varchar (254) NULL ,
	ASUNTO varchar (512) NULL ,
	ACT_FUNC varchar (80) NULL ,
	MTRS_COMP varchar (2) NULL ,
	SIT_TLM varchar (2) NULL ,
	URL varchar (254) NULL ,
	INTERESADO varchar (64) NULL ,
	TP_REL varchar (4) NULL ,
	ORG_RSLTR varchar (80) NULL ,
	FORMA_INIC varchar (1) NULL ,
	PLZ_RESOL int NULL ,
	UNID_PLZ varchar (1) NULL ,
	FINICIO datetime NULL ,
	FFIN datetime NULL ,
	EFEC_SILEN varchar (1) NULL ,
	FIN_VIA_ADMIN varchar (2) NULL ,
	RECURSOS varchar (500) NULL ,
	FCATALOG datetime NULL ,
	AUTOR varchar (64) NULL ,
	ESTADO varchar (1) NULL ,
	NVERSION int NULL ,
	OBSERVACIONES varchar (500) NULL ,
	LUGAR_PRESENT varchar (500) NULL ,
	CNDS_ECNMCS varchar (500) NULL ,
	INGRESOS varchar (1024) NULL ,
	F_CBR_PGO varchar (1024) NULL ,
	INFR_SANC varchar (1024) NULL ,
	CALENDARIO varchar (1024) NULL ,
	DSCR_TRAM varchar (1024) NULL ,
	NORMATIVA varchar (1024) NULL ,
	CND_PARTICIP varchar (500) NULL ,
	DOCUMENTACION text NULL ,
	GRUPOS_DELEGACION varchar (1000) NULL ,
	COD_SISTEMA_PRODUCTOR varchar (2) NULL DEFAULT (0),
	MAPEO_RT text NULL
)
GO
CREATE TABLE <username>.SPAC_CT_REGLAS (
	ID int NOT NULL ,
	NOMBRE varchar (100) NULL ,
	DESCRIPCION varchar (250) NULL ,
	CLASE varchar (250) NULL ,
	TIPO int NULL
)
GO
CREATE TABLE <username>.SPAC_CT_TPDOC (
	ID int NOT NULL ,
	NOMBRE varchar (100) NULL ,
	COD_TPDOC varchar (16) NULL ,
	TIPO varchar (64) NULL ,
	AUTOR varchar (64) NULL ,
	DESCRIPCION varchar (1024) NULL ,
	FECHA datetime NULL ,
	TIPOREG varchar (64) NULL ,
	OBSERVACIONES varchar (512) NULL
)
GO
CREATE TABLE <username>.SPAC_CT_TRAMITES (
	ID int NOT NULL ,
	NOMBRE varchar (250) NULL ,
	COD_TRAM varchar (16) NULL ,
	DESCRIPCION varchar (1024) NULL ,
	TIPO varchar (32) NULL ,
	ORDENACION varchar (2) NULL ,
	OBSERVACIONES varchar (512) NULL ,
	FCREACION datetime NULL ,
	AUTOR varchar (64) NULL ,
	ID_SUBPROCESO int NULL
)
GO
CREATE TABLE <username>.SPAC_CT_TRTD (
	ID int NOT NULL ,
	ID_TRAMITE int NULL ,
	ID_TPDOC int NULL
)
GO
CREATE TABLE <username>.SPAC_CTOS_FIRMA (
	ID int NOT NULL ,
	ID_INSTANCIA_CIRCUITO int NULL ,
	FECHA datetime NULL ,
	ID_DOCUMENTO int NULL ,
	ID_CIRCUITO int NULL ,
	ID_PASO int NULL ,
	ID_FIRMANTE varchar (128) NULL ,
	NOMBRE_FIRMANTE varchar (32) NULL ,
	ESTADO int NULL
)
GO
CREATE TABLE <username>.SPAC_CTOS_FIRMA_CABECERA (
	ID_CIRCUITO int NOT NULL ,
	NUM_PASOS int NULL ,
	DESCRIPCION varchar (256) NULL ,
	TIPO INT NULL,
	SISTEMA varchar (64) NULL ,
	SECUENCIA varchar (64) NULL ,
	APLICACION varchar (64) NULL
)
GO
CREATE TABLE <username>.SPAC_P_CTOSFIRMA(
  ID INT NOT NULL,
  ID_CIRCUITO INT,
  ID_PCD INT
)
GO
CREATE TABLE <username>.SPAC_CTOS_FIRMA_DETALLE (
	ID int NOT NULL ,
	ID_CIRCUITO int NULL ,
	ID_PASO int NULL ,
	ID_FIRMANTE varchar (128) NULL ,
	NOMBRE_FIRMANTE varchar (32) NULL	,
	TIPO_NOTIF VARCHAR(2),
	DIR_NOTIF VARCHAR(64),
	TIPO_FIRMANTE VARCHAR (16) NULL
)
GO
CREATE TABLE <username>.SPAC_DOCOBJ (
	ID int NOT NULL ,
	TAM int NULL ,
	OBJ image NULL ,
	MIMETYPE varchar (40)
)
GO
CREATE TABLE <username>.SPAC_DT_DOCUMENTOS (
	ID int NOT NULL ,
	NUMEXP varchar (30) NULL ,
	FDOC datetime NULL ,
	NOMBRE varchar (100) NULL ,
	AUTOR varchar (250) NULL ,
	ID_FASE int NULL ,
	ID_TRAMITE int NULL ,
	ID_TPDOC int NULL ,
	TP_REG varchar (16) NULL ,
	NREG varchar (64) NULL ,
	FREG datetime NULL ,
	INFOPAG varchar (100) NULL ,
	ID_FASE_PCD int NULL ,
	ID_TRAMITE_PCD int NULL ,
	ESTADO varchar (16) NULL ,
	ORIGEN varchar (250) NULL ,
	DESCRIPCION varchar (250) NULL ,
	ORIGEN_ID varchar(20) NULL ,
	DESTINO varchar (250) NULL ,
	AUTOR_INFO varchar (250) NULL ,
	ESTADOFIRMA varchar (2) NULL ,
	ID_NOTIFICACION varchar(64) NULL,
	ESTADONOTIFICACION varchar (2) NULL ,
	DESTINO_ID varchar(20) NULL ,
	FNOTIFICACION datetime NULL ,
	FAPROBACION datetime NULL ,
	ORIGEN_TIPO varchar (1) NULL ,
	DESTINO_TIPO varchar (1) NULL ,
	ID_PLANTILLA numeric(18, 0) NULL ,
	BLOQUEO varchar (2) NULL ,
	REPOSITORIO varchar (8) NULL ,
	EXTENSION varchar (64) NULL ,
	FFIRMA datetime NULL ,
	INFOPAG_RDE varchar (256) NULL,
	EXTENSION_RDE varchar (64) NULL ,
	id_reg_entidad int,
	id_entidad int,
	ID_PROCESO_FIRMA text,
	ID_CIRCUITO int
)
GO
CREATE TABLE <username>.SPAC_DT_INTERVINIENTES (
	ID int NOT NULL ,
	ID_EXT varchar (32) NULL ,
	NUMEXP varchar (30) NULL ,
	ROL varchar (4) NULL ,
	TIPO int NULL ,
	TIPO_PERSONA varchar (1) NULL ,
	NDOC varchar (12) NULL ,
	NOMBRE varchar (250) NULL ,
    IDDIRECCIONPOSTAL varchar (32) NULL,
	DIRNOT varchar (250) NULL ,
	EMAIL varchar (250) NULL ,
	C_POSTAL varchar (10) NULL ,
	LOCALIDAD varchar (150) NULL ,
	CAUT varchar (150) NULL ,
	TFNO_FIJO varchar (32) NULL ,
	TFNO_MOVIL varchar (32) NULL ,
	TIPO_DIRECCION char (1) NULL ,
	DIRECCIONTELEMATICA varchar (60) NULL
)
GO
CREATE TABLE <username>.SPAC_DT_TRAMITES (
	ID int NOT NULL ,
	NUMEXP varchar (30) NULL ,
	NOMBRE varchar (250) NULL ,
	ESTADO int NULL ,
	ID_TRAM_PCD int NULL ,
	ID_FASE_PCD int NULL ,
	ID_FASE_EXP int NULL ,
	ID_TRAM_EXP int NULL ,
	ID_TRAM_CTL int NULL ,
	NUM_ACTO varchar (16) NULL ,
	COD_ACTO varchar (16) NULL ,
	ESTADO_INFO varchar (100) NULL ,
	FECHA_INICIO datetime NULL ,
	FECHA_CIERRE datetime NULL ,
	FECHA_LIMITE datetime NULL ,
	FECHA_FIN datetime NULL ,
	FECHA_INICIO_PLAZO datetime NULL ,
	PLAZO int NULL ,
	UPLAZO varchar (1) NULL ,
	OBSERVACIONES varchar (254) NULL ,
	DESCRIPCION varchar (100) NULL ,
	UND_RESP varchar (250) NULL ,
	FASE_PCD varchar (250) NULL ,
	ID_SUBPROCESO int NULL,
	ID_RESP_CLOSED varchar (250) NULL
)
GO
CREATE TABLE <username>.SPAC_REGISTROS_ES(
	ID int NOT NULL,
	NUMEXP varchar (30) NULL,
	NREG varchar(32),
	FREG datetime NULL,
	ASUNTO text NULL,
	ID_INTERESADO varchar(32),
	INTERESADO varchar(128),
	TP_REG varchar(16),
	ID_TRAMITE int,
	ORIGINO_EXPEDIENTE VARCHAR(2)
)
GO
--CREATE TABLE <username>.SPAC_ENTIDADES_RELACION_MULTIPLE (
--	ID int NOT NULL ,
--	NUMEXP varchar (30) NULL ,
--	ENTITY_ID int NULL ,
--	KEY_ID int NULL ,
--	 PRIMARY KEY  CLUSTERED (ID)
--)
GO
CREATE TABLE <username>.SPAC_EXP_RELACIONADOS (
	ID int NOT NULL ,
	NUMEXP_PADRE varchar (30) NOT NULL ,
	NUMEXP_HIJO varchar (30) NOT NULL ,
	RELACION varchar (64) NULL
)
GO
CREATE TABLE <username>.SPAC_EXPEDIENTES (
	ID int NOT NULL ,
	ID_PCD int NULL ,
	NUMEXP varchar (30) NULL ,
	REFERENCIA_INTERNA varchar (30) NULL ,
	NREG varchar (64) NULL ,
	FREG datetime NULL ,
	ESTADOINFO varchar (128) NULL ,
	FESTADO datetime NULL ,
	NIFCIFTITULAR varchar (16) NULL ,
    IDTITULAR varchar (32) NULL ,
    IDDIRECCIONPOSTAL varchar (32) NULL ,
	DOMICILIO varchar (128) NULL ,
	CIUDAD varchar (64) NULL ,
	REGIONPAIS varchar (64) NULL ,
	CPOSTAL varchar (5) NULL ,
	IDENTIDADTITULAR varchar (128) NULL ,
	TIPOPERSONA varchar (1) NULL ,
	ROLTITULAR varchar (4) NULL ,
	ASUNTO varchar (512) NULL ,
	FINICIOPLAZO datetime NULL ,
	POBLACION varchar (64) NULL ,
	MUNICIPIO varchar (64) NULL ,
	LOCALIZACION varchar (256) NULL ,
	EXPRELACIONADOS varchar (256) NULL ,
	CODPROCEDIMIENTO varchar (16) NULL ,
	NOMBREPROCEDIMIENTO varchar (128) NULL ,
	PLAZO int NULL ,
	UPLAZO varchar (1) NULL ,
	FORMATERMINACION varchar (1) NULL ,
	UTRAMITADORA varchar (256) NULL ,
	FUNCIONACTIVIDAD varchar (80) NULL ,
	MATERIAS varchar (2) NULL ,
	SERVPRESACTUACIONES varchar (128) NULL ,
	TIPODEDOCUMENTAL varchar (16) NULL ,
	PALABRASCLAVE varchar (64) NULL ,
	FCIERRE datetime NULL ,
	ESTADOADM varchar (128) NULL ,
	HAYRECURSO varchar (2) NULL ,
	EFECTOSDELSILENCIO varchar (1) NULL ,
	FAPERTURA datetime NULL ,
	OBSERVACIONES varchar (256) NULL ,
	IDUNIDADTRAMITADORA varchar (250) NULL ,
	IDPROCESO int NULL ,
	TIPODIRECCIONINTERESADO varchar (16) NULL ,
	NVERSION varchar (16) NULL ,
	IDSECCIONINICIADORA varchar (64) NULL ,
	SECCIONINICIADORA varchar (250) NULL ,
	TFNOFIJO varchar (32) NULL ,
	TFNOMOVIL varchar (32) NULL ,
	DIRECCIONTELEMATICA varchar (60) NULL
)
GO
CREATE TABLE <username>.SPAC_FASES (
	ID int NOT NULL ,
	ID_FASE_BPM varchar(64) NULL,
	ID_EXP int NULL ,
	ID_PCD int NULL ,
	ID_FASE int NULL ,
	NUMEXP varchar (30) NULL ,
	FECHA_INICIO datetime NULL ,
	FECHA_LIMITE datetime NULL ,
	ESTADO int NULL ,
	OBSERVACIONES varchar (4000) NULL ,
	ID_RESP varchar (250) NULL ,
	RESP varchar (250) NULL ,
	ID_RESP_SEC varchar (250) NULL ,
	RESP_SEC varchar (250) NULL ,
	ESTADO_PLAZO int NULL ,
	NUM_DIAS_PLAZO int NULL ,
	ID_CALENDARIO int NULL ,
	TIPO int NULL,
	FECHA_INICIO_PLAZO datetime NULL,
	ESTADO_ANTERIOR int NULL
)
GO
CREATE TABLE <username>.SPAC_GESTION_APLICACIONES (
	ID int NOT NULL ,
	NOMBRE_APLICACION_GESTION varchar (100) NULL ,
	ENLACE varchar (50) NULL ,
	CLSID varchar (50) NULL ,
	CODEBASE varchar (50) NULL ,
)
GO
CREATE TABLE <username>.SPAC_GESTION_FASES (
	ID int NOT NULL ,
	ID_PCD int NULL ,
	ID_FASE int NULL ,
	ID_APLICACION_GESTION int NOT NULL
)
GO
CREATE TABLE <username>.SPAC_HITOS (
	ID int NOT NULL ,
	ID_EXP int NULL ,
	ID_FASE int NULL ,
	ID_TRAMITE int NULL ,
	HITO int NULL ,
	FECHA datetime NULL ,
	FECHA_LIMITE datetime NULL ,
	INFO text NULL ,
	AUTOR varchar (250) NULL ,
	DESCRIPCION varchar (250) NULL ,
	ID_INFO int NULL
)
GO
CREATE TABLE <username>.SPAC_INFOTRAMITE (
	ID int NOT NULL ,
	NUMEXP varchar (30) NULL ,
	ID_TRAMITE int NULL ,
	ID_CT_TRAMITE int NULL ,
	ID_PCD int NULL ,
	ID_P_FASE int NULL ,
	INFO text NULL
)
GO
CREATE TABLE <username>.SPAC_INFOSISTEMA (
	ID int NOT NULL ,
	CODIGO varchar (16) NOT NULL ,
	VALOR varchar (16) NOT NULL ,
	FECHA_ACTUALIZACION datetime NOT NULL
)
GO
CREATE TABLE <username>.SPAC_NUMEXP_CONTADOR (
	ANIO int NOT NULL ,
	CONTADOR int NULL ,
	FORMATO varchar (32) NULL ,
	ID_PCD int NOT NULL DEFAULT (-1)
)
GO
CREATE TABLE <username>.SPAC_P_BLP (
	ID int NOT NULL ,
	NBYTES int NULL ,
	BLOQUE image NULL ,
	MIMETYPE varchar (40) NULL
)
GO
CREATE TABLE <username>.SPAC_P_ENTIDADES (
	ID int NOT NULL ,
	ID_ENT int NULL ,
	ID_PCD int NULL ,
	TP_REL int NULL ,
	ORDEN int NULL ,
	FRM_EDIT int NULL,
    FRM_READONLY int NULL,
    ID_RULE_FRM int NULL,
    ID_RULE_VISIBLE int NULL
)
GO
CREATE TABLE <username>.SPAC_P_EVENTOS (
	ID_OBJ int NOT NULL ,
	TP_OBJ int NOT NULL ,
	EVENTO int NOT NULL ,
	ORDEN int NOT NULL ,
	ID_REGLA int NULL,
	CONDICION text
)
GO
CREATE TABLE <username>.SPAC_P_FASES (
	ID int NOT NULL ,
	ID_CTFASE int NULL ,
	ID_PCD int NULL ,
	NOMBRE varchar (250) NULL ,
	ID_RESP varchar (250) NULL ,
	ID_RESP_SEC varchar (250) NULL
)
GO
CREATE TABLE <username>.SPAC_P_FLUJOS (
	ID int NOT NULL  ,
	ID_FLUJO_BPM varchar (64) NULL,
	ID_PCD int NULL ,
	ID_ORIGEN int NULL ,
	ID_DESTINO int NULL
)
GO
CREATE TABLE <username>.SPAC_P_FRMFASES (
	ID int NOT NULL ,
	ID_ENT int NULL ,
	ID_FASE int NULL ,
	FRM_EDIT int NULL,
	FRM_READONLY int NULL,
	ID_RULE_FRM int NULL,
	ID_RULE_VISIBLE int NULL
)
GO
CREATE TABLE <username>.SPAC_P_FRMTRAMITES (
	ID int NOT NULL ,
	ID_ENT int NULL ,
	ID_TRAMITE int NULL ,
	FRM_EDIT int NULL,
	FRM_READONLY int NULL,
	ID_RULE_FRM int NULL,
	ID_RULE_VISIBLE int NULL
)
GO
CREATE TABLE <username>.SPAC_P_FSTD (
	ID int NOT NULL ,
	ID_FASE int NULL ,
	ID_TPDOC int NULL
)
GO
CREATE TABLE <username>.SPAC_P_NODOS (
	ID int NOT NULL ,
	ID_NODO_BPM varchar (64) NULL ,
	ID_PCD int NULL ,
	TIPO int NULL ,
	G_INFO varchar (4000) NULL
)
GO
CREATE TABLE <username>.SPAC_P_PLANTDOC (
	ID int NOT NULL ,
	ID_TPDOC int NULL ,
	FECHA datetime NULL 	 ,
	NOMBRE varchar (250) NULL ,
	COD_PLANT varchar (16) NULL,
	EXPRESION varchar (2000) NULL ,
	MIMETYPE varchar (60) NULL ,
	PATH varchar (250) NULL ,
	ESTACION varchar (250) NULL
)
GO
CREATE TABLE <username>.SPAC_P_PLANTILLAS (
	ID int NOT NULL ,
	ID_P_PLANTDOC int NULL ,
	ID_PCD int NULL
)
GO
CREATE TABLE <username>.SPAC_P_PLAZOS (
	ID int NOT NULL ,
	PLAZO varchar (250) NULL
)
GO
CREATE TABLE <username>.SPAC_P_PROCEDIMIENTOS (
	ID int NOT NULL ,
	ID_PCD_BPM varchar (64) NULL ,
	NVERSION int NULL ,
	NOMBRE varchar (250) NULL ,
	ESTADO int NULL ,
	TIPO int NULL DEFAULT (1),
	ID_RESP varchar (250) NULL ,
	ID_RESP_SEC varchar (250) NULL ,
	ID_GROUP int NULL ,
	ID_CRT varchar (250) NULL ,
	NOMBRE_CRT varchar(250),
	TS_CRT datetime NULL ,
	ID_UPD varchar (250) NULL ,
	NOMBRE_UPD varchar(250),
	TS_UPD datetime NULL
)
GO
CREATE TABLE <username>.SPAC_P_RELPLAZOS (
	ID int NOT NULL ,
	TP_OBJ int NOT NULL ,
	ID_OBJ int NOT NULL
)
GO
CREATE TABLE <username>.SPAC_P_SINCNODO (
	ID int NOT NULL ,
	ID_PCD int NULL ,
	TIPO int NULL
)
GO
CREATE TABLE <username>.SPAC_P_TRAMITES (
	ID int NOT NULL ,
	ID_CTTRAMITE numeric(18, 0) NULL ,
	ID_TRAMITE_BPM varchar (64) NULL  ,
	ID_PCD numeric(18, 0) NULL ,
	ID_FASE numeric(18, 0) NULL ,
	NOMBRE varchar (250) NULL ,
	ORDEN int,
	OBLIGATORIO int,
	LIBRE numeric(18, 0) NULL ,
	ID_RESP varchar (250) NULL ,
	ID_RESP_SEC varchar (250) NULL ,
	ID_PCD_SUB numeric(18, 0) NULL
)
GO
CREATE TABLE <username>.SPAC_P_DEP_TRAMITES (
    ID int NOT NULL,
    ID_TRAMITE_PADRE int NOT NULL,
    ID_TRAMITE_HIJO int NOT NULL
);
GO
CREATE TABLE <username>.SPAC_P_VERSPLANT (
	ID int NOT NULL ,
	ID_PLANT int NULL ,
	FECHA datetime NULL ,
	USUARIO varchar (250) NULL ,
	ESTADO int NULL
)
GO
CREATE TABLE <username>.SPAC_PROCESOS (
	ID int NOT NULL ,
	ID_PROCESO_BPM varchar (64) NULL ,
	ID_PCD int NULL ,
	NUMEXP varchar (30) NULL ,
	ESTADO int NULL ,
	FECHA_INICIO datetime NULL ,
	FECHA_LIMITE datetime NULL ,
	FECHA_CIERRE datetime NULL ,
	ID_RESP varchar (250) NULL ,
	RESP varchar (250) NULL ,
	ID_RESP_SEC varchar (250) NULL ,
	RESP_SEC varchar (250) NULL ,
	ESTADO_PLAZO int NULL ,
	NUM_DIAS_PLAZO int NULL ,
	ID_CALENDARIO int NULL ,
	TIPO int NULL,
	FECHA_INICIO_PLAZO datetime NULL,
	FECHA_ELIMINACION  datetime NULL,
	ESTADO_ANTERIOR int NULL
)
GO
CREATE TABLE <username>.SPAC_S_BLOQUEOS (
	ID varchar (200) NULL ,
	TP_OBJ int NOT NULL ,
	ID_OBJ int NOT NULL ,
	NUMEXP varchar(30) NOT NULL,
	FECHA datetime NULL
)
GO
CREATE TABLE <username>.SPAC_S_SESIONES (
	ID varchar (200) NOT NULL ,
	FECHA datetime NULL ,
	DATOS varchar (4000) NULL ,
	USUARIO varchar (250) NULL ,
	HITS int NULL ,
	TIEMPO_OP int NULL ,
	TIEMPO_SS int NULL ,
	HOST varchar (150) NULL ,
	KEEP_ALIVE datetime NULL ,
	APLICACION varchar (32) NULL
)
GO
CREATE TABLE <username>.SPAC_S_VARS (
	ID int NOT NULL ,
	NOMBRE varchar (60) NULL ,
	VALOR varchar (4000) NULL ,
	ID_SES varchar (200) NULL
)
GO
CREATE TABLE <username>.SPAC_SINCNODO (
	ID int NOT NULL ,
	ID_EXP int NULL ,
	ID_NODO int NULL ,
	ESTADO varchar (4000) NULL ,
	ID_PCD decimal(20, 0) NULL ,
	TIPO int NULL
)
GO
CREATE TABLE <username>.SPAC_SQ_SEQUENCES (
	sequence_name varchar (100) NOT NULL ,
	sequence_id int NULL
)
GO
CREATE TABLE <username>.SPAC_SS_FECHSUSTITUCIONES (
	ID int NOT NULL ,
	FECHA_INICIO datetime NULL ,
	FECHA_FIN datetime NULL ,
	DESCRIPCION varchar (255) NULL ,
)
GO
CREATE TABLE <username>.SPAC_SS_SUSTITUCIONFECHA (
	ID int NOT NULL,
	ID_SUSTITUCION int,
	ID_FECHSUSTITUCION int
)
GO
CREATE TABLE <username>.SPAC_SS_FUNCIONES (
	ID int NOT NULL ,
	UID_USR varchar (120) NULL ,
	FUNCION int NULL
)
GO
CREATE TABLE <username>.SPAC_SS_PERMISOS (
	ID int NOT NULL ,
	ID_PCD int NULL ,
	UID_USR varchar (120) NULL ,
	PERMISO int NULL
)
GO
CREATE TABLE <username>.SPAC_SS_SUPERVISION (
	ID int NOT NULL ,
	UID_SUPERVISOR varchar (120) NULL ,
	UID_SUPERVISADO varchar (120) NULL ,
	TIPO int NULL
)
GO
CREATE TABLE <username>.SPAC_SS_SUSTITUCION (
	ID int NOT NULL ,
	UID_SUSTITUTO varchar (120) NULL ,
	UID_SUSTITUIDO varchar (120) NULL
)
GO
CREATE TABLE <username>.SPAC_TBL_001 (
	ID int NOT NULL ,
	VALOR varchar (8) NULL ,
	SUSTITUTO varchar (64) NULL ,
	VIGENTE int NULL,
	ORDEN int
)
GO
CREATE TABLE <username>.SPAC_TBL_002 (
	ID int NOT NULL ,
	VALOR varchar (8) NULL ,
	SUSTITUTO varchar (64) NULL ,
	VIGENTE int NULL,
	ORDEN int
)
GO
CREATE TABLE <username>.SPAC_TBL_003 (
	ID numeric(18, 0) NOT NULL ,
	VALOR varchar (8) NULL ,
	SUSTITUTO varchar (64) NULL ,
	VIGENTE int NULL,
	ORDEN int
)
GO
CREATE TABLE <username>.SPAC_TBL_004 (
	ID int NOT NULL ,
	VALOR varchar (8) NULL ,
	SUSTITUTO varchar (64) NULL ,
	VIGENTE int NULL,
	ORDEN int
)
GO
CREATE TABLE <username>.SPAC_TBL_005 (
	ID int NOT NULL ,
	VALOR varchar (8) NULL ,
	SUSTITUTO varchar (64) NULL ,
	VIGENTE int NULL,
	ORDEN int
)
GO
CREATE TABLE <username>.SPAC_TBL_006 (
	ID int NOT NULL ,
	VALOR varchar (8) NULL ,
	SUSTITUTO varchar (64) NULL ,
	VIGENTE int NULL,
	ORDEN int
)
GO
CREATE TABLE <username>.SPAC_TBL_007 (
	ID int NOT NULL ,
	VALOR varchar (64) NULL ,
	VIGENTE int NULL,
	ORDEN int
)
GO
CREATE TABLE <username>.SPAC_VLDTBL_TIPO_NOTIF (

	ID int NOT NULL ,
	VALOR varchar (2) NULL ,
	SUSTITUTO varchar (64) NULL ,
	VIGENTE int NULL,
	ORDEN int
)
CREATE TABLE <username>.SPAC_TBL_008 (
	ID int NOT NULL ,
	VALOR varchar (8) NULL ,
	SUSTITUTO varchar (64) NULL ,
	VIGENTE int NULL,
	ORDEN int
)
GO
CREATE TABLE <username>.SPAC_TBL_009 (
	ID int NOT NULL ,
	VALOR varchar (2) NULL ,
	VIGENTE int NULL,
	ORDEN int
)
GO
CREATE TABLE <username>.SPAC_TRAMITACIONES_AGRUPADAS (
	ID int NOT NULL ,
	ID_RESP varchar (250) NULL ,
	ESTADO int NULL ,
	ID_FASE int NULL ,
	ID_ULTIMO_TRAMITE int NULL ,
	ID_ULTIMO_TIPODOC int NULL ,
	ID_ULTIMO_TEMPLATE int NULL ,
	FECHA_CREACION datetime NULL
)
GO
CREATE TABLE <username>.SPAC_TRAMITCS_AGRUPADAS_EXPS (
	ID int NOT NULL ,
	ID_TRAM_AGRUP int NOT NULL ,
	NUMEXP varchar (30) NULL
)
GO
CREATE TABLE <username>.SPAC_TRAMITES (
	ID int NOT NULL ,
	ID_TRAMITE_BPM varchar (64) NULL ,
	ID_EXP int NULL ,
	ID_PCD int NULL ,
	ID_FASE_EXP int NULL ,
	ID_FASE_PCD int NULL ,
	ID_TRAMITE int NULL ,
	ID_CTTRAMITE int NULL ,
	NUMEXP varchar (30) NULL ,
	NOMBRE varchar (250) NULL ,
	FECHA_INICIO datetime NULL ,
	FECHA_LIMITE datetime NULL ,
	ESTADO int NULL ,
	OBSERVACIONES varchar (4000) NULL ,
	ID_RESP varchar (250) NULL ,
	RESP varchar (250) NULL ,
	ID_RESP_SEC varchar (250) NULL ,
	RESP_SEC varchar (250) NULL ,
	ESTADO_PLAZO int NULL ,
	NUM_DIAS_PLAZO int NULL ,
	ID_CALENDARIO int NULL ,
	TIPO int NULL ,
	ID_SUBPROCESO int NULL ,
	FECHA_INICIO_PLAZO datetime NULL ,
	ESTADO_ANTERIOR int NULL
)
GO
CREATE TABLE <username>.SPAC_VARS (
	ID int NOT NULL ,
	NOMBRE varchar (64) NULL ,
	VALOR text,
	DESCRIPCION varchar (256) NULL
)
GO
CREATE TABLE <username>.SPAC_VLDTBL_ACTS_FUNCS (
    ID INT NOT NULL,
    VALOR VARCHAR(8),
    SUSTITUTO VARCHAR(64),
    VIGENTE INT,
	ORDEN int
)
GO
CREATE TABLE <username>.SPAC_VLDTBL_EFEC_SLNCIO (
    ID INT NOT NULL,
    VALOR VARCHAR(8),
    SUSTITUTO VARCHAR(64),
    VIGENTE INT ,
	ORDEN int
)
GO
CREATE TABLE <username>.SPAC_VLDTBL_FORMA_INIC (
    ID INT NOT NULL,
    VALOR VARCHAR(8),
    SUSTITUTO VARCHAR(64),
    VIGENTE INT,
	ORDEN int
)
GO
CREATE TABLE <username>.SPAC_VLDTBL_MATS_COMP (
    ID INT NOT NULL,
    VALOR VARCHAR(8),
    SUSTITUTO VARCHAR(64),
    VIGENTE INT,
	ORDEN int
)
GO
CREATE TABLE <username>.SPAC_VLDTBL_RECURSOS (
    ID INT NOT NULL,
    VALOR VARCHAR(8),
    SUSTITUTO VARCHAR(64),
    VIGENTE INT,
	ORDEN int
)
GO
CREATE TABLE <username>.SPAC_VLDTBL_SIST_PRODUCTORES (
    ID INT NOT NULL,
    VALOR VARCHAR(8),
    SUSTITUTO VARCHAR(64),
    VIGENTE INT,
	ORDEN int
)
GO
CREATE TABLE <username>.SPAC_VLDTBL_SIT_TLM (
    ID INT NOT NULL,
    VALOR VARCHAR(8),
    SUSTITUTO VARCHAR(64),
    VIGENTE INT,
	ORDEN int
)
GO
CREATE TABLE <username>.SPAC_VLDTBL_TIPOREG (
    ID INT NOT NULL,
    VALOR VARCHAR(10),
    VIGENTE INT,
	ORDEN int
)
GO
CREATE TABLE <username>.SPAC_VLDTBL_TIPOS_DOCS (
    ID INT NOT NULL,
    VALOR VARCHAR(64),
    VIGENTE INT,
	ORDEN int
)
GO
CREATE TABLE <username>.SPAC_VLDTBL_TIPOS_TRAM (
    ID INT NOT NULL,
    VALOR VARCHAR(32),
    VIGENTE INT,
	ORDEN int
)
GO

CREATE TABLE <username>.SPAC_CT_INFORMES(
  	ID INT NOT NULL,
  	NOMBRE VARCHAR(100),
  	DESCRIPCION VARCHAR(255),
  	XML TEXT,
  	FECHA DATETIME,
  	TIPO int,
  	FILAS int,
  	COLUMNAS int,
	FRM_PARAMS text,
	VISIBILIDAD int DEFAULT (0)
)
GO

CREATE TABLE <username>.SPAC_CT_INFORMES_ORG(
	ID INT NOT NULL,
	ID_INFORME INT,
	UID_USR VARCHAR(255)
)

GO
CREATE TABLE <username>.SPAC_P_INFORMES (
  	ID_OBJ INT NOT NULL,
  	TP_OBJ INT NOT NULL,
  	ID_INFORME INT NOT NULL
)
GO

CREATE TABLE <username>.SPAC_CT_FRMBUSQ_INFORMES (
  	ID_FMRBUSQUEDA INT NOT NULL,
  	ID_INFORME INT NOT NULL
)
GO


CREATE TABLE <username>.SPAC_CT_JERARQUIAS(
  ID INT NOT NULL,
  ID_ENTIDAD_PADRE INT NULL,
  ID_ENTIDAD_HIJA INT NULL,
  NOMBRE VARCHAR(64),
  DESCRIPCION VARCHAR(4000) NULL,
  TIPO INT DEFAULT (1)
)
GO

CREATE TABLE <username>.SPAC_AYUDAS
(
	id 			INT				NOT NULL,
	nombre		VARCHAR(100),
	tipo_obj 	INT,
	id_obj 		INT,
	idioma 		VARCHAR(5),
	contenido   text
)

GO


CREATE TABLE <username>.SPAC_PERMISOS
(
   TP_OBJ int NOT NULL,
   ID_OBJ int NOT NULL,
   ID_RESP varchar(250) NOT NULL,
   RESP_NAME varchar(250) NOT NULL,
   PERMISO int NOT NULL
)

GO


ALTER TABLE <username>.SPAC_CT_ENTIDADES_RESOURCES ADD CONSTRAINT PK_CT_ENTRESOURCES PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_ANOTACIONES ADD CONSTRAINT PK_ANOTACIONES PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_CT_ENTIDADES ADD CONSTRAINT PK_CT_ENTIDADES PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_CT_FASES ADD CONSTRAINT PK_CT_FASES PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_P_FSTD ADD CONSTRAINT PK_P_FSTD PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_CT_FSTR ADD CONSTRAINT PK_CT_FSTR PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_CT_PCDORG ADD CONSTRAINT PK_CT_PCDORG PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_CT_PROCEDIMIENTOS ADD CONSTRAINT PK_CT_PROCEDIMIENTOS PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_CT_TPDOC ADD CONSTRAINT PK_CT_TPDOC PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_CT_TRAMITES ADD CONSTRAINT PK_CT_TRAMITES PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_CTOS_FIRMA ADD CONSTRAINT PK_CTOS_FIRMA PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_CTOS_FIRMA_CABECERA ADD CONSTRAINT PK_CTOS_FIRMA_CABECERA PRIMARY KEY (ID_CIRCUITO)
GO
ALTER TABLE <username>.SPAC_P_CTOSFIRMA ADD CONSTRAINT PK_P_CTOSFIRMA PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_CTOS_FIRMA_DETALLE ADD CONSTRAINT PK_CTOS_FIRMA_DETALLE PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_DT_DOCUMENTOS ADD CONSTRAINT PK_DT_DOCUMENTOS PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_FASES ADD CONSTRAINT PK_FASES PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_HITOS ADD CONSTRAINT PK_HITOS PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_P_ENTIDADES ADD CONSTRAINT PK_P_ENTIDADES PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_P_FASES ADD CONSTRAINT PK_P_FASES PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_P_FLUJOS ADD CONSTRAINT PK_P_FLUJOS PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_P_NODOS ADD CONSTRAINT PK_P_NODOS PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_P_PLANTDOC ADD CONSTRAINT PK_P_PLANTDOC PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_P_PROCEDIMIENTOS ADD CONSTRAINT PK_P_PROCEDIMIENTOS PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_P_TRAMITES ADD CONSTRAINT PK_P_TRAMITES PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_P_DEP_TRAMITES ADD CONSTRAINT PK_P_DEP_TRAMITES PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_CT_TRTD ADD CONSTRAINT PK_CT_TRTD PRIMARY KEY (ID)
GO
ALTER TABLE <username>.PUB_ACCIONES ADD CONSTRAINT PK_PUB_ACCIONES PRIMARY KEY (ID)
GO
ALTER TABLE <username>.PUB_APLICACIONES_HITOS ADD CONSTRAINT PK_PUB_APLICACIONES_HITOS PRIMARY KEY (ID)
GO
ALTER TABLE <username>.PUB_CONDICIONES ADD CONSTRAINT PK_PUB_CONDICIONES PRIMARY KEY (ID)
GO
ALTER TABLE <username>.PUB_ERRORES ADD CONSTRAINT PK_PUB_ERRORES PRIMARY KEY (ID_HITO, ID_APLICACION, ID_SISTEMA, ID_OBJETO)
GO
ALTER TABLE <username>.PUB_HITOS_ACTIVOS ADD CONSTRAINT PK_PUB_HITOS_ACTIVOS PRIMARY KEY (ID_HITO, ID_APLICACION, ID_SISTEMA)
GO
ALTER TABLE <username>.PUB_REGLAS ADD CONSTRAINT PK_PUB_REGLAS PRIMARY KEY (ID)
GO
ALTER TABLE <username>.PUB_ULTIMO_HITO_TRATADO ADD CONSTRAINT PK_PUB_ULTIMO_HITO_TRATADO PRIMARY KEY (ID_SISTEMA)
GO
ALTER TABLE <username>.SPAC_CALENDARIOS ADD CONSTRAINT PK_SPAC_CALENDARIOS PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_CT_APLICACIONES ADD CONSTRAINT PK_SPAC_CT_APLICACIONES PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_CT_FRMBUSQUEDA ADD CONSTRAINT PK_SPAC_CT_FRMBUSQUEDA PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_CT_FRMBUSQUEDA_ORG ADD CONSTRAINT PK_SPAC_CT_FRMBUSQUEDA_ORG PRIMARY KEY (ID);
GO
ALTER TABLE <username>.SPAC_CT_REGLAS ADD CONSTRAINT PK_SPAC_CT_REGLAS PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_DOCOBJ ADD CONSTRAINT PK_SPAC_DOCOBJ PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_DT_INTERVINIENTES ADD CONSTRAINT PK_SPAC_DT_INTERVINIENTES PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_EXP_RELACIONADOS ADD CONSTRAINT PK_SPAC_EXP_RELACIONADOS PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_INFOTRAMITE ADD CONSTRAINT PK_SPAC_INFOTRAMITE PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_P_BLP ADD CONSTRAINT PK_SPAC_P_BLP PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_P_FRMFASES ADD CONSTRAINT PK_SPAC_P_FRMFASES PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_P_FRMTRAMITES ADD CONSTRAINT PK_SPAC_P_FRMTRAMITES PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_P_PLAZOS ADD CONSTRAINT PK_SPAC_P_PLAZOS PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_P_RELPLAZOS ADD CONSTRAINT PK_SPAC_P_RELPLAZOS PRIMARY KEY (ID, TP_OBJ, ID_OBJ)
GO
ALTER TABLE <username>.SPAC_P_SINCNODO ADD CONSTRAINT PK_SPAC_P_SINCNODO PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_P_EVENTOS ADD CONSTRAINT PK_SPAC_PEVENTOS PRIMARY KEY (EVENTO, TP_OBJ, ORDEN, ID_OBJ)
GO
ALTER TABLE <username>.SPAC_PROCESOS ADD CONSTRAINT PK_SPAC_PROCESOS PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_S_BLOQUEOS ADD CONSTRAINT PK_SPAC_S_BLOQUEOS PRIMARY KEY (TP_OBJ, ID_OBJ, NUMEXP)
GO
ALTER TABLE <username>.SPAC_S_SESIONES ADD CONSTRAINT PK_SPAC_S_SESIONES PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_S_VARS ADD CONSTRAINT PK_SPAC_S_VARS PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_SINCNODO ADD CONSTRAINT PK_SPAC_SINCNODO PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_SS_FUNCIONES ADD CONSTRAINT PK_SPAC_SS_FUNCIONES PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_SS_PERMISOS ADD CONSTRAINT PK_SPAC_SS_PERMISOS PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_SS_SUPERVISION ADD CONSTRAINT PK_SPAC_SS_SUPERVISION PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_TBL_001 ADD CONSTRAINT PK_SPAC_TBL_001 PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_TBL_002 ADD CONSTRAINT PK_SPAC_TBL_002 PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_TBL_003 ADD CONSTRAINT PK_SPAC_TBL_003 PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_TBL_004 ADD CONSTRAINT PK_SPAC_TBL_004 PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_TBL_005 ADD CONSTRAINT PK_SPAC_TBL_005 PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_TBL_006 ADD CONSTRAINT PK_SPAC_TBL_006 PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_TBL_007 ADD CONSTRAINT PK_SPAC_TBL_007 PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_VLDTBL_TIPO_NOTIF ADD CONSTRAINT PK_SPAC_VLDTBL_TIPO_NOTIF PRIMARY KEY (ID)

ALTER TABLE <username>.SPAC_TBL_008 ADD CONSTRAINT PK_SPAC_TBL_008 PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_TBL_009 ADD CONSTRAINT PK_SPAC_TBL_009 PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_VLDTBL_ACTS_FUNCS ADD CONSTRAINT PK_SPAC_VLDTBL_ACTS_FUNCS PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_VLDTBL_EFEC_SLNCIO ADD CONSTRAINT PK_SPAC_VLDTBL_EFEC_SLNCIO PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_VLDTBL_FORMA_INIC ADD CONSTRAINT PK_SPAC_VLDTBL_FORMA_INIC PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_VLDTBL_MATS_COMP ADD CONSTRAINT PK_SPAC_VLDTBL_MATS_COMP PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_VLDTBL_RECURSOS ADD CONSTRAINT PK_SPAC_VLDTBL_RECURSOS PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_VLDTBL_SIST_PRODUCTORES ADD CONSTRAINT PK_SPAC_TBL_SIST_PRODUCTORES PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_VLDTBL_SIT_TLM ADD CONSTRAINT PK_SPAC_VLDTBL_SIT_TLM PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_VLDTBL_TIPOREG ADD CONSTRAINT PK_SPAC_VLDTBL_TIPOREG PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_VLDTBL_TIPOS_DOCS ADD CONSTRAINT PK_SPAC_VLDTBL_TIPOS_DOCS PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_VLDTBL_TIPOS_TRAM ADD CONSTRAINT PK_SPAC_VLDTBL_TIPOS_TRAM PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_TRAMITACIONES_AGRUPADAS ADD CONSTRAINT PK_SPAC_TRAMTCS_AGRUPADAS PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_TRAMITCS_AGRUPADAS_EXPS ADD CONSTRAINT PK_SPAC_TRAMTCS_AGRUPADAS_EXPS PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_VARS ADD CONSTRAINT PK_SPAC_VARS PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_TRAMITES ADD CONSTRAINT PK_TRAMITES PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_AVISOS_ELECTRONICOS ADD CONSTRAINT SPAC_AVISOS_ELEC_IDX01 PRIMARY KEY (ID_AVISO)
GO
ALTER TABLE <username>.SPAC_CT_APLICACIONES ADD CONSTRAINT SPAC_CT_APLICACIONES_NOM_KEY UNIQUE (NOMBRE)
GO
ALTER TABLE <username>.SPAC_CT_FRMBUSQUEDA ADD CONSTRAINT SPAC_CT_FRMBUSQUEDA_DESC_KEY UNIQUE (DESCRIPCION)
GO
ALTER TABLE <username>.SPAC_P_PLANTILLAS ADD CONSTRAINT SPAC_P_PLANTILLAS_PKEY PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_DT_TRAMITES ADD CONSTRAINT SPAC_PK_DTTRAMITES PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_REGISTROS_ES ADD CONSTRAINT SPAC_PK_REGISTROS_ES PRIMARY KEY (ID)
GO
ALTER TABLE <username>.SPAC_SS_SUSTITUCION ADD CONSTRAINT PK_SPAC_SS_SUSTITUCION PRIMARY KEY (ID);
GO
ALTER TABLE <username>.SPAC_SS_FECHSUSTITUCIONES ADD CONSTRAINT PK_SPAC_SS_FECHSUSTITUCIONES PRIMARY KEY (ID);
GO
ALTER TABLE <username>.SPAC_SS_SUSTITUCIONFECHA ADD CONSTRAINT PK_SPAC_SS_SUSTITUCIONFECHA PRIMARY KEY (ID);
GO
ALTER TABLE <username>.SPAC_NUMEXP_CONTADOR ADD CONSTRAINT PK_SPAC_NUMEXP_CONTADOR PRIMARY KEY (ID_PCD);
GO
ALTER TABLE <username>.SPAC_CT_INFORMES ADD CONSTRAINT PK_SPAC_CT_INFORMES PRIMARY KEY (ID);
GO
ALTER TABLE <username>.SPAC_P_INFORMES ADD CONSTRAINT PK_SPAC_P_INFORMES PRIMARY KEY (ID_OBJ, TP_OBJ, ID_INFORME);
GO
ALTER TABLE <username>.SPAC_CT_INFORMES_ORG ADD CONSTRAINT PK_SPAC_CT_INFORMES_ORG PRIMARY KEY (ID);

GO
ALTER TABLE <username>.SPAC_SQ_SEQUENCES ADD CONSTRAINT PK_SPAC_SQ_SEQUENCES PRIMARY KEY (SEQUENCE_NAME)
GO
ALTER TABLE <username>.SPAC_CT_JERARQUIAS ADD CONSTRAINT PK_SPAC_CT_JERARQUIAS PRIMARY KEY (ID)
GO

ALTER TABLE <username>.SPAC_AYUDAS ADD CONSTRAINT PK_SPAC_AYUDAS PRIMARY KEY (ID)
GO

ALTER TABLE <username>.SPAC_PERMISOS ADD CONSTRAINT PK_SPAC_PERMISOS PRIMARY KEY (TP_OBJ, ID_OBJ, ID_RESP , PERMISO)


GO

--
-- RESTRICCIONES
--
ALTER TABLE <username>.SPAC_CT_FASES ADD CONSTRAINT U_CT_FASES UNIQUE (NOMBRE)
GO
ALTER TABLE <username>.SPAC_CT_REGLAS ADD CONSTRAINT U_CT_REGLAS_CLASE UNIQUE (CLASE)
GO
ALTER TABLE <username>.SPAC_CT_REGLAS ADD CONSTRAINT U_CT_REGLAS_NOMBRE UNIQUE (NOMBRE)
GO
ALTER TABLE <username>.SPAC_CT_TPDOC ADD CONSTRAINT U_CT_TPDOC UNIQUE (NOMBRE)
GO
ALTER TABLE <username>.SPAC_CT_TRAMITES ADD CONSTRAINT U_CT_TRAMITES UNIQUE (NOMBRE)
GO
ALTER TABLE <username>.SPAC_CTOS_FIRMA_CABECERA ADD CONSTRAINT U_CTOS_FIRMA_CABECERA UNIQUE (ID_CIRCUITO)
GO
ALTER TABLE <username>.SPAC_CTOS_FIRMA_DETALLE ADD CONSTRAINT U_CTOS_FIRMA_DEFINICION UNIQUE (ID)
GO
ALTER TABLE <username>.SPAC_SS_FUNCIONES ADD CONSTRAINT U_SPAC_SS_FUNCIONES UNIQUE (UID_USR, FUNCION)
GO
ALTER TABLE <username>.SPAC_SS_PERMISOS ADD CONSTRAINT U_SPAC_SS_PERMISOS UNIQUE (UID_USR, PERMISO, ID_PCD)
GO
ALTER TABLE <username>.SPAC_SS_SUPERVISION ADD CONSTRAINT U_SPAC_SS_SUPERVISION UNIQUE (UID_SUPERVISOR, UID_SUPERVISADO)
GO
ALTER TABLE <username>.SPAC_GESTION_APLICACIONES ADD CONSTRAINT PK_SPAC_APLICACION_GESTION PRIMARY KEY (ID);
GO
ALTER TABLE <username>.SPAC_SS_SUSTITUCION ADD CONSTRAINT U_SPAC_SS_SUSTITUCION UNIQUE (UID_SUSTITUTO, UID_SUSTITUIDO);
GO


--
-- ÍNDICES
--
CREATE INDEX SPAC_AVISOS_ELEC_IDX02 ON <username>.SPAC_AVISOS_ELECTRONICOS (ID_AVISO, ID_DESTINATARIO, ESTADO_AVISO, TIPO_DESTINATARIO)
GO
CREATE INDEX SPAC_IND_CT_PROCEDIMIENTOS ON <username>.SPAC_CT_PROCEDIMIENTOS (NOMBRE)
GO
CREATE INDEX SPAC_IND_P_PCDS_ID_GROUP ON <username>.SPAC_P_PROCEDIMIENTOS (ID_GROUP)
GO
CREATE INDEX SPAC_IND_P_PCDS_NOMBRE ON <username>.SPAC_P_PROCEDIMIENTOS (NOMBRE)
GO
CREATE UNIQUE INDEX UI_CT_FSTR ON <username>.SPAC_CT_FSTR (ID_FASE, ID_TRAMITE)
GO
CREATE UNIQUE INDEX UI_CT_TRTD ON <username>.SPAC_CT_TRTD (ID_TPDOC, ID_TRAMITE)
GO
CREATE UNIQUE INDEX UI_P_FSTD ON <username>.SPAC_P_FSTD (ID_FASE, ID_TPDOC)
GO

CREATE INDEX SPAC_EXPEDIENTES_IX_NUMEXP ON <username>.SPAC_EXPEDIENTES (NUMEXP);
GO
CREATE INDEX SPAC_DT_DOCUMENTOS_IX_NUMEXP ON <username>.SPAC_DT_DOCUMENTOS (NUMEXP);
GO
CREATE INDEX SPAC_DT_TRAMITES_IX_NUMEXP ON <username>.SPAC_DT_TRAMITES (NUMEXP);
GO
CREATE INDEX SPAC_DT_TRAMITES_IX_IDTRAMEXP ON  <username>.SPAC_DT_TRAMITES (ID_TRAM_EXP);
GO
CREATE INDEX SPAC_DT_INT_IX_NUMEXP ON  <username>.SPAC_DT_INTERVINIENTES (NUMEXP);
GO
CREATE INDEX SPAC_REGISTROS_ES_IX_NUMEXP ON <username>.SPAC_REGISTROS_ES (NUMEXP);
GO
CREATE INDEX SPAC_PROCESOS_IX_NUMEXP ON <username>.SPAC_PROCESOS (NUMEXP);
GO
CREATE INDEX SPAC_PROCESOS_IX_IDRESP ON <username>.SPAC_PROCESOS (ID_RESP);
GO
CREATE INDEX SPAC_FASES_IX_NUMEXP ON <username>.SPAC_FASES (NUMEXP);
GO
CREATE INDEX SPAC_FASES_IX_IDRESP ON <username>.SPAC_FASES (ID_RESP);
GO
CREATE INDEX SPAC_TRAMITES_IX_NUMEXP ON <username>.SPAC_TRAMITES (NUMEXP);
GO
CREATE INDEX SPAC_TRAMITES_IX_IDRESP ON <username>.SPAC_TRAMITES (ID_RESP);
GO
CREATE INDEX SPAC_PERMISOS_IX_TP_ID_OBJ ON SPAC_PERMISOS (TP_OBJ, ID_OBJ);
GO
CREATE INDEX SPAC_PERMISOS_IX_PERMISO ON SPAC_PERMISOS (PERMISO);


