CREATE PROCEDURE <username>.spac_nextval
	@sequence varchar(100),
	@sequence_id INT OUTPUT
AS
-- return an error if sequence does not exist
-- so we will know if someone truncates the table
	SET @sequence_id = -1
	
	UPDATE <username>.SPAC_SQ_SEQUENCES
	SET    @sequence_id = sequence_id = sequence_id + 1
	WHERE  sequence_name = @sequence
RETURN @sequence_id

GO


-- Secuencias para las tablas internas
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_ANOTACIONES');
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_AVISOS_ELECTRONICOS'); 	
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_CTAPLICACIONES'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_CTENTIDADES'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_CTFASES'); 			
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_CTFRMBUSQUEDA'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_CTFRMBUSQUEDA_ORG'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_CTFSTR'); 			
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_CTOS_FIRMA'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_CTOS_FIRMA_CABECERA'); 	
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_CTOS_FIRMA_DETALLE'); 	
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_CTOS_FIRMA_INSTANCE'); 	
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_CTPCDORG'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_CTREGLAS'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_CTTPDOC'); 			
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_CTTRAMITES'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_CTTRTD'); 			
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_DOCOBJ'); 			
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_DTDOCUMENTOS'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_DTINTERVINIENTES'); 	
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_DTTRAMITES'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_ENTIDADESRESOURCES'); 	
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_EXP_RELACIONADO'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_EXPEDIENTES');
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_REGISTROSES');
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_FASES'); 			
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_HITOS'); 			
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_INFOTRAMITE'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_INFOSISTEMA'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_P_PLANTILLAS'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_PENTIDADES'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_PEVENTOS'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_PFLUJOS'); 			
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_PFRMFASES'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_PFRMTRAMITES'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_PFSTD'); 			
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_PNODOS'); 			
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_PPLANTILLAS'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_PPLAZOS'); 			
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_PPROCEDIMIENTOS'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_PROCESOS'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_PTRAMITES'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_PDEPTRAMITES');
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_SINCNODOS'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_SSFUNCIONES'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_SSPERMISOS'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_SSSUPERV'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_SVARS'); 			
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_TRAMITACION_AGRUPADA'); 	
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_TRAMTCS_GROUP_EXPS'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_TRAMITES'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_VARS'); 			
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_PCTOSFIRMA'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_CALENDARIOS');
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_SSSUSTITUCION');
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_SSFECHSUSTITUCIONES');
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_SSSUSTITUCIONFECHA');
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_CTINFORMES');
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_CTINFORMES_ORG');
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_CTJERARQUIAS');
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_ID_AYUDAS');


GO                             
-- Secuencias para las tablas de validación			                                        
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_SPAC_TBL_001'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_SPAC_TBL_002'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_SPAC_TBL_003'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_SPAC_TBL_004'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_SPAC_TBL_005'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_SPAC_TBL_006'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_SPAC_TBL_008'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_SPAC_TBL_009'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_SPAC_VLDTBL_ACTS_FUNCS'); 	
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_SPAC_VLDTBL_EFEC_SLNC'); 	
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_SPAC_VLDTBL_FORMA_INIC'); 	
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_SPAC_VLDTBL_MATS_COMP'); 	
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_SPAC_VLDTBL_RECURSOS'); 	
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_SPAC_VLDTBL_SIST_PROD'); 	
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_SPAC_VLDTBL_SIT_TLM'); 	
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_SPAC_VLDTBL_TIPOREG'); 	
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_SPAC_VLDTBL_TIPOS_DOCS'); 	
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_SPAC_VLDTBL_TIPOS_TRAM'); 	
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_SPAC_TBL_007'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_VLDTBL_TIPO_NOTIF')

GO  								                                        
-- Secuencias para el publicador				                                        
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('PUB_SQ_ID_ACCIONES'); 			
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('PUB_SQ_ID_APLICACIONES_HITOS'); 	
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('PUB_SQ_ID_CONDICIONES'); 		
INSERT INTO <username>.SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('PUB_SQ_ID_REGLAS'); 			
GO

UPDATE <username>.SPAC_SQ_SEQUENCES SET SEQUENCE_ID = 0 WHERE SEQUENCE_ID IS NULL;
GO             
