-----------------------------
-- INDEX KEYS INVESDOC     --
-----------------------------
CREATE UNIQUE INDEX IDOCAPPEVENT1
ON IDOCAPPEVENT (APPID, EVENTID)
;
CREATE INDEX IDOCARCHDET1
ON IDOCARCHDET (ARCHID, DETTYPE)
;
CREATE INDEX IDOCARCHDET2
ON IDOCARCHDET (ARCHID)
;
CREATE INDEX IDOCARCHHDR1
ON IDOCARCHHDR (ID)
;
CREATE INDEX IDOCARCHHDR2
ON IDOCARCHHDR (TYPE)
;
CREATE UNIQUE INDEX IDOCAUTONUMCTLG1
ON IDOCAUTONUMCTLG (ID)
;
CREATE UNIQUE INDEX IDOCAUTONUMCTLG2
ON IDOCAUTONUMCTLG (NAME)
;
CREATE UNIQUE INDEX IDOCBTBLCTLG1
ON IDOCBTBLCTLG (ID)
;
CREATE INDEX IDOCCOMPUSG1
ON IDOCCOMPUSG (COMPID, COMPTYPE)
;
CREATE INDEX IDOCDATNODE1
ON IDOCDATNODE (ID, TYPE)
;
CREATE INDEX IDOCDATNODE2
ON IDOCDATNODE (PARENTID)
;
CREATE INDEX IDOCDATNODE3
ON IDOCDATNODE (TYPE)
;
CREATE UNIQUE INDEX IDOCDBCTLG1
ON IDOCDBCTLG (ID)
;
CREATE UNIQUE INDEX IDOCDBCTLG2
ON IDOCDBCTLG (NAME)
;
CREATE INDEX IDOCDIRHDR1
ON IDOCDIRHDR (ID)
;
CREATE INDEX IDOCDIRHDR2
ON IDOCDIRHDR (TYPE)
;
CREATE INDEX IDOCFDRLINK1
ON IDOCFDRLINK (ID)
;
CREATE INDEX IDOCFDRLINK2
ON IDOCFDRLINK (CNTRDBID, CNTRARCHID, CNTRFDRID, CNTRCLFID)
;
CREATE INDEX IDOCFDRLINK3
ON IDOCFDRLINK (SRVRDBID, SRVRARCHID, SRVRFDRID)
;
CREATE INDEX IDOCFDRLINKX1
ON IDOCFDRLINKX (ID)
;
CREATE INDEX IDOCFDRLINKX2
ON IDOCFDRLINKX (CNTRDBID, CNTRARCHID, CNTRFDRID, CNTRCLFID)
;
CREATE INDEX IDOCFDRLINKX3
ON IDOCFDRLINKX (SRVRDBID, SRVRARCHID, SRVRFDRID)
;
CREATE INDEX IDOCFDRSTAT1
ON IDOCFDRSTAT (ARCHID, FDRID)
;
CREATE INDEX IDOCFDRSTAT2
ON IDOCFDRSTAT (STAT)
;
CREATE UNIQUE INDEX IDOCFIAUXTBLCTLG1
ON IDOCFIAUXTBLCTLG (ID)
;
CREATE INDEX IDOCFIAUXTBLCTLG2
ON IDOCFIAUXTBLCTLG (NAME)
;
CREATE INDEX IDOCFIAUXTBLCTLG3
ON IDOCFIAUXTBLCTLG (USERID)
;
CREATE UNIQUE INDEX IDOCFMT1
ON IDOCFMT (ID)
;
CREATE INDEX IDOCFMT2
ON IDOCFMT (ARCHID, TYPE)
;
CREATE INDEX IDOCGLBDOCH1
ON IDOCGLBDOCH (ID)
;
CREATE INDEX IDOCGLBDOCH2
ON IDOCGLBDOCH (ARCHID, FDRID)
;
CREATE INDEX IDOCGLBDOCH3
ON IDOCGLBDOCH (ARCHID, FDRID, CLFID)
;
CREATE UNIQUE INDEX IDOCMACRO1
ON IDOCMACRO (ID)
;
CREATE UNIQUE INDEX IDOCMACRO2
ON IDOCMACRO (NAME)
;
CREATE UNIQUE INDEX IDOCNEXTID1
ON IDOCNEXTID (TYPE)
;
CREATE UNIQUE INDEX IDOCPAGEANNS1
ON IDOCPAGEANNS (ID)
;
CREATE UNIQUE INDEX IDOCPICT1
ON IDOCPICT (ID)
;
CREATE UNIQUE INDEX IDOCPICT2
ON IDOCPICT (NAME)
;
CREATE UNIQUE INDEX IDOCPREFFMT1
ON IDOCPREFFMT (ARCHID, FMTTYPE, USERID)
;
CREATE UNIQUE INDEX IDOCPREFWFMT1
ON IDOCPREFWFMT (ARCHID, FMTTYPE, USERID)
;
CREATE INDEX IDOCRPT1
ON IDOCRPT (ID)
;
CREATE INDEX IDOCRPT2
ON IDOCRPT (ARCHID)
;
CREATE UNIQUE INDEX IDOCRPTAUXTBL1
ON IDOCRPTAUXTBL (FDRID)
;
CREATE INDEX IDOCSRVSTATEDET1
ON IDOCSRVSTATEDET (ID)
;
CREATE INDEX IDOCSRVSTATEDET2
ON IDOCSRVSTATEDET (SESSIONID)
;
CREATE INDEX IDOCSRVSTATEDET3
ON IDOCSRVSTATEDET (PARENTID)
;
CREATE UNIQUE INDEX IDOCSRVSTATEHDR1
ON IDOCSRVSTATEHDR (ID)
;
CREATE INDEX IDOCSRVSTATEHDR2
ON IDOCSRVSTATEHDR (USERID, PRODID)
;
CREATE INDEX IDOCSRVSTATEHDR3
ON IDOCSRVSTATEHDR (timestamp)
;
CREATE UNIQUE INDEX IDOCVTBLCTLG1
ON IDOCVTBLCTLG (ID)
;
CREATE UNIQUE INDEX IDOCWMACRO1
ON IDOCWMACRO (ID)
;
CREATE UNIQUE INDEX IDOCWMACRO2
ON IDOCWMACRO (NAME)
;
CREATE UNIQUE INDEX IDOCXNEXTID1
ON IDOCXNEXTID (TYPE, PARENTID)
;
CREATE INDEX ITDSMSSESS1
ON ITDSMSSESS (CID)
;
CREATE INDEX ITDSMSSESS2
ON ITDSMSSESS (CAPPID)
;
CREATE INDEX ITDSMSSESS3
ON ITDSMSSESS (CUSERID)
;
CREATE UNIQUE INDEX IUSERCURRCNT1
ON IUSERCURRCNT (ID)
;
CREATE UNIQUE INDEX IUSERCURRCNT2
ON IUSERCURRCNT (USERID, PRODID, APPID)
;
CREATE UNIQUE INDEX IUSERDEPTHDR1
ON IUSERDEPTHDR (ID)
;
CREATE INDEX IUSERDEPTHDR2
ON IUSERDEPTHDR (NAME)
;
CREATE INDEX IUSERDEPTHDR3
ON IUSERDEPTHDR (PARENTID)
;
CREATE INDEX IUSERDEPTHDR4
ON IUSERDEPTHDR (MGRID)
;
CREATE INDEX IUSERDEPTHDR5
ON IUSERDEPTHDR (TYPE)
;
CREATE INDEX IUSERGENPERMS1
ON IUSERGENPERMS (DSTTYPE, DSTID)
;
CREATE INDEX IUSERGENPERMS2
ON IUSERGENPERMS (DSTTYPE, DSTID, PRODID)
;
CREATE UNIQUE INDEX IUSERGROUPHDR1
ON IUSERGROUPHDR (ID)
;
CREATE INDEX IUSERGROUPHDR2
ON IUSERGROUPHDR (NAME)
;
CREATE INDEX IUSERGROUPHDR3
ON IUSERGROUPHDR (MGRID)
;
CREATE INDEX IUSERGROUPHDR4
ON IUSERGROUPHDR (TYPE)
;
CREATE INDEX IUSERGROUPUSER1
ON IUSERGROUPUSER (GROUPID)
;
CREATE INDEX IUSERGROUPUSER2
ON IUSERGROUPUSER (USERID)
;
CREATE UNIQUE INDEX IUSERLDAPGRPHDR1
ON IUSERLDAPGRPHDR (ID)
;
CREATE UNIQUE INDEX IUSERLDAPGRPHDR2
ON IUSERLDAPGRPHDR (LDAPGUID)
;
CREATE UNIQUE INDEX IUSERLDAPUSERHDR1
ON IUSERLDAPUSERHDR (ID)
;
CREATE UNIQUE INDEX IUSERLDAPUSERHDR2
ON IUSERLDAPUSERHDR (LDAPGUID)
;
CREATE UNIQUE INDEX IUSERNEXTID1
ON IUSERNEXTID (TYPE)
;
CREATE INDEX IUSEROBJHDR1
ON IUSEROBJHDR (ID)
;
CREATE INDEX IUSEROBJHDR2
ON IUSEROBJHDR (OWNERTYPE, OWNERID)
;
CREATE INDEX IUSEROBJHDR3
ON IUSEROBJHDR (PRODID)
;
CREATE INDEX IUSEROBJHDR4
ON IUSEROBJHDR (PRODID, TYPE)
;
CREATE INDEX IUSEROBJHDR5
ON IUSEROBJHDR (PRODID, TYPE, EXTID1)
;
CREATE INDEX IUSEROBJPERM1
ON IUSEROBJPERM (DSTTYPE, DSTID)
;
CREATE INDEX IUSEROBJPERM2
ON IUSEROBJPERM (OBJID)
;
CREATE INDEX IUSEROBJPERM3
ON IUSEROBJPERM (DSTTYPE, DSTID, OBJID)
;
CREATE UNIQUE INDEX IUSERREMUSER1
ON IUSERREMUSER (ID)
;
CREATE UNIQUE INDEX IUSERUSERHDR1
ON IUSERUSERHDR (ID)
;
CREATE INDEX IUSERUSERHDR2
ON IUSERUSERHDR (NAME)
;
CREATE INDEX IUSERUSERHDR3
ON IUSERUSERHDR (DEPTID)
;
CREATE INDEX IUSERUSERMAP1
ON IUSERUSERMAP (SRCDBID, SRCUSERID)
;
CREATE INDEX IUSERUSERMAP2
ON IUSERUSERMAP (DSTDBID, DSTUSERID)
;
CREATE INDEX IUSERUSERMAP3
ON IUSERUSERMAP (SRCDBID, SRCUSERID, DSTDBID)
;
CREATE INDEX IUSERUSERPWDS1
ON IUSERUSERPWDS (USERID)
;
CREATE INDEX IUSERUSERPWDS2
ON IUSERUSERPWDS (PASSWORD)
;
CREATE INDEX IUSERUSERTYPE1
ON IUSERUSERTYPE (USERID)
;
CREATE INDEX IUSERUSERTYPE2
ON IUSERUSERTYPE (USERID, PRODID)
;
CREATE UNIQUE INDEX IVOLACTDIR1
ON IVOLACTDIR (VOLID)
;
CREATE INDEX IVOLARCHLIST1
ON IVOLARCHLIST (ARCHID)
;
CREATE INDEX IVOLARCHLIST2
ON IVOLARCHLIST (LISTID)
;
CREATE UNIQUE INDEX IVOLFILEFTS1
ON IVOLFILEFTS (ID)
;
CREATE INDEX IVOLFILEHDR1
ON IVOLFILEHDR (ID)
;
CREATE INDEX IVOLFILEHDR2
ON IVOLFILEHDR (VOLID)
;
CREATE UNIQUE INDEX IVOLLISTHDR1
ON IVOLLISTHDR (ID)
;
CREATE INDEX IVOLLISTVOL1
ON IVOLLISTVOL (LISTID)
;
CREATE INDEX IVOLLISTVOL2
ON IVOLLISTVOL (VOLID)
;
CREATE UNIQUE INDEX IVOLNEXTID1
ON IVOLNEXTID (TYPE)
;
CREATE UNIQUE INDEX IVOLREPHDR1
ON IVOLREPHDR (ID)
;
CREATE INDEX IVOLVOLHDR1
ON IVOLVOLHDR (ID)
;
CREATE INDEX IVOLVOLHDR2
ON IVOLVOLHDR (REPID)
;
CREATE UNIQUE INDEX IVOLVOLTBL1
ON IVOLVOLTBL (LOCID)
;

-----------------------------
-- END INDEX KEYS INVESDOC --
-----------------------------