--INSTITUCIONES
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('IARCHIDOC','IARCHIDOC','ARCHIDOC',1,0,NULL,2,CURRENT TIMESTAMP,NULL,NULL);
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('INST1','INST1','Institución 1',1,0,NULL,2,CURRENT TIMESTAMP,NULL,'Institución 1');
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('INST2','INST2','Institución 2',1,0,NULL,2,CURRENT TIMESTAMP,NULL,'Institución 2');
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('INST3','INST3','Institución 3',1,0,NULL,2,CURRENT TIMESTAMP,NULL,'Institución 3');
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('INST4','INST4','Institución 4',1,0,NULL,2,CURRENT TIMESTAMP,NULL,'Institución 4');
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('INST5','INST5','Institución 5',1,0,NULL,2,CURRENT TIMESTAMP,NULL,'Institución 5');
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('INST6','INST6','Institución 6',1,0,NULL,2,CURRENT TIMESTAMP,NULL,'Institución 6');
-- 6 INSTITUCIONES

--ORGANOS
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('ORG1','ORG1','Órgano 1',2,1,'INST1',2,CURRENT TIMESTAMP,NULL,'Órgano 1');
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('ORG2','ORG2','Órgano 2',2,1,'INST2',2,CURRENT TIMESTAMP,NULL,'Órgano 2');
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('ORG3','ORG3','Órgano 3',2,1,'INST3',2,CURRENT TIMESTAMP,NULL,'Órgano 3');
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('ORG4','ORG4','Órgano 4',2,1,'INST4',2,CURRENT TIMESTAMP,NULL,'Órgano 4');
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('ORG5','ORG5','Órgano 5',2,1,'INST5',2,CURRENT TIMESTAMP,NULL,'Órgano 5');
INSERT INTO AOESTRORG (ID,CODIGO,NOMBRE,TIPO,NIVEL,IDORGPADRE,ESTADO,FINICIOVIGENCIA,FFINVIGENCIA,DESCRIPCION) VALUES ('ORG6','ORG6','Órgano 6',2,1,'INST6',2,CURRENT TIMESTAMP,NULL,'Órgano 6');
-- 6 ÓRGANOS

--USUARIOS
INSERT INTO AOUSRORGV (IDUSUARIO,NOMBREUSUARIO,IDORGANO) VALUES ('USR1','Administrador de Series','ORG1');
INSERT INTO AOUSRORGV (IDUSUARIO,NOMBREUSUARIO,IDORGANO) VALUES ('USR2','Administrador de Fondos','ORG2');
INSERT INTO AOUSRORGV (IDUSUARIO,NOMBREUSUARIO,IDORGANO) VALUES ('USR3','Administrador de Préstamos','ORG3');
INSERT INTO AOUSRORGV (IDUSUARIO,NOMBREUSUARIO,IDORGANO) VALUES ('USR4','Administrador de Depósito','ORG4');
INSERT INTO AOUSRORGV (IDUSUARIO,NOMBREUSUARIO,IDORGANO) VALUES ('USR5','Administrador de Archivo','ORG5');
INSERT INTO AOUSRORGV (IDUSUARIO,NOMBREUSUARIO,IDORGANO) VALUES ('USR6','Administrador de Oficina','ORG6');