--/***************************/
--/* Versión 3.4             */
--/***************************/

--  Crear tablas para el conector de organización

CREATE TABLE dbo.AOESTRORG ( 
	ID VARCHAR(32) NOT NULL,
	CODIGO VARCHAR(64) NOT NULL,
	NOMBRE VARCHAR(254) NOT NULL,
	TIPO INT NOT NULL,
	NIVEL INT NOT NULL,
	IDORGPADRE VARCHAR(32),
	ESTADO INT NOT NULL,
	FINICIOVIGENCIA DATETIME,
	FFINVIGENCIA DATETIME,
	DESCRIPCION VARCHAR(254)
);

CREATE TABLE dbo.AOUSR ( 
	ID VARCHAR(64) NOT NULL,
	DIRECCION VARCHAR(254),
	EMAIL VARCHAR(254),
	NOMBRE VARCHAR(64),
	APELLIDOS VARCHAR(128),
	NOMBREUSUARIO VARCHAR(64) NOT NULL,
	PASSWORD VARCHAR(64) NOT NULL
);

CREATE TABLE dbo.AOUSRORGV ( 
	IDUSUARIO VARCHAR(64) NOT NULL,
	NOMBREUSUARIO VARCHAR(254) NOT NULL,
	IDORGANO VARCHAR(32) NOT NULL
);

CREATE UNIQUE INDEX ORGANIZACION1 ON AOESTRORG (ID);
CREATE UNIQUE INDEX ORGANIZACION2 ON AOESTRORG (CODIGO);

CREATE INDEX USUARIO1 ON AOUSR (NOMBRE);
CREATE UNIQUE INDEX USUARIO2 ON AOUSR (NOMBREUSUARIO);

CREATE UNIQUE INDEX USRORGANO1 ON AOUSRORGV (IDUSUARIO);

DROP INDEX ASGTUDOCSDF2 ON ASGTUDOCSDF; 
CREATE UNIQUE INDEX ASGTUDOCSDF2 ON ASGTUDOCSDF (ID, IDRELENTREGA);

-- Actualizar el nombre de clasificador de serie de una ficha
UPDATE ADFICHA SET NOMBRE='ISAD(G) Nivel de Descripción Clasificador Serie' WHERE ID='3';

INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','3.4',getdate());
