-----------------------------------------------
-- Recursos de las entidades principales en CA
-----------------------------------------------

DECLARE @sequence_resources_id int

-- Entidad EXPEDIENTES
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'ASUNTO', 'Assumpte');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'CIUDAD', 'Ciutat');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'CODPROCEDIMIENTO', 'Cod. de Procediment');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'CPOSTAL', 'Codi Postal');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'DIRECCIONTELEMATICA', 'Adreça Telemàtica');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'DOMICILIO', 'Adreça Postal');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'EFECTOSDELSILENCIO', 'Efecte del Silenci Administratiu');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'ESTADOADM', 'Estat Administratiu');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'ESTADOINFO', 'Informació d''Estat');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'EXPRELACIONADOS', 'Expedients Relacionats');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'FAPERTURA', 'Data Obertura');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'FCIERRE', 'Data Tancament');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'FESTADO', 'Data d''Estat');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'FINICIOPLAZO', 'Data Inicio Termini');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'FORMATERMINACION', 'Forma Terminació');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'FREG', 'Data de Registre');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'FUNCIONACTIVIDAD', 'Funció/Activitat');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'HAYRECURSO', 'Recurs');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'IDDIRECCIONPOSTAL', 'Id. d''Adreça Postal');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'IDENTIDADTITULAR', 'Identitat');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'ID_PCD', 'Id. de Procediment');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'IDPROCESO', 'Id. de Procés');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'IDSECCIONINICIADORA', 'de Secció Iniciadora');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'IDTITULAR', 'Id. d''Interessat');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'IDUNIDADTRAMITADORA', 'Id. de Secció Tramitadora');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'LBL_CONFIRMADA', 'Verificada');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'LBL_LIBRE', 'Lliure');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'LBL_NO_VALIDADO', 'No Validat');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'LBL_VALIDADO', 'Validat');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'LOCALIZACION', 'Localització');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'MATERIAS', 'Matèries');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'MUNICIPIO', 'Municipi');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'NIFCIFTITULAR', 'NIF/CIF');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'NOMBREPROCEDIMIENTO', 'Procediment');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'NREG', 'Nº de Registre');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'NUMEXP', 'Nº Expedient');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'NVERSION', 'Versió');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'OBSERVACIONES', 'Observacions');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'PALABRASCLAVE', 'Paraules Clau');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'PLAZO', 'Termini de Resolució');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'POBLACION', 'Població');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'REFERENCIA_INTERNA', 'Referència Interna');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'REGIONPAIS', 'Regió/País');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'ROLTITULAR', 'Relació');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'SECCIONINICIADORA', 'Secció Iniciadora');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'SEP_DIRECCIONES', 'ADREÇA NOTIFICACIÓ');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'SEP_INTERESADO_PRINCIPAL', 'INTERESSAT PRINCIPAL');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'SEP_TERRITORIO', 'TERRITORI');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'SERVPRESACTUACIONES', 'Serv. Pres. Actuacions');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'SPAC_EXPEDIENTES', 'Expedient');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'SPAC_EXPEDIENTES_TAB_DATOS_EXPEDIENTE', 'Dades de l''Expedient');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'SPAC_EXPEDIENTES_TAB_INFORMACION_ADICIONAL', 'Informació addicional');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'TFNOFIJO', 'Tfn. Fix');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'TFNOMOVIL', 'Tfn. Mòbil');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'TIPODEDOCUMENTAL', 'Tipus de Documental');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'TIPODIRECCIONINTERESADO', 'Tipus Adreça Notificació');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'TIPOPERSONA', 'Tipus de Persona');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'UPLAZO', 'Unitat del Termini de Resolució');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 1, 'ca', 'UTRAMITADORA', 'Secció Tramitadora');

-- Entidad DOCUMENTOS
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'AUTOR', 'Autor');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'AUTOR_INFO', 'Informació de l''Autor');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'BLOQUEO', 'Estat de Bloqueig');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'DESCRIPCION', 'Descripció');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'DESTINO', 'Destinació');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'DESTINO_ID', 'Id. de Destinació');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'DESTINO_TIPO', 'Tipus de la Destinació');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'DOCUMENTO', 'Document');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'ESTADO', 'Estat');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'ESTADOFIRMA', 'Estat de Signatura');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'ESTADONOTIFICACION', 'Estat Notificació');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'EXTENSION', 'Extensió');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'EXTENSION_RDE', 'Extensió documento signat');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'FAPROBACION', 'Data Aprovació');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'FDOC', 'Data Generació');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'FFIRMA', 'Data Estat de Signatura');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'FNOTIFICACION', 'Data Notificació');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'FREG', 'Data de Registre');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'ID_ENTIDAD', 'Id. Entitat');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'ID_FASE', 'Id. de Fase');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'ID_FASE_PCD', 'Id. de Fase en el Procediment');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'ID_NOTIFICACION', 'Id. de Notificació');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'ID_PLANTILLA', 'Id. de Plantilla');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'ID_REG_ENTIDAD', 'Id. Reg. Entitat');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'ID_TPDOC', 'Id. de Tipus de Document');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'ID_TRAMITE', 'Id. de Tràmit');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'ID_TRAMITE_PCD', 'Id. de Tràmit en el Procediment');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'INFOPAG', 'Referencia Gestor Documental');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'INFOPAG_RDE', 'Referencia Gestor Documental de Documents Electrònics');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'NOMBRE', 'Nom');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'NREG', 'Nº de Registre');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'ORIGEN', 'Origen');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'ORIGEN_ID', 'Id. de Origen');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'ORIGEN_TIPO', 'Tipus de l''Origen');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'REPOSITORIO', 'Repositori');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'SPAC_DT_DOCUMENTOS', 'Document');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 2, 'ca', 'TP_REG', 'Tipus de Registre');

-- Entidad PARTICIPANTES
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'CAUT', 'Regió/País');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'C_POSTAL', 'Codi Postal');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'DIRECCIONTELEMATICA', 'Adreça Telemàtica');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'DIRNOT', 'Adreça Postal');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'EMAIL', 'E-Mail');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'IDDIRECCIONPOSTAL', 'Id. de Adreça Postal');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'ID_EXT', 'Referència Externa');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'IMAGEN', 'user');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'LBL_CONFIRMADA', 'Verificada');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'LBL_LIBRE', 'Lliure');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'LBL_NO_VALIDADO', 'No Validat');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'LBL_VALIDADO', 'Validat');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'LISTA', 'LLISTAT DE PARTICIPANTS');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'LOCALIDAD', 'Ciutat');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'NDOC', 'NIF/CIF');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'NOMBRE', 'Nom');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'NUMDOCUMENTO', 'Nº Document');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'ROL', 'Relació');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'SEP_DIRECCIONES', 'ADREÇA NOTIFICACIÓ');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'SPAC_DT_INTERVINIENTES', 'Participants');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'SPAC_DT_INTERVINIENTES_TAB_DATOS_PARTICIPANTE', 'Dades de Participant');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'TFNO_FIJO', 'Tfn. Fix');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'TFNO_MOVIL', 'Tfno. Mòbil');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'TIPO', 'Tipus');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'TIPO_DIRECCION', 'Tipus Adreça Notificació');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 3, 'ca', 'TIPO_PERSONA', 'Tipus de Persona');

-- Entidad TRAMITES
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'COD_ACTO', 'Cod. d''Acte');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'DESCRIPCION', 'Descripció');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'ESTADO', 'Estat');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'ESTADO_INFO', 'Informació d''Estat');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'FASE_PCD', 'Fase en el Procediment');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'FECHA_CIERRE', 'Data de Tancament');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'FECHA_FIN', 'Data de Finalització');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'FECHA_INICIO', 'Data de Creació');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'FECHA_INICIO_PLAZO', 'Data Inicio Termini');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'FECHA_LIMITE', 'Data Alarma');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'ID_FASE_EXP', 'Id. de la Fase Activa');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'ID_FASE_PCD', 'Id. de la Fase en el Procediment');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'ID_SUBPROCESO', 'Id. de Subproceso');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'ID_TRAM_CTL', 'Id. del Tràmit al Catàleg');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'ID_TRAM_EXP', 'Id. del Tràmit Actiu');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'ID_TRAM_PCD', 'Id. del Tràmit en el Procediment');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'INICIADO', 'Iniciat');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'NOMBRE', 'Tràmit');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'NUM_ACTO', 'Nº d''Acte');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'OBSERVACIONES', 'Observacions');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'PLAZO', 'Termini');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'SPAC_DT_TRAMITES', 'Tràmit');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'TRAMITE', 'TRÀMIT');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'TRAMRESPONSABLE', 'Tramitador Responsable');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'UND_RESP', 'Departament Responsable');
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_resources_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_ENTIDADESRESOURCES';
INSERT INTO <username>.SPAC_CT_ENTIDADES_RESOURCES (ID, ID_ENT, IDIOMA, CLAVE, VALOR) VALUES (@sequence_resources_id, 7, 'ca', 'UPLAZO', 'Uts. Termini');
