--
-- Trazas de auditorias
--
CREATE TABLE AUDIT_TRAZA (
  ID bigint NOT NULL,
  APP_ID bigint NOT NULL,
  APP_DESCRIPTION VARCHAR (128),

  EVENT_TYPE bigint NOT NULL,
  EVENT_DATE datetime  NOT NULL,
  EVENT_DESCRIPTION VARCHAR (512),

  USER_ID  VARCHAR (128) NOT NULL,
  USER_NAME  VARCHAR(256) NOT NULL,
  USER_HOST_NAME VARCHAR (256) NOT NULL,
  USER_IP VARCHAR (256) NOT NULL,

  OBJECT_TYPE VARCHAR (128) NOT NULL,
  OBJECT_TYPE_DESCRIPTION VARCHAR (512),
  OBJECT_ID  VARCHAR (128),
  OBJECT_FIELD VARCHAR (128),

  OLD_VALUE VARCHAR (4000),
  NEW_VALUE VARCHAR (4000)

);


ALTER TABLE AUDIT_TRAZA ADD CONSTRAINT PK_AUDIT_TRAZA PRIMARY KEY(ID);

CREATE TABLE AUDIT_TRAZA_SEQ (id bigint identity);

CREATE TABLE AUDIT_APPS (
  APP_DESCRIPTION VARCHAR (128) NOT NULL,
  APP_ID bigint NOT NULL

);

ALTER TABLE AUDIT_APPS ADD CONSTRAINT PK_AUDIT_APPS PRIMARY KEY(APP_DESCRIPTION);
ALTER TABLE AUDIT_APPS ADD CONSTRAINT UQ_AUDIT_APPS_APP_ID UNIQUE (APP_ID);


--
-- Auditoria para la aplicacion de Gestion de Expedientes
--
INSERT INTO AUDIT_APPS (APP_ID, APP_DESCRIPTION) VALUES (1,'TRAMITACION_EXPEDIENTES');