-----------------------------------
-- Actualización de v6.2 a v6.3
-----------------------------------


--
-- Información de versión
--
DECLARE @sequence_id int
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_INFOSISTEMA';
INSERT INTO <username>.spac_infosistema (id, codigo, valor, fecha_actualizacion) VALUES (@sequence_id, 'VERSIONBD', '6.3', getdate());
UPDATE <username>.SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'SPAC_SQ_ID_INFOSISTEMA';
INSERT INTO <username>.spac_infosistema (id, codigo, valor, fecha_actualizacion) VALUES (@sequence_id, 'VERSIONAPP', '6.3', getdate());

GO

--
-- Se añaden dos columnas más a spac_procesos spac_fases y spac_tramites para guardar el nombre del responsable 
-- y el nombre del responsable secundario.
--

ALTER TABLE SPAC_PROCESOS ADD  RESP VARCHAR (250);
ALTER TABLE SPAC_FASES ADD  RESP VARCHAR (250);
ALTER TABLE SPAC_TRAMITES ADD RESP VARCHAR (250);
ALTER TABLE SPAC_PROCESOS ADD  RESP_SEC VARCHAR (250);
ALTER TABLE SPAC_FASES ADD  RESP_SEC VARCHAR (250);
ALTER TABLE SPAC_TRAMITES ADD RESP_SEC VARCHAR (250);

GO

--
-- Actualización de la vista de plazos
--

DROP VIEW <username>.SPAC_DEADLINE;

CREATE VIEW <username>.SPAC_DEADLINE AS 
SELECT OBJ.NUMEXP, OBJ.FECHA_LIMITE, PROCEDIMIENTO.NOMBRE AS NOMBRE_PCD, OBJ.ID_RESP, OBJ.ID AS ID_OBJETO, 'RESOLUCIÓN EXPEDIENTE' AS DESCRIPCION, 1 AS TIPO
   FROM SPAC_PROCESOS OBJ, SPAC_CT_PROCEDIMIENTOS PROCEDIMIENTO
  WHERE OBJ.ID_PCD = PROCEDIMIENTO.ID AND OBJ.ESTADO = 1 AND OBJ.FECHA_LIMITE IS NOT NULL
UNION 
 SELECT OBJ.NUMEXP, OBJ.FECHA_LIMITE, PROCEDIMIENTO.NOMBRE AS NOMBRE_PCD, OBJ.ID_RESP, OBJ.ID AS ID_OBJETO, 'RESOLUCIÓN FASE' AS DESCRIPCION, 2 AS TIPO
   FROM SPAC_FASES OBJ, SPAC_CT_PROCEDIMIENTOS PROCEDIMIENTO
  WHERE OBJ.ID_PCD = PROCEDIMIENTO.ID AND OBJ.ESTADO = 1 AND OBJ.TIPO=1 AND OBJ.FECHA_LIMITE IS NOT NULL
UNION 
 SELECT OBJ.NUMEXP, OBJ.FECHA_LIMITE, PROCEDIMIENTO.NOMBRE AS NOMBRE_PCD, OBJ.ID_RESP, OBJ.ID AS ID_OBJETO, OBJ.NOMBRE AS DESCRIPCION, 3 AS TIPO
   FROM SPAC_TRAMITES OBJ, SPAC_CT_PROCEDIMIENTOS PROCEDIMIENTO
  WHERE OBJ.ID_PCD = PROCEDIMIENTO.ID AND OBJ.ESTADO = 1 AND OBJ.FECHA_LIMITE IS NOT NULL
UNION 
 SELECT OBJ.NUMEXP, OBJ.FECHA_LIMITE, PROCEDIMIENTO.NOMBRE AS NOMBRE_PCD, OBJ.ID_RESP, OBJ.ID AS ID_OBJETO, 'RESOLUCIÓN ACTIVIDAD' AS DESCRIPCION, 4 AS TIPO
   FROM SPAC_FASES OBJ, SPAC_P_PROCEDIMIENTOS PROCEDIMIENTO
  WHERE OBJ.ID_PCD = PROCEDIMIENTO.ID AND OBJ.ESTADO = 1 AND OBJ.TIPO=2 AND OBJ.FECHA_LIMITE IS NOT NULL

GO


--
-- Creación de índices
--

CREATE INDEX SPAC_EXPEDIENTES_IX_NUMEXP ON <username>.SPAC_EXPEDIENTES (NUMEXP);
GO
CREATE INDEX SPAC_DT_DOCUMENTOS_IX_NUMEXP ON <username>.SPAC_DT_DOCUMENTOS (NUMEXP);
GO
CREATE INDEX SPAC_DT_TRAMITES_IX_NUMEXP ON <username>.SPAC_DT_TRAMITES (NUMEXP);
GO
CREATE INDEX SPAC_DT_TRAMITES_IX_IDTRAMEXP ON  <username>.SPAC_DT_TRAMITES (ID_TRAM_EXP);
GO
CREATE INDEX SPAC_DT_INT_IX_NUMEXP ON  <username>.SPAC_DT_INTERVINIENTES (NUMEXP);
GO
CREATE INDEX SPAC_PROCESOS_IX_NUMEXP ON <username>.SPAC_PROCESOS (NUMEXP);
GO
CREATE INDEX SPAC_PROCESOS_IX_IDRESP ON <username>.SPAC_PROCESOS (ID_RESP);
GO
CREATE INDEX SPAC_FASES_IX_NUMEXP ON <username>.SPAC_FASES (NUMEXP);
GO
CREATE INDEX SPAC_FASES_IX_IDRESP ON <username>.SPAC_FASES (ID_RESP);
GO
CREATE INDEX SPAC_TRAMITES_IX_NUMEXP ON <username>.SPAC_TRAMITES (NUMEXP);
GO
CREATE INDEX SPAC_TRAMITES_IX_IDRESP ON <username>.SPAC_TRAMITES (ID_RESP);
GO

--
-- Cambio del tipo de la columna ORIGEN_ID en SPAC_DT_DOCUMENTOS
--
ALTER TABLE SPAC_DT_DOCUMENTOS ALTER COLUMN ORIGEN_ID varchar(20);
GO
