package es.ieci.plusvalias.domain;

// Generated 30-jun-2010 12:15:53 by Hibernate Tools 3.2.4.CR1

/**
 * BoniexenDTO generated by hbm2java
 */
public class BoniexenDTO implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer numero;
	private Integer anyoejercicio;
	private String texto;
	private Double porcentaje;

	public BoniexenDTO() {
	}

	public BoniexenDTO(Integer numero) {
		this.numero = numero;
	}

	public BoniexenDTO(Integer numero, Integer anyoejercicio, String texto,
			Double porcentaje) {
		this.numero = numero;
		this.anyoejercicio = anyoejercicio;
		this.texto = texto;
		this.porcentaje = porcentaje;
	}

	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	public Integer getAnyoejercicio() {
		return this.anyoejercicio;
	}

	public void setAnyoejercicio(Integer anyoejercicio) {
		this.anyoejercicio = anyoejercicio;
	}

	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	public Double getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Double porcentaje) {
		this.porcentaje = porcentaje;
	}
}
