package es.ieci.plusvalias.domain;

// Generated 30-jun-2010 12:15:53 by Hibernate Tools 3.2.4.CR1

/**
 * CalleDTO generated by hbm2java
 */
public class CalleDTO implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String numero;
	private String tipo;
	private String nombre;
	private Integer categoria;
	private String textoCalle;

	public CalleDTO() {
	}

	public CalleDTO(String numero) {
		this.numero = numero;
	}

	public CalleDTO(String numero, String tipo, String nombre, Integer categoria, String textoCalle) {
		this.numero = numero;
		this.tipo = tipo;
		this.nombre = nombre;
		this.categoria = categoria;
		this.textoCalle = textoCalle;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Integer getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Integer categoria) {
		this.categoria = categoria;
	}
	
	public void setTextoCalle(String textoCalle) {
		this.textoCalle = textoCalle;
	}

	public String getTextoCalle() {
		return textoCalle;
	}
}
