package es.ieci.plusvalias.domain;

// Generated 30-jun-2010 12:15:53 by Hibernate Tools 3.2.4.CR1

/**
 * InmuebleDTO generated by hbm2java
 */
public class InmuebleDTO implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private String refcatastral;
	private String fijocatastral;
	private String nif;
	private String nombre;
	private String tipovia;
	private String nombrevia;
	private String numero;
	private String escalera;
	private String planta;
	private String puerta;
	private Double supsolar;
	private Double coepro;
	private Double supconstruida;
	private Double valsuelo;
	private Double valconstruido;
	private Double valcatastral;

	public InmuebleDTO() {
	}

	public InmuebleDTO(String refcatastral, String fijocatastral,
			Double valsuelo, Double valconstruido, Double valcatastral) {
		this.refcatastral = refcatastral;
		this.fijocatastral = fijocatastral;
		this.valsuelo = valsuelo;
		this.valconstruido = valconstruido;
		this.valcatastral = valcatastral;
	}

	public InmuebleDTO(String refcatastral, String fijocatastral, String nif,
			String nombre, String tipovia, String nombrevia, String numero,
			String escalera, String planta, String puerta, Double supsolar,
			Double coepro, Double supconstruida, Double valsuelo,
			Double valconstruido, Double valcatastral) {
		this.refcatastral = refcatastral;
		this.fijocatastral = fijocatastral;
		this.nif = nif;
		this.nombre = nombre;
		this.tipovia = tipovia;
		this.nombrevia = nombrevia;
		this.numero = numero;
		this.escalera = escalera;
		this.planta = planta;
		this.puerta = puerta;
		this.supsolar = supsolar;
		this.coepro = coepro;
		this.supconstruida = supconstruida;
		this.valsuelo = valsuelo;
		this.valconstruido = valconstruido;
		this.valcatastral = valcatastral;
	}

	public String getRefcatastral() {
		return this.refcatastral;
	}

	public void setRefcatastral(String refcatastral) {
		this.refcatastral = refcatastral;
	}

	public String getFijocatastral() {
		return this.fijocatastral;
	}

	public void setFijocatastral(String fijocatastral) {
		this.fijocatastral = fijocatastral;
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTipovia() {
		return this.tipovia;
	}

	public void setTipovia(String tipovia) {
		this.tipovia = tipovia;
	}

	public String getNombrevia() {
		return this.nombrevia;
	}

	public void setNombrevia(String nombrevia) {
		this.nombrevia = nombrevia;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public String getEscalera() {
		return this.escalera;
	}

	public void setEscalera(String escalera) {
		this.escalera = escalera;
	}

	public String getPlanta() {
		return this.planta;
	}

	public void setPlanta(String planta) {
		this.planta = planta;
	}

	public String getPuerta() {
		return this.puerta;
	}

	public void setPuerta(String puerta) {
		this.puerta = puerta;
	}

	public Double getSupsolar() {
		return this.supsolar;
	}

	public void setSupsolar(Double supsolar) {
		this.supsolar = supsolar;
	}

	public Double getCoepro() {
		return this.coepro;
	}

	public void setCoepro(Double coepro) {
		this.coepro = coepro;
	}

	public Double getSupconstruida() {
		return this.supconstruida;
	}

	public void setSupconstruida(Double supconstruida) {
		this.supconstruida = supconstruida;
	}

	public Double getValsuelo() {
		return this.valsuelo;
	}

	public void setValsuelo(Double valsuelo) {
		this.valsuelo = valsuelo;
	}

	public Double getValconstruido() {
		return this.valconstruido;
	}

	public void setValconstruido(Double valconstruido) {
		this.valconstruido = valconstruido;
	}

	public Double getValcatastral() {
		return this.valcatastral;
	}

	public void setValcatastral(Double valcatastral) {
		this.valcatastral = valcatastral;
	}
}
