package es.ieci.plusvalias.domain;

// Generated 30-jun-2010 12:15:53 by Hibernate Tools 3.2.4.CR1

/**
 * NotarioDTO generated by hbm2java
 */
public class NotarioDTO implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer numero;
	private String nombre;
	private String calle;
	private String poblacion;
	private Integer postal;
	private String nif;
	private String telefono;
	private String observaciones;
	private Long codigo;

	public NotarioDTO() {
	}

	public NotarioDTO(Integer numero) {
		this.numero = numero;
	}

	public NotarioDTO(Integer numero, String nombre, String calle,
			String poblacion, Integer postal, String nif, String telefono,
			String observaciones, Long codigo) {
		this.numero = numero;
		this.nombre = nombre;
		this.calle = calle;
		this.poblacion = poblacion;
		this.postal = postal;
		this.nif = nif;
		this.telefono = telefono;
		this.observaciones = observaciones;
		this.codigo = codigo;
	}

	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	public Integer getPostal() {
		return this.postal;
	}

	public void setPostal(Integer postal) {
		this.postal = postal;
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Long codigo) {
		this.codigo = codigo;
	}
}
