package es.ieci.plusvalias.domain;

// Generated 30-jun-2010 12:15:53 by Hibernate Tools 3.2.4.CR1

/**
 * RecargoDTO generated by hbm2java
 */
public class RecargoDTO implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer numero;
	private Integer anyoejercicio;
	private Integer maxdias;
	private Double porcentaje;
	private String liqinteresessn;

	public RecargoDTO() {
	}

	public RecargoDTO(Integer numero) {
		this.numero = numero;
	}

	public RecargoDTO(Integer numero, Integer anyoejercicio, Integer maxdias,
			Double porcentaje, String liqinteresessn) {
		this.numero = numero;
		this.anyoejercicio = anyoejercicio;
		this.maxdias = maxdias;
		this.porcentaje = porcentaje;
		this.liqinteresessn = liqinteresessn;
	}

	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	public Integer getAnyoejercicio() {
		return this.anyoejercicio;
	}

	public void setAnyoejercicio(Integer anyoejercicio) {
		this.anyoejercicio = anyoejercicio;
	}

	public Integer getMaxdias() {
		return this.maxdias;
	}

	public void setMaxdias(Integer maxdias) {
		this.maxdias = maxdias;
	}

	public Double getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Double porcentaje) {
		this.porcentaje = porcentaje;
	}

	public String getLiqinteresessn() {
		return this.liqinteresessn;
	}

	public void setLiqinteresessn(String liqinteresessn) {
		this.liqinteresessn = liqinteresessn;
	}
}
