package es.ieci.plusvalias.domain;

// Generated 30-jun-2010 12:15:53 by Hibernate Tools 3.2.4.CR1

/**
 * SituacionDTO generated by hbm2java
 */
public class SituacionDTO implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Integer numero;
	private Integer anyoejercicio;
	private String texto;
	private String poneoperador;
	private String admitepago;
	private String admitenotificacion;
	private String admitesituacionf;
	private String ponetesoreria;

	public SituacionDTO() {
	}

	public SituacionDTO(Integer numero) {
		this.numero = numero;
	}

	public SituacionDTO(Integer numero, Integer anyoejercicio, String texto,
			String poneoperador, String admitepago, String admitenotificacion,
			String admitesituacionf, String ponetesoreria) {
		this.numero = numero;
		this.anyoejercicio = anyoejercicio;
		this.texto = texto;
		this.poneoperador = poneoperador;
		this.admitepago = admitepago;
		this.admitenotificacion = admitenotificacion;
		this.admitesituacionf = admitesituacionf;
		this.ponetesoreria = ponetesoreria;
	}

	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	public Integer getAnyoejercicio() {
		return this.anyoejercicio;
	}

	public void setAnyoejercicio(Integer anyoejercicio) {
		this.anyoejercicio = anyoejercicio;
	}

	public String getTexto() {
		return this.texto;
	}

	public void setTexto(String texto) {
		this.texto = texto;
	}

	public String getPoneoperador() {
		return this.poneoperador;
	}

	public void setPoneoperador(String poneoperador) {
		this.poneoperador = poneoperador;
	}

	public String getAdmitepago() {
		return this.admitepago;
	}

	public void setAdmitepago(String admitepago) {
		this.admitepago = admitepago;
	}

	public String getAdmitenotificacion() {
		return this.admitenotificacion;
	}

	public void setAdmitenotificacion(String admitenotificacion) {
		this.admitenotificacion = admitenotificacion;
	}

	public String getAdmitesituacionf() {
		return this.admitesituacionf;
	}

	public void setAdmitesituacionf(String admitesituacionf) {
		this.admitesituacionf = admitesituacionf;
	}

	public String getPonetesoreria() {
		return this.ponetesoreria;
	}

	public void setPonetesoreria(String ponetesoreria) {
		this.ponetesoreria = ponetesoreria;
	}
}
