package es.ieci.plusvalias.domain;

// Generated 30-jun-2010 12:15:53 by Hibernate Tools 3.2.4.CR1

/**
 * TipointeresDTO generated by hbm2java
 */
public class TipointeresDTO implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	private Double porcentaje;
	private Integer anyoejercicio;

	public TipointeresDTO() {
	}

	public TipointeresDTO(Double porcentaje) {
		this.porcentaje = porcentaje;
	}

	public TipointeresDTO(Double porcentaje, Integer anyoejercicio) {
		this.porcentaje = porcentaje;
		this.anyoejercicio = anyoejercicio;
	}

	public Double getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(Double porcentaje) {
		this.porcentaje = porcentaje;
	}

	public Integer getAnyoejercicio() {
		return this.anyoejercicio;
	}

	public void setAnyoejercicio(Integer anyoejercicio) {
		this.anyoejercicio = anyoejercicio;
	}
}
