--/*************************/
--/* Versión 4.3           */
--/*************************/

	-- Insertar la versión actual de bd
	INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.2->4.3',CURRENT TIMESTAMP);

	--Añadir columna MARCASBLOQUEO
	ALTER TABLE ASGTUNIDADDOCRE ADD COLUMN MARCASBLOQUEO INTEGER DEFAULT 0 NOT NULL;

	--Añadir columna MARCASBLOQUEO
	ALTER TABLE ASGFUNIDADDOC ADD COLUMN MARCASBLOQUEO INTEGER DEFAULT 0 NOT NULL;