--/***************************/
--/* Versión 4.2             */
--/***************************/

    -- Insertar la versión actual de bd
	INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.0->4.2',CURRENT TIMESTAMP);

	-- Establecer el id de motivo como nulo
	CREATE TABLE ASGPCONSULTA2 (
		ID VARCHAR(32) NOT NULL,
		ANO VARCHAR(4) NOT NULL,
		ORDEN INTEGER NOT NULL,
		TIPOENTCONSULTORA SMALLINT NOT NULL,
		NORGCONSULTOR VARCHAR(254),
		NUSRCONSULTOR VARCHAR(254) NOT NULL,
		FINICIALRESERVA TIMESTAMP,
		FENTREGA TIMESTAMP,
		FMAXFINCONSULTA TIMESTAMP,
		ESTADO SMALLINT NOT NULL,
		FESTADO TIMESTAMP NOT NULL,
		MOTIVO VARCHAR(254),
		IDARCHIVO VARCHAR(32) NOT NULL,
		IDUSRSOLICITANTE VARCHAR(32) NOT NULL,
		INFORMACION VARCHAR(1024),
		TEMA VARCHAR(254),
		TIPO SMALLINT NOT NULL,
		TIPOENTREGA VARCHAR(254),
		DATOSAUTORIZADO VARCHAR(254),
		DATOSSOLICITANTE VARCHAR(512),
		OBSERVACIONES VARCHAR(254),
       IDMOTIVO VARCHAR(32)) ;

	INSERT INTO ASGPCONSULTA2 SELECT ID,ANO,ORDEN,TIPOENTCONSULTORA,NORGCONSULTOR,NUSRCONSULTOR,FINICIALRESERVA,FENTREGA,FMAXFINCONSULTA,ESTADO,FESTADO,MOTIVO,IDARCHIVO,IDUSRSOLICITANTE,INFORMACION,TEMA,TIPO,TIPOENTREGA,DATOSAUTORIZADO,DATOSSOLICITANTE,OBSERVACIONES,IDMOTIVO FROM ASGPCONSULTA;
	DROP TABLE ASGPCONSULTA;
	RENAME TABLE ASGPCONSULTA2 TO ASGPCONSULTA;

	CREATE UNIQUE INDEX ASGPCONSULTA1 ON ASGPCONSULTA (ID);
	CREATE INDEX ASGPCONSULTA2 ON ASGPCONSULTA (NUSRCONSULTOR);
	CREATE INDEX ASGPCONSULTA3 ON ASGPCONSULTA (IDUSRSOLICITANTE);
	CREATE INDEX ASGPCONSULTA4 ON ASGPCONSULTA (ESTADO);

	-- Establecer el identificador de motivo en préstamos como nulo
	CREATE TABLE ASGPPRESTAMO2 (
		ID VARCHAR(32) NOT NULL,
		ANO VARCHAR(4) NOT NULL,
		ORDEN INTEGER NOT NULL,
		NORGSOLICITANTE VARCHAR(254) NOT NULL,
		NUSRSOLICITANTE VARCHAR(254) NOT NULL,
		IDUSRSOLICITANTE VARCHAR(32),
		FINICIALRESERVA TIMESTAMP,
		IDORGSOLICITANTE VARCHAR(32),
		FENTREGA TIMESTAMP,
		FMAXFINPRESTAMO TIMESTAMP,
		ESTADO SMALLINT NOT NULL,
		FESTADO TIMESTAMP NOT NULL,
		IDARCHIVO VARCHAR(32) NOT NULL,
		IDUSRGESTOR VARCHAR(32) NOT NULL,
		NUMRECLAMACIONES INTEGER NOT NULL,
		FRECLAMACION1 TIMESTAMP,
		FRECLAMACION2 TIMESTAMP,
		TIPOENTREGA VARCHAR(254),
		DATOSAUTORIZADO VARCHAR(254),
		DATOSSOLICITANTE VARCHAR(512),
		OBSERVACIONES VARCHAR(254),
       IDMOTIVO VARCHAR(32));

	INSERT INTO ASGPPRESTAMO2 SELECT ID,ANO,ORDEN,NORGSOLICITANTE,NUSRSOLICITANTE,IDUSRSOLICITANTE,FINICIALRESERVA,IDORGSOLICITANTE,FENTREGA,FMAXFINPRESTAMO,ESTADO,FESTADO,IDARCHIVO,IDUSRGESTOR,NUMRECLAMACIONES,FRECLAMACION1,FRECLAMACION2,TIPOENTREGA,DATOSAUTORIZADO,DATOSSOLICITANTE,OBSERVACIONES,IDMOTIVO FROM ASGPPRESTAMO;
	DROP TABLE ASGPPRESTAMO;
	RENAME TABLE ASGPPRESTAMO2 TO ASGPPRESTAMO;

	CREATE UNIQUE INDEX ASGPPRESTAMO1 ON ASGPPRESTAMO (ID);
	CREATE INDEX ASGPPRESTAMO2 ON ASGPPRESTAMO (NUSRSOLICITANTE);
	CREATE INDEX ASGPPRESTAMO3 ON ASGPPRESTAMO (IDUSRSOLICITANTE);
	CREATE INDEX ASGPPRESTAMO4 ON ASGPPRESTAMO (ESTADO);