--/*************************/
--/* Versión 4.5           */
--/*************************/

	-- Insertar la versión actual de bd
	INSERT INTO AGINFOSISTEMA (NOMBRE,VALOR,FECHAACTUALIZACION) VALUES ('VERSIONBD','4.4->4.5',CURRENT TIMESTAMP);

	-- Crear tabla de Edificios
	CREATE TABLE ASGSEDIFICIO (
     ID			VARCHAR (32) NOT NULL,
     NOMBRE        VARCHAR (64) NOT NULL,
     UBICACION     VARCHAR (254),
     IDARCHIVO     VARCHAR (32) NOT NULL
	);

	-- Crear índices de la tabla de Edificios
	CREATE UNIQUE INDEX ASGSEDIFICIO1 ON ASGSEDIFICIO(ID);
	CREATE UNIQUE INDEX ASGSEDIFICIO2 ON ASGSEDIFICIO(NOMBRE);

	-- Crear tabla de Salas
	CREATE TABLE ASGSSALA (
     ID                    VARCHAR (32) NOT NULL,
     NOMBRE                VARCHAR (64) NOT NULL,
     DESCRIPCION           VARCHAR (254),
     IDEDIFICIO            VARCHAR (32) NOT NULL,
     EQUIPOINFORMATICO     CHAR (1) NOT NULL
	);

	-- Crear índices de la tabla de Salas
	CREATE UNIQUE INDEX ASGSSALA1 ON ASGSSALA(ID);
	CREATE UNIQUE INDEX ASGSSALA2 ON ASGSSALA(IDEDIFICIO,NOMBRE);
	CREATE INDEX ASGSSALA3 ON ASGSSALA(IDEDIFICIO);

	-- Crear tabla de Mesas
	CREATE TABLE ASGSMESA (
     ID              VARCHAR (32) NOT NULL,
     CODIGO          VARCHAR (64) NOT NULL,
     NUMORDEN        INTEGER NOT NULL,
     IDSALA          VARCHAR (32) NOT NULL,
     ESTADO          CHAR (1) NOT NULL,
     FECHAESTADO     TIMESTAMP NOT NULL,
     IDUSRCSALA      VARCHAR (32)
	);

	-- Crear índices de la tabla Mesas
	CREATE INDEX ASGSMESA1 ON ASGSMESA(IDSALA);
	CREATE UNIQUE INDEX ASGSMESA2 ON ASGSMESA(IDSALA,CODIGO);
	CREATE UNIQUE INDEX ASGSMESA3 ON ASGSMESA(IDSALA,NUMORDEN);
	CREATE INDEX ASGSMESA4 ON ASGSMESA(ESTADO);

	-- Crear tabla de usuarios investigadores de consulta de sala
	CREATE TABLE ASGSUSRCSALA (
     ID                        VARCHAR (32) NOT NULL,
     TIPODOCIDENTIFICACION     INTEGER NOT NULL,
     NUMDOCIDENTIFICACION		VARCHAR (32) NOT NULL,
     NOMBRE                    VARCHAR (64) NOT NULL,
     APELLIDOS                 VARCHAR (254) NOT NULL,
     NACIONALIDAD              VARCHAR (64),
     TELEFONOS					VARCHAR (128),
     EMAIL						VARCHAR (128),
     DIRECCION                 VARCHAR (254),
     FECHAALTA                 TIMESTAMP NOT NULL,
     VIGENTE					CHAR (1) NOT NULL,
     IDSCAUSR					VARCHAR (32)
	);

	-- Crear índices de la tabla usuarios investigadores
	CREATE UNIQUE INDEX ASGSUSRCSALA1 ON ASGSUSRCSALA(ID);
	CREATE INDEX ASGSUSRCSALA2 ON ASGSUSRCSALA(NUMDOCIDENTIFICACION);
	CREATE INDEX ASGSUSRCSALA3 ON ASGSUSRCSALA(VIGENTE);

	-- Crear tabla relación usuarios consulta y archivos
	CREATE TABLE ASGSUSRCSARCH (
     IDUSRCSALA      VARCHAR (32) NOT NULL,
     IDARCHIVO       VARCHAR (64) NOT NULL
	);

	-- Crear índices de la tabla de relación entre usuarios y archivos de consulta
	CREATE UNIQUE INDEX ASGSUSRCSARCH1 ON ASGSUSRCSARCH(IDUSRCSALA,IDARCHIVO);
	CREATE INDEX ASGSUSRCSARCH2 ON ASGSUSRCSARCH(IDUSRCSALA);

	-- Crear tabla de registro de consultas
	CREATE TABLE ASGSREGCSALA (
     ID                    VARCHAR (32) NOT NULL,
     IDUSRCSALA            VARCHAR (32) NOT NULL,
     FENTRADA				TIMESTAMP NOT NULL,
     FSALIDA				TIMESTAMP,
     NUMDOCIDENTIFICACION	VARCHAR (32) NOT NULL,
     NOMBREAPELLIDOS		VARCHAR (254) NOT NULL,
     IDSCAUSR				VARCHAR (32),
     IDARCHIVO				VARCHAR (32) NOT NULL,
     MESAASIGNADA			VARCHAR (254) NOT NULL
	);

	-- Crear índices de la tabla de registro de consultas
	CREATE UNIQUE INDEX ASGSREGCSALA1 ON ASGSREGCSALA(ID);
	CREATE INDEX ASGSREGCSALA2 ON ASGSREGCSALA(IDUSRCSALA);
	CREATE INDEX ASGSREGCSALA3 ON ASGSREGCSALA(NUMDOCIDENTIFICACION);

	--Añadir columna IDUSRCSALA
	ALTER TABLE ASGPCONSULTA ADD COLUMN IDUSRCSALA VARCHAR(32);

	--Añadir columna IDUSRCSALA
	ALTER TABLE ASGPTEMA ADD COLUMN IDUSRCSALA VARCHAR(32);

	--Añadir columnaS CONREENCAJADO E IDFORMATORE a la tabla de relaciones de entrega
	ALTER TABLE ASGTRENTREGA ADD CONREENCAJADO CHAR(1) DEFAULT 'N' NOT NULL;
	ALTER TABLE ASGTRENTREGA ADD IDFORMATORE VARCHAR(32);

	--Añadir columna IDUIREEACR a la tabla de huecos
	ALTER TABLE ASGDHUECO ADD IDUIREEACR VARCHAR(32);

	--Crear la tabla de unidades de instalación transferencias entre archivo con reencajado
	CREATE TABLE ASGTUIREEACR (
     ID              VARCHAR (32)  NOT NULL,
     IDRELENTREGA    VARCHAR (32)  NOT NULL,
     IDUIDEPOSITO    VARCHAR (32),
     SIGNATURAUI     VARCHAR (16),
     IDFORMATO       VARCHAR (32) NOT NULL,
     ORDEN           SMALLINT NOT NULL,
     ESTADOCOTEJO    SMALLINT DEFAULT 1 NOT NULL,
     NOTASCOTEJO     VARCHAR (256),
     DEVOLUCION      CHAR (1) DEFAULT 'N',
     DESCRIPCION     VARCHAR (256)
	);

	--Crear la tabla de unidades documentales en unidad de instalacion de transferencias
	--entre archivos con reencajado
	CREATE TABLE ASGTUDOCENUIREEACR (
     ID              VARCHAR (32)  NOT NULL,
     IDUDOCORIGEN    VARCHAR (32)  NOT NULL,
     IDRELENTREGA    VARCHAR (32)  NOT NULL,
     IDUNIDADDOC     VARCHAR (32)  NOT NULL,
     IDUIREEACR      VARCHAR (32),
     ASUNTO          VARCHAR (1024) NOT NULL,
     UDOCCOMPLETA    VARCHAR (1) NOT NULL,
     SIGNATURAUDOC   VARCHAR (32),
     POSUDOCENUI     SMALLINT,
     NUMEXP          VARCHAR (256),
     NUMPARTE        SMALLINT,
     FECHAINI        VARCHAR (64),
     FECHAFIN        VARCHAR (64),
     SIGNATURAUDOCORIGEN VARCHAR (32),
     DESCRIPCION     VARCHAR (256)
	);

	--Tabla de unidades documentales originales en el reencajado
	CREATE TABLE ASGTUDOCREEACR (
     ID              VARCHAR (32)  NOT NULL,
     IDRELENTREGA    VARCHAR (32)  NOT NULL,
     IDUNIDADDOC     VARCHAR (32)  NOT NULL,
     SIGNATURAUDOC   VARCHAR (32)  NOT NULL,
     IDUIDEPOSITO    VARCHAR (32)  NOT NULL,
     SIGNATURAUI     VARCHAR (16)  NOT NULL
	);

	-- Tabla: ASGTUIREEACR
	CREATE UNIQUE INDEX ASGTUIREEACR1 ON ASGTUIREEACR (ID);
	CREATE INDEX ASGTUIREEACR2 ON ASGTUIREEACR (IDRELENTREGA);

	-- Tabla: ASGTUDOCENUIREEACR
	CREATE UNIQUE INDEX ASGTUDENUIREEACR1 ON ASGTUDOCENUIREEACR (ID);
	CREATE INDEX ASGTUDENUIREEACR2 ON ASGTUDOCENUIREEACR (IDUDOCORIGEN);
	CREATE INDEX ASGTUDENUIREEACR3 ON ASGTUDOCENUIREEACR (IDRELENTREGA);
	CREATE INDEX ASGTUDENUIREEACR4 ON ASGTUDOCENUIREEACR (IDUNIDADDOC);
	CREATE INDEX ASGTUDENUIREEACR5 ON ASGTUDOCENUIREEACR (IDUIREEACR);
	CREATE INDEX ASGTUDENUIREEACR6 ON ASGTUDOCENUIREEACR (IDRELENTREGA,IDUNIDADDOC);

	-- Tabla: ASGTUDOCREEACR
	CREATE UNIQUE INDEX ASGTUDOCREEACR1 ON ASGTUDOCREEACR (ID);
	CREATE INDEX ASGTUDOCREEACR2 ON ASGTUDOCREEACR (IDRELENTREGA);
	CREATE INDEX ASGTUDOCREEACR3 ON ASGTUDOCREEACR (IDRELENTREGA,IDUNIDADDOC);