CREATE VIEW SPAC_WL_BATCHTASK AS
	SELECT SPAC_TRAMITACIONES_AGRUPADAS.ID AS ID_AGRUPACION, SPAC_TRAMITACIONES_AGRUPADAS.ID_RESP, SPAC_TRAMITACIONES_AGRUPADAS.ESTADO, SPAC_TRAMITACIONES_AGRUPADAS.FECHA_CREACION, SPAC_P_FASES.NOMBRE AS FASE, SPAC_TRAMITACIONES_AGRUPADAS.ID_ULTIMO_TRAMITE, SPAC_TRAMITACIONES_AGRUPADAS.ID_ULTIMO_TEMPLATE, SPAC_TRAMITACIONES_AGRUPADAS.ID_ULTIMO_TIPODOC, SPAC_CT_PROCEDIMIENTOS.COD_PCD, SPAC_CT_PROCEDIMIENTOS.NOMBRE AS PROCEDIMIENTO, SPAC_TRAMITACIONES_AGRUPADAS.ID_FASE
	FROM SPAC_TRAMITACIONES_AGRUPADAS, SPAC_P_FASES, SPAC_CT_PROCEDIMIENTOS
	WHERE SPAC_TRAMITACIONES_AGRUPADAS.ID_FASE = SPAC_P_FASES.ID AND SPAC_P_FASES.ID_PCD = SPAC_CT_PROCEDIMIENTOS.ID
;


CREATE VIEW SPAC_WL_PROC AS
	SELECT FASES.ID_EXP AS ID, FASES.NUMEXP, FASES.ID_PCD, FASES.ID_FASE AS ID_STAGEPCD, FASES.ID AS ID_STAGE, FASESPCD.NOMBRE AS NAME_STAGE, FASES.FECHA_INICIO AS INITDATE, FASES.FECHA_LIMITE AS LIMITDATE, FASES.ID_RESP AS RESP, FASES.TIPO 
	FROM SPAC_FASES FASES, SPAC_P_FASES FASESPCD 
	WHERE FASES.ID_FASE = FASESPCD.ID AND FASES.ESTADO = 1
;


CREATE VIEW  SPAC_WL_PCD AS
	SELECT PCD.ID, PCD.NOMBRE AS NAME, PCD.NVERSION AS NVERSION, FASES.ID_RESP AS RESP, FASES.TIPO
	FROM SPAC_FASES FASES, SPAC_P_PROCEDIMIENTOS PCD
	WHERE FASES.ESTADO = 1 AND PCD.ID = FASES.ID_PCD
	GROUP BY PCD.ID, PCD.NOMBRE, PCD.NVERSION, FASES.ID_RESP, FASES.TIPO
	UNION
	SELECT PCD.ID, PCD.NOMBRE AS NAME, PCD.NVERSION AS NVERSION, SPC_PERMS.ID_RESP AS RESP, FASES.TIPO
	FROM SPAC_FASES FASES, SPAC_P_PROCEDIMIENTOS PCD, SPAC_PERMISOS SPC_PERMS
	WHERE FASES.ESTADO = 1 AND PCD.ID = FASES.ID_PCD AND SPC_PERMS.TP_OBJ = 1 AND SPC_PERMS.ID_OBJ = FASES.ID_PCD
	GROUP BY PCD.ID, PCD.NOMBRE, PCD.NVERSION, SPC_PERMS.ID_RESP, FASES.TIPO
;


CREATE  VIEW SPAC_WL_TASK  AS
	SELECT TRAM.ID, TRAM.NOMBRE AS NAME, TRAM.ID_TRAMITE AS ID_TASK, TRAM.ID_CTTRAMITE AS ID_CTTASK, TRAM.ID_RESP AS RESP, TRAM.ID_PCD AS ID_PROC, PCD.NOMBRE AS NAME_PROC, TRAM.ID_FASE_PCD AS ID_STAGE, P_FASES.NOMBRE AS NAME_STAGE, TRAM.ID_EXP, TRAM.ID_FASE_EXP, TRAM.NUMEXP, TRAM.FECHA_INICIO AS INITDATE, TRAM.FECHA_LIMITE AS LIMITDATE, TRAM.ESTADO AS STATUS, TRAM.TIPO, PRO.ID AS ID_SUBPROCESO, PRO.ID_PCD AS ID_SUBPCD FROM SPAC_TRAMITES TRAM LEFT JOIN SPAC_PROCESOS PRO ON TRAM.ID_SUBPROCESO = PRO.ID, SPAC_P_FASES P_FASES, SPAC_P_PROCEDIMIENTOS PCD WHERE TRAM.ESTADO = 1 AND TRAM.ID_PCD = PCD.ID AND TRAM.ID_FASE_PCD = P_FASES.ID
	UNION
	SELECT TRAM.ID, TRAM.NOMBRE AS NAME, TRAM.ID_TRAMITE AS ID_TASK, TRAM.ID_CTTRAMITE AS ID_CTTASK, FASES.ID_RESP AS RESP,TRAM.ID_PCD AS ID_PROC, PCD.NOMBRE AS NAME_PROC, TRAM.ID_FASE_PCD AS ID_STAGE, P_FASES.NOMBRE AS NAME_STAGE, TRAM.ID_EXP, TRAM.ID_FASE_EXP, TRAM.NUMEXP, TRAM.FECHA_INICIO AS INITDATE, TRAM.FECHA_LIMITE AS LIMITDATE, TRAM.ESTADO AS STATUS, TRAM.TIPO, PRO.ID AS ID_SUBPROCESO, PRO.ID_PCD AS ID_SUBPCD FROM SPAC_TRAMITES TRAM, SPAC_PROCESOS PRO, SPAC_FASES FASES, SPAC_P_FASES P_FASES, SPAC_P_PROCEDIMIENTOS PCD WHERE TRAM.ESTADO = 1 AND TRAM.TIPO = 2 AND TRAM.ID_SUBPROCESO = PRO.ID AND FASES.ID_EXP = PRO.ID AND TRAM.ID_SUBPROCESO = PRO.ID AND TRAM.ID_PCD = PCD.ID AND TRAM.ID_FASE_PCD = P_FASES.ID
;
	

CREATE VIEW SPAC_WL_CLOSE_TASK AS
	SELECT T.ID,T.NOMBRE AS NAME,T.ID AS ID_TASK,T.ID_TRAM_CTL AS ID_CTTASK,T.ID_RESP_CLOSED AS RESP,P.ID AS ID_PROC,CASE WHEN (T.ID_SUBPROCESO IS NULL) THEN 1 ELSE 2 END AS TIPO, P.NOMBRE AS NAME_PROC,T.ID_FASE_PCD AS ID_STAGE,P.NOMBRE AS NAME_STAGE,PC.ID AS ID_EXP,T.ID_FASE_EXP,T.NUMEXP,T.ID_SUBPROCESO AS ID_SUBPCD,T.FECHA_INICIO AS INITDATE,T.FECHA_CIERRE AS ENDDATE
	FROM SPAC_DT_TRAMITES T,SPAC_CT_PROCEDIMIENTOS P,SPAC_P_FASES F,SPAC_PROCESOS PC
	WHERE T.NUMEXP = PC.NUMEXP AND PC.ID_PCD = P.ID AND T.ID_FASE_PCD = F.ID AND T.ESTADO = 3
;


CREATE VIEW SPAC_WL_ACTIVITY AS
	SELECT SPAC_FASES.ID, SPAC_P_FASES.NOMBRE, SPAC_FASES.ID_FASE_BPM, SPAC_FASES.ID_EXP, SPAC_FASES.ID_PCD, SPAC_FASES.ID_FASE, SPAC_FASES.NUMEXP, SPAC_FASES.FECHA_INICIO, SPAC_FASES.FECHA_LIMITE, SPAC_FASES.ESTADO, SPAC_FASES.OBSERVACIONES, SPAC_FASES.ID_RESP, SPAC_FASES.RESP, SPAC_FASES.ID_RESP_SEC, SPAC_FASES.RESP_SEC, SPAC_FASES.ESTADO_PLAZO, SPAC_FASES.NUM_DIAS_PLAZO, SPAC_FASES.ID_CALENDARIO, SPAC_FASES.FECHA_INICIO_PLAZO, SPAC_FASES.ESTADO_ANTERIOR, SPAC_TRAMITES.ID AS ID_TRAMITE, SPAC_TRAMITES.ID_EXP AS ID_EXP_TRAMITE, SPAC_TRAMITES.ID_PCD AS ID_PCD_TRAMITE, SPAC_TRAMITES.ID_FASE_EXP AS ID_FASE_TRAMITE, SPAC_TRAMITES.ID_FASE_PCD AS ID_FASE_PCD_TRAMITE, SPAC_TRAMITES.ID_TRAMITE AS ID_TRAMITE_PCD_TRAMITE, SPAC_TRAMITES.ID_CTTRAMITE AS ID_CTTRAMITE_TRAMITE
	FROM SPAC_FASES, SPAC_TRAMITES, SPAC_P_FASES
	WHERE SPAC_FASES.ESTADO = 1 AND SPAC_FASES.TIPO = 2 AND SPAC_FASES.ID_FASE = SPAC_P_FASES.ID AND SPAC_FASES.ID_EXP = SPAC_TRAMITES.ID_SUBPROCESO
;


CREATE VIEW SPAC_DEADLINE AS
	SELECT OBJ.NUMEXP, OBJ.FECHA_LIMITE, PROCEDIMIENTO.NOMBRE AS NOMBRE_PCD, OBJ.ID_RESP, OBJ.ID AS ID_OBJETO, 'RESOLUCIÓN EXPEDIENTE' AS DESCRIPCION, 1 AS TIPO
	FROM SPAC_PROCESOS OBJ, SPAC_CT_PROCEDIMIENTOS PROCEDIMIENTO
	WHERE OBJ.ID_PCD = PROCEDIMIENTO.ID AND OBJ.ESTADO = 1 AND OBJ.FECHA_LIMITE IS NOT NULL
	UNION 
	SELECT OBJ.NUMEXP, OBJ.FECHA_LIMITE, PROCEDIMIENTO.NOMBRE AS NOMBRE_PCD, OBJ.ID_RESP, OBJ.ID AS ID_OBJETO, 'RESOLUCIÓN FASE' AS DESCRIPCION, 2 AS TIPO
	FROM SPAC_FASES OBJ, SPAC_CT_PROCEDIMIENTOS PROCEDIMIENTO
	WHERE OBJ.ID_PCD = PROCEDIMIENTO.ID AND OBJ.ESTADO = 1 AND OBJ.TIPO=1 AND OBJ.FECHA_LIMITE IS NOT NULL
	UNION 
	SELECT OBJ.NUMEXP, OBJ.FECHA_LIMITE, PROCEDIMIENTO.NOMBRE AS NOMBRE_PCD, OBJ.ID_RESP, OBJ.ID AS ID_OBJETO, OBJ.NOMBRE AS DESCRIPCION, 3 AS TIPO
	FROM SPAC_TRAMITES OBJ, SPAC_CT_PROCEDIMIENTOS PROCEDIMIENTO
	WHERE OBJ.ID_PCD = PROCEDIMIENTO.ID AND OBJ.ESTADO = 1 AND OBJ.FECHA_LIMITE IS NOT NULL
	UNION 
	SELECT OBJ.NUMEXP, OBJ.FECHA_LIMITE, PROCEDIMIENTO.NOMBRE AS NOMBRE_PCD, OBJ.ID_RESP, OBJ.ID AS ID_OBJETO, 'RESOLUCIÓN ACTIVIDAD' AS DESCRIPCION, 4 AS TIPO
	FROM SPAC_FASES OBJ, SPAC_P_PROCEDIMIENTOS PROCEDIMIENTO
	WHERE OBJ.ID_PCD = PROCEDIMIENTO.ID AND OBJ.ESTADO = 1 AND OBJ.TIPO=2 AND OBJ.FECHA_LIMITE IS NOT NULL
;


CREATE VIEW SPAC_PCD_PERMISOS AS
	SELECT  ID_PCD , UID_USR, PERMISO
	FROM SPAC_SS_PERMISOS 
	UNION
	SELECT ID_OBJ, ID_RESP, PERMISO
	FROM SPAC_PERMISOS WHERE TP_OBJ=1
;


-- Vista para avisos electronicos en la que se combina la informacion de fase y tramite si existe
CREATE VIEW SPAC_V_AVISOS_ELECTRONICOS AS
	SELECT A.*, F.NOMBRE AS NOMBRE_FASE, T.NOMBRE AS NOMBRE_TRAMITE FROM SPAC_AVISOS_ELECTRONICOS A LEFT OUTER JOIN SPAC_P_FASES F 
	ON A.ID_FASE_PCD = F.ID LEFT OUTER JOIN SPAC_P_TRAMITES T 
	ON A.ID_TRAMITE_PCD = T.ID
;


--Vista para obtener las fases activas que estén en la papelera
CREATE  VIEW SPAC_WL_PROC_TRASH AS
	SELECT FASES.ID_EXP AS ID, FASES.NUMEXP, FASES.ID_PCD, FASES.ID_FASE AS ID_STAGEPCD, FASES.ID AS ID_STAGE, FASESPCD.NOMBRE AS NAME_STAGE, FASES.FECHA_INICIO AS INITDATE, FASES.FECHA_LIMITE AS LIMITDATE, FASES.ID_RESP AS RESP, FASES.TIPO
	FROM SPAC_FASES FASES, SPAC_P_FASES FASESPCD
	WHERE FASES.ID_FASE = FASESPCD.ID AND FASES.ESTADO = 5
;