--
-- Tablas de los pilotos
--
CREATE TABLE SGL_OBRAS_MENORES (
    ID INT NOT NULL,
    NUMEXP VARCHAR(30),
    TIPO_OBJETO VARCHAR(15),
    TIPO_LOCALIZADOR VARCHAR(15),
    LOCALIZADOR VARCHAR(15),
    ACTUACION_CASCO_HISTORICO VARCHAR(2),
    TIPO_FINCA VARCHAR(15),
    TIPO_SUELO VARCHAR(15),
    UBICACION_INMUEBLE VARCHAR(512),
    REFERENCIA_CATASTRAL VARCHAR(20),
    LOCALIZACION VARCHAR(15),
    DESCRIPCION TEXT,
    PRESUPUESTO_TOTAL NUMERIC(15,2),
    FECHA_INICIO DATETIME,
    FECHA_TERMINACION DATETIME,
    OCUPACION_VIA_PUBLICA VARCHAR(2)
)

CREATE TABLE SGQ_QUEJAS (
    ID INT NOT NULL,
    NUMEXP VARCHAR(30),
    ID_ORGANO_OBJETO VARCHAR(64),
    ORGANO_OBJETO VARCHAR(512),
    TIPO_OBJETO VARCHAR(10),
    LOCALIZADOR_OBJETO VARCHAR(64),
    ASUNTO TEXT,
    TIPO_ORGANO_DESTINO VARCHAR(8),
    ID_ORGANO_INFORME VARCHAR(64),
    ORGANO_INFORME VARCHAR(512)
)

CREATE TABLE SGS_SUBVENCIONES (
    ID INT NOT NULL,
    NUMEXP VARCHAR(30),
    ID_PCD INT,
    ANIO_PRESUPUESTARIO NUMERIC(4,0),
    TIPO_SUBVENCION VARCHAR(8),
    FECHA_CONVOCATORIA DATETIME,
    DENOMINACION_PROYECTO VARCHAR(120),
    RESUMEN_PROYECTO TEXT,
    FECHA_INICIO_EJECUCION DATETIME,
    FECHA_FIN_EJECUCION DATETIME,
    DURACION_PROYECTO NUMERIC(2,0),
    COLECTIVO_DESTINO VARCHAR(64),
    IMPORTE_SOLICITADO NUMERIC(13,2),
    IMPORTE_CONCEDIDO NUMERIC(13,2),
    PREVISION_GASTOS TEXT,
    IMPORTE_GASTOS NUMERIC(10,2),
    TOTAL_GASTOS NUMERIC(10,2),
    APORTACION_AYTO NUMERIC(13,2),
    APORTACION_ENTIDAD NUMERIC(13,2),
    OTRAS_APORTACIONES NUMERIC(13,2),
    TOTAL_APORTACIONES NUMERIC(13,2),
    FINALIDAD_SUBVENCION TEXT,
    OBSERVACIONES TEXT
)


-------------------
-- OBRAS MENORES --
-------------------

--
-- Tablas de validación
--

-- Tabla de validación para Tipos de Suelo
CREATE TABLE SPAC_TBL_010 (
    ID INT NOT NULL,
    VALOR VARCHAR(8),
    SUSTITUTO VARCHAR(64),
    VIGENTE INT,
    ORDEN INT
)

-- Tabla de validación para Tipos de Finca
CREATE TABLE SPAC_TBL_011 (
  	ID INT NOT NULL,
  	VALOR VARCHAR(8),
  	SUSTITUTO VARCHAR(64),
  	VIGENTE INT,
	ORDEN INT
)

-- Tabla de validación para Localización de Obras
CREATE TABLE SPAC_TBL_012 (
  	ID INT NOT NULL,
  	VALOR VARCHAR(8),
  	SUSTITUTO VARCHAR(64),
  	VIGENTE INT,
	ORDEN INT
)


------------------
-- SUBVENCIONES --
------------------

--
-- Tablas de validación
--

-- Tabla de validación para Tipos de Subvención
CREATE TABLE SPAC_TBL_013 (
  	ID INT NOT NULL,
  	VALOR VARCHAR(8),
  	SUSTITUTO VARCHAR(64),
  	VIGENTE INT,
	ORDEN INT
)