----------------
-- SECUENCIAS --
----------------
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SGL_SQ_ID_OBRAS_MENORES',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SGQ_SQ_ID_QUEJAS',0);      
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SGS_SQ_ID_SUBVENCIONES',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_SPAC_TBL_010');
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_SPAC_TBL_011');
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_SPAC_TBL_012');
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME) VALUES('SPAC_SQ_SPAC_TBL_013');