------------------------------------------------------
-- Configuración del PUBLICADOR para los prototipos --
------------------------------------------------------

--
-- Aplicación de publicación
--

UPDATE pub_aplicaciones_hitos set nombre='PUBLICADOR_SIGEM' where id=1;

--
-- Acciones de publicación
--
INSERT INTO pub_acciones (id, nombre, clase, activa, descripcion, tipo) VALUES (2, 'CT-Alta Expediente', 'ieci.tdw.ispac.ispacpublicador.business.action.consultaTelematica.AltaExpedienteAction', 1, 'Consulta Telemática - Alta de expediente', 1);
INSERT INTO pub_acciones (id, nombre, clase, activa, descripcion, tipo) VALUES (3, 'CT-Establecer Hito Actual', 'ieci.tdw.ispac.ispacpublicador.business.action.consultaTelematica.EstablecerHitoActualAction', 1, 'Consulta Telemática - Establecer Hito Actual', 1);
INSERT INTO pub_acciones (id, nombre, clase, activa, descripcion, tipo) VALUES (4, 'CT-Establecer Hito Histórico', 'ieci.tdw.ispac.ispacpublicador.business.action.consultaTelematica.EstablecerHitoHistoricoAction', 1, 'Consulta Telemática - Establecer Hito Histórico', 1);
INSERT INTO pub_acciones (id, nombre, clase, activa, descripcion, tipo) VALUES (5, 'Notificación Telemática', 'ieci.tdw.ispac.ispacpublicador.business.action.notificacionTelematica.NotificacionTelematicaAction', 1, 'Notificación Telemática', 1);
INSERT INTO pub_acciones (id, nombre, clase, activa, descripcion, tipo) VALUES (6, 'CT-Anexar Ficheros Hito Actual', 'ieci.tdw.ispac.ispacpublicador.business.action.consultaTelematica.AnexarFicherosHitoActualAction', 1, 'Consulta Telemática - Anexar Ficheros al Hito Actual', 1);
INSERT INTO pub_acciones (id, nombre, clase, activa, descripcion, tipo) VALUES (7, 'CT-Solicitud Subsanación', 'ieci.tdw.ispac.ispacpublicador.business.action.consultaTelematica.SolicitudSubsanacionAction', 1, 'Consulta Telemática - Solicitud de Subsanación', 1);
INSERT INTO pub_acciones (id, nombre, clase, activa, descripcion, tipo) VALUES (8, 'CT-Cambio Interesado Expediente', 'ieci.tdw.ispac.ispacpublicador.business.action.consultaTelematica.CambioInteresadoExpedienteAction', 1, 'Consulta Telemática - Cambio del interesado principal del expediente', 1);
INSERT INTO pub_acciones (id, nombre, clase, activa, descripcion, tipo) VALUES (9, 'CT-Cerrar Expediente', 'ieci.tdw.ispac.ispacpublicador.business.action.consultaTelematica.CerrarExpedienteAction', 1, 'Consulta Telemática - Cerrar expediente', 1);
INSERT INTO pub_acciones (id, nombre, clase, activa, descripcion, tipo) VALUES (10, 'MC-Envío e-mail', 'ieci.tdw.ispac.ispacpublicador.business.action.mensajesCortos.EnvioMailAction', 1, 'Mensajes Cortos - Envío de e-mail', 1);
INSERT INTO pub_acciones (id, nombre, clase, activa, descripcion, tipo) VALUES (11, 'MC-Envío SMS', 'ieci.tdw.ispac.ispacpublicador.business.action.mensajesCortos.EnvioSmsAction', 1, 'Mensajes Cortos - Envío de SMS', 1);
UPDATE SPAC_SQ_SEQUENCES SET sequence_id = 12 WHERE sequence_name = 'PUB_SQ_ID_ACCIONES';


--
-- Reglas de publicación
--
DECLARE @sequence_id int
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, -1, -1, -1, -1, 8, 5, 1, '<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''ASUNTO_EMAIL''>Notificación telemática/Notificacio telematica/Jakinarazpen telematikoa/Notificación telemática</attribute><attribute name=''TEXTO_EMAIL''>Notificación expediente nº ${NUMEXP}/Notificacio expedient num. ${NUMEXP}/${NUMEXP} zk.ko espedientearen jakinarazpena/Notificación expediente nº ${NUMEXP}</attribute><attribute name=''DESCRIPCION_NOTIFICACION''><labels><label locale=''es''>Dispone de una notificación correspondiente al expediente nº ${NUMEXP}. Puede usted recogerla accediendo a su buzón en la siguiente dirección: URL</label><label locale=''eu''>${NUMEXP} zk.ko espedientearen jakinarazpen bat duzu. Hura jasotzeko, postontzira sar zaitezke helbide honetan: URLa</label><label locale=''ca''>Disposeu d\u0027una notificacio corresponent a l\u0027expedient num. ${NUMEXP}. Podeu recollir-la accedint a la vostra bustia a l\u0027adreça seguent: URL</label><label locale=''gl''>Dispón dunha notificación correspondente ao expediente nº ${NUMEXP}. Pode recollela accedendo á súa caixa de correo no seguinte enderezo: URL</label></labels></attribute></attributes>', 1, 1, 1);

UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 3, 6, 0, 0, 3, 2, 1, '<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''APORTACION''>N</attribute><attribute name=''CODPRES''>1</attribute></attributes>', 1, 2, 0);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 3, 6, 0, 0, 3, 3, 1, '<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>Solicitud recibida</label><label locale=''eu''>Eskaera hartua</label><label locale=''ca''>Sol·licitud rebuda</label><label locale=''gl''>Solicitude recibida</label></labels></attribute></attributes>', 1, 3, 0);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 3, -1, -1, -1, 8, 8, 1, NULL, 1, 4, 2);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 3, 6, 5, 0, 6, 6, 1, NULL, 1, 5, 0);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 3, 7, 0, 0, 3, 3, 1, '<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>Se está estudiando su solicitud</label><label locale=''eu''>Zure eskaera estudiatzean dago</label><label locale=''ca''>S''està estudiant la seva sol·licitud</label><label locale=''gl''>Está a estudarse a súa solicitude</label></labels></attribute><attribute name=''PASO_A_HISTORICO''>S</attribute></attributes>', 1, 6, 0);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 3, 7, 8, 0, 6, 3, 1, '<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>Se le enviará una comunicación referente al expediente</label><label locale=''eu''>Espedienteari buruzko mezu bat bidaliko dizugu</label><label locale=''ca''>Se li enviarà una comunicació referent a l''expedient</label><label locale=''gl''>Enviaráselle unha comunicación referente ao expediente</label></labels></attribute><attribute name=''PASO_A_HISTORICO''>S</attribute><attribute name=''ENVIAR_DOCUMENTOS''>S</attribute></attributes>', 1, 7, 0);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 3, 8, 11, 0, 6, 3, 1, '<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>Se le enviará una comunicación referente al expediente</label><label locale=''eu''>Espedienteari buruzko mezu bat bidaliko dizugu</label><label locale=''ca''>Se li enviarà una comunicació referent a l''expedient</label><label locale=''gl''>Enviaráselle unha comunicación referente ao expediente</label></labels></attribute><attribute name=''PASO_A_HISTORICO''>S</attribute><attribute name=''ENVIAR_DOCUMENTOS''>S</attribute></attributes>', 1, 8, 0);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 3, 8, 0, 0, 4, 3, 1, '<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>Expediente finalizado</label><label locale=''eu''>Espediente bukatua</label><label locale=''ca''>Expedient finalitzat</label><label locale=''gl''>Expediente finalizado</label></labels></attribute><attribute name=''PASO_A_HISTORICO''>S</attribute></attributes>', 1, 9, 0);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 3, 0, 0, 0, 2, 9, 1, null, 1, 1, 0);

UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 4, 10, 0, 0, 3, 2, 1, '<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''APORTACION''>N</attribute><attribute name=''CODPRES''>1</attribute></attributes>', 1, 10, 0);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 4, 10, 0, 0, 3, 3, 1, '<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>Solicitud recibida</label><label locale=''eu''>Eskaera hartua</label><label locale=''ca''>Sol·licitud rebuda</label><label locale=''gl''>Solicitude recibida</label></labels></attribute></attributes>', 1, 11, 0);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 4, -1, -1, -1, 8, 8, 1, NULL, 1, 12, 2);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 4, 10, 15, 0, 5, 3, 1, '<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>Comprobando la documentación aportada</label><label locale=''eu''>Dokumentazio porturatua egiaztatzean</label><label locale=''ca''>Comprovant la documentació aportada</label><label locale=''gl''>Comprobando a documentación achegada</label></labels></attribute><attribute name=''PASO_A_HISTORICO''>S</attribute></attributes>', 1, 13, 0);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 4, 10, 15, 0, 5, 7, 1, '<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''MENSAJE_SUBSANACION''><labels><label locale=''es''>Documentos a subsanar: ${NOMBRE_DOC}.</label><label locale=''eu''>Konpontzera dokumentuak: ${NOMBRE_DOC}.</label><label locale=''ca''>Documents a esmenar: ${NOMBRE_DOC}.</label><label locale=''gl''>Documentos a emendar: ${NOMBRE_DOC}.</label></labels></attribute></attributes>', 1, 14, 0);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 4, 10, 15, 0, 6, 6, 1, NULL, 1, 15, 0);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 4, 11, 0, 0, 3, 3, 1, '<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>Se está estudiando su solicitud</label><label locale=''eu''>Zure eskaera estudiatzean dago</label><label locale=''ca''>S''està estudiant la seva sol·licitud</label><label locale=''gl''>Está a estudarse a súa solicitude</label></labels></attribute><attribute name=''PASO_A_HISTORICO''>S</attribute></attributes>', 1, 16, 0);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 4, 12, 20, 0, 6, 3, 1, '<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>Decisión sobre la solicitud</label><label locale=''eu''>Eskaeraz erabakia</label><label locale=''ca''>Decisió sobre la sol·licitud</label><label locale=''gl''>Decisión sobre a solicitude</label></labels></attribute><attribute name=''PASO_A_HISTORICO''>S</attribute><attribute name=''ENVIAR_DOCUMENTOS''>S</attribute></attributes>', 1, 17, 0);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 4, 12, 0, 0, 4, 3, 1, '<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>Expediente finalizado</label><label locale=''eu''>Espediente bukatua</label><label locale=''ca''>Expedient finalitzat</label><label locale=''gl''>Expediente finalizado</label></labels></attribute><attribute name=''PASO_A_HISTORICO''>S</attribute></attributes>', 1, 18, 0);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 4, 0, 0, 0, 2, 9, 1, null, 1, 1, 0);

UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 5, 14, 0, 0, 3, 2, 1, '<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''APORTACION''>N</attribute><attribute name=''CODPRES''>1</attribute></attributes>', 1, 19, 0);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 5, 14, 0, 0, 3, 3, 1, '<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>Solicitud recibida</label><label locale=''eu''>Eskaera hartua</label><label locale=''ca''>Sol·licitud rebuda</label><label locale=''gl''>Solicitude recibida</label></labels></attribute></attributes>', 1, 20, 0);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 5, -1, -1, -1, 8, 8, 1, NULL, 1, 21, 2);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 5, 14, 33, 0, 5, 3, 1, '<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>Comprobando la documentación aportada</label><label locale=''eu''>Dokumentazio porturatua egiaztatzean</label><label locale=''ca''>Comprovant la documentació aportada</label><label locale=''gl''>Comprobando a documentación achegada</label></labels></attribute><attribute name=''PASO_A_HISTORICO''>S</attribute></attributes>', 1, 22, 0);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 5, 14, 33, 0, 5, 7, 1, '<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''TASA_1''><tax><name>Resguardo del pago de tasa</name><labels><label locale=''es''>Resguardo del pago de tasa</label><label locale=''eu''>Tasaren ordainagiria</label><label locale=''ca''>Protegeixo del pagament de taxa</label><label locale=''gl''>Resgardo do pago de taxa</label></labels><import>1000</import><sender_entity_id>000000</sender_entity_id><self_settlement_id>200</self_settlement_id></tax></attribute><attribute name=''MENSAJE_SUBSANACION''><labels><label locale=''es''>Documentos a subsanar: ${NOMBRE_DOC}.</label><label locale=''eu''>Konpontzera dokumentuak: ${NOMBRE_DOC}.</label><label locale=''ca''>Documents a esmenar: ${NOMBRE_DOC}.</label><label locale=''gl''>Documentos a emendar: ${NOMBRE_DOC}.</label></labels></attribute><attribute name=''MENSAJE_PAGO''><labels><label locale=''es''>Durante la tramitación de su expediente ${NUMEXP} de ${NOMBREPROCEDIMIENTO} se le comunica que es necesario que acredite el pago de la tasa de ${NOMBRE_PAGO} por un valor de ${IMPORTE_PAGO} euros.</label><label locale=''eu''>${NOMBREPROCEDIMIENTO}(e)ko ${NUMEXP} espedientea bideratzen ari dela, jakinarazten zaizu ${NOMBRE_PAGO}ren tasa (${IMPORTE_PAGO} eurokoa) ordaindu izana ziurtatu behar duzula.</label><label locale=''ca''>Durant la tramitacio del vostre expedient ${NUMEXP} de ${NOMBREPROCEDIMIENTO} se us comunica que acrediteu el pagament de la taxa de ${NOMBRE_PAGO} per un valor de ${IMPORTE_PAGO} euros.</label><label locale=''gl''>Durante a tramitación do seu expediente ${NUMEXP} de ${NOMBREPROCEDIMIENTO} comunicaráselle que é necesario que acredite o pagamento da taxa de ${NOMBRE_PAGO} por un valor de ${IMPORTE_PAGO} euros.</label></labels></attribute></attributes>', 1, 23, 0);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 5, 14, 33, 0, 6, 6, 1, NULL, 1, 24, 0);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 5, 15, 0, 0, 3, 3, 1, '<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>Se está estudiando su solicitud</label><label locale=''eu''>Zure eskaera estudiatzean dago</label><label locale=''ca''>S''està estudiant la seva sol·licitud</label><label locale=''gl''>Está a estudarse a súa solicitude</label></labels></attribute><attribute name=''PASO_A_HISTORICO''>S</attribute></attributes>', 1, 25, 0);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 5, 16, 38, 0, 6, 3, 1, '<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>Decisión sobre la solicitud</label><label locale=''eu''>Eskaeraz erabakia</label><label locale=''ca''>Decisió sobre la sol·licitud</label><label locale=''gl''>Decisión sobre a solicitude</label></labels></attribute><attribute name=''PASO_A_HISTORICO''>S</attribute><attribute name=''ENVIAR_DOCUMENTOS''>S</attribute></attributes>', 1, 26, 0);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 5, 16, 0, 0, 4, 3, 1, '<?xml version=''1.0'' encoding=''ISO-8859-1''?><attributes><attribute name=''DESCRIPCION''><labels><label locale=''es''>Expediente finalizado</label><label locale=''eu''>Espediente bukatua</label><label locale=''ca''>Expedient finalitzat</label><label locale=''gl''>Expediente finalizado</label></labels></attribute><attribute name=''PASO_A_HISTORICO''>S</attribute></attributes>', 1, 27, 0);
UPDATE SPAC_SQ_SEQUENCES	SET @sequence_id = sequence_id = sequence_id + 1 WHERE sequence_name = 'PUB_SQ_ID_REGLAS';
INSERT INTO pub_reglas (id, id_pcd, id_fase, id_tramite, tipo_doc, id_evento, id_accion, id_condicion, atributos, id_aplicacion, orden, id_info) VALUES (@sequence_id, 5, 0, 0, 0, 2, 9, 1, null, 1, 1, 0);