CREATE TABLE ACTIVIDAD_CLASIFICADA (
    ACTIVIDAD VARCHAR(254),
    CLASIFICACION VARCHAR(254),
    EMPLAZAMIENTO TEXT,
    TASAS NUMERIC(14,2),
    NUMEXP VARCHAR(30) NOT NULL,
    ID INT NOT NULL,
    ORDEN NUMERIC(10,0)
)


CREATE TABLE ACTIVIDAD_NO_CLASIFICADA (
    ACTIVIDAD VARCHAR(254),
    EMPLAZAMIENTO TEXT,
    TASAS NUMERIC(14,2),
    NUMEXP VARCHAR(30) NOT NULL,
    ID INT NOT NULL,
    ORDEN NUMERIC(10,0)
)


CREATE TABLE CAMB_TITULAR_LA (
    ACTIVIDAD VARCHAR(254),
    EMPLAZAMIENTO TEXT,
    TASAS NUMERIC(14,2),
    NUMEXP VARCHAR(30) NOT NULL,
    ID INT NOT NULL,
    FECHA_LICENCIA DATETIME,
    FECHA_APROBACION DATETIME,
    DENOMINACION VARCHAR(254),
    ORDEN NUMERIC(10,0)
)


CREATE TABLE CERT_URBANISTICO (
    FECHA_EMISION DATETIME,
    SITUACION VARCHAR(500),
    TECNICO_NOMBRE VARCHAR(100),
    TECNICO_CARGO VARCHAR(50),
    NUMEXP VARCHAR(30) NOT NULL,
    ID INT NOT NULL,
    ORDEN NUMERIC(10,0)
)


CREATE TABLE CLASIFICACION_ACTIVIDADES (
    ID INT NOT NULL,
    VALOR VARCHAR(20),
    SUSTITUTO VARCHAR(500),
    VIGENTE NUMERIC(1,0),
    ORDEN NUMERIC(10,0)
)


CREATE TABLE CONTRATO (
    ID INT NOT NULL,
    NUMEXP VARCHAR(30) NOT NULL,
    TIPO VARCHAR(100),
    FORMA_ADJUDICACION VARCHAR(100),
    PRESUPUESTO_MAXIMO NUMERIC(20,2),
    APLICACION VARCHAR(250),
    PRECIO_ADJUDICACION NUMERIC(20,2),
    PLAZO_EJECUCION INT,
    UD_PLAZO VARCHAR(1),
    GARANTIA_PROVISIONAL NUMERIC(20,2),
    GARANTIA_DEFINITIVA NUMERIC(20,2),
    CLASIFICACION VARCHAR(500),
    FECHA_FIN_EJECUCION DATETIME,
    FECHA_FIN_GARANTIA DATETIME,
    ORDEN NUMERIC(10,0)
)


CREATE TABLE DATOS_TARJETA_MINUS (
    TIPO_TARJETA VARCHAR(100),
    FECHA_CADUCIDAD DATETIME,
    NUMEXP VARCHAR(30) NOT NULL,
    ID INT NOT NULL,
    ORDEN NUMERIC(10,0)
)


CREATE TABLE FORMA_ADJUDICACION (
    ID INT NOT NULL,
    VALOR VARCHAR(100),
    VIGENTE NUMERIC(1,0),
    ORDEN NUMERIC(10,0)
)


CREATE TABLE LOTES (
    ID INT NOT NULL,
    NUMEXP VARCHAR(30) NOT NULL,
    NOMBRE VARCHAR(250),
    PRESUPUESTO NUMERIC(20,2),
    ORDEN NUMERIC(10,0)
)


CREATE TABLE OBRA_MENOR (
    ID INT NOT NULL,
    NUMEXP VARCHAR(30) NOT NULL,
    OBRA_SOLICITADA TEXT,
    SITUACION_OBRA VARCHAR(500),
    PROMOTOR VARCHAR(100),
    DIRECTOR_OBRA VARCHAR(100),
    DIRECTOR_EJECUCION VARCHAR(100),
    PRESUPUESTO_PROMOTOR NUMERIC(14,2),
    "PRESUPUESTO_TÉCNICO_MUNICIPAL" NUMERIC(14,2),
    AUTOR_PROYECTO VARCHAR(100),
    USO_OBRA VARCHAR(200),
    CLASIFICACION_SUELO VARCHAR(100),
    CUALIFICACION_SUELO VARCHAR(100),
    IMPORTE_TASAS NUMERIC(14,2),
    IMPORTE_ICIO NUMERIC(14,2),
    TOTAL_LIQUIDACION NUMERIC(14,2),
    ORDEN NUMERIC(10,0)
)


CREATE TABLE OFERTA (
    ID_LICITADOR INT,
    IMPORTE NUMERIC(20,2),
    PLAZO INT,
    UD_PLAZO VARCHAR(1),
    NUMEXP VARCHAR(30) NOT NULL,
    ID INT NOT NULL,
    ORDEN NUMERIC(10,0)
)


CREATE TABLE REBAJE_ACERA (
    ID INT NOT NULL,
    VALOR VARCHAR(100),
    VIGENTE NUMERIC(1,0),
    ORDEN NUMERIC(10,0)
)


CREATE TABLE RECLAMACION (
    ID INT NOT NULL,
    NUMEXP VARCHAR(30) NOT NULL,
    TIPO VARCHAR(64),
    DESCRIPCION TEXT,
    DESTINATARIO VARCHAR(32),
    ACEPTADA VARCHAR(2),
    ORDEN NUMERIC(10,0)
)


CREATE TABLE SANCION (
    INSTRUCTOR VARCHAR(254),
    CALIFICACION VARCHAR(100),
    IMPORTE NUMERIC(20,2),
    GRADO VARCHAR(100),
    INFRACCION TEXT,
    HECHOS TEXT,
    ACTUACION TEXT,
    NUMEXP VARCHAR(30) NOT NULL,
    ID INT NOT NULL,
    ORDEN NUMERIC(10,0)
)


CREATE TABLE TIPO_CONTRATO (
    ID INT NOT NULL,
    VALOR VARCHAR(100),
    VIGENTE NUMERIC(1,0),
    ORDEN NUMERIC(10,0)
)


CREATE TABLE TIPO_TECNICO (
    ID INT NOT NULL,
    VALOR VARCHAR(10),
    SUSTITUTO VARCHAR(64),
    VIGENTE NUMERIC(1,0),
    ORDEN NUMERIC(10,0)
)


CREATE TABLE TIPO_VADO (
    ID INT NOT NULL,
    VALOR VARCHAR(100),
    VIGENTE NUMERIC(1,0),
    ORDEN NUMERIC(10,0)
)


CREATE TABLE VADO (
    NUMLICENCIA VARCHAR(100),
    UBICACION VARCHAR(250),
    TIPO VARCHAR(100),
    LARGOENTRADA NUMERIC(14,2),
    ANCHOACERA NUMERIC(14,2),
    SUPERFICIEACERA NUMERIC(14,2),
    SUPERFICIELOCAL NUMERIC(14,2),
    ACTIVIDAD VARCHAR(250),
    REBAJE VARCHAR(100),
    TASAS NUMERIC(14,2),
    NUMEXP VARCHAR(30) NOT NULL,
    ID INT NOT NULL,
    NUMVEHICULOS NUMERIC(20,0),
    ORDEN NUMERIC(10,0)
)


CREATE TABLE VISTO_BUENO (
    ID INT NOT NULL,
    NUMEXP VARCHAR(30) NOT NULL,
    TASK_NAME VARCHAR(250),
    VB VARCHAR(2),
    TASK_ID INT,
    STAGE_NAME VARCHAR(250),
    ID_TRAM_EXP INT,
    OBSERVACIONES TEXT,
    ORDEN NUMERIC(10,0)
)


CREATE TABLE VLDTBL_CALIF_SUELO (
    ID INT NOT NULL,
    VALOR VARCHAR(10),
    SUSTITUTO VARCHAR(100),
    VIGENTE NUMERIC(1,0),
    ORDEN NUMERIC(10,0)
)


CREATE TABLE VLDTBL_CLASIF_SUELO (
    ID INT NOT NULL,
    VALOR VARCHAR(10),
    SUSTITUTO VARCHAR(100),
    VIGENTE NUMERIC(1,0),
    ORDEN NUMERIC(10,0)
)


CREATE TABLE VLDTBL_SAN_CALIFICACION (
    ID INT NOT NULL,
    VALOR VARCHAR(100),
    VIGENTE NUMERIC(1,0),
    ORDEN NUMERIC(10,0)
)


CREATE TABLE VLDTBL_SAN_GRADO (
    ID INT NOT NULL,
    VALOR VARCHAR(100),
    VIGENTE NUMERIC(1,0),
    ORDEN NUMERIC(10,0)
)


CREATE TABLE VLDTBL_TIPO_DESTI (
    ID INT NOT NULL,
    VALOR VARCHAR(32),
    VIGENTE NUMERIC(1,0),
    ORDEN NUMERIC(10,0)
)


CREATE TABLE VLDTBL_TIPO_RECLAM (
    ID INT NOT NULL,
    VALOR VARCHAR(64),
    VIGENTE NUMERIC(1,0),
    ORDEN NUMERIC(10,0)
)


CREATE TABLE VLDTBL_TIPO_TARJETA (
    ID INT NOT NULL,
    VALOR VARCHAR(100),
    VIGENTE NUMERIC(1,0),
    ORDEN NUMERIC(10,0)
)
