--
-- Secuencias
--

INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_DATOS_TARJETA_MINUS',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_FORMA_ADJUDICACION',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_ID_ACTIVIDAD_CLASIFICA',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_ID_ACTIVIDAD_NO_CLASIF',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_ID_CAMB_TITULAR_LA',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_ID_CERT_URBANISTICO',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_ID_CLASIFICACION_ACTIV',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_ID_CONTRATO',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_ID_LOTES',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_ID_OBRA_MENOR',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_ID_OFERTA',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_ID_SANCION',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_ID_VADO',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_ID_VLDTBL_SAN_CALIFICA',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_ID_VLDTBL_SAN_GRADO',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_REBAJE_ACERA',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_RECLAMACION',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_TIPO_CONTRATO',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_TIPO_TECNICO',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_TIPO_VADO',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_VISTO_BUENO',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_VLDTBL_CALIF_SUELO',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_VLDTBL_CLASIF_SUELO',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_VLDTBL_TIPO_DESTI',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_VLDTBL_TIPO_RECLAM',0);
INSERT INTO SPAC_SQ_SEQUENCES (SEQUENCE_NAME, SEQUENCE_ID) VALUES('SPAC_SQ_VLDTBL_TIPO_TARJETA',0);

