--/***************************/
--/* Versión 4.2             */
--/***************************/

    -- Insertar la versión actual de bd
    INSERT INTO AGINFOSISTEMA (AUTID,NOMBRE,VALOR,FECHAACTUALIZACION) VALUES (SEQ_INFO.NextVal,'VERSIONBD','4.0->4.2',SYSDATE);

    -- Establecer el id de motivo en consultas como nulo
    ALTER TABLE ASGPCONSULTA MODIFY IDMOTIVO VARCHAR2(32 CHAR) NULL;

    -- Establecer el motivo en consultas como nulo
    ALTER TABLE ASGPCONSULTA MODIFY MOTIVO VARCHAR2(32 CHAR) NULL;

    -- Establecer el id de motivo en préstamos como nulo
    ALTER TABLE ASGPPRESTAMO MODIFY IDMOTIVO VARCHAR2(32 CHAR) NULL;
COMMIT;

--/*************************/
--/* Versión 4.3           */
--/*************************/

	-- Insertar la versión actual de bd
	INSERT INTO AGINFOSISTEMA (AUTID,NOMBRE,VALOR,FECHAACTUALIZACION) VALUES (SEQ_INFO.NextVal,'VERSIONBD','4.2->4.3',SYSDATE);

	--Añadir columna MARCASBLOQUEO
	ALTER TABLE ASGTUNIDADDOCRE ADD (MARCASBLOQUEO NUMBER DEFAULT 0 NOT NULL );

	--Añadir columna MARCASBLOQUEO
	ALTER TABLE ASGFUNIDADDOC ADD (MARCASBLOQUEO NUMBER DEFAULT 0 NOT NULL );
COMMIT;



--/*************************/
--/* Versión 4.5           */
--/*************************/

	-- Insertar la versión actual de bd
	INSERT INTO AGINFOSISTEMA (AUTID,NOMBRE,VALOR,FECHAACTUALIZACION) VALUES (SEQ_INFO.NextVal,'VERSIONBD','4.3->4.5',SYSDATE);


	-- Crear tabla de Edificios
	CREATE TABLE ASGSEDIFICIO (
     ID            VARCHAR2 (32 CHAR) NOT NULL,
     NOMBRE        VARCHAR2 (64 CHAR) NOT NULL,
     UBICACION     VARCHAR2 (254 CHAR),
     IDARCHIVO     VARCHAR2 (32 CHAR) NOT NULL
	);

	-- Tabla: ASGSEDIFICIO
	CREATE UNIQUE INDEX ASGSEDIFICIO1 ON ASGSEDIFICIO(ID) TABLESPACE &1;
	CREATE UNIQUE INDEX ASGSEDIFICIO2 ON ASGSEDIFICIO(NOMBRE) TABLESPACE &1;

	-- Crear tabla de Salas
	CREATE TABLE ASGSSALA (
     ID              		VARCHAR2 (32 CHAR) NOT NULL,
     NOMBRE          		VARCHAR2 (64 CHAR) NOT NULL,
     DESCRIPCION     		VARCHAR2 (254 CHAR),
     IDEDIFICIO      		VARCHAR2 (32 CHAR) NOT NULL,
     EQUIPOINFORMATICO 	CHAR (1 CHAR) NOT NULL
	);

	-- Tabla: ASGSSALA
	CREATE UNIQUE INDEX ASGSSALA1 ON ASGSSALA(ID) TABLESPACE &1;
	CREATE UNIQUE INDEX ASGSSALA2 ON ASGSSALA(IDEDIFICIO,NOMBRE) TABLESPACE &1;
	CREATE INDEX ASGSSALA3 ON ASGSSALA(IDEDIFICIO) TABLESPACE &1;

	-- Crear tabla de Mesas
	CREATE TABLE ASGSMESA (
     ID              VARCHAR2 (32 CHAR) NOT NULL,
     CODIGO          VARCHAR2 (64 CHAR) NOT NULL,
     NUMORDEN        NUMBER NOT NULL,
     IDSALA          VARCHAR2 (32 CHAR) NOT NULL,
     ESTADO          CHAR (1 CHAR) NOT NULL,
     FECHAESTADO     DATE NOT NULL,
     IDUSRCSALA      VARCHAR2 (32 CHAR)
	);

	-- Tabla: ASGSMESA
	CREATE INDEX ASGSMESA1 ON ASGSMESA(IDSALA) TABLESPACE &1;
	CREATE UNIQUE INDEX ASGSMESA2 ON ASGSMESA(IDSALA,CODIGO) TABLESPACE &1;
	CREATE UNIQUE INDEX ASGSMESA3 ON ASGSMESA(IDSALA,NUMORDEN) TABLESPACE &1;
	CREATE INDEX ASGSMESA4 ON ASGSMESA(ESTADO) TABLESPACE &1;

	-- Crear tabla de usuarios investigadores de consulta de sala
	CREATE TABLE ASGSUSRCSALA (
     ID	 	  	  			VARCHAR2 (32 CHAR) NOT NULL,
     TIPODOCIDENTIFICACION     NUMBER NOT NULL,
     NUMDOCIDENTIFICACION		VARCHAR2 (32 CHAR) NOT NULL,
     NOMBRE			  	    VARCHAR2 (64 CHAR) NOT NULL,
     APELLIDOS			  	    VARCHAR2 (254 CHAR) NOT NULL,
     NACIONALIDAD	   	  	    VARCHAR2 (64 CHAR),
     TELEFONOS					VARCHAR2 (128 CHAR),
     EMAIL						VARCHAR2 (128 CHAR),
     DIRECCION		            VARCHAR2 (254 CHAR),
     FECHAALTA				    DATE NOT NULL,
     VIGENTE					CHAR (1 CHAR) NOT NULL,
     IDSCAUSR					VARCHAR2 (32 CHAR)
	);

	-- Crear índices de la tabla usuarios investigadores
	CREATE UNIQUE INDEX ASGSUSRCSALA1 ON ASGSUSRCSALA(ID) TABLESPACE &1;
	CREATE INDEX ASGSUSRCSALA2 ON ASGSUSRCSALA(NUMDOCIDENTIFICACION) TABLESPACE &1;
	CREATE INDEX ASGSUSRCSALA3 ON ASGSUSRCSALA(VIGENTE) TABLESPACE &1;

	-- Crear tabla relación usuarios consulta y archivos
	CREATE TABLE ASGSUSRCSARCH (
     IDUSRCSALA  	  VARCHAR2 (32 CHAR) NOT NULL,
     IDARCHIVO       VARCHAR2 (64 CHAR) NOT NULL
	);

	-- Crear índices de la tabla de relación entre usuarios y archivos de consulta
	CREATE UNIQUE INDEX ASGSUSRCSARCH1 ON ASGSUSRCSARCH(IDUSRCSALA,IDARCHIVO) TABLESPACE &1;
	CREATE INDEX ASGSUSRCSARCH2 ON ASGSUSRCSARCH(IDUSRCSALA) TABLESPACE &1;

	-- Crear tabla de registro de consultas
	CREATE TABLE ASGSREGCSALA (
     ID		  	  		VARCHAR2 (32 CHAR) NOT NULL,
     IDUSRCSALA  	  		VARCHAR2 (32 CHAR) NOT NULL,
     FENTRADA				DATE NOT NULL,
     FSALIDA				DATE,
     NUMDOCIDENTIFICACION	VARCHAR2 (32 CHAR) NOT NULL,
     NOMBREAPELLIDOS		VARCHAR2 (254 CHAR) NOT NULL,
     IDSCAUSR	  	  		VARCHAR2 (32 CHAR),
     IDARCHIVO	  	  		VARCHAR2 (32 CHAR) NOT NULL,
     MESAASIGNADA			VARCHAR2 (254 CHAR) NOT NULL
	);

	-- Crear índices de la tabla de registro de consultas
	CREATE UNIQUE INDEX ASGSREGCSALA1 ON ASGSREGCSALA(ID) TABLESPACE &1;
	CREATE INDEX ASGSREGCSALA2 ON ASGSREGCSALA(IDUSRCSALA) TABLESPACE &1;
	CREATE INDEX ASGSREGCSALA3 ON ASGSREGCSALA(NUMDOCIDENTIFICACION) TABLESPACE &1;

	--Añadir columna IDUSRCSALA
	ALTER TABLE ASGPCONSULTA ADD IDUSRCSALA VARCHAR2(32 CHAR);

	--Añadir columna IDUSRCSALA a la tabla de TEMAS
	ALTER TABLE ASGPTEMA ADD IDUSRCSALA VARCHAR2(32 CHAR);

	--Añadir columnaS CONREENCAJADO E IDFORMATORE a la tabla de relaciones de entrega
	ALTER TABLE ASGTRENTREGA ADD CONREENCAJADO VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL;
	ALTER TABLE ASGTRENTREGA ADD IDFORMATORE VARCHAR2(32 CHAR);

	--Añadir columna IDUIREEACR a la tabla de huecos
	ALTER TABLE ASGDHUECO ADD IDUIREEACR VARCHAR2(32 CHAR);

	--Crear la tabla de unidades de instalación transferencias entre archivo con reencajado
	CREATE TABLE ASGTUIREEACR (
     ID			  VARCHAR2 (32 CHAR)  NOT NULL,
     IDRELENTREGA    VARCHAR2 (32 CHAR)  NOT NULL,
     IDUIDEPOSITO    VARCHAR2 (32 CHAR),
     SIGNATURAUI     VARCHAR2 (16 CHAR),
     IDFORMATO       VARCHAR2 (32 CHAR) NOT NULL,
     ORDEN			  NUMBER NOT NULL,
     ESTADOCOTEJO 	  NUMBER(1) DEFAULT 1 NOT NULL,
     NOTASCOTEJO	  VARCHAR2 (256 CHAR),
     DEVOLUCION	  CHAR (1 CHAR) DEFAULT 'N',
     DESCRIPCION	  VARCHAR2 (256 CHAR)
	);

	--Crear la tabla de unidades documentales en unidad de instalacion de transferencias
	--entre archivos con reencajado
	CREATE TABLE ASGTUDOCENUIREEACR (
     ID			  VARCHAR2 (32 CHAR)  NOT NULL,
     IDUDOCORIGEN    VARCHAR2 (32 CHAR)  NOT NULL,
     IDRELENTREGA    VARCHAR2 (32 CHAR)  NOT NULL,
     IDUNIDADDOC     VARCHAR2 (32 CHAR)  NOT NULL,
     IDUIREEACR	  VARCHAR2 (32 CHAR),
     ASUNTO		  VARCHAR2 (1024 CHAR) NOT NULL,
     UDOCCOMPLETA	  VARCHAR2 (1 CHAR) NOT NULL,
     SIGNATURAUDOC   VARCHAR2 (32 CHAR),
     POSUDOCENUI     NUMBER,
     NUMEXP          VARCHAR2 (256 CHAR),
     NUMPARTE        NUMBER,
     FECHAINI        VARCHAR2 (64 CHAR),
     FECHAFIN        VARCHAR2 (64 CHAR),
     SIGNATURAUDOCORIGEN VARCHAR2 (32 CHAR),
     DESCRIPCION	  VARCHAR2 (256 CHAR)
	);

	--Tabla de unidades documentales originales en el reencajado
	CREATE TABLE ASGTUDOCREEACR (
     ID			  VARCHAR2 (32 CHAR)  NOT NULL,
     IDRELENTREGA    VARCHAR2 (32 CHAR)  NOT NULL,
     IDUNIDADDOC     VARCHAR2 (32 CHAR)  NOT NULL,
     SIGNATURAUDOC	  VARCHAR2 (32 CHAR)  NOT NULL,
     IDUIDEPOSITO	  VARCHAR2 (32 CHAR)  NOT NULL,
     SIGNATURAUI	  VARCHAR2 (16 CHAR)  NOT NULL
	);

	-- Tabla: ASGTUIREEACR
	CREATE UNIQUE INDEX ASGTUIREEACR1 ON ASGTUIREEACR (ID) TABLESPACE &1;
	CREATE INDEX ASGTUIREEACR2 ON ASGTUIREEACR (IDRELENTREGA) TABLESPACE &1;

	-- Tabla: ASGTUDOCENUIREEACR
	CREATE UNIQUE INDEX ASGTUDOCENUIREEACR1 ON ASGTUDOCENUIREEACR (ID) TABLESPACE &1;
	CREATE INDEX ASGTUDOCENUIREEACR2 ON ASGTUDOCENUIREEACR (IDUDOCORIGEN) TABLESPACE &1;
	CREATE INDEX ASGTUDOCENUIREEACR3 ON ASGTUDOCENUIREEACR (IDRELENTREGA) TABLESPACE &1;
	CREATE INDEX ASGTUDOCENUIREEACR4 ON ASGTUDOCENUIREEACR (IDUNIDADDOC) TABLESPACE &1;
	CREATE INDEX ASGTUDOCENUIREEACR5 ON ASGTUDOCENUIREEACR (IDUIREEACR) TABLESPACE &1;
	CREATE INDEX ASGTUDOCENUIREEACR6 ON ASGTUDOCENUIREEACR (IDRELENTREGA,IDUNIDADDOC) TABLESPACE &1;

	-- Tabla: ASGTUDOCREEACR
	CREATE UNIQUE INDEX ASGTUDOCREEACR1 ON ASGTUDOCREEACR (ID) TABLESPACE &1;
	CREATE INDEX ASGTUDOCREEACR2 ON ASGTUDOCREEACR (IDRELENTREGA) TABLESPACE &1;
	CREATE INDEX ASGTUDOCREEACR3 ON ASGTUDOCREEACR (IDRELENTREGA,IDUNIDADDOC) TABLESPACE &1;

COMMIT;


--/*************************/
--/* Versión 4.7           */
--/*************************/

INSERT INTO AGINFOSISTEMA (AUTID,NOMBRE,VALOR,FECHAACTUALIZACION) VALUES (SEQ_INFO.NextVal,'VERSIONBD','4.5->4.7',SYSDATE);

--Catalogo de Tablas Temporales
CREATE TABLE ASGFCTLGTBLTMP(
	ID NUMERIC(5)NOT NULL,
	NOMBRETABLA VARCHAR2(16 CHAR) NOT NULL,
	IDUSUARIO VARCHAR2(32 CHAR),
	ESTADO NUMERIC(1) default 0,
	FECHA DATE
);

CREATE UNIQUE INDEX ASGFCTLGTBLTMP1 ON ASGFCTLGTBLTMP(ID) TABLESPACE &1;
CREATE UNIQUE INDEX ASGFCTLGTBLTMP2 ON ASGFCTLGTBLTMP(NOMBRETABLA) TABLESPACE &1;

CREATE UNIQUE INDEX ASGFFONDO2 ON ASGFFONDO(CODARCHIVO,IDENTPRODUCTORA) TABLESPACE &1;

COMMIT;

--/*************************/
--/* Versión 4.7 > 4.8     */
--/*************************/

INSERT INTO AGINFOSISTEMA (AUTID,NOMBRE,VALOR,FECHAACTUALIZACION) VALUES (SEQ_INFO.NextVal,'VERSIONBD','4.7->4.8',SYSDATE);


--Fecha devolución en prorroga
ALTER TABLE ASGPPRORROGA ADD (FECHAFINPRORROGA DATE);

--Motivo por el cual se solicita la prorroga
ALTER TABLE ASGPPRORROGA ADD (MOTIVOPRORROGA VARCHAR2(512 CHAR));

DROP INDEX ASGFELIMSELUDOC1;
DROP INDEX ASGFELIMSELUDOC2;

--Modificar el nombre de la tabla ASGFELIMSELUDOC por ASGFELIMUDOCCONS
RENAME ASGFELIMSELUDOC TO ASGFELIMUDOCCONS;

-- Tabla: ASGFELIMSELUDOC
CREATE INDEX ASGFELIMUDOCCONS1 ON ASGFELIMUDOCCONS (IDELIMINACION) TABLESPACE &1;
CREATE INDEX ASGFELIMUDOCCONS2 ON ASGFELIMUDOCCONS (IDUDOC) TABLESPACE &1;


CREATE TABLE ASGFELIMSELUDOC(
    IDELIMINACION VARCHAR2(32 CHAR) NOT NULL,
    IDUDOC VARCHAR2(32 CHAR) NOT NULL,
    IDFONDO VARCHAR2(32 CHAR),
    CODREFERENCIA VARCHAR2(1024 CHAR),
    CODIGO VARCHAR2(128 CHAR),
    SIGNATURAUDOC VARCHAR2(32 CHAR),
    EXPEDIENTEUDOC VARCHAR2(256 CHAR),
    TITULO VARCHAR2(1024 CHAR),
    CODSISTPRODUCTOR VARCHAR2(1 CHAR6),
    TIPODOCUMENTAL VARCHAR2(254 CHAR),
    IDUINSTALACION VARCHAR2(32 CHAR),
    UBICACION VARCHAR2(512 CHAR),
    FECHAINIUDOC DATE,
    FECHAFINUDOC DATE,
    NUMERO VARCHAR2(10 CHAR)
);

-- Tabla: ASGFELIMSELUDOC
CREATE INDEX ASGFELIMSELUDOC1 ON ASGFELIMSELUDOC (IDELIMINACION) TABLESPACE &1;
CREATE INDEX ASGFELIMSELUDOC2 ON ASGFELIMSELUDOC (IDUDOC) TABLESPACE &1;

-- Tabla: ASGFUNIDADDOC
CREATE INDEX ASGFUNIDADDOC4 ON ASGFUNIDADDOC(IDFONDO) TABLESPACE &1;

--/*************************/
--/* Versión 4.8 > 5.0     */
--/*************************/

INSERT INTO AGINFOSISTEMA (AUTID,NOMBRE,VALOR,FECHAACTUALIZACION) VALUES (SEQ_INFO.NextVal,'VERSIONBD','4.8->5.0',SYSDATE);

--Renombrar IDLVOLPREF a IDREPECMPREF
ALTER TABLE ADCTLGLISTAD RENAME COLUMN IDLVOLPREF TO IDREPECMPREF;

--Renombrar IDLVOL a IDREPECM
ALTER TABLE ADDESCRIPTOR RENAME COLUMN IDLVOL TO IDREPECM;

--Renombrar IDLVOL a IDREPECM
ALTER TABLE ASGFELEMENTOCF RENAME COLUMN IDLVOL TO IDREPECM;

--Renombrar IDLVOLPREF a IDREPECMPREF
ALTER TABLE ASGFNIVELCF RENAME COLUMN IDLVOLPREF TO IDREPECMPREF;

--Renombrar INFOFICHAUDOCLVOL a INFOFICHAUDOCREPECM
ALTER TABLE ASGFSERIE RENAME COLUMN INFOFICHAUDOCLVOL TO INFOFICHAUDOCREPECM;

--Añadir campo IdRepEcm
ALTER TABLE ADOCDOCUMENTODESCR ADD IDREPECM VARCHAR2(32 CHAR);

--Añadir campo IdRepEcm
ALTER TABLE ADOCDOCUMENTOCF ADD IDREPECM VARCHAR2(32 CHAR);
--Añadir campo IdRepEcm
ALTER TABLE ADPCDOCUMENTOVIT ADD IDREPECM VARCHAR2(32 CHAR);

--Cambiar Tamaño de IDFICH a 128
ALTER TABLE ADPCDOCUMENTOVIT MODIFY IDFICH	VARCHAR2(128 CHAR);

--Añadir el campo subtiponivel
ALTER TABLE ADFICHA ADD (SUBTIPONIVEL INTEGER DEFAULT 0 NOT NULL);

--Actualizar los valores de subtiponivel
UPDATE ADFICHA SET SUBTIPONIVEL=61 WHERE ID='1';
UPDATE ADFICHA SET SUBTIPONIVEL=62 WHERE ID='6';

--Nuevo Índice por etiquetaxml en campo tabla
CREATE UNIQUE INDEX ADCAMPOTBL5 ON ADCAMPOTBL (ETIQUETAXML) TABLESPACE &1;

UPDATE ADCAMPODATO SET ETIQUETAXML = 'Documento_Fisico_Descripcion' WHERE ID='43' AND ETIQUETAXML = 'Descripcion';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Documento_Electronico_Descripcion' WHERE ID='50' AND ETIQUETAXML = 'Descripcion';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Identificacion' WHERE ID='1' AND ETIQUETAXML = 'Identificador';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Identificador_Recurso' WHERE ID='131' AND ETIQUETAXML = 'Identificador';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Entidad_Relacionada_Nombre' WHERE ID='114' AND ETIQUETAXML = 'Nombre';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Documento_Fisico_Nombre' WHERE ID='19' AND ETIQUETAXML = 'Nombre';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Productor_Nombre' WHERE ID='34' AND ETIQUETAXML = 'Nombre';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Documento_Electronico_Nombre' WHERE ID='49' AND ETIQUETAXML = 'Nombre';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Entidad_Relacionada_Tipo_Relacion' WHERE ID='115' AND ETIQUETAXML = 'Tipo_Relacion';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Naturaleza_Relacion' WHERE ID='133' AND ETIQUETAXML = 'Tipo_Relacion';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Interesado_Validado' WHERE ID='12' AND ETIQUETAXML = 'Validado';
UPDATE ADCAMPODATO SET ETIQUETAXML = 'Emplazamiento_Validado' WHERE ID='212' AND ETIQUETAXML = 'Validado';

--Nuevo Índice por etiquetaxml en campo dato
CREATE UNIQUE INDEX ADCAMPODATO6 ON ADCAMPODATO (ETIQUETAXML) TABLESPACE &1;

--Modificado el tamaño del nombre del formato
ALTER TABLE ADFMTFICHA MODIFY NOMBRE VARCHAR(128 CHAR) NOT NULL;


--Modificar el NUMORDEN de para que no tenga tamaño fijo
ALTER TABLE ASGDDEPOSITO MODIFY NUMORDEN NUMBER NOT NULL;
ALTER TABLE ASGDELEMNOASIG MODIFY NUMORDEN NUMBER NOT NULL;
ALTER TABLE ASGDSIGNUMORDEN MODIFY NUMORDEN NUMBER NOT NULL;

ALTER TABLE ASGTRENTREGA MODIFY ESTADO NUMBER(2) NOT NULL;


--Nuevo Rol para el servicio web de transferencias
INSERT INTO ASCAROL (ID,NOMBRE, TIPOMODULO,DESCRIPCION)
VALUES('ID_ROL_WS_TRANSFERENCIAS','Servicio Web de Transferencias de Expedientes','2','Permisos necesarios para la ejecución del servicio web de transferencias');

-- Servicio Web de Transferencias

--Ampliado de Elaboración de Transferencias Ordinarias
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,201);

--Ubicación de Relaciones de Entrega
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,207);

-- Consulta de Cuadro de Clasificación
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,500);

--Solicitud de Alta de Serie
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,501);

-- Gestor de Serie
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,502);

-- Gestión de Solicitudes de Serie
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,503);

-- Creación en el Cuadro de Clasificación
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,505);

-- Consulta de Descripción en el Cuadro de Clasificación
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,600);

-- Edición de Descripción en el Cuadro de Clasificación
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,601);

-- Administración de Descripción
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,606);

-- Uso de Ficha Descriptiva en Altas/Relaciones
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,607);

--Administración de Usuarios, Órganos, Grupos y Perfiles
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,701);

-- Consulta de Documentos Electrónicos
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,900);

--Edición de Documentos Electrónicos
INSERT INTO ASCAPERMGENROL (IDROL, TIPOMODULO, PERM)
VALUES('ID_ROL_WS_TRANSFERENCIAS',2,901);

--Tabla de Firmas
INSERT INTO ADCAMPOTBL (ID,NOMBRE,TIPONORMA,IDAREA,ETIQUETAXML, ETIQXMLFILA)
VALUES ('105','Firmas',1,'3','Firmas','Firma');

--Norma ENI
INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1001','Versión NTI',1,'1','3',NULL,NULL,'Version_NTI');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1002','Estado',1,'1','3',NULL,NULL,'Estado');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1003','Tipo de Firma',1,'1','3','105',1,'Tipo_Firma');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1004','Valor_CSV',2,'1','3','105',2,'Valor_CSV');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1005','Definición de Generación CSV',1,'1','3','105',3,'Definicion_Generacion_CSV');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1006','Identificador interno Firma',1,'1','3','105',4,'Id_Interno_Firma');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1011','Documento Electrónico: Versión NTI',1,'1','3','6',3, 'Documento_Electronico_Version_NTI');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1012','Documento Electrónico: Órgano',5,'1','3','6',4,'Documento_Electronico_Organo');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1013','Documento Electrónico: Fecha de Captura',3,'1','3','6',5,'Documento_Electronico_Fecha_Captura');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1014','Documento Electrónico: Origen',1,'1','3','6',6,'Documento_Electronico_Origen');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1015','Documento Electrónico: Estado Elaboración',1,'1','3','6',7,'Documento_Electronico_Estado_Elaboracion');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1016','Documento Electrónico: Nombre Formato',1,'1','3','6',8,'Documento_Electronico_Nombre_Formato');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1017','Documento Electrónico: Tipo Documental',1,'1','3','6',9,'Documento_Electronico_Tipo_Documental');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1018','Documento Electrónico: Tipo Firma',1,'1','3','6',10,'Documento_Electronico_Tipo_Firma');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1019','Documento Electrónico: Valor CSV',2,'1','3','6',11,'Documento_Electronico_Valor_CSV');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1020','Documento Electrónico: Definición Generación CSV',2,'1','3','6',12,'Documento_Electronico_Definicion_Generacion_CSV');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1021','Documento Electrónico: Identificador Documento Origen',1,'1','3','6',13,'Documento_Electronico_Identificador_Documento_Origen');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1022','Documento Electrónico: Id Interno',1,'1','3','6',14,'Documento_Electronico_Id_Interno');

INSERT INTO ADCAMPODATO(ID,NOMBRE,TIPO,TIPONORMA,IDAREA,IDTBLPADRE,POSENTBL,ETIQUETAXML)
VALUES('1023','Documento Electrónico: Identificador interno Firma',1,'1','3','6',15,'Documento_Electronico_Id_Interno_Firma');
